[short="Testimony of Balby Monthly Meeting"]
== A Testimony

[.blurb]
=== Of Balby Monthly Meeting in the County of York, concerning Daniel Wheeler deceased.

Our beloved friend Daniel Wheeler was the youngest son
of William and Sarah Wheeler of Conduit-street,
Hanoversquare, London; and was born there the 27th day of Eleventh Month, 1771.

His parents were rather above the middle rank in society,
and being consistent members of the Established church,
were strict in conforming to its rites and ceremonies,
punctual in attending their place of worship,
and careful to train up their children to devotional exercises.

Before he was twelve years old,
he was deprived of parental restraint by the death of his father and mother;
and was placed at a school at Fulham, for the purpose of learning navigation,
to prepare him for his future seafaring life.

Thus left an orphan,
through the interest of a relative he was entered on
the King`'s books as midshipman at an early age:
while he was preparing for the service, and before he had completed his thirteenth year,
circumstances led to the breaking up of the family circle,
giving rise to a long separation from his brothers and sisters,
to whom he was very warmly attached.

He now sailed for the first time, cruising on the coast of Portugal;
and after remaining six years in the navy, he finally quitted his ship,
and entered the ranks of the army as a private soldier.

"`When about sixteen years of age,`" he says, "`having been unwell,
and probably led to reflect a little on that account,
I was made sensible of a Divine visitation extended to me at that time; disclosing,
with indubitable clearness, the vanity and emptiness of every earthly station,
tarnishing the pride and glory of this perishing world in my sight; and which,
though little understood and less regarded at the moment, has since, at different times,
been brought to my remembrance by Him that declares unto man what is His thought,
that makes the morning darkness, and treads upon the high places of the earth, the Lord,
the God of Hosts is his name!
When this occurred, although then entered into the bond of iniquity,
yet I had not launched so fully into its awful abyss,
as was afterwards most lamentably the case; and from what I have since witnessed,
in unutterable mercy, of the strength and power of redeeming love, a belief is induced,
that, if this warning voice, then sounded in the secret of my sinful heart,
had been hearkened unto and waited upon, my footsteps,--even mine,
would have been conducted from the horrible pit to which they were fast verging.`"

It was after long exposure to the severity of the weather,
during a harassing service in one of the most unhealthy districts of Europe,
that Daniel Wheeler was seized with a prevailing fever,
which swept away many of his fellow-soldiers;
and after all prospect of recovery seemed to be gone,
he was in mercy raised up from the hospital,
where numbers were daily perishing round him, to become, in future years,
the messenger of mercy and glad tidings to others.
At this period, however, although he maintained a fair character among his fellow-men,
he was living in a state of much estrangement of heart from God,
and often striving against his own secret convictions.
In the discharge of those duties belonging to his station,
he had acquitted himself to the satisfaction of his superiors;
he had been advanced to the rank of serjeant-major, and was afterwards further promoted.

In 1794 or 1795, he paid a short visit to his eldest sister residing near Sheffield,
who was married, and had become a member of the Society of Friends by convincement.
He was not long allowed to enjoy this interval of quiet,
before he was summoned to join the regiment, in which he had obtained a commission,
on its departure for the West Indies.
They set sail; twice the fleet put to sea, and as often encountered a dreadful hurricane;
several of the vessels were lost, the troops perishing in them:
but Daniel Wheeler was providentially spared, experiencing a narrow escape.

Reflecting on these disasters, and the renewed occurrence of wonderful preservation,
so unexpected and so undeserved, his heart was touched;
he could not resolve a third time to expose his life as he had done,
but determined to quit the army, so soon as he could meet with suitable employment.
He communicated this resolution to his sister at Woodhouse near Sheffield,
and returned there, having given up his commission, in 1796.

His mind was now opened to embrace the principles of Friends,
and he attended our meetings at Woodhouse.
This excited the ridicule of some of his nearest relatives and companions,
whose astonishment was great at the thorough change that soon appeared in him.
The work was not suffered to be long on the wheel; the effect was decisive and permanent,
affording a display of Divine power, not less remarkable in this rapid conversion,
than where there has been a more gradual accomplishment of its purposes.

He made an application to be admitted into membership with Friends:
and after a suitable time, his request was complied with, in the Second Month, 1799.

It is worthy of notice, that but little, if any,
instrumental means was concerned in this remarkable change.
While attending the small and generally silent meetings of Woodhouse,
Daniel Wheeler had felt the truth of our principles, and had yielded to the conviction.
His was a stability and growth in religion of no ordinary measure.
In a very few years after his convincement he was appointed an overseer,
and he was indeed a bright example of zeal, sincerity, and love to his friends,
in that responsible station.

An opening to begin business in a small way at
Sheffield presenting itself was readily embraced;
and in this, as in his future undertakings, the Divine blessing appeared to attend him,
and to crown his exertions with success.

In the Sixth Month, 1800, he was married to Jane Brady,
the daughter of Thomas and Rachel Brady of Thorne, in whom he found a helpmate indeed,
of sound judgment, guileless and faithful.
He remarks in a letter written after her death,
"`The heavenly Master`'s love has never ceased to
follow us through all the vicissitudes of time,
during a life, not a little chequered,
for a term of more than thirty-two years and a half,
when He was pleased to deprive me of my greatest earthly treasure,
and to take back that which He gave: but it was His own, I verily believe,
even His,--the same who enabled me to say, in the moment of my greatest distress,
'`Blessed be the name of the Lord.`'`"

As a tradesman he was diligent in business; he was also "`fervent in spirit;
serving the Lord.`"
By the strictest attention to integrity in all his dealings,
he gained the esteem of all with whom he had to do.
Yet it was easy to see where his heart was fixed: his Bible was his favourite companion,
and the few minutes that could be spared at a time amidst his daily concerns,
were spent in the perusal of the inspired writings.

For some time previous to 1813, the impression had become strong upon his mind,
that he would be called to advocate the cause of truth and righteousness upon the earth.
Very deep were his conflicts,
and very close was his application of soul to his
heavenly Father for strength to perform his will;
and it was his practice, when he lived in the country,
to withdraw early in the morning to a small field near his house,
for the purpose of religious retirement and prayer.

He was very watchful lest he should be led away from the grace vouchsafed to him;
frequently refraining from conversation apparently innocent, and in which he delighted,
lest at any unguarded moment he might grieve that Holy Spirit,
whom he felt to be his comforter and guide.
He was recorded as an approved minister in the Sixth Month, 1816.

About this period our friend was made sensible that
some sacrifice would be called for on his part,
as an evidence of his gratitude for the unutterable
mercy and great condescension of the Almighty,
in having plucked him as a brand from the burning;
and he saw clearly that it was indispensable for him, as much as might be,
to separate himself from the world and the things of the world,
by declining his prosperous trade, and retiring with his family into a smaller compass.
The extent of his business was becoming a burden.
He felt the force of our Lord`'s declaration:
"`You cannot serve God and mammon,`" and his obedience to
the requirement was full and unreserved.
"`Not,`" said he, "`that I have acquired a sufficiency,
without doing something for my livelihood; far from it.
I have still a prospect of maintaining my family comfortably with care and industry,
leaving the event to Him who knows the thoughts and intents of the heart.
I have no desire to accumulate riches for my children, the blessing seldom attends it;
and the baneful effects thereof are too often visible, even in our Society.`"

His mind was thus disposed to withdraw from his concerns in trade,
and he was in a state of waiting preparation, when an inquiry was made,
on behalf of the Emperor Alexander of Russia for a member of the Society of Friends,
to superintend some works of drainage and of
agriculture in the neighbourhood of Petersburg.
Daniel Wheeler offered himself for the service, and finally accepted the appointment.

On the 18th of Sixth Month, 1818, he attended the meeting at Sheffield,
when he took an affectionate leave of Friends there.
He told them that nothing less than apprehended duty
could have induced him to take the present step;
that four years ago it was clearly intimated to him,
that it would be required of him to remove into Russia;
and though the prospect was very trying to the natural part,
yet endeavouring to obtain resignation, he had been favoured to feel sweet peace.
His mind had been deeply affected while sitting among them,
in viewing the prospect before him,
when he would be deprived of the precious privilege of thus assembling with his Friends;
that he wished none might suppose his case a hard one,
for he thought that there was scarcely a person on the face of the earth,
who had more largely partaken of the gracious dealings
and protecting care of a merciful Providence.
Twice he had been preserved from shipwreck,--he had been favoured to
escape the devouring pestilence when numbers were falling around him;
and, when many were destroyed by the cruel hand of war,
his life had indeed been marvellously spared.
And surely the Almighty Being, whose arm had been so often extended for his preservation,
when he was running headlong in the paths of error,
had a right to dispose of the residue of his days, and was worthy of obedience.

He shortly after embarked for Petersburg, and took charge of the works committed to him.
These operations appear to have been conducted successfully,
much to the improvement of the extensive estates,
and to the satisfaction of the parties concerned.
There is also ground to hope,
that his labours will at a future day prove a blessing to that empire.

On account of circumstances connected with the religious profession of the country,
the gospel services of our dear friend were much circumscribed to private interviews;
and in the line of his religious duty, he addressed the English residents in that city.
The uniformly guarded and consistent life and conversation,
the unbending integrity which no self-interest could
warp,--no influence from without could suppress,
will be long had in honourable remembrance in that land,
to the glory of that Lord and Master; whom diligently to serve and faithfully to obey,
was more to our dear friend than the smiles of princes,
or all that the world could bestow.

During the abode of Daniel Wheeler in Russia,
he was careful to keep up in his house the regular attendance of meetings for worship,
twice on First days, and on Fifth days.
An orderly and regular attention to the reading of the
Scriptures was daily observed in his family;
nor did they omit the frequent perusal of the writings of Friends.

For the distant members of his own Monthly Meeting he evinced his concern,
by addressing them once a year, and occasionally at other times;
putting them in remembrance of the things which belonged unto their peace.

In the Fourth Month, 1825,
our friend Daniel Wheeler was liberated by his Monthly
Meeting to attend the Yearly Meeting in Dublin,
and for other religious engagements in Ireland.
He was also concerned in Third Month, 1831, to visit Friends in Devonshire and Cornwall,
as well as the inhabitants of the Scilly Islands.
These services appear to have been accomplished, much to the satisfaction of his Friends,
and to the comfort of his own mind.

At the end of 1832,
while he was confined by indisposition at the house of a friend in Norfolk,
the mournful intelligence arrived from Russia of the death of his beloved wife.
This was one of the greatest trials that could have befallen him;
but the Almighty hand was near to comfort and sustain him;
and he was mercifully strengthened to say, "`The Lord gave, and the Lord has taken away;
blessed be the name of the Lord.`"
A little before this he had laid before his Friends at
their Monthly Meeting in Ninth Month 1832,
his prospect of paying a visit in gospel love to the Islands of the Pacific Ocean,
Van Diemen`'s Land, and New South Wales, in which,
as well as in the Quarterly Meeting and the Morning
Meeting of ministers and elders in London,
he had their full concurrence and earnest desires for his preservation.

For so very extensive a service, the necessary arrangements occupied a considerable time;
these being at length completed, he sailed from the Thames the 13th of Eleventh Month,
1833.
The vessel was proceeding down the English Channel,
when on the 21st they were overtaken by a heavy storm,
which induced them to take shelter off the Isle of Wight; and from adverse winds,
and other causes,
they were not able to take their final departure until the 15th of Third Month, 1834.
He had been anxious to set out, and this detention was a great exercise to his faith.
Yet, prompt in his movements as our dear friend was accustomed to be,
when his duty was clearly defined, his example is strikingly instructive,
in the patience and the steadfast faith with which he
would wait until the true light so shone upon his path,
as to point out not only the way, but the right time to move in it;
and closely as he had been tried on this occasion,
he was at last permitted to see and acknowledge,
that he had not been detained one day too long.

The voyage out was a very tempestuous one, but he was preserved through all danger; and,
accompanied by his son Charles, arrived safely at his destination.

Among those distant islands he was long and acceptably occupied.
Yet he was often made sensible, preparatory to attending meetings,
and other religious services, that he had no ability or qualification of his own,
until he was humbled as in the dust;
when after patiently waiting to be endowed with strength from on high,
he has been enabled so to minister, that the Divine power has overshadowed the assembly;
softening and contriting these poor islanders; filling their eyes with tears,
and their hearts with love, until they could scarcely allow him to leave them.
This arduous service, extended through the long period of nearly four years,
was at length brought to a close; and he returned safely to England.

In the published accounts of our valued Friend`'s labours in these distant regions,
there is abundant evidence of his care to direct
his hearers to the Great Teacher and Sanctifier,
and to wean them from a dependence on instrumental aid; and it is gratifying to observe,
that, in preaching the truth boldly, without respect of persons,
he also gained the good-will of the resident missionaries,
who received him with uniform kindness,
and gave him on his departure very ample testimonials of their approval.

It may not be unprofitable in this place to notice the exemplary care
which our departed Friend had exercised over his tender offspring,
to train them up in the nurture and admonition of the Lord:
that they might experience a growth in grace, was the fervent desire of his heart.
He would rise at an early hour to read the Scriptures to them,
and at night he would quietly withdraw from the room,
when the children were gone to rest,
to endeavour to direct their youthful minds in
reverent approach to their heavenly Father.

The blessing of Him who alone was able to preserve them,
and render them fit for His kingdom, we believe was not lacking.
For when, within a short period of each other,
three of these young people were called from their
afflicted parent to exchange time for eternity,
he had the consolation of knowing that their end was crowned
by a humble and confiding trust in redeeming mercy.

Had it been in the ordering of the Divine will,
after so long a traveller in distant regions,
and sensible of declining strength our dear Friend
would have thankfully settled down for a season of rest.
Hence it is scarcely in words to express the sympathy that was felt for him,
when he informed his Monthly Meeting,
on the return of his certificate for the South Seas,
that it was required of him at once to set out for the American Continent,
to visit more especially the cities on the coasts.
At this time his son Charles Wheeler,
his endeared companion amidst the perils and fatigues of the Southern hemisphere,
was in a critical state of health,
and for his sake his father might have felt anxious to delay his voyage.
But so devoted was he to his Master`'s service, and so faithful to apprehend duty,
that the yearnings of a father`'s heart could not stay him,
nor call forth a repining word.
He proceeded to America,
and appeared to have pretty much carried out the work required of him,
when he found himself released to pay a visit to the remnant of his family,
who had now removed on account of Charles`'s declining state,
to the more genial climate of France.
At St. Germains, near Paris, he witnessed the peaceful close of his dear son.
He once more attended his own Monthly Meeting in Third Month, 1840,
and soon after sailed from this country for the last time, for New York.
On preparing for his voyage out, he writes, "`But now that the time draws nigh,
I feel more than ever the need of the prayers of the faithful for
preservation and support in this the evening sacrifice about to be offered,
when the natural strength of the poor body,
and perhaps that of the mind also is weakened, as days have multiplied upon me,
and years have increased; and,
I think I never felt more at the prospect of being
again severed from my beloved children:`" adding,
"`Certain it is that nothing short of implicit obedience to
what we believe to be a divine requirement will be accepted;
and nothing can so fully bring our love to the test,
as the having to leave all and forsake all, without making any reserve for ourselves.`"

A week after he sailed, Daniel Wheeler was taken ill,
and continued so for the remainder of the voyage.
The complaint appeared to be a cold attended with fever,
and as he was unable to lie down from difficulty of breathing,
his strength rapidly declined.
He received every attention that could be rendered on ship-board,
for he bore the respect and regard of all.
When he arrived at New York, he was conducted on shore by kind Friends there,
and further medical advice was obtained.
The opinion formed of his situation was decidedly unfavourable.
On being told that he was thought to be in a very critical state, he said:
"`All has been done that could be done;--only write to my dear children,
how it is. The work has been going on with the day.
All I want is quietness,
it is a great thing to be clear from pain. Love to all my
friends on this side the Atlantic as well as the other. I
want nothing but the love of my heavenly Father,
and I witness it.
The Lord is good to them who love and fear His name: great things has He done for me;
things so wonderfully marvellous, that they could hardly be believed,
were I to tell of them.`"

He remarked to a friend; As to himself, he had no doubt:
he had the same faith that had been with him through life,
and which was founded upon the gospel of Christ,
which enabled him to say with the Apostle, "`nevertheless I live; yet not I,
but Christ lives in me: and the life which I now live in the flesh,
I live by the faith of the Son of God, who loved me, and gave himself for me.`"

All that the most assiduous care and tenderness, aided by medical skill, could do,
proved unavailing to restore him.
His exhausted frame gradually sunk under the disorder,
and he quietly passed away on the 12th of Sixth Month, 1840, aged sixty-eight years;
having been a faithful labourer in the gospel vineyard above twenty-four years.

The Christian warfare was thus ended.
Full of years, his loins girded about, and his light burning,
he was as one that waits for his Lord.

We see abundant cause to exalt His holy name,
who thus led forth our beloved friend,--who preserved him through many
perils by sea and land--who conferred upon him strength in time of need,
and sufficient qualification for His service;--and who, in His own appointed time,
we reverently believe,
has called him in redeeming love "`to an inheritance incorruptible, and undefiled,
and that fades not away.`"

[.signed-section-context-close]
Signed in and on behalf of the Meeting aforesaid, held at Sheffield,
the 3rd of Twelfth Month, 1840.
