[#testimony-new-york, short="Testimony of New York Monthly Meeting"]
== A Testimony

[.alt]
=== Of the Monthly Meeting of Friends of New York, concerning our Friend Daniel Wheeler.

'`At the Yearly Meeting of Friends held in New York, by adjournments,
from the 24th of Fifth Month, 1841, to the 28th of the same inclusive.

'`A Testimony of the Monthly Meeting of New York, concerning our late valued,
and beloved friend Daniel Wheeler of Great Britain,
approved by the Quarterly Meeting of Westbury, and by the Meeting for Sufferings,
was read:--

'`This tribute of affection and of justice to his
memory was very satisfactory to this meeting;
the Testimony was directed to be recorded,
and the Clerk was requested to cause a copy of it, together with a copy of this minute,
to be forwarded to the Monthly Meeting of Balby in England,
of which our dear friend was a member.`'

Our beloved friend Daniel Wheeler of England,
having finished his labours in the ministry of the gospel,
and ended his days in this city,
this meeting feels it to be incumbent upon it to make public
some account of his religious services in this land,
of the progress of his illness, and of his interesting expressions,
when he laid down his head in peace among us.

He first arrived in this city on a religious visit to Friends in this country,
with certificates of unity from the meetings to which he belonged,
on the 1st of the First Month, 1839.

During the following spring and summer, he attended the Yearly Meetings of Philadelphia,
Virginia, New York, and New England.
In the Eighth Month, he visited the British provinces of New Brunswick and Nova Scotia,
and in the Ninth Month attended the Yearly Meeting of Ohio.
During his religious engagements amongst us,
he was careful to seek for the guidance of the Holy Spirit,
and to move no faster nor further than his way was thus opened.
Hence his preaching was sound, weighty, and edifying, ministering grace to the hearers,
and is fresh in our minds,
accompanied by deep and feeling unity with his religious services.
In all his movements he was remarkably watchful to wait for that Divine direction,
which had so often and so remarkably preserved him in many seasons of peril,
during his extensive travels by sea and land.

In consequence of intelligence of the declining health of his son Charles,
he sailed for England on the 1st of the Tenth Month, and found him in France,
where he had gone with the hope of deriving benefit from the climate,
and had the satisfaction of continuing with him until the peaceful close of his life;
after which our dear friend again embarked for this country,
and arrived in New York on the 28th day of the Fourth Month, 1840.

During the voyage he was taken sick, and was so ill on arrival,
that he was removed with difficulty to the house of our friend John Clapp.
On the following day he was increasingly ill,
and remarked to the physician that he could not endure another such a day.

On the morning of the 30th,
it appeared from his rapid respiration and the coldness of his extremities,
as if he was sinking fast, and it was thought proper to inform him of it: he replied,
'All has been done that could be done; only write to my dear children how it is:
the work has been going on with the day.
Love to all my friends, on this side the Atlantic as well as the other.
It is a great thing to be clear of pain.
I desire nothing but the love of my heavenly Father, and I witness it.'

He revived, however, in the afternoon, so as to write a few lines to his children.
On the following day, he had returns of oppression.
On the 3rd of the Fifth Month, after being bled, he said,
'Without blood there is no cleansing upon which one of the physicians remarked,
"`It is the blood of Jesus that cleanses us from all our sins.`"
'Yes,' Daniel replied,' but not in our natural unregenerate state.
If we walk in the light as he is in the light,
then I believe it will cleanse us from our sins: yes,' he added with much emphasis,
'I know it.'

In the evening he said he had had a hard struggle,
and at one time he did not know but it was the cold sweat of death.

On the morning of the 6th, he called for his clothes,
and having given directions for the disposition of some papers which they contained,
he said, 'Now I have done with the things of this world;' and further observed,
that he had no wish to live, but for the sake of his family,
and that the Lord Jesus might live in him; that he had been his guide for many years,
and he had declared his name unto thousands: that he had no hope but in Him,
and he was the same Lord over all: that it was not the prospect of immediate release,
that led him to speak thus, but it was in his heart,
and he must say it while he had words; with much more, in a very impressive manner,
and with a strong voice.

Towards evening his mind appeared to overflow with adoration
of the mercy and goodness of his dear Lord and Master,
which had constantly attended him in his pilgrimage,
and crowned him with loving-kindness and tender mercies.

He briefly recapitulated what had occurred since he left America,
alluding to the consolation he had received at the death of his son Charles;
so that he had to rejoice in the midst of grief, saying,
"`The Lord is good to them that love and fear his name:
great things has he done for me;`" things so wonderfully marvellous
that they would hardly be believed were I to tell of them.
If I have experienced any shortness in my journey Zionward, it has been on my side,
and not the Lord's; for he has been faithful,
and his promises have been and remain to be, yes and amen, forever.
While I was on ship-board, and thought by some to be nigh unto death,
how did the Lord appear for my help and consolation!
and since I have been in this chamber,
how has he appeared for my comfort in the night season,
and I have been enabled to sing hymns of praises and thanksgiving unto him!
When the ship made her soundings I made my soundings,
on that Rock which has never failed me,
whose foundation is from everlasting to everlasting.
I saw that I should be safely landed, though extremely weak in body,
and was enabled to say, should the Lord see fit to raise me up, and strengthen me,
still to show forth his wonderful works to the children of men,
or cut short the work in righteousness, Your will, O God, and not mine be done.
I do not see how the end will be.'

9th.--He passed a distressing night, and one time said,
'I did not know whether I should live to see the light of another day.'

11th.--He said he felt the Saviour to be near him, every hour of the day.
From this period there was some apparent improvement,
and for a time he was more comfortable; but the disease not being removed,
his weakness again increased, and on the 29th he was very feeble.
At one time he said, as to himself, he had no doubt:
he had the same faith which had been with him through life,
and which was founded upon the gospel of Christ,
which enabled him to say with the apostle, "`Nevertheless I live; yet not I,
but Christ lives in me; and the life which I now live in the flesh,
I live by the faith of the Son of God, who loved me, and gave himself for me.`"

12th of Sixth Month in the morning, he said,
'Perhaps this day will end all your cares and troubles.' In the afternoon he said,
'It is very doubtful whether I shall be permitted to return to
England.' In the evening his breathing became more laboured:
after some time he was incapable of being aroused,
and a little after twelve o'clock at night, he quietly passed away,
in the 69th year of his age.

Throughout all his extreme weakness and great distress,
that faith and trust in the mercies and promises of his dear Redeemer,
which had been so remarkably exemplified during his eventful life,
remained firm and unshaken; and that all things would work together for good,
seemed to be the prevailing covering of his mind throughout his illness.

He had ceased from his many and extensive labours;
and we feel an assurance that he has entered into that rest,
which is prepared for the people of God.

His remains were conveyed to Friends' Meeting-house, in Orchard-street,
where a large and solemn meeting was held; in which,
testimony was borne to the sufficiency of that Divine power,
by which he was prepared for usefulness in the church,
and made instrumental in promoting the cause of vital Christianity in the world.
After which the corpse was followed to the grave by many Friends and others,
and interred in Friends' burial-ground, the 15th of the same month.

[.signed-section-context-close]
Signed by direction, and on behalf of the Monthly Meeting aforesaid, held in New York,
7th of Fourth Month, 1841.
