== Chapter II.

[.chapter-synopsis]
* The Author Goes to Plymouth, There with His Regiment to Ireland
* Kilkenny
* Dublin
* Harassing Service
* Personal Danger
* Recruits
* Liverpool
* Bristol
* Southampton
* Embarks from There with Troops for the Campaign in Holland

It was a little remarkable, that,
after all the pains I had taken to screen my fallen situation
from the knowledge of those who had been acquainted with me,
the regiment in which I had engaged, proved to be at that very time on duty at Plymouth,
a place where, above all others, I had the greatest number of acquaintances;
but I was so completely metamorphosed in appearance,
that I was never in one instance found out by any whom I had formerly known,
even when brought into close contact with them.
This change of condition, however, wrought in me no change of life.
My conduct for a time was almost entitled to the appellation of reformed,
but this period was short indeed;
for having speedily acquired a knowledge of all
that was required of me in the way of duty,
I began to rise above the impressions made by difficulties gone by,
and again to look forward to a farther participation in the delusive
and miserable pleasures of this transitory and wicked world.

In less than a year we were ordered to Ireland;
and three transports having arrived for us in Catwater,
a short time completed the embarkation: we sailed for the Cove of Cork,
reaching it in safety after a fine passage.
While at sea, it was soon discovered,
that I was no stranger to the management of a vessel;
and though I concealed my having served several years in a superior station,
yet I felt so much at home,
that I voluntarily performed the duty of a sailor during my stay on board,
not a little proud of my qualifications.
It is most probable that pride and self-conceit were the only
motives that prompted these endeavours to be useful;
few, indeed, of our actions, however specious in appearance,
are wholly divested of self in some shape or other,
when examined in the pure mirror of truth;
such is the depravity of the human heart in its natural state.

Having frequently been sheltered before by the coves, bays, and harbours of Ireland,
and frequently been on shore in different places,
I was tolerably well acquainted with the character and customs of the people;
whose hospitality to strangers has long been
acknowledged by all who have visited their shores:
and although now unable to move in the same sphere as formerly,
yet I still found opportunities to indulge the evil propensities of fallen nature.
But as the miserable inhabitants in some of the
provinces were rapidly ripening for rebellion,
our time was much occupied by hard and laborious service.

After landing at the Passage of Cork, we proceeded to that city,
but shortly marched forward to Kilkenny.
This place was a station that afforded more quiet and comparative ease,
than any which afterwards fell to my lot, while engaged in the regular service;
but our stay here was of short duration,
before entering upon the arduous duty of Dublin garrison.
The agitated state of public affairs at that period, greatly augmented our fatigue;
and it frequently happened that we were on duty every other night,
and this in the winter season.

Discontent increasing and disturbances breaking out in the interior of the country,
small detachments of troops were dispatched from Dublin,
to strengthen the authority of magistrates in
their endeavours to maintain public tranquillity,
and to afford protection to the peaceable inhabitants from the nightly
depredations of numerous gangs of misled and intoxicated desperadoes,
to which they and their property were constantly
exposed under a variety of diabolical pretences.
It was my lot to be chosen with the first of the detached parties,
to a share of this dangerous and harassing service; on which,
such was at one time the emergency, that we were kept on the alert night after night,
without any intermission for a week together,
with only such intervals of rest as could be procured in the day time.

While on this expedition, on a particular enterprise with a constable,
I was to all appearance reduced to the necessity
of taking the life of another to save my own.
The constable perceiving the danger, had left me alone;
when I was suddenly attacked by a poor infuriated creature,
in a state little short of perfect madness from continued intoxication,
supported by several others, but in a less outrageous condition.
I kept him at bay for some time; but at last he got so near,
that it became every moment more difficult to avoid being reached by
the violent strokes he made with some kind of weapon,
I think of iron, which were repeatedly received by the firelock in my hands,
then loaded with ball.
In this situation,
there seemed left to me no other than the dreadful
alternative of shooting him to save myself.
I called in vain in the language of appeal to the other people to interfere:
they stood by, as if to see how matters were likely to terminate,
before they began to act or take a part of any consequence either way;
which they nearly carried too far:
but when they saw me actually preparing to shoot the man,
they hastily cried out,--'spare life! spare life!'--which I
only needed their help to enable me to accomplish.
They then seized him,
and in the midst of the struggle and confusion which took place amongst themselves,
my escape was happily effected.
I cannot suppose at that time,
when I needed only the help of other men to enable me to spare life,
that the principal motive was other than that of self-preservation,--accompanied by
fear of the immediate consequences that would inevitably have followed,
and must have resulted in my own destruction.
Therefore it is greatly to be feared (although that heart must be callous indeed,
which in all such cases does not recoil from the horrid
act,) that it was not love to my fellow-creature,
which prompted the desire in me to spare his life.
Let none mistake it as such.
I have frequently thought of this circumstance since it occurred,
I hope with humble thankfulness to the great Preserver of men;
and now on committing it to record, as one of those many events,
in which there was but one step between me and the grave,
and while shuddering at the strong recollection of it,--
my soul magnifies that unmerited and amazing mercy,
afresh displayed and multiplied to my understanding in a two-fold view:--on the one hand,
in withholding me from the crime of taking away the life of a fellow-creature,
like myself, "`in the gall of bitterness;`" and if I had escaped myself, thus sparing me,
at this late hour, amidst the decay of nature,
when the shadows of the evening are stretching out and my feet drawing near
the margin of the grave,--the appalling thought of a brother's blood,
yet unwiped away:--on the other hand,
in rescuing from immediate death two miserable sinners, wholly unprepared to die;
for had I taken away the man's life,
my own would doubtless have been quickly sacrificed to
the revenge of his enraged companions.
Thus as my history rolls on,
the enormous load of debt which I already owe unto my Lord still accumulates;
and verily it never can be liquidated, but in that infinite and wondrous mercy,
which delights to forgive every repenting sinner,
who in the depths of humility and abasedness of self,
has indeed "`nothing to pay`" withal.

On the arrival of some fresh detachments from the garrison,
I learned that a vacancy had occurred during our absence on this service,
and that the blank was filled up by the promotion of myself.
Although this circumstance was of trifling import,
yet it served to flatter and feed pride,
and eventually to open the way again for a renewal of those evil habits,
from which for a time I had been sheltered.
As each body of troops was relieved from this extra fatigue at a given time,
our turn came in regular course at the expiration of a few weeks,
when we again returned to Dublin.
Not long after this,
inquiry was made for a person qualified to assist in
the writing department of the commander-in-chief,
under his own personal inspection: I never knew exactly how it was brought about,
but in the course of a few days, it was decided in my favour;
and I immediately entered upon this new and altogether unexpected employment.
Being now on most days at liberty at an early hour, and freed from restraint and control,
and from that incessant round of duties,
which had before fully occupied my time and attention,
and compelled in a degree to orderly conduct,
together with having it more in my power by possessing greater
means,--I soon began to take my swing in every inordinate
gratification to which I was naturally prepense,
and in which an extensive metropolis furnished ample opportunity to indulge;
thus adding sin to sin, and making farther woeful work for repentance.
And although at times,
in the midst of these evil practices I was made sensible of convicting reproofs,
sufficient to have awakened any one but myself;
yet they only seemed to deter me for a short interval from persisting in them,
or until another opportunity offered;--such was their dominion over me.
This course was however at last stopped,
by my attendance being no longer necessary at the writing department,
together with the sudden march of the regiment to Granard;
but not before my health had begun to suffer from my folly.

Our stay was not long at this place; for the French revolution,
which had occurred about two years before,
now began to occasion more frequent movements and changes amongst the military.
I was engaged in some hazardous enterprises while lying here;
and although the town was small, and our time in it short,
yet there were sufficient temptations to be found for my unwary feet to fall into.
From this place, a part of the regiment,
consisting of two hundred picked men and a suitable number of officers,
was drafted to serve in an expedition then preparing to act in the West Indies.
The same quota was selected from every regiment in Ireland,
then seventeen in number,--and possibly from every regiment in England also.
From all the information that I could ever obtain, the greatest part,
if not the whole of these poor devoted fellows,
then declared to be the flower of the British army,
fell victims to the climate and the war.
I mention this lamentable fact, although foreign to my subject,
to perpetuate all in my power,
the ravages of this horrid and desolating scourge of the human race.
At the same time, under a deep sense of my then sinful and still sinning condition,
my mind is struck with admiration, that I was not included in the above-mentioned draft,
to which I was no less liable than others;
were it only as a punishment which I so justly merited,
for my unprecedented rebellion against a long-suffering and all-gracious Lord God.

Our next remove was to Galway; where after some weeks I was again promoted,
from what cause I do not now remember; but, as had been the case in the navy, so now,
however profligate my conduct in the general, I still kept up a fair name,
by being ready for all the duties that devolved upon me.

By this time several new regiments were raising by field-officers,
in expectation of promotion when the number of each was completed,
according to the then existing proposals of the government; at whose expense,
and under whose particular patronage these measures were undertaken,
for the purpose of more vigorously prosecuting the continental war.
In order to expedite the formation of these new corps,
application was made to the commanding officers of old established regiments,
for persons competent to assist in their equipment and discipline,
where such could be recommended.
For one of these regiments,
intended to be formed in Dublin of recruits raised from the different provinces,
two others with myself were selected,
and accordingly despatched immediately to
commence the necessary operations in that city.

After leaving Grranard, and to the time of my again reaching Dublin,
perhaps my course of life, from one or other cause,
might not be quite so dissipated as for some time previous.
But this could only be attributed to an accumulation of duty,
and not from any change wrought in myself:
for alas! the old evil root still remained in unabated strength, though dormant;
which in a while did not fail to shoot forth,
and produce those works of unmortified flesh,
which had so long and so often been manifested in my conduct and conversation,
and were now not likely to be less frequent,
from my being again promoted shortly after joining this new regiment.
Some progress was made in organizing the new troops,
as the different small detachments arrived in the
course of the winter from the interior of the country;
and by the time the spring fairly opened, the whole number stipulated,
was raised and accepted.
Such was the urgency of affairs just then, that,
while in a raw and incomplete state of discipline, almost beyond conception,
from the wildness of character of the class of people,
of which the principal part of the regiment was composed,
immediate embarkation was ordered, and transports were actually in waiting to receive it.
In two days, the whole were on board of three ships,
which sailed with the first tide for Bristol.

When the time for sending off these newly raised troops was fully come,
the utmost despatch was necessary; for it was very evident,
that had time been allowed for the information to spread to any material extent,
the embarkation could scarcely have been effected without bloodshed.
As it was, though the preparations commenced soon after three o'clock in the morning,
the concourse of people assembled together was immense,
to behold their unfortunate countrymen in every relation of fathers, husbands, brothers,
and sons, forced away from their native shores,--I may say forced away,
for it was necessary to assemble a strong military
force from the garrison to ensure the embarkation,
which after all was not effected without some difficulty.
From my own personal knowledge of the fate of many of these poor fellows,
and of the destination of those remaining after I left them,
I think it is possible but scarcely probable,
that any of them ever returned to their families, friends, or country any more;
as will subsequently appear, if this narrative be proceeded with.

We were favoured with a fine passage to the Severn,
and landed about six miles below Bristol; in which city we remained one night,
and then marched forward to an encampment,
where several other regiments were previously assembled, at Netley Abbey,
not many miles from Southampton.
From the undisciplined condition, with but small exception,
of the officers and men who composed our regiment,
it was only reasonable to suppose it had now reached its destination for the present;
but after a few weeks training, it was numbered with the line.
We received a set of new colours, and embarked on Southampton river,
with the other regiments which formed the camp at Netley Abbey,
to join the British army then on the Continent, under the command of the Duke of York.
We dropped down to Spithead the next morning, and the same afternoon, Earl Moira,
the commander-in-chief, having joined the expedition, we sailed,
thirty-seven ships in company, under proper convoy to the coast of Flanders.

The weather being thick, with light airs of wind, our passage, though fine,
was rather tedious, before reaching an anchorage off the port of Ostend.
From circumstances of an unfavourable cast, unknown to us at the time,
it was judged most prudent for the expedition to be free from every
incumbrance likely to retard or impede its movements through the Netherlands;
the success and safety of the enterprise wholly
depending upon its ability to evade and elude,
by the rapidity of its movements, in forced marches by night,
the greatly disproportionate strength of the enemy.
The number of troops then under Earl Moira, was little more than 7000;
while the French force, through which we had to pass, was estimated at 80,000,
and they were at the time so posted,
as seemed to prohibit our junction with the Duke's army.
It was therefore concluded,
that every article of baggage and stores belonging either to officers or soldiers,
beyond what they could themselves carry, should be left on board the ships.
At an early hour of the morning after our arrival in the roads off the town of Ostend,
every officer and soldier was furnished with a blanket,
and an allowance of three days' provisions and water from the stores of the transports;
it being very uncertain whether any supplies could be obtained for some days to come.
Thus provided, the troops were disembarked under cover of two large floating batteries,
prepared for the occasion, to prevent any attempt to frustrate their descent.
As the boats employed had many times to pass to and fro, between the ships and the shore,
before the whole were conveyed,
it was near night when the landing was fully accomplished.
To expedite the landing, a large float was made use of,
to assist in crossing a narrow space of water connected with the harbour;
so that the troops were enabled to land at more than one point at a time, and then unite.
It was well for those who had nothing to do with this ill-adapted float;
for in the hurry, it became overladen with soldiers, and was quickly overturned,
causing the loss of many men, who, from their being encumbered with arms, baggage,
and provisions, were incapable of making much effort to save themselves;
this weight being strongly attached to their bodies,
they sank before they could extricate themselves from it.
I landed on the main shore of the harbour,
and thus providentially escaped with only seeing the float then loading,
just before the accident happened.

I do not know how it fared with others, but it is scarcely probable,
all circumstances considered,
that there could be any material superiority in
the accommodation of one more than another.
On the morning that we landed, I might doubtless have been supplied with a blanket,
in common with others; but as I occupied a station,
in which little rest could be expected, even when others slept,
and supposing that I should be able to borrow from some of the others,
when they could not be used by themselves, this opportunity was lost;
but I afterwards regretted the non-acceptance of it.
From the day we left the transports,
several weeks elapsed before I got to sleep under the cover of a tent; as these,
with the rest of the luggage and stores,
were left on board the ships to be conveyed to Helvoetsluys,
as a place more secure from the French than Ostend.
We remained upon the sand hills near Ostend three days and nights after landing,
and then commenced a march which could scarcely be equalled for fatigue and hardship;
as we were wholly unprovided with provisions, and every common necessary,
with which the generality of troops are usually furnished at the opening of a campaign.

It would be no very difficult task for me at this day,
to enter into minute detail of particular circumstances,
were it consistent with the declared object before me,
in setting about to pen this memoir;
for although so many years have rolled away since these miserable
scenes were actually shared in and witnessed,--yet such are the
strong impressions stamped on my memory by the sufferings endured,
and the manifold deliverances which followed,
that while endeavouring to insert such incidents only
as are needful to preserve the chain of history,
in sufficient links of connection to enable me to proceed with
correctness,--transactions that have long been forgotten,
though they once formed a prominent feature in the toils of the day,
are recalled from oblivion in a remarkable manner.
I must however forbear to intrude them here, and proceed again with saying,
that on leaving the neighbourhood of Ostend, we passed through Bruges,
and penetrated into the country by way of Ghent.

The first halting place of the army,
in the evening of the same day that it left the coast,
was called the 'Pigeon's Nest;' but it did not prove a
very quiet one,--for by two o'clock in the morning,
the advance of the enemy was announced by the firing of the picquets,
by which we were surrounded.
Whether this attack was intended to alarm only, or to endeavour to take us by surprise,
I never understood; if the latter, it certainly failed,
for the troops were literally sleeping on their arms, covered with their blankets,
so that in a few minutes, a line was formed, with the commander-in-chief present.
It was however considered prudent to remain there no longer,
and in half an hour this post was abandoned,
and the march continued until noon the next day, when a stoppage occurred,
from the French having occupied a bridge over which we had to pass.
Notwithstanding the men were almost ready to faint for lack of food,
having scarcely tasted any thing for twenty-four hours;
yet on its being proclaimed through the line that volunteers
were needed to force the passage over the bridge,
a sufficient number immediately offered, apparently glad of such an opportunity.
After three hours' detention, the obstruction was removed,
I am inclined to think by its being found that the force advancing against it,
was much too strong for that by which the bridge was occupied.

The army then moved forward until midnight,
although its course was much impeded by a tremendous storm of thunder, lightning,
and heavy rain, which commenced at nine, p.m., and continued several hours.
I do not see how I could have sufficiently exalted the name of my God,
and his gracious dealings with a poor benighted and rebellious creature,
without mentioning the two facts just related; inasmuch as they magnify in my view,
his long-suffering and protection,
to one who was utterly insensible of his loving-kindness, and who then knew Him not:
and I trust I shall not be permitted to overlook or
pass by any thing that will show forth his praise,
and tend to his glory; or be prevented from acknowledging his power and his might;
who has, according to his mercy, so many times delivered me out of every distress.
For, notwithstanding the constant exposure to every shower of rain that fell,
without covering over my head, and with no couch but the earth,
and that at times soaked with wet;
while harassed with fatiguing marches night after night, and with little rest by day;
amidst hunger and thirst, being often short of food for days together,
and occasionally no water to be had, without digging a well to procure it,
to avoid the unwholesome waters of the stagnant pools;--and although
for several weeks together my clothes were never taken off,
but to renew a shirt, and my shoes but seldom off my weary feet;--yet through all,
my health was not materially affected, till near the approach of winter.
But in the above description,
not one half has been told of that marvellous mercy
which was still extended for my preservation,
when many fell by the sword,
or were taken captives by the enemy,--when thousands
were swept off by pestilence,--and while unhurt myself,
I saw the wounds of others bleed.
Once while gone to Helvoetsluys in search of some baggage, I entirely missed a contest,
in which our regiment was deprived of twenty-eight men; and,
when at last overwhelmed with sickness and distress,
the same Divine and compassionate arm of everlasting love and strength,
was still underneath to bear up my helpless head,
and in his own time to rescue me from the very jaws of death, to celebrate his praise,
and to declare in humble thankfulness and gratitude of soul,
"`his wonderful works to the children of men.`"
