== Chapter V.

[.chapter-synopsis]
* Prospect of Duty in Russia
* Offers Himself to the Russian Government to Superintend Agricultural Improvements Near Petersburg
* Voyage to Cronstadt, 1817
* Interview with Prince Galitzin at Petersburg, also with the Emperor
* Voyage Homeward

A new field of action was now about to open before him,
for which his mind had been secretly preparing,
until a willingness had been begotten in his heart,
to follow the requisitions of his Lord, whithersoever these might lead him,
or whatever sacrifice to his natural feeling, an acquiescence in them might involve.

For several years, he had an impression that it would be required of him to go abroad.
This prospect frequently cost him much exercise of mind;
and one day while pacing up and down his parlour, feeling unusually burdened under it,
he was led earnestly to cry unto the Lord,
desiring that he would be pleased to show him to what part of the world he must go.
One of his children was in the room putting together a dissected map,
and as his father approached him,
his eye rested on Petersburg with such an intimation
that there his Divine Master would send him,
that, said he, in relating the circumstance many years afterwards to an intimate friend,
"`I never afterwards doubted; he however kept the matter entirely to himself,
believing that when the right time should come, way would be made for him.`"

Early in the year 1817, enquiry having been made, by order of the late Emperor of Russia,
for a person to undertake the management of an
agricultural establishment in his dominions,
Daniel Wheeler believed it his duty to offer himself for this service.
The Emperor, as the reader may recollect, visited this country, in the year 1814,
and was much struck with the perfection of the English system of farming.
His attention had been drawn in several ways to the Society of Friends;
and a casual visit made to the farm of a Friend, on the Brighton road,
had given him a favourable impression of their character as agriculturists.
This impression, as the event proved, was not soon effaced;
for having three years afterwards concluded on the drainage
and cultivation of certain marshes and waste lands,
in the immediate neighbourhood of Petersburg,
and enquiry being made in England for a suitable manager for this work,
the Emperor particularly specified his wish,
that a member of the Society of Friends should be selected.
The information was circulated in the Society,
by the late Richard Phillips of Wandsworth;
and the following extract from a letter received from a Friend of Sheffield,
in reference to this subject,
is inserted as showing the manner in which this
undertaking was entertained by Daniel Wheeler.

[.signed-section-context-open]
Second Month 15th, 1817.

Little did I suppose on the receipt of your letter of the 22nd,
that I should have occasion so speedily to reply to it.
Soon after reading it, I observed to my wife,
if such a Friend as Daniel Wheeler had believed
it right to embark in such an undertaking,
I knew of no person, that for all the purposes required, might be so fully recommended.
But this idea did not at that time operate farther on my mind,
than to induce me to conclude to take him into consultation,
respecting some one well qualified.
On the receipt of your letter, he was engaged in a family visit in a neighbouring meeting.
In consequence, I was prevented from communicating the subject to him, until yesterday;
when I perceived, to my surprise, that it made considerable impression on his mind,
and that, from some questions he put to me, he was making the application to himself.
Without noticing this, I told him,
I wished he would give the overtures of the Emperor a place in his thoughts;
and if any eligible person occurred to him, to inform me within a week.
But my surprise was increased this morning, by his coming to inform me,
that it would be mere form to defer acknowledging,
that his mind was already made up to offer himself for the situation,
for which it had been preparing more than two years.
Great as the trial will be to many, to spare such a one out of our Monthly Meeting,
there was an assent in my mind, like that of "`you are the man.`"
I have often said, that in respect both to civil and religious attainments,
I knew of no one, moving in a similar sphere,
who is so much qualified for the superintendence and the direction of others.
A novice as to the world, or one who had had little experience as to the ways of men,
however much he might have had of agriculture, would lack many requisites,
essential to the filling with propriety a station,
designed to be under the immediate eye of an Emperor.
In his character, so much of true dignity is united with Christian humility,
as qualifies him to appear before princes.

After acquiring the first reputation in Sheffield as a tradesman, he took a farm,
as if to give proof of his practical skill in agriculture;
which has excited the admiration of the neighbourhood,
and demonstrated that his talents in this direction are of a superior kind.

For a person of his qualifications,
to come forward on the ground of religious sensibility,
appears to me an extraordinary instance of devotedness; but he has been heard to say,
he has been forgiven so much,
that he cannot give too great proof of gratitude and attachment to the King of kings.
If he enter upon this undertaking,
it will be no small sacrifice in a pecuniary consideration, which he will have to make.

[.asterism]
'''

One of the first difficulties which presented itself, in regard to this movement,
was that of mentioning his prospect to our dear mother.
He believed her timid nature would be ready to shrink under such a requirement.
His distress therefore on her account was great: but what was his surprise and comfort,
when on informing her,
and querying whether she could leave her friends and native land to go with him,
she sweetly and calmly acquiesced; stating her belief,
that if it was the will of the Lord, strength would be given them to bear the trial,
as well as ability to perform the service required, whatever it might be.

His own explanation of the motives which induced him to enter into this engagement,
is thus given by himself, in a paper addressed to an official person in Petersburg,
during his first visit to that city, from which the following is extracted:

[.signed-section-context-open]
Eighth Month 13th, 1817.

It seems altogether unnecessary to preface what I am about to state in this memorial,
seeing that the truth never did, nor ever will need any apology.
I shall therefore proceed by observing,
that it is now two years and a half since the subject of visiting Russia,
and rendering myself useful in promoting the happiness of its numerous inhabitants,
was presented to the view of my mind, by that inward principle of light and grace,
a manifestation of which is given to every man to profit withal, in which I believe;
and Petersburg was the place pointed out to me as the scene of my operations.
It was, I must acknowledge, a prospect at which I was ready to shudder: for,
although we may at times feel a willingness, and even profess it,
to go with our Lord and Master into prison and unto death;
yet such is the frailty and weakness of human nature, that when the trying hour comes,
like Simon Peter, we are ready to deny Him.
But He who is touched with a feeling and compassionate sense of our manifold infirmities,
I trust saw that it was not wilful disobedience, but human weakness;
and He who only knows the thoughts and intents of the heart,--yes,
from whom "`the darkness hides not,
but the night shines as the day,--the darkness and the light +++[+++being]
both alike to Him,`"--in adorable condescension and mercy,
does at seasons qualify his poor, dependent, humble followers,
acceptably to breathe the aspiration,--"`Lord you know all things,
you know that I love You.`"
However, I must honestly confess,
that at the time I could not possibly devote myself to such an undertaking;
for I am certain, that no earthly consideration whatever,
could have induced me to leave my beloved wife and tender children: but He,
who "`blows with his wind,
and the waters flow,`"--at whose touch the mountains of opposition melt down and vanish,
has by His wonder-working power, reduced my mind to a willingness to go,
whensoever and wheresoever He is pleased to lead,
and to do whatsoever he is pleased to call for.

Some time after this, as I was returning home late one evening,
I had a sense of invitation after this manner,
"`What if the Emperor of Russia should need a person for the superintendence
of agriculture?`"--at which time a willingness was begotten in my mind to go,
if that should be the case; but when, or in what manner, this was to come to pass,
was totally hidden from me.
The frequent conflict of soul I had to pass through,
none can conceive or have an idea of, but those who have been alike circumstanced;
all which was permitted in infinite wisdom, for the subjection of the natural will,
and is what I verily believe all must pass through,
before they can in sincerity of heart say,--"`Not my will, but Yours be done.`"

In this manner I was prepared for this great event, and I cannot but record it,
as a great and signal event in the life of a private individual:
for when a letter was received from Russia by Richard Phillips of London,
a copy of which was sent to a Friend in Sheffield, and by him handed directly to me,
it did not create any surprise, as I was in a state of preparation to receive it,
and in daily expectation of something important coming to pass.
The circumstances which afterwards took place, are too well known to need enumerating.

I have had to leave my family for short periods of time,
having been called upon to proclaim the glad tidings of the everlasting gospel,
and to endeavour to stir up the pure mind by way of
remembrance of those things that are most excellent,
in visits to my brethren and sisters, in their separate churches,
in different parts of England;
and I humbly hope the day's work was keeping pace with the day:
but now a greater trial of faith was to be exercised,
a greater sacrifice to be made;--I must not only leave my family, but my country also.
The second letter arrived from Russia, and the time seemed fully come.
Accordingly I drank the cup with all its bitter dregs of separation, and tore myself away.

If my proposals be altogether rejected, I do not know what I can do more.
I have not stood at a distance, but have actually come into Russia, and offered myself,
my family, and the sacrifice of nearly all the resources I possess.
If this offer be refused, I humbly trust the will will be accepted for the deed,
and that obedience will have kept pace with knowledge;
for verily it matters little our knowing, unless we practise also.
It is "`not the hearers of the law, but the doers of it,
that are justified`" in the sight of Almighty God: it is "`not every one that says, "`Lord!
Lord!`" that shall enter into the kingdom of heaven,
but they that do the will,`" etc.:--and again, "`If you know these things,
happy are you if you do them.`"
In this case, I shall of course return immediately home,
and resume my former occupations; committing myself to Him,
who will not break the bruised reed, nor suffer it to be broken;
and whom I earnestly desire to serve to the latest moment of my breath.^
footnote:[The above was copied from the original in "`The Chancery of
drainage and cultivation of the neighbourhood of Petersburg.`"]

[.asterism]
'''

To return to the narrative:--it was concluded that Daniel Wheeler should,
in the first instance, visit Petersburg alone;
and for this purpose he set out from his home, towards the close of the Sixth Month,
1817; and, after making a satisfactory journey, returned the same autumn.
The following are extracts from memoranda made during this visit:--

On board the "`Loft,`" 115 miles from the Holderness Coast.
Sixth Month 29th, First day.--My mind constantly bending towards home,
and tracing the various situations and occupations of my dear wife and family,
as the different periods of the day advanced,
and I remembered my beloved Friends in their Meeting at Sheffield;
but I had very little opportunity for retirement myself,
the affairs of the ship being much unsettled on
account of having so recently come from harbour,
and the cabin subject to frequent interruption.
Last night my mind was disquieted,
and being very desirous of promoting the safety of the ship,
I stayed on deck until after midnight; and when I lay down in my cabin,
it was with reluctance, as if the ship was not safe, unless I was upon the look-out.
I have felt deserted and uncomfortable a considerable part of the day;
but have been this evening favoured to see that it arose from lack of holding fast
my confidence,--from not being sufficiently resigned into His hands,
"`who sleeps not by day,
nor slumbers by night,`" and without whose protecting arm of help,
"`the watchman wakes but in vain;`" and I believe that
I have nothing to do but to be quiet,
and endeavour patiently to trust in the all-sufficiency of His power.

30th.--As the forenoon advanced, the wind increased and the sea arose,
and by degrees we were obliged to diminish our canvass.
I have been a passive beholder of what has been going on upon deck,
my mind now and then recurring to the cause of my being here; and I can,
with humble gratitude, acknowledge that I feel myself free from any accusation,
believing I am in my proper place; and truly nothing short of this will do to lean upon.

After a series of boisterous and contrary winds,
we were favoured to anchor in the roads of Elsineur, about one o'clock, p.m.,
on the Second day, the 7th of Seventh Month, and the tenth day from leaving Hull.
The captain going ashore to clear at the Quarantine Office, I accompanied him;
and while he attended to his duties, I walked as far as Cronenburgh Castle,
also to a royal palace and garden not far distant.
Here I may remark the attention paid me by a young Englishman, an entire stranger to me,
who was very desirous of going about with me.
I soon found he wished to converse on religious subjects;
and I gave him all the opportunity I could.
Before we parted, I was strengthened to declare to him the way of life and salvation:
and may He who has begun the good work in his heart, be pleased to carry it on,
to the praise of His own great and excellent name,--for
it is His own works only that can praise Him.
I believe the language of our blessed Lord may be applied to
this young man,--"`You are not far from the kingdom of God.`"
We reached the ship in safety, between 11 and 12 o'clock at night,
taking a pilot on board with us.
If I should have been instrumental, in any degree, in fanning the immortal spark,
which I believe to be mercifully kindled in the
heart of this young Englishman at Elsineur,
I shall think myself amply compensated for coming so far.

Seventh Month 8th.--I think the Danish coast surpasses
all I ever saw before for beautiful plantations,
interspersed with houses, from Cronenburgh Castle to Copenhagen: at this place,
the devastations committed by the British fleet, under the late Horatio Nelson,
are still visible,
and are suffered to remain in nearly the same
ruinous state as they were left by our shipping.
The king's residence is principally here.
I observed at Elsineur a few solid countenances;
but I thought the generality of them seemed to be living as without God in the world,
and the faces of many plainly show the low price
at which spirituous liquors may be purchased.
The pilot, who brought us through the grounds, appeared to be a thoughtful man,
and conducted himself in a solid manner while with us;
my heart yearned over him as he left the ship,
and I could not help craving that the Divine blessing might rest upon him.

10th, Fifth day.--Fresh gales and fine weather; pressing forward before the sea and wind.
I felt myself rather unwell this morning,
and when I endeavoured to hold my solitary meeting in the cabin, I might have said,
as Mary did,--"`They have taken away my Lord, and I know not where they have laid Him.`"
But I trust I am endeavouring to learn in all states to
be content,--a very necessary qualification (however
difficult of attainment) for all poor finite beings.
In the afternoon, saw the Island of Gothland, and hauled to the northward a little,
to obtain a fresh departure from it.
In the evening, poverty of spirit and indisposition of body were my portion;
I retired to rest early,
and in the morning was favoured to feel my mind quietly resigned and comfortable,
and nature refreshed.

11th, Sixth day.--Off the east end of Gothland, still running before the wind and sea.
One of our sailors had managed, while we were at Elsineur, to get a supply of Hollands,
with which the poor fellow had kept himself in a state of intoxication,
and was twice dismissed from the helm,
for not keeping the ship in her course before the sea.
This man when sober is an excellent sailor,
and well knows how much depends upon the steering of a ship in these narrow rocky seas;
but such is his love of liquor, that his own life, the ship,
and all her crew may take their chance, if he can but get his darling grog.
He looks very grave at the helm this morning.

12th, Seventh day afternoon.--Gulf of Finland.
We are now very near a small island called Oxholm,
on which resides a respectable English widow,
who suffered shipwreck here about twenty years ago: her husband was captain of the ship,
and perished at the time.
She could never be prevailed upon to leave the island,
and by the interest of Admiral Greig, of the Russian navy, and his friends,
she was enabled to open a boarding school,
to which the children of very respectable English families in Russia are sent:
last year she had about forty scholars.
There are few other houses, besides those belonging to her establishment.
She has cultivated a piece of land as a garden; and from the view we had of it just now,
it wears the appearance of management and neatness:
she has also the care of the light-house close to her dwelling.
The island is not more than from three to four miles in circumference,
and only four leagues from the main land.

13th, First day.--Steering towards the island of Hogland, and expecting shortly to see it.
I have had my silent sitting in the cabin this forenoon;
but ships at sea are not very quiet places.
I was however favoured with a sense of my own weakness, and humbled therewith.
My mind has for these last two days begun to feel a burden upon it,
which increases as we draw nearer to Petersburg; and He only,
who sees the end from the beginning, knows what is to befall me there.
But I am fully sensible,
He will require no more than what strength and ability will be furnished to perform;
and I have abundant cause to trust in Him, "`who walks upon the wings of the wind,
and makes the clouds his chariot`"--who not only commands the storm,
but at His pleasure rebukes it, and causes the undulating waves to be at peace:
of which I have had renewed instances during our passage from England.
I have this morning thought more than usual of my dear wife and family,
desiring they might be comforted by the Great Comforter;
and I have traced some of them to their seats in Sheffield meeting,
among my beloved brethren and sisters; whom, though absent in body,
my heart is often with, and on whose account, I have frequently felt,
and still feel an affectionate interest,
that every age and every class among them may come to know Him,
"`who is from the beginning,`" and sit under His teaching;
whose teaching remains to be excellent,
to those who are happily found in the counsel of His will:--"`bread will be given them,
their waters will be sure,`"--even that bread which the world knows not of,
and that water which will be in them a well of water springing up into everlasting life.

Seventh Month 15th.--Arrived at Cronstadt.
After the ship was secured, we went on board an old ship of war,
fitted up as the Harbour Master's Office.
In the places where the public business is transacted,
are paintings of the saints richly ornamented,
before which the members of the Greek church repeat their prayers:
they make a point of bowing and crossing themselves as soon as they see them.
I observed the people, employed in the office, stared very much at me,
principally I believe on account of my wearing my hat.
On going into the presence of the Port Admiral, of whom I had to obtain a pass.
I observed he also noticed my hat; and finding he could speak English,
on his coming to inquire my name, I said,
I hoped the keeping on my hat would not be considered as intended disrespect,
and entered into an explanation of my reasons, for not taking it off unto man;
when he stopped me by saying, when it was omitted from any motive of religion,
he did not wish it.
I left Cronstadt in the steam-packet that afternoon for Petersburg,
and on landing there I was met by one of the Bible Society's agents,
who conveyed me to the Bible Office, the gift of the Emperor to the Bible Society;
at which place I was treated with great kindness and courtesy,
and found in it a quiet asylum for several days.

The next morning, I had an hour's conversation with Basil Papoff:
he is called 'his Excellency,' and I think with some propriety,
as he appears an excellent man.
He thought my business would go on slowly,
as the Emperor was so much engaged on account of the marriage of his brother,
the Grand Duke Nicholas.
I was introduced to the minister of the Moravian congregation here,
also to William Glenn,
who is going to Astrachan to translate the Scriptures into the Persian language.
I have also met another person from Scotland,
who I have since found is desirous of knowing the way of Truth more perfectly.

17th.--I traversed a considerable part of the city,
and went up the country opposite the summer palace of Kamenny Ostrof,
where the Emperor now resides.
I think the generality of the soil is better than I expected to see it.
I recognised clover and several kinds of grasses by the roadside,
and abundance of weeds in the gardens,
of pretty much the same kinds as we have in England.
In returning, we passed the hut that Peter the Great at one time inhabited;
and we saw the boat built with his own hands.
We passed through the public gardens, which are beautiful.
Most kinds of provisions are good here; but the water at this season is unwholesome.
Thirteen cart-loads of Bibles and Testaments have been sent off today for Moscow.

21st.--Took possession of a room at an inn kept by an Englishwoman.
Drank tea with an English family,
and had a good opportunity of explaining to the head of it,
the nature of our silent meetings, which was such as he had no conception of.
He had an idea that Friends went to meeting to meditate,
and he thought that might be done at home; and that on account of the young people,
we should, at any rate, read the Scriptures.
I told him we read the Scriptures to them at home.
He then concluded, it must be the bias of education,
that reconciled us to sitting in silence.
I replied it could not be so, as related to myself,
for I was brought up in what is called the Established Church of England.
This led to many questions on his part, all of which I was enabled to answer;
and best Help being near, I explained to him the nature of true worship,
and that there was at seasons a power to be felt, which was before words were,
and which will remain when words have ceased.
He asked whether I came to a knowledge of the truth,
while I was in communion with the Established Church.
No, I said, never while I was pestered with words.
I could not help inveighing against words,
as they seemed to place all their confidence and dependence in them.

Seventh Month 23rd.--Received a message that I
was to be introduced to Prince Galitzin today:
I had little time to spare for preparations, but had not many to make,
having no clothes but what I landed in,
my luggage having been detained at the Custom house.
I was accordingly conducted to the splendid mansion of the Prince,
the entrance and marble staircase of which were well lined with attendants;
in whose countenances surprise and anger were evidently depicted,
at my assurance in keeping on my hat.
We waited a short time in an open gallery, as the Prince was engaged;
and took a turn into a spacious room,
the walls of which were hung with pictures of all the imperial family of Russia,
from the first to the last.
In a short time a messenger came to say that the Prince was at liberty;
when we were ushered into his apartment of ample size.
The Prince came forward, and met us in a very courteous manner;
and on +++_______+++ introducing me, he took me by the hand,
and we retired to the back part of the room, and sat down at the end of a writing table.
He asked many questions with great affability in
Russian,--my companion interpreting between us.
Amongst others, he inquired what family I had; which being answered,
he wished to know whether I would bring them all with me, if I came to reside in Russia.
I said, 'Yes; I should not leave a hoof behind; at which he seized my hand,
and expressed his satisfaction.
He then inquired, how I should do,
as there was no place of worship for me,--no meeting--no society,--
how was that? I told him the worship of Almighty God was not confined
either to time or place,--that it is neither in this mountain,
nor at Jerusalem; but in every place incense should be offered to His name,
and a pure offering.
After pausing a little, he desired the sentence might be thoroughly explained to him.
He then seemed quite to understand it, bowing his head in a reverent manner,
and appeared to ponder over it.
In the midst of this, I found my mind drawn into silence;
but the Prince kept asking question after question, as if afraid of losing time:
my answers were now very short; and at last,
I endeavoured to explain to my companion the situation I was in,
but could not make him understand me.

The conversation then turned to agriculture, and the soil of the neighbourhood,
and to the Emperor; but as a burden still remained with me,
I cannot recollect all he said, or what answers I made him.
At last, we rose from our seats as with one accord;
but before the Prince had time to bid me farewell in his way, I found my time was come:
and I was enabled to declare unto him the everlasting foundation,--even Christ Jesus,
the rock of ages,--who was "`to the Jews a stumbling block,
and to the Greeks foolishness;`" but to them that obey his
gospel inwardly revealed in the secret of their hearts,
Christ crucified, the power of God, and the wisdom of God unto salvation.
As I stopped at the end of every sentence, my companion interpreted,
as if he had been accustomed to the work, and might have known what he was going to do.
After we had finished, we stood like statues for a short time; and on my moving,
as if I was at liberty, the Prince took me by the hand, saying,
'although our languages are different,
the language of the Spirit is the same.' He held my hand till we got near the door,
when I bade him farewell, and departed, comparatively as light as a feather.
I cannot but admire how I was guided; for in delivering what was upon me to the Prince,
at the end of every sentence, all was taken from me,
as if I should have nothing further to say;
but when +++_______+++ had had sufficient time to interpret,
then a supply was again vouchsafed.
Whereas if I could have proceeded, as it were without stopping,
I should have overpowered the interpreter,
and the work would have been marred altogether.
Thus the blind are guided in ways that they know not,
and in paths that they have not seen:
but truly the pillars of my tabernacle were mightily shaken.
May I ever be preserved in that humility,
through which alone the grateful heart can bless His holy name;
"`who redeems our lives from destruction,
and crowns us with loving-kindness and tender mercies.`"

In the afternoon,
I met with some very humiliating circumstances
in the course of my business at the Custom-house,
which helped to keep under the creaturely part.

[.offset]
+++[+++From this time to the 10th of Eighth Month,
Daniel Wheeler was employed in examining the waste crown lands
and the marshes in the vicinity of the capital,
in preparing reports of his investigations, etc.]

Seventh Month 27th, First day.--After I had sat down in my room to hold my meeting,
I was interrupted by the coming of an individual, whom I had before seen.
He resides about twenty versts from hence,
and had come on purpose to inquire into the principles of Friends.
He had once had a sight of 'Barclay's Apology,'
but was never able to get it a second time,
and I much regretted I had not one to give him.
He is well acquainted with the Scriptures,
but very desirous of having them expounded and explained.
After a long conversation, I referred him to the never-failing and only key,
the Holy Spirit, by which they were given forth,
and without which the natural man will ever read them in vain,--or when he has done,
if he thinks he knows any thing, he knows nothing as he ought to know.
He gave me a kind invitation to his house, and we parted in a friendly manner.

Eighth Month 3rd, First day.--I spent the day at home in retirement.
In the evening the city was illuminated,
and I understand there was a great display of fire and
water-works at the country palace of Peterhoff,
on account of its being the saint's day of the Dowager Empress Mary.

On the 15th, I began a letter to my dear wife, and had finished two sides of it,
when I seemed quite at a loss for a subject, which I could not account for.
I went into the yard, and walked up and down for fresh air; but had not been there long,
when I received a message, that the Emperor would see me that afternoon,
and that I was to be at five o'clock at the lodgings of Prince Galitzin,
which are close to the gate of the palace of Kamenny Ostrof.
Having been kindly assisted in procuring a conveyance, I was there in time,
and the Prince received me with his usual openness.
In about half an hour a messenger came, and (bareheaded) conducted me through the garden,
and the different guards, who stared at me not a little.
At last we entered the palace, and after going through a range of rooms,
I was shown into the apartment of the Emperor,
who received me with more parade than I expected;
but I thought afterwards this was only on account of the page,
for as soon as the door was shut, he took me by the hand, saying, 'Sit down,
sir.' I was not however, quite ready to sit down; for the salutation arose in my heart,
of "`Grace, mercy, and peace be multiplied, from God the Father,
and our Lord Jesus Christ,`" upon the noble Emperor, etc.
As I proceeded I took off my hat, and the Emperor stood quite still,
until I had finished; when we both sat down.
He had several questions to ask,
and expressed his surprise and satisfaction at
the manner in which I had been led into Russia.
I had a great deal to say to him,
and full opportunity to express every thing that arose on my mind.
He mentioned my memorial, and I think touched upon every particular head distinctly,
and said he agreed to the whole.
I then gave him a paper I had ready in my pocket book,
which brought the peculiar principles of our Society into view; this he read,
and questioned me about all of them; which gave time to clear myself fully.
I had a good deal to say to him on silent waiting.
I remember my last words were, the expression of a desire that attended my mind,
"`that when time shall rob you of your earthly crown,
an inheritance incorruptible and undefiled--a crown immortal,
may be your happy portion.`" He held my hand fast in his for some time,
and did not utter another word.
I then returned to Prince Galitzin, and on taking leave,
I had a little matter to express to him, which, +++_______+++ who was present, interpreted.
The next morning, I finished my letter to my wife, in time for the post,
and thought myself clear of Petersburg: but in the evening,
I found something like an invitation to such of the
English people as inclined to sit down with me.

The next day, after dining with J. Paterson, he invited me to go to hear their sermon,
which I declined; but afterwards I told him,
that if his friends inclined to sit down with me in a large room at the Bible Office,
if I had any thing for them they should have it, and if not, they must forgive me.
It was accordingly fixed that we should meet at seven o'clock the next evening.
I repaired there about the time,
and found a larger number assembled than I had any expectation of,
including four ministers of the Independent denomination.
Scarcely an individual amongst them had sat in silence before, in this way: it was,
however, exercising to me, and we had a solemn sitting.
I was enabled to declare the truth amongst them about three-quarters of an hour,
to the relief of my own mind, and the sitting ended well:
there seemed something like an unwillingness on their part to break up: I was, I trust,
thankful when it was over.

The forepart of the 18th and 19th instant, was employed in taking leave of my friends,
and preparing for my homeward voyage.
On the 20th, I went down to Cronstadt by steam-boat,
and proceeded at once on board the Fortune, a fine ship, for Hull.
I concluded to remain on board, although the ship was not quite ready for sea; and,
as night came on, I began to be very uncomfortable,
and was fearful I had been making more haste than I should have done,
and that in my hurry I had not hit upon the right vessel.
I walked the deck till late,
and a willingness was wrought in my mind to quit the ship in the morning, if required.
This exercise, being amongst entire strangers, made the pressure very heavy.
I retired to my cabin, and got some rest, and when I awoke in the morning,
I found my accusers were all gone, and tranquillity again restored;
for which I was thankful.
Going on shore in the course of the day, I found a long looked for letter from home,
and thankfulness was raised in my heart to the Giver of every good and perfect gift,
for the cheering account it contained.

Eighth Month 23rd.--We got out of the Mole this morning,
and having been boarded by the guard-ship,
by eleven o'clock all impediments were removed, and we proceeded down the Gulf,
with a fair wind.

24th, First day.--When I awoke in the morning, I found the ship was rolling,
which she would not have done if the wind had not been fair, and the sea following us;
so that I got up cheerfully.
I went into my state room in the forenoon;
but found I could not get into any settlement of mind.
The thought of proceeding homeward with a fair wind was
too much for me to be able to keep out of view;
but I trust the Father of mercies saw my weakness with his eye of compassion.

31st, First day.--Having no opportunity of sitting down in the cabin,
I held my sitting upon deck; and though I met with many interruptions,
yet I was favoured with settlement of mind in a good degree.
In the afternoon, rounded the Falsterbo Reef, on which lay the wreck of a large ship,
and at five o'clock made a signal for a pilot to carry us through the grounds;
but could not perceive one coming off to us.
As I was walking the deck, it just passed my mind, how soon our prospects are blighted;
and going to the quarter-deck, I heard the sailor who was heaving the lead cry,
"`by the deep four, a quarter less four,--by the mark three,
a quarter less three,`"--and immediately after I felt the ship strike on a rock;
in a few seconds she struck a second time, and then stuck fast.
The crew were of course all in a state of consternation,
and the captain was almost speechless; and indeed it was a serious moment,
for the ship was under full sail when she struck, and on a lee shore too.
The first thing was to take the sails off her; then the boats were lowered,
and two anchors carried out with strong hawsers.
During this time several ships passed,
to whom our captain waved his hat by way of signal to keep off;
and very mortifying it certainly was, to see the different ships take in their pilots,
and make sail.
Soon after, a large boat full of men approached, with whom, the captain agreed,
after hard bargaining, to carry out a large anchor for us: this took up some time,
and as night came on, the wind rose, and things began to wear a gloomy aspect.
I was favoured however to feel quietness cover my mind like a canopy;
and a petition arose in my heart to the Father of mercies,
to bless the endeavours of the toiling crew.
While the Danish boat was receiving the anchor and cable, finding I could be of no use,
I went below, and stretched myself on the locker, with my arm supporting my head.
I continued in this position till the sailors began to heave upon the cable; and,
at length, I plainly felt her keel grate upon the rock.
Being fully satisfied that she moved, I hastened on deck with the pleasing intelligence.
Shortly after one in the morning the ship floated, and was soon in deep water again,
which was cause of humble thankfulness.
We anchored in Elsineur roads the same afternoon.

[.offset]
+++[+++The voyage to England was completed in safety.]
