== Chapter VIII.

[.chapter-synopsis]
* Address to Balby Monthly Meeting in 1822 and in 1823
* Visit from the Emperor, etc.
* Great Flood at Petersburg

[.embedded-content-document.letter]
--

[.letter-heading]
To Balby Monthly Meeting

[.signed-section-context-open]
First Month 20th, 1822.

[.salutation]
Dear Friends,

Being once more permitted to send you the answers to
the queries from our little company in this land,
my mind is renewedly and affectionately turned towards my dear brethren and sisters,
whom I have long and tenderly loved; for whose welfare every way,
an unabated solicitude remains, and I trust will ever have a dwelling-place in my heart.

Great indeed is the weakness, and painfully discouraging the feelings I am under,
on the present occasion.
"`What could have been done more to my vineyard,`" than has been done unto it,
is the language that presents itself to my mind.
In the breast of every individual capable of reflection,
I believe the acknowledgment will be found--"`Nothing, Lord.`" None can say,
knowledge has been lacking;
for "`the grace of God which brings salvation has appeared unto all, teaching`" all:
"`precept upon precept, line upon line,`" have been abundantly administered.
How unavailing and ineffectual will be the feeble efforts of one,
who feels himself less than the least of all the flock and family,
to stir up the pure mind in any,
to a remembrance of things that are excellent--things that accompany life and salvation;
when so many dignified servants have hitherto pleaded
the blessed Master`'s righteous cause in vain.
How many of the Lord`'s deeply baptized,
faithful messengers have been sent from time to time,
to "`cry aloud and spare not,`"--clothed with indisputable authority to preach, rebuke,
exhort;--and in that love which causes joy in the presence of the holy angels,
beseeching us to be "`reconciled unto God.`"
What could have been done more,
that has not been done? We ourselves must testify against ourselves,
to the truth of this.

Dearly beloved Friends, consider what I say; and the Lord give you understanding hearts,
rightly to estimate the greatness of His love and mercy.
"`May the Lord direct your hearts into the love of God,
and into the patient waiting for Christ,`"--strengthen your faith in Him,
and enable you to obey His voice; lest His glory should depart from Israel,
and nothing be left but a name.

Be pleased, O Lord! to remember them that sigh.
Be with your little ones, wherever scattered;
who for Zion`'s sake cannot hold their peace, and for Jerusalem`'s sake cannot rest;
"`until the righteousness thereof go forth as brightness,
and the salvation thereof as a lamp that burneth.`"
Strengthen them to cry day and night unto you: sustain, support, and comfort them.
Bless them, and continue with them to the end; and crown them with everlasting glory.

[.signed-section-closing]
So prays your affectionate Friend and brother,

[.signed-section-signature]
Daniel Wheeler

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Elizabeth Robson^
footnote:[It may be worthy of remark, that Elizabeth Robson,
to whom the letter is addressed, expired the very day on which it was written.]

[.signed-section-context-open]
Tenth Month 27th, 1822.

My Dearest Eliza, Notwithstanding I have hitherto been silent,
the affecting events which have taken place since we last saw each other,
have not been suffered to transpire unregarded; on the contrary,
they have only served to heighten that love and affection,
which have long dwelt in my heart towards you, and your dear brothers and sisters.
Believe me, my dear niece, that through all, you have had my nearest sympathy;
and that I have participated most feelingly and sincerely in all the painful afflictions,
which "`the Father of mercies and God of all comfort,`" has in
His unsearchable wisdom been pleased to dispense unto you;
although I have been dumb as to the expression of it by letter.

Often has a secret petition been raised in my heart for your protection and preservation,
to Him,
whose Almighty power can sustain our minds through
every conflict;--who will not break the bruised reed,
nor suffer it to be broken.
When contemplating your situation,
I am often comforted by a knowledge of the many near
and dear relations and friends who surround you,
who are affectionately careful and solicitous for your welfare every way;
but my greatest consolation arises, from a firm belief,
that you are indeed the peculiar objects of Divine regard.
Ah! my very dear Eliza,
what a blessed privilege to be under the superintending care and oversight of Him,
who slumbers not: such, though cast down,
are not forsaken in the day of trouble;--resignation`'s healing balm,
which soothes the keen anguish of an afflicted mind,
in purest love is given:--not a tear, not a sigh, escapes His ever-watchful eye,
in those who strive to bow in meek submission to His holy righteous will.
How do I long that I could find words to convey
the sweet consolation which pervades my mind,
when turned towards you: it cannot be expressed.
"`Behold the tabernacle of God is with men,`"--is the language that arises in my mind,
while dwelling under the precious influence of this feeling;
and I humbly pray that it may be richly verified,
to your inexpressible comfort and delight, and to the admiration, gratitude and praise,
not only of yourself, but of all your dear connections and friends.
It is the broken,
contrite spirit that the Lord regards;--it is the heart
that wears the costly robe of sweet humility,
in which the lowly Jesus makes His blessed abode.
O the riches of His grace! It is peace, joy and love;--that precious peace,
which the world with all its perishing enjoyments,
however splendid and specious in appearance, cannot give; and,
blessed be the name of the Lord the only Giver,
neither can it take one particle away:--that joy,
in which the ransomed and redeemed only can rejoice,
"`unspeakable and full of glory`"--that love,
which enlarges the heart, and casts out all fear,--even the love of God,
through Jesus Christ our Lord, to the children of men.
"`He will dwell with them, and they shall be His people,
and God himself shall be with them, and be their God.
And God shall wipe away all tears from their eyes; and there shall be no more death,
neither sorrow, nor crying, neither shall there be any more pain:
for the former things are passed away.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend Under Affliction

[.signed-section-context-open]
Eleventh Month 22nd, 1822.

I have been for many months desirous of writing to you;
and be assured that my silence has not arisen from any diminution of love or regard.
On the contrary, the fight of affliction you have had to pass through,
since we last exchanged letters,
has rendered you more than ever the companion of my thoughts,
with increased affectionate solicitude; and yet it is only of late,
that I have come to the determination of addressing you.

Now, my dear friend, I hope I shall not awaken feelings of a painful nature,
as from my own weakness and poverty I feel more than usually
incapable of administering the smallest ray of comfort,
or of lulling them again into quietness and repose.
But, while it is not in my power to strengthen,
I trust I shall be preserved from weakening or lessening, in any degree,
your confidence in Him; who has been pleased to strip you of, I believe,
your greatest earthly treasure.
How mysterious to our poor finite comprehension, are the ways of Infinite wisdom,
to prepare and purify us for an inheritance, incorruptible and undefiled,
and which will never fade away!
How difficult it is for us, in the hour of dismay and extremity, to distinguish,
that the arm of everlasting mercy is still underneath for our support:
but as humble resignation and submission to that Holy Will which cannot err,
are patiently sought after,
the poor tossed mind becomes mercifully strengthened to look unto Him, who gave,
and who has been pleased to take away;--and to say in the depth of humility,
Amen,--Blessed be the name of the Lord!
This, I trust, has been your sensible experience, my very dear friend,
long before this time;
and that patient fortitude has conspicuously shone
forth to your sympathizing relations and friends:
that they who have been eye-witnesses,
may also have been partakers with you of that tranquil and peaceful resignation of mind,
which sheds a lustre, consoling, comforting, and animating to all within its sphere.
It is this that designates the true Christian,--rising with increased brightness
through the gloom of affliction,--lowly and weak in self-estimation,
and poor indeed,--disrobed of self and what self most
delighted in;--but ah! how rich in heavenly garb,
attired and decorated with the costly gem of sweet humility,
which has been won by keenest suffering, and which suffering alone can purchase!

These last seven weeks I have suffered from rheumatism in my right arm,
which has deprived me of much sleep: while it takes from my rest,
it allows a larger portion of time for reflection,
and I hope will teach me to number my days;
and if happily I am found applying my heart unto wisdom, it will be a blessing indeed;
that so the day`'s work may be finished, when the night draws nigh.
For truly I am often filled with fear on this account, finding yet much to do,
and many things alive, which ought to have been long ago slain.
And O! the weakness and poverty that I daily feel! and the absence of that ability,
which can alone qualify for every good thought, word and work!
If under feelings of this kind long dispensed, there be no cause for discouragement,
then may I hope yet to praise Him, who was the health of David`'s countenance and his God.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Friends of Balby Monthly Meeting

[.signed-section-context-open]
First Month 23rd, 1823.

[.salutation]
Dear Friends,

I herewith enclose our answers to the queries which are
usually considered at the Spring Quarterly Meeting,
and at the same time am desired to acknowledge the
receipt of your certificate on behalf of +++_______+++.

On looking towards my dear brethren and sisters,
I am thankful in feeling a degree of that love, which alters not by separation,
neither is subject to change amidst the vicissitudes of time;
in which I once more salute you, with desires for your present and eternal well-being.
Under a humbling sense produced by the recollection of those precious seasons,
when I have been permitted to assemble with you,
previously to the Spring Quarterly Meeting in each year,
I am induced to bring to your remembrance the days that are over and past.
Nearly five years have glided away,
since I saw the well-gathered assembly on such an occasion;
at that time there were many vacant seats,
which had been occupied by faithful labourers in
the Lord`'s vineyard both in word and doctrine,
and by those who were in their day and generation fathers and mothers in our Israel.
During this period, others also of blessed memory have been called away,
who "`rest from their labours, and their works do follow them.`"
In thus calling to mind a succession of Friends whom I knew and loved,
who have sooner or later finished their earthly course, fought the good fight,
and kept the faith, for whom a crown of righteousness is prepared;
I feel an engagement of mind,
that those who are left a little longer in this scene of conflict,
may be thereby encouraged and strengthened to persevere in following Him,
in whom they have believed; that they also, at the end of their race,
may obtain the immortal prize.
And Oh! my beloved Friends,
upon whom the weight of the precious cause of truth and righteousness must soon devolve,
when the few remaining pillars of the present day are gathered to their everlasting rest,
how earnestly do I desire that you may be aroused to preparation,
by a deep sense of the important station that awaits you.
Let me entreat you seriously to consider, how far the time and talents,
so richly and so mercifully bestowed,
are employed and devoted to the service of the Most High God;
and whether the many vacant places would have remained unfilled up to the present day,
if obedience had kept up with knowledge, which has been from time to time vouchsafed.
To the just witness in every heart I appeal, and in tender love I refer you.

And dear brethren and sisters, I wish to press it not only upon heads of families,
but upon all who are capable of reflection, to lay these things to heart;
for it is a glorious cause in which all are or ought to be concerned,
inasmuch as all are called to glory and virtue.
Let these things sink deep in your minds,--let
them have a place equal to their vast importance.
How great is the responsibility, how awful the consideration,
that by the influence of your example in faithfulness and upright walking,
and by your religious care and oversight,
the precious young people may be induced to choose the "`Lord for their portion,
and the God of Jacob for the lot of their inheritance.`"
Of ourselves we can do nothing;--but dear Friends,
help is laid upon one that is mighty to save and to deliver:--
unto Him all power in heaven and on earth is given;
even our Lord and Saviour Jesus Christ,--the blessed medium of access to God!
He has graciously declared,--"`Him that comes unto me, I will in no wise cast out.`"
All things are possible with Him: counsel is His,
and sound wisdom:--He is understanding:--He is strength.
What then remains, but for us, in humble prostration of soul,
to draw nigh unto Him? By yielding simple obedience to His Divine requisitions,
this work of eternal consequence begins.
It is not limited to a chosen few; it is extended unto all:--"`What I say unto you,
I say unto all, Watch.`"
The watch, with constancy maintained, will lead to prayer.
Praying always with all prayer and supplication in the Spirit, and watching thereunto,
will lead the soul to God; to whom all power belongs.
"`Blessed will be those servants who are found so doing.`"
Great will be their peace while here; glorious their reward hereafter.
They will be numbered with those, that shall shine as the brightness of the firmament,
and amongst them, who,
turning "`many to righteousness,`" shall shine as the stars forever and ever.

[.signed-section-closing]
I am your affectionate friend and brother,

[.signed-section-signature]
Daniel Wheeler

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard Cockin, Doncaster

[.signed-section-context-open]
Eighth Month 6th, 1823.

Day after day passes away,
leaving accumulated cause to regret how much I am indebted to you,
my dear and long loved friend;
without being able to give you an assurance of my unabated love,
or to acknowledge the receipt of many affectionate tokens of remembrance,
which have from time to time been conveyed in your acceptable and welcome letters;
all of which, though unreplied to,
have been regularly received with gratitude and renewed feeling of affection.
I have long meditated writing to you, but have always been prevented; now, however,
I have once more taken up the pen, and must endeavour, in some degree,
to account for such apparent neglect.

Laying aside all other causes, which time and paper will not permit my bringing forward,
I must inform you that sickness has hung about
our dwelling since the middle of last winter.
The severity of the weather laid us all by for a time; but as spring opened,
all the invalids came about again, with the exception of my dear wife and my Joshua,
who lingered on until the fine weather fairly opened, and seemed likely to recover;
but great heat coming suddenly upon us,
their already weakened frames could not support it.
Every means was tried which a skillful physician could devise,
without any material benefit being visible:
returning to England seemed the only alternative he could point out.
I believe nothing could have induced my wife to leave us,
but the hope of the change being beneficial to her son; however,
she at length came to the resolution to make the attempt,
and accompanied by my daughters, they sailed for London, on the 18th of last month.
I was three days on board the ship with them, previously to their sailing,
but was obliged to return home the evening before they got to sea:
although this was a disappointment, I was very glad I had been with them,
as the first night they slept on board,
there was the most dreadful storm of thunder and lightning I ever witnessed.
I felt thankful I was with them, for I think they would have been quite terrified,
if they had not had somebody to cheer them a little.
I hope by this time they are in sight of the '`white cliffs,`'
and I shall rejoice to hear of their safe arrival.

I am grieved to find the character of our Emperor does
not stand so high with many in England as it did;
and fully believe he has been prompted by evil-disposed
persons to do things that he does not approve of,
and would not have done, but at their instigation.
We know of no difference here,
in respect to the government of the internal affairs of this country.
I think his judgment has been biased by some of the other crowned heads,
with whom he has of late associated: at the same time there is reason to believe,
he has seen through some of their devices.
I only wonder how he bears up, amidst the many difficulties that surround him;
and the constant exercise of moderation, patience, and forbearance,
he is in the daily practice of, is to me extraordinary.
The manner in which he is imposed upon by many who enjoy his confidence,
would scarcely be believed in its full extent.
With my work, and as regards myself, I find no lack of assistance,
when any thing that requires his aid is brought to his knowledge.
I have frequently seen him passing on the road, since he returned from Verona.
A few weeks ago, I was looking at some oats pretty soon in the morning,
in the neighbourhood of a pavilion to which he
was going with the Dowager Empress to breakfast;
and they passed close by me in a low carriage with a pair of horses.
He looked very well; and I observed he pointed me out to his mother.
I am at present much occupied in the neighbourhood where he mostly resides in summer,
about seventeen miles from Petersburg; and ten days ago,
while laying out some ground in a wood, which is preparing for cultivation,
a carriage stopped near the part where I was.
My William was near, and called to me that it was the Emperor.
On seeing him alight and spring over the ditch towards the place, I went to meet him.
He gave me his hand, and immediately entered into conversation with his usual freedom.
One of his Generals followed him; but it appeared to make no difference in his manner.
He remained for some time, made many inquiries about my family;
and having no doubt remarked our hay crops,
he said,--"`You will have more hay than all the people in the
neighbourhood.`" I mentioned the indisposition of my family,
and that my wife was gone to England: he seemed a little surprised,
and directly asked if she would return.
I said she intended it.
He appeared greatly interested in my report of the abundant crops upon the ground.
Last year there was quite a dearth of fodder in this neighbourhood;
a large number of cattle were lost for lack of food.
After explaining to him what were my plans relative to
the parcel of land on which we were standing,
he shook me by the hand, and said,
"`I will let you do what you like.`" I understand that the next day he
made some inquiry as to the cause of the sickness among us,
and having learnt that it was occasioned by the coldness of the house in which we live,
he gave orders that it should be altered immediately.
On the third day after the interview, an architect arrived, to ascertain what was needed;
and we are now well stocked with bricklayers, carpenters, and the like.

I believe I have long been partaker of the tender sympathy of my friends in England;
but I think I never knew a time when I stood more in need of it, than the present.
Exclusive of domestic enjoyments, I have long ceased to have any delights,
the loss of which would give me an hour`'s pain or thought:
in the bosom of my family was to be found all
that could afford me gratification or comfort.
With them about me, I had everything I could wish for or desire,
in this state of mutability.
The compact is, however, unexpectedly and suddenly dissolved,
and one-half diminished as in a moment.
I have, however, one consolation, which is, that they will not feel it as I do: they,
if permitted to reach their native land in safety,--strengthened, I humbly hope,
through heavenly goodness and mercy, by the sea air,
and their health in some degree restored,
will be cheered and comforted by the countenances of many dear relations and friends.

I confess my prospects here wear a very different aspect;
but I trust I have in some degree learned in all states to be content.
There is, my dear friend, and without any inclination to boast,--I believe I may say,
I know there is,--a soul-solacing presence to be felt in a retired and lonely mansion,
as well as in a place where large assemblies crowd; which,
unbounded and unlimited by time and space, extends to every clime, to every place,
to every heart:--and O! says my soul in humble prayer,
may it be felt by us all!--that all our hearts may be so cleansed,
so prepared and purified from every defilement,
as to be in constant readiness to receive the heavenly guest.
That the whole human race may be brought to the same blessed experience,
is the earnest desire of your tribulated friend at this moment of time;
that all may have life, that all may be washed, that all may be sanctified,
that all may be "`justified, in the name of the Lord Jesus,
and by the Spirit of our God.`"

I must now come to a conclusion, after saying,
that although my dwelling is in low places,
I am frequently favoured to feel humble resignation of mind; at the same time believing,
that the hand of the Lord is in the present dispensation,
I can freely commit my all to His divine disposal,
who I am persuaded will not break the bruised reed.

To your dear wife and family I beg to be remembered in love unfeigned,
and assuring you that you are included in the same.
I remain your affectionate friend,

[.signed-section-signature]
Daniel Wheeler

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Smith, Sheffield

[.signed-section-context-open]
Second Month 16th, 1824.

Your last letter came duly to hand, and was welcome indeed: my beloved invalids,
it is true, had furnished me with repeated accounts of their improving health;
yet to receive a confirmation from an affectionate eye-witness of the same,
demands every acknowledgment of which I am capable,
for your kindness in thus adding to our comfort and consolation.
You have no doubt heard before this time,
that a variety of circumstances combine to prevent my projected visit to England,
which I most sincerely regret: although it must have been short,
and professedly to accompany my dear family back to this country,
as I could but have had a short space of time to perform it in,
and of course should have seen but few of the faces of my Friends,
and comparatively for a moment only; yet this would have been very precious to me.
Our present solitary situation may be better imagined than described;
I need not advert to it, except to acknowledge with gratitude and thankfulness,
the preservation and support we have witnessed.
I hope most sincerely, that the journey of my dear wife and children to England,
will be productive of much future comfort;
not only through the restoration of the health of the invalids,
but by causing a renewal of affectionate regard and interaction with our friends; which,
I trust, will be strengthened and increased, by a more frequent interchange of letters,
which will have a tendency to keep alive feelings of love and sympathy for each other.
I remember very well, it was the advice of our dearly beloved friend, Stephen Grellet,
when in this country,
that we should make a great point of keeping up
a correspondence with our Friends in England.

I am quite aware, my dear friend, that you must sensibly feel the loss,
when your beloved niece is removed from under your roof; but you need not fear,
you will be cared for: you have cared for many; her place will be filled, I believe,
to your comfort and admiration.
I sometimes think that heavenly goodness and
loving-kindness are plainly evinced in these things,
and all in love and mercy to us poor creatures,
gradually and progressively to separate us, and more perfectly to wean us,
from every sensible delight,
even from things which may at one time have been graciously dispensed,
and whereon our affections may have been properly and lawfully fixed.
In infinite wisdom they are withdrawn, for our farther refinement and purification,
that our minds may become unfettered and loosened more
and more from the things of time and sense;
that nothing may hinder or stand in the way of
the complete removal of all that can be shaken,
that those things only which cannot be shaken may remain,
which are founded on the immutable Rock;
and that the great and good God may be all in all.
So that we may not only have our lamps trimmed and lights burning, but,
like the wise virgins,
we may be ready and looking for the coming of the heavenly Bridegroom;
at the same time prepared to wait, should the time be prolonged,
having a supply of "`oil in our vessels with our lamps.`"

--

[.offset]
+++[+++In the following letter he speaks of the safe return of his wife and party from England.]

[.embedded-content-document.letter]
--

[.letter-heading]
To John Hipsley, Hull

[.signed-section-context-open]
Fifth Month 31st, 1824.

I have now the pleasure of informing you,
that we were much surprised by the arrival of the Fanny, after a passage of sixteen days,
as we had had a succession of easterly gales.
She was quite unlooked for on our part.
A little before bedtime, on Fourth day, we were roused by the sound of wheels;
but had not the most distant idea who our guests could be.
There were only a few moments to think about it,
before the whole party were in the house;
and our surprise and joy may be more readily conceived than described.

As I have once more got them safe at home,
I may now tell you somewhat of the trial of faith, patience, and feeling,
under a lengthened-out sickness, which I have had to pass through for several months.
It is near four months ago that I became seriously ill,
and at one time there seemed little probability of my struggling through,
until my wife could reach her home;
but as I could not bear the thought of making her uneasy while in England,
and without a possibility of getting to me or affording any relief,
I took great pains to keep it from her, either in letters from us,
or from any other person that I knew was writing.
At times, when at the worst, I blamed myself for having withheld the information,
as it seemed almost presumptuous to suppose I should recover; but at seasons I had hope:
and I trust I can in some degree adopt the language of the Psalmist,
and say,--"`The Lord is my strength and my shield; my heart trusted in Him,
and I am helped:`" and great cause I have to ascribe all to his goodness and mercy,
and to put my trust and confidence in Him.

I had intended visiting England this spring, attending the Yearly Meeting,
and bringing home my family in the summer; but the Lord prevented me, and not man,
as I had every permission that man could give me.
This reconciles all, and raises consolation in my mind,
and a hope that I am still an object of his divine compassion,
although under a humiliating sense of my unworthiness.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To David Mallinson, Sheffield

[.signed-section-context-open]
Tenth Month 25th, 1824, O. S.

According to expectation our dear friend Thomas Shillitoe arrived about seven weeks ago,
and seems very comfortable amongst us.
All who have seen him are much pleased with him;
and his having brought no books with him has prevented much trouble,
and removed all suspicion far away.
He is remarkably furnished with a sense of things in this place,
and acts with the greatest prudence and caution.
The more we know him, the more we love him;
his conduct and conversation are altogether consistent with his profession,
without which he would make little impression on the minds of the people,
whose views and expectations are altogether outward;
and they take more notice of external appearances perhaps,
than the people in England or in other nations further
advanced in civilization and religious sensibility.

--

[.offset]
+++[+++The awful visitation upon the City of Petersburg,
by the great inundation in the Eleventh Month, 1824, is thus described:--]

[.embedded-content-document.letter]
--

[.letter-heading]
To John Hipsley, Hull

[.signed-section-context-open]
Eleventh Month 11th, 1824, O. S.

As it is probable that accounts of an alarming nature,
relative to the situation of this neighbourhood will shortly reach England,
and knowing from experience the lively interest which
yourself and family at all times take in our welfare,
I thought I would prevent your being disturbed with unnecessary fears,
occasioned by imperfect statements, as to our personal safety.

On the 7th inst.,
the inhabitants of Petersburg experienced the most awful visitation
that has ever occurred within the memory of the oldest person living,
by a deluge, which threatened for several hours the destruction of the city and suburbs.
A dreadful tempest came on during the night of the 6th from the south-west,
and continued to rage with unabated fury nearly the whole of the next day.
Two days previously,
an unusual roaring of the sea had been noticed about the head of the Gulf of Finland,
and at Cronstadt.
On the morning of the 7th, the sea began to rise,
and shortly afterwards to push its waves into the heart of the city.
The people at first supposed it would only be
one of the floods which have frequently occurred,
and manifested no particular alarm; but before noon,
they became convinced of the necessity of flying for their lives.
The road we live on exhibited a scene of terror and dismay not easy to describe:
every one anxious to save himself and his cattle.
As our situation is somewhat higher than the city itself,
we had many applications for food for the cattle and shelter,
which of course we were glad to comply with.
Our neighbourhood was protected from sharing in the
general calamity by the bank of the Ligofsky canal,
which is raised above the regular surface of the country;
but from the upper part of the house we could see over this bank,
which discovered to us the city, standing as it were in the open sea.

The water continued to rise until three, p.m., when the wind shifted to the north-west,
and although its violence continued, it prevented the water from rising any higher.
At that time the water was twelve feet deep in the main street on Vasily`'s Island.
Buildings consisting of only one story were of course filled;
and the frightened occupants obliged to take refuge upon their roofs.
In the afternoon, we made some attempt to go towards the city;
but found it unsafe to try much further than the bank of the canal just mentioned.
The land under our care, between this and the city, was nearly all under water,
so that we could hear nothing that night of the distress which prevailed there.

By the morning of the 8th, the water had subsided so much,
that it could only be seen about the low places;
in the afternoon I went off intending to see how our friend Sarah Kilham had fared,
but after passing the barrier, I was compelled to return,
as all the bridges were carried away by the force of the water.
The 9th (a First day) arrived,
and brought only our dear friend Thomas Shillitoe to meeting; who,
although he knew enough of the general suffering to prevent his
speaking for a short interval on first coming into the room,
yet knew almost nothing in comparison of what has since been unfolded.
The part where dear Thomas lives, stands pretty high,
but in those streets the water stood only eighteen inches below the lamps.
For three hours, a general silence prevailed in the city;
and from Thomas Shillitoe`'s windows, which command a view of four streets,
nothing was to be seen but one poor struggling horse,
and the police rowing about in boats to see where any assistance could be rendered.

Our land before hinted at, is covered over with timber, boats, dead horses, cows,
barrels of fish, crosses from the grave yards, parts of coffins, and other articles,
and I regret to add, with many human bodies, drowned by this disastrous flood;
one is a female with a child under each arm, which she was endeavouring to save.

It is now Third day night: I have been both today and yesterday in the city,
and have heard such accounts of accumulated suffering, as are impossible to be set forth.
I fear the number of lives lost will amount to ten thousand,
and the loss of cattle and property is estimated at 20,000,000 roubles,
(£800,000 sterling.) Whole squadrons of cavalry horses were drowned in their stables,
and many saved by being led up stairs.
One Englishman, a horse dealer, has lost all his horses.

When the water began to rise above its usual height in floods,
the Emperor went in person, and ordered the sentinels away from the different posts.
When the palace became surrounded by water many feet deep,
he appeared with the Empress on the balconies, encouraging the people to exertion,
and offering rewards to those who would endeavour to save life,
wherever he saw any particular danger: by this, many were saved,
who would otherwise have been inevitably lost.
A subscription has been begun today for the benefit of the sufferers,
to which the Emperor has given 1,000,000 roubles (,£40,000
sterling;) and he has ordered the military governor to take
care that the poor people are furnished with food.
Yesterday, it was difficult to procure bread,
as the bakers`' ovens were mostly deluged by the water; today, there is a supply.
All the sugars at the Custom-house are melted,
and all goods that will damage with water are spoiled.
The shops in many places were full up to the ceilings:
oats which have been under water in the stores,
are selling at two and three roubles (from 20 to
30 pence) the chetvert of five English bushels.
The inhabitants and houses of three villages near the Gulph, are with their cattle,
said to be entirely swept away.
The Emperor has been today to several places, where the greatest suffering has occurred,
to devise relief for the people.

However affecting this visitation may appear, I cannot but view it with a hope,
that it may yet prove a blessing in disguise, to those that remain:
and I very much desire that it may have its proper and lasting effect upon all our minds;
that so all may repent, and turn unto Him, with whom is mercy and plenteous redemption;
lest a worse and more terrible warning should follow.
There is, I think,
reason to fear that another woe will succeed that which has now passed over,
I mean the occurrence of pestilential disorders,
which the dampness of the houses may bring on; particularly,
if intense frost should succeed, before they are in some degree dry and aired:
last night it froze hard; at present there is less frost,
but with the appearance of more snow.

Our friend Sarah Kilham, is likely to suffer less than we feared,
although her furniture was floating in her parlour.
Her day scholars were in the house when the water rose,
so that she was obliged to lodge them as she could.

We scarcely know what to conclude about our friends at sea,
as so much depends upon the situation of the different ships:
we hear that some have been wrecked, and others have returned to Cronstadt.
This island has been entirely under water.

In the midst of the general distress,
we have been permitted to partake of peace and quietness,
of which we seem altogether unworthy.
I sometimes fear we are not making an adequate return
for the numerous comforts and blessings we enjoy;
and were it not to acknowledge with gratitude the
loving-kindness and mercy which surrounded us,
I should willingly omit saying any thing about ourselves:
all belonging to us seem to shrink into nothingness,
when we behold the surrounding scene of woe and misery.

--
