== Chapter XI.

[.chapter-synopsis]
* Visits England with His Wife in 1830
* His Affectionate Address to the Members of the Church of England
* Religious Visit into Devonshire, Cornwall, the Scilly Isles, etc.

This year (1830) the health of our dear mother having again failed considerably,
she was recommended to pass the ensuing winter in England;
and my father having concluded to accompany her, they came over together in the autumn.
The interval of leisure thus afforded, was not suffered to pass unimproved.
Besides the attendance of the various meetings that fell in his way,
he wrote and published, during the winter, a pamphlet entitled,
An affectionate Address to the Members of the Church of England;
which it is believed was widely circulated at the time.

In the First Month 1831,
he applied for and obtained a certificate from his Monthly Meeting,
enabling him to visit parts of Devon, Cornwall, and the Scilly Isles.
On the conclusion of this service, he attended the Dublin Yearly Meeting,
and afterwards that held in London, returning to Petersburg in the Sixth Month following.

[.offset]
The succeeding extracts are from letters written during this period.

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Smith, Sheffield

[.signed-section-context-open]
York, First Month 8th, 1831.

On Second day morning, the 3rd instant,
I shaped a northerly course for Durham Quarterly Meeting, held at Darlington.
We had a very solemn meeting for worship the next morning, in the course of which,
the great cause was ably advocated by several present;
and I had to throw in my poor mite among them,
and in a particular manner to call their attention to myself, as one exhibiting,
and that without boasting, the triumph of Divine grace,
over human nature in its most depraved state.
It was indeed a memorable time;--the Truth rose into dominion over all,
and many minds were sensibly humbled under the power thereof.
I stayed over their week day meeting on Fifth day last;
and had again to declare of the goodness and mercy of our God.
This meeting ended well,
but was not quite so highly favoured as that preceding the Quarterly Meeting.

After meeting, I left Darlington for York;
where I was favoured to find my wife better than when I left her.
For this, and for all the blessings and favours I daily and hourly enjoy,
what shall I render unto the great and bountiful Giver,
but the acknowledgment of being utterly unworthy of the least of all His tender mercies.
On the way from Darlington, during the half hour allowed for dining,
I called on a person who has lately joined the Society by convincement:
he has a daughter in a very delicate state of health.
I was gratified with my visit;
and have since felt such a draught of love towards this dear young woman,
that I have had to address a letter to her father on her behalf, which, I trust,
will be received in the same love in which it was written.

Yesterday I went to sit by the deathbed of a young man,
who is not expected to be long on this side the grave.
It was a season to be long and gratefully remembered;
for the Son of peace had mercifully visited this habitation.
I had to bow in thankfulness for the precious quiet vouchsafed,
and to petition the Father of mercies, on behalf of the humble patient sufferer.
I believe that many have been instructed by this bedside.

My little address is now in the press, in York, as well as in London,
so that I hope it will shortly appear at Sheffield.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Absent Family

[.signed-section-context-open]
York, Third Month 3rd, 1831.

[.salutation]
My Dear Children,

I find things, as I go on, much altered as regards our Society;
but it is a great consolation that there are here and there a few,
comparable to the odd berries on the uppermost bough and in the fruitful branch,
who are preserved alive at the root, and I trust growing from grace to grace,
and that they will continue to grow,
until they attain to "`the measure of the stature of the fullness of Christ.`"
There are others again,
whom the everlasting Father is graciously
drawing by merciful visitations to that Saviour,
who will in no wise cast them out.
In Sheffield, Doncaster, York, and Darlington, there are of this description,
as well as at many other places, where my lot has been cast.
It is astonishing what a striking difference there is between some meetings and others;
but the most barren sittings I have been at,
were at +++_______+++. I found it my place to dwell low with the suffering seed,
and was quite closed up in both the meetings there.
"`If any man serve me, let him follow me; and where I am,
there shall also my servant be,`"--was the declaration of the Saviour of men,
when personally upon earth:
and truly there is no alteration in the Christian course;--if we would reign with Christ,
we must be willing to suffer with Him.
We must indeed, according to our measure, drink of the cup which He drank of,
and with the baptism that He was baptized withal, must we be baptized;
or how can we know a fellowship with His sufferings,
or witness the power of His resurrection? In
some meetings I have had to deal very plainly,
and to declare among them without reserve,
that however they might disregard the precious gift in their own hearts,
and keep aloof from its warnings and monitions,
that the same would judge them at the last day,
according to the words of our holy Redeemer,
when he said,--"`I judge no man,`" but "`the word that I have spoken,
the same shall judge him in the last day;`"--or to this effect.

There is a new work,
published by a minister of the Independent denomination of Sunderland,
entitled [.book-title]#The Book of the Priesthood,#
proving from Scripture, that under the gospel,
the whole institution is at an end.
I have procured a copy; also one of a smaller work, [.book-title]#The Church in Danger from itself,#
and of another, [.book-title]#Hurn`'s reasons for Secession from the Church of England.#
The author of [.book-title]#The Book of the Priesthood,#
is now said to be employing his pen on the subject of tithes.
In short, the nation seems at last to open its eyes,
or rather to permit their being opened; and I believe that the day is fast approaching,
when the hireling will flee, "`because he is a hireling.`"
I have met with a work lately on Christian perfection, which has pleased me not a little,
because there are so few of the different professing
Christians who will admit this doctrine.
I believe the author is a Wesleyan Methodist;
and although he retains things which we do not deem essential,
he very ably maintains the possibility and necessity of Christian perfection.

I have mentioned these things to show you what is doing in the world this way.
It is wonderful to behold the great shaking there is in the minds of men at this time;
all I hope indicating, that the day has begun to dawn,
when "`the knowledge of the Lord shall cover the earth,
as the waters cover the sea,`"--even the knowledge of that "`word of God,
which lives and abides forever;`" and which in the days
of the apostles so mightily grew and prevailed,
to the utter exclusion of the earthly nature from every
heart in which it is permitted to operate.

For some months past,
I have been rather looking forward towards paying a visit to the Scilly Islands,
and to the different meetings of Friends in Devonshire and Cornwall; and latterly,
the track has been so defined, that there seemed no doubt in my mind respecting it.
I was strengthened to cast the subject before the Monthly Meeting,
held on the 21st ultimo,
and was favoured to receive every encouragement that could be desired;
and since taking this step, I have felt the reward of peace,
for this small act of obedience to what I believe is required of me.
I am now making preparations for leaving Yorkshire for a season.
As I am very much a stranger to every one in those parts,
the prospect at times feels rather heavy;
but having been mercifully favoured to taste of that soul-sustaining food,
upon which a man may +++[+++in a spiritual sense]
travel forty days, I am encouraged to hope, that He,
who has been graciously pleased to be with me in so many troubles,
will not now forsake me.

I trust you will still continue to be cared for:--"`as
the mountains are round about Jerusalem,
so is the Lord round about his people, from henceforth and forever.`"
Those who fear, love, honour, and obey Him, they are His people:
and "`the Lord will bless His people with peace;`" and
truly there is no peace like the peace of the righteous;
no love like the love of God shed abroad in the heart;
and no joy like unto the joy of God`'s salvation.
Love was the distinguishing characteristic of
the first and great commandment under the law:
and it is the first fruit of the Spirit in the gospel dispensation;
which is exhibited in love to God, and love to man.
If we are but once favoured with this inestimable treasure,
the whole train of Christian virtues will follow in beautiful succession,--joy, peace,
long-suffering, gentleness, goodness, faith, meekness, temperance;
against which there is no law.
"`Love is the fulfilling of the law,`" and the end of the commandment.
It is indeed the heavenly badge that designates the
disciples of the one same compassionate Saviour;
it outlives faith and hope; it casts out fear;
and animates the Christian traveller to persevere in the tribulated path,
which leads to life everlasting.
Then let us individually wrestle for this unutterable blessing;
for we are told that "`God is love if we find it, we find Him.`"
Let us press through the crowd of encumbering things,
even things perhaps harmless in themselves,
which serve to keep alive in us the evil and hindering propensities of fallen nature;
that so we may happily come in heart to the Saviour,
who only can enable us to banish the things of time and sense.
Though they may compass us about like bees,
in the name of the Lord we will destroy them; for through Him we can do all things,
but without Him nothing, as it should be done.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Island, called St. Mary`'s, the largest of the Scilly group, 31st of Third Month, 1831.

[.salutation]
My Dear Children,

I think my last letter mentioned the probability of my
visiting the counties of Devon and Cornwall,
together with these islands.
At the last Balby Monthly Meeting, a certificate was granted me for this purpose.
On the 5th instant, I left York, by way of Leeds, to Bradford,
and was at both their meetings the next day; in which I had to labour among them,
to my own comfort at any rate.
When at this meeting, a few weeks previously,
there seemed no door of entrance to be found among them,
and I was shut up in both meetings.
The next day I came on to Sheffield, and on the 10th attended the Monthly Meeting,
and received my certificate.
The same day, accompanied by +++_______+++, I went to Woodhouse, Hackenthorpe, Burleigh,
and two places at Handsworth,
to pay a small debt due from me to some invalids at these
places,--two or three of them far advanced in years,
who were absent when I visited Woodhouse meeting some time before.
The next day I went in the mail to Birmingham,
and proceeded the same evening towards Bristol; here we arrived early in the morning,
and after some refreshment, went forward to Wellington;
where I found Samuel and Maria Fox,
(whom I think you know,) were intending to unite with
me as far as our routes might continue together.
I attended both their meetings on First day,
and had a little to do among them in the morning; but in the afternoon was silent.
On the 14th, we proceeded to Kingsbridge, where a meeting was appointed for the next day.
I slept at +++_______+++`'s, whose wife is an old acquaintance of mine.
Our mutual satisfaction at thus meeting,
was very much damped by the poor state of her health.
The meeting was a highly favoured time, and we all had to labour together in love,
unity and harmony.
Next day we proceeded to Modbury, to another meeting; this was rather more dull at first,
but was favoured to end comfortably.
We reached Plymouth the same evening.
At this place, Samuel and Maria Fox had a prospect of visiting families.
It was I believe best that we separated; as when united,
we seemed rather to depend on the strength of each other,
and perhaps even felt a little too strong.

The next day, I proceeded alone to a newly settled meeting at Tavistock,
consisting mostly of convinced Friends.
I was a little disappointed to find this meeting flat and dull: at the first,
perhaps I expected too much; but towards the latter end Truth rose into dominion,
to our mutual comfort and consolation.
I returned to Plymouth the same night.

As way opened, I accompanied Samuel and Maria Fox in some of their family visits.
On First day the 20th, sat with two families, and attended both the regular meetings,
in which I was enabled to obtain considerable relief:
towards the close of my testimony in the afternoon,
the way seemed clear for taking leave of Friends there,
to some of whom I felt closely attached.
In the evening, was at a public meeting, held in the Bethel at Devonport,
at the request of Samuel and Maria Fox.
It was well filled;
and after the people were informed of the object of our meeting together,
great solemnity prevailed over the assembly.
Samuel Fox had to break the silence with the voice of prayer.
I suppose almost the whole congregation,
consisted of persons connected with the sea-faring life, with their families.
My heart was greatly enlarged towards them,
as companions and shipmates in the voyage of life; having the Lord God,
merciful and gracious, and abundant in goodness and Truth, for our commander;
and an all-sufficient Saviour and holy Redeemer for a heavenly pilot;
who would never leave His vessel,
but would safely conduct us through all the dangers and difficulties of time,
and would remain with us through the never ending ages of eternity.

Towards the close, I had to call the attention of the meeting to myself,
as an example for their encouragement, that none need despair;
for in me they might behold a living monument of the Lord`'s everlasting mercy,
and the triumph of Divine grace over human nature in its most depraved state;--in one,
who, like themselves, had been cradled on the ocean,
whom the everlasting arm had ofttimes been stretched out to save,
when the briny wave had nearly prevailed against him.
Maria Fox concluded the meeting in supplication.
The people seemed in no hurry to leave the place,
many coming to shake hands in a very friendly way.
By what I have said, you will have some idea what sort of a meeting it was;
and I think you cannot refrain from joining with
me in the grateful tribute of admiration,
gratitude, and praise,
to Him who "`sits upon the flood,`" who "`sits King forever;`"--who only can
"`give strength unto His people,--who will bless the provision of Zion,
and satisfy her poor with bread,--and fill with that peace,
which the topaz of Ethiopia cannot equal in value.`"

Being clear of Plymouth,
next morning I crossed the Tamar in a boat to the Cornish side of Hamoaze,
passing close under the stern of the Malta man-of-war.
We proceeded to Looe, where a meeting was appointed: few Friends live here;
but one of the few is that faithful servant, Sarah Tucket.
We were favoured with a comfortable meeting, to mutual refreshment.
After dinner, we proceeded to Tideford, and next morning attended their meeting.
This was a memorable time from beginning to end:
I can scarcely calculate upon being again permitted to partake
of such another heavenly banquet in the course of this journey,
if ever: but my soul right well knows that there is a power,
in whom I am happily taught to believe, and with whom all things are possible;
who can at His pleasure "`bind the sweet influences of
Pleiades,`" "`loose the bands of Orion,`"
"`bring forth Mazzaroth in his season,
and guide Arcturus with his sons`"--"`He that opens, and no man shuts; and shuts,
and no man opens`" the heavenly treasury of peace, love, and joy,
which are at times revealed through the riches and glory of His grace, to His praise.

We dined at Liskeard.
This meeting was appointed at six in the evening, and was much hurt,
by the disorderly gathering of the town`'s people,
attracted by the lights in the windows of the meetinghouse, perhaps a rare thing.
However, at last, we were favoured, and light sprung up,
which brought weight and solemnity over all; under a feeling of which we separated.
Samuel Rundell, an elderly minister, appeared after I sat down,
in a weighty and confirming testimony.
The next meeting was at Austle, at three p.m. on the following day: it was small,
but upon the whole, comfortable: after which I went on to Truro,
and attended their meeting held in course next day.
This proved a refreshing season to many present, and to some a time of rejoicing.
In the afternoon, W. T. kindly accompanied me to Camborne;
and the next day I proceeded to Penzance: the ground here was covered with snow,
and the morning very cold and boisterous.
I had hastened to be in time for the packet for Scilly,
but found she had been detained by stress of weather five days behind her time.
The next day was very stormy, and there was rough work among the shipping.
An East Indiaman, the Andromache, put into Mount`'s Bay for shelter,
and landed her passengers here from Calcutta.

On First day the 27th, I attended both meetings at Penzance,
which were refreshing and comfortable seasons: Friends in these parts are not numerous.
I was lodged at the house of J. S., who has kindly accompanied me to these islands.
We sailed the next afternoon, and had a fine but tossing passage.
It is not often otherwise at any time,
as the set of the tide into the British and George`'s Channel,
and the exposure to the Bay of Biscay and the mighty Atlantic,
cannot fail to cause great agitation of the water,
particularly when it has blown hard for several previous days together.
The Wolf Rock lies in the run of the packet,
and is only discovered by the breaking of the sea upon it.
We bore up for it about ten p.m.,
distant from four to five hundred yards:--I had just fallen asleep at the moment,
and so missed seeing it, which I rather regretted,
as I have formerly been several times near it, but have never seen it.
In light winds it makes a roaring noise from being hollow,
and the breaking of the sea into it may be heard at a considerable distance.
At eleven p.m.,
we were in full sight of the fine revolving light on the island of [St.] Agnes;
and in a couple of hours afterwards were anchored safely in the roads of [St.] Mary`'s.

We landed immediately, and were glad to get to an inn,
where the people kindly made us a fire, as the night was cold.
The next day, a meeting was appointed on the Isle of Tresco;
the people were long in gathering, but behaved solidly;
and I was favoured with encouragement to persevere with my engagement.
Next day we had a meeting on Sampson`'s Island in the afternoon,
and another on Boyer`'s Isle in the evening;
both were satisfactory and comforting seasons,
tending to administer an increase of strength,
and begetting humble thankfulness of heart.

Fourth Month 1st. Last evening we had a meeting on Martin`'s Isle,
which ended in a very solemn season.
A class of Methodists called Bryanites abound here; their minister,
and many that were present, made a continual groaning.
One poor woman in particular, who seemed much struck with the solemnity of the occasion;
I was upon my feet at the time, but was favoured with calmness.
I could plainly hear the words,
"`praises,`" "`praises,`" from the lips of the minister and others.

Fourth Month 2nd. Yesterday, we crossed to the island called St. Agnes,
and found the landing rather difficult on account of the surf:
in consequence of the great ebb and flow of the tides,
few of these islands have proper landing places.
It being what is called Good Friday, the people were mostly at home;
and their Bryanite minister, knowing we were among the islands,
had appointed a meeting for us at six in the evening, saying, that if we did not come,
he would preach himself:--so that all was made ready to our hands.
There is a good new schoolhouse on this island
belonging to the Protestant establishment;
but the clergyman will not allow it to be used for any other purpose than as a school.
He seldom comes near these people himself,
although there is a regular church-house for his use;
and yet he does all he can to make it inconvenient for Dissenters to come among them.
Our meeting was necessarily held in a dwelling-house, in two lower rooms,
which were excessively crowded; and after all,
many had to stand outside the open doors and windows.
You know that I can bear a tolerable portion of heat, but this was almost too much for me.
There was much groaning around us; but no particularly wild extravagances were exhibited,
and on the whole it was a highly favoured meeting.
We drank tea at the same house with their minister; but carrying our materials with us,
we made a distinct table.
It was striking to see the homely fare he partook of; in his absence,
I inquired of our hostess how he was supported; she said,
they could not afford to pay him much, so had agreed among themselves,
that they should take it by turns to board him one day each,
in the same manner as they lived themselves; so that he is at a fresh house every day:
but that one person had agreed to find him a lodging at her sole expense;
and that the society of which he was a member allowed him £8 per annum.
He is a kind, sincere-hearted, and unpretending young man, and I felt a regard for him.

I am very thankful that I am favoured to have finished
visiting all the straggling distant islands;
and it is due from me to acknowledge the great
support and strength that have been afforded me.
It has blown strong ever since I have been here,
so that getting about has been difficult,
particularly embarking in the dark in strange places,
among rocks slippery with oozy sea-weed;
we could not avoid getting our clothes wet every day, and sometimes twice a day.
My companion is a plain, honest, worthy Friend,
to whom I feel under many and great obligations for his kindness and attention.

After the two meetings in prospect on the island called St. Mary`'s,
I know of nothing more to detain me here;
but do not like exactly fixing my return to Yorkshire.
I hope to be rightly directed, though but an unprofitable servant;
but to be admitted a servant of such a Master on any terms,
ought to be sufficient for any of us unworthy creatures.

I have lately received an extract from your last letter,
and am sorry to find there is so much sickness near you,
and that a fear prevails of the cholera approaching your borders.
But we have "`a strong city`" and I humbly hope,
we shall be mercifully prepared for an entrance therein, through the strait gate;
that we may indeed be among the number of the few, out of the many called,
who are happily chosen;--this gate of the Lord through
which the righteous enter into the city of their God;
all the inhabitants of which are "`redeemed with
judgment,`" and converted with righteousness,
even the righteousness of Him who died for the sins of all mankind.

Fourth Month 6th. Penzance.--On First day, we had two meetings on [St.] Mary`'s Isle:
the first, at Holyvale, was a little disturbed by some rude people;
I reproved them for it; and I believe many thought it a solemn time.
The meeting in the Garrison town, was larger than any preceding it;
and was a highly favoured time throughout.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Smith, Sheffield

[.signed-section-context-open]
Barnstaple, North Devon, Fourth Month 18th, 1831.

Presuming that my dear wife has before this time taken
her departure from your hospitable dwelling,
I am at a loss how to direct to her, and shall therefore be greatly obliged,
if you will forward the enclosed letter,
as you are doubtless in possession of the secret.

Since arriving at Penzance from the Scilly Isles,
I have been searching out the infirm and invalids at Marazion,
who did not get to the meetings when I was at Penzance, previously to embarkation.
On the Sixth day following, went eighteen miles to sit with some Friends at Portreath,
a small port near the entrance of the North Channel; and afterwards to Redruth,
where a meeting was appointed for the next day.
This was a comfortable time I trust to many present, and a relieving one to myself;
which I desire to remember with gratitude of heart to the great Giver.

On Fourth day the 13th, the Quarterly Meeting was held: this was a favoured time;
though in all these meetings I had some heavy work to do,
but was strengthened to perform it faithfully.
There seemed no getting out of Falmouth without
holding a public meeting with the inhabitants,
to which the sailors were specially invited.
The house was well filled, and it proved a solemn opportunity;
which I hope will be lastingly and profitably remembered by some present.
I had to tell them, that like themselves, I had been cradled on the boisterous ocean:
that the mercy of the Lord was unbounded as His love: that none need despair,
for that Jesus Christ came into the world to save sinners, of whom I am chief, etc.

The time of liberation was now come, and I set out the next day for Plymouth,
and finally for this place.
Yesterday, I was at a meeting at Newton Tracey in the morning;
none who attend it are members,--it was a refreshing season, and a thankful time for me.
In the evening sat with Friends of this place; many strangers came in,
and we were refreshed together.

I have lately been anticipating the pleasure of returning to
my dear wife and all my friends at Carr Wood,
intending to stop next First day at Birmingham;
but what poor shortsighted creatures we are!
I was on the morning watch yesterday soon after four o`'clock,
when the love of God filled my heart;
and a public meeting with the inhabitants of this town presented to my mind.
A willingness was wrought immediately on the opening:
the Yearly Meeting in Dublin followed;
and I bowed in humble resignation to what I believe to be the Divine will.
In obedience to this, I have informed the Friends here;
and the Wesleyan meetinghouse is procured for seven o`'clock this evening.
I feel that I am left single handed among strangers;
but happily I know that there is a Power,
which can yet enable me to "`run through a troop,
or leap over a wall`" in whose blessed will I rest, and in whose mercy I trust.

After the Quarterly Meeting at Exeter, I must press forward with all speed to Bristol,
as there will be barely time for me to get to Dublin,
if I find a steamboat starting the same day.
It is very clear that this is not the place of rest for me,
but I humbly hope it is a road that leads to it.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife

[.signed-section-context-open]
Dublin, Fourth Month 25th, 1831.

[.salutation]
My Dearest Jane,

I have now the pleasure of informing you,
that I arrived in this city early yesterday morning.
I wrote to you last from Barnstaple,
then looking forward to a meeting at that place the same evening,
which proved in the end a truly comforting season: such a one as I have seldom witnessed.
It was held in the Wesleyan meetinghouse, which was much crowded.
The people were very quiet and attentive,
and I had full opportunity to relieve myself among them,
and have since been favoured to finish my visits to the remaining meetings in Devon,
and to leave the country in peace;
although humbled under a sense of my unworthiness to
partake in the least of the Lord`'s mercies,
and thus preserved by sea and land,
and enabled to give the glory and the praise to Him to whom all belongs.

I left for Exeter the next day, and attended the Select Meeting the same evening,
which to me was a heavy time.
Here I again met with Samuel and Maria Fox.
Next morning the Quarterly Meeting began with a meeting for worship,
which was for some time very flat; but gradually improved,
and in the end a relieving time was obtained, but not without plain dealing.
The next appointed meeting was at Spiceland, about twenty miles distant,
on the following evening; but it did not prove a land of spice for any of us.
We had to experience the truth of the apostolic declaration,
of the sympathy in the members of the mystical body: "`if one member be honoured,
all the members rejoice with it;`" but our lot was to
suffer together:--"`whether one member suffer,
all the members suffer with it.`"

We reached Wellington the same night,
and I had the pleasure of seeing my beloved
companions restored to the bosom of their family,
to the great delight of all around them.
We were favoured to separate under feelings not soon to be forgotten,
in that love which absence and distance only serve to strengthen.
I pursued my course to Bristol, lodging at the hospitable mansion of Benjamin Thomas,
and embarked the next day in the Killarney steamer, for Dublin; a very fine vessel,
crowded with passengers, but all strangers to me.
Our progress was impeded by contrary wind, and an old sea swell;
so that although the vessel possessed the power by steam of 220 horses,
we were several hours beyond the usual time of arrival.
The two first inns were full of guests, but the third took in the stranger,
but could only give him a bed in a double bedded room.
You know I often say.--"`any port in a storm`" but
I believe there was a secret hand in all this.
The other bed was occupied by a stranger,
with whom I had some satisfactory conversation before we got to sleep.
It was renewed at an early hour next morning,
and I never remember to have seen any person so
completely overcome by the force of Truth.
My feelings were such as led me to conclude, that if I had no other service in Ireland,
this was enough, and my reward was ample for coming.

The meeting, so far, has been a solemn time:
I have not had to open my mouth in any of the sittings.
The disturbed state of this country is certainly appalling.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Liverpool, Fifth Month 3rd, 1831.

[.salutation]
My Dear Children,

Although I have had but rough doings on board the Etna steam-packet all night,
yet I do not like the thoughts of letting this letter be sent off,
without an assurance of dear love on my own behalf;
at the same time not doubting that your dear mother has said all that is needful,
in her letter.

We have had a very solemn Yearly Meeting, which continued nearly the whole of last week.
The dreadful situation of the people in Ireland seems to have
created very general apprehension in the minds of Friends,
and I think very justly: in some counties open rebellion is the order of the day,
and some bare-faced murders have been committed in broad daylight.
These things, and the altogether appalling signs of the times,
have combined to bring the minds of many into great humility and abasement of self.
In addition to these outward circumstances,
the general call from the ministry has been in effect,
"`How long will you see the standard,
and hear the sound of the trumpet? How long will you hear, and see,
and disregard the lovingkindness of the Lord?`" It was rather remarkable,
that the strangers present were all from places distant from each other;
and yet all uniformly had to raise a similar language, and to warn the revolting,
backsliding sons and daughters in our Society, of a day that is fast hastening upon them,
that would shake every building not upon the true foundation--the eternal Rock of ages,
Christ Jesus our Lord.
I trust the call will sink deep into the minds of many, and bring into thoughtfulness,
about their own soul`'s peace, such characters as the great Apostle describes,
when he says,--"`of whom I told you often, and now tell you even weeping,
that they are the enemies of the cross of Christ.`"

I understand that poor +++_______+++ was last week seized with illness, and died the next day:
it was quite my intention to have paid him a visit, when I reached his neighbourhood;
but I shall now be too late.
I believe he has been much softened,
since an illness which he had a few weeks previous to this last attack;
and has been heard to lament the manner in which his family have been educated.
We have but one instance recorded in Scripture of any being accepted at the last hour,
that none may presume; but there is one, that none should despair.

Hoping shortly to speak to you all face to face, and to recount the mercies,
the blessings, and the lovingkindness of the Lord to his poor finite creatures;
I remain with full assurance of love, your affectionate father,

[.signed-section-signature]
Daniel Wheeler

--
