== Chapter XII.

[.chapter-synopsis]
* Return to Russia, 1831
* Cholera at Petersburg, etc.
* Epistle to Friends of York Quarterly Meeting, 1832 etc

[.letter-heading]
To Sarah Smith, Sheffield

[.signed-section-context-open]
Sixth Month 28th, 1831, Ship Army, in the Cattegat.

I think I never witnessed greater variety and changes in the weather,
than have befallen us since embarking on the 22nd. Each
revolving day has been fraught with changes,
again and again reminding us of the uncertainty of all things here below:
each day has produced a calm, and each calm has been followed by boisterous winds.
My dear wife has suffered greatly from sea sickness;
I think I never before saw her so much reduced from this cause.

It has often been my lot,
(and it seems as if the measure was not yet filled up,)
to witness and to share many painful scenes;
I sometimes think that a greater portion of
suffering is necessary for me than for others,
to hold in check and humble a disposition, which is naturally so prone to rebel.
It is, at any rate, no more than I deserve,
after the days without number that have been passed in
folly and forgetfulness of that gracious Being,
who has in unutterable condescension and mercy followed me from my youth up,
even to the present day; and who, I humbly trust,
will never forsake His poor unworthy creature: but by renewed trials and baptisms,
will keep alive the vital spark, until He is graciously pleased to say, "`it is enough.`"
If I know myself, I think that I do not desire a life of ease;
but I would gladly devote the few remaining days which may be my portion here,
in declaring "`the mighty acts of the Lord to my benighted fellow-creatures,`"
though unequal and unworthy to show forth half His praise.

[.offset]
+++[+++About this period the cholera prevailed with great virulence at Petersburg;
the two following letters give some description of this awful visitation.]

[.letter-heading]
To Sarah Backhouse, York

[.signed-section-context-open]
Plains of Shoosharry, near Petersburg,

[.signed-section-context-open]
Eighth Month, 31st, O. S. 1831.

Let me acknowledge with reverent thankfulness and gratitude,
that we are all in the enjoyment of the inestimable blessing of health,
which nothing earthly can bestow; a high privilege at all times, but how much enhanced,
when the earth has been opening around us,
and swallowing up the people to a fearful extent from cholera,
in some cases at the short notice of from two to three hours.
Old and young, strong and weak, rich and poor, have fallen;
but such as were in the constant habit of drinking
spirituous liquors were amongst the first victims.
Although we have had to stand as with our lives in our hands,
yet we have been favoured beyond precedent; as out of our establishment,
employing this year more than five hundred persons,
not a single man has been taken off by this disease:
when it is a well authenticated fact, that in one house in the city,
(a large one of course, containing several families,) forty persons have died.
What, indeed, can we render to the Most High,
for such unmerited mercies showered down upon such poor unworthy creatures;
while so many thousands have been hastily summoned
hence by the undeniable herald of the grave!
"`Who can utter the mighty acts of the Lord? Who can show
forth all His praise?`" Truly in vain is the attempt,
my soul right well knows,
for any of us to exalt and magnify His ever great and adorable name,
without his strengthening aid;
though glowing with renewed desires to proclaim to all mankind, if it were possible,
his matchless and unutterable love.

From a variety of circumstances which occurred both before reaching the Sound,
and after leaving it, our suspicions were awakened as to the state of things,
in regard to the fatal disease at the place to which we were bending our course;
but the weather threw us out of the track of the homeward-bound ships,
and prevented our getting the least information till we entered the Gulf of Finland.
From all the accounts we received from the vessels then spoken with,
there seemed no doubt, but that the cholera was raging both at Cronstadt and Petersburg;
and the nearer we approached to these places, the more alarming the reports became.
One night, when off that part of the coast nearest to the seat of war,
we were quite annoyed with the unpleasant state of the
air,--although we were not in sight of the land,
I believe, but the wind blew from that direction: it pervaded the whole ship,
so that my wife, though in bed, discovered it,
and thought it arose from something on board:
the atmosphere seemed filled with tainted air.
From this time our captain fumigated the ship daily,
making free use of the chloride of lime, of which he had a plentiful supply.

The long continuance of contrary winds had hitherto
tried our stock of patience rather severely;
but now the time was at hand for a trial of faith,
and of our resignation to that holy will, which is ever excellent,
though it is beyond the reach of poor finite man to
develope its ever merciful and all gracious designs.
The captain had been told shortly after we sailed,
that I had regularly arrived in Russia on one particular day;
and he now began to talk of this in rather a sneering manner, saving,
that my calculation had failed, for the ship was a long way off her port,
and the wind still contrary.
I told him we should be there soon enough in all probability,
merely alluding to the sickness.
When we had been twenty-two days from Hull, the wind changed,
and once again blew a fine fresh gale from the westward, which, in ordinary cases,
would have brightened every countenance on board;
but such was the gloomy prospect before us, that even this, so often hoped for,
had no power to charm.
The breeze continued through the night, and the rising sun increased its strength;
and our noble vessel seemed to rush onward with more speed than we desired,
except as the recollection arose of the three dear children,
whom we dared now only to look forward with a very
trembling hope to behold again in mutability.
As the day advanced, the wind became stronger and stronger,
so that by noon we were favoured to anchor
safely off the entrance to the Mole of Cronstadt,
amidst a crowd of shipping.
Is it not worthy of something more than ordinary remark,
that we should arrive on the very same day,
on which I had three times before been permitted to do so--the 15th of Seventh Month,
N+++.+++ S.? To me, this had a promising and strengthening effect;
it was a pleasing coincidence,
bringing to remembrance many great mercies and favours in times that are past,
but now signally to be commemorated with admiration, gratitude, and praise to Him,
who "`commands the morning, and causes the dayspring to know its place.`"
It was indeed a day of humiliation, self-abasement,
and bowing down amongst all around us,
producing from the hardy captain the appropriate exclamation,
"`There is nothing but the Almighty for it,
at any rate:`" and I believe he never spoke more
strictly in adherence to truth in his life;
for what could the possession of the whole world have done for us in this day of
distress? The "`secret tabernacle of the Most High`" was the only hiding-place,
the only pavilion of safety and refuge.

I would gladly impart to my dear friends,
a share of the marvellous loving-kindness and tender mercy,
which were so graciously displayed for our relief and consolation on this memorable day;
but language is utterly incapable of conveying it,--words cannot set it forth.
I think that nothing short of being placed in an exactly similar situation,
could make it be felt and understood to its full extent.
However much it may be thought an uncharitable desire, I cannot help craving,
that all my beloved Friends were brought, by any means,
under a similar state of feeling;--not a mole-hill to rest upon, humbled in the dust.
How softened every heart!--how tearful every eye!--the Lord alone exalted!
This is what I want all to witness for themselves;
that they may indeed witness the power of everlasting love,
to comfort and strengthen their hearts; and enable them to assert,
in similar language with the great Apostle of the Gentiles,
and from the same heart-felt knowledge, "`we glory in tribulation.`"

I have made a long digression from the subject of our arriving at Cronstadt,
but my heart warms with the remembrance of the sustaining evidence,
with which our minds were favoured in the midst of the scene of terror that awaited us.
My poor wife was greatly supported,
and only in one instance expressed any thing like discouragement,
and that was at the thought of my having to expose myself amongst the people on shore.
But it was not a time for any one to flinch, particularly when mercifully favoured,
as was my happy portion, to banish all fear, and not experience a single desire to arise,
to be any where but where my lot was cast.

On landing, some difficulties arose from a new law respecting passengers`' luggage:
the captain proposed applying to the British Consul for advice.
I felt averse to this; but nothing else suggesting, it was attempted.
It was soon ascertained that no person was admitted into his office; and that letters,
etc., were received with a pair of tongs, for fear of infection.
It seemed as if nothing was to be achieved by any contrivance of our own;
but the very barrier which at first appeared insurmountable,
proved to be the channel through which relief and comfort were to flow.
This new law occasioned my having to go to a particular department of the Custom House,
when I was accosted by a stranger with a letter in his hand, who asked if it was for me.
The measure was now filled; the tide which had flowed in such an appalling current,
was now at its height, and beginning to turn.
The letter was in dear William`'s hand writing; and I had the joy of finding,
that my children had wholly escaped the ravages of this awful disease;
which was considered to be at its height, just about the time of our arrival.
I hastened on board again with my letter, and will leave you to judge of what followed,
and to partake of the joy which once more we were permitted to
share together,--I hope with humble gratitude.
I was on shore again until late; but everything moved tardily, and no wonder,
when the judgments of the Almighty were at the very doors of most,
in so striking a manner.
In this small town one hundred and fifteen died that day.

After another day unavoidably spent at Cronstadt,
we got into the steam-boat on the 17th of Seventh Month, and reached the city about noon.
It being First day,
it was expected that a considerable number of persons
would be waiting the arrival of the steam-boat,
as in former similar instances, it has sometimes been difficult to get through the crowd.
But the contrast was so remarkable,
that I did not suppose we had reached our proper destination,
as there were only three or four people belonging to the wharf to be seen,
and not a single carriage standing for hire:
scarcely any body was to be seen in the streets, and in some the grass was growing.
We were at length favoured to reach our abode, and to find all well,
to our mutual rejoicing,--such was the abundant and unmerited mercy bestowed upon us.
William had anticipated our arrival,
and thoughtfully got the letter conveyed only the day before,
which afforded us so much relief.
If it had not been for the new regulation,
it is probable the letter would not have found me,
as I should not have had occasion to go to the Custom House.
How admirably things are brought about, and a way made,
when to finite comprehension none could be expected.

I hope you are at seasons favoured sensibly to
feel the presence of the ever blessed Master:
do not suffer yourself to be discouraged, though He may seem to tarry long;
but remember that "`in due season we shall reap, if we faint not.`"
The path of suffering is that which leads to blessedness and glory;
and it is only those who are willing to suffer with Christ Jesus,
who can expect to reign with Him: therefore be not weary in well-doing.
Let us humbly endeavour to dwell low, and abide with Him;
being "`buried with Him in baptism;`" that so we may be among
the happy number that shall rise with Him to life everlasting.
I am more and more confirmed in believing, that nothing can separate us from His love;
neither nakedness, nor peril, nor sword.
Though we may indeed be as "`killed all the day long,`" and
"`accounted as sheep for the slaughter;`" yet as we abide in His fear,
"`watching unto prayer,`" "`praying always with all prayer and supplication
in the Spirit,`"--the incense will be continually burning:
and "`in all things we are more than conquerors,
through Him that loved us;`"--to whom be the praise and the glory forever.

[.letter-heading]
To Richard Cockin, Doncaster

[.signed-section-context-open]
Shoosharry Establishment, Ninth Month 22nd, 1831, O. S.

In my last letter,
I could give few particulars as to the number of
persons that has fallen victims to this disorder,
nor will the total number ever be known or made public.
I have heard through a channel that cannot be doubted, that on the day we landed,
eight hundred died in Petersburg.
The published accounts state the total loss throughout the empire, at fifty-two thousand;
and, we may be sure, that this is a very moderate calculation indeed.
Through mercy, this calamity seems nearly overpast;
and how should I rejoice if it was in my power to say,
that the inhabitants have learned righteousness,
while the "`judgments of the Lord`" have been so signally manifested in the earth.

It is really astonishing what a degree of ignorance prevails,
or what cause can have operated to deceive the people;
many of whom at this day do not believe that such a complaint has ever existed;
but suppose the mortality has been occasioned by poison
administered by persons in the employ of the Poles.
This delusion has itself caused a waste of human life.
It would of course help to exasperate the public mind against the Poles;
but this was not all, for it caused the lower orders to rise, and in their blind zeal,
it is said, people were actually destroyed on suspicion of being paid agents:
the doctors were implicated in this suspicion;
and I believe at least one was killed by the rabble.
The fact is, the doctors were altogether at a loss how to treat the disease:
all their skill was baffled completely;
and as almost every case was fatal to which they were called,
when this awful visitation first commenced,
it was considered sufficient proof that they were the authors of the mischief.
When we arrived, not above five out of every hundred cases recovered.
Some of these objects of suspicion were seized and searched,
and compelled to swallow any article found upon them, supposed to be poison,
in order to ascertain their guilt.
We heard of one on whom a smelling bottle containing strong French salts was found;
the test in this case, it is said, proved fatal.
In another instance, the owner of a set of castors was compelled to swallow the contents;
but by taking an emetic, he escaped material suffering.
The rabble broke into some of the hospitals, and speedily liberated the patients:
in one instance, they threw the doctor out of the window; he escaped being much hurt,
and was actually carried up stairs and thrown out a second time,
and fell a sacrifice to their fury.
The confusion was at one time so great, that some people are said to have died of fear,
and many fled from the neighbourhood.
Others shut themselves up to escape this terrible malady, but in repeated instances,
those who took the greatest precautions, were the first carried off.

We cannot wonder at every effort being used on the part of the government,
to endeavour to check the progress of the disease;
but these efforts were not always well devised or executed.
The police very improperly took up every man,
whom they suspected of having the complaint, and carried him off to a hospital; where,
in spite of all he could say, he was immediately treated as a patient, and many such,
perhaps from afterwards taking the complaint, never came out again alive.
This treatment exasperated the people to such a degree,
that they broke through all bounds, as they thought, in self-defence.
One of our men was taken up, charged with having the disease;
in vain he declared that he was in perfect health,--
nothing would serve but his going to the hospital,
where he was quickly treated as a patient;
but was released from his perilous situation by
the multitude getting possession of the hospital,
when he availed himself of the opportunity of escape, and returned to his work.
With a view to prevent the contagion from spreading,
the dead were hastily put into coffins, and it is very possible,
that some were coffined before they were actually deceased,--of course unintentionally.
However, some coffins were detected with living bodies in them;
so that altogether the scene of confusion scarcely ever had its parallel.

Shortly after we arrived at Cronstadt, my attention was directed to a large open lighter,
full of men and horses, crowded in all positions.
These people were in the act of flying from the infection,
hoping to reach the other side of the Gulf, and get off to the villages up the country.
I think I never before saw such a closely stowed cargo of men and beasts,
in all the course of my pilgrimage.

At one of the military colonies a dreadful affray took place,
arising from a similar cause, in which the soldiers suspected their own officers:
it is impossible to say how many, but it is reported,
that a considerable number of officers were killed,
and some of them with unheard-of cruelty.
It really seemed as if the most trifling cause was
enough to "`turn every man`'s hand against his fellow.`"
I mentioned in a former letter, that no part of our establishment had lost a single man;
but we afterwards lost a poor woman, who had been in the city, and fell ill the next day.
Everything in our power was done for her, but all was in vain.
Two women were employed to attend on her;
but it was quite needful to look well after them: as an instance,
the poor creature had had a warm bath, and in getting her out,
her nurses perceived that her countenance was distorted, which so alarmed them,
that they let her fall upon the floor, and ran away from her;
so that it was absolutely necessary to compel them to return, and stay with her.
Now, what must have been the neglected situation of thousands of these poor people,
when it was with great difficulty that we could
procure tolerable assistance for even one.

The past has been a memorable year indeed; I seemed to partake pretty largely of changes,
while hovering about my native land;
and yet how much was to be passed through to complete a year,
from the date of our leaving this country to its next anniversary.

I have brought back with me impressions, to which my mind continually reverts,
when looking at the past; impressions strongly engraven on my heart by the love, unity,
and, may I not say, godly sincerity, and kindness,
of many of my friends in England and Ireland.
Although deprived of all these as to the outward,
the remembrance of them remains sweet and precious,
and I trust will lastingly endure with freshness and fragrance, and brighten the days,
that I may yet have to sojourn in Mesech, and dwell in the tents of Kedar.

[.letter-heading]
To Friends of York Quarterly Meeting

[.signed-section-context-open]
Near Petersburg, First Month 25th, 1832.

Under a renewed sense of the Lord`'s manifold and tender mercies, which,
to His praise and to His glory be it spoken,
have compassed us about "`as with a shield,`" since we last saw each other;
my soul feels bound thus to recognize the good hand that has led us,
and to salute my dear brethren and sisters,
in a feeling of that love which cannot change: earnestly desiring that "`grace, mercy,
and peace, from God the Father, and our Lord Jesus Christ,
may be multiplied to them;`" causing the hearts of the faithful to rejoice,--and joy,
gladness, and thanksgiving to abound amongst them.

Although far separated from each other as to the outward,
yet such is the glorious privilege of the least
living member of the true church universal,
that nothing can separate, or prevent us from standing fast in the one Holy Spirit,
striving together in one mind,
for the faith of the gospel;--"`till we all come in the unity of the faith,
and of the knowledge of the Son of God, unto a perfect man,
unto the measure of the stature of the fulness of Christ.`"
For assuredly, my beloved Friends, a day of trial is approaching, yes,
hastening upon the nations,
when nothing short of an individual heartfelt knowledge of Him,
in whom we profess to believe, will stand unshaken by the storm.

Great is the solicitude I feel on behalf of our highly favoured religious Society,
that it may be preserved immovable upon this its ancient and sure foundation,
Jesus Christ--"`Christ in you the hope of glory`" which never did, and never will,
fail those, who in simplicity believe, and faithfully build thereon, nothing doubting.
By diligently maintaining the watch in that holy light,
bestowed in redeeming love on every individual of the human race,
the snares of the insidious adversary, although laid in the most insinuating manner,
will be detected and broken;
the specious guise of a false religion itself will be penetrated.
This has assuredly slain its thousands,
who dazzled and distracted by creaturely activity and excitement,
have thus been corrupted from the simplicity that is in Christ.
"`Watch therefore, and pray always;
that you may be accounted worthy to escape all these things that shall come to pass,
and to stand before the Son of man.`"
Blessed and holy injunction,--never out of season,--never more needed!

We may feel lamentably conscious of unworthiness, weakness,
and incapacity from our manifold backslidings,
to come up "`to the help of the Lord against the mighty,`" or to unveil the
subtle workings of the mystery of iniquity to the sight of others.
These feelings are painful; and how great is the need of circumspection under them, lest,
in the impatience of our spirits, heightened as this too often is,
by the ill-advised example and counsel of those about us,
we should attempt to stay the ark with unsanctified and unauthorized hands;
or lest we should countenance to our own condemnation willings and runnings,
on the part of those with whom we may stand connected, which,
however specious in themselves,
nevertheless contribute most essentially and
insidiously to promote the kingdom of anti-christ,
already alas! extensive in the earth.

Frequently am I brought under appalling apprehensions for us, as a people,
sought out and chosen of the Lord:
for had we followed the footsteps of our honourable predecessors in religious profession,
who bore the burden and heat of a day of deep suffering, in the faithful support,
in their original brightness, of those principles,
which they transmitted to us,--the spiritual beauty of the
gospel church might have shone forth even through us,
with a splendour which the different professors of the Christian name,
could neither have gainsayed nor resisted.
And it is awfully impressed upon my mind, I might almost say,
it is given me awfully to believe, that if the "`world,
and the things of the world,`" which "`are not of the
Father,`" had not stolen away our hearts from His love,
the glad tidings of that gospel,
which is indeed "`the power of God unto salvation,`" would, long before this,
have been proclaimed in remote, in heathen portions of the habitable globe,
by instruments raised up from amongst us,
duly prepared and clothed with the true baptizing authority of the Lord Jesus;
whose "`inheritance is the heathen,
and the uttermost parts of the earth his possession.`"
He alone can endue His messengers with "`power from on high,`"
in His name to open the eyes of the spiritually blind,
to turn them from darkness to light, and from the power of Satan unto God.
Mark, then, the awful consequences of our short-comings as a people; and let us tremble,
lest God should visit our iniquity upon us;
and the awful language should be sounded in our ears:--`"
`The kingdom of God shall be taken from you,
and given to a nation or people bringing forth the fruits thereof.`"
"`Watch, therefore,`" and remember,
"`and pray always`" for "`the time is come that judgment must begin at the house of
God;`" what then "`shall the end be of them that obey not the gospel of God?`"

"`Fear, and the pit, and the snare are upon you,
O! inhabitant of the earth!`" from which nothing but a Saviour`'s all-powerful arm,
can extricate and deliver.
All are involved in the momentous consequences; yet it is an individual work,
and admits of no delay.
Then, dear Friends of every age and of every class, let us hasten to it in earnest:
let us "`humble ourselves under the mighty hand
of God,`" even to the state of little children;
and turn inward to his pure unflattering witness, which cannot deceive, or be deceived.
Let us accomplish a diligent search,
and patiently examine how far those indispensable
conditions are submitted to on our part,
without which none can follow the blessed Jesus.
Where is that self-denial and the daily cross He enjoins? Are
we denying ourselves those gratifications of time and sense,
which nourish sin,
and keep alive in us the evil propensities of
fallen nature? Have we taken up that daily cross,
and offered all to Him,
"`who died for us and rose again?`" It is not giving up
this or that particular thing that will suffice:
a full surrender of the will must be made to Him, "`whose right it is to reign.`"
Let none plead for disobedience in what they may think little things,
on the ground of their being so.
If such they really are, they are the more easily parted with;
and our tenacity in wishing to reserve them,
assuredly indicates that they are of more importance in our
practical estimation than we may be disposed to allow.
Let no man deceive himself;--unqualified obedience is
the necessary condition of discipleship.
Without it we cannot be consistent followers of our Lord; and if not followers of Him,
we cannot serve Him, be where He is,
nor learn of Him that meekness and lowliness of heart,
which draw down heavenly blessings and regard, and which he alone can bestow.

As the sorrowful declension which has so marred the beauty of our religious Society,
may be traced to departing from this heavenly indwelling principle of light, life,
and love;
so our restoration to primitive purity can only be effected by
returning unto the Lord with full purpose of heart,
in the depths of humility and self-abasement:--yes, my Friends,
nothing less than this will do.
We must deny ourselves, take up our daily cross, and follow Him, who is "`holy, harmless,
undefiled, separate from sinners,
and made higher than the heavens`"--ever mighty to save, and to deliver;
and who will deliver out of every distress the soul that in sincerity seeks Him.

Come brother--come sister--come all my dear Friends;
let no earthly consideration whatever be suffered to hinder this important work:
for "`the night is far spent, the day is at hand;
let us therefore cast off the works of darkness,
and let us put on the armour of light`" that we may no longer bring forth fruit,
whereof we are ashamed,--for the end of those things is death;
but that we may "`be strong in the Lord, and in the power of His might,
to stand against the wiles of the devil.`"
"`For we wrestle not against flesh and blood, but against principalities, against powers,
against the rulers of the darkness of this world,
against spiritual wickedness in high places.`"
Let us "`pray always, with all prayer and supplication in the Spirit, watching thereunto,
with all perseverance;`" striving together in one mind for the faith of the gospel,
even for that faith which works by love, purifies the heart,
and gives victory over the world.
Thus shall we indeed be found with "`our loins girded about, and our lights burning,
we ourselves like unto men who wait for their lord, that when he comes and knocks,
they may open unto him immediately`" even unto Him who
said--"`Behold I stand at the door and knock,
if any man hear my voice, and open the door, I will come in to him,
and will sup with him, and he with me.`"
Then "`lift up your heads,
O you gates! even lift them up you everlasting
doors! and the King of glory shall come in.
Who is this King of glory? The Lord of hosts, He is the King of glory.`"

In the love of the gospel, I remain your affectionate friend and brother,

[.signed-section-signature]
Daniel Wheeler

[.letter-heading]
To John Hipsley, Hull

[.signed-section-context-open]
Second Month 3rd, 1832.

I sincerely hope that fruit will result from the
labours of the Committees +++[+++of Yearly Meeting]
in different parts of the country: it is high time for the Society to be roused,
and awakened to a sense of its deplorable state, which appears to me,
in too many instances, to be quite affecting and mournful.

I have lately written a letter and forwarded it to Sheffield,
for the examination of the Friends of Balby Monthly Meeting,
addressed to Friends of York Quarterly Meeting.
I began it with the expectation of writing to Balby Monthly Meeting;
but I found it must have a more general circulation
than the Monthly Meeting could give it.
If it should be approved and accepted, it cannot be too widely spread;
and with its present address it may probably be sent to the different Monthly Meetings,
and from there to the Preparative meetings, which would be a great relief to me.
But whichever way it may terminate, I must rejoice; for if accepted,
a great weight will be removed from my shoulders; and if thought objectionable,
I shall still rejoice in having endeavoured to discharge my duty;
which will enable me to bear the disappointment with patience and submission.

[.letter-heading]
To Elizabeth Backhouse, York

[.signed-section-context-open]
Third Month 29th, 1832.

Although a very poor creature myself, and often bowed down under a weight of exercise,
yet I am at times comforted to feel great love
in my heart for my dear friends in England;
greatly desiring that the present awful aspect of things may be an effectual means
of driving every individual of us home to the precious principle of Truth,
so mercifully implanted in every heart.
The importance of this,
as regards our own highly favoured Society as well as mankind in general,
is more and more stamped upon my mind;
believing that a great weight of responsibility will rest upon us,
if instead of letting our light so shine,
that others may see and glorify our heavenly Father,
we should unhappily be found darkening by our conduct
and conversation the path which leads to the kingdom;
and thereby causing others to stumble and turn aside.
Independently of this consideration, how great is the loss we are sustaining,
in contenting ourselves with merely hearing of the inestimable treasure,
instead of possessing the thing itself; which at seasons would fill our hearts with love,
and peace, and joy unspeakable.

I cannot help mourning over some who are seriously disposed,
and desirous of doing what is right;
and yet suffer their minds to be led astray with a continued round of publications,
containing accounts of the experience of others,--things perhaps valuable in themselves,
but still only tending to keep the mind afloat on the surface;
feeding upon visibles which can never nourish the vital part,
which remains still unsatisfied and hungering:
and all for lack of sinking down to the living and eternal substance;
which if once tasted,
nothing short of the same soul-sustaining food could ever satisfy again.

Now this is what I want all my beloved friends to enjoy, and to give up all to purchase;
to offer up all in measure, upon the same cross to the natural will and inclination,
as that on which the meek and lowly Saviour of the world was crucified;
and I verily believe, that this must be the heartfelt experience of us all,
before we can witness the fellowship of His sufferings, and know Him,
and the power of His resurrection, being made conformable to his death.
It is those only, who are buried with Him in baptism, that will rise with Him;
it is only those, who are willing to suffer in this life with Him,
who will reign with Him in life everlasting.
There are none who can enter into this truly interesting employment,
of engaging in the blessed and heavenly warfare,
with the same advantages as those in early life;
because the minds of such are undoubtedly much less charged and encumbered with the
surfeiting cares and perplexities of this transitory and perishing world.
To these, therefore, I would particularly address myself,
with an earnest recommendation in tender solicitude,
that they would look at the great and holy pattern; who, though the Son of the Highest,
"`made himself of no reputation, and took upon Him the form of a servant,
and was made in the likeness of men: and being found in fashion as a man,
he humbled himself, and became obedient unto death, even the death of the cross.
Wherefore God also has highly exalted him,
and given him a name which is above every name;
that at the name of Jesus every knee should bow.`"
And greatly do I desire,
that we may all be amongst the number of those that believe in his power;
that so our hearts may be softened into the same child-like obedience,
even to the death of everything in us, that stands opposed to the Divine will.
Then, indeed, with the heart shall we believe unto righteousness,
and with the tongue confession will, unavoidably and involuntarily,
be made unto salvation, even "`that Jesus Christ is Lord,
to the glory of God the Father.`"

I hope that all your fears and anxieties are hushed at present,
and changed into gratitude and thankfulness to Him,
who has thus far conducted the steps of your brother in safety,
and borne up his head upon the mighty ocean;
enabling him to put full trust and confidence,
in the Almighty and compassionate arm of never-failing strength,
as an infant slumbers on the bosom of its mother.
He is often present in my thoughts,
and my heart often follows him in love and sympathy across the trackless deep;
but thus far no feeling of discouragement as to his safety has dared to show itself.
I do greatly desire that the work in which he is engaged may abundantly prosper,
to the promotion of the Divine glory, the welfare of our fellow-men,
and his own peace and comfort,--the blessed and
sure rewards which crown the faithful labourer.
For "`he that reaps receives wages, and gathers fruit unto life eternal;
that he that sows and he that reaps may rejoice together.`"
May that Almighty power, in whose presence is life,
continue to surround him by night and by day,
and strengthen him to proclaim the day of the Lord,
even amongst those who are strangers to His ever great and excellent name;
that glory to the righteous Lord may resound from far,
and the voice of thanksgiving and praise be heard on high.
