== Chapter XV.

[.chapter-synopsis]
* Journey to Russia In 1833
* His Return, and Preparations for His Long Voyage
* Sails from the Thames the 13th of Eleventh Month, 1833
* Detention Off the Isle of Wight From Adverse Gales
* Letters and Extracts from His Journal

+++[+++Several circumstances having combined to delay the projected
voyage to the South Seas till the succeeding autumn;
our beloved father felt himself at liberty to
employ a part of the interval thus occasioned,
in visiting his family at Shoosharry.

The following letter describes some of the hardships of
travelling between Holland and Russia in that day:
since that time, however,
macadamized roads and good post-houses have been constructed
along the whole line from Hamburgh to Petersburg.]

[.letter-heading]
To One of His Sons

[.signed-section-context-open]
Memel, Fourth Month 1st, 1833.

[.salutation]
My Dear Joshua,

I was favoured to reach Hamburgh in safety, after a cold rough passage.
There was only a small number of passengers; but amongst these was a German family,
consisting of a mother and two little girls, and her brother, on their way to Memel,
where they reside.
We soon formed an acquaintance, and it afterwards appeared,
that we had almost from the first kept an eye on each other,
as likely to continue companions in travel;
this has now been fully and agreeably realized,
confirming a belief which had fastened on my mind previously to setting out,
that I should be provided for on my long and weary way.
Though Germans, they speak English so well, that I have had no difficulty as to language,
as we have passed along.
We purchased a carriage in Hamburgh for about £20 sterling, which when divided was easy;
and our expenses have amounted to little more than they would have done by diligence,
of which there are none running at this time of the year between Hamburgh and Berlin.
It is a britchka with a good head, and a leather covering from the head,
fastened to iron stanchions in front.
The mother and children were of course placed under the head,
as the most comfortable and secure place,
while J. J. F. and myself occupied the front seat the whole way:--on it, however,
the man must be weary indeed who could get much sleep.
The roads through the Mecklenburgh district cannot easily be described;
but I can tell you, that many articles of clothing were actually chafed into holes.
I ought however with thankfulness to add, that we were not once overturned,
though we frequently expected it.
We reached Berlin after thirty-nine hours travelling,
and were accommodated at the King of Portugal hotel.
The falls of sleet now seemed over; but the cold was still very piercing.
We started the next day, and, with the exception of two intervals of four hours each,
travelled on for five days and four nights.
Two stations on this side of Friedeburgh we seemed again to overtake the winter,
and have kept possession of it ever since.
Even to this day,
those parts of Prussia which anciently belonged to Poland are distinguishable:
the people still look different from their neighbours,
and their houses and modes of living are quite peculiar.
At one place they gave us the flesh of the wild boar;
but hunger reconciled us to it pretty well,
though otherwise it would have gone slowly down.

At Custrin, we passed the Oder, which was free from ice,
but some huge blocks were lying about the shores of the Vistula; and we were informed,
that the bridge had only been passable one day, so that had we reached it earlier,
we must have been detained.
We crossed the Nogatt at Marienburgh, and the Vistula at Dirschau, where in 1825,
I crossed it with dear Thomas Shillitoe;
and the mercies of the Lord so compassionately bestowed upon us at that time,
were renewedly brought to my remembrance.
From the advanced stage of the season, and the state of the roads,
it seemed dangerous to attempt going round by Tilsit,
as the river (Niemen) generally overflows the surrounding flat country,
to the prevention of travelling in the spring.
The only alternative was, to travel along the Courish Nerung,
a strip of land separated from the main land of East Prussia by the Haafe,
a navigable bay or arm of the Baltic.

On returning to England in 1825, I promised your dear mother,
that I would not go over this sand on that journey,
and the recollection of this was trying to me;
but the advantages in the present case were so great, that at length I agreed to venture.
No sooner had we left the regular post road, than the roads became heavy,
and were at last so bad,
as to make it doubtful whether we should be able to proceed by this route.
As night came on, our situation became more critical,
and the carriage seemed every few minutes in danger of
being dashed to pieces against tree-roots,
stones, or frozen masses of mud and snow.
On reaching the next station, a fifth horse was yoked, unasked for by us,
and uncharged by the keeper, but a fearful omen of the road to come.
Having now additional strength of horses,
the carriage seemed the more certain to be destroyed,
having to pass through a forest amongst many obstructions;
frequently we were thrown almost from our seats,
and the shock so violent as to produce pain in the head.
Sometimes we hove down on one side, then on the other; and again for short intervals,
rumbling with great rapidity over a frozen level surface,
which generally concluded with a violent concussion against some hard substance.
As we had only one driver to our five horses,
his principal business seemed to consist in cracking his long whip, which,
performed with great dexterity, made the forest echo and re-echo with the sound.
Late in the night we reached a lonely dwelling, and, to our surprise,
without any damage done to the carriage.
Here we waited till day dawned, and after a comfortless repast of coffee and black bread,
again proceeded.
From the nature of the quicksand of this part of the Nerung,
we could only travel close to the margin of the sea, where it is the most solid.
On our right hand were masses of ice,
thrown into piles higher than the top of the carriage,
by the force of the sea during the late gales.
At first the sea was pretty smooth; but the wind soon shifted dead upon the shore,
and as the gale increased, the surf broke violently on the beach,
occasionally forcing itself many yards higher up the shore than our carriage,
so that we seemed at times to be travelling actually in the sea,
until it again recoiled and showed the naked strand.
In this manner several hours passed,
until at length we began to edge away from the cutting blast,
amidst a heavy fall of snow, until we finally reached the Niemen or Memel river.
We were favoured to land in perfect safety on the quay
of Memel,--though such was the fury of the gale,
that the carriage, after it had been lashed in its chucks,
had to be lowered to the bottom of the boat, for fear of being upset in crossing.

Thus have loving-kindness and tender mercy still followed me;
and I actually feel better in health than when I left London,
though my legs and hands are somewhat swelled, probably with the cold.

[.offset]
+++[+++He returned to this country in the Sixth Month following,
where he was shortly afterwards joined by our brother Charles,
who had believed it his duty to offer himself as a companion to his father,
and was finally accepted in that capacity by the Meeting for Sufferings.
In a letter written on this subject, dated the 2nd of Sixth Month, 1833,
Charles Wheeler says,

"`Though by no means unconscious of my incapacity to act in a concern of such importance,
and however inexpedient to the eye of mere reason such
a step may be in a temporal point of view;
yet I cannot omit offering my assistance in any way
which shall be deemed best to promote the object,
allowing that it shall ultimately be deemed proper.
Nature, as might be expected,
shrinks from a step which involves such important consequences,
and which in itself simply considered, is by no means such as I should have chosen;
yet my only wish in the case is, I trust,
to act faithfully the part designed for me by that gracious Being,
who has an undoubted right to dispose of his creatures
according to the good pleasure of His will;
and keeping my obligation to do so in view,
I do not see how I can do other than make the offer which this is intended to convey.`"

After the concern of our dear father had received the sanction of the
Morning Meeting of ministers and elders in the Eleventh Month of 1832,
as it appeared a question of some intricacy, how such an undertaking,
requiring many voyages from island to island, could best be accomplished,
a Committee of the Meeting for Sufferings was
appointed to take the subject into consideration,
and to make such arrangements as might appear requisite for the object in view.
Having devoted much time and attention to the investigation,
after consulting several persons likely to give accurate information,
and after very mature deliberation, the Committee came at length to the conclusion,
as recommended by those whose local knowledge enabled them to form a correct judgment,
to purchase a small vessel for the purpose, not only as the most suitable,
but probably in the end, the least expensive mode of conveyance.

During the following summer, an opportunity occurred of purchasing, on reasonable terms,
the Henry Freeling, lately a post-office packet, of 101 tons register.
A number of Friends generously came forward, not only to pay for the vessel,
but at a considerable expense to prepare her for the voyage.
This offer the Committee gratefully accepted.

The necessary arrangements having been completed,
they sailed from the river Thames on the 13th of Eleventh Month, 1833,
and were proceeding down the English Channel,
when on the 21st they were overtaken by a heavy storm,
which induced them to seek for shelter near the Isle of Wight.
The following extracts are from his journal and letters written at this time.]

[.letter-heading]
To a Friend

[.signed-section-context-open]
Mother-bank, Eleventh Month 21st, Six o`'clock, p.m.

Some ships that sailed with us have already reached the Mother-bank;
but it is thought that many will have to return to the Downs,
as the weather is now becoming very stormy,
and the wind directly opposed to our course down the channel.
It is indeed a great favour to be enabled to find a place of safety,
and demands our humble gratitude and thankfulness to Him who presides over every storm,
whether of outwardly contending elements or of spiritual conflicts;
and though the present dispensation may impede our progress towards Cape Horn:
yet it is my belief, and I am comforted in it, that all will be well at last,
because ordered by Him in whose will I desire to rest, and in whose tender mercy I trust.

[.letter-heading]
To Mary Backhouse

[.signed-section-context-open]
Henry Freeling, Spithead, near Portsmouth,

[.signed-section-context-open]
Eleventh Month 22nd, 1833.

You wouldest perhaps hear from some kind friend,
how much I had been engaged previously to taking a final departure from London;
so that I could not write to any one, my time was so fully occupied day by day,
in rendering what assistance I could in the outfit of our little vessel.
In addition to the bodily fatigue which pressed upon me, you will, I am sure,
be at once aware and capable of entering into the state of mind of
one about to leave almost every thing near and dear on earth,
and that one already stripped of the crown,
far beyond the "`price of rubies`" but who can know it,
like him that has to bear the loss of a virtuous woman:
truly her children have abundant cause to "`rise up and call her blessed,
her husband also, and he praises her.`"
But however I may desire to be preserved,
and to strive against a disposition to murmur at the
dispensations of an ever-gracious and most merciful Lord God:
yet I cannot cease to feel as one born out of due time,
and as standing alone in many things amongst my brethren and sisters,
and even as an alien in my Father`'s house.

And now being far advanced in years,
and on the point of quitting these shores for remote climes, can it be wondered at,
if nature shrinks at the prospect before me;
and were it not for a knowledge in some degree of that Almighty power,
whose arm of strength is made perfect in weakness, often to our humble admiration,
and whose saving grace is at all times sufficient for us,
what would be my situation at this day? But blessed be
the Lord God of heaven and earth forever,
He has sustained me in a marvellous manner, and borne up my head at seasons,
when the waves and the billows have swelled and threatened to overwhelm my soul.
And now in mercy He enables me to look forward
with calmness and resignation to His holy will;
shedding abroad in my heart the constraining
influence of that love which makes not afraid,
but which, in the true dignity of its character, casts out fear,
and enables the Christian traveller to persevere in the path that leads to blessedness.
Having been strengthened thus far to come up in the obedience of faith,
that justifying heavenly principle, I think I may say without a disposition to boast,
(for truly all boasting is excluded,
and the creature laid low as in the dust,) in the words
of the great Apostle,--"`we have peace with God,
through our Lord Jesus Christ;
by whom also we have access by faith into this grace wherein we stand,
and rejoice in hope of the glory of God.
And we glory in tribulation also, knowing that tribulation works patience,
and patience experience, and experience hope,
which makes not ashamed;`"--a hope full of immortality,
through the mercy of God in Christ Jesus: which has been hid from ages and generations,
and is still hid from the great bulk of mankind because of unbelief.

Our little Henry Freeling being nearly equipped and ready for sea,
I took leave of the Committee of the Meeting for Sufferings, about a fortnight ago.
It was a solemn interview, in which all were encouraged in the belief,
that Friends had adopted the best mode that could be devised
for accomplishing the service which I have in view,
which was very satisfactory to many minds.
From one circumstance or other,
I was detained in the neighbourhood of London until the
Morning Meeting held in course on the 11th instant;
when I found that I was not clear without bearing a
testimony to the alarming state of things amongst us,
in a very close manner, and with a warning voice.
But although my exercise was great,
great was my consolation and peace after this was accomplished;
my way then seemed to open with clearness to depart.

On the 13th, accompanied by several Friends, we took passage in a steamer to Gravesend,
where the vessel had preceded us; and on account of the unsettled state of the crew,
it was judged proper that we should repair on board that night.
Before separating, we were favoured with a parting opportunity truly precious,
and like an earnest of Divine regard;
in which our minds were united and solemnized together
by the overshadowing of everlasting love.
It was as if the blessed Master was graciously pleased himself to preside,
and to sanctify the offering which he had called for; and under the consoling,
contriting influence of this merciful visitation, we bade adieu.
A coach was ready to take our Friends back to London,
as soon as they had seen us down to the beach, where dear Charles and I embarked;
and after a long row in the dark, we found the Henry Freeling lying at the Lower Hope.
The next morning we sailed for the Downs; but the wind being contrary,
we did not reach our anchorage till the 17th instant.

The next day, we sailed with light airs of wind in our favour;
but after having served us a little further than Dover, they forsook us,
and from that time we had to beat down the channel.
On the 20th, the weather assumed a threatening aspect; and yesterday,
it became so boisterous,
with such strong and never-failing indications of tempestuous westerly gales,
that it was deemed most expedient to bear up for the nearest port.
A signal being made, we were favoured to obtain a pilot,
as we stretched in upon the Isle of Wight; soon after this it blew violently,
and we were happily permitted to find shelter here, about an hour after night-fall.
It has blown a tempest all the night, which still continues,
so that at present all communication is cut off between us and the shore;
but last night I dispatched a few lines for the
information of the Meeting for Sufferings.

+++[+++On the 31st of Twelfth Month, he writes;]
in two days more we shall have been six weeks hereabouts,
and I am sometimes ready to think our dear
friends will be weary of hearing again and again,
that we are still buffeted by adverse gales at the Mother-bank;
but the will of the Lord must be done:
and I endeavour to wait patiently to see what He
will be pleased to do for His great name`'s sake;
for He knows my downsitting and my uprising, and understands my thoughts afar off;
and that the sole cause of my being here, is no other,
than that I may be found coming up in the path of
obedience to what I believed to be required of me.
The consciousness of not being here in my own creaturely will and activity,
reconciles me to all the turnings and overturnings of His holy hand;
and that He will continue to bear me up, is my humble prayer,
until He shall be pleased to say, "`it is enough.`"

[.letter-heading]
To Hannah Breary

[.signed-section-context-open]
Henry Freeling, 22nd of First Month, 1834.

Still at the Mother-bank.
I look round at others, but feel myself a close prisoner;
and forlorn indeed would be my condition,
were it not for a most merciful and heavenly Keeper,
whose unslumbering eye beholds the most solitary dwelling of his poorest creatures,
and regarding all their needs,
He opens his bounteous hand and "`satisfies the desire of every living thing.`"
I have written very few letters of late, for my mind has been otherwise engaged,
and often not a little depressed: but as regards our delay here,
although trying to the will of the creature,
I am comforted by a consoling evidence of having
done all that I could to forward the work,
to which I believe myself called;
and therefore I can rest peacefully amidst the restless waters,
which incessantly burst and foam within a few inches of my pillow.

It is now thirty-eight years since I was witness to a season
similar to this for south-westerly and westerly gales;
but with this difference, that the greater part of the winter was then spent at sea,
instead of at Spithead, and much more disastrously;
for after having been at one time seven weeks out of sight of land in a leaky ship,
we were driven back to Spithead at last, with the loss of twenty-seven of our people.
Should the present season be permitted to resemble that I allude to throughout,
we have now been only half the time that we have to be detained.

My dear Charles is as well as can be expected, but looks thin,
and although he says little, it is evident he feels the time long;
but he bears up with a good degree of Christian patience.
My heart often yearns over him, having some knowledge of the bitterness he feels,
and gladly would I share in his conflict to spare him;
but I am sometimes reminded of those expressions--"`Heaven tempers the
wind to the shorn lamb,`" and it may be added,--"`Shorn indeed,
and to the quick.`"

On Fifth days, we regularly sit down together in my cabin, to wait upon the Lord;
and though frequently feeling something like what is described
as the solitary "`sparrow on the house-top,`"--yet we know
that even these poor outcasts are cared for;
and are sensible that strength is renewed, though perhaps, but in small degree.

[.offset]
+++[+++During the detention of the vessel,
it appeared that advantage would arise from a change
being made in the person who had the charge of her;
and while the Committee were looking out for a more suitable one to supply his place,
Daniel Wheeler thus writes, under date of 15th of Second Month, 1834.]

In treating with a person to take the command of our vessel,
there are many stipulations which ought to be made and insisted upon,
besides nautical skill and other qualifications.
In the first place, it should be understood by the person in treaty for the station,
that we are a Temperance vessel;--secondly,
that the crew are regularly assembled in the cabin twice on every First day,
for devotional purposes;
and also that the Scriptures are read every
morning and evening in the cabin on other days,
when both the captain and mate are expected to (and now do) attend; thirdly,
that as much as practicable, all unnecessary work is dispensed with,
as regards the sailors, on the First day of the week,
to afford them a portion of time for themselves.
These things ought, I think, to be thoroughly understood in the outset,
so that nothing unpleasant may afterwards occur,
when perhaps it would be too late to make them
obligatory and bring about their establishment.
My motive for mentioning these particulars,
is not to make the way more difficult for my dear Friends;
but in order to save both time and trouble,
and perhaps prevent much disappointment and uneasiness in future.

[.offset]
+++[+++Owing to a succession of contrary winds and boisterous weather,
very unusual for such a length of time, their vessel, with many others,
was detained until the 10th of the Third Month, 1834, when they set sail.
On the 14th, Daniel Wheeler writes,]

It is more than three months since I had my foot on the shore;
but if I had not persisted in remaining on board,
I should not have been in possession of the true character of our seamen,
nor of every minutiae of the state and condition of our vessel.
We have put her in the best trim which we are capable of doing,
and must rely on One who is Almighty to help; and if He is but with us,
we shall have nothing to fear.
Good indeed, +++[+++he adds,]
has it been for me to be here; and true it is also,
that sufferings and tribulations have only been permitted in
boundless mercy to draw me nearer and nearer to the bosom of my Lord,
the only but never-failing source of consolation in every time of trial and distress:
however dark the hour of conflict, the entrance of His word is light and life.
+++[+++He further observes,]
that the present great object of my life, the service before me,
revives at seasons with increasing and encouraging brightness to my view.

[.offset]
+++[+++The same day, being that previous to their sailing,
he addressed a farewell letter to the Committee of the Meeting for Sufferings,
as follows:]

[.signed-section-context-open]
Henry Freeling, Mother-bank, Third Month 14th, 1834.

Upon reference I find that it is now considerably more than three
months since I began a letter for the information of my dear friends,
when anticipating that before long we should be permitted to direct
our course across the trackless ocean to the southern hemisphere;
but I had not completed more than half a sheet of paper,
when the progress of my pen was arrested,
by circumstances which have prevented any further addition being made until this day,
when the way seems to open for resuming the subject--our departure being at hand.

Among the many multiplied mercies and blessings which unceasingly
flow from the bounteous and compassionate hand of Him,
who "`crowns the year with his goodness,`" and "`satisfies the
desire of every living thing,`"--I feel bound to acknowledge
with humble thankfulness and admiration,
our long detention on these shores.
Notwithstanding there have been many gloomy days, and days of darkness,
"`as the morning spread upon the mountains,`" and many
long and dreary winter nights to pass through,
when the raging storm has again and again whitened with
foam the surface of the agitated deep around us;
and not only the strife of elements to witness without,
but a conflicting and spiritual strife within,
"`tossed with tempest and not comforted;`" yet how unspeakably
great the faithfulness of our good and gracious Lord God!
"`His compassions fail not,`" but have been, and still continue to be,
"`new every morning,`" as the returning day;
for in moments of the greatest conflict and trial there has been something permitted,
like the "`bow in the cloud,`" for the poor mind to look at, to animate, and cheer,
and to strengthen with hardness to endure and to stand firm.

But although moon after moon has waned,
and faith and patience have been beset as on the right hand and on the left,
and the afflictions of the gospel have at times been permitted to abound;
yet to the glory, and honour, and praise of Him, whose name ever excellent and adorable,
shall be great among the nations,
from the rising of the sun to the going down of the same,--the
consolations of the gospel have also abounded,
in a degree of the fulness of that heavenly blessing which makes truly rich,
and whereunto no sorrow is added; when faith has been mercifully strengthened,
and patience renewed under the tribulations of the day.
And notwithstanding an untrodden path has been my portion, yet after all,
though weakness and fear are my constant companions by the way,
safety and peace have been hitherto found.
I would, therefore,
encourage all my beloved friends to keep near to their heavenly Teacher and Leader; who,
if faithfully followed, will not only conduct their steppings to a hair`'s breadth,
but will preserve and keep the mind in calmness and serenity, securely as in a pavilion,
from the strife of tongues.

In addition to the marvellous loving-kindness I have thus endeavoured to portray,
many other mercies and blessings have been showered upon our heads,
during the apparently long and unaccountable
detention of our little bark upon our own coasts;
these I have often had to number with grateful sensations,
when the light has shone brightly,
and manifested clearly to my finite understanding how much we should have missed,
if our progress had not thus been arrested.
So that with myself, instead of this delay having been productive of regret,
or the cause of letting in fear or doubt,
to stagger or depress my tribulated mind,--I do, my dear friends,
hail it with gratitude and thankfulness,
as the gracious and compassionate dealing of my Lord and Master;
not only as a time of Divine favour and condescension,
but as an earnest of His love and mercy, for our encouragement, instruction,
and future benefit,
graciously vouchsafed,--a time of preparation for the important work before us,
and of weaning from every dependence and guidance which are not of Him,
to strengthen our confidence in His power to help and deliver out of every distress;
who not only commands the storm,
but at whose rebuke the mountain billows cease to undulate,
and lo! "`there is a great calm.`"

Within the last two or three days,
the prospect of liberation has begun to dawn with clearness; but I trust,
that if even a further detention should be meted out to us,
either here or in some other port, the same resignation to the Divine Will,
will be vouchsafed: for although I have for more than two years past,
felt anxious to move forward in a work,
which has yet to begin when the decay of nature is visible,
and the shadows of the evening proclaim, as they lengthen around me,
the steady decline of life`'s setting sun;
yet I have been frequently comforted by a renewed evidence,
that we have not yet been here one day too long.

It will, I feel assured, afford my dear friends much satisfaction to know,
that the crew of the vessel,
notwithstanding the frequent though unavoidable communication
with the neighbouring shore for so great a length of time,
have given no cause for uneasiness by improper conduct,
and that they have at all times behaved, with scarcely an exception,
in an orderly and agreeable manner:
the captain now provided for us seems to be judiciously selected, and the man who,
beyond all expectation, is admirably adapted to aid and assist,
by example and experience, in the accomplishment of the important object before us:
so that I hope what has passed, and what may yet be in store for us,
will be found and acknowledged to be among the
"`all things that work together for good.`"
I must not omit adding,
that the solemn covering frequently witnessed in mercy to prevail and preside over us,
when sitting together before the Lord,
is worthy to be commemorated with humble gratitude,
as the strongest and most indubitable evidence for our encouragement,
that at seasons "`He is with us of a truth.`"

As it is now a period of the year when ships seldom sail to those parts to
which we are destined,--whether we proceed by the Cape of Good Hope,
which is most probable, or by Cape Horn, in either case a wintry season awaits us;
but my trust is in the Lord,
not doubting but that we shall have the privilege of
the prayers of the faithful for our preservation:
and though conscious of our own weakness and utter unworthiness,
and often under a feeling of being less than the least of all my dear
brethren and sisters that are alive in the unchangeable Truth;
yet I think I can say that these things trouble me not, nor move me,
neither count I my life dear unto myself, so that I might finish my course with joy,
and the ministry which I have received of the Lord Jesus,
to testify of the gospel of that grace, "`which brings salvation,
and has appeared unto all men,`" teaching all;
that so from the uttermost parts of the earth songs of praise may be heard,
and the grateful tribute of "`thanks be to God for his
unspeakable gift,`" may resound to his glory:
for it is not of him that wills, nor of him that runs, but of God that shows mercy;
it is "`not by might nor by power, but by my Spirit, says the Lord of Hosts.`"

And now, while my heart is bearing towards the isles afar off,
the same constraining love which wrought the willingness to
leave all for my gracious Lord`'s sake and His gospel`'s,
extends its binding influence to all my dear brethren and sisters,
of every age and of every class, wherever situated, and however circumstanced;
desiring in tender and affectionate solicitude,
that they may be found steadfastly following the footsteps of those honourable and
worthy predecessors in the same religious profession with ourselves,
who have long since rested from their labours, and whose memorial is on high;
who bore the burden and heat of a day of deep suffering,
in the faithful discharge of their duty,
for the support of those principles in their original purity and brightness,
which have been transmitted to us.
If any should feel sensible of having fallen short in this important work,
let me in tenderest love encourage such to be willing
to humble themselves under the mighty hand of God,
even to the state of little children; and to turn inward to the pure,
unflattering Witness, which cannot deceive nor be deceived;
to be willing to enter into a diligent and heart-felt search,
and patiently and impartially examine how far those
indispensable conditions are submitted to on their part,
without which none can be followers of the meek and lowly Jesus.
Where is that self-denial and the daily cross He first enjoined? Are
we denying ourselves those gratifications of time and sense,
which cherish and keep alive in us the evil propensities of fallen nature,
that separate man from his Maker, and like the little foxes which spoil the tender vines,
designed in richest mercy to bud, blossom, and bring forth fruit,
lastingly to remain to the praise and glory of
the great Husbandman? Without faithfulness,
there will be no fruitfulness.
It is not giving up or forsaking this or that little thing,
to part with which is little or no sacrifice or privation, that will suffice;
a full surrender of the whole will in all things, must be made to Him,
whose sovereign right it is to rule and reign in our hearts.
Let none plead for disobedience in these little things,
on the ground of their being such; for if such they really are,
they are the more easily dispensed with, and not worth retaining;
and a tenacity in wishing to preserve them, assuredly indicates,
that they have more place in our affections than perhaps we are aware of:
"`He that loves father or mother more than me, is not worthy of me;
and he that loves son or daughter more than me, is not worthy of me;
and he that takes not his cross, and follows after me, is not worthy of me.`"

And now, my dear brethren and sisters, "`may the God of peace,
who brought again from the dead our Lord Jesus, that great Shepherd of the sheep,
through the blood of the everlasting covenant,
keep all your hearts and minds`" and "`make you
perfect in every good work to do His will,
working in you that which is well-pleasing in His sight, through Jesus Christ;
to whom be glory forever and ever.`"

In the love of the everlasting gospel, accept this expression of farewell,
from your affectionate friend and brother,

[.signed-section-signature]
Daniel Wheeler

15th of Third Month, at Sea, and clear of the Needle Bocks, all well.

+++[+++During their long stay at the Mother-bank,
Daniel Wheeler says in his journal.]--It has been our usual practice,
except when prevented by particular and sufficient causes,
to assemble the crew in the cabin twice on every
First day of the week with the captain and mate,
to read to them a portion of the Holy Scriptures,
and to sit together before the Lord in solemn silence.
The first time of our assembling in this manner,
it was my lot to break in upon the silent solemnity
which prevailed in a remarkable manner over us,
and to call their attention to the magnitude of the voyage in contemplation;
feeling no hesitation in believing,
that every individual present was desirous that it might be prosperous;
and the desire of my heart was, that it might be so in reality,
not only as regarded the safety of the ship and of ourselves,
but that it might prove a voyage towards the kingdom of heaven,
into which nothing that is unclean or impure, "`nothing that works an abomination,
or that makes a lie, can ever enter.`"
In order that this might be the case, we must do every thing in the fear of the Lord;
and the way to prove we feared Him, was to keep a diligent watch over our thoughts,
words, and actions, etc.

Although this was a novel scene to all of them, they behaved with great solidity,
and becoming attention;
and the peaceful covering so evidently manifest to spread and remain over us,
was truly precious and worthy of commemoration.
Although the weather was extremely rough and boisterous at the time,
and the sea occasionally bursting over the deck, all was quiet and undisturbed below.
On inquiry when we broke up,
it was found that several of the men were not provided with copies of the Scriptures.
They were of course, in due time, all furnished.
