== Chapter XVII.

[.chapter-synopsis]
* Departure from Rio de Janeiro
* Proceed by the Cape of Good Hope for Van Diemen`'s Land
* Heavy Seas and Stormy Weather
* Remarkable Preservation
* Continuance of Stormy Weather
* Lightening the Vessel
* Hurricane
* Frequent '`Lying To`'
* Tremendous Storms

Sixth Month 2nd, 1834.--Since leaving the land,
the winds have been so strongly opposed to our going round Cape Horn,
as nearly to put that course out of sight:
today we are so far off the coast of South America as
to be exposed to the swell of the great South Sea,
which is no longer kept from us by a point of land which forms the projecting Cape;
this swell is prodigious,
and plainly shows the turbulent state of the weather in that quarter;
it seems like a final settlement and removal of any thing like a doubt in my mind,
as to our being in the right track at present.
After midnight the weather became very rough,
and the wind inclining more and more southerly,
rendered our position in sailing very critical.
Before four o`'clock, a.m., two heavy seas broke in upon us,
one of which stove in a part of the bulwark on the starboard side:
happily none of the watch on deck were washed overboard.
From this time things got rapidly worse,
and the only alternative now left was to bring the vessel to,
with her head to the wind and sea,
under suitable storm-canvass to maintain that position.
In addition to the great risk attending at all times any circumstance connected
with '`lying to,`' it was a position in which we had not yet tried the Henry Freeling.
It was not indeed an everyday occurrence for a small vessel,
which we have had hitherto no opportunity of proving under more gentle circumstances,
to be brought round against a sea,
which had nothing to break the range of its sweeping
influence between her and the south pole.
Captain Koen manifested great coolness and ability on the occasion;
and soon after day-break all things were ready to accomplish our intended purpose:
to effect which, an interval was waited for, when the blast should lull a little:
and while much depended upon a timely re-action of the sails,
so as to prevent the vessel from forcing herself
with too great violence into the opposing waves,
as her head came round towards them;
at the same time it was indispensably needful to
keep a sufficient quantity of canvass set,
to guard against being overtaken and overwhelmed by the mountain waves,
which in an awful manner were now threatening us behind.
A few minutes relieved us from suspense and anxiety,--and although heavy laden,
with our newly recruited stock of water,
some of which encumbered the deck,--yet we had the comfort to see the
vessel rise in a lively manner to the surface of the loftiest billows,
before any material quantity of their contents had time to burst over her.
As the wind blew directly from an immensity of ice,
a change so sudden from the great heat we had so recently witnessed,
to such a cold penetrating blast, was sensibly felt by all on board.

10th.--Towards evening it again became stormy with much rain;
the sea breaking over us with great violence, scarcely any part, even below deck,
could be preserved free from wet,
and all our ingenuity was called forth to preserve our beds moderately dry.
At times the weight of water seemed too much for our little bark to bear,
from which she could scarcely extricate herself,
before another deluge burst in upon her deck.
A state of desertion was my lot throughout the day,
and although at seasons I was ready to say, "`Lord,
do you not care that we perish?`" yet I was not permitted in
the darkest moment to castaway my confidence;
although for many hours it seemed needful for us to stand as with our lives in our hands,
not knowing how soon they might be called for.
At midnight the scene was truly awful, the wind blew in a furious manner,
and the sea raged with increased violence, with heavy falls of rain.
The mercury in the marine barometer, which had been falling all the day, became lower,
and the little vessel seemed to twist and bend beneath her heavy burden.
At this moment of extremity, behold a shift of wind to the south-west,
which instead of taking aback suddenly the little canvass we were scudding under,
(which might have produced consequences above all
others the most to be dreaded) came regularly round;
and the captain, availing himself of this moment,
directed that the vessel should be '`hove to.`' Captain Keen
came to me shortly after this circumstance had taken place,
to acknowledge how providentially this change had been ordered,
being sensible of the favour thus graciously bestowed upon us.

Sixth Month 13th.--This date has not failed to awaken feelings of painful
reflection in reference to days which have long since passed away,
it being thirty-three years since it pleased the God of all my
mercies to bestow a crown upon the head of a poor unworthy creature,
even the rich blessing of a truly virtuous wife, at the close of a meeting at Doncaster.
Full well at this remote period do I remember the solemn and
delightful season with which we were favoured,
from the beginning to the end of the meeting.
Dear Thomas Colley appeared largely in testimony on the occasion,
to the tendering of many present.
It was indeed an earnest of the heavenly Master`'s love;
which never ceased to follow us through all the vicissitudes of time,
during a life not a little chequered,
for a term of more than thirty-two years and a-half,
when He was pleased to deprive me of my greatest earthly treasure,
and to take back that which He gave; but it was His own, I verily believe, even His,
the same who enabled me to say, in the moment of my greatest distress,
"`blessed be the name of the Lord.`"
In looking over the different relatives and friends present on the above occasion,
there is at this period scarcely one of those individuals,
at that time about our own age, who now survives;
and I find that many of them much younger than ourselves,
have been summoned from works to rewards: thus,
while many of my contemporaries have finished their earthly career,
I am still spared a little longer,
a living monument of the Lord`'s everlasting mercy,--for the purpose, I humbly trust,
of declaring unto others what He has done for my soul,
and to show forth the praises of Him,
who has translated me out of darkness into his marvellous light.
And although the sacrifice I am making may appear great,
and be rendered more formidable by the late hour
in the evening in which it has to be offered;
yet in my estimation it is small indeed, and light as the dust of the balance,
when the love and mercy, long-suffering and compassion, of my good and gracious Lord God,
are brought into remembrance; who has redeemed my life from destruction,
and crowned me with loving-kindness and tender mercies,--to myself incomprehensible,
and I am persuaded only known in the same degree,
to those whose sin is blotted out as a cloud, and their transgressions as a thick cloud,
by repentance toward God, and faith toward our Lord Jesus Christ,
who came into the world to save sinners, of whom each of us,
in the depth of self-abasement, can say, "`I am chief.`"

17th.--A considerable press of sail was carried in the
hope of making the island of Tristan d`'Acunha,
and two others lying at no great distance from it.
Next morning, the 18th, the weather was rough and threatening, with fog and rain.
The captain considered it the more needful to obtain a sight of the islands;
and relinquishing the design of passing to the northward of them,
we bore up after day-break, in a southeasterly direction,
to avail ourselves of the strong but favourable wind.
As the day advanced, the wind and sea increased,
and the fog was so dense close down to the horizon,
that there seemed but little prospect of discovering the land,
at a sufficient distance to prevent our running directly upon it.
As the afternoon wore away, the danger hourly increased: but at this juncture,
the Everlasting Arm of strength, in customary mercy and compassion,
was signally displayed for our preservation,
and in such a manner as wholly to exclude the slightest
pretence of mortal man`'s having the least share in it.
The mist cleared suddenly away; and though but for a short interval,
yet it was sufficient to discover a lofty rocky island, about half a mile distant,
standing nearly perpendicularly out of the sea,
far above the mast-head of the Henry Freeling.
We soon perceived that this was the island called Inaccessible, and appropriately so,
as from its vast height and steep approach, no landing apparently on the side next to us,
could possibly have been effected.
This seemed at once to relieve our anxiety,
and the captain now considered all danger as past,
and that we should safely run between this island and another called Nightingale Island,
although not able to see it on account of the fog,
these islands being ten miles asunder.

Thus cheered, we pursued our course with great velocity,
as the wind had increased in violence soon after the high rocky island was first seen.
But in another hour,
our prospect was suddenly clouded by the appearance of
more rugged rocky land on the same side of us.
This circumstance, for a time, staggered all our hopes, as it could not be accounted for;
and of course we knew not how soon some unknown
lurking reef might wreck our fragile vessel,
which was scourged on by a hurricane-blast with greater speed, it is probable,
than at any previous time.
In this situation,
the night was gathering blackness and darkness in the midst of a heavy tempest.
The captain, though evidently unprepared for this mysterious circumstance,
conducted everything with calmness and composure,
and concluded to haul two or three points to the southward,
lest a shift of wind in the night should drive us back upon these desolate islands.
He afterwards drew a sketch of these islands,
with their respective latitudes and longitudes, showing the drift of the Henry Freeling,
and the manner in which she had approached them in the night,
and after day-break in the morning;
plainly demonstrating the true cause which placed the islands
in an apparently unknown position as we passed them,
exactly showing why we did not pass between them, as he expected we should do,
which merely arose from the course having been altered to a more southerly direction,
unremembered in the moment of surprise.
Although I have thus entered into the above details,
yet it plainly appeared to me at the time,
and is here recorded with humble gratitude to the great Preserver of men,
that if the weather had continued so impenetrably thick and
dark as totally to have hidden the islands from our sight,
still we should have been guided past them in safety,
as was evidently the case when first they were discovered,
notwithstanding the alarming proximity of their lofty crags and precipices.

19th.--Before sunset we got sight of the island of Tristan d`'Acunha.
It is fifteen hundred miles from any other land,
except the two small islands before-mentioned,
and is said to be upwards of eight thousand feet above the level of the sea;
though we are now fifty-seven miles distant, it is still plainly discernible,
even to my imperfect sight.

20th.--It was observed that the mercury in the barometer,
was this morning again on the decline, and by four o`'clock, p.m.,
had fallen to 29-53. The wind freshened throughout the day,
and at night blew with such tremendous violence,
accompanied with heavy rain and some lightning,
as compelled us again to seek safety by '`lying to;`' but,
however trying to be thus disabled from making use of a fair wind when it blows,
I believe we are truly thankful in having such a source
of relief from the terrors of the storm afforded to us,
poor solitary wanderers on the mighty deep.
It is three weeks today since we left Rio,
and up to this time we have not seen another ship.

21st.--Still '`lying to,`' in heavy gales from the southwest,
with frequent squalls still more heavy, with rain and forked lightning:
to use the expression of the carpenter who had charge of the morning watch,
'`the lightning had been flying about like ribbons.`' The
weather was extremely cold and penetrating.
Owing to the water searching through every little
crevice from the working of the frame of the vessel,
my berth has become so damp,
as to compel me to have recourse to any part of the main cabin,
where most free from dropping water.

Sixth Month 22nd.--'`Lying to,`' as yesterday;
the storm still raging with unabated violence, squalls, heavy rain,
and lightning through the night.
The sea having risen to a fearful height, frequently inundated the deck of the vessel;
and from the continual working of her whole frame,
our bed-places have been unfit to sleep in,
the water having found its way through numerous chinks.
This morning early, a heavy sea broke into us,
bringing a larger quantity of water upon the deck than at any time before.
To myself a very remarkable and striking event took place this morning.
Shortly after the vessel had shipped a heavy body of water,
I went up the hatchway to look round for a short interval;
at that moment the seas were running in mountainous succession,
and I observed that some of the loftiest of the waves
were very nearly prevailing against our little vessel;
it seemed as if she could not much longer escape being overwhelmed by them altogether.
I made no remark to any one, but soon after we tried to get some breakfast:
while so occupied,
one of the men called down to inform us that there was a sight worth looking at on deck;
it was a large collection of a species of whale, close by the ship.
I thought I should like to see them;
there were perhaps more than two hundred of these animals close to us,
each about twelve feet long.
When I went upon deck after breakfast they were still close to our bows;
and the man at the helm said, that they served as a breakwater for us:
their being so was afterwards mentioned by some other person.
At last my eyes were open to discover the protection
they were affording to our little struggling vessel:
they occupied a considerable portion of the surface of the sea,
in the exact direction between the vessel and the wind and waves, reaching so near to us,
that some of them might have been struck with a harpoon;
they remained constantly swimming in gentle and steady order,
as if to maintain the position of a regular phalanx,
and I suggested that nothing should be done to frighten them away.
It was openly remarked by some, that not one sea had broken on board us,
while they occupied their useful post; and when they at last retired,
it was perceived that the waves did not rage with the
same violence as before they came to our relief.
I give this wonderful circumstance just as it occurred;
and if any should be disposed to view it as a thing of chance, I do not;
for I believe it to be one of the great and marvellous works of the Lord God Almighty.
These friends in need, and friends indeed,
filled up a sufficiently wide space upon two of the large swells of the ocean,
completely to obstruct the approach of each succeeding wave opposed to the vessel;
so that if the third wave from us was coming in lofty foam towards us,
by the time it had rolled over and become the second wave,
its foaming threatening aspect was destroyed entirely,
reaching us at last in the form of a dead and harmless swell.
They are very oily fish, but seldom larger than to yield about two barrels of oil;
they are commonly called black fish.

Sixth Month 23rd.--Still '`lying to,`' sustained through another rough and perilous night;
the wintry storm yet howling around us.
We remarked, after having just passed the shortest day in this climate,
that our friends in England had returned home from the Yearly Meeting,
and were enjoying the delightful days of summer at their greatest length.

Sixth Month 26th.--The tempestuous weather,
which our little vessel has had of late to contend with so largely,
the great length of voyage still unaccomplished,
at the most unfavourable season of the year,
have frequently been a subject of serious thought, but more particularly from witnessing,
since the last heavy gales,
considerable and almost daily increasing leakage from different parts of the deck,
owing to the great strain to which her upper works have been subjected,
by the enormous weight of lumber, together with part of our stock of fresh water,
upon the deck.
After looking at the state of things on every side,
and taking the different bearings of the whole into deliberate consideration,
it seemed the most prudent measure,
in the hope of contributing to the future safety of the vessel,
and enabling her to perform the service looked forward to, in its fullest extent,
to lighten her deck, by launching overboard, on the first favourable opportunity,
every weight of spars, etc. that could be dispensed with.
As this could not be done in rough weather,
without the risk of injury both to the people and the ship;
and there being less wind and sea today, than for some time back, it was resolved,
if possible, to accomplish it.
Accordingly, four heavy logs, an old spare squaresail-yard,
a heavy spar intended for a top-mast, with many other cumbrous weights,
which tended to increase the weakness of the quarters of the vessel,
were cast into the sea without accident.
It is truly cause of regret thus to sacrifice articles,
which at a future day may be much needed;
but the necessity of endeavouring to relieve the present difficulty and distress,
compelled us to pass over that, which now can be looked at as remote,
and may never occur.
As this step has not been taken suddenly,
or hastily determined upon in the moment of impending danger,
when fear might have operated, but is the result of patient and deliberate observation,
I trust that our dear friends in England will see the propriety of our so doing.
Several of the articles thus thrown into the sea,
belonged to the vessel when first purchased,
and I believe the sum of five pounds sterling would cover the whole amount
of such things as were afterwards bought and intended as extra stores.
I was disappointed at finding on inquiry that the name Henry Freeling,
which was deeply branded on each of the four logs,
had not been previously cut out before they were thrown overboard,--lest
this omission should give rise to a report of our having been wrecked,
gone to pieces, or foundered at sea, if any of them should reach a distant shore,
or be picked up by another ship.

Seventh Month 2nd.--Since the 26th ultimo, the weather has been very rugged.
Tomorrow we expect to be abreast of the Cape of Good Hope,
but more than one hundred and fifty miles to the southward of it,
having kept aloof from the coast, in the hope of avoiding the currents and heavy gales,
which prevail in its vicinity at this season of the year.
To us, so far, it has not proved a Cape of Good Hope,
but a Cape of constant anxiety and fearful expectation,
having been marked by tempest after tempest, cold rain, hail, sleet, and lightning.^
footnote:[This passage will probably remind the reader,
that when Bartholomew Diaz first rounded the Cape,
he bestowed upon it the significant appellation of '`Cape of the Furies,`' which the
Portuguese authorities thought proper to exchange for its present name.]

7th.--Still '`lying to,`' the storm has continued all night,
and the sea makes very heavy upon us.
The mercury in the marine barometer sunk to 29° 30, then rose a little,
and again sunk lower in the tube.
As the night advanced, the storm increased with awful violence.
The strength of the wind was incredible, and the lightning appalling,
with a fall of rain and sleet;
the sea broke in upon our little ship in an alarming manner.
The poor men were lashed upon the deck with ropes, to prevent their being washed away;
benumbed with cold,
and at times floating with the vast load of water upon
the deck--their sufferings are not easily described.
The bulwark on the starboard side was damaged,
and the spray reached more than two-thirds up the main-mast.
In the morning, the seamen expressed considerable discouragement;
and I observed a disposition rather to make the worst of things.
The captain said
he hoped he should not see such another night in this vessel.
One person did not expect she would have kept up until morning.
When assembled at the breakfast table, I had to tell them, with a degree of firmness,
that a murmur ought not to be heard among us,
but rather the expression of thankfulness, that we are as we are.
On looking round at the ravages of the storm,
I was surprised to find that so little damage was done;
and the increase of pumping had been comparatively trifling to what might
have been expected from the violent and frequent strokes of the sea,
and the floods of water that had rolled over the deck of the vessel.

In the darkest part of the night, a distinct luminous appearance, or glow of light,
remained at our mast-head; a phenomenon only seen in dreadful weather,
when the atmosphere is highly charged with electric fluid.
The sailors call it a corposant.^
footnote:[(Originally written Corpus Sancti.) See John Woolman`'s Journal, Dublin edition,
1704, p. 212,]
I think such an appearance is mentioned in John Churchman`'s Journal,
or that of some other worthy.
The countenances of our men were considerably whitened this morning,
by the great quantity of salt,
which having been deposited by the constant wash of the sea, had dried upon their faces.

8th.--Early this morning the storm abated,
and at eight a.m. we bore away before it to the eastward.
In the course of the storm yesterday evening, unusual darkness gathered round us,
when suddenly the wind which blew with great violence, increased to a complete hurricane,
and roared in a terrific manner, and for a while closely threatened our little vessel.
The force of the wind was so great,
that the waves for the time almost ceased to undulate,
and the surface of the ocean became levelled and whitened with foam.
At this juncture I was comforted in beholding the calmness and
resignation with which my dear Charles was favoured.
At one time he remarked, "`What a painful situation those people must be in,
who have not a good reason for being exposed to similar distress,
when they find themselves overtaken by it.`"
I told him it was formidable enough,
even to those who felt themselves in the line of apprehended duty.

9th.--The wind moderate,
but the swell of the sea caused by the late tempest continues to impede our progress;
the motion however of the vessel is become greatly diminished: Charles remarked,
"`then are they glad, because they be quiet,`" which truly was our case.

13th.--This morning the monsters of the deep seemed roused from their secret abodes,
probably by the approach of elementary strife.
Several whales were observed about us:
a fine spermaceti whale followed for some time close to the vessel, exactly in her wake.
This was a full grown female fish,
and was thought to be nearly as long as the Henry Freeling.
As night approached another storm began to threaten.

Seventh Month 14th.--At ten a.m., it was so tempestuous,
that we again hugged the howling blast,
by '`heaving to:`' as the vessel came round with her head to the wind,
one heavy wave broke on board, but happily none of the crew were lost.
In the afternoon,
when it was thought that the storm had arrived at its greatest strength,
this hope was suddenly extinguished by the mercury falling in
a short space of time down to 29-50. The captain said,
"`We have done all we can,--trust in Providence only remains.`"
Heavy rain succeeded;
but instead of the bursting forth of another hurricane,
which the incessant thunder and lightning led us to expect,
it was observed that the roar of the wind was lessening;
it changed from northeast to north-west,
but shifted so gradually in the right direction for the vessel,
that the change was scarcely felt,
and the sea fell in full proportion as the wind abated.

Two or three days previous to this tempest,
I felt much depressed on account of my Charles, he having drooped more than usual,
from the effects of the cold weather;
the great length of time we had already been the sport
of the winds and waves since leaving Rio de Janeiro,
could not but excite a painful and discouraging fear lest his
strength should prove unequal to the remaining part of the voyage,
as we had only passed over about one thousand miles in distance,
since beginning to traverse the margin of the Indian Ocean;
and we are still greatly annoyed by the strong currents and
heavy gales which prevail from the direction of Madagascar,
and are probably attracted down the Mozambique Channel,
which separates that island from the coast of Natal, on the south-east shore of Africa.
But as the late storm approached, I felt, through unmerited favour,
increasing peacefulness and tranquillity,
which nothing during its whole continuance was permitted to disturb;
and in the most awful moment of uncertainty and impending danger,
fear had no place to enter;
this was utterly banished by the love of the ever-blessed Master that flowed in my heart,
and which in the true dignity of its heavenly power east it out:
and the language which at intervals continued to prevail and occupy the inner man,
with a soothing and encouraging sweetness,
was that of the Psalmist,--"`Delight yourself in the Lord,
and he shall give you the desires of your heart.`"
Thus indeed was strength truly administered,
according to the glorious working of His power,
unto all patience and long-suffering with joyfulness,
to endure and to give thanks to the Lord Most High.
I should shrink from making any remark on the state of my own mind,
while in the extremity out of which we have been so remarkably delivered,
did I not feel called upon by a sense of gratitude to our compassionate Lord;
at the same time a hope gleams through my heart,
that it will tend to strengthen the faith of some hesitating and
doubting fellow travellers who may eventually peruse these lines,
to "`follow on to know the Lord`" for themselves; and thus partake of His love, mercy,
and life-giving presence, and be encouraged to forsake all and follow Him,
"`nothing doubting.`"
wherever He may be pleased to lead:
for the declaration,--"`Lo I am with you alway,`"
will assuredly be verified in their experience,
and all earthly things will be estimated but as loss and dross,
in comparison with the excellence of the knowledge of Christ Jesus.

Seventh Month 22nd.--While lying to in heavy weather the forepart of last night,
(the fourth time within eight days,) I felt much exhausted for lack of rest,
and not a little discouraged by surrounding circumstances.
The almost incessant labouring of the vessel, and the heavy strokes of the sea,
which have so often assailed her battered sides,
could not fail to occasion extra pumping when it blew hard: although upon the whole,
she had suffered little since her deck had been freed from dead weights;
and yet every returning day seemed to bring a fresh tempest with it,
which kept the sea unceasingly agitated.
All these circumstances could not fail to occasion renewed thoughtfulness,
more especially as we have still more than one
hundred degrees of east longitude to run down,
before reaching our intended port,
and are so frequently compelled to '`lie to,`' for our safety,
lest the sea should overwhelm us altogether.
Thus I was letting in fear and doubts, and listening to the tempter`'s insinuations,
notwithstanding the multitude of mercies which
have been showered upon us for our deliverance.
Such is the frailty of human nature,
that when we see the waves of adversity boisterous about us, we begin to sink,
by letting in fear at the prospect,
although fully sanctioned at setting out by the Lord himself:
even the brightest gleam of sunshine soon loses its gladdening influence on our minds,
unless again and again renewed by the ever-blessed Master,
who having been touched with a feeling of our manifold infirmities,
pities the weakness of poor mortal dust.
After passing through considerable mental conflict, in contrition I went upon the deck,
supposing from the great motion of the vessel,
that the storm had continued all the night, and that we were still '`lying to;`' when,
to my surprise, I found a bright and beautiful morning,
the weather apparently entirely changed, the wind fair,
and the vessel gradually pursuing her route;
but the great and diverse swells of the sea still occasioned her to labour hard,
nearly as much as during the storm in the forepart of the night.
I could not help feeling ashamed and mortified in abasement of self,
in finding I had been thus duped by the grand adversary, who,
ever on the alert and unwearied,
had found the '`watch`' neglected in a darkened gloomy hour of trial and perplexity;
and thus he improved the opportunity to his own advantage,
leaving me covered with self-reproach as in dust and ashes.

27th.--It is cause of humble admiration and
gratitude to observe within the last few days,
an improvement in the health of my Charles;
considering the cold and damp to which he has been so long exposed,
without having felt the glow of a fire the whole winter,
and the small portion of exercise that can possibly be obtained,
beyond what the motion of the vessel supplies,
he is certainly sustained in a very remarkable manner.
I have of late been much comforted by a circumstance
brought to my recollection respecting him,
I feel no hesitation in believing,
by the good remembrancer,--although many years have passed away since it occurred;
but a lively image of the whole event is now strikingly brought home to my mind.
When he was about four years old,
it was concluded that the time was come for him to begin to attend meetings;
and I well remember sitting under the gallery in Sheffield meeting,
about twenty-one years ago,
when he was conducted by one of his brothers to a seat at the top of the meeting,
for the first time.
I had been in my seat a short time previously, and on seeing him led up the side aisle,
it sprang up in my heart to offer him that day unto the Lord.
Although at the time a pretty strong impression was
engraven on my mind which yielded a peaceful review,
to the best of my knowledge it has since been as much obliterated,
as a thing that never took place, from that period until a few days ago,
when it was recalled fresh and fragrant to my understanding.

Seventh Month 28th.--The height of the waves compelled
us again to '`lie to,`' under storm-canvass,
for thirty hours.
This gale increased to a violent degree,
but differed in most respects from all we had previously been called to witness.
In all the preceding cases there had been a change of a
favourable nature to cheer us through the dreary tempest;
but now every alteration appeared to be against us,
serving only to render our situation more and more alarming.
It did seem as if we were now cast off, and left to the fury of the wind and waves;
and notwithstanding we had with our own eyes seen as it were Jordan driven back,
and the waters of the Red Sea stand as on heaps, for our deliverance;
yet now the glorious presence was withdrawn, and so completely hidden,
that no trace could be perceived to administer one glimmering
ray of hope in the midst of our complicated distress.
On looking at our forlorn situation, and the overwhelming appearance of the storm,
the fury of which had been only aggravated by every change which had so far taken place,
it now seemed too late for any thing to occur that could operate in our favour,
as the sea was running in confused heaps different ways in a frightful manner,
caused by the wind having shifted to different points,
and from each point blowing furiously.
About three o`'clock in the afternoon, the mercury fell lower and lower,
when we were overtaken with a squall of wind, truly appalling and terrific,
which in a short time afterwards was succeeded by a second still more violent; but,
through the medium of these two dreadful blasts,
which at first threatened nothing but destruction,
our deliverance was marvellously effected.
Such was the fury of these two tyfoons, that they actually, in a short space of time,
changed the wild and disfigured surface of the troubled
ocean from unruly mountains to a rugged level,
by their boisterous breath, leaving nothing but a sea white as milk with foam.
From this time the storm subsided,
and at midnight we were again enabled to bear away for Van Diemen`'s Land,
distant about four thousand seven hundred miles.

31 st.--'`Lying to,`' with an increasing tempest around us.
Charles and myself sat down together, it being Fifth day;
though "`troubled on every side, yet not distressed; perplexed, but not in despair;
persecuted`" again and again, but verily "`not forsaken;
cast down but not destroyed`"--however much like two poor
outcasts tossing on the bosom of the restless waters,
far from friends and native home,
but under a peaceful feeling of resignation and poverty of spirit.
The barometer was low yesterday, but had begun to rise a little: in a short time,
however, it began again to sink, and dropped down to 28-50,
being an inch lower than when we experienced the
hurricane in the neighbourhood of the Cape of Good Hope.
This circumstance spread a gloom over us;
having witnessed such dreadful weather about three weeks before,
when the mercury was at 29.50,
and knowing the correctness of the barometer in former cases,
our apprehensions were increasingly awakened;
and under a sense that another close trial was not far distant,
we endeavoured to wait patiently the event, though in painful suspense, with, I believe,
a full surrender of ourselves to the will of Almighty God;--remembering my poor,
scattered orphan family and dear relations and friends
everywhere,--in earnestness and brokenness before Him,
who knows the anguish of a tribulated soul.
Towards evening the wind and sea increased in such a dreadful manner,
that the horrors of the scene cannot be faithfully described.
It blew a perfect hurricane;
and although we had only sufficient storm
canvass set to keep the vessel`'s head to the sea,
yet she seemed in danger of being torn to pieces with the intense pressure,
against which she had to struggle for some hours together.
The captain was much alarmed, and said,
"`If she gets through this, she will get through any thing.`"
The agitated waters broke in upon us on every side,
like cascades, frequently loading the deck with their weight:
the whole frame of the vessel trembled and shook with the strain in an unusual manner.
This hurricane at length became a steady gale of wind, but very heavy.

Eighth Month 4th.--The weather very boisterous,
although we were permitted to keep before the wind and sea.
Today we were escorted by an unusual number of birds, such as the albatross, Cape hen,
stormy petrell, etc.
On the 5th we were compelled again to '`lie to`' and this day, the 6th,
we were again '`lying to.`' At three o`'clock, p.m.,
we were assailed by a most violent tempest, with heavy falls of rain, sleet, and hail;
the sea curled in an unusual manner,
and raging in opposite directions;--our little bark seemed as
if she could not long sustain the unequal conflict,
as the wind kept increasing to a degree almost inconceivable,
except to those who may have witnessed the
hurricane with all its furious and angry growl.
Everything was done that could be devised for our relief;
but all our efforts seemed overpowered,
and we could not wholly divest ourselves of an apprehension that she
must eventually fill and founder by the lee with us at last,
if the fury of the storm were not curbed; of this, however, there seemed no probability,
and the approach of night served only to increase its horror, and renew its force.
In this situation one would have supposed that no relief could
have availed short of an abatement of the storm;
but true it is, that an increase of its fury produced a circumstance,
which at once enabled our little vessel to rise with
comparative ease to every opposing mountain-billow.

At eight o`'clock, p.m., the wind was so powerfully strong,
that it blew our new storm-jib away from the duff or bolt-rope altogether.
Every exertion was made to prevent the total loss of the sail,
but it flapped with such violence as to shake the whole frame of the vessel,
threatening destruction to all that came near it.
At length it was lowered down into the water under the lee of the ship,
and happily secured, but not without one man being hurt by it.
For lack of this sail,
it was now feared that the sea would make a constant breach over our deck;
but before another sail could be prepared to replace it,
it was truly relieving to find that the vessel bowed to the seas as they met her,
in a much more lively manner without it, than she had done with it.
Thus, in a very unexpected manner,
was a way made for us to ride triumphantly through the remainder of the terrific storm,
without any material injury to the vessel beyond the loss of part of her bulwark.
"`This poor man cried, and the Lord heard him,
and saved him out of all his troubles and to Him be the glory and the praise forever.`"
Every storm which we had witnessed previously to the last,
had been more or less accompanied by thunder and lightning, sometimes in an awful manner:
and although we left England without conducting chains; yet thus far,
not a flash has been permitted to harm us.
By way of precaution, the pumps have at times been stopped up,
to prevent their being split.
Such favours I desire to record with thankfulness,
and to number them among the many blessings,
which have descended upon us from our heavenly Parent times innumerable.

11th.--It is now more than ten weeks since we sailed from Rio de Janeiro;
we are still more than three thousand miles from our desired port,
and yet the winds have mostly blown from favourable quarters,
but often with such violence as to render them unavailing,
on account of the tremendous seas they have occasioned.
A larger vessel would have profited by many of the gales,
which have compelled us to '`lie to`' until they have moderated; when, perhaps,
a change of wind to a less favourable quarter has succeeded,
our progress has been much retarded by the old swell yet remaining.
What little we do gain seems like fetching water
from the well beside the gate of Bethlehem,
at the risk of natural life;
yet I am fully persuaded that it has been "`good for us to be here.`"

10th.--The two last days the weather has been very rugged,
but it became more gentle in the course of last night;
and some heavy showers of rain have greatly assisted in
stilling the swellings of the restless waters;
which allowed our ship`'s company to sit down together in a good degree of comfort,
it being First day.

14th.--Today we have again ventured before the wind.
In the forenoon, it being the Fifth day of the week,
Charles and myself were engaged in silent waiting.
I sat under a painful feeling of great strippedness and desertion,
which have frequently been my portion of late;
but my Lord knows best what is best for me;
and although His blessed will may not at all times suit
the creaturely desires of a poor finite mortal,
yet I think I desire to be patiently resigned,
and to be able to say in sincerity of heart, "`I have behaved and quieted myself,
as a child that is weaned of his mother;
my soul is even as a weaned child;`" humbly praying,
that at seasons an evidence may be granted that all things will work together for good,
although the blessed Comforter, who alone can relieve my soul,
may be so veiled from the view of my mind as to appear far from me.
By noon the wind and sea had so much risen,
that it became needful again to '`lie to,`' without delay.
Soon after the vessel was brought to the wind,
every indication was exhibited of another dreadful tempest being close upon us.
The interval of suspense was short before our fears were realized by
being again surrounded with all the horrors of a furious storm,
which continued through the night with unabated fury.

15th.--The wind shifted several points in the course of the gale,
causing the white crested foaming billows to run one against another in fearful heaps,
and breaking as they met in every direction,
to exhibit one vast ocean of white foam in confused agitation, not to be described.
As the principal weight of this mighty tempest was from the southward and westward,
in the neighbourhood of the pole; the wind coming off such vast bodies of ice,
brought with it most chilling cold, and heavy falls of hail or sleet,
which added much to the already accumulated sufferings of our poor, drenched,
and benumbed seamen.

16th.--After midnight the storm became less violent, and only blew a gale of wind,
which gradually diminished before day-break this morning,
and the mountainous waves having ceased from foaming, though still prodigious,
about seven o`'clock, a.m.,
we again put the head of our little bark towards the long desired Tasmania;
although but small progress could be made, from the lofty swells which remained.
During the tempest of yesterday,
it was very evident that several on board were much discouraged at its awful strength.
It was acknowledged by the captain, mate, and others,
that they had never beheld such a dreadful sea at any time before;
and yet the little Freeling was preserved
through it all with comparatively slight injury.
Such indeed have been the renewed extendings of abounding mercy,
as ought to be sufficient to cause even those of little faith to be ashamed,
and to cease any longer to doubt: but, alas! the rod once withdrawn, is soon forgotten;
as is the loving-kindness of the Lord, when the danger is passed away:
like Israel of old, we sing His praise, but soon forget His works.

17th.--The weather being more gentle the crew were assembled
twice in the course of the day for devotional purposes.
The evening was crowned with sweet peace.

At noon this day we have completed full 140° of longitude,
more than 100 of these since leaving Rio de Janeiro by the way
of the South American continent to the Cape of Good Hope;
and we have yet about 46.5° more to accomplish before entering the Derwent river,
besides several degrees of south latitude to fill up.

Ninth Month 6th.--Since the 17th ult.
to this date, the weather has been more favourable, though often boisterous.
Today strong gales and cloudy; but the sea although high,
still admits of our steering a direct course:
yesterday at noon we were about 340 miles from the southern promontory of Tasmania.
If the weather be clear tomorrow,
and the wind continue in this quarter with the same strength,
we expect to see the land once more in the afternoon.
This evening there is a rumour of land being in sight.
