== Chapter XVIII.

[.chapter-synopsis]
* Van Diemen`'s Land
* Anchor Off Hobart Town
* Meeting With James Backhouse and George W. Walker
* Aborigines
* Illness of Daniel Wheeler
* Sail for Botany Bay
* Arrival at Sydney Interview with the Governor
* Public Meeting at Sydney
* Religious Engagements

Ninth Month 7th.--After sailing rapidly with a strong breeze all night,
the land was fairly in sight at day-light this morning;
but it was too distant to be determined with certainty what particular part we saw.
Towards noon the south Cape of Van Diemen`'s Land,
with the land in the neighbourhood of Tasman`'s Head were distinguished;
but the wind had shifted almost directly against our vessel,
and a considerable swell of the sea had risen,
although in the morning these were both in our favour.
In the course of the day we had two satisfactory sittings with the crew,
it being First day.
About five o`'clock, p.m., the atmosphere assumed a very threatening appearance.
The sailors could scarcely get in the sails before it blew in a furious manner.
Our hopes, which had previously brightened at the prospect of getting into port,
were now unexpectedly blighted; and instead of a probability of this being soon realized,
we had the mortification to witness a painful reverse;
for before midnight we were literally blown off the land altogether,
and our situation rendered hazardous by the neighbourhood of rocks and shoals.
One of these rocks, from its exact position being unknown,
caused more thoughtfulness than others.
The storm lasted all night, and brought with it the swells of the Pacific;
which meeting those from the edge of the Indian Ocean,
together with the currents occasioned by New Holland, etc.,
soon raised a cross and outrageous sea.
It was thought that our vessel had not sustained more real damage
from any storm she had previously encountered during the whole voyage,
except one, which exceeded it in violence.
The sea ranged over our deck almost the whole night.
She was struck several times in different parts by heavy seas,
and part of the bulwark on the starboard side was driven on board.

Towards morning on the 9th instant, the strength of the wind was so greatly diminished,
that by eleven o`'clock, a.m., we made sail, and stretched to the northward again.
Soon after noon the small islands of Pedro Blanco and
the Eddystone were plainly ascertained;
afterward the main land appeared, and we steered at once for Tasman`'s Head,
entering Storm Bay just at nightfall.
After beating about for the next forty-eight hours with
contrary winds and great fatigue to the men,
we entered the Derwent before dark on the 10th instant,
and were at last favoured to anchor safely off Hobart Town at eleven, p.m.,
nearly opposite Mulgrave battery; and eventually moored with two anchors,
close to the garden of the Lieutenant-Governor Arthur.
Next morning I ascertained,
that our dear friends James Backhouse and George
Washington Walker were still in these parts and well.

+++[+++In a letter from Hobart Town Daniel Wheeler thus writes:]

My friends will bear with me while recapitulating the
gracious dealings of our heavenly Father,
as set forth in the extracts from my Journal.
Though many storms and tempests have been enumerated,
yet not one half of what it has been our portion to witness, has been told.
It may suffice for me to say,
that we have been compelled to seek refuge more than twenty times from the fury of
the hostile elements by '`lying to,`' with the ship`'s head to the wind and waves:
and this has been resorted to only in cases of extreme danger.

+++[+++In the same letter, he alludes to one of the sailors, who, it appears,
had been remarkably visited, and brought under feelings of deep condemnation,
and who opened his mind to him in a letter:--of this man he remarks;]
a lapse of two months had occurred from the time of his first impression,
before he divulged the secret in that letter.
I had perceived in his eye, the anguish of his wounded spirit,
but knew not the cause until he wrote to me.
He had several times been in danger of being washed overboard;
and once nearly fell from one of the yards when aloft,
but no outward danger was sufficient wholly to bring down his stubborn heart.
But the power within was too strong for him, he could not resist it;
thus verifying the assertion of the Apostle, "`greater is He that is in you,
than he that is in the world.`"
I think this circumstance cannot fail to animate the hearts of all our dear friends,
particularly such as have been instrumental in any degree,
towards promoting the great work in which we are engaged,
and cause them to feel a lively participation in that heavenly joy,
which welcomes the repenting and returning sinner to his Father`'s house.

+++[+++From a previous extract, it will be observed that Daniel Wheeler suggested,]
that certain stipulations should be made with any person who
might be engaged to take the command of the vessel;
one of these was, that himself and mate should attend morning and evening,
when the Holy Scriptures were read; this appears to have been attended to,
and the sailors also enjoyed the privilege of hearing them read at suitable times.
From a paragraph in one of his letters,
it appears that he had been careful to inform them,
that he did not consider such reading as a part of Divine worship;
but that true worship is an act between man and his great Creator,
and can only be performed acceptably in spirit and in truth.

+++[+++In a letter from Hobart Town, bearing date the 21st of Tenth Month, 1834,
the following passages occur.]


Soon after my last letters were finally closed,
our dear friends James Backhouse and George Washington Walker, returned to Hobart Town:
as we had previous information of the time they were expected to arrive,
we were at their lodgings in readiness to receive them.
They were not strangers to our being here,
as the arrival of the Henry Freeling had been publicly notified in the newspapers,
in connexion with my name, as a member of the Society of Friends.
Our joy at meeting so remote from England, I believe was mutual,
and can be more easily conceived than described;
and it has been since not a little heightened by our having
been favoured and strengthened to labour unitedly together,
for the promotion of the same great and glorious cause,
in the different meetings which have been held at this place since our arrival,
as also in opportunities of a more private nature.

On examination, after reaching this port,
it was found that several repairs were necessary, both to the upper works of the vessel,
and also to the sails and rigging,
as might be expected from the long and tempestuous voyage
which we had been favoured so safely to accomplish;
but these are not of such magnitude as to require more than some blacksmith`'s work,
and timber, in addition to our own strength, and stores.
I think we are unitedly of the opinion,
that she is as good a vessel as can be put together,
and that if she had not really been such, she never would have been here.

With a little exception,
our sailors have exceeded my most sanguine expectations
as to behaviour and conduct in general;
and I think no men could have suffered more hardships from the weather,
than they have endured.
For a time we gave them some wine,
but whether from its becoming flat and vapid by washing about in the cask,
when a quantity of it had been taken out, or with the change from cold to heat,
and then to cold again, some of them declined drinking it,
on account of its not suiting them;
so that they had nothing but water for months together.
It is a little remarkable, that, although they have been sometimes wet,
and in wet clothes, not for a day or two,
but for a week together,--when their teeth have chattered with cold,
with no warm food,--the sea having put the fires out, even below the deck;
and the water filtering through the deck on their beds below,
and not a dry garment to change;--yet not a single
instance of the cramp has occurred amongst them,
nor the slightest appearance of the scurvy,
even in those who have before-time been afflicted with it,
and still bear the marks about them: and with the solitary instance of one man,
who was forced to quit the deck for two hours during his watch, from being taken unwell,
every man and boy have stood throughout the whole voyage in a remarkable manner.
They have been plentifully supplied with fresh
provisions and vegetables since we arrived,
and with some malt liquor also; but their character for sobriety and temperance,
and general good behaviour,
has warranted every reasonable indulgence likely to conduce to their health and welfare.

My dear friends will perhaps remember,
that the Society Islands have always been the primary object before my mind;
and this originally gave rise to our making the attempt to
reach them by the way of Cape Horn as the nearest route.
And although Van Diemen`'s Land and New South Wales are
also included in the certificates granted me,
yet the Society Isles are still the object bright before me,
as the first point of destination to be aimed at.
It is expected that we shall be ready to leave this port in about a fortnight,
and as it appears that our dear friends, James Backhouse and George Washington Walker,
are now about closing their engagements in Van Diemen`'s Land,
and will be ready to proceed hence at the same time,
we therefore propose conveying them to Port Jackson; where it is my intention to call,
for the purpose of recruiting our stock of coals, oil, etc., all of which,
are extremely high in price at Hobart Town,
and may be purchased in Sydney at a reasonable rate.
As our course will be round the northern extremity of New Zealand,
we shall have but a trifling distance extra to perform,
by hauling in for the coast of New Holland.

+++[+++Soon after the foregoing was written, Daniel Wheeler was taken so seriously ill,
with a complaint which settled on his lungs, that his recovery seemed doubtful;
he remarks:]
For a time it almost seemed as if I had come to
Van Diemen`'s Land to lay down my head there;
but in this prospect, resignation to whatever should be the will of my heavenly Father,
was the stay and comfort of my mind; bearing it up above the bondage of fear,
even to a degree of rejoicing in humble trust
and confidence in the inconceivable love of Him,
who "`came not to call the righteous,
but sinners to repentance;`" permitting them to know and
sensibly to feel the riches of that universal heavenly grace,
which triumphs over all the depravity of human nature,
where its operations are submitted to; begetting a faith,
that can remove every mountain of sin and opposition,
and can give the victory over death, hell, and the grave,
to all who believe in its powerful and saving efficacy: who "`live not unto themselves,
but unto Him who died for them and rose again;`" and "`because He lives,
they live also,`" through the mercy of God, in their crucified and glorified Redeemer.

The season was particularly late and cold;
deep snow was lying upon the mountains in sight;
and cold rains almost daily falling in torrents,
rendered the streets and roads in the town nearly impassable,
excepting a few of the principal thoroughfares that are macadamized.
No regularly formed footpaths are yet established in any part of the colony;
so that getting about on foot was almost impracticable for invalids,
even in an advanced stage of convalescence.
But although our intentions have been thus frustrated, yet I am persuaded,
that all things which have hitherto been permitted, have been mercifully dispensed,
and have worked, and will continue to work together, for good;
and that the lengthened continuance of cold winterly weather has been best for us,
and will serve the more effectually to brace us,
and prepare our constitutions for the relaxing and constant
heat that we shall meet with amongst the Society Islands.
Besides the advantages which have been thus derived, I am firm in the belief,
that our protracted stay in this neighbourhood will ultimately
be found to have been in the ordering of Divine wisdom;
however apparently at the moment impeding the great object before me,
which it has been my earnest and anxious solicitude to accomplish
while the earthly tabernacle retains a good degree of strength.
By this detention an opportunity was afforded
for a complete and satisfactory arrangement,
not only of our own affairs,
but of those of our dear friends James Backhouse and George Washington Walker.
The arrival of a ship in this interim, brought out for them a variety of books, tracts,
etc.; these were much needed for distribution in Van Diemen`'s Land;
so that it seemed to crown all their labours, and enable them to depart in peace.

During this time we were present at two conferences
with members of the Wesleyan connexion;
at the latter of these, most, if not all, of their preachers were collected.
Some time back the Wesleyans were very favourable to our
friends James Backhouse and George Washington Walker,
and disposed to render them every assistance in their power; supposing,
although they were walking among men under a different name from themselves,
that still in Christian doctrine they were nearly agreed,
or that the difference was so trifling, as to be unimportant.
But finding that of late some of their members
have become convinced of Friends`' principles,
a marked shyness has begun to show itself; and several attempts have been made to prove,
that the principles which we profess, are not fully supported by Scripture authority.
The perceptible guidance of the Spirit, it seems, they cannot believe in,
notwithstanding they profess to be continually under
its influence in all their religious proceedings:
we cannot therefore wonder,
that our mode of worship and silent waiting upon Almighty God,
are disapproved of and incomprehensible to them.
These conferences have served to show,
that there is a much wider difference between them and us,
than they had previously supposed.
However we may be disposed to cherish Christian charity
one towards another as religious professors,
yet I am fully persuaded,
that whenever the principles of our religious Society are thoroughly understood,
they will always be found striking at the root of a tree,
upon which most other denominations are feeding; and this must and will be the case,
so long as the preachers and teachers of the people are
paid for the performance of their offices,
and are trained up for them.
I am far from asserting, that there are not individuals of other societies,
who are truly called to the work of preaching the gospel,
and who are labouring in the noble cause from pure and disinterested motives;
but I do fear that the number of these is comparatively small: and it is my belief,
that if no money was permitted to circulate in connexion with
the outward performance of any religious service,
the religion of Jesus would soon shake off the
defilements with which it has been sullied,
and again shine forth in primitive purity and lustre, "`clear as the sun,
fair as the moon, and terrible`" to sin and iniquity, "`as an army with banners.`"
O! that men would come to that true teaching of the heavenly anointing within them,
which would abide in them and teach them all things;
and which is Truth itself and no lie.
Then would they be sensible, that they needed no man to teach them;
for the teachings of man would be to them as that water, of which "`whoever drinks,
shall thirst again`" but when they have tasted of the
water given them by the Prince of life Himself,
which should be in them "`a well of water springing up
unto everlasting life,`"--"`whosoever drinks of this,
shall never thirst.`"

+++[+++After making several visits to take leave of their friends, previous to their departure,
in company with James Backhouse and George Washington Walker,
they weighed anchor in the evening of the 11th of Twelfth Month;
having previously had a parting opportunity in the family of the lieutenant-Governor,
George Arthur, who uniformly treated them with kindness and hospitality.
They had however, no sooner left the quiet moorings of the Derwent river,
than they had to encounter the buffetings of the stormy main.
This was more or less the case, during the whole passage from the Derwent to Port Jackson.
In the night of the 19th,
they were in considerable danger of being driven
amongst the rocks by some unknown current;
but were favoured to discover and escape the danger in time, although the night was dark,
and much rain falling.
Daniel Wheeler adds, although the danger which threatened, was evident and imminent,
yet our little company were preserved in quietness, and divested of fear.
At eleven o`'clock, next day, the 20th,
they saw the light-house and signal-staff on the South Head,
which forms one side of the entrance of Port Jackson.]


A timely signal having been made, we got a pilot on board on nearing the reef,
and immediately worked up the bay towards the harbour.
At two o`'clock p.m., we were favoured safely to anchor in Sydney Cove,
at a convenient distance from the shore; before anchoring, the mail,
with which we had been entrusted from Van Diemen`'s Land,
was duly conveyed to the post-office at Sydney.

+++[+++They met with a cordial reception there,
not only from persons to whom they had letters of recommendation,
but from many others also; marks of respect, kindness,
and hospitality were also shown them by the Governor and local authorities.
Meetings for worship, on First and Fifth days,
were regularly held on board the vessel during their stay,
which several persons usually attended.

+++[+++The deplorable situation of some of the aboriginal inhabitants, is thus described:]

Twelfth Month, 23rd.--After dinner, we landed on an uninhabited part of the coast,
on the north side of the harbour, to obtain sufficient exercise;
and accidentally met with an aboriginal family, consisting of two females,
one of them far advanced in years, and three children,
the offspring of the younger woman.
There were two men not far off, who belonged to them, but they kept aloof.
These women appeared to be in a poor state of health, and exceedingly shrunk:
they could talk a little English, and on our making them some trifling presents,
and saying that some of us would see them again, if they should be there tomorrow,
one of them said, '`You welcome;
come.`' It was affecting to behold the degraded condition of these natives of the soil.
The state of these poor creatures has been rendered abundantly more miserable,
since the English have taken possession of their country,
from the introduction of vices to which they were before strangers,
particularly the use of spirituous liquors.

24th.--We sent some biscuit to the native family on the north side of the bay,
by the mate and my son Charles;
who saw two other families of these people in the course of their excursion.
Their debased condition is greater than can well be conceived,
and such as to render every attempt to assist them fruitless: if money be handed to them,
it is immediately exchanged for rum; or if clothes,
they are immediately sold or exchanged for whatever will procure strong drink:
such is the curse entailed upon them since their acquaintance with the British;
who are doubtless chargeable, not only on this score,
but for much of the demoralization and degradation of these harmless people.
While dining on shore today, we had both windows and doors open;
such is the heat prevailing on this side of the globe,
on what is commonly called Christmas eve.

26th.--This morning we received a visit from William Pascoe Crook,
one of the missionaries that first went to Tahiti, in the ship Duff, many years ago.
The letters he had very recently received from the Society Islands,
enabled him to communicate much interesting intelligence,
some of which was of an encouraging nature,
although many mournful facts were at the same time related.

In the evening we went on shore for exercise.
On returning towards the boat,
we were abruptly thanked by a negro for what we had done for their colour.
At first we did not understand what he meant,
but soon found he was alluding to the exertions
of our Society for the abolition of slavery.
He had come from the Mauritius, on his way home to Jamaica,
and was waiting for a ship bound for Europe or America, in order to get there.
Although the abolition of slavery could never have been effected,
but through Divine interposition,
yet it was pleasant to find that any of the instruments employed in the work,
were remembered with sensations of gratitude.

27th.--We called upon the Colonial Secretary, who accompanied us to the government house.
We were kindly received by the Governor, Sir Richard Bourke; who,
being informed that James Backhouse was desirous to
visit the penal settlement upon Norfolk Island,
readily gave his consent; at the same time saying,
that no person was ordinarily allowed to go there,
but under present circumstances there would be no objection.
He lamented the low state of religion and morality upon that island.
The account of the prisoners there, as furnished by Dr. Marshall,
of the Alligator sloop of war, is truly affecting.
About one thousand persons reside upon the island.
When I first understood that it was the intention of our dear friend James Backhouse,
to pay an early visit to the settlement upon that island,
I shrunk at the thought of going there; a feeling which was, I believe,
induced principally by the desire of hastening to Tahiti,
without any further sacrifice of time.
But, as the subject dwelt with weight upon my mind, and as I abode under it,
without consulting any one, I had a clear and lively impression,
that if I gave up to conveying our dear friends James
Backhouse and George Washington Walker to Norfolk Island,
at this time, it might be the means of preventing my having to go there at a future day;
not doubting that my beloved Friends in England would unite in this measure,
when all the circumstances of the case were considered.
The Governor was therefore informed,
that I proposed to convey them in the Henry Freeling;
but not until he had made the inquiry how they were to get there,
as no vessels are allowed to touch at that island,
except those belonging to the government, which are but few in number,
and seldom go there, and none of them were about to sail at the present juncture.
It is therefore presumed, that ample time will be afforded to our friends,
if conveyed there by the Henry Freeling,
to perform what service may be called for at their hands,
and be ready to return to New South Wales by the first
government vessel which may arrive after their landing;
or it may be, by the second, as duty may demand, or longer tarriance become needful.
Before leaving the Governor,
we had an assurance that proper documents and private
signals should be furnished by the Colonial Office,
to enable us to approach Norfolk Island without difficulty.
An allowance of the usual rations for the subsistence of our
friends during their residence at that settlement,
was also mentioned.
Since I have given up to convey our friends to Norfolk Island,
my mind has been peaceful and easy, and the way has opened with clearness;
a circumstance at once consoling and confirming.
This island is no great distance out of our regular course to Tahiti,
and bears from hence about east and by north half-north,
distant less than one thousand miles.

30th.--At noon we received a visit from Samuel C. Marsden,
who has been connected with this colony, in and out, more than forty years,
as a Church missionary.
He has been six times in New Zealand,
and speaks highly in favour of its enterprising inhabitants,
with whom he has so frequently resided in peace and safety, and amongst whom,
he would have no fear whatever of dwelling again, if occasion required it.
His great experience in these parts, the plainness and simplicity of his manners,
and the abundant store of authentic information he possesses,
made his company not only edifying but animating.^
footnote:[This devoted servant of Christ is since deceased;
he died on the 12th of the Fifth Month, 1838.]

+++[+++During their stay, they had several visits from this interesting individual,
as also from some other pious characters,
several of whom were occupying prominent stations in different religious societies.]

First Month 3rd, 1835.--Today a hot wind prevailed, which is common in this country,
but almost insupportable.
The thermometer in the cabin standing at 90°, but on shore at 100°, in the shade.
A sudden change took place before two p.m., commencing with a tremendous squall of wind:
the great heat was at once turned into cold.
It is this peculiarity of climate which renders
inflammatory complaints so frequent and fatal here,
affecting the aborigines as well as strangers.

7th.--Having at times for the last two or three days,
felt my mind drawn towards holding a public meeting with the inhabitants of Sydney,
and dear James Backhouse unexpectedly inquiring whether
I had thought any thing of such a meeting,
I felt a willingness to unite with him, in the freedom of the gospel, to appoint one,
and to take the necessary steps to procure a suitable place to hold it in.
The old Court-house was obtained, and the meeting was held in the evening of the 11th;
which appears to have been a satisfactory and relieving opportunity.
Notwithstanding another meeting was to be held under the same roof at seven o`'clock,
appointed by a Baptist preacher,
yet we had the satisfaction to witness a crowded attendance at ours,
of nearly five hundred persons; and many that could not be seated, went away altogether,
but a large number stood the whole time;
perhaps from the novelty of its being the first meeting
of Friends for public worship held at Sydney,
and we hope, on the part of many from a desire to be benefited,
the room was presently filled:
several present were persons who held public stations in the town and neighbourhood.
It was upon the whole, from beginning to end, a solid opportunity:
James Backhouse and myself were largely opened in testimony amongst them:
James Backhouse appeared a second time, and concluded the meeting in prayer.
From the quietness and solemnity which reigned throughout the whole time of the meeting,
it might have been supposed that the congregation consisted
wholly of persons accustomed to stillness and silence,
instead of an audience,
of which scarcely an individual had ever before been present at a Friends`' meeting,
or was even aware of the manner in which they are
usually conducted:--but the glory was and is the Lord`'s.

+++[+++The following Third day, the 13th, James Backhouse and himself, by invitation,
paid a visit to the Governor at his house at Paramatta,
on which he remarks:]--However humiliating such visits may be to myself,
they may have a tendency to promote the great work,
and open the way in the minds of those in power, to contribute to its furtherance;
and this brings into a willingness to be held up as a
spectacle before men for the great Name`'s sake.
But on such occasions, great circumspection and watchfulness are increasingly needful,
lest any of our testimonies should be let fall or compromised,
and the enemy have to exult in the loss we sustain.
+++[+++Daniel Wheeler adds:]--It was ascertained, while on this visit,
that it is in contemplation to build a large
hospital for insane persons in the neighbourhood,
which afforded an opportunity for James Backhouse to furnish
the Governor with Samuel Tuke`'s Account of the Retreat,
and with his pamphlet, entitled Practical Hints;
both these contain important information,
highly needful for those who are about to establish such an institution.

First Month 21st.--I have found the advantage of placing our sailors,
upon rather a different and more respectable footing than those of other ships;
and the result has been, so far, that we have had comparatively no trouble with them.
It is so common a thing for the shipping to lose their men here, that a few days ago,
the question was put to me by General Bourke, the Governor,
'`Have you lost any of your men?`' and it is satisfactory to know,
that some of the strangers who have attended our meetings on board, have,
in more than one instance remarked,
(as if of rare occurrence,) that our sailors look more like healthy, fresh-faced farmers,
than men come off a long voyage: the generality of those we see daily,
have a thin and worn-down appearance,
particularly when they belong to ships that supply them daily with ardent spirits;
our sailors have each a quart of beer per day, of weak quality, being brewed,
as is customary here, with only sugar and hops, both of which are very cheap.
I found it advisable to keep up a desire in the crew,
to make themselves acquainted with the art of navigation;
and this could not be done without their being
furnished with materials for its accomplishment,
such as quadrants, slates, pens, paper, etc.;
and though the expense of such things ultimately devolves upon themselves, yet,
at the moment of purchase, the advance of money has been unavoidable on my part.

23rd.--Captain Saunders, who commanded the Science,
when she brought out our friends James Backhouse and George Washington Walker,
came on board.
He related to us the extraordinary escape from
shipwreck he had experienced off Cape Horn,
on his return from that voyage;
when the Science by one stroke of a heavy sea was dismasted,
and turned nearly bottom uppermost.
The mate and part of the crew were washed overboard at the same time,
and never seen again.
Captain Saunders and his companions continued on board
the vessel in this situation for six days and nights,
when the floating hull was observed, and taken for a whale,
by one of the South Sea whalers,
which ultimately was the means of rescuing them from
being wrecked on a barren and inhospitable coast,
from which they were only about two days drift when discovered.
The everlasting Arm was signally displayed on this occasion,
as they were so near the coast,
as to be quite out of the usual track of every description of vessel;
and yet one was actually brought near enough to descry the hull,
and save their helpless crew, though at considerable risk to themselves.

First Month 27th.--For the last three or four
days I have been in a low and stripped situation;
and while anxious to be getting on our way towards the islands,
I could not come to any decision and clearness
sufficient to enable me to fix the time for our sailing.
This morning,
dear James Backhouse asked me if I had felt any thing as to
another public meeting with the inhabitants of Sydney.
+++[+++This subject occupied their close and serious consideration,
and they unitedly agreed that one should be appointed
to be held the following First day evening,
as the most suitable time, and that extensive notice should be given thereof.
Daniel Wheeler adds:]
I felt relieved, and willing to take a share with him in that exercise of mind; which,
with me, at all times, precedes a prospect of such magnitude and importance.

+++[+++The old Court-house was again procured,
and the meeting held on the evening of the following First-day, the 1st of Second Month,
which was as numerously attended as the former one, and proved a relieving opportunity.]

Second Month 4th. (Fourth day.)--As James Backhouse has
for a day or two been under no small concern of mind,
from an apprehension that an attempt must be made to
collect the sailors of the fleet now in Sydney,
at this time very considerable; and as this is not likely to be accomplished,
but on a First day;
there seems now no probability of our proceeding
towards Norfolk Island during the present week.
The crews of the ships had not wholly escaped the notice of my mind,
for several days previous to James Backhouse mentioning the subject to me;
but not in any manner as of pressing obligation towards seeking a
religious opportunity with this class of the people exclusively,
but yet sufficient to raise a feeling of unity with him in the engagement.
Upon inquiry,
it seemed to be the general opinion that meetings were mostly
best attended by sailors when held on board of ship;
application was thereupon made to Captain John Hart, of the ship Henry Porcher,
who readily granted the use of that vessel`'s deck for the intended purpose,
in the forenoon of the following First day.
+++[+++The meeting was held accordingly on the 8th, and was attended by about 130 persons,
and is thus described:]
James Backhouse was largely engaged both in testimony and supplication.
It was my lot to keep silence,
although I could spiritually unite in the labours of the day,
under a sense of the states of some in particular, of those by whom we were surrounded.
After the meeting, a large number of Friends`' tracts,
and those of the Temperance Society, were distributed,
and received with eagerness as the company returned to their boats.
