== Chapter XX.

[.chapter-synopsis]
* Tahiti Visit of Chiefs
* The Young King
* Meeting for Sailors
* Distribution of Tracts, Bibles, etc. Temperance Ships
* Introduction of Ardent Spirits
* Visit to the Schools
* Attend the Native Meeting Visitors on Board
* John Davies
* Meeting on Board
* Importance of Translating and Circulating the Scriptures
* Tahitian Council--Native Meeting

Tahiti, 14th of Fifth Month 1835.--This morning, Tatiand his brother,
two of the principal chiefs, and truly great in stature,
with a grand-daughter of the former, came on board at breakfast time,
bringing with them another person of note.
They partook of our meal, and stayed over our usual reading in the Scriptures;
during which, and in the time of silence, they behaved in a solid manner.
These are the most elderly chiefs that we have seen,
and perhaps the oldest upon the island;
and they are said to be the principal support of the present government.
They had been on board once before,
but it being late in the evening they had not stayed long.
I put a small cotton dress upon the child, and presented a shawl to each of the great men.
They invited us to come with the vessel to Mairi Pehe, where they reside,
and on leaving seemed well satisfied with their visit.
It being Fifth-day, Charles and myself endeavoured to wait upon the Lord,
but under feelings oppressively languid from the heat.

15th.--My mind having for some days past been brought into thoughtful solicitude
for the best welfare of the crews of the vessels now lying at anchor about us,
I mentioned it to my Charles soon after rising this morning;
and seeing no way of being clear of the blood of these poor neglected people,
but by appointing a public meeting, to be held next First-day,
it was concluded to make the necessary arrangements for so doing.
There was no doubt that the deck of one of the whaling
vessels might have been procured for the purpose;
but on considering the subject,
it seemed best to have the deck of the Henry Freeling made use of,
lest umbrage should be taken by the English sailors,
if the meeting was held on board an American vessel; or by the American sailors,
if held on board an English one, in the same calling;
both parties considering our own as employed on
very different grounds from any other in the bay.
There were six American whalers, and one trading vessel, all large and well manned,
in the bay; and only one English whaler, the Rover, of London.

I stepped on shore to inquire whether the eleventh hour, next First-day,
would interfere with any arrangements the missionaries might have made;
that the work of neither party might be marred,
and that nothing on our part might appear as done in a corner.
On learning at George Pritchard`'s,
that nothing would clash if our meeting was held at that hour,
and having invited him or any part of his family to attend it,
we returned immediately on board,
and were soon after visited by a serious and respectable person,
who had been sent out in 1825,
by the London Missionary Society to teach the natives the art of spinning and weaving.

The young king and his brother came on board in a private capacity:
their visit was much more agreeable than when
attended by several of the principal chiefs.
They stayed dinner, and remained on board several hours.
The simple habits, and gentle unassuming manner of this young man,
do not appear at present to be liable to alter
from his having become the husband of the queen.
The amiable disposition he possesses, and which cannot be concealed,
at once renders him an object of general esteem.
He has evidently acquired considerable polish from the interaction with foreigners,
of which he does not fail to avail himself at every opportunity;
and although from this circumstance,
his manners are much more civilized than those of his countrymen,
yet now and then the wild nature of a South Sea Islander shows itself.
They brought us some fine bunches of oranges,
the largest of which contained eleven in a cluster, and the smallest seven.
A sliding knife and fork were presented to each, also a three-bladed knife and a penknife.
Shortly after these guests had left us, Paofai a chief, residing near Point Venus,
came on board, and made signs that he wished to read my certificates,
which were accordingly furnished for his perusal in the Polynesian language,
although he could speak more English than any we have yet met with.
He is considered a great man,
and was more modest in behaviour than any we have yet seen of his stamp.
Having observed, while he read the certificate, that his sight was impaired,
I presented him with a pair of spectacles;
at the same time a pocket-handkerchief and a small hatchet were given him;
upon which he said he had no money to pay for them.
Such an honest confession we had not before met with,
nor with any person who mentioned payment for what they received.
He left us with an acknowledgment of the kindness with which he had been treated,
and I believe both parties were satisfied with the interview.
In the evening, we were engaged in writing notices of the public meeting,
intended to be held next First day.

16th.--After breakfast,
my Charles went to distribute the written notices amongst the shipping.
In the forenoon, a quantity of tracts were selected,
and parcelled in readiness for distribution at the close of the meeting tomorrow.

17th. (First day.)--In the morning the prospect before us was rather gloomy.
There had been rain in the night,
and soon after daylight the Mariner whaling vessel put to sea;
thus the seamen on board of her were prevented from attending the meeting:
but I thought there was no reason why they
should be deprived of their share of the tracts,
which had been got ready for distribution the day before.
As the wind was light,
there was no difficulty in overtaking her before she got outside of the reef.
Our mate was accordingly dispatched in good time, and succeeded in handing them on board.
They were received with civility, and the requested application of them promised.
By the accommodation of some planks kindly provided by the Emerald,
our decks were extensively seated, and the planks were well covered with canvass,
spare flags, etc.

At half-past ten o`'clock, a bethel-flag, with which we have been furnished, was hoisted,
as a thing understood by all sailors, and a little in their own way:
this allowed half-an-hour for the boats to collect from each ship,
in order that the time appointed (eleven o`'clock,) might be kept to,
and the quiet of the meeting preserved from late comers on board.
Although the invitation, with the exception of George Pritchard`'s family,
had not been extended by us beyond the shipping in the bay,
several persons attended from the shore;--Doctor Vaughan, Captain Henry, George Bicknell,
and some other white people with children,
whose copper-coloured skins indicated that they were the offspring of Tahitian mothers.
The meeting at length settled down into stillness beyond our expectation.
I thought there would scarcely be a single individual then present, except our own crew,
that had ever before been at a meeting held exclusively after the manner of Friends.
In this, however, I found I had been mistaken,
as the mate of the Lancaster came on board the next day,
and acknowledged he was a member of our Society, though, as he stated,
he had not kept close to it.
He told us, that he little expected to see a Friends`' meeting held amongst these islands;
but seemed glad of having an opportunity to attend one.

However long the time of silence might be thought,
there was no restlessness sufficient to disturb the quiet of the meeting.
Unexpectedly to myself, I felt an engagement of mind to state to the meeting,
that the religious Society of which I was a member, had, from its earliest rise,
been called upon to bear a faithful testimony to the
excellency of silent worship and waiting upon God:
that it was a noble testimony to the all-sufficiency and teaching of that grace,
which had appeared unto all men,--teaching all,
and bringing salvation to all;--"`for the grace of God that brings salvation,
has appeared unto all men, etc.,
looking for that blessed hope and the glorious
appearing of the great God and our Saviour,
Jesus Christ,`" etc., to the end of the text.
"`For God is a Spirit: and they that worship him,
must worship him inspirit and in truth:`" and we are told in holy writ, by the Son,
that "`the Father seeks such to worship him.`"
I was then carried forth on the nature of true, silent, and spiritual worship,
to a considerable length; and had to state,
that my head would not have laid easy upon the pillow at a future day,
if the attempt had not been made to collect the seamen of the
fleet:--that sailors were a class of men more than most others,
separated from their homes and regular places of worship,
particularly on these long voyages upon the mighty deep, for months and months together;
but that the ample provision made by the glorious
gospel for the restoration and redemption of mankind,
boundless as its love, extended unto all: for He that said, "`Let there be light,
and there was light`" even "`God, who commanded the light to shine out of darkness,
has shined in our hearts, to give the light of the knowledge of the glory of God,
in the face of Jesus Christ.`"
I had largely to proclaim some of the principal doctrines of the gospel,
and was helped through, to my humble and thankful admiration.
It was indeed a glorious, and I trust to some, a blessed meeting.
I had, I think,
more than once to call their attention to the heavenly
power that reigned over us with precious solemnity,
as a crown and diadem: and before the meeting closed,
I had to acknowledge the same with prayer and thanksgiving,
to the glory and the praise of my God.
After the meeting was broken up,
I requested an individual out of each ship to step forward,
when two hundred and twenty-nine tracts, principally those of Friends, were disposed of,
including those sent on board the Mariner in the morning.

19th.--The Nassau sailed early this morning for the coast of California,
to prosecute the whale fishing.
The captain was furnished with six Bibles and six Testaments,
in the Spanish language. He said there would be no
difficulty in putting them into suitable hands,
he being well acquainted with those parts.

20th.--The American ship Emerald,
being about to sail for Manilla and the Phillipine Islands,
and Captain Eaglestone having kindly offered, on application being made,
to forward our views, in circulating the Scriptures in the Spanish language,
he being on a trading voyage, and of extensive acquaintance,
this morning eighteen Bibles, eighteen Testaments,
eighteen Letter by +++________+++ on Christianity,
with five copies of Wilberforce`'s Practical View,
were got ready and delivered to that ship.
We have met with great civility and willingness to lend
a helping hand in many of the American captains:
at the same time, we are frequently sensible of a mixture which cannot be reconciled.
The foregoing remark has no allusion to the inconsistent
conduct of the crews of many of the American vessels,
which we have fallen in with here,
that are called "`temperance ships.`"
At first I could not but view these with satisfaction,
and with a degree of thankfulness,
as likely to contribute by their example to the welfare of the islanders.
But, alas!
I now find, with horror and surprise,
that the word "`temperance`" applies only to the ships, and not to their crews,
none probably of which are members of a Temperance Society;
they are merely bound by articles,
that the voyage shall be performed without any spirits being on board,
except as medicine, and their sobriety only exists because they cannot get the liquor;
when on shore, and unbound by these articles, they are lamentably, in many instances,
notorious for drinking to excess; and their immoral conduct, at this place,
makes me shudder for the awful and woeful consequences, both as regards themselves,
and the daughters of Tahiti.
Although great exertion is made and promoted by the missionaries here
to stop this overwhelming torrent of iniquity,
yet all their measures are abortive, and can never be successful,
unless co-operated with on the part of the masters of the shipping.
Notwithstanding the disuse of spirituous liquors is rigidly enforced at Tahiti,
and no person is allowed to have the article in his house;
yet this bane of the human race is still to be purchased on shore,
and the supply is kept up by the American ships;
it is clandestinely landed amongst the supposed
empty casks which are sent on shore for water,
(an instance of this kind took place a few days ago,) and by other methods.
A considerable quantity was brought in last week by an American schooner from Valparaiso,
and safely landed; but has since been discovered,
the casks destroyed and their contents totally lost.
By what is said,
I do not mean to imply that this gross immorality is
confined solely to the crews of the American vessels,
because those of the English are perhaps equally implicated, but with this difference,
they do not assume the character of "`temperance ships.`"

How dreadful and appalling the consideration,
that the interaction of distant nations should have entailed upon these poor,
untutored islanders, a curse unprecedented and unheard of in the annals of history;
it is said that one-fourth of the whole population is
miserably affected with disease brought amongst them,
and kept up by the licentious crews of the shipping.
Will not, shall not the Lord visit for these things?

22nd.--The American schooner Peruvian, came in before noon from Valparaiso, with horses.
In the afternoon, went on shore upon the Queen`'s Island.
On this small spot of ground much is concentrated: a small chapel,
with sides of upright bamboos, (wicker-work,) is standing, with seats and a pulpit,
at one time probably in use: there were also several pieces of cannon in a useless state,
one placed on a platform, formed of loose stones and coral,
and others lying about in a condition equally harmless.
These have been left as presents by the ships of different nations,
which have visited these seas, and stand as memorials against them,
by showing that their dependence is upon the arm of flesh for protection: England,
France and Russia seem to have been the donors of them.
Part of one building is fitted up as an armoury,
with an inscription to this import over the arms,
which consist of three worthless muskets without locks.
We cannot wonder at young and barbarous nations being
eager to possess weapons of a destructive nature,
when they see in what high estimation they are held by those who are called Christians;
but, alas! their conduct proclaims aloud,
that such are not the followers of the Prince of peace,
nor are living under the blessed influence of the gospel.

[.offset]
+++[+++About this time,
the following interesting letter was written by Daniel Wheeler to John Wilbur,
an American minister in the Society of Friends:^
footnote:[This letter of Daniel Wheeler was taken from
the Journal of the Life of John Wilbur,
and included in this memoir by The Friends Library.]]

[.letter-heading]
To John Wilbur

[.signed-section-context-open]
From the Henry Freeling--Papieta Bay, Island of Otaheite, 5th mo. 21st, 1835.

[.salutation]
My Dear Friend John Wilbur,

Although much time has elapsed since we saw each other at Norwich in England,
and though many have been the turnings and overturnings
of my heavenly Lord and Master`'s hand since that day,
yet at seasons I have never ceased to remember you, in the fresh aboundings of that love,
the precious influence of which, binds together in one,
the disciples of the one crucified, risen and glorified Lord,
however distant from each other their lot may be cast.
You may probably have heard something,
(though I doubt it as I write,) of the fight of
affliction and distress which I had to endure,
within the borders of my own beloved family,
which deprived me of the beloved partner of all my joys and sorrows,
and a faithful sharer in them for more than thirty-two and a half years.
What my Master did, I knew not at the time, but have since known,
to the comfort and consolation of my tribulated mind,
and to the praise and glory of his grace.
"`What I do, you know not now, but you shall know hereafter.`"
And persuaded I am, renewedly, that every dispensation of his holy will towards me,
was only to prepare me for the great work in which I am now engaged;
and to set the captive spirit more and more free from every earthly care,
and to wean it from the near and dear social tie,
and render it more fit to be employed in the highest, greatest,
and most noble calling upon earth, even in a cause, dignified with immortality,
and crowned with eternal life.

In addition to this heavy trial, which took me back across the continent of Europe,
a winter`'s journey, twenty-eight days in length,
once more to behold the wreck of my precious family, and regulate their affairs,
for their future well-being, the messengers of Satan,
(for they were many) were let loose to buffet me.
After the vessel "`Henry Freeling,`" from which I now address you, was fitted out,
we sailed from London on the thirteenth of eleventh mo., 1833,
and joined her a few miles below Gravesend;
and eventually proceeded from there to Portsmouth,
in the neighborhood of which we were detained more than four months,
by strong adverse gales, and other circumstances,
but all tending eventually to promote the great object in view; and I fully believe,
"`working together for good.`"
During this long detention, in the winter months, our little bark,
of about one hundred tons only, was often tempest-tossed without,
and some on board often tempest-tossed within.

After having been here about a month, my mind was sorely exercised,
and there was but one way for me to throw it off, to my relief;
and this was by making an open avowal, that I was not satisfied to proceed any further,
let the consequences be what they might,
with the Friend appointed by the "`Meeting for Sufferings`" in London,
as an assistant--or by some termed a companion, but not by myself.
This circumstance seemed to raise a "`hue and cry`"--or something like it,
against me in almost every part of England; and at length,
drew down a committee appointed by the "`Meeting
for Sufferings`" to visit me at Portsmouth,
namely: Peter Bedford, George Stacey, Josiah Yorster of Tottenham, and Samuel Gurney;
bringing with them the final determination of a Meeting
for Sufferings specially convened on the occasion,
which was--that I should be left at liberty to proceed on the
voyage without any further companion than my son Charles,
(about twenty-four years of age,) who believed
it his duty to resign his situation in Russia,
(all the living that he had,) and surrender himself to the Divine disposal,
by making the offer of going with me,
and of making himself useful in any way that might present,
if approved by Friends in London; and this was accepted by the generality of Friends,
as far as I know; but the conduct of Daniel Wheeler in this business was considered,
from north to south, to be highly reprehensible,
if not shameful,--to use the said Friend in the manner I had done.
They wanted a reason, and I could give them none;
but that I had acted under a sense of duty.
This could not be reconciled.
It was not understood by those who never heard the Master`'s voice, at any time,
or saw his shape; and I fear it may be said, believe not in him.
Of this description I am aware you are not ignorant;
there are not a few in our Society in England.
I think they cannot be better pointed out than by my saying,
they were such as highly disapprove of "`John Wilbur`'s
Letters,`" published by George Crosfield,
of which I am thankful, in having several copies now along with me.

But what puzzled these people most of all,
was that the Friend and myself parted in brotherly love.
There had at no time been any difference existing between us,
and I quite thought that he had been right in making the offer, at the outset,
inasmuch as he had promoted my being set at liberty by the "`Meeting for Sufferings,`"
which would not have been the case if another Friend had not offered himself,
as neither the outfit nor the purchase of the vessel would have been entered into,
until one had showed himself.
When we separated at Portsmouth, he gave me as handsome a clearance in writing,
as I could desire, or wish for; and in a letter to the Monthly Meeting at Balby,
(near Doncaster,) to which we both belong as members,
I had also given him full satisfaction, and the meeting too,
as well as the "`Meeting for Sufferings,`" which had been furnished, by myself,
with a copy of the said letter.
Moreover, when sifted by some friends who wanted to get information from him, he,
in the same noble manner, declared that if he had it to do again,
he would still do the same; but even this could not satisfy.
I received letter after letter reproaching me for my conduct,
and declaring that my going had not their unity;
and one Friend did not hesitate to express his belief
that the Divine presence was withdrawn from me,
that I was left to myself,
and that the detention and other circumstances combined to declare it.

At one time I concluded to return to London, and meet these enemies face to face,
but something continually occurred to prevent my taking this step, when ready to set out.
Some of my true friends approved of it, and others dreaded the result.
I was, however, favored to see through this snare of the enemy,
for I fully believe if I had gone again to London,
the voyage would have been set aside altogether;
as I am satisfied that it would have caused a complete
exposure of the principles of many among us,
and a complete explosion also;
and I was not desirous to shrink from going on this account,
but the language in my mind was, "`Let the dead bury their dead--but you go!`"
I believe many Friends could see the divine Hand in all this,
as it occasioned my writing many letters, in support, I humbly trust,
of the Truth as it is in Jesus.
The detention also afforded time for our captain`'s character to be fully developed,
and another to be appointed in his place.
It was thought afterwards by many, and particularly by myself,
that we had not been detained one day too long.
I must pass over all particulars of the voyage; however,
on leaving the neighborhood of Portsmouth,
we reached our anchorage in the harbor of Rio de Janeiro in
Brazil,--without making a single tack,--a thing,
perhaps, never done before by any vessel.

Farewell, my very dear friend.
My dear love awaits you and yours, and all those that in sincerity love the Lord Jesus,
in which my Charles would gladly join, and believe me your affectionate friend,

[.signed-section-signature]
Daniel Wheeler

23rd.--The king came on board to breakfast this morning by himself,
but departed as soon as our reading was over.
As attending the Tahitian worship has been frequently
the companion of my thoughts for several days past,
it seemed best for me to be in readiness by
having the way opened for the ensuing First day,
(tomorrow,) should this be my portion.
After communicating this to my son Charles, we concluded to go on shore,
and mention the subject to George Pritchard.
On seeing the latter,
I told him that my mind had been drawn to attend the Tahitian worship tomorrow morning.
He asked, if I meant to perform service there, or to sit as a spectator.
"`To sit as a spectator,`" I replied,
"`but if required to speak, to have permission to do so.`"
He then said,
"`You must not expect to find things in the same order as if you were at home,`"
and added, "`If you could come on shore about half-past eight o`'clock in the morning,
there would be time to look at the schools before the meeting begins:
the meeting for worship begins at nine o`'clock,
but a prayer-meeting commences at sun-rise.`" I cannot but admire,
with reverential gratitude and thankfulness,
how in every instance of this kind that has yet occurred,
mountains have become mole-hills, as a willingness has been wrought to approach them:
and if it were not fixing a very high stamp upon ourselves, I should say,
surely the blessed Master,
in like manner as when He sent forth His disciples two and two
formerly to every place where He intended to come,
is already not only come, but has condescended to go before,
and prepare the way for us poor creatures in a remarkable manner,
in the hearts of others with whom we have to do.
In returning we walked along the edge of the bay, and were accosted by a respectable,
clean-looking white man, who has resided here about fifteen years.
He had been a sailor,
but a severe hurt in his right hand and wrist had caused his being left at this place.
It seemed that he had been told we were much at a loss for an interpreter:
he wished to render us every assistance he could,
and was willing to accompany us wherever we might have to go; wanting nothing in return,
as he was comfortably off;
and he was not one that stood opposed to the work in which we were engaged:
as he had but a small piece of land, he was at liberty at any time to attend us.
We acknowledged the kindness and disinterestedness of this offer, and told him,
if occasion required it, we should make application to him.
We think him a suitable person to have the care of some tracts for lending out to others,
and one with whom some of the writings of Friends may be left.

On First day morning, the 24th of Fifth Month,
we proceeded to George Pritchard`'s house about the appointed time.
We were much too early for the school,
owing to there being no regular time kept amongst the people;
and some having to come from considerable distances,
are the more likely to be out of season when they arrive.
The principal teacher, who is a deacon in the church, made his appearance;
soon after which we followed to the school-house.
A considerable number of children were collected:
the boys sitting at one end of a long building, and the girls at the other;
the teacher standing on one side, about midway between them.
He gave out questions to the boys and girls alternately,
which were answered in the same way by a few of the
elder children in a singing tone simultaneously,
the rest seeming to take but little interest in what was going on.
We were told, that when the queen resided here,
the number of children was much greater than at present; but as she now lives at Papaoa,
such children as formerly attended here, now go to the school at that place.

It was considerably more than half an hour after the fixed time,
before we entered (what is called) the church,
where a large number of persons were collected and collecting.
The whole congregation were squatted on the floor,
the building being in an unfinished state, and no seats as yet provided:
they appeared to occupy the whole of the floor, which is very extensive.
While they were proceeding in their usual manner,
I endeavoured to draw near to the Fountain of Israel, whose God is, and ever will be,
Him who gives strength and power to his people.
My heart was softened in an unusual manner,
and the creature was brought down into a state of nothingness:
tears flowed beyond a capability of restraint, as "`in the day of the great slaughter,
when the towers fall,`" (the towers of pride, high-mindedness,
and self-exaltation,) and the will of the creature
subjected to the will of the great Creator;
as shadowed forth by the prophet, when pointing to the spiritual conflict,
and the accomplishment of the great work of regeneration in the heart of man,
at that day when the Lord alone is exalted.^
footnote:[Isaiah 30:25]
My mind was in a calm, and I was prepared to stand up when the proper moment arrived.
At length the singing ended, and a universal stillness prevailed over the meeting,
probably increased by expectation,
which had for some time been stamped upon the countenances of the whole assembly.

"`God is not the author of confusion, but of peace,
as in all churches of the saints,`"--were the first words uttered by me;
which being interpreted,
were followed by,--"`it is not an every day circumstance
for a stranger thus to speak amongst you,
probably what you never before witnessed;
but it is according to the true order of the gospel
that the prophets should speak two or three,
that all might learn and all might be comforted,`"--with more of the text;
repeating again, for "`God is not the author of confusion, but of peace,
as in all churches of the saints;`" proceeding with,--"`I have nothing new to offer:
the way to the kingdom is the same now as in the beginning;
there is no variableness or shadow of turning with that God, with whom we have to do.
The things of time may vacillate and change; but the Rock of Ages remains unimpaired:
it changes not,--"`the foundation of God stands sure, having this seal,
the Lord knows them that are his.`"
This foundation is Christ Jesus: and no other foundation can any man lay than is laid.
Every man`'s work will be made manifest, the day shall declare it,
the fire of the Lord will try it:
that only will stand which is built on Christ Jesus the righteous,
that tried corner stone, elect of God,
and precious indeed to them that believe,--though to the Jews a stumbling block,
and to the Greeks foolishness.
But to them who are called, and who obey, "`Christ, the power of God,
and the wisdom of God.`"
For this cause "`God gave his only begotten Son,
that whosoever believes in Him should not perish but have
everlasting life:`"--with more on this important point.
'`In looking over this large assembly,
the love of God has filled my heart as I have sat
amongst you:--may the Lord in heaven bless you,
is the language that has arisen therein.
It is this love that induced me to come amongst you;
it is this love that would gather all into the heavenly garner of rest and peace.
Endless in duration is the mercy of the Lord; free and unbounded is His love.
His love has been long extended to these islands, and covered them as with a mantle.
This island has had advantages beyond many others.`'
I reminded them that many years
had now elapsed since the sound of the gospel was first heard in their land:
they had long had many parts of the Holy Scriptures in circulation,
which from their earliest pages point to the Saviour.
It was promised soon after the fall of man,
that the seed of the woman should bruise the serpent`'s head.
Moses declared to the people in his day,--"`A prophet shall
the Lord your God raise up unto you of your brethren,
like unto me;
him shall you hear in all things;`" and "`the soul which will not hear that prophet,
shall be destroyed from among the people,`" which led to the query,
what return had been made for all this,
and wherein had they been benefited by these great privileges.
They had run well for a season: what had hindered them? What had prevented them,
that they should have turned again as unto the weak and
beggarly elements? If they had obeyed the gospel,
this would not have been the case:
they would by this time have been a pure people for their God.
That unless there was a thorough alteration and change,
the blessing intended for them would be withdrawn;
and the rod would be administered for their iniquity.
Continuing,--"`Be watchful, and strengthen the things which remain,
that are ready to die; for your works are not perfect in the sight of God.`"
"`Remember, therefore, how you have received and heard; and hold fast, and repent.`"
There is a great work to be done;
for where is your hope when the present generation are summoned from works to rewards,
if the younger children are not trained in succession? I had to call
upon the parents to step forward before it was too late;
they had all a part to take in it.
Tahitian mothers had a large share devolving upon them;
much depended upon their influence and example in endeavouring
to train up their children in habits of civilized life,
by letting them learn to read; (which at present is much neglected,
and disliked both by parents and children;) that so they might partake in
the advantages which are to be derived from the Holy Scriptures:
reminding them, that "`they that be wise, shall shine as the brightness of the firmament;
and they that turn many to righteousness,
as the stars forever and ever,`" exhorting them, not to be overcome with evil,
but to overcome evil with that which is good; that the promises are many, great,
and precious, which are recorded in Holy Writ, to them that overcome, etc.
Though, perhaps, more might be expressed than above noted,
and with some variation as to the words;
yet I believe that what is here inserted is the
substance and principal part of what was uttered.

Having finished, I took my seat.
Soon after this, George Pritchard concluded the meeting.
When the whole congregation rose, the elderly people came forward to shake hands;
but being pretty near one of the doors,
we were soon carried outside by the current of people turning that way.
There were upwards of a thousand people inside of the building,
and a considerable number outside also: the doors and windows being all open,
those without could hear about as well as those within.

28th. (Fifth-day.)--Soon after breakfast,
Charles and myself endeavoured to draw near in silence before the Most High.
Although under feelings of great weakness and inability of
ourselves to maintain the watch against our subtle enemy,
yet we must not shrink or be discouraged from using our
humble endeavours to maintain the unequal conflict;
seeing that He with whom we have to do, knows that we are but dust,
pities our frailties and weakness,
and regards with an eye of merciful compassion his poorest creatures; yes,
even the lone sparrow on the house-top cannot fall to the ground without his knowledge.

Fifth Month 30th.--Yesterday, C. Wilson and son, from Point Venus, dined with us.
They came to inquire for some articles for the latter,
who is about to join the mission likely to proceed to the Navigator islands.
In the evening, went on shore for exercise.
William Henry having purchased supplies for our vessel,
came on board this morning to procure sundry articles of barter goods.
In the forenoon, had an opportunity of furnishing a respectable woman with a Testament,
Selection of Advices, John Woolman`'s Serious Considerations,
and nine tracts on religious subjects.
This female was taken into William Henry`'s family when a child of four years old:
she is well acquainted with the English language, and has a numerous family,
which she is endeavouring to bring up in a praiseworthy manner.
The influence of her example of industry and notability may be traced
in the different appearance of the family from that of others;
and the result is strikingly obvious in the behaviour and habits of the children.
She is, doubtless, the offspring of one white parent.
Her husband is a native, but we have not yet seen him:
they reside in the neighbourhood of Mairi Pehe.

Yesterday morning, a native of Dundalk in Ireland, by name Murphy,
lately arrived in the Peruvian, came on board.
He stated that his coming here was solely for the
purpose of procuring a passage to the Sandwich Islands;
but that he is not suffered to remain here, for lack of proper credentials,
which are required of such as come to reside on shore.
It is one of those cases in which we can not render any assistance,
there being a decided law in this country, that prevents strangers,
under such circumstances, from coming amongst the people,
and which applies to all foreigners.
At the same time, it is pretty evident,
that a fear of his introducing the Roman Catholic religion greatly operates against him;
for which it is probable there may be some ground,
as he acknowledges to have been six years at a college in Ireland, training for a priest;
but says he never was ordained.
He is now come from the Gambier Islands, where, he says,
there are six French Roman Catholic priests and one English:
whatever may be the real cause of his coming here,
his present situation renders him an object of pity.
As attending the public places of worship here,
can only be done to purpose on First days,
as it is only then that large bodies of the people are assembled;
and as it is probable that I may have to see the whole
population of the island before I can proceed any further;
I have felt a little anxious to avail myself of these opportunities,
so as not to protract the length of time we may have to remain here.
In the afternoon my mind became more uneasy, and it seemed best to go on shore,
and make inquiry as to the meetings to be held tomorrow; but I soon ascertained,
that George Pritchard had been unexpectedly summoned to a distant district,
and that notice had been generally given of this arrangement.
I now found that I could not cut and contrive for myself, in my own will, way, and time;
but that the Lord`'s time must be waited for:
without His approving and sanctifying requisition, our creaturely performances,
instead of procuring the blessed and joyful sentence of "`well done,`"
may only place on the same woeful level with the workers of iniquity,
even though we may profess to have prophesied in His name, in His name cast out devils,
and in His name done many wonderful works.

Fifth Month 31st. (First day.)--In the forenoon the decks being too damp,
the crew were collected in the cabin,
where we were joined by several strangers from the shore,
including the family of the female who was on board yesterday, and some others.
After having read the latter part of the epistle to the Hebrews,
and a portion of the Psalms, we settled down into silent waiting,
not aware that I should have any thing to offer.
We continued to sit in this manner, deepening in solemnity;
when I perceived that matter was gathering upon my mind, which, from, as it were,
a mere blank, was now filling under a quickening influence,
until utterance was yielded to.--"`That which may be known of God is manifest in man;
for God has showed it unto him,`" as we are told in the epistle to
the Romans;--"`God has not left himself without a witness,`" in the
heart of every son and daughter of the human race,
however circumstanced, or wherever placed, sufficient if attended to,
and co-operated with on our part,
to enable us to work out our salvation with fear and trembling.--"`He has showed you,
O man, what is good, and what does the Lord require of you, but to do justly,
to love mercy, and to walk humbly with your God.`"
Thus was I led on step by step, until strengthened to show, I trust,
that there was no occasion to look to this minister or that minister,
for we all had the great Minister of the sanctuary,
and of the true tabernacle which the Lord has pitched
and not man,--the only true Teacher of His people;
who continues to teach as never man taught.
Declaring,--that this was "`the grace of God that
brings salvation,`" which "`has appeared unto all men,
teaching us,`" etc.;--that it was the poor in spirit,
on whom the blessing was pronounced.
In this manner, having turned the attention of the company to their heavenly Teacher,
to an extent never contemplated when my mouth was first opened,
we again settled down into solemn silence; and my peace flowed, under a consoling belief,
that my remaining on board was in the ordering of the blessed Master.
I have not met with a circumstance since leaving England, more truly cheering to my mind,
than to find, that the Lord has even in this place, some of the seven thousand,
that have not bowed the knee to the image of Baal.
I pray that I may yet meet with many more like
this dear woman:--before they went on shore,
I had some interesting conversation with her.

Sixth Month 3rd.--For the last three days our time has
been much occupied by persons coming on board,
and in attending to the exchange of some of our articles for barter,
to obtain the needful supplies of fresh provisions, fruit and vegetables.

While on shore yesterday for exercise, we met with an aged native,
who remembered the first coming to these islands of Captain James Cook.
It was clear that he was no stranger to the circumstances of his death at Hawaii,
as he himself alluded to the place.
Although we had the advantage of an interpreter being with us,
yet the age of this man could not be ascertained,
as no record of births is instituted amongst them.
In the forenoon, a judge, with whom we were previously acquainted, came on board,
bringing with him the queen`'s mother, and a third person, to us a stranger.
It evidently appeared to be one of those visits made only with
a view to extort something from us in the way of present;
signs were made by the female of chopping with an axe;
but as I could only talk to her in English, she found there was nothing to be got,
and I did not consider it at all necessary to satisfy
demands which were altogether unreasonable;
and especially as I knew, that if her wishes had been complied with,
numerous applications would be made by her colleagues,
which would have been more difficult to refuse.

Sixth Month 4th.--The king and his brother came on board to dinner,
but did not remain long; their coming now is in a plain way,
they come and go as they please: we treat them with civility, but no longer as strangers,
or they us.
This seems to suit their habits and inclination, which, like their bodies,
are not accustomed to restraint.
They paddle themselves off in a canoe, with no other clothing than check shirts,
with a loose piece of blue cotton tied round the waist,
and low crowned straw hats on their heads, and a broad blue ribbon round them.

5th.--This morning a respectable Spaniard came on board,
whom I had seen several times when on shore.
He was presented with +++_______+++'`s Essays in his own language,
with which he seemed highly gratified.
He had been an officer in the Spanish army,
and was banished from his country at the last revolution in South America:
he has resided here about three years, and bears a good character.
He was promised a copy of the Holy Scriptures and other books in his native language:
I never saw any person so much pleased and thankful at the
prospect of having these books furnished him in this country.
On inquiry, we found that there are three Manilla men here,
one of whom was in the canoe at the time.
This man read very intelligibly in +++_______+++'`s Essays;
and his willingness to receive any books we were
disposed to give for himself and comrades,
made us glad that we are in possession of such a variety in their language.

6th.--At George Pritchard`'s we met with John Davies, the missionary from Papara,
who has been engaged here about thirty-five years; he is an intelligent elderly man.
From his long residence he has acquired the greatest fund of
information respecting these islands and their inhabitants,
of any person we have yet met with;
which he imparted in a manner to us highly interesting, and the more so,
as its authenticity may be relied on.
In speaking of the idols formerly in great repute here and in the neighbouring isles,
he said, that when expostulating with the people,
and endeavouring to convince them of the worthlessness of these wooden deities,
which can neither see nor speak, nor stand, nor go;
the most sensible amongst the natives would say, that they did not worship them as God;
but that they served only to remind them of God, who is invisible,
but in some manner connected with those images,--how they knew not.
He considered that the received opinion of these islands
having been originally peopled from South America,
was altogether without foundation;
indeed their having been peopled from Asia can be proved by striking facts.
When traversing to the westward,
the same language is invariably to be found on the islands, though, perhaps,
in a variety of dialects; and this may be traced to Sumatra, Borneo, Malacca, etc.:
and the same tradition as regards a deity may also be traced throughout them,
more or less in degree, and varying in some particulars: but on going to the eastward,
the language is less and less to be recognized, and eventually disappears altogether.
The intelligent natives seem to be awakened to a confused idea
of a general deluge having taken place at some time or other,
from their having discovered,
that upon the tops of the highest mountains in this island and others,
the same marine substances are met with,
as they are accustomed to find at the bottom of the sea.
It has been the opinion of some,
that the whole of these islands formed at one time a vast continent;
but that by an unaccountable convulsion of the earth, this continent became water,
except the tops of the loftiest mountains,
which constitute the islands as they stand at this day.

7th. (First day.)--Notwithstanding some information had
spread that I should be gone to Papaoa,
yet the state of the weather perhaps induced some to come on board
about the time that we usually assemble the crew together.
We had not sat long before some others arrived.
The forepart of the time the children were a little restless,
owing to the great heat of the place below,
the deck being too wet to allow us to sit in the open air with safety;
but a solemn feeling spread over our little company, and remained with us.
My mind was gradually drawn into exercise,
and at last I had to break through the silence with the expression,--True it is,
that "`God is no respecter of persons:
but in every nation he that fears Him and works righteousness,
is accepted with Him.`"--"`It is a fearful thing
to fall into the hands of the living God.`"
And, "`If the righteous scarcely be saved,
where shall the ungodly and the sinner appear?`" Also, true it is,
that no man can save his brother, nor give to God a ransom for his soul:
the work is our own, etc.
It was one of those favoured times, of which it may be said,
that the latter end surpassed the beginning, "`because of the Truth.`"

10th.--This morning received information that a public meeting of the
principal chiefs and people of the island was about to take place,
to consider the case of the supposed Roman Catholic.
Although I had not been invited to a missionary
conference which had taken place on this subject,
yet I felt my way more than usually opened to attend the council of the Tahitians,
then about to meet.
Accordingly myself and Charles hastened to the shore,
and landed opposite to the building where the people were assembling.
The queen with her mother and attendants were seated upon the floor,
surrounded by the chiefs of seven districts.
The sister of the principal chief, or king of Rarotonga, was one of the party.
The business commenced with the examination of the Irish Roman Catholic;
the place was now crowded with people,
but the examination proceeded very slowly and unsatisfactorily;
which I could not help perceiving was entirely for lack of an able interpreter,
who thoroughly understood the English language as well as the Tahitian.
The people were restless and unsettled from this circumstance,
the most part not seeming to know for what they had come together.
None of the missionaries appeared willing (for
sufficient reasons) to have any hand in the business;
and seeing the real cause of the dilemma they had got into was still undiscovered,
it seemed best for me to step forward, at a suitable moment,
and state plainly to the heads of the meeting,
that it was impossible for the business to proceed
satisfactorily unless a competent interpreter was appointed;
and turning to Captain Henry, who stood near me,
I requested him to inform the chiefs what I had said.
This being done, the council agreed that Captain Henry should be chosen;
and he having consented, things began to move more readily forward,
until the Catholic made some assertions highly injurious to the missionary cause,
and offensive to the queen and all her chiefs, who felt very indignant on the occasion;
and which I knew to be incorrect.
There did not seem any other part for me, however unpleasant,
than publicly to contradict what he had said,
and to declare that some of the language he had used,
had never been expressed by the person whom he was charging with having uttered it.
This for a time caused considerable altercation; but having three witnesses on my side,
this difficulty was soon got over, and order again restored.
The examination continued, until the Catholic,
unable to prove the statements he had made on first coming to Tahiti,
and finding himself foiled on every side, made a hasty retreat,
to all appearance not a little offended.
One of the chiefs then expatiated on the case,
as follows:--"`This man (meaning the Catholic)
held out that he should not come to this meeting;
and it is seen that he did come to the meeting.
He declared that he had a letter sealed with King William`'s seal,
and he had no such thing: that he had a letter from the British Ambassador at Paris,
and he had no such thing; and now, by his running away,
he has shown himself to be a deceiver.`"
Then turning the attention of the assembly to my Charles and myself,
he said, "`On their coming amongst us, we had no occasion to ask for letters;
they gave them themselves into our hands.
It is known to every chief in the island there was no trouble with them,
because they are not deceivers.`"
He finished his speech,
by proposing that such a man should never be allowed to come amongst them.
After this the queen`'s speech was delivered by a clear headed middle-aged chief;
which concluded with a call upon all her faithful
subjects to unite in never permitting this Catholic,
or any other of the same profession,
to come to disturb the peace and tranquillity of Tahiti.
Another chief made a very animated oration,
which we were informed contained a proposition,
not only to banish this man forever from their shores, but to follow him on the sea,
and not allow either him or his comrades to remain so near them as the Gambier Islands,
but to banish them from there, lest the plague should come amongst them:
throwing his long stick upon the floor, to describe them as trampled under foot,
never again to rise.

11th.--Yesterday we went to George Pritchard`'s
to become acquainted with Alexander Simpson,
the missionary from the island of Eimeo.
He had come over to attend the meeting that had been
appointed for the missionaries of all the districts,
to take into consideration the arrival of the Irish Roman Catholic, above-mentioned.
Alexander Simpson`'s wife and daughter were with him.
He seems kindly disposed to forward our views,
when visiting the island upon which he resides.

14th. (First day.)--In the forenoon a few strangers assembled with our own crew.
In the course of the time we were together,
I had a short testimony to bear to the indispensable duty of loving one another.
How can we expect to be forgiven our trespasses,
if we from our hearts do not forgive every man his brother their trespasses.
Soon after one o`'clock, p.m., George Pritchard called,
accompanied by Alexander Simpson`'s wife, in a whale boat,
to convey Charles and myself to Papaoa.
We reached in time for the meeting of the Tahitians,
which consisted of a large body of the people.
Throughout much of the day,
and much of the time also that their religious engagements were going forward,
my mind was under no small weight of exercise,
and it seemed doubtful to myself whether I should have any thing to communicate or not;
but towards the latter part,
I only waited for a proper interval of silence to stand upon my feet.
George Pritchard observing this, asked whether I wished to say any thing then,
or after the next singing was over: but the present moment seemed the right one;
which being signified, he exhorted the meeting to stillness and attention,
and waited by my side for me to begin.
+++[+++Daniel Wheeler then communicated what was upon his mind.]
Shortly after this, the meeting broke up: when the people drew towards us,
and commenced the usual ceremony of shaking hands.
The queen was present; but I did not know it until afterwards.
We called at her house on our way to the boat, but she was gone off on foot to Papoete.

Half-past eleven o`'clock, p.m. My mind is peaceful and easy, and relieved;
and the God of glory has the praise;
who thus continues to bear up a poor tribulated way-worn traveller,
renewing my youth as the eagle`'s, and as the day is, so causing my strength to be.
