== Chapter XXI.

[.chapter-synopsis]
* Visit to Bunaauia
* Native Meeting
* Kindness of the Principal Chief
* Point Venus
* Perilous Situation
* Meeting at Point Venus
* Visit to Papara
* Beautiful Scenery
* School at Teahupoo
* Meeting of the Natives
* Letter from the Native Congregation
* Native Meeting at Papara
* Return to the Henry Freeling
* Letter from the Queen Of Tahiti

Sixth Month 16th.--Last night had some conversation with George
Pritchard about accompanying me to Bunaauia this afternoon.
It was proposed that we should lodge at the house of David Darling,
the missionary at that station,
in order to attend the Tahitian worship at sun-rise tomorrow morning.
We set out in a whale-boat about three o`'clock,
p.m. our company consisted of Alexander Simpson and George Pritchard,
with some other members of the missionary families, my son Charles and myself,
with four Tahitians at the oars.
We had a fine passage while within the reef;
but on reaching the opening which leads out into the main ocean,
the rollers broke with so much violence,
that some of our company were discouraged from
making the attempt to force a passage through it.
At length it was concluded to run the boat on shore upon a sandy beach,
near some of the huts of the natives, who sallied forth in a body,
and soon hauled her up beyond the reach of the surf.
Our party being all landed, we proceeded on foot,
and should soon have reached the mission-house, and in good day-light,
but having a considerable river to encounter,
the night overtook us before we had all passed over it.
This river is rapid, and of uncertain depth;
and notwithstanding the bed of it is covered with loose round stones,
the natives are so dexterous, that an accident but rarely occurs.
A number of these people soon came to our assistance,
and the company were all landed safely on the other side.
Soon after dark we reached the hospitable mansion of David Darling,
and were received with great kindness by his wife and family;
himself being from home among the Marquesan Islands,
where he had gone to assist in establishing a missionary.
At this place we found the wife and three children of J. M. Osmond,
the missionary at the Taiarapu station.
They had been tossing about for a considerable time in a clumsy boat of their own,
not at all likely soon to reach their abode,
unless the wind should blow from a direction seldom witnessed at this season of the year.
Being rather unwell in the evening, and having passed an almost sleepless night,
I felt in poor condition when it was time to get ready
to attend the sun-rise meeting of the Tahitians,
on the morning of the 17th instant.
A large number of the people collected together,
and when the usual service of their own was gone through, I stood up,
and George Pritchard interpreted for me, as at other times.

The principal burden that rested upon my mind,
was to turn the attention of the people to the light of Christ Jesus in their own hearts,
that their conversation might be such as becomes His gospel.
I had to tell them, that although I did not understand their language,
yet I was fearful for them, seeing that for every idle word a man shall speak,
he must give an account in the day of judgment; for by our words we shall be justified,
and by our words we shall be condemned: believing and declaring this belief,
that a very loose and shameless conversation was a besetting sin among them.
I had to remind them of the superior advantages bestowed upon these islands,
over many others of this part of the habitable globe,
by the introduction of Christianity among them.
Had they obeyed the gospel,
the effect of the evil introduced among them by distant nations,
would have been prevented.
That the Lord is looking for fruit;
and "`the earth which drinks in the rain that often comes upon it,
and bears herbs useful for those by whom it is cultivated, receives blessing from God;
but if it bears thorns and briers, it is rejected and near to being cursed,
whose end is to be burned.`"
that the desire of my soul was,
that the lamentation once taken up by the Saviour of the world,
might never be applicable to them as a people:--"`O Jerusalem, Jerusalem, etc.,
how often would I have gathered your children together,
even as a hen gathers her chickens under her wings; and you would not!`"
That the love of God had overshadowed these islands in an eminent degree;
and I never heard of an instance where the Lord in matchless mercy,
was pleased to send any of his servants among a people,
but that his love was still towards that people.
That Christ Jesus had been often preached to them, but they had not obeyed His gospel:
they must repent and obey; and the way to repent and obey, is to fear God,
and give glory to Him.
That it is the same gospel now, as was proclaimed by the angel,
which John saw flying through the midst of heaven,
having the everlasting gospel to preach unto every nation and kindred,
and tongue and people; saying with a loud voice, "`fear God and give glory to him;
for the hour of his judgment is come: and worship him that made heaven, and earth,
and the sea, and the fountains of waters.`"
Desiring that they might be sensible of that day,
when the Lord`'s judgment is come upon all that is of a sinful and transgressing nature;
that so they might indeed fear Him, and in thought, word, and deed, give glory unto Him;
and thus be prepared to worship Him in spirit and in truth;
for it is such the Father seeks to worship Him.
That "`God who commanded the light to shine out of darkness,
has shined in our hearts,`" and to this saving light I wished to turn them.
The people were generally very attentive,
and a solemn covering was permitted to prevail over us.
On rising from our seats, they gathered around us in the usual way.
Being previously acquainted with Utami, a principal chief in that neighbourhood,
we met like old friends, who knew and loved each other,
if his love for me was the same as I felt for him.
We got out into the air as soon as we well could,
in order to escape some of the usual greetings,--not feeling in a condition,
from weakness and exhaustion, to accept of all the kindness intended by these people.
It is indeed worthy of humble gratitude and thankfulness,
to witness how my gracious Lord, from time to time,
has opened the way for me among the missionaries.

The printing-office is established at this place: we looked into it,
but as the principal conductor of this work, David Darling, was absent,
the press was standing still.
The organization of the language,
so as to admit the translation of the Holy Scriptures into the native tongue, is a work,
the importance of which cannot be duly estimated nor conceived, as to the happy result,
under the Divine blessing, that is in store for generations yet unborn;
any more than the extent can be defined to which they may be permitted to
circulate and diffuse revealed truth in the language of holy inspiration.
This work now considered to be near its completion, has been the labour of many years,
in a climate wasting to the constitution of every European,
being oppressively relaxing from the heat.
Henry Nott has been a very laborious servant in this cause,
without any regard to the many hardships and privations which
the earliest settlers had particularly to encounter,
and in which he deeply shared; his constitution is now sinking from long residence,
and the effects of close sedentary application:
who can doubt for a moment the devotedness of such a man?

While here, we were waited upon by Utami, in the capacity of chief,
to request permission to feed us,
as they term furnishing strangers with a supply of food;
which with them is considered the greatest respect that can be shown to a stranger:
but we were compelled to decline their kind attention,
as the materials could not be procured from the
different parts of the district before the morrow,
and we were bound to return to the Henry Freeling that night, if practicable,
as the chronometers from being locked up in our cabin,
could not be wound up until we returned on board again.
The quantity of food usually furnished at such times, is quite preposterous;
consisting of a hog, fowls, fish, plantains, bananas, etc.,
with a quantity of cocoa-nuts, and if hinted at,
there is little doubt that a dog would be prepared,
according to the ancient custom of the island.
As the chief Utami has undertaken to repair a building for a school,
I agreed to furnish a few pounds of nails, and a lock for the door,
for his encouragement in this useful work.
In the course of the day,
our boat was brought from the place where we landed the preceding evening;
and after taking leave of this family, we again reembarked,
and in a short time got safely through the most
dangerous pass in the reef into smooth water,
and reached the Bay of Papeete before dark, not a little fatigued,
and in much poverty of spirit, and unable to write for lack of sleep.

Sixth Month 19th.--Principally employed on board.
Consulted in the forenoon with Samuel Wilson on the
best mode of visiting the district of Point Venus,
where his father resides, and that of Tiarei, the residence of William Henry.
In the afternoon we went on shore for exercise until dark.
Samuel Wilson, with whose plainness and simplicity we were much gratified,
has kindly offered to accompany us to the distant districts as interpreter.

20th.--George Pritchard came on board in the forenoon,
and assisted in arranging a plan for accomplishing our visit to the
remaining and most distant districts upon the island of Tahiti.
It was concluded best for us to set off this afternoon towards Tiarei.
As the wind blew fresh,
about sunset was considered the proper time to proceed as far as Point Venus,
presuming the strength of the wind would lessen as the evening approached.
It was proposed that we should remain at Point Venus until two o`'clock in the morning,
and then push forward so as to reach Tiarei about day-break, before the tradewind set in,
which is mostly pretty strong,
and generally from the quarter to which we were bending our course.
All things being ready, we left the Henry Freeling soon after four o`'clock,
the wind having materially lessened by the fall of some rain,
and it still continued to get lighter as we proceeded.
As there was every indication of clear and serene weather long
before reaching the first place of intended destination,
it was suggested by our native boat`'s crew, that we should not make much stay there,
but push forward while the wind and sea were gentle.
The principal motive for wishing to stop by the way at all,
was to lessen the fatigue of these men by dividing the journey into two parts,
so that they might rest between them:
but they were well aware that the whole distance
could be performed at once in calm weather,
with much more ease than if divided and time given for rest,
if the wind and sea should rise against them, although but in a moderate degree.
Just before dark we landed upon the shore of Point Venus,
the place from which the celebrated navigator Captain James Cook,
observed the transit of the planet Venus on the disk of the sun.
Opposite that part of the coast of Tahiti, which we had next to traverse,
there is no sheltering coral-reef for its protection;
so that the remainder of our journey was exposed to the whole beat of the Pacific Ocean,
and can only be performed when the weather is moderate.

Having with us Samuel Wilson,
we were readily conducted to the habitation of his father Charles Wilson,
the resident missionary at this station, and were kindly entertained by the family.
As the passage round Point Venus is very intricate, and the water particularly shoal,
the boat was taken round to the other side, while we were partaking of some refreshment:
we lost no time in preparing again to embark.
The crew met us with a native torch,
made of the dry branching leaves of the cocoa-nut tree; which with our own lantern,
lighted the intricate narrow path among the bushes,
and was particularly useful at the sea-side, the night being now very dark.
As the night advanced, we were helped by a gentle land breeze,
so that the labour of the oars was a little diminished.
There was an experienced elderly native employed at the stern-oar of our whale-boat,
whose course seemed to be principally directed by the white tops of the rolling surf,
as it broke upon the coast, near to which he mostly kept.
Off one rocky point of land it became needful to
turn with a wide sweep towards the offing,
to escape a projecting ridge of rocks,
the outermost extremity of which was defined by the termination of breakers.

By ten o`'clock p.m., it was declared that we were abreast of Tiarei;
but the night was so dark,
that the narrow entrance through the reef to it could
not be distinguished even by the eagle-eyed Tahitians.
The boat`'s mast was struck,
and one of the natives stationed in the front with Samuel Wilson, to look out;
and her head being turned shorewards, we edged gently down towards the foaming breakers,
which were bursting on the rocky strand with thundering noise.
As the rowing had now altogether ceased,
the boat drifted only at the rate at which the swell of the sea hove her along;
a measure highly prudent,
until the dangerous pass we had to go through was clearly ascertained;
as was afterwards sufficiently demonstrated,
though at the moment such tardy proceeding might seem to protract the term of suspense.
Having silently proceeded for some time in this way,
and from the increasing roar of the restless waters,
evidently drawing nearer and nearer to the margin of the crags,
on a sudden there were symptoms of alarm, which could not be mistaken,
on the part of the boat`'s crew;
who now perceived that we had missed the only
entrance that afforded a passage to the shore;
and, from our present position,
a large lump of rock was in the way to the mouth of the channel,
which the boat could not possibly escape.
Our poor Tahitians immediately jumped into the sea,
and did all they could to save the boat from being dashed to pieces;
but they could not prevent her from striking.
She however only struck once, and lay quiet, the wave having so far receded,
that she did not float enough to beat, and the next roller that came in,
carried her completely over the obstruction.
But it was difficult for some time to ascertain whether the worst was now over or not;
for our men began to howl and shout, the meaning of which we could not comprehend:
it afterwards appeared, that this was done to rouse the sleeping natives on the shore;
who, well understanding this yell,
shortly came running with lighted torches to our assistance,
and a few minutes placed us once more upon terra firma.
As the boat could not get close in, one of these men very soon had me upon his back,
to prevent my getting wet: Samuel Wilson and my son Charles were landed in the same way.

The journey altogether had been more speedy,
and in many respects more favourable than is often witnessed,
until we came to the last pinch,
when the never-failing arm of Almighty power was again
displayed in the needful time for our relief.
As we were strangers to the language of the people,
and could render them no assistance whatever,
and any attempt to direct their efforts must only have increased the general confusion,
we therefore sat silent beholders of what was going forward; committing ourselves to Him,
who saw our perilous situation through the darkened gloom,
and did not suffer the briny waters to prevail against us;
but in love and mercy and compassion, stretched forth his hand to save.
As to myself I may say, my heart was fixed, trusting in the Lord;
whose lovingkindness is better than life.
He was with us of a truth, in fulfilment of his gracious promise,
and we were not confounded.
I desire to record this signal favour with humble thankfulness and reverence,
to His praise and to His glory.
We soon reached the mission-house where William Henry resides,
to whom we were all personally known;
by whom and his wife we were kindly accommodated for the night; although,
from their secluded situation, but little in the way of receiving strangers,
and at an hour so unseasonable they could not have had the least idea of our coming.
Much sleep could not be obtained, but we passed the night in quietness,
and we felt refreshed at rising.

Tiarei,
21st.--Previously to the commencement of the
Tahitian worship at nine o`'clock in the morning,
our time was pretty fully occupied with the family devotion and taking breakfast;
after which we repaired to the meetinghouse,
it being agreed if I should have any thing to speak to the people,
that Samuel Wilson was to stand as interpreter.
This was a relief to William Henry,
(and also to myself,) as he had quite as much to go through as his strength was equal to,
he being far advanced in years.
After William Henry had shown us to a seat, he went into the pulpit,
Samuel Wilson remaining not far from us.
The difference in appearance and in the general deportment of the people,
at this distance from the contaminating effects of the shipping,
was discernible throughout the greater part of the congregation, which was large.
Being comforted by the sensible presence of the great Master,
my mind was strengthened in an unusual manner;
but not until after a season of humiliating conflict had been passed through; in order,
I believe that the excellency of the power might be felt and known,
and acknowledged to be of God and not of us,
nor of any thing that we can command or call our own.
When the usual engagements of the meeting were gone through, I stood up,
and beckoned to Samuel Wilson to draw nearer to me.
We went into a position a little more central, near the table;
and under a solemn covering, after a short interval of silence,
I said:--"`I am fully persuaded in my own mind, that you, my beloved people,
will suffer a few words from a stranger, who is with you in the fear, and in the love,
and I may add, in the will of God, and not in my own;
and therefore I stand among you with innocent boldness,
because I seek not yours but you,
that immortal part in you which must sooner or later have a being in
endless felicity or in endless misery.`" Declaring unto them,
that "`there is no alteration in the Christian course; the warfare is continual,
and can only be maintained and accomplished with burning and
fuel of fire,--by the cleansing operation of that burning,
which the spirit of judgment produces, and that unquenchable fire of the Lord,
which consumes the chaffy and transgressing nature in our hearts; and if submitted to,
would prepare and purify us (even as He is pure) for a kingdom,
consisting not in food and drink,
but in righteousness and peace and joy in the Holy Spirit;--a kingdom,
where nothing that is unclean, nothing that is impure, nothing that works an abomination,
or that makes a lie, can ever enter.
While I have been sitting with you,
my heart has been filled with the love of God towards you;
raising in it a fervent desire, that every individual, from the least to the greatest,
might be numbered among the ransomed and redeemed of the Lord;
who shall return and come to Zion with songs and everlasting joy upon their heads,
from whom sorrow and sighing shall flee away.`" But I had to tell them
that a great and individual work must be accomplished before these
gracious and prophetic promises are realized.
The indignation of the Lord must be patiently borne for sin and for transgression;
until He should arise and plead their cause, and execute judgment for them,
and in his own time say--it is enough; and bring them forth to the light,
even the light of Christ Jesus,
in whom they will then behold the Lamb of God that takes away the sin of the world.
This light shines in every heart,
and is the true light that enlightens every man that comes into the world;
in which only the righteousness of Christ Jesus
is witnessed to be brought forth and beheld.
When the precious blood of Christ was shed for the sins of all mankind,
He ascended up on high; He led captivity captive, and received gifts for men,
even for the rebellious also; that the Lord God might dwell among them,
even among sinners, such as themselves and me.
That a measure or manifestation of the gift of the Holy
Spirit is given to every man to profit withal;
and well will it be for those who are profiting thereby,
and faithfully occupying therewith.
I then had to remind them of the great things which the Lord had done for them:
that the gospel sound had long been heard in their land;
that many parts of the Holy Scriptures had been translated into their native tongue,
which directed them to the Saviour,--to the Word, which was in the beginning,
which was with God, and was God.
After enlarging further,
although I think what I have stated are the principal heads that were touched upon,
I sat down poor and empty; yet satisfied with favour,
and full with the blessing of the Lord.
Instead of the congregation beginning to separate immediately in a hasty manner,
as we have sometimes witnessed, even the dear children kept their seats,
with the whole of the company; a delightful pause ensued, which was short,
but crowned with that solemnity not at our command;
during which I humbly trust the thanksgiving of many redounded to the glory of God.
Silence was at last broken by one of the chiefs expressing,
on behalf of the assembly and himself, their thankfulness and satisfaction,
and how welcome my visit had been to them; because, he said,
"`You have preached to us the everlasting gospel,
and have shown to us the propitiatory sacrifice for the sins of mankind,
Christ Jesus.`" with something further, which when interpreted,
I was fearful attached too much to the creature;
and I requested Samuel Wilson to tell them not to look to the creature,
but to their Creator.
The whole of the people still continued together, about eight hundred persons;
and seemed as if they knew not how to begin to separate,
until some person proposed their shaking hands with us, which immediately commenced,
and exceeded all we had before met with.

On our return, the difficulty of passing through the reef was trifling and insignificant;
the light of day had dispelled all our fears and its terrors:
we could now see what we were about to encounter.
In a few minutes we were clear of the breakers, and spreading our sail,
directed our course towards Point Venus;
where we arrived in something less than two hours,
the wind having kept on the increase the whole of the way;
and having a fine lively whale-boat that could run from the swell,
there was no danger to apprehend, so long as it continued to follow her.
We were soon ready to go to meeting, but a very different scene awaited us,
for instead of another feast of heavenly dainties, the Bridegroom was taken away,
and a fast was proclaimed;--"`then shall they fast in those days.`"
It was a time altogether the most discouraging that had yet befallen us.
The continual talking and light behaviour of a
large portion of the people were truly painful,
although several attempts were made to restore order among them;
and the sound of some sharp strokes of the long sticks,
by the agents employed to keep order, was distinctly heard among the younger people.
I requested Samuel Wilson to say, that although I had brought nothing with me,
a little matter had arisen which I did not wish to take away.
The attention of the people being somewhat arrested, I proceeded with--"`Be not deceived;
God is not mocked; for whatsoever a man sows, that shall he also reap.
For he that sows to his flesh, shall of the flesh reap corruption;
but he that sows to the Spirit,
shall of the Spirit reap life everlasting.`"--"`The Lord is good unto them who wait
for Him,--to the soul that seeks Him;`" and eternal life is the reward of all those,
"`who, by patient continuance in well doing, seek for glory, honour, and immortality;
but unto those who are contentious, and do not obey the truth, but obey unrighteousness,
indignation and wrath, tribulation and anguish, upon every soul of man that does evil,
of the Jew first, and also of the Gentile; but glory, honour,
and peace to every man that works good.`"
I then had to turn their attention to the sure and only foundation, Christ Jesus;
and to the necessity of their believing in his inward and spiritual appearance in
their hearts:--that without faith it is impossible to please God;
pointing to the holy author and blessed finisher thereof,
from whom alone it is to be derived.
Without they live by this faith of the Son of God, who loved them,
and gave himself for them, all their profession of religion is vain.
With some further additions, I sat down; and the meeting soon after closed.
We called at the house to bid the family farewell,
and immediately put off for the Bay of Papeete.
We should have reached the Henry Freeling by dark;
but having lost our pilot and interpreter, Samuel Wilson,
who remained at home at Point Venus, we were twice entangled in the mazy reef,
and forced to row back again each time to get clear of it.

Sixth Month 23rd.--Today employed in arranging matters
to enable us to set out again for the Taiarapu journey,
to visit the district where J. M. Orsmond resides.

24th.--A whale-boat having been procured last evening,
we proceeded after an early breakfast to George Pritchard`'s;
and from there accompanied by our kind friend Samuel Wilson, set forward towards Papara.
We reached Bunaauia in good time,
and were again hospitably received by David Darling`'s family at the mission-house,
he himself being still from home.
After resting our crew more than an hour, we were again seated in the boat,
fearful of wasting time; as the difficulty in some parts of the passage,
going out and in between the reefs, on account of the currents which prevail,
renders daylight indispensable in passing through them.
We landed at a place where a large English barque had been broken up.
Here we met with three Englishmen, employed in preparing to build a new vessel,
with part of the materials selected from the old one.
These poor men seemed to be left in a very destitute and neglected situation;
and it is to be feared,
were strangers to the great work yet to be accomplished
for the salvation of their immortal souls,
if not altogether unconcerned about it.
A parcel of tracts were left for their perusal, which was promised by one of them.

We reached Papara before sunset, and on landing were met by Tati,
with whom I was previously acquainted.
This man is considered to be the greatest orator upon the islands,
and one of the few who stand as champions for the general welfare of their country.
After little more had passed than the salutations customary among the islanders,
the natives began to flock round us as we stood upon the beach,
when an interesting conversation took place in their hearing.
Tati began by saying, that the peace and harmony which now prevailed,
were the result of the gospel having come among them.
I replied, that wherever the spirit of the gospel breathes, there must be peace;
reminding him of the angelic chorus,
that ushered in this glorious dispensation,--"`Glory to God in the highest,
and on earth peace, good-will towards men.`"
He said,
that the wars which formerly were continually breaking out and depopulating the country,
had nearly altogether ceased since the gospel
had been brought to them by the missionaries.
On this I queried,--"`But did you not hear the sound of the gospel,
before the missionaries came among you? I believe you did;
and that many of you were sensible when you committed evil,
and were stung with remorse for it;
and also that a feeling of peace had been witnessed when a virtuous action had been done.
Have you not been sensible of this?`" He replied,
they knew it was necessary to offer sacrifices frequently for sin,
to appease the wrath of an offended Deity.
This, I told him, that had disquieted them for sin and transgression,
though at the time they had not known what it was,
was that gospel which had been preached in and unto every creature under heaven.
After this, Tati invited us to his house, and refreshed us with the milk of the cocoa-nut.
He said,
that although many improvements had been introduced by foreigners coming among them;
yet we might perceive they still retained many of their old habits and customs,
alluding to their domestic arrangements, squatting upon the floor, etc.
The house exhibited more of an air of comfort and
industry than any we had before seen:--native cloth,
fishingnets, etc., of their own manufacture were lying about.
The approach of night occasioned us to hasten to the house of John Davies,
a native of Montgomeryshire, one of the oldest missionaries upon the island,
where we were kindly received and entertained.

Sixth Month 25th.--Rising by the break of day, and partaking of an early breakfast,
we departed, as soon as the family devotion was over for Tairapu,
the south-eastern extremity of the island.
By the way we landed at Mairi Pehe and visited Samuel Henry and family;
he is commonly styled Captain Henry,
from having been several years the commander of a vessel: he is the son of William Henry,
the missionary at Tiarei.
Here the whole process of making sugar was going forward,
from pressing the juice out of the cane by rollers,
and all the different stages that it passes through,
until reduced to the granulated state fit for use.
The sun was nigh setting when we reached the
missionary station to which we were destined;
but the beauty and various scenery of this part of the island served
to enliven the last hour of a long day`'s exposure to the sun,
and to quiet in some degree the sensations of hunger and weariness,
by which we had long been assailed.
The stupendous mountains, however steep and rugged,
were clothed in the richest and fullest manner,
with every kind of fruit and forest-tree which flourish in these tropical climates,
where perpetual summer reigns;
their luxuriance only now and then interrupted by falls of water hurrying
down the steep declivities in beautiful cascades to the vales beneath:
but the noise of these numerous cataracts is at once
overpowered and lost in the roar of the mighty Pacific,
whose waves incessantly thunder in endless
succession upon the shores and reefs of Tahiti.
The rattle of our oars on the ocean`'s glassy surface as we approached near the shore,
soon drew forth the natives, with the missionary John Muggeridge Orsmond,
who were ready to welcome and assist the strangers at their landing.
We had before become acquainted with the wife of J. M. Orsmond at Bunaauia; this,
together with the hearty reception now given us by her husband,
produced feelings somewhat like those experienced on reaching a home:
we were favoured to feel refreshed and well the next morning.

26th.--We went to look at the children who had assembled for school at sun-rising,
with a considerable number of adults of both sexes.
Everything here looked clean and comfortable,
as if under diligent care and superintendence, as did the different buildings,
the whole being in a respectable state of repair.
Being aware that the children would be gratified by notice being taken of them,
I shook hands with every individual, both young and old, that was collected.
While here,
the people present exceedingly urged our staying with them over the next sabbath-day:
but as my engagements were such as could not be altered,
and would prevent my consistently complying with their request,
I asked J. M. Orsmond to interpret my answer; and to tell them,
that as the whole congregation was to meet me in the afternoon,
I trusted that the Divine presence would be with us, and if so,
we should be satisfied with favour, and filled with the heavenly blessing of the Lord.
In returning from the school, we had to pass through a long train of provisions,
which the natives had provided in readiness to present to us, and which,
through the medium of J. M. Orsmond,
we were informed were intended for our food and refreshment.
Although this provision was as unnecessary as it was undesired,
I felt sensible of the kindness and good-will of the people towards us, with which,
at my request, they were made acquainted.
The quantity of food thus furnished was enormous,
sufficient probably to have sunk our boat, if it could have been taken into her.
Besides large quantities of the mountain plantain,
and a variety of other vegetables and fruits, there were several fowls;
and I observed among them a black pig tethered.
The native boat`'s crew, which had brought us from Papeete,
fared sumptuously for two days on the occasion;
and I believe the major part was consumed or carried off by them,
as is customary and expected at such times.

At four o`'clock p.m., the people assembled in the meetinghouse;
where I had full opportunity to clear my mind towards them.
The district on this peninsula being quite distinct from those on the other,
it was needful that my certificates should be read,
as none of the people could have previously heard them.
They were read accordingly, with ample explanation, by J. M. Orsmond,
before I stood on my feet.
The people were turned to the light of Christ Jesus in their own hearts.
They were told that their being members of an outward and visible church,
would not avail them in the great and awful day of account:
that they must be members of the true gospel church, the church triumphant,
whose names are written in heaven; and unless this was attained while here,
it would be too late, for it cannot be done hereafter:
there is no work nor device in the grave, etc.
Showing them how the primitive believers, through the blood of sprinkling,
that speaks better things than that of Abel, attained to it in their day;
and that it is equally attainable at this day,
through the purifying operations of the Holy Spirit.
I urged and encouraged them to persevere in this great and important work,
earnestly desiring that they might not rest satisfied with an empty profession;
but that they might come into possession of the inestimable pearl,
the pearl of great price, the truth as it is in Jesus.
It was indeed a solid and solemn opportunity,
and one of those which I afterwards learned left the people hungering, I trust,
for heavenly bread; while to myself it was productive of that soul-enriching peace,
which can only be purchased by sharing in the blessed Master`'s cup of sufferings,
of which I had drank, and under which I had been heavily bowed down during the afternoon,
before going to the meeting, and there also.
And now how can I sufficiently acknowledge and declare the
condescending mercy and lovingkindness of my gracious Lord God,
who in a particular manner was pleased to warm the hearts of
those dear people with his life-giving presence;
which made it an occasion truly memorable,
and caused many of them to rejoice and abound
with thanksgiving to his praise and to his glory.
The same evening the deacons of the church, Tetohi and Puna by name,
came to J. M. Orsmond`'s house, and being seated with us, one of them produced a letter,
written on behalf of the congregation at Tea-hu-poo; which, being directed to myself,
I opened; it was found to contain the address that follows,
as literally translated by Samuel Wilson.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Tea-hu-poo, 26th of June, 1835.

[.salutation]
Dear Friends,

The ministers, with the Brethren and Sisters in London.

Peace be unto you, in the true God Jehovah, and in Jesus Christ his Son,
who came into the world to save sinful men:--we indeed are sinful men.
Here is Daniel Wheeler among us;
and he has made known unto us all the good words of Jesus Christ.
And comfort has grown in our hearts; and great pleasure has been to us from his words,
concerning the words of Jesus the Messiah.

It was indeed very great pleasure in his saying to us, Jesus is the pearl of great price:
it is a pearl good within and good without.
And many have been the good words that he has spoken to us.
Now indeed we know assuredly he has true love to the brethren
and sisters in all places where the things of Jesus are held.
In that love he has come among us:
and indeed our love is grown towards him and his son,
in their making known on their way the things of Jesus,
and in their visit of love to all the brethren,
and in inviting all to enter in to Jesus the Messiah.

[.signed-section-closing]
Signed on behalf of the Church,

[.signed-section-signature]
Puna

--

At the breaking up of the meeting in the afternoon, I told J. M. Orsmond,
that I felt so much love to these people,
I thought I should see them again--when he proposed to meet me at the
out-station on the other side of the peninsula next First day but one;
where he said he would collect the whole of the people from this place,
and from the two other stations.
I could not speak decisively at the moment,
though expectation was given that it might probably be so.
Since this conversation I have recollected, that on leaving Tiarei last First day,
we were told that the people from an out-station of that district had just arrived,
in expectation that we should be again at the meeting in the afternoon.
It seems right for me to go to the out-station on the other side of the peninsula,
called Tautira; and I find, on inquiry,
that the Tiarei outstation can be visited at the same time;
but that it will require fine weather and a smooth sea to effect it.
It must, however, be left for the present with Him,
who knows the thoughts of all our hearts;
before whom I desire to stand in humble resignation and willingness to go or to stay,
as seems Him good.
The two men who came with the letter before-mentioned,
(Tetohi and Puna) remained with us until near midnight; and I think it may be said,
that by the breaking of bread our spiritual eyes were opened to perceive,
that the great Master was there in marvellous
condescension and mercy to bless the opportunity.
It was indeed a heavenly banquet: and some of us who had lain many days in the grave,
were now, like Lazarus, permitted to sit at the table with their Lord.
I was reminded of the passover,
and was constrained to declare among them,--"`This is
the true supper--this is the sacrament indeed,
as you call it:`" it could not be denied, for the Lord`'s power was over all.
One of those present observed more than once,
"`This is what is so much lacking among us--spiritual religion:
this is what is so much lacking.`" +++[+++Daniel Wheeler then proceeds]--
Hearken to the invitation of the Bridegroom of souls,
held forth in the language of holy inspiration: "`Eat, O! friends; drink, yes,
drink abundantly, O! beloved.`"
Sweet is his voice, and his countenance comely.
Let us hearken that so we may be favoured to hear it.
Let us wait for it with our lamps trimmed, and our lights burning; with girded loins,
like men that are waiting indeed for the coming of their Lord; for sweet is his voice,
even the voice of Him, the same and no other, who said,
"`Behold I stand at the door and knock; if any man hear my voice, and open the door,
I will come in to him, and will sup with him, and he with me.`"
Then let us hearken, so that we may hear; and be ready to open the doors of our hearts,
that the King of Glory may come in.
Blessed and happy are they that hear and obey; they share in the highest, greatest,
and richest heavenly favour bestowed on earth,
by the quickening Spirit of the Lord from heaven, upon poor, frail, mortal dust.
These "`behold the King in his beauty,`" and cannot refrain from declaring to others,
that sweet is His voice, and His countenance comely.

Sixth Month 27th.--Rose early, and after breakfast took leave of the family,
and embarked quickly for Papara.
We reached Mairi Pehe, (about forty miles,) before two o`'clock p.m.;
Samuel Henry rode on horseback to the Mairi, while we pushed on in the boat,
intending to meet together on the spot.
This Mairi was, during the days of idolatry,
considered the most sacred place upon the island: it is spoken of by Captain James Cook,
who visited it when in its full splendour.
At present it appears to be nothing more than a stupendous heap of stones,
almost hidden with bushes and trees that have grown over it and the neighbourhood of it;
where formerly human sacrifices were plentifully offered.
Parting with Samuel Henry, we continued our course to Papara,
and passed through the opening of the reef with a strong current,
before the sun went down.
At this place the boys were amusing themselves in the surf,
by lying at full length on their backs upon boards, and letting the rolling,
curling breakers whirl them precipitately down the liquid slope to the gulf below.
Some of the boys best acquainted with this slippery sport,
by watching the proper moment to launch forth,
were hurled with great velocity to considerable distances,
without being dislodged from their boards;
while the unskillful would be impetuously rolled over by the curling wave,
and for a time altogether hidden in the foam below.
We were received with kindness by the ancient missionary John Davies,
at whose house we passed the night.

Sixth Month 28th. (First day.)--At nine o`'clock a.m., the Tahitian worship commenced.
John Davies had previously told me,
that if I should have any thing to speak to the people,
he himself would interpret for me.
When the customary service was gone through, and he came down from his pulpit,
I rose and stood near him.
+++[+++When the attention of the people was attracted, and stillness prevailed,
Daniel Wheeler communicated what was upon his mind;
he adds,]--notwithstanding there was reason to apprehend that many
would be able to collect but a small part of what was said,
on account of the feeble state of the interpreter,
yet it was so evident that the Divine presence and power reigned over all,
that I had to appeal to the people as witnesses to the
solemnizing influence with which we were favoured.
I trust the Lord alone was exalted this day and magnified;
and the people turned to their true teacher, Christ Jesus;
whose name shall be great in every nation,
from the rising of the sun to the going down of the same.
What might be the feelings of others on this occasion, I am not aware;
it was to myself a highly favoured, precious season,
the sense and remembrance of which is relieving, and still abiding:
and although some days have now passed away since this event took place,
it yet raises in my heart a tribute of thanksgiving, and a song of praise to my great,
and bountiful, and ever merciful Creator and Preserver.

One part of the return journey from Papara, was attended with considerable risk,
by a violent current, occasioned by some alteration which had occurred in the wind,
driving immense bodies of water from the ocean through the open parts of the reef,
causing broken water in every direction;
through the midst of which we were compelled to pass,
surrounded by innumerable spires and stones of coral
rock which presented themselves in every direction;
and through the narrow winding intricacies of which,
we were sometimes whirled in a frightful manner:
we were however safely conducted through them all without any disaster;
although the Tahitians were thrown into confusion,
which added materially to the risk we were encountering,
by their hastily rising from their seats.

We stayed a short time at the house of David Darling,
and then proceeded with a fresh and favourable wind towards Papeete,
where we were favoured to reach the Henry Freeling, about an hour after dark,
and to find all well on board.

30th.--Yesterday employed on board most of the day.
In the evening wrote late to bring up my Journal.
Today still looking forward towards the Tautira journey;
and I shall be thankful to feel clearness and strength from my heavenly Father,
whether by staying or going.

[.offset]
+++[+++Literal translation, by Samuel Wilson of Point Venus, of a letter, received this day,
from the Queen, in which she remits the port dues on the Henry Freeling.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Tahiti, 30th of June, 1835.

I do away with the money for the anchoring of the vessel.
This is the reason why I do away with it, because yours is a visit of love,
and not a trading voyage.
If it was a trading voyage, it would not be done away with:
I would still demand the money for the anchoring: but because yours is a visit of love,
I have not therefore demanded the money.

[.signed-section-signature]
(Signed) Pomabe V.

Health to you and your son in your (two) voyaging.

Na Daniella Wira.

--
