== Chapter XXII.

[.chapter-synopsis]
* Set Out for Tautira
* A Native "`Feeding`"
* Meetings at Tautira
* Visit to Hitea
* Return to the Henry Freeling
* Obstructions to the Progress of Religion
* Visit to the Queen
* Meeting for the White Residents on Board the Henry Freeling
* Letters from Home--Distribution of Books

1st of Seventh Month.--In the forenoon busily employed in preparing
packages to send to the stations of Papara and Taiarapu,
to make some amends for the trouble our late journey had occasioned.
The eldest son of Tati, the principal chief at Papara, came on board to dinner.
His behaviour throughout would have done credit to a people
much farther advanced in civilization than the Tahitians.
Before going away he was furnished with a razor, a pair of strong scissors,
a pocket-knife, and a pen-knife for his father;
and also with articles of the same description for himself,
and a work-bag for the wives of both parties.
Before he left us, George Pritchard came on board to bid us farewell,
as the vessel in which he was about to sail was getting under weigh.
He was going to visit the missions at the Leeward Islands, forming the Society group;
intending afterwards to proceed to the Marquesas, to see the state of things there,
and to bring back David Darling,
who went there several months ago to establish the missionaries, Stalworthy and Rogerson,
on those islands.
Got on shore for exercise towards the cool of the day.

2nd.--Prepared ourselves,
expecting that we should have to be in readiness to proceed on our way towards Tautira,
either late this evening, or at a very early hour tomorrow morning,
so that we might have a few hours to spare to contend with the wind,
if it should prove too strongly opposed to us.
A whaleboat and a crew of Tahitians were accordingly provided for our journey.
After our interpreter Samuel Wilson came on board,
we were soon convinced of the propriety of moving forward this afternoon,
in order to make sure of the object before us, as much as lay in our power.
With exertion we got off at half-past four o`'clock, and were scarcely seated in the boat,
when it was discovered, that the wind which had blown favourably all the day,
was now changed against us.
The men had a heavy pull up to Point Venus,
(of late years called Matavai,) where we landed,
and drank tea at Charles Wilson`'s. There was a little delay at the seaside,
while our men finished their vegetable meal; we then set forward again:
but the wind continuing fresh against us,
it was eleven o`'clock at night before it was reported
that we were abreast of the narrow entrance to Tairei;
and the moon which had shone beautifully all the evening, was now sunk behind the island,
just at a moment when most needed to light us through the difficult opening in the reef.
But having witnessed beforetime the danger of missing the passage in the dark,
and seeing the great utility of timely rousing the sleeping natives,
I did not fail to urge this precaution being adopted,
as soon as we began to steer shorewards.
As we drew near the breakers, the crew shouted and yelled in true native character,
until answered by one of the people on the shore,
who was presently seen running with a lighted torch in his hand,
and soon took up his station directly opposite the narrow pass through the reef.
On nearing the coast, it was found that we were only a few yards to the eastward of it,
and sufficiently distant to allow of the boat`'s head being turned in a fair direction,
without touching the rock.
A few surges hove us through this little gulf into smooth water;
and the crew taking us upon their backs, soon placed their burden upon the sandy beach,
beyond the reach of the agitated waters.

Upon arriving at the ancient missionary`'s dwelling,
it was ascertained that the family were all asleep; and, however undesirable,
there was no alternative but that of disturbing them,
to afford us shelter for a few hours, as the boat`'s crew were too much exhausted,
by having had so long to contend against both the wind and the swell of the sea,
to proceed further without rest.
William Henry himself soon gave us a hearty welcome,
and allowed us to set out in the morning as early as we thought proper,
without waiting for breakfast.

Seventh Month 3rd.--Rising before day,
we departed without seeing any of the inmates of the house,
and continued our course towards Tautira.
As the morning advanced, the wind freshened against us,
and before noon was so much increased,
that it was concluded best to run in the boat at the first aperture
that the coral clad shore should present for our relief:
and just at the moment when the united strength of the
men was scarcely able to impel her forward,
we found ourselves opposite to a narrow passage, but sufficiently wide,
with skillful management, to admit of our entering it with safety;
and a native from the nearest hut placed himself as a beacon for our guide.
On landing,
the boat was immediately hauled up to secure her from the invasion of the breaking surf.
From hence it seemed best to dispatch a letter
by a messenger to our friend J. M. Orsmond,
at Tautira, to say that we had arrived at this point,
and were only waiting for the force of the wind to lessen,
when it was our intention to proceed,
so as to reach the place of destination as early as might be, that evening;
which would allow the whole of next day, (Seventh,) for the information to spread,
in the hope that the meetinghouse would be filled with people the next morning.

Having had but little to refresh us since leaving Point Venus the preceding evening,
two o`'clock the next afternoon was rather a late breakfast hour;
the resident natives had, however, lost no time in preparing some food for us.
After our arrival, they killed and roasted whole a good sized pig upon hot stones,
covered over with leaves and then wood ashes, with bread-fruit, tarro,
and the mountain plantain.
When this "`feeding,`" as they term it, was ready,
and the floor covered over to a considerable
extent with the large leaves of the purau-tree,
it was presented to us in a formal manner, with a bundle of the island cloth,
made from the beaten bark of the bread-fruit-tree,
according to the custom of the country.
The company then sat down upon the floor, consisting of Samuel Wilson,
Charles and myself; with the boat`'s crew close to us, but according to usage,
forming a distinct party.
We had a solemn pause before beginning to dine,
and all remained still until this was over.
One of our men, who had acted the part of cook, cut up the pig,
using a knife with one hand, and holding the victim with the other:
when the carver had separated the pig into a variety of shapeless lumps,
he threw some of them to us, and the rest to his comrades,
and the whole was pretty soon out of sight.
The milk of fresh-pulled young coconuts furnished our drink; and salt-water,
in calabashes, fresh from the Pacific to dip the food in, was used instead of salt:
this we found to be an excellent substitute.
When nearly ready to depart,
about six yards of a piece of cotton handkerchiefs was given to the
man who had charge of the premises during the absence of the owner.
It may be said that we dined in public,
as the place was pretty well crowded with lookers on, principally women and children.

We got nicely out of the creek, and the wind, now much lower, although still opposing,
allowed us to proceed with less difficulty.
The day was nearly closing when we reached Tautira,
situate at almost the easternmost end of the island; it is a straggling village,
about ten miles distant from Tea-hu-poo, where we had been the preceding week;
the whole belonging to the district under J. M. Orsmond`'s care.
On approaching the mouth of the river,
this active missionary was discovered in waiting to welcome our arrival.
He conducted us to the residence (when here) of the queen,
at which place we remained during our stay in the neighbourhood.
In a short time after reaching these premises our attention
was awakened by the voice of a person speaking aloud,
in as high a tone as could be well imagined.
This man, we were told, was the queen`'s speaker, who was come in her name,
that of the church, and of the whole of the inhabitants, to welcome us to Tautira.
On going to him at the door, he delivered a sort of congratulatory address,
which happily was soon over, as he spoke so loud as to make it painful to our ears.
After partaking of some refreshment, in true Tahitian style,
the deacons and some others of the congregation assembled in the room,
and one of them read a portion of Scripture, and prayed at considerable length.
When this was finished, a general conversation followed,
principally on our coming to visit them, and of a serious nature.
We retired to rest about nine o`'clock;
J+++.+++ M. Orsmond upon a strong bench with a back to it, something like a sofa,
Samuel Wilson upon a mat on the floor,
and Charles and myself upon a mat spread over a raised frame, and supported by open work,
made from the bark of a tree, which I thought an excellent bed.
At this place I found my gimlets particularly useful in
keeping my clothing a considerable height above the floor,
by which they were not only out of the damp, but avoided the vermin,
which were very annoying, and of various kinds.
A house-lizard was caught upon the wall in the course of the evening;
the house had been built several years, but had never had doors, so that dogs, rats,
etc., had free access to any part of it.
It was however to myself a peaceful and comfortable asylum.

Next morning, the 4th, we visited the principal part of the village,
after having been presented with an ample feeding in due form by its inhabitants,
accompanied, as usual, by a bundle of island-made cloth, and many assurances of welcome.
This feeding fell into the hands of our boat`'s crew.
A quantity of vegetables were unconsumed when the place was left,
and they took away with them at least seven fowls alive.
In the afternoon the body of the congregation assembled to receive us,
when my certificates were read,
and three persons spoke in strong terms of approbation
and thankfulness at our coming among them,
and of the satisfaction that had been conveyed to their
minds by the language contained in the certificates.
I had to speak a few sentences to them in reference to the certificates,
declaring that I had no other motive for visiting them,
than that the fulness of the blessing of the gospel might be theirs;
that some of them then present must have witnessed what the effect had been,
as far as it had already been faithfully embraced; what then must be the result,
when all the dreadful passions which pervade the human breast are brought
under its benign and heavenly influence? nothing less than peace on earth,
good will towards men: a prospect at which none of them could refrain from rejoicing,
and uniting together in giving God the glory.
On their being informed that my intention was to stay
with them over the forenoon meeting tomorrow,
and then endeavour to proceed to Hitea, they came forward, and in a pressing manner,
desired us to stay over the Sabbath, and spend the whole day with them.
This, however, I could not decide upon at the moment; and a reason being given,
which made its probability doubtful, they were in measure prepared not to expect it.
Some of the people seemed much disappointed at my not
being willing to accept of small presents of shells,
etc.
I requested J. M. Orsmond to inform them, that I sought not theirs, but them;
to bring their souls to God.
I have taken care that the value of the feedings we have received,
should be amply returned in nails, or other useful articles, as clothing, thimbles,
slates, etc.

5th. (First day.)--It is a little remarkable,
that today should be the opening of a newly erected meetinghouse, of large dimensions,
only finished yesterday.
This building is erected upon the site of an ancient Marai,
a place where preposterous scenes of idolatry
and superstition had for ages been exhibited.
At half-past eight o`'clock the children of the school assembled to be catechized,
and at nine o`'clock the regular congregation gathered.
The meeting was well attended; and Samuel Wilson performed the duties,
which at other times devolve upon the resident missionary at each station.
Towards the close of their meeting, I was strengthened to stand up,
and to recite the query of our blessed Lord,--"`Who is my mother? and who
are my brethren?`" which led on to the gracious answer given by Himself,
after looking round upon His disciples;
"`Behold my mother and my brethren! for whosoever shall
do the will of my Father which is in heaven,
the same is my brother, and sister, and mother.`"

The people near the place where I stood were very attentive,
and full opportunity was afforded for me to clear my mind;
and the everlasting blessed Truth was set over all.
It had been previously fixed for us to depart
for Hitea as soon as this meeting was ended,
in order to reach that place in time for the afternoon gathering there;
yet it did not seem as if I had fully done with Tautira.
The morning had been rainy, with thunder,
and the general appearance of the weather now became more threatening than before:
the wind had shifted, and it was blowing strong from the point to which we wanted to go.
Upon inquiry of those best acquainted with the distance from place to place,
and the effect which the present strong wind and swell
of the sea would have in retarding our progress,
with the probability of our not being able to make much headway,
in the heavy gusts which frequently broke forth, it appeared to be the general opinion,
that it was not practicable for us to arrive in time for the afternoon meeting at Hitea.
This, with the information that the natives never travel themselves in rainy weather,
nor expect strangers to do so,
determined me without hesitation to remain with the people of Tautira,
and I had satisfaction in believing, that I should be in the right place;
the tempestuous state of the weather, as the afternoon advanced,
served to confirm the propriety of the measure adopted.

In the afternoon meeting, on standing up, I had to tell the people,
that however contrary to my expectation,
I was fully persuaded that my sitting among them again,
was not only in the will of the God and Father of our Lord Jesus Christ,
but in his everlasting love to their immortal souls;
in which my heart was greatly enlarged.
Many solemn and incontrovertible truths were
brought to my remembrance to speak before them,
under a fresh and renewed influence of heavenly strength graciously vouchsafed;
whereby I was enabled to sound an alarm,
and to point out the repenting sinner`'s sure and never-failing friend and refuge,
Christ Jesus, the Lord of life and glory:
I humbly hope that the great and adorable name of the only true God,
and our Saviour was exalted.

Just as the meeting was about to break up,
the attention of the people was arrested by an individual asking me in English,
whether I could speak encouragingly, and with confidence,
as to the day not being far distant when the reign of
the Messiah would be universal in the earth.
I told him that I could speak with the fullest confidence of
all the great and precious promises recorded in Holy Writ,
connected with this important and interesting subject.
As to the day being not far distant which he spoke of, I was one of those who believed,
that it was already come in the hearts of all,
who believed in the inward and spiritual appearance of the
Lord Jesus by his Holy Spirit,--of those who loved Him,
and obeyed His voice.
The substance of what had passed was then imparted to the people at large.
We then separated under a solemn feeling,
better and more easily to be conceived than described.
The weather cleared up in the evening; and a feeling pervaded,
as if nothing had been lost by the delay, which it had apparently occasioned.

On the 6th, after a break-of-day breakfast of baked pork, the mountain plantain,
and coconut milk, we took leave, and departed for Hitea with a favourable prospect.
We had not rowed much more than an hour, when the trade-wind sprung up in our favour,
and drove us along the coast so quickly, that by ten o`'clock a.m.,
we were abreast of the out-station about to be visited.
On landing, we met with Etoti and Paofai,
two brothers and principals among the island chiefs, then travelling towards Papara;
with both of whom I had been acquainted from almost the
first of our setting foot on Tahitian ground.
We were informed that the people had been collected the preceding day,
in expectation of our arrival; but that the weather had accounted for our absence.
Having made two attempts to see these people, first at Tiarei,
and now again on returning from Tautira,
on each occasion prevented by the weather from seeing them assembled as proposed,
I at first thought that I might venture to move forward towards the Bay of Papeete,
where we left our vessel lying:
but on being assured that if I would stay till next morning,
a meeting would be held in due course at sun-rise, and that many people would attend,
I found that I could do no less than make the sacrifice of another day,
by remaining on the spot, however inconveniently circumstanced.
The idea that I might venture to move on, and pass by these people,
had been none other than a plausible suggestion of the grand enemy;
but I was delivered out of his hand.
This being agreed upon, we were shown to an empty house,
like a large bird-cage in appearance; perhaps occasionally occupied,
though but little trace of that was to be seen.
It was built with open lattice-walls,
and screens of cocoanut branches to keep out the wind.
The floors were covered with withered grass, in a very dirty condition from long use,
being laid upon loose earth, in a low and damp situation.
There were latticed divisions which made four apartments;
but not a door either within or without.
The people soon brought us a supply of food,
according to their custom of treating strangers;
and in due time beds were prepared for us, consisting of frames of wood,
supported on posts driven into the ground, and spread with clean mats.

We paid a visit to the resident chief, to whom I was no stranger,
having seen him more than once on board the vessel.
At his house a large '`feeding`' was preparing, to which we were invited,
but declined partaking of it.
In the course of the afternoon we looked round the neighbourhood;
and after the evening refreshment of ourselves and boat`'s crew,
the governor and the elders or deacons of the church, with a native teacher,
came to visit us.
These were soon followed by a number of men, women, and children;
and when the room in which we sat,
was pretty well filled with guests seated on the floor,
the adjoining room was occupied by others who were only
separated from the rest by open lattice-work;
through which however they could see and hear, and be heard,
almost as well as if we had been together in the same room.
On inquiring of the native teacher, through the medium of Samuel Wilson,
our interested and highly interesting companion and interpreter,
whether there was any indication that would encourage a hope
that some few among the people were desirous to improve in
those things that accompany life and salvation;
he said, he thought, that there were instances where this was discernible,
and that he himself was very desirous and anxious that this should be the case;
that he laboured hard for it, greatly desiring to "`work, while it is called today.`"
I said, where there is such a desire in the teacher,
and a correspondent one in the object of his care,
a happy result under the Divine blessing could
scarcely fail to be produced,--or to this import.
I told him, however,
that although the text he had mentioned might in some degree
be applicable to the work in which he was engaged,
yet I did conceive it was more so,
as regarded the great work of regeneration in the heart of man:
that this great and important and indispensable work,
could be done only while the light of the day of merciful visitation was extended;
and if this unhappily were overlooked and neglected,
a night of darkness would assuredly follow, in which no man can work.
"`If, therefore, the light that is in you be darkness, how great is that darkness.`"
That there was a day of visitation extended to every son and daughter of Adam,
sufficiently long for them all to work out their
own souls`' salvation with fear and trembling;
and it was also as certain, that this day might, from one cause or other,
be overlooked and withstood, or suffered to pass away unimproved.
That this was evident from the language of the compassionate Saviour,
when he lamented and wept over the city of Jerusalem:--"`If you had known, even you,
at least in this your day, the things which belong unto your peace,
but now they are hid from your eyes.`"
"`How often would I have gathered your children together,
as a hen does gather her brood under her wings,
and you would not:`"--which plainly shows, that her children might have been gathered;
but, alas! they would not,
because they knew not the day of their visitation;--their destruction was of themselves.

As we proceeded with this kind of conversation,
the company more and more settled down into serious thoughtfulness.
One person, however,
seemed very desirous to understand what was my real object in coming to their island;
several reasons were alleged,
but they were evidently not comprehended or not satisfactory.
The spirituality of the gospel dispensation was
gradually brought before the view of their minds;
and it was strikingly evident,
that there was a fertile soil or good ground prepared by the ever-blessed husbandman,
in the hearts of some present,
for the reception of the sacred truths that were afterwards disclosed to their view.
Some of them acknowledged that they had never seen things before in the same light,
but at once yielded an assent from sensible conviction.
The important distinction was explained to them,
between the Word which was in the beginning with God and was God, and the Bible;
a subject on which their ideas were confused,
from having been accustomed to hear the Scriptures styled '`the
word of God.`' After alluding to the memorable conference
between the Saviour of the world and the woman of Samaria,
who, when told she had had five husbands, etc.,
left her water pot and went her way into the city, and said, "`Come,
see a man that told me all things that ever I did;
is not this the Christ?`"--I asked them,
if they had not at seasons felt something within themselves,
which brought to their remembrance sins and transgressions that had
been long ago committed,--things which they would be glad to forget,
much rather than remember with painful retrospect;--querying,
whether they had not long been sensible of this,
before they ever saw the face of a missionary,
or heard his voice? On this some of them shook their heads,
and answered in the most satisfactory manner,
with unequivocal simplicity and sincerity,--yes, that they had,
long enough ago;--proving a fact which I have never doubted,
since the Lord Most High was pleased to reveal
the Son of his love to my finite understanding,
that the gospel has been preached in and unto every creature under heaven.
I reminded them of the apostle`'s declaration to the Romans,--
"`That which may be known of God is manifest in them,
for God has showed it unto them;`"`' and--"`He has showed you, O! man, what is good.`"
This I told them was that gospel "`which was preached to every
creature which is under heaven,`"--to every son and daughter of Adam.
On their saying they had never heard of this before,--S. W. replied,--
they had always been exhorted to pray for the Holy Spirit,
to seek and they should find, etc.; but they said,
"`never in this way.`" Such a solemnity now spread over us as could not be mistaken,
even had "`the doors`" been "`shut;`" for--"`peace be
unto you,`" though not outwardly proclaimed,
was known and felt to be among us, by some present.
Under this precious, heavenly canopy,
I told them,--now they might know for what I had come among them,
in the love of the everlasting gospel;--that they might
be witnesses for themselves of the blessings it conveys,
and the glorious privilege to which it entitles, if faithfully embraced.
Some of them could not forbear expressing their inward state, and their fear,
from the uncertainty they were in, as to the future well-being of their immortal souls.
It was indeed a season never to be forgotten;
for it seemed as if some of their hearts were laid open by the Almighty Searcher,
and a willingness wrought to confess their sins, and to call on the name of the Lord,
through the powerful efficacy of redeeming love shed abroad therein,
and working in them to will and to do of the Lord`'s good pleasure:--
to the praise of the riches of his grace be it faithfully recorded,
in characters which can never be defaced while memory holds her place.

At a late hour, we adjourned until sunrise next morning, the 7th of the Seventh month,
when the people generally assembled in a commodious meetinghouse.
As this was a meeting held in regular course,
the accustomed duties were performed by Samuel Wilson,
who acted instead of their native teacher.
My certificates were then read,
which seemed to prepare the minds of the people for the solemn season,
with which we were afterwards favoured.
I had a fine open time among them,
during which the path to the kingdom was set before them, wherein a wayfaring man,
though a fool, cannot err: and the state of mind which must be attained to by all,
before true spiritual worship can be performed, and accepted by Him,
who is worshipped only in spirit and in truth,--was, I trust, declared in plainness.
I had largely to treat on the all-sufficiency of the light, the grace,
which has appeared to all men, bringing salvation to all; teaching all men,
"`that denying ungodliness and worldly lusts, they should live soberly, righteously,
and godly in this present world,`" and commending
"`them unto God and the word of his grace,
which is able to build us up,
and to give us an inheritance`" among those that are
already sanctified by faith that is in Christ Jesus.
I sat down with a thankful and peaceful mind.
Before we separated, one of the people stood up, and thanked me,
in the name of the queen and of the church.
I requested Samuel Wilson to say, that no thanks were due to me:
I had done no more than that which was my duty to do,
and was only an unprofitable servant.
After taking some refreshment, we proceeded to Tiarei.
Our stay here was limited, for fear of losing the wind,
yet we did not like to pass by the mission-house altogether,
whose inhabitants we might never see again.
We had from hence a rapid passage,
and were favoured to find all well and comfortable on board the Henry Freeling.

Seventh Month 9th.--Since returning from Hitea,
my attention has been turned towards the white residents in this neighbourhood,
and I have endeavoured to dwell under the prospect of collecting them together,
with the crews of the different vessels now here, at eleven o`'clock next First day.

11th.--After breakfast, went to inquire of Eliza Pritchard,
(her husband having sailed for the Marquesas Islands,) whether
there would be any meeting for the English tomorrow;
for in the morning, matters had so far opened, that I found it best to tell my Charles,
I did not see that I could do less than endeavour to
meet the English residents tomorrow forenoon.
But little information could, however, be obtained on the subject,
until late in the evening;
when a missionary from a distant station came on board to tell me,
that he had given notice of a meeting to be held on his own account,
but that he should be glad to turn it over to me.
As he had appointed it himself, it seemed best to tell him that he must go on with it,
but that I intended to be there; and if I should have any thing to offer,
it would be only according to gospel order.
Our captain took considerable pains, late in the evening, to spread the information,
that all persons inclining to attend might have an opportunity
of knowing there would be such a meeting held.

12th. (First day.)--Called at George Pritchard`'s
house a little before the time appointed,
to be in readiness, it being near the meetinghouse.
I met there with the missionary who had given notice last evening,
who wished me (as he expressed it) to begin the service of the meeting.
I was best satisfied to decline the offer, as he had personally given notice of it,
and by those to whom he had spoken, it was certainly understood to be for himself:
if it had been appointed for me, it could only begin in silent waiting upon God.
It afterwards occurred to me, however, that at a proper time it would be safest for me,
if found needful, to spread the subject before the meeting when collected together;
and believing that I should have to speak to the people, I availed myself of an interval,
after the reading of the 14th chapter of Luke, to step upon the base of the pulpit,
and state,--that as this meeting was not specifically appointed on my account,
it might be considered out of order to open my mouth in it;
but as we might never have the opportunity of meeting together again,
I had been made willing to attend it,
and in the ability which might be given me to minister in it if called upon:
that such a mode of procedure would still be only in
accordance with the true order of the gospel:
but, if any should consider it an intrusion, I hoped they would speak and object,
and I believed I should be satisfied with having made this offer.
No one spoke, until the missionary said,
he believed there was not the least objection in the minds of any present.
+++[+++In the course of the meeting Daniel Wheeler expressed
what was upon his mind at considerable length.
The people behaved in a solid manner, and a solemn covering prevailed.]

13th.--Employed on board most of the day.
Omitted mentioning that last week a canoe from Tea-hu-poo, and another from Tautira,
reached the ship:
in both these canoes were persons with whom we had social and
religious interaction at the places where they reside.
Their coming afforded an opportunity to send clothing and slates for some of
the most diligent children at the district schools in those parts;
and nails suitable for general purposes, to the different congregations.
As the dear people composing them had abundantly more
than administered to my needs when among them,
it was a relief to be enabled to return their kindness,
and convince them that in my coming, I sought not theirs, but them.
I do feel anxious, and I hope it is an allowable solicitude,
that none may have it in their power to say,
that we have in any degree been chargeable to them;
and thus far I think there are none at whose houses we have been entertained,
that have not in one way or other been remunerated.

There are so many aggravated circumstances which contribute to
lessen the desire of the people for religion,
that the present aspect of things here is truly discouraging;
none of these seems to operate more powerfully to produce dislike and disgust,
than the arbitrary laws that have been made to compel the
people to attend the places of worship and the schools;
the neglect of which has no less a penalty attached to it,
than the forfeiture of their lands.
So long as these things are suffered to exist,
and the native authorities permit or wink at the
landing of spirituous liquors from the English traders,
from the colonies of New South Wales, and from America,
(which are much more numerous than the former,)
hopeless indeed will be every attempt to civilize,
much more to christianize the natives of these islands;
these are disadvantages which must ever impede the free course of the gospel.

15th.--This afternoon went up to Papara in one of our own boats,
to take leave of Henry Nott.
We found him alone, and in a very weak and feeble state.
He has long been unable to attend the place of worship regularly,
though near his own dwelling.
On our return we called to take leave of the queen:
we found her sitting on the step at the back-door,
with several of her chiefs squatted round about her,
one of whom had been reading to the others, until interrupted by our approach;
the king was sitting on a wall, eating part of a coconut.
For lack of an interpreter, I was unable to acknowledge the indulgence of the queen,
in remitting the port charges on our vessel.
Reached the Henry Freeling before dark.
Soon after our return,
the carpenter of the vessel was seized with violent inflammatory symptoms,
which increased so rapidly, that a boat was dispatched for Doctor Vaughan.
One of our strongest seamen,
has for some days been rendered totally unfit for duty by a similar attack,
and the apprentice is nearly useless with an inflamed leg.
Many persons on shore, both natives and foreigners, are in a weak state, occasioned,
it is thought, by the coolness of the night air,
while the sun by day emits a scorching heat.
We have great cause to be thankful for the blessing of
health so graciously bestowed upon us,
while visiting the different stations on every part of the island,
notwithstanding the great dampness of the lodging places which fell to our lot,
and the variety of food, to which we were for the most part wholly unaccustomed;
we had also been exposed to every sort of weather in an open boat, in heavy dews,
at times for hours together.
The distance travelled on these occasions exceeded three hundred miles;
but for the most part, under the reefs of shelving coral,
which skirt the island in many places in a wonderfully providential manner:
where these do not extend, the swellings of the Pacific had to be encountered.
The rapid eddying currents, in some places, rendered our situation perilous at times;
but the Lord was nigh, sustaining us through all, and making our way prosperous,
as already recorded in some of the most favourable interviews with the people, and,
I humbly trust, to the exaltation of His own great and ever excellent name.
Who would not fear Him? Who would not serve Him?

16th. (Fifth day.)--The forepart of the morning much unsettled,
by the natives being more numerous on board than usual;
but a large ship appearing in the offing, served to attract most of them away.
This ship proved to be the Charles Carroll, Reuben Weeks, master;
out twenty months from Rhode Island, in America.
It was quite a relief to be permitted to sit down in silence this morning,
although much was found still remaining to cause
a painful struggle between flesh and spirit.

18th.--Yesterday,
with the exception of taking our usual exercise on shore about sun-down,
we were busily employed on board, among other things,
in selecting copies of the Scriptures in the English, French,
Spanish and Portuguese languages; also a large number of religious tracts,
and some standard works and writings of Friends for Samuel Wilson.
He leaves us next week, on a mission to the Samoas or Navigator`'s Islands.
May the fear of man not be permitted to operate on his mind,
so as to prevent his acting up to what he knows to be right;
but may the fear of God more abundantly dwell in him, and prevail in him abidingly;
and may the rich aboundings of His love in Christ Jesus
be the comfort and strength of his heart,
and his portion forever.

This morning, called on board the American ship Charles Carroll, for a short time.
My mind has at times, both yesterday and today,
been occupied with the prospect of holding another meeting
with the white inhabitants residing in this neighbourhood,
together with the crews of the vessels in the bay,
and any other persons that understand English.
On considering this subject,
it seemed best to hold this meeting on board the Henry Freeling.
It was late in the afternoon,
before I ventured to disclose my prospect to my son Charles and Captain Keen, lest,
instead of being found following my heavenly guide, I should be detected in having,
through mistaken zeal, got before him, and missed the way.

Seventh Month 19th. (First day.)--Early in the morning, the deck of the Henry Freeling,
with the assistance of some planks furnished from the Charles Carroll,
and our own resources, was prepared with seats, in readiness for the intended meeting.
At half-past ten o`'clock, our boats and one from the American ship,
were employed to convey the people on board from different parts of the shore,
and soon after eleven, the meeting was comfortably settled.
As there were a number of persons present who
had never before attended a Friends`' meeting,
and were wholly unacquainted with the manner in which they are conducted, it seemed best,
after we had sat for some time,
to suggest the necessity of our endeavouring to
restrain all wandering thoughts and imaginations,
that we might be sensible of the Lord`'s life-giving presence,
if peradventure we should be favoured therewith;
and also be the better prepared to receive any
thing He might please to give for expression,
for our edification and refreshment,--or words to this import.
A covering of solemnity now drew over the assembly, and continued in a precious manner;
under which I was strengthened and raised up to
speak of the ways of the Lord among them;
repeating his expressions to the disciples,
which so beautifully illustrate the immediate connection between Himself and the church,
under the similitude of the vine and its branches.--"`I am the vine,
you are the branches; he that abides in me, and I in him,
the same brings forth much fruit: for without me you can do nothing.`"
And if we stand in need of help to wade through the common occurrences of human life,
how much more needful then is the assistance of his Holy Spirit,
when thus assembled together for the professed purpose of worshipping that God,
who "`is a Spirit,`" and must be worshipped "`in spirit and in truth.`"
After this,
I had to speak of the excellency and efficacy of silent waiting upon Almighty God,
in order to be qualified for the right performance of this spiritual worship;
that mankind might be turned to the only true teacher of His people, Christ Jesus,
without whom we can do nothing, but all things,
by and through the strengthening influence of his Holy
Spirit:--contrasting the worship under the law,
with that under the present glorious gospel dispensation, unlimited as to time and place;
but which can never be acceptably performed,
while we continue in sin and transgression,--because it
must be offered in the beauty of holiness,
and in newness of life, through the blessed aid of the Holy Spirit,
in spirit and in truth.
I had strongly to press the necessity of every individual`'s turning inward,
and of diligently seeking an acquaintance with the manifestation of the Holy Spirit,
a measure of which is mercifully bestowed upon every son and daughter of the human race;
and which, if sought unto, would set their sins in order before them, in love and mercy,
that they might repent and be saved from them.
Appealing to them,
whether they had not been sensible of the strivings of this blessed Spirit,
when sin had been committed: at the same time declaring,
that it might be withstood and rebelled against, until it ceased to strive;
and they themselves be suffered to go on, adding sin to sin,
without feeling its reproofs and checks.
If this light (of Christ) in you be darkness, how great is that darkness!
Thus would the day of their visitation be passed over, and they know it not;
and this light, if once withdrawn and extinguished in Divine displeasure,
could never be rekindled, although before they might often have been gathered,
like Jerusalem of old.
The heads above quoted may suffice to show the
substance of what I had to express among them,
though but a small part of the whole.
The Lord has been pleased to favour us with many blessed meetings;
but this for solemnity and stillness excelled.--"`Blessed be the Lord God,
the God of Israel, who only does wondrous things;
and blessed be His glorious name forever:
and let the whole earth be filled with His glory.
Amen, and Amen.`"

Our two sick men continue in a precarious state;
their absence from duty seems to protract our stay here:
but I believe it is in the Divine will.
Though sensible of almost daily increasing infirmities, arising from the decay of nature,
yet I am mercifully supported in humble resignation to
whatever may yet be in reserve for me;
being fully persuaded and taught to confide in
the all-sufficiency of that Almighty power,
that can, at His pleasure, help me to run through a troop of difficulties and besetments,
and to leap over a wall of opposition and unbelief.
And as I believe it to be so, why should I not say, in the language of the apostle,
"`I can do all things through Christ which strengthens me.`"

Seventh Month 20th.--Began to prepare the vessel for sea,
in the hope that our two invalids will soon be restored to health,
though at present extremely weak.

21st.--Received a packet of letters from London,
which had been left at the island of Eimeo by the Ulitea,
on her way from Sydney to Raiatea.
Our joy may be more easily conceived than described,
on finding an uninterrupted series of favourable accounts from home, as well as,
in the general, from others whom we also dearly love:
they did not fail to raise in my heart a tribute of
thankfulness and gratitude to the great Preserver of men,
our Almighty and merciful Benefactor.

23rd.--By the mission,
which is nearly ready to proceed to the Navigator`'s Islands or Samoas,
an eligible opportunity is afforded, for an extensive circulation of the sacred writings,
and other books of a religious nature.
We have accordingly furnished a supply of the Scriptures in the English, French, Spanish,
and Portuguese languages.
As many white people and Europeans are known to be mingled
among the inhabitants of this extensive group of islands;
a large quantity of Friends`' tracts, and of those from the Tract Society,
were also selected for distribution through this channel.

24th.--This forenoon the Harmony sailed for the Sandwich Islands.
In this vessel, the mail brought from Sydney by the Henry Freeling, was duly forwarded.
It would have been better for the people of Tahiti, if she had never entered the bay,
having been a fruitful source of wickedness,
from having landed a considerable quantity of rum;
although spirits are strictly prohibited by the present laws of that island.
If all persons who contribute to the destruction of their fellow creatures,
by this or any other evil practice, were publicly stigmatized as the agents of Satan,
and at all times shunned by virtuous characters,
as unworthy of being noticed while persisting therein, it might, I think,
be a means of compelling some of them to desist and to be ashamed of their conduct,
and deter them from further adding sin to sin, in causing others to sin by their means.
The Baiatea, a vessel engaged to convey the mission to the Samoas,
sailed soon after noon for Eimeo.

In the departure of Samuel Wilson for the Samoas, we have lost a most willing, competent,
and faithful interpreter:
but as he was provided for us in a manner altogether unexpected and unlooked-for,
we may safely trust that we shall be cared for in this respect,
while among the islands of the Society group, which we have yet to visit.

25th.--At the close of the public meeting on board the Henry Freeling,
last First day morning, Reuben Weeks, the master of the Charles Carroll,
expressed a desire that a meeting might be held on board his own vessel,
when all the crew would be collected together: of this I was afterwards informed.
This did not escape my recollection,
and my attention was frequently turned to it in the course of the past week,
though until this morning I did not mention it;
when I did not see how I should stand acquitted,
without availing myself of the offered opportunity, and to embrace it.
Having mentioned the subject after breakfast to our captain and my Charles,
I wished to ascertain whether if the meeting should be
held on board the American ship tomorrow forenoon,
it would be attended by the whole of the crew.
There appearing no doubt on this head,
I felt willing that Captain Keen should inform Reuben Weeks,
that I had no objection to the meeting being held on board the Charles Carroll,
provided the whole crew, without any compulsory measures being adopted,
should be found willing to attend it;
but that they should be left at their liberty to choose for themselves in this matter.
It is a regular custom, on board whaling-ships, when lying there,
to allow one-half of the seamen to be on shore daily for exercise;
and therefore I am desirous that all who may attend our meeting
should do it of their own accord;--it was known that only one-half of
the ship`'s company attended our meeting last First day,
the other half having claimed the privilege of their liberty.
As this doubt was removed to my satisfaction,
the meeting was appointed to be held at eleven o`'clock tomorrow morning.
Care was taken that this intention should be spread to all the vessels in the bay,
and on the shore also.
At noon, Reuben Weeks came on board to say, that William Henry,
the missionary from Tiarei,
(now here on account of sickness in his family,) had given notice
that service for the English would be performed by him tomorrow,
at their chapel on shore, at eleven o`'clock.
I did not see it my place to flinch from the
arrangement which had been made as to our meeting,
more especially as no invitation had been extended from
the shore to the crews of the shipping.
In the evening, I called upon William Henry, who having heard of our intended meeting,
at once said that he should countermand the notice he had given,
and would come himself to our meeting;
not doubting but his hearers would be very willing to join him in so doing.

27th.--Yesterday morning, we repaired on board the Charles Carroll,
in time to attend the meeting appointed.
About fifty persons were assembled on the occasion,
and the Lord was graciously pleased to give us a precious season together,
and to magnify His ever great and adorable name.
With those that attended from the shore, were the missionary and his wife from Rarotonga,
Eliza the wife of George Pritchard, and William Henry of Tiarei.

After the meeting had sat a considerable time in silence,
it was with me to make a few remarks, to wean the expectation of the people from words,
and to prepare them for a longer time of silence, if that should be permitted.
I had to tell them, that if I were to read to them,
or to speak to them in my own strength,
it would only be an act between one man and others; but that worship,
for which very solemn purpose we were met together,
could only be performed between man and his Almighty Creator, who is a Spirit,
and must be worshipped in spirit and in truth, with our spirits,
through the Spirit of his dear Son.
A precious covering of solemnity now spread over us,
under the feeling of which we continued until the time
was fully come for clearing my mind among them,
and declaring the mercy, lovingkindness, compassion, and faithfulness of my God;
who wills not the death of a sinner, but rather that all should return, repent,
and live forever.
The means were amply provided by His sending His only-begotten Son into the world,
that whosoever believes on him should not perish, but have everlasting life;
who came not to kill or destroy,--He came, that we might have life;
and that we might have it more abundantly,--declaring himself to be "`the Way,
and the Truth,
and the Life:`" He continues to be so to all such as
not only believe in His outward appearance on earth,
and in His sufferings, death and resurrection,
but in his inward and spiritual appearance also in their hearts,
and in the operation of his Holy Spirit there,--even that of burning and fuel of fire,
to the consuming of the chaffy and transgressing nature therein; and if waited for,
submitted unto, and abode under,
this would prepare us for an inheritance incorruptible and undefiled,
in the kingdom of Christ Jesus, that shall never have an end.
I had largely to treat on the subject of Divine worship,
and to point out the difference between that under the Mosaic dispensation,
and that under the gospel: that, with the Jews under the former, was outward, ceremonial,
and superficial; but under the latter, it was altogether inward,
in the inner temple of the heart,--simple, but spiritual and substantial,
in spirit and in truth.
I had to declare the beauty, purity, and spirituality of the true gospel church,
of which none are members, but the ransomed and redeemed of the Lord;
who have passed through the great work of regeneration,
and have been ransomed by the blood of Jesus:--with much more of warning,
and exhortation, and encouragement, as ability and utterance were graciously afforded.

After I sat down, my heart was filled with humble gratitude;
and a tribute of thanksgiving and praise was raised to
the God and Father of our Lord Jesus Christ,
who had thus graciously condescended to make Himself known among us, what if I say,
by the breaking of the bread of life: under a sense of which,
I had publicly to acknowledge the same,
and that the Lord should have the glory due unto His holy name.
The meeting held longer than usual; but the weight and solemnity so strikingly apparent,
(as afterwards openly acknowledged,) remained to the last undissipated and undiminished.
What, indeed, is man, or the son of man,
that the Lord Most High is thus mindful of him,--that He thus visits him.

28th.--I may mention, for the encouragement of others,
who at a future day may have to follow in a track similar to this,
in which it is my highly-favoured and happy lot to tread,
that previously to attending the meeting just alluded to, I had felt very poor,
and empty, and disqualified:
although without any particular feeling of discouragement as to the result.
When the time came for me to stand up,
although weakness and fear were my wholesome companions; yet the further I proceeded,
the more I was strengthened and furnished for the work before me,
and was even to the end unexhausted.
The remainder of the day, and through the night-watches,
my peace flowed undisturbed and uninterrupted, as the stream of a mighty river;
and a song of praise filled my heart:
for I was indeed made joyful in the house of prayer,
as on the mountain of the Lord;--to the glory of the riches of His grace be it spoken.
