== Chapter XXVI.

[.chapter-synopsis]
* Sandwich Islands
* Anchor in the Harbour of Honolulu
* Native Meeting
* Visit from the King
* Meeting at the Mariners`' Chapel
* Distribution of Tracts, etc.
* Native Meeting
* Visit of the Governor of Hawaii
* Half-Caste Girls`' School
* Meeting at the Chapel
* Native Marriages
* Meeting at the Chapel
* Native Girls`' School

Oahu.
Twelfth Month 26th.--Plyed to and fro during the darkness to windward of the island,
and at the earliest dawn of day bore up for Diamond Hill.
As we neared the entrance, several boats were seen coming out.
The first brought two or three of the resident traders,
the second brought the pilot and some others,
and in the third came the British and American Consuls;
the former bringing us a packet of letters from our beloved family, as might be expected,
all of old date, but new to us, and truly welcome;
and afresh claiming a grateful tribute of thankfulness to Him
whose tender mercies extend to all His poor unworthy creatures,
however widely separated.
The wind, which at first was likely to prevent our getting in, now changed,
and bore us quickly through the winding narrow channel,
into the still harbour of Honolulu.
The anchor was but just dropped, when Hiram Bingham,
the senior missionary of the establishment at this place, came on board,
and offered his services in whatever way we could accept them;
at the same time inviting us to become his guests while here.
We had on board a large packet of letters and parcels
for him and his colleagues on these islands.
It appeared that information of our being at the
Georgian Islands had long since reached this place;
and as soon as our vessel came in sight, there was no doubt,
from her strange and novel figure in these seas, but that we were arrived:
this was evidently the case, for the British Consul, Richard Charlton,
brought off our letters without hesitation.
The natives here being much accustomed to see shipping,
in general take but little notice of them, and seldom visit them;
but they soon swarmed upon our deck,
attracted by the odd appearance of the Henry Freeling;
and we afterwards understood that they gave her the name of
the "`Mast-and-a-half.`" We now find it needful to make an
alteration in the day of the month and of the week,
to accommodate the time in these islands.
Yesterday was with us what is commonly called Christmas-day: but we find that today,
(with us the 26th,) is here only the 25th, and is observed accordingly.
To prevent confusion, we purpose adopting the day considered the sabbath here,
instead of our own, while we remain among the Sandwich Isles;
but the ship`'s log-book will still retain the dates and days as when we left England,
and in it the change will never be observable.

27th.--In the afternoon landed and made our way to Hiram Bingham`'s habitation;
but not finding him at home, we called upon the British Consul,
who kindly accompanied us to obtain some exercise on foot,
it being forty-five days since we had had an opportunity of
walking more than a few paces at a time on the Freeling`'s deck.
Returned to Hiram Bingham`'s about the time his return home was expected,
and found him accordingly.
Believing it safest for me not to miss an opportunity, if one could be obtained,
of seeing a body of the natives collected together tomorrow,
at their own place of worship, I mentioned the matter to Hiram Bingham,
who readily made way for my accommodation,
kindly offering his services to interpret if I wished to address the people.
After partaking of an early tea with the family, we returned on board,
at ten o`'clock p.m. Mercifully supported to look forward towards tomorrow in
humble confidence and hope of that help and strength which is almighty,
and which has never yet failed to deliver me out of every trouble and distress.
My trust is in the Lord,
who alone can bless and cause his own works to praise his ever great and adorable name

28th. (First day.)--At nine a.m., repaired to the house of Hiram Bingham,
who accompanied us to the native meeting.
As the branch of the mission here consists of several families from America,^
footnote:[The missionaries stationed in the Sandwich Islands
are exclusively from the American board of missions.]
who understand the native language but in a small degree,
and as some other white people attending the meeting
are labouring under the same disadvantage,
Hiram Bingham proposed that my certificates should be first read in English,
and then to the people in the native tongue;
and this plan afterwards appeared more eligible,
when it was observed that other persons came into the meeting
(probably induced by curiosity) who do not attend on other occasions,
such as the foreign Consuls and others from the town.
The service performed here by the missionary,
somewhat differed from what we had seen among the Southern Islands.
It commenced with a very short prayer,
which we had previously been told was for a blessing on what was about to follow;
a portion of the Scriptures was then read, and afterwards a hymn was sung.

When this was finished, the principal prayer, as before explained to us,
was offered at considerable length, and then another hymn was sung,
after which the reading of my certificates commenced.
I had sat under a great weight of exercise,
from a belief that I should have to stand up when the reading of them was gone through,
and not without a humiliating feeling of weakness and fear at my own insufficiency.
Not having for perhaps a year and a half heard my certificates read,
except in the Polynesian language, I felt quite struck on hearing them in English;
but I think the unity and sympathy of my dear brethren and sisters at home,
never at any time felt so truly precious and strengthening to my bowed-down mind:
and the expressions which they contain of my beloved
family`'s concurrence with my leaving them,
to attend to the call of apprehended duty, were so unexpectedly sounded in my ears,
that the weakness of human nature could not be repressed,
nor the tear of parental affection restrained.
"`Deep called unto deep;`" the waves and the billows passed over,
leaving me in a state of nothingness and emptiness; but, perhaps,
never more fit to declare of the goodness and mercy of my Lord,
in the ability he was graciously pleased to bestow.
When Hiram Bingham had finished reading and explaining my certificates to the people,
I went and stood by his side, as "`a reed shaken with the wind.`"
A solemn silence now prevailed over us,
until it was with me to say--'`It is more than probable
that the greater part of the company now assembled,
never before heard of the existence of a Society under the denomination of Friends,
(alluding to my certificates:) but my beloved people,
all such as love the Lord Jesus Christ and keep his commandments,
are friends,--friends universally to God, friends to one another,
and friends to all mankind.
"`You are my friends,`" said Christ, "`if you do whatsoever I command you.`"
All such are members of the same society the world over.`' Then,
charging the people to endeavour to draw near unto God,
that under the sanctifying influence of His power and life-giving presence,
our meeting together might be rendered a blessing,
I was largely opened to declare the everlasting Truth among them,
and to turn them to its light in their own hearts,--to the Holy Spirit of Him,
who is "`the true light that enlightens every man that
comes into the world;`" in whom only there is life,
and who is the only way to God the Father, as declared by himself:--"`I am the way,
the truth, and the life; no man comes to the Father but by me.`"
That a mere outward profession of religion would prove altogether unavailing to them;
the great work of regeneration must be witnessed:--that to be members of the
true church they must be redeemed with judgment from sin and transgression,
and be converted unto God by the righteousness of Christ Jesus,
believed in and submitted to through faith in the operation of the Spirit of God;
who raised Him from the dead, with whom also they must be raised from death unto life.
That we cannot worship God in the manner He requires,
while we continue in sin and wickedness;
for the prayers of the wicked are not heard,--they cannot pray acceptably in that state;
their sacrifice is an abomination.
The true and living worshippers of the only true and living God,
are no longer dead in sins and trespasses;
they are redeemed from these by the righteousness of Christ Jesus,
who came to save his people from their sins, and never while they continue in them.
That we must fear God, and in thought, word, and deed, give glory unto Him,
before we can worship Him in spirit and in truth.
For considerably more than an hour my heart was enlarged in the Sowings of gospel love,
as a stream bearing down everything before it.
A more attentive audience can scarcely be conceived, than certain classes of this people,
both natives and foreigners.
The Lord`'s power had the dominion, and reigned preeminently,
until the breaking up of the meeting.
Every class and variety of the people flocked round us,
scarcely affording us an opportunity of speaking
to the members of the missionary establishment.
Some of the natives endeavoured to thank me through the medium of Hiram Bingham;
but I requested him to refer such to the great Creator, and not to the creature.
One said I had brought them a blessing.
A number of serious-looking women came round us,
whose countenances bespoke the love that was in their hearts.
Troops of the dear children gathered in their turn,
and seemed delighted to find that they also might shake hands with the strangers:
some of them would come again and again until they found their faces were recognized.
We seemed to need more hands than we possessed,
as frequent attempts would fail to shake hands with those that held theirs out to us,
by others reaching forward and taking hold of ours before them, in quick succession.
Thus has my gracious Lord been pleased to deal with a poor, unprofitable creature,
but who is a living monument of His everlasting love and mercy;
although he is unworthy of being numbered among the least of His servants.
Truly His judgments are a great deep; but His love who can declare? It is unutterable,
unfathomable, and unbounded as His mercy; whose is the kingdom,
and to whom all power and glory belong forever.
When we got into the open road,
Hiram Bingham told us the bell was then ringing at the Mariners`' Chapel,
where the English and other foreigners meet, if I wished to go to it.
I replied, that I believed I must go on board to my little family there.

31st.--Engaged on board during the forepart of each day,
preparing despatches for England, and by the numerous callers to look at the vessel,
and see the newly-arrived strangers: the governor of the fort,
and some of the principal chiefs, with the governor of the island of Maui,
were among them.
In the afternoon took exercise on shore, and called upon some of the inhabitants;
engaged in writing till late at night.
This evening spent some time with the seaman`'s chaplain,
a young man appointed and sent out by the Seamen`'s Friend Society in America,
to preach at the Mariners`' Chapel.
While we were together, some interesting conversation took place on important subjects.

First Month 1st,
1836.--This morning a deputation of chiefs of the highest order came on board,
bringing a letter, addressed to me, as follows:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Honolulu, January 1st, 1836.

As an expression of friendly regard of Kinau and her associate chiefs to Mr. Wheeler,
the friendly visitant, they beg his acceptance of a few supplies.
They are the following:--five barrels of potatoes, five turkeys, five fowls, and one hog.

[.signed-section-signature]
Na Kinau

--

Finding upon inquiry that to refuse this present, would create much dissatisfaction,
because entirely intended as a good-will offering,
the following acknowledgment was returned:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Henry Freeling, in the harbour of Honolulu,

[.signed-section-context-open]
First Month 1st, 1836.

[.salutation]
To Kinau, the governing chief of the Sandwich Islands,

Highly sensible of the kindness and hospitable intention of Kinau,
the governing chief of the Sandwich Islands, and the constituted authorities of the same,
I assure them of my Christian regard in the love of the everlasting gospel,
which has induced me to visit these isles afar off.

I feel and value this token of good-will, in their act of generosity,
and I do freely accept the supplies so gratuitously furnished.

With best desires for their present and eternal welfare,
and that of every age and every class over whom they preside,
I am her and their sincere friend.

[.signed-section-signature]
Daniel Wheeler

--

Before the business was fully arranged, and the parties gone from the cabin,
the young king Kauikeaouli arrived, with several of his principal attendants.^
footnote:[Kauikeaouli is said to mean in the Sandwich
Island dialect, "`to hang upon the dark blue sky.`"]
He was escorted on board by the English Consul, accompanied by two other foreigners.
It appears that the king, although the lawful ruler of these islands,
has delivered up the executive power into the hands of Kinau,
and takes no part whatever in the administration of public affairs.
He is surrounded by a set of evil advisers, and there is every reason to apprehend,
he leads a very unsteady, dissipated life,
but is said to possess good abilities and an amiable disposition:
he talks some English and understands much of what is said.
He examined every part of our vessel very minutely,
and might possibly have gone to the mast-head,
(a common thing with him;) but our rigging being fresh tarred,
deterred him from attempting it.
An intelligent person, a native of Dundee, was on board at the time,
though not one of the palace party.
To this man I mentioned what I thought of the islanders; and as the king,
who sat next him, appeared to listen attentively,
I spoke freely and plainly of the ruin that awaited these islands,
if the importation of spirits and the use of them were allowed to continue;
and unless the private property of the poor inhabitants is protected by wholesome laws,
firmly executed without partiality.
At present these people are groaning under an arbitrary feudal system,
kept up with shameful tyranny on the part of the chiefs.
I may mention a recent instance that has come within our knowledge,
which is only a fair specimen of the actual state of things here:
an industrious native had grown a small plot of sugar cane,
and when its produce was ascertained,
his chief who had permitted him to cultivate the land,
ordered the whole of it to be brought to him, except a portion of the molasses.
This summons was duly obeyed, and the chief afterwards informed him by message,
that the next year he should take the whole, both sugar and molasses.
This however so damped the exertion of the poor man,
that he did not attempt to grow any more; though, if his chief had insisted on it,
he dared not have refused, as things now stand.
This mercenary chief has been one of our visitors on board.

2nd.--In the evening called upon Hiram Bingham and Richard Charlton.
On our way to the habitation of the latter, accidentally met with the seaman`'s chaplain,
who accompanied us there.
While together,
I felt best satisfied to make inquiry as to the probability of the inhabitants
being willing to attend a religious meeting held on a First day evening;
and being assured that the foreigners would come
more freely in the evening than in the morning,
I believed it best for me to agree,
that public notice should be given at the close of the morning meeting,
that a meeting for worship after the manner of the Society of Friends,
was intended to be held there in the evening of next First day,
at the usual hour of the place being open:
the use of the Mariners`' Chapel having been previously
offered at any time I might be ready to accept it,
with every assistance that could be suggested, as likely to facilitate my object.

3rd.--Having prepared a number of written notices of the intended public meeting,
we landed and took measures for their circulation.
Called at the reading-rooms, and looked into the chapel, which is over them.
Captain Keen was employed to spread the information of the
meeting both on shore and among the shipping in the harbour.
"`The Lord is my defence, and my God is the rock of my refuge.`"

5th.--Yesterday,
as our people were left at their liberty to attend a place of worship on shore,
Charles and myself sat down together in the forenoon:
with the weight of the prospect before me of the appointed
meeting to be held in the evening with the public,
the quiet season we were favoured with was both refreshing and strengthening.
We landed soon after dark to be in readiness for the time appointed,
and repaired to the place of worship.
The time no sooner arrived, than the people poured in from every direction,
and soon filled nearly all the seats.
The novelty of a "`Quaker`'s meeting,`" and the first ever held on a Sandwich Island,
might induce many to come out of curiosity,
who at other times never think of attending a place of worship; and it is probable,
that the whole of the white residents were present,
besides those who came from the shipping,
and a considerable number of the natives and halfcastes,
with several of the highest authorities in the place; so that the house was crowded,
we were informed, as it had never been before.
Sitting in silence seemed quite incomprehensible to nearly all that were there.
The first part of the time was unsettled by many whispering and talking,
and an individual or two not quite sober, were a little troublesome and annoying;
but I think I have witnessed in lands accounted civilized, a meeting,
from one or other cause quite as unsettled,
though altogether free from the disadvantages under which this was labouring.
Having sat a considerable time in silence after the meeting was fully gathered,
it was with me to say,
that as the disciples formerly were incapable of feeding a hungry multitude,
until the great Master had blessed and broken the bread, so it is at this day.
Without Him we can do nothing as it should be done;
and it is only when He is pleased to qualify any of his servants to proclaim his Truth,
that the people can be availingly benefited.
"`Without me you can do nothing,`" was our Lord`'s declaration;
and true it is,--for without Him we can do nothing, not even think a good thought,
nor restrain an evil one; the spirit truly is willing, but the flesh is weak.
That the Society of which I have the privilege of being a member,
has always borne a faithful testimony to the excellency of waiting upon the Lord,
as the all-sufficient and only true Teacher of his people.
After recommending that we should endeavour to wait for the
influence of the Holy Spirit to solemnize our minds together,
I sat down.

The meeting became much more settled after this,
though doubtless the patience of many were tried before the silence was again broken.
When the time was come, I stood up with these expressions: "`I am no prophet,
nor a prophet`'s son,`" but in me you may behold a
living monument of the Lord`'s everlasting mercy;
and although, in my own estimation, less than the least child that is alive in the Truth,
yet to me, even unto me is this grace given,
that I should declare unto others the unsearchable riches of Christ.
I have no sinister motive in thus coming among you;
the comprehensive principle of the gospel, which would gather and embrace all mankind,
enables me to call every country my country, and every man my brother.
It is this that has induced me to leave a delightful home,
and a numerous and endeared family, and everything besides which a mortal need possess,
and more,--to visit these "`isles afar off;`" well knowing,
that whosoever loses his life for Christ`'s sake
and the gospel`'s, "`the same shall save it.`"
I have no new doctrine to preach; the way to the kingdom is the same that it ever was;
the foundation is the same,
"`Jesus Christ himself being the chief corner-stone:`"--
"`for other foundation can no man lay than is laid.`"
But although the foundation be from everlasting to everlasting,
yet if the superstructure is not raised upon it, what will it avail? It is, then,
of the greatest importance for each of us seriously to examine,
upon what we are really building our hope of salvation;
for a day of trial will come upon every man`'s work: the day will declare it,
and the fire of the Lord will try of what sort it is;
when nothing will stand and endure the trial, but what is built upon the same sure,
immutable foundation,
which the righteous in all ages and generations of the
world have built upon,--even Christ Jesus the righteous,
that tried corner-stone, elect of God,
and precious indeed to them that believe and obey His gospel.

I had largely to declare of the universality of Divine
grace,--that none are left short of a measure of it:
it has appeared unto all men, and its teaching, if regarded,
would bring salvation to all men.
That "`a manifestation of the Spirit,`" which is no other than "`the
Spirit of grace,`" is "`given to every man to profit withal.`"
This precious gift was not limited to a few individual members of the church only,
but extended to all men universally; first,
when our holy Redeemer had suffered without the gates of Jerusalem on Calvary`'s mount.
"`He ascended up on high, led captivity captive,
and received gifts for men;`" not for an elect, chosen few only,
to the exclusion of others, but "`for the rebellious also;
that the Lord God might dwell among them,`" as by holy writ declared.
So that every man has "`a manifestation of the Spirit bestowed on him to profit
withal;`" however widely this Divine gift may be diversified in its operations,
or its administrations may differ, it was obtained through the shedding of His blood,
"`who died for us, and rose again,`"--"`the just for the unjust,
that he might bring us unto God.`"
All men have an opportunity of becoming members of the mystical body of Christ,
the true church,
if but willing to turn to the light of the Holy Spirit of the Lord Jesus,
that shines in every heart,--"`the true light,
that enlightens every man that comes into the world.`"
Although many may think themselves dwelling securely, and spending their precious time,
days without number, in dissipation, folly, and utter forgetfulness of God,
rejoicing as in the days of thoughtless youth; yet they will be overtaken at last,
when least expecting it, in the midst of their sinful course, and brought under judgment.
"`Rejoice O! young man, in your youth;
and let your heart cheer you in the days of your youth;
and walk in the ways of your heart, and in the sight of your eyes: but know,
for all these things God will bring you into judgment.`"
Ask the votaries of dissipation and folly, after a dark season of sinful pleasure,
or rather of wretchedness, if they have not felt horror, remorse, shame, and fear,
the certain and constant attendants upon guilt,
and which are nothing less than the effects of the strivings of the Holy Spirit,
discovering unto them their deeds of death and darkness; and which, if attended to,
would deliver them out of this miserable bondage of Satan,
and lead them to the knowledge of the Holy Spirit of Him,
who is the life and light of men.
It is true that this light would make manifest all their evil deeds;
it would set their sins in order before their guilty minds,
in tenderest mercy and redeeming love; that they might forsake them and repent,
return unto God and live.
But, alas! how many turn away from these faithful reproofs of instruction,
and join in fresh scenes of vice and wickedness;
or with large draughts of strong and poisonous drink,
endeavour to smother and drown the voice of this heavenly witness against sin.
But this light will search them out at last, although but for their condemnation.
To those who turn inward unto it, and are willing to bring their deeds to its shining,
the exceeding sinfulness of sin will be discovered:
that sorrow of heart will then be begotten,
which never fails to work true and unfeigned "`repentance toward God,
and faith toward our Lord Jesus Christ.`"
It was the desire of my heart that all might be encouraged to repent, return, and live,
by embracing the means so amply provided in wondrous love and compassion,
for the salvation of all mankind.
So great was the solemnity that continued to be spread over us,
that I had to call the attention of the people to it,
as beyond the reach and power of man to produce.
The Lord alone was exalted; His own arm brought him the victory and the praise.

First Month, 8th.--Since the 5th instant,
our time has been filled up in preparing letters for England,
and in making a large selection of Friends`' tracts, with several of their standard works,
illustrating the principles of the Society;
also numerous other tracts for depositing in the reading rooms,
fitted up by the "`Seaman`'s Friend Society in America.`"
Some of the tracts were for general distribution,
the others to lend out for perusal;
a copy of each of the standard works to remain stationary at the rooms:
the total number of the above was 1099. There is a large field
open for the circulation of publications among the shipping,
which touch here for supplies, etc.; there are at present twelve sail in the harbour.
This morning furnished some Spaniards on board the Rasselas,
(which sailed for China in the afternoon,) with two Testaments,
and some other religious works in the Spanish language.
English Testaments were given to two half-white girls, who had learnt to read in English.

10th.--I have several times throughout the week
had to look towards the approaching First day,
as if I might have again to go to the natives`' place of worship, and, probably,
hold another public meeting with the foreigners in the evening at the Mariners`' Chapel;
but I could not arrive at sufficient clearness,
to warrant the necessary steps being taken to bring these things about.
This afternoon, it seemed best for me to go on shore to Hiram Bingham, and say,
that if I should come to the native meeting in the morning,
I would endeavour to be at his house in time: this matter, though in degree arranged,
was still left open.
It was afterwards agreed with the minister of the Mariners`' Chapel,
that if I should have to hold another meeting with the foreigners tomorrow evening,
care would be taken to inform him in time, that public notice of it might be given,
at the breaking up of the morning meeting at his place.
Satisfied with the steps thus far taken, I returned on board before dark,
leaving the following morning to decide the work of the day;
taking care to have a written notice ready,
of the intended public meeting to be held after the manner of the Society of Friends,
if the way should be clear to make use of it;
but I was not satisfied that it should be forwarded, until after the native meeting,
if I should have to be there.

11th. (First day.)--Awaking at an early hour with the
prospect of the native meeting full before me,
I made no hesitation about setting off to attend it.
My Charles,
who for some days past had had considerable irritation about his throat and lungs,
was too unwell to accompany me, and it was rather a relief than otherwise,
that he was prevailed upon to remain quietly on board.
On reaching Hiram Bingham`'s, I found him also unwell with a similar attack of cold,
and unable to act the part of interpreter for me; but he had provided Doctor Judd,
the physician to the mission, who had studied the language,
and at one time was intended for an ordained preacher in the establishment:
on this head I was satisfied, if I should find occasion for an interpreter.
A missionary from Hawaii, now here, was to supply the place of Hiram Bingham.

When going into the meeting, I felt a poor creature indeed, now entirely companionless,
and in the midst of strangers: I was bowed down before the Lord,
who comforted and strengthened my heart; and I felt resigned and willing,
and in degree prepared, when the first proper interval offered, to stand up.
I had not spoken to the stranger about to officiate for Hiram Bingham,
previously to the meeting; but just at the time when he was about to commence his sermon,
I got up, and with some difficulty waded through a dense body of the natives,
who were seated or squatted so thickly on the floor in front of me,
that I could scarcely avoid treading on some of them:
I took a station in front of the pulpit upon the ground floor;
and Doctor Judd observing this movement, came and stood beside me.
We remained in silence,
with the eyes of more than two thousand five hundred people fixed upon us,
until my mouth was opened to declare the cause of my again standing before them;
which was, that I might be found in the counsel of the Divine will,
in order that the fulness of the blessing of the gospel might be theirs.
That "`Christ might dwell in their hearts by faith;
that they being rooted and grounded in love,
might be able to comprehend with all saints what is the breadth, and length, and depth,
and height; and to know the love of Christ, which passes knowledge;
that they might be filled with all the fulness of God.`"
That it was not to the high and the mighty that the gospel message was sent formerly,
neither is it now; but to the "`poor in spirit`" the gospel was,
and is still preached;--and blessed are they;--"`blessed are the poor in spirit,
for theirs is the kingdom of heaven:`"--these shall be satisfied with favour;
they shall be filled with good things, but the rich and the full are sent empty away.

For upwards of an hour I had to declare the glad
tidings of the glorious gospel among them;
the people were very solid and attentive:
they were encouraged "`to press towards the mark for the prize
of the high calling of God in Christ Jesus:`"--the Lord`'s love
flowed richly in my heart towards these people.
The meeting was unusually large, owing, perhaps,
to the governors of three distant islands being there, namely, of Hawaii, Maui,
and Tauai.
A number of strangers came about me when the meeting separated; and Kuakini,
the governor of Hawaii,
(well known by the name of John Adams,) who speaks tolerable English,
wanted to know when I should come to his island.
I could only say that I was not my own master;
but it was not improbable that I should visit Hawaii before leaving the group.
I got off from them as soon as I could with propriety,
as the way seemed now fully open before me to appoint a
public meeting for the whites and halfcastes,
to be held at the Mariners`' Chapel in the evening.

Repaired to the shore before dark, in time to be in readiness for the meeting;
but the approach of a storm, the thunder and lightning having commenced,
it is probable prevented some from being there,
as it was not so large as the one held the preceding week,
but not the less comfortable on that account.
After sitting long in silence, I had to express a desire,
which had quickened upon my mind shortly after taking my seat,
that it might not be said of us as of a people formerly,
--"`This people draws nigh unto me with their mouth,
and honours me with their lips,
but their heart is far from me;`" and to explain the
necessity of drawing nigh and waiting upon the Lord,
and of persevering to wrestle for that spiritual blessing, which makes truly rich,
and whereunto no sorrow is added.
We again dropped into silence, during which, only one person went out.
In a short time afterwards, I stood up with those expressions of the apostle,
"`We through the Spirit wait for the hope of
righteousness by faith;`" by which we are justified,
and have peace with God the Father, through the Son,
our Lord and Saviour Jesus Christ;--even that peace,
which the world with all its delusions cannot give; and, blessed be the name of the Lord,
of Israel`'s God, neither can it take one particle of it away.

I had largely to speak of the beauty of true spiritual worship,
and also of the life and immortality which are brought to light by the gospel;
and of the possibility of the day of visitation passing over unheeded,
and the things which belong to the soul`'s
eternal peace being forever hidden from our eyes,
for lack of walking in the light of the Lord Jesus: it was a solemn, comfortable meeting,
yielding peace.
When it broke up the rain fell in torrents, and the streets, in some places,
were literally running in sheets of water: but for the friendly assistance of a stranger,
who procured a lantern, we could not easily have found our way to the sea-side,
so dark was the night.
The rain fell in such quantities, that the water was about our feet in the boat,
although she had been once emptied out after leaving the vessel.
The captain only was with me;
and I was thankful that my Charles had not ventured on shore that night.

12th.--In the morning, a native teacher called on board, named Tootee,
(i.e. Cookee,) after Captain Cook.
He was born at Huahine, and with another teacher since deceased,
was sent to these islands several years ago: there was something agreeable about him;
and we find that he is well spoken of by those who know him.

13th.--This forenoon, Kuakini, the governor of the island of Hawaii, came on board;
he was proceeding homeward in his own schooner,
but having to convey the princess Harrietta Nahienaena, the king`'s sister,
to the island of Maui, was detained until her arrival on board his vessel,
which was standing off and on, while he paid us a visit during the interval,
to invite us to the shores of Hawaii.
We had a good opportunity to show him what must inevitably be the dreadful result,
if measures are not speedily taken to check the desolating scourge of rum,
with which the American ships are deluging these much to be pitied islanders.
He is an intelligent person, and speaks very fair English,
considering it has been acquired only by interaction with the
crews of the British and American whaling vessels.
He said that the use of rum was prohibited at Hawaii among the natives,
and that it was only in the hands of foreigners.
We told him that the foreigners would be the certain ruin of these islands,
if the government did not lay such a tax upon all spirit dealers,
as would place this curse of the human race beyond the reach of the natives,
and render it not worth any person`'s while to continue the sale of it.
They have tried, he said, to abolish it here, (Oahu,) but could not do it,--adding,
"`the king is fond of it;`"--at the same time intimating that the princess not being
ready this morning was owing to the king`'s being intoxicated last night.
He said, the merchants here,
(who are all Americans,) take good care to supply the king with money,
and every other thing that he needs:
by this plan they have him so completely in their hands, as to succeed in persuading him,
that it is to the interest of the islands to allow the free use of spirits.
Kuakini is about the largest man we have met with;
but he seems to possess very little bodily strength in proportion to his ponderous bulk,
and has very little use of his limbs: he is forty-five years of age.
He could not climb up our little vessel`'s side without the assistance of two men,
and a descent into the cabin was quite a serious fatigue:
the passage down was certainly not sufficiently wide to
allow him to make use of his unwieldly legs and arms.
He told us his sight was failing, asking for a pair of spectacles,
which were immediately handed to him:
although very coarse articles and rusty from the dampness of the vessel,
he seemed glad to have them.
He would have stopped while some fish was prepared;
but the arrival of his passenger summoned him
away as quickly as he was capable of moving.

Yesterday, arrived the Thetis schooner, from Ascension Island.
This vessel has had a mutiny on board:
her captain and several of the crew were murdered by one man in the night, a Bengalee;
who himself sprung overboard at last, and was shot by one of the surviving sailors.
They suffered much from the natives, or rather from the runaway sailors,
at Strong`'s Island, one of the Pescadores.

First Month, 14th.--In the evening met with an interesting young Spaniard and his sister,
the wife of an English merchant of California.
This young man had been in the United States, and spoke good English;
but his sister knew only the Spanish language.
In the course of conversation, I mentioned having some books on board in Spanish,
and proposed to furnish some of them;
at which they seemed grateful and gladly accepted the offer.

17th.--Yesterday visited the school for half-white girls,
it being the anniversary of its establishment three years ago.
To teach this class of children is a laudable undertaking,
and highly needful on their behalf.
These children are of a description calculated to do
either much good or much harm upon these islands,
from their knowledge of the native language, derived from the mother`'s side: this,
in conjunction with a moral education,
would tend to assist in the civilization of the people at large;
at the same time there is much reason to fear
their assuming a superiority over the natives,
from their nearness of kin to Europeans or Americans from whom they have sprung.
Although little to be proud of on this account,
yet it mostly happens that they abound in pride and haughtiness;
and the fathers of such being for the most part runaway sailors, rum-sellers,
or other profligate characters, their offspring, from earliest age,
are accustomed to scenes of vice and wickedness;
the effects of which are not likely to be shaken off as they grow up,
but rather to render them highly injurious to the natives around them,
by their unrestrained, immoral, and base conduct and example.
Not the least difficulty to be surmounted,
is that of finding suitable employment to keep them out of mischief,
having been trained in habits of sloth and idleness,
and ignorance of every domestic and useful occupation whatever.
We have had a visit from the surgeon of the British whaler Corsair,
lately arrived from Ascension Isle.
The Corsair was lost upon the Nautilus Reef, near one of the Kingsmill group.
This young man, with five seamen, were saved in a whale-boat:
after enduring great hardship for lack of food,
they were favoured at last to reach the isle of Ascension, in the North Pacific.
The Corsair was fitting out in the West India dock,
at the time the Henry Freeling was equipping in the City Canal, in 1833.

18th. (First day.)--Having no engagement on shore,
the day was spent on board with our own people.
In the afternoon, two seamen from the Ganymede, of London,
on her way to the Hudson`'s Bay Company`'s settlement on the Columbia River,
north-west coast of America, attended with our men.
I had a few words to utter in testimony to the light of Christ Jesus,
which shines in every heart: and the necessity of bringing our thoughts, words,
and actions to it.
Before leaving our vessel, these men were furnished with tracts of different kinds.

24th.--In the course of the week,
a prospect of holding another public meeting with the
foreigners and half-whites in the Mariners`' Chapel,
has at intervals crossed my mind; and yesterday afternoon,
accidentally meeting with the missionary from the Columbia River,
(at present here on a visit,) who occasionally officiates as pastor,
he asked me in plain terms, if I would occupy the Mariners`' Chapel next First day,
either in the morning, afternoon, or evening.
I told him that I had thought a little about it;
but it seemed to pass away at the moment, and nothing was fixed,
although I was not quite clear of the subject.
Today it seemed best for me to see this young man again, and to tell him,
if right for me to do so,
I would send him a written notice to be read at the close of the morning meeting,
which would serve as an invitation to all present to attend a meeting in the evening,
held according to the practice of Friends.

26th.--On Seventh day evening,
having prepared written notices of the intended meeting before-mentioned,
in readiness for distribution on First day morning,
and finding freedom to circulate them when the day opened,
Captain Keen was commissioned to do the needful,
in order to spread the information that a
meeting for worship would be held in the evening,
after the usual manner of our Society.
In the course of the day our crew assembled for devotional purposes.
The weight of the prospect spread upon my mind, was as a heavy burden through the day,
raising in me strong cries to Him from whom only comes help and strength,
for ability to do His will, and to exalt His ever great and excellent name.
We repaired in time to the shore, and were the first that took seats in the meeting.
The people gathered slowly, but with quietness;
and the number was probably as large as at any time previously.
After a considerable time of silence, beyond all expectation solid,
I had to supplicate Him who only has immortality,
and dwelling in the light;--that everything in us that
stood opposed to His righteous principle of light,
life, and love, might be shaken and removed out of the way;
that that only which cannot be shaken may remain,
--to the exaltation of His own great name,
and the establishment of the kingdom of Christ Jesus, which shall never have an end.
Afterwards the people sat as if accustomed to silence.
The first expressions with which the silence was broken,
were;--As "`no man can save his brother,
or give to God a ransom for his soul`" so no man can perform
for another the solemn act of worshipping the Almighty Creator.
If I were to speak to you, or read to you for an hour,
it would only be an act between a man and his fellow creatures, and not worship;
for worship can only be performed between a man and his Maker, who is a Spirit.
"`God is a Spirit: and they that worship Him,
must worship Him in spirit and in truth.`"--"`The Father seeks
such to worship Him.`"--"`Our fathers worshipped in this
mountain`" said the woman of Samaria to our condescending Lord;
"`and you say, that in Jerusalem is the place where men ought to worship.
Jesus says unto her, Woman, believe me, the hour comes,
when you shall neither in this mountain, nor yet at Jerusalem, worship the Father.
You worship what you do not know: we know what we worship; for salvation is of the Jews.
But the hour comes, and now is,
when the true worshippers shall worship the Father in spirit and in truth;
for the Father seeks such to worship Him.`"
This is the will of the Father, that we should hear His beloved Son,
Christ Jesus:--"`I am the light of the world,`" said He,
"`he that follows me shall not walk in darkness, but shall have the light of life.`"
The same eternal Power who said, "`Let there be light, and there was light;`"--even God,
who commanded the light to shine out of darkness, has shined in our hearts,
to give us the light of the knowledge of His own glory, in the face of Christ Jesus:
it is to this light that all men must be turned,
and to which all men must come if they are saved.
This is the condemnation, that light is come into the world,
and men are not willing to believe in it,
because it makes manifest their dark and sinful state:
they love darkness rather than light, because their deeds are evil.
"`For every one that does evil hates the light, neither comes to it,
lest his deeds should be reproved.`"
Such continue under the power of Satan; "`but he that does truth comes to the light,
that his deeds may be made manifest,
that they are wrought in God;`"--he is turned from darkness to light,
and from the power of Satan unto God:--he receives forgiveness of sins,
and inheritance among them which are sanctified by faith which is in Christ Jesus,
the life and light of men.
The people were very attentive,
and such a solemn stillness prevailed the greatest part of the time,
that if they could not have been seen upon their seats,
it would have been difficult to ascertain whether any persons were present.
It was the Lord`'s doing; and as is His name, so is His praise forever!

27th.--Yesterday had a satisfactory visit from the
Canadian missionary stationed on the Columbia river,
north-west coast of America.
He was desirous of information respecting the principles of our religious Society,
and of possessing a Book of Extracts;
from having only one on board the Henry Freeling of the new edition,
a copy of the old edition was given him, with a copy of Bates`'s Doctrines, etc.
I look forward to furnishing him with some religious tracts,
which may be useful to the North American Indians, among whom a mission is established;
although the result is hopeless indeed,
as these poor people are too often paid in rum by the trading vessels,
both American and British, for their beaver skins, etc.; which, with other causes,
is fast sweeping from the face of the earth this injured race of mankind.
Muskets and gunpowder are among the principal articles of barter goods taken to them.

This afternoon I received a letter from the senior missionary here,
of which the following extract is part:

"`I am happy to inform you that today we commence a series of
meetings with the people for their spiritual benefit.
The hours of service for five days will be sun-rise, ten o`'clock a.m., two o`'clock p.m.,
four o`'clock p.m., in the natives`' chapel;
and a meeting at one of our houses at half-past seven o`'clock p.m. Probably
there will be present some hundreds of the people more than usual,
possibly a thousand: perhaps our chapel will be filled:
several of my brethren will be present from the other stations on this island.
If you will favour us with your assistance tomorrow at ten, or at four o`'clock,
I will gladly interpret for you, Providence permitting.
Shall be happy to see you and your son at any of our meetings,--the field is white.`"

I called the same evening at the writer`'s house; and having considered the subject,
acknowledged the receipt of his letter,
and told him that I had felt nothing upon my mind towards the meetings tomorrow,
which he had mentioned.
All that seemed safe for me to say was,
that I had a desire to be present when the largest body
of the people was collected together.
It appeared to me that the forenoon of the following
First day would be the right time for me to be there,
which was at last fully agreed upon.
While at this house, five marriages were solemnized at seven o`'clock p.m.,
in the room where we sat.
This ceremony to four couples was performed in the native language,
and in English to the fifth, the man being an American negro.
One thousand five hundred and forty-six marriages have
taken place upon these islands within the last year.
It is hoped that the institution of regular marriage will be of use to this people;
but it is greatly to be feared, from what the missionary himself said,
that their solemn vows and promises are soon forgotten.

First Month, 30th.--On Fifth day our meeting was held as usual.
Yesterday employed in selecting various books and lessons for the use of schools.
For the last two or three days,
the prospect before me of attending the native
meeting has been more formidable than usual,
from the apprehension, lest I should be found running, if not altogether unsent,
without an evidence sufficiently strong, that it is my duty to be there.
I have endeavoured to keep close to the exercise, though in much conflict of mind.

31st. (First day.)--Had an almost sleepless night,
but towards morning the way seemed to open with
relieving clearness for me to attend the native meeting:
landed in due time, and called upon the missionary, who accompanied us to the meeting.
When on the way,
Hiram Bingham asked whether I would prefer
speaking to the people before the service began,
or after it was over.
This question was so unexpected, that I replied without proper consideration,
that I had rather wait, I meant in silence before the Lord;
but he supposed until their service was gone through,
and of course matters went on in their usual way.
I felt regret afterwards that I had not more fully entered into explanation at the moment.
It was afterwards proposed by Hiram Bingham that I should go
into the pulpit with himself and another missionary,
saying,
that the crowd would be so great that he should
not be heard if he interpreted from the floor.
This proposal was declined at first; but on getting into the place,
I was convinced that if I did not go then,
it would scarcely be possible afterwards should it be needful,
as the floor was already almost a solid mass of people;
so we proceeded accordingly without delay.
I sat as one who had the sentence of death in himself, and felt so much depressed,
that at one time I thought of telling Hiram Bingham that I did
not expect to have any thing to say to the people,
but was withheld from doing so.
In addition to their usual services on these occasions, a child was baptized,
and it seemed long before all was finished, and general silence prevailed.
After a short interval I stood up, when Hiram Bingham exhorted the people to stillness.
I remarked on taking up the time of the meeting, which had already sat long;
but that I was induced to stand before them once more to
communicate whatever might be given me on the occasion.
The attention of the people seemed now fully arrested,
and after a solemn pause it was with me to express the
encouraging language of the Lord`'s prophet,--"`Arise,
shine; your light is come, and the glory of the Lord is risen upon you.
For behold, the darkness shall cover the earth, and gross darkness the people:
but the Lord shall arise upon you and his glory shall be seen upon you.`"
Thus was announced by holy inspiration, the light of that glorious gospel morning,
then preparing to dawn upon the benighted regions of the earth,
to dispel the mists of darkness from the mind of man;
that sin should no longer have dominion over the human race,
but that mercy and truth should meet together, and love, and joy,
and peace through righteousness,
should prevail from the river to the uttermost parts of the earth:
that as sin has reigned unto death, so now might grace reign through righteousness,
unto eternal life, by Jesus Christ our Lord.
There is no other way by which mankind can participate in the
life and immortality that are brought to light by the gospel,
than that of believing in Christ Jesus, and turning to the light of His Holy Spirit,
which shines in every heart.
I was sure that these beloved people (telling
them so) were no strangers to the name of Christ:
but that the bare name is not enough; I wanted them to become acquainted with His power,
to save them from their sins: without this He would be no Saviour of theirs.
The number of people present was computed at four thousand and upwards,
and being placed above them, the heat was almost insupportable:
they stood in crowds outside of the six double doors,
and about a window that was open at the back of the pulpit.
The building is one hundred and ninety-six feet long, and sixty-eight feet wide, and was,
to all appearance, as full as the people could pack together.
The mercy of the Lord is from everlasting to everlasting,
and His truth to all generations of them that fear and love Him.
We sat a few minutes with Hiram Bingham`'s family after the meeting concluded;
and then returned on board to our own crew,
who were assembled in the cabin in the afternoon.

Second Month 9th.--While at the Consul`'s yesterday evening,
with eight or nine other persons,
and a general conversation going forward in which I had taken little or no share,
I felt my heart attracted by that power, at whose approach the earth is silent;
and abiding under it, I thought that something might arise towards the company present,
but in that was mistaken.
Remaining for some time under sensible weakness and fear,
a public meeting next First day forenoon,
at the Mariners`' Chapel was presented to the view of my mind;
to which I was favoured to feel resigned and willing,
keeping the matter closely to myself.

13th--Not able to take any exercise on shore since last Second day,
until yesterday evening, on account of the extreme wetness of the weather,
it being the rainy season in this region.
In the course of our walk,
called upon one of the missionaries for the translation of an
article relative to the arrival of the Henry Freeling at Oahu,
that had appeared in the Hawaiian Teacher, a semi-monthly periodical,
printed at the mission press, and edited by a regularly ordained minister.
When coming away, without any previous hint on my part,
he kindly proposed that I should have the Mariners`' Chapel tomorrow,
(First day,) either in the forenoon or evening, or both.
I parted from him with saying, I should turn the matter over and let him know,
in order that timely notice might be given, if the meeting was of my appointing,
so that the people might be fully aware of its being
held according to the established practice of Friends:
but I thought it well to wait a further time before giving a decided answer,
lest it should not come to pass;
although the prospect had been again and again before me early and late, at intervals,
since I first got sight of it.

This morning, being Seventh day,
it seemed best for me to move forward by having notices prepared,
that information might be well spread in good time,
both on the shore and on board of the shipping.
While these were preparing, I went on shore to the missionary,
and told him that I believed it safest for me to hold a meeting tomorrow in the forenoon:
the way was now thoroughly cleared for the distribution of the notices;
and I endeavoured to dwell under the weight of
the responsibility of this important engagement,
which seemed fastened upon me as a knot not easily untied.
My mind is often turned to the Lord with secret cries for help:
greatly do I desire that the noble cause of Truth may not be tarnished in my hands;
but that His ever great and adorable name may be exalted,
and the people turned to the power of the Holy Spirit of the Lord Jesus,
and the creature laid low and kept in dependence on Him alone;
that the work and the praise may be His, unto whom the kingdom, and the power,
and the glory, forever belong.
In the afternoon spent some time with the manager of the
book-binding department of the American printing establishment:
his wife superintends a school of the native children,
and with her husband appears to move in much plainness and simplicity.

15th.--After a restless night,
landed in good time yesterday morning in readiness for the appointed meeting;
which was well attended by the residents and strangers from the shipping.
After a time of silence, it was with me to revive among them the Divine command,
"`Be still,
and know that I am God;`" and that this command must be obeyed before
we can come to the blessed knowledge of the only true God,
and his Son Jesus Christ,
whom to know is life eternal:--desiring that we might humble ourselves before Him,
and in the silence of all flesh "`be still`" peradventure He would
graciously condescend to overshadow us with his heavenly presence.
After recommending that we should endeavour to settle down in
stillness of mind before the God of the spirits of all flesh,
I again resumed my seat.
A comforting solemnity soon spread over us, under the precious covering of which we sat,
until the time was come for my standing up again, when it seemed increasingly to prevail.
I reminded them of the expressions of those formerly,
who were struck with the display of the Divine power of the Saviour of the
world when personally upon earth,--"`What manner of man is this,
that even the winds and the sea obey Him!`" and that
the solemnity then so evident was not at our command,
but came from Him, unto whom all power in heaven and earth is given.
Man cannot cause it: has he "`commanded the morning since his days,
or caused the day-spring to know his place? No, verily,
no more than the leopard can change his spots,
and the Ethiopian his skin;`"--it is in the power of Him only,
who "`declares unto man what is his thought,`" to do this.
We must all pass through the great work of regeneration,
before the kingdom can be entered;
it is wrought in the heart through the faith of the operation of God,
who raised from the dead our Lord Jesus, that great Shepherd of the sheep; by whom,
and with whom, we must also rise from death unto life: but before we can rise with Him,
we must be willing to suffer with Him;
we must know what it is to be crucified with Him,--the lust of the eyes,
and the pride of life, totally disregarded and set at naught.
But these things, which war against the soul, must be removed,
before we can know and be admitted into the fellowship of His sufferings;
and we must witness the power of his resurrection, before we can adopt for ourselves,
from heart-felt living knowledge,
the apostolic language of--"`I am crucified with Christ; nevertheless I live, yet not I,
but Christ lives in me: and the life which I now live in the flesh,
I live by the faith of the Son of God, who loved me, and gave himself for me.`"
There is no obtaining and wearing the crown, but by the way of the cross:
we must be willing to suffer with our suffering Lord;
and it is only such as suffer with him, that shall reign with Him in glory.
We must be willing to bring our deeds to the light of the Holy Spirit of the Lord Jesus,
which shines in every heart, and to bear the indignation of the Lord,
because we have sinned against him;--to sit alone and keep silence,
ashamed and confounded, as in the dust, because of the reproach of our youth:
and it is only while we have the light, that we can thus bring our deeds to it,
and walk in it.
He that walks in darkness knows not where he goes: and if by neglect and disobedience,
the light in us be darkness, how great is that darkness!
We may sin out the day of our visitation; then the candle of the Lord is withdrawn,
or put out; for He has declared, "`My Spirit shall not always strive with man.`"
These visitations are the merciful tokens of the Father`'s love,
to draw man to the Holy Spirit of His beloved Son in the heart,
"`the life and light of men;`" unto whom, although shining in all,
none of us can come in our own will and strength,
or by any inherent righteousness of our own.
"`No man comes unto me,`" said Christ, "`except my Father which has sent me draw him;
and I will raise him up at the last day.`"
As no man comes to the Son but by the Father,
so no man comes to the Father but by the Son; according to his word,
"`No man comes to the Father but by me.`"
By grace are we saved, and that not of ourselves;
it is through the boundless mercy and everlasting love of God in Jesus Christ.
After this manner was I strengthened to declare
that lovingkindness which is better than life,
and to testify of that grace, which comes by Jesus Christ.
The meeting held longer than usual, but ended well:
I trust the Lord magnified his own power in the hearts of some;
who is blessed and worthy, and God over all forever.
Most of the missionary families were present.

16th.--Visited the school for native girls,
under the superintendence of a missionary`'s wife; which,
for good order and general quietness,
is the best conducted establishment of the kind we have yet seen.
For some time after the formation of this school,
the children could not be prevailed upon to go forward with the regular duties,
without an adopted child of the queen`'s led the way, and had the preference shown to her.
When ordered to break up at noon, or in the afternoon, they would all retain their seats;
and when the reason was asked for this, would say,
"`Let the queen go first;`" although she was a mere shrimp, in size,
compared with many of the other children, and not more than six years old.
The school-mistress has taken much pains to abolish
such an unnecessary and invidious distinction,
and has not hesitated to punish this child when in fault, like the other children,
without showing any partiality because of her patronage;
for a time this gave great offence,
but by firmness and steady perseverance the difficulty was at last completely surmounted.
Most of the children have now got the better of yielding such undue servility,
although it is said that some of the timid still consider this child`'s word as law.
