== Chapter XXIX.

[.chapter-synopsis]
* Oahu
* Annual Meeting of the Missionaries
* Meeting with the Members of the Mission
* Addressed by the Senior Missionary
* Sail For Tauai
* Native Meeting at Koloa
* Waimea
* Oppression of the Natives
* Final Departure from the Sandwich Islands

Oahu, Sixth Month 1st.--Early in the forenoon,
the British Consul came on board in a whale-boat, and conveyed us to the shore,
as our own small boat was in such a shattered condition from exposure to the sun,
as scarcely to be fit to trust to for so considerable a distance,
as from our present anchorage without the reefs, to the town of Honolulu.
After landing, proceeded to the missionary establishment,
and had an interview with the three missionaries from the island of Tauai,
about ninety miles to leeward of Oahu,
who had arrived yesterday in the Missionary Packet.
Our situation was fully explained to them, and it was I believe understood,
that unless one of them would kindly accompany us to that island,
our making an attempt to visit the people would be useless.
We remained on shore until near dark,
but were favoured to reach the vessel without difficulty,
she having displayed a light as a beacon to guide us.
While on shore we were informed that the neighbourhood of New Zealand had been visited,
in the First Month last, with an awful tempest,
in which much damage had been done to the shipping; that Captain Russel,
of the American ship Zone, with whom we were personally acquainted,
and to whom we were much attached, in endeavouring to save one of the sailors,
had himself been washed overboard and lost.
We met with him last year, at the Society Isle Huahine,
and were much pleased with his serious and steady deportment.
Several books and tracts were furnished for the use of the crew of his vessel,
by whom he was much beloved.
We were informed by the missionary family,
that he had been much interested at the meeting that was held there with the natives,
which he had attended.
He had determined that that should be his last voyage, and so it has proved.
I humbly trust he has safely entered a haven of eternal rest;
where storm and tempest cannot come, nor pain nor sorrow find place.

2nd.--During most of the day I had to struggle with discouraging circumstances;
all perhaps needful, to keep the creature in its proper place.
In the afternoon, landed with a view to ascertain from Hiram Bingham,
whether one of the Tauai missionaries had consented to
accompany us to that island as interpreter.
Hiram Bingham said an adjourned annual meeting was about to assemble,
and it would afford a good opportunity of getting to
know what had transpired on that subject.
The bell soon rang, and we repaired to the meeting.
At a vacant opportunity the subject was brought forward by Hiram Bingham,
but nothing came of it, as several of the parties were absent.
I was afterwards informed that one of the Hawaii
missionaries was kindly disposed to accompany us,
which I rather viewed with regret,
from being aware that he would expect to be brought back again by our vessel.
Our suspense was at last relieved by a proposition from
one of the Tauai missionaries to go with us,
and an assurance that he would be ready to depart
before the final conclusion of the annual meeting.
Although this might occasion ten or twelve days`' delay,
yet the saving of time would be considerable, when compared with the first offer,
which would involve our having to return again to Oahu, against a relentless trade-wind,
the effect of which had been fully tried.
The circumstances of the case in all its bearings considered,
it seemed prudent to take the Henry Freeling again into harbour,
rather than risk her any longer outside the reefs.
It is no small trial to be thus delayed;
but as it is not to gratify self that we linger on the way, the Lord knows,
I trust we shall yet be able to redeem this apparent loss of time,
and be favoured to improve the future to his praise.

Although the prospect which had been spread before the view of my mind,
for some weeks previous to our return to Honolulu,
of seeing the whole of the missionaries and their
families when collected at their general meeting,
still remained strongly with me;
yet the time did not seem come for me to take any steps to accomplish the same,
until we had ascertained that the whole of them had arrived.
Those who were present at the opening of this general meeting,
concluded I was detained until an interpreter
was ready to accompany us to the island of Tauai,
and in a very kind and brotherly manner invited us to
attend the several sittings of that meeting.
The manner in which the affairs of the mission to these islands is conducted,
could not fail to excite much interest in our minds;
and although well aware that in our attendance at the meetings we
should be subjected to witness many things that we could not unite in,
yet, as they had always allowed us to do that which was most easy to ourselves,
without a single remonstrance or the slightest
appearance of dissatisfaction on their part,
I was not satisfied to let such an opportunity pass away, however painful it might prove,
without availing ourselves of it: at the same time,
the unmortified part would gladly have been excused altogether.

3rd.--This morning, one of the Tauai missionaries came on board to say,
that he hoped to have his business in such a state of forwardness,
as to enable him to return to that island before
the final conclusion of the general meeting.
A light breeze having sprung up from the southward,
soon after breakfast the Henry Freeling got under weigh, and made sail for the harbour;
before ten o`'clock she anchored off the fort of Honolulu.
Being desirous of going to the mission-station at Eva next First day,
application was made to know whether a missionary would
return there to meet the natives on that day;
but it appeared that the whole of them will remain here,
on account of its being the usual time for the celebration of what is
called the '`Lord`'s Supper.`' We were informed that so few of the
natives would remain within the compass of their own station,
that a visit would be better deferred until next week.
In the evening attended one of the general meetings,
and had to wade through a painful season therein.

4th.--The leak before alluded to in our vessel still continuing,
although considerably lessened since our getting her into still water,
it was deemed prudent that such parts of her should be well caulked,
which were supposed to be the cause of her requiring so much pumping;
while at the same time the needful repairs of the sails and rigging were going forward,
in the expectation of again crossing the Equator, when altogether clear of these islands.

Sixth Month 5th. (First day.)--Remained on board through the day with our own people.
In the evening repaired to the Mariners`' place of worship,
where a time of suffering was my lot.

10th.--Since First day my time has been pretty fully occupied in attending
the different sittings of the general meeting of the members of the mission,
as they came in course, and in procuring the supplies needful for the vessel,
in exchange for such articles of barter remaining in our possession,
as were most in demand.
Having deferred going to Eva last week, as no interpreter could be procured,
today I went in search of the missionary belonging to that district,
and found that he had procured a large canoe,
with the intention of setting forward tomorrow morning at the proper time of the tide,
to enable us to pass in safety over the shallow places near the shore,
and thus preclude the necessity of our being exposed to the swell outside of the reef.

11th.--In the afternoon left the vessel and proceeded towards the Pearl river,
at the head of which lies the station of Eva;
we were favoured to reach it in less than five hours,
though our progress was for some time impeded by the giving way of the outrigger;
but the natives soon sprung overboard and put it in order again.
At this place, a prayer-meeting has been instituted among the natives,
and sixteen of them collected in the evening at the house where we lodged:
this station has been but recently organized.

12th. (First day.)--Having retired early to rest last evening,
we were seated at the breakfast table by six o`'clock this morning.
The horn was blown in good time to collect the people,
and at ten o`'clock we met about seven hundred of them in a shed open on every side,
there being as yet no place of worship erected.
I had largely to declare among them the glad tidings of the gospel,
turning their attention, as ability was afforded,
to the just witness for God in every heart.
Although under feelings of great weakness as to myself,
yet the deportment of the people afforded an encouraging
evidence that the great Master was near to own the work.
The afternoon meeting was not quite so numerously attended,
but it proved even more solid than that in the morning.
In this meeting I had to turn them from the teachings of men,
to that power which alone can save.
For "`none of them can by any means redeem his brother,
nor give to God a ransom for him.`"
Hut the Almighty Father of love and mercy has amply provided
for the salvation of all mankind by his Son Jesus Christ,
who came into the world to save sinners; "`he was made sin for us, who knew no sin,
that we might be made the righteousness of God
in Him who died to obtain for us the Holy Spirit,
that we might live and come unto God by Him.
The countenances of many of these dear people, spoke louder than words what they felt:
weakness and poverty were my close companions;
yet I was favoured with peaceful tranquillity of mind.

We left Eva at three o`'clock this morning, the 13th instant,
and got well on our way an hour before day-light, through the narrow rushy channel,
which in places is overhung by the spreading boughs of large trees.
Although there was very little wind, we were annoyed by the swell of the Pacific;
but were favoured to reach the Henry Freeling by eight o`'clock.
It had been to me a time of favour,
and a day to be remembered among the memorable ones of my chequered life;
and the more so, when on looking back,
it was discovered according to the time of England,
to be a date on which I had more than once had to record the tender mercies of the Lord,
for signal and crowning loving-kindness bestowed upon a poor unworthy creature.
In the course of the day it was ascertained that the last of the missionary
families had arrived to attend the general meeting in a small vessel from Wairuku;
and that the other family residing at Waimea, on the island of Hawaii,
were prevented from attending by an increase of family since we were at their dwelling.
The time was now fully come for me to request an opportunity
with the whole of the members of the mission;
and in the evening I stated my case to the senior missionary,
who appeared quite disposed to make way for it,
by consulting his brethren at a meeting then about to collect, to which we repaired.
Most of two hours elapsed before a suitable opportunity
presented to spread the subject before the meeting;
but when once understood, my request was immediately granted,
and the next evening was fixed for us to meet together.

14th.--Employed on board through the day.
In the evening, called upon Hiram Bingham who accompanied us to the meeting.
I was shown into the moderator`'s seat, and the company was soon gathered together.
After some time in silence, it was with me simply to state,
that on leaving Honolulu a few weeks ago, I had no expectation of returning to it again;
but some time afterwards I found that I should not be clear of these parts,
without endeavouring to see the whole of the missionary
establishment in its collected capacity.
At that time it seemed difficult to comprehend how it would be brought about,
but I felt a willingness and resignation on my part towards
its accomplishment:--He that causes his wind to blow,
and the waters flow, directed our steps and brought it to pass.
As it is probable, (I continued) that all are present who will be on the occasion,
I would suggest that we now endeavour to sink down in humble reverence of soul
before "`the Judge of all the earth,`" to wait for the counsel of His will;
and, if graciously favoured therewith, endeavour to do it,
to his praise and to his glory.
The meeting then settled down in silence and remained
for a considerable time under a solemn covering;
until I had to speak of the order in the church of Christ,
and of the preparation of heart which every member must
pass through by the operation of the Holy Spirit,
before he can become a part of this glorious body, which is without spot or wrinkle;
and the necessity of our individually knowing for
ourselves the hope of our high and holy calling.
It was afterwards with me to state,
the opportunity I had had of seeing them in their different, distant,
solitary and secluded allotments,
and of witnessing their patient endeavours to
promote the work in which they were engaged.
Having myself dwelt amongst those whose language I could not understand,
I was the better able to feel for them on this account with brotherly sympathy;
and I was no stranger to the many obstacles thrown in their way,
and the numerous difficulties that they had to encounter;
but their only refuge was Christ Jesus the Lord; if He was with them,
they had nothing to fear.
I had no desire to discourage any,
but while beholding the vast importance of the work they had taken in hand,
I was ready to tremble at the awful weight of the responsibility which rested upon them.
It was not for me to judge whether they had been called and chosen for the work, or not.
I knew that our Lord had declared,
"`this gospel of the kingdom shall be preached
in all the world for a witness unto all nations;
and then shall the end come.`"
Their being called or not called to the work, rested with themselves.
It is, however, possible for a man to have a zeal for God,
but not according to knowledge;
and while earnestly endeavouring to lend a hand of help to others,
he may be neglecting the all-important duty of
coming to the knowledge of the Lord for himself.
I believed that many of them were truly and earnestly
desirous to know the Lord for themselves,
and I wished to encourage such to follow on to know Him: to seek Him,
and not to rest contented, until they found Him who said, "`seek and you shall find.`"
"`The Lord whom you seek,
shall suddenly come to His temple,--even the messenger of the covenant,
whom you delight in: behold, He shall come, said the Lord of Hosts.
But who may abide the day of his coming, and who shall stand when he appears!`"
Nothing that is of man, or in man,--that is earthly, sensual or unclean,
can stand before Him:
the heart must be cleansed and purified from every thing that defiles,
before it can become the temple of a holy, pure, and just God:
and none is sufficient for these things but He,
unto whom all power in heaven and earth is given; who, the prophet declares,
is "`like a refiner`'s fire, and like fuller`'s soap;
and He shall sit as a refiner and purifier of silver.`"
This heart-searching process we must all pass through:
and by yielding in meekness and submission to the baptizing operation thereof,
we shall in due time be given to know and to feel it to be the
"`messenger to prepare the way of the Lord`" before Him,
who will not dwell in the defiled temple of an unclean heart.
This ordeal all have to pass through in a greater or smaller degree,
before they come to that knowledge which is "`life
eternal,`"--even the knowledge of "`the only true God,
and Jesus Christ whom He has sent;`" who once visited
the earth in a body that was prepared for Him,
but who now visits by His Holy Spirit the heart of man:
who is indeed the heavenly messenger of the covenant, to all that seek him,
and delight in him, and whose coming is sure, because the Lord has promised.
But to those who are called and chosen to speak to others in the name of the Lord,
and to proclaim the glad tidings of that gospel
which "`is the power of God unto salvation,
to every one that believes,`" a larger portion
of the "`refiner`'s fire`" is often needful,
to purge them as gold and silver,
and prepare them for the great work of declaring "`the truth as it is
in Jesus,`" from their own blessed and sensible experience.
Just in proportion as the Lord`'s messengers are qualified and taught of Him,
when commissioned to go forth in his name,
may we expect that the people will be benefited: if our eyes are not first opened,
vain is the attempt to open the eyes of the blind, and turn them from darkness to light.
I was largely drawn forth to speak of the vast
importance of the work in which they had engaged,
and to arouse them to a sense of the responsibility it involved;
recommending them to take counsel of the Holy Spirit of the
Lord Jesus,--for the same shall judge us at the last day.
I had much to express to them in great plainness of speech,
under the overshadowing power of that love which makes not afraid;
reminding them of the many blessed seasons we had been permitted to witness together,
on the different islands,
when the Divine presence was as a crown and
diadem over those large assemblies of the people.
That "`faith which works by love,`" and the true supper of the Lord,
were also largely held up to their view.

15th.--Taking the necessary measures to prepare the vessel for sea.
In the evening met the whole of the missionary establishment again; when the senior,
on behalf of his brethren and himself, delivered an address,
on the subject of our visit to these islands;
in which he expressed their satisfaction in terms of applause, perhaps,
better forgotten by us, than remembered.
I was silent among them; but when the meeting broke up, I told the speaker,
I could have added, "`Not unto us,`" etc.

16th.--In the morning,
Charles and myself took an early opportunity of sitting
down together and were favoured to get into the quiet,
although all was bustle around us.
In the afternoon went on shore to settle our affairs,
and take leave of those with whom we had now been several months acquainted,
and for whom an earnest solicitude was felt.
Soon after returning on board, we embarked the baggage of Peter J. Gulick the missionary,
who had engaged to accompany us to the island of Tauai,
and who resides at the station of Koloa; he, his wife, and five children,
with the British Consul and the master of the free school, were our passengers.
The tradewind being fresh in our favour, and having our pilot '`SugarCane`' in readiness,
at five o`'clock we quitted the sheltering harbour of
Honolulu and stretched well into the offing,
in the hope of a permanent breeze at a good distance from the land.
Having only ninety-four miles to run,
an expectation was raised of our being in the
roads of Koloa by ten o`'clock the next morning,
but the wind forsook us before midnight,
and the island of Tauai was not discovered until too late for its accomplishment.

17th.--Got sight of the island at three o`'clock p.m., and at six o`'clock,
anchored in the open roadstead of Koloa,
just in time to land our passengers before the night came upon us.
Our vessel being observed approaching towards the roads,
a large canoe belonging to the missionary, was sent from the shore; which,
by making three journeys to and fro, succeeded in carrying the family,
and the major part of the baggage, in safety to the land.
Peter J. Gulick, with his wife and five children, remained on board,
until their luggage was sent off, and were at last placed in the canoe, which,
from the rolling of the vessel, and the incessant swells of the ocean, was no easy task.
The father having one of the young children to care for,
could not render his wife the slightest assistance: the child cried,
and he seemed very anxious lest an accident should happen: but his wife,
(while hanging suspended, watching for the right moment, when the canoe coming up,
borne by the swell,
should rise high enough for her to get foothold sufficient to induce
her to let go all hold of the vessel,) calmly cried out to him,
'`we must be patient, my dear.`' After two or three efforts she ventured,
and was received in the arms of two of the natives, and placed in tolerable security.
The youngest child,
which had for some time been held by the rough grasp of one of our sailors,
and unconscious of the risk to which it was exposed, was now handed, with smiling face,
over the side of our little reeling bark, in safety to its mother.
Although this appeared a hazardous enterprise, demanding the utmost care,
yet I believe they were all safe, as in the hollow of the Divine hand.

Sixth Month ]8th.--Landed on the island of Tauai,
and made our way to the missionary station.
Having made the needful arrangements relative to
meeting the people of this district tomorrow,
I left my certificates with Peter J. Gulick, who kindly undertook to convene the natives.
After visiting a sugar plantation in the neighbourhood conducted by Americans,
we returned on board.

19th. (First day.)--Repaired in good time to the shore,
having two miles to go to the native meeting in the heat of the sun.
By nine o`'clock, about eight hundred of the people were assembled in an open shed.
I was poor, and under feelings of great weakness amongst them;
but after reminding them of the solemn purpose for which we were brought together,
when the missionary had finished reading the translation of my certificates,
the way was opened for me largely to declare the
glad tidings of great joy to all that repent,
believe, and obey the gospel;
and to make a solemn appeal to the just witness for God in every heart.
I felt an earnest engagement to turn the attention of
these dear people to the Holy Spirit of the Lord Jesus,
which would discover to them "`all things that ever
they did,`" would set their sins in order before them,
and save them from sin with an everlasting salvation.
The people were very attentive, and under a solemn feeling the meeting broke up;
when they flocked round us in the usual manner.
I found that on account of the weak state of the health of the missionary,
no afternoon meeting was held; but the school was largely attended: on this occasion,
however, the people were again assembled for worship,
at three o`'clock p.m. I felt little on my mind towards them,
but was fearful of withholding that little,
and stood for a time under much discouragement; strength was, however,
in due time graciously afforded,--and I was enabled, to my admiration,
to set before the people "`life and death,
good and evil,`"--and to encourage them not to be overcome of evil,
but to overcome evil with good.
"`Let every one that names the name of Christ depart
from iniquity,`" and "`live unto Him who died for them,
and rose again;`" and who now by the grace of His Holy Spirit,
brings salvation to all men, has appeared unto all men, and teaches all men, etc.
Although the number present was less than in the morning,
yet the meeting was no less solemn.
Returned on board before dark to lessen the risk of staving the boat against the vessel,
as the constant swell of the sea renders access and egress at all times difficult,
but much less hazardous by day-light.

21st.--Yesterday and this morning pretty fully engaged in procuring vegetables,
Indian corn, etc.
In the afternoon went up to Koloa, to take leave of the missionary`'s family,
he himself being about to accompany us to Hanarei,
a station on the other side of the island.
Towards evening the needful supplies were obtained, and Peter J. Gulick,
Richard Charlton, (the Consul) with three or four natives were embarked.
At seven o`'clock we loosed from the roads,
and stretched away into the offing for the night, with a fresh gale,
but directly opposed to the course we were desirous of steering.

22nd.--On approaching the land again this morning,
it was found that but little had been gained through the night;
and unless the wind veered a little in our favour,
there seemed no probability of our rounding the head-
land which obstructed the passage to Hanarei.
Employed in plying to windward all day, and by midnight our position was such,
that day-light only was needed to sanction our taking the advantage
of the bending of the coast to steer for the entrance of the bay.
But when our object was nearly accomplished, the wind died away,
and a strong current set the vessel so rapidly to leeward,
that for a time there seemed no prospect of our getting in at all: the breeze, however,
rallied again, and helped us round the point of the reef; and by nine o`'clock a.m.,
an anchor was dropped in ten fathoms water in the midst of heavy rain.

23rd.--As vessels seldom touch here, our arrival soon brought off a number of canoes,
and a supply of fresh fish;
butter and milk were quickly furnished from the estate of Richard Charlton,
who had sent an overland messenger from Koloa, to keep a good look-out for the vessel,
and have these articles in readiness on our arrival.
After breakfast,
our kind interpreter Peter J. Gulick went on
shore to examine into the state of the people,
their own missionary and his family being absent at Oahu,
attending the General Meeting of the mission.
Some of our people were employed on shore in the forenoon,
slaughtering a bullock from the stock of Richard Charlton,
kindly provided for our accommodation,
in the expectation that the Henry Freeling would
return towards the Equator before many days.

24th.--Our missionary friend came off from the shore at an early hour,
to inform us that the natives would be collected about half-past nine o`'clock.
We landed with him in a large canoe, conducted by skilful natives,
which carried us comfortably through the surf.
As we approached the strand, the people collected in a body,
and watching the return of the roller which bore
the canoe a sufficient height for their purpose,
it was placed in a few moments very safely out
of the reach of the breakers upon dry ground.
The conch-shells were immediately sounded;
and after waiting some time at the missionaryhouse, we proceeded to the meeting.
Here we found, perhaps, seven hundred people, all squatted upon the ground in stillness,
(as no seats were provided,) waiting for the strangers.
After a time my mind was opened to declare amongst them Christ Jesus the Lord;
the light of the knowledge of whose Holy Spirit visits every heart,
to give the glory of God in the face of Jesus Christ, and if believed in, and walked in,
to restore man from a state of sin and death to holiness and newness of life.
Strength and ability were richly afforded me,
to testify the love and the mercy of God in Christ Jesus to the children of men;
and the people were exhorted to turn to His light while
the day of their visitation was extended,
lest they should be overtaken by the night, wherein no man can work.

Although the people were very attentive, and great solemnity prevailed on the occasion,
yet after the meeting broke up, as was the case with those held at Koloa,
the sentence of death in myself was my only portion:
at its conclusion they flocked round us in the usual way,--many of them, I believe,
with love in their hearts.
At least one hundred and fifty accompanied us down to the strand,
and saw us safely launched again into deep water.
In the afternoon landed on the other side of the bay,
and had full opportunity of witnessing the very low state of these poor degraded people,
and the filthy abodes of several of them.
I exchanged needles and fish-hooks for any thing they could furnish,
even for broken shells, as they seemed to have nothing to part with,
to purchase such articles as they stood in need of,
and which they were very desirous to obtain.
At seven o`'clock p.m., departed from the bay,
and made sail to the eastward with a fair breeze, and heavy showers of rain falling.

25th.--In the course of this day,
we were much baffled with variable winds and strong currents;
towards sun-set we anchored in five fathoms water, in the road of Waimea,
opposite a fort formed some years ago by the crew of a Russian vessel.
Soon after arriving,
Peter J. Gullick went on shore to arrange for a meeting with the people tomorrow.
In the evening, some milk was sent off from the missionary station; its occupants,
Samuel Whitney and family, are now absent at Oahu, with the rest of the mission.

26th. (First-day.)--Landed in good time to attend the meeting.
Richard Charlton undertook to conduct us through the surf with the natives,
having acquired their language from long residence among these islands;
we soon met with Peter J. Gulick, and proceeded to the meeting together.
By nine o`'clock about one thousand persons were collected,
who filled every part of the house, except a narrow gallery intended for singers,
at the lower end of it.
I felt as one stripped of every thing but a sense of utter weakness and inability,
which has been the case for several seasons of late;
and although the Lord was again pleased to try my faith,
that my trust and confidence might be centred in Him alone,
He again condescended to clothe me with strength and power,
to declare amongst the people the unsearchable riches of Christ.
Soon after Peter J. Gulick had read my certificates, I stood up;
and having awakened their attention and directed them to Him,
unto whom the cattle on a thousand hills belong,
I told them I had no desire to multiply words amongst them,
lest I should be found darkening counsel;
but that my desire was to turn them from words to the power of
the Holy Spirit of the Lord Jesus in their own hearts.
My tongue was loosed to declare freely the things relating to the gospel of the kingdom,
for upwards of an hour.
No people could be more attentive; my prayer is, that many of them may be enabled to say,
from heart-felt living experience,--"`Now we believe, not because of your saying:
for we have heard him ourselves, and know that this is indeed the Christ,
the Saviour of the world:`"--unto whom be ascribed glory and dominion forever.

After the meeting was over,
I found that my interpreter was greatly exhausted by
the fatigue he had had to pass through,
although he offered to attend again in the afternoon, but added,
that the number of people would be much reduced,
as no afternoon meetings are held in the absence of the resident missionary;
and when at his post, the Bible class system is usually adopted.
I told him, that if I came with a view to see the people again,
I should take care to be on shore in time in the afternoon.
The surf had increased since our landing in the morning; but we were assisted as before,
by experienced and skilful managers.
The weather becoming wet in the afternoon, seemed to decide my remaining on board,
having been informed that the islanders do not like to go out in the rain themselves,
nor do they expect strangers to do it; but more especially,
from not feeling it binding upon me to return to the shore again that day.
On looking at the subject after the time had passed by,
although in poverty and depression, I did not feel as one that had held back.
Had there been a probability of a meeting being held,
I was scarcely fit to attempt a second landing, from pain in my head.
In the afternoon, read portions of Scripture to our own crew.
Late in the night, made a fair copy of a short address to the members of the mission,
in the Sandwich Islands;
at the same time acknowledging the receipt of a joint
communication from them in their general meeting capacity,
signed by all the members.

27th.--Engaged in procuring yams, pumpkins, with other vegetables, and live stock,
in the prospect of again steering towards the Equator.
Found it expedient to hire from the natives a strong canoe, to assist our operations,
as our own jolly-boat is now old and very crazy,
and altogether unfit to contend with the surf upon this side of the island,
even when in her best condition.
On landing we found a considerable body of the natives collected together,
with a prodigious quantity of various sorts of vegetables, fruits, fowls, etc.,
intended as a present to our vessel: the missionary being present,
there was no lack of an interpreter between us.
I told him that we could not accept of any thing as a present from these poor people;
and even if we could,
that the quantity before us upon the beach was greater
than our vessel could take in with convenience;
at the same time I would not object to take what might be useful to us,
provided they would allow us to make a suitable return.
It appeared from the statement of the missionary,
that the people were intending to build a new meeting-house at Koloa,
by voluntary contribution, and that as this was the case,
the difficulty could be at once surmounted by the appropriation of
the amount of the supplies which might be taken by us,
to that purpose.
To effect this, the articles we needed were to be valued in dollar money,
which enabled us to pay for them in such commodities as
could be used in the building in question as materials,
or in the payment of workmen employed in erecting it:
articles of clothing were much in demand for the latter purpose.
The people, particularly the females,
brought with them on this occasion many of the simple native productions of the island;
with small quantities of shells,
and other ornamental trifles in use among them in the days of gross idolatry,
but now laid aside.
These articles were intended as presents from individuals then present,
so that each person received an equivalent for what he had to offer on the spot;
and care was taken that an ample return was made to each of them.
Needles, fish-hooks, and pocket combs, were eagerly sought after in exchange.
Some native dresses were brought in the shape of a morning robe for a female,
made from the bark of the paper mulberry tree, and with thread of their own manufacture:
this circumstance accounted for the brisk demand for large sized needles,
to enable them to use their own thread,
while a very small quantity of our thread was taken.
These dresses were mostly purchased for scissors; but knives, combs,
and other articles were in demand, for native cloth of stained colours.
We returned on board to avoid the hottest part of the day, as the heat was extreme,
and the reflection from the white sand on the beach almost insupportable.
As the sun declined, we landed again and pursued our barter trade,
until the natives began to retire from the shore for the night:
crossed the river by canoe opposite the fort.

Some years ago,
the chiefs of this island had been prevailed upon by the Russians to
place themselves under the protection of that nation,
and on that score had ceded one-half of the island over to them.
After this, the fort was erected;
the step altogether was found to be obnoxious to some other powers,
and the Russian government disclaiming the action,
as having been committed without any sanction on their part,
the scheme was abandoned altogether, and the blame cast upon its supposed projectors:
be this correct or not, the fort is still in existence.
Cannon of other nations are to be seen in it, besides those of Russia;
and several may be distinguished to have come from England, by the G. R., etc. upon them.
It is probable these may have been procured by the chiefs, or their own king,
with a view to strengthen this place for the security of the island.

28th.--Today, for the most part employed in embarking yams, sweet potatoes, water melons,
goats, etc., which had been purchased with barter goods.
Some molasses had been spoken about to a Chinaman who is engaged here
as an agent to an American master residing at Oahu;
but finding that this article was entirely the gain of oppression,
we declined taking it on that account.--A few
gallons were purchased at last from an American,
who had produced the sugar cane by his own labour,
which wholly removed all difficulty on this head.
On this island, it is said that the poor natives are more oppressed by the chiefs,
than on any other of the Sandwich group.
The introduction of two establishments for making sugar,
with which the chiefs are connected, it seems probable,
will eventually be the cause of promoting a state of slavery,
as oppressive as that which has existed in the West Indies: the population, from this,
and other much to be deplored causes,
is rapidly decreasing these sugar plantations were set on foot by two Americans.
In one instance, the chiefs find all the labour, and have one-half of the profit;
in the other, the scheme is more plausible,
as the natives are paid a small pittance for their labour:
but the chiefs are compelled by contract to furnish a
sufficient number of labourers for their share of the profit;
for the sake of which, the contract is more rigidly enforced.
This was spoken of as being conducted upon a fair principle; but we told them,
nothing compulsory could be just.
Our friend the missionary having left us and returned to his family at Koloa,
we found the kind assistance of the British Consul very
useful in our transactions with the natives.

At the edge of dark, we had all on board,
and only waited the land-breeze to waft us from the island.
At nine o`'clock P. M., Richard Charlton left us,
into whose hands were committed our letters for England, to be forwarded from Oahu,
by the first eligible conveyance which might offer after his arrival there.
Our pilot "`Sugar-Cane`' was now paid off, and all things being settled,
we took a final departure, and stretched off a south and by east course;
leaving these interesting isles of the ocean, amongst which,
more than half a year of our time had been expended.
The best welfare of the inhabitants of the Sandwich Islands
will be an object ever near and dear to my heart,
and which, however distantly separated as to the body, my spirit will earnestly crave.

[.offset]
Extract from a letter of this date written to an intimate friend in England:

Time would fail me to tell of the everlasting mercy and
compassion that have been extended to us-ward,
in that love which has compassed about as with a shield,
during our recent operations in dangerous bays and roadsteads,
lying open within a very few points of the compass, to the whole beat of the Pacific.
In most of these places, we have had to land amidst a breaking surf,
sometimes in our own boat, and at others in canoes, which when managed by the natives,
are by far the safer, although subject to frequent drenchings from the sea.

I brought with me from London, as recommended by a dear friend,
a patent water-proof belt, or life-preserver, made by Macintosh, of Cheapside;
but I have been ashamed to make use of it on any one occasion,
and when we have been going to land, I have uniformly left it on board the vessel.
How could I now begin to doubt the loving-kindness of Him,
whose goodness has followed me all my life long;
and dare to distrust that never-failing arm of strength,
that has been so often and eminently stretched forth for my preservation,
by night and day, by sea and land, amongst strangers and foreigners,
where no man cared for my soul,--in cold and heat,--in hunger, thirst,
and weariness,--amid the din of arms,
the noisome pestilence and the destruction that wastes at noon day:
how often from boyhood to the present day have I been
sheltered from the rage of the angry tempest;
and how was I supported in the iron grasp of affliction, when week after week,
tidings of family distress assailed me,
without the power to lend a hand of help,--the parent stock smitten and removed,
and the branches withering.
And after all this, shall I now, when old and grey-headed,
begin to doubt the heavenly source of help,
that still strengthens me to proclaim the unsearchable riches of his love,
to the tribes which inhabit his possessions in these uttermost parts of the earth;
when the feelings of decaying nature are lost sight of,
and the inner man strengthened by the might of
the Lord`'s glorious power and sensible presence,
to my humble admiration.
"`To whom shall we go,`" when He only has the words of eternal
life? to whom all power in heaven and earth is given.

[.signed-section-signature]
Daniel Wheeler

Sixth Month 29th.--There being no probability of further
interaction with the natives in these parts of the globe,
we now return to the true time of England,
from which we digressed on our arrival at Oahu, to prevent mistakes:
but the log book of the Henry Freeling underwent no alteration,
and is now dated the 30th of Sixth month, 1836.
(Fifth day.) This morning, being fifty miles from Tauai,
the loom of the island under a bank of clouds was but just discernible.
Cloudy weather,
but we had a wind that enabled us to steer a steady course to the south south-east.

When on the point of leaving the harbour of Honolulu, at Oahu,
when there could be no further communication between us and the parties concerned,
a letter was received from the general meeting of the American mission,
signed by all the members; of which the following is a copy.

[.signed-section-context-open]
Honolulu, June 16th, 1836.

[.salutation]
Daniel Wheeler, Dear Friend,

We, the missionaries of the Sandwich Islands,
feel ourselves happy to have the opportunity of reciprocating the kindness and sympathy,
which you and our young friend, your esteemed son Charles Wheeler,
have manifested to us and our families, during the period of five and a half months,
while you have sojourned and laboured with us.
We have hailed your arrival in this country with gladness,
and welcomed your visit to our stations with much pleasure.
We have read your credentials from York and London with care;
and have been cheered by the Christian spirit which they breathe.
We have been refreshed by your interesting account of
the origin and progress of your enterprise,
and by your earnest and repeated evangelical appeals to our people.
You have seen with what readiness of mind we
have interpreted your discourses to the people,
and endeavoured to facilitate your work.
And we now tender you our thanks for your kind co-operation in our work,
with which you have been enabled, by the great Head of the church, to favour us.
Your design to preach "`the unsearchable riches of Christ`" in
the isles and on the shores of this great ocean,
for an indefinite but protracted period,
at such a remove from the comforts of home and all you held dear on earth, must,
we are aware,
(for we are acquainted with the nature of the service,) be attended with sacrifices,
toils, and cares, in which none but the Divine arm can sustain you;
but this arm Divine has thus far sustained you.
For this we would unite with you in thanksgiving "`to the Father of lights,
from whom comes every good and perfect gift;`"
and with you would we rejoice in the assurance,
that it will sustain you still.
Take courage, dear friend, and go on with your good work.
Do what is in your power to pour the light of the sun
of righteousness upon the people which sit in darkness,
upon the tribes on whom the star-light of nature nightly shines,
and upon the isles over which the day-star of grace has arisen.
Accompanied and aided by your own beloved son,
sustained and guided by the adorable Spirit of God;
may you be enabled to do much to dry the fountain of intemperance and licentiousness,
which threaten such desolations in every quarter of the globe,
and to hasten the universal diffusion of revealed truth.
We bid you God speed, while you proclaim to perishing men the glad tidings of salvation,
through a crucified and exalted Saviour;
while with self-sacrifice and devotedness to Christ,
you labour "`to turn men from darkness to light, and from the power of Satan unto God.`"
Pray for us, that we may be found faithful in this work,
and that the gospel may have free course, and be glorified.
And now, as you are convinced that our Master calls you to leave us,
to prosecute the service you have to perform for Him in other isles and coasts,
we bid you and your son an affectionate farewell;
and part with you as with valued friends, whom we hope to meet in peace,
when the sacrifices, and toils, and trials of a missionary life are ended.
"`The Lord bless you and keep you.
The Lord make his face to shine upon you, and be gracious unto you.
The Lord lift up his countenance upon you, and give you peace.`"
Not unto us, but to God be the glory.
Your affectionate friends.`'

Signed by: Asa Thurston, Hiram Bingham, Samuel Whitney, William Richards,
Levi Chamberlain, Artemas Bishop, Lorrin Andrews, John Smith Green, Peter J. Gulick,
Ephraim W. Clark, Gerrit P. Judd, Dwight Baldwin, Reuben Tinker, Henry Dimond,
Sheldon Dibble, Titus Coan, Henry H. Hitchcock, John S. Emerson, David B. Lyman,
Ephraim Spalding, Richard Armstrong, Cochraine Forbes, Wm. P. Alexander,
Edmund H. Rogers, Lowel Smith, Benj.
W+++.+++ Parker, Edwin O. Hall.

[.offset]
An acknowledgment of the receipt of this document was sent to Oahu by the British Consul,
Richard Charlton, as before hinted at; a copy of which now follows,
with the substance of what quickened upon my mind to the members of the mission.

[.letter-heading]
To the Members of the Mission at the Sandwich Islands

[.salutation]
Dear Friends,

Your joint communication, replete with the expression of brotherly kindness and regard,
was put into my hand just as we were quitting the shores of Oahu.
Although utterly unmerited on my part, yet I feel compelled to accept it,
from a belief in the purity of those motives by which it was dictated; while,
at the same time, the feeling is awakened,
that to me belongs only "`blushing and confusion of face.`"
I rejoice in the opportunity so soon afforded me to acknowledge its receipt,
and more especially because I had felt my mind drawn towards you,
before I saw its contents;
desiring more and more that you may individually become
acquainted with the binding influence of that love,
which many waters cannot quench,
"`unto all riches of the full assurance of understanding,
to the acknowledgment of the mystery of God, and of the Father, and of Christ;
in whom are hid all the treasures of wisdom and knowledge.`"

I desire for you, my friends, all that you can possibly desire for yourselves;
believing that your principal desire is to be true followers of Him,
who said,--"`If any man will come after me, let him deny himself,
and take up his cross daily, and follow me.`"
These are the express and explicit terms of discipleship,
to which unqualified obedience is required;
and from which all reservations are inadmissible:
let us examine then how far these indispensable conditions are submitted to on our part.
If we profess to follow the great and heavenly example of "`Him who died for us and
rose again,`" in which all the graces of earthly perfection are combined,
in all our actions before men, let us, my friends, be complete,
and do it also in all our words: let our language to and before men be like His.
Surely we ought to be content to use the language which
he himself uttered and accepted of men.
His words are pure words: they are wholesome words:
and we ought to consent to the words of our Lord Jesus Christ.
Then let us be willing to follow the Lord of life and glory:
if we carry His example fairly out,
our speech will bewray us and show that we are his disciples indeed:
we shall find that this brings us at once to the foot of the cross--the daily cross:
without this we are strangers to the self-denying holy cross;
and if we do not bear the cross, we can never wear the crown.
Then let us not fear to confess our Lord and Saviour Jesus Christ,
nor be ashamed of Him and His word before men;
remembering the awful declaration which bears upon all,
and applies to all,--"`Whosoever shall deny me before men,
him will I also deny before my Father which is heaven;`" and "`whosoever
shall be ashamed of me and my words in this adulterous and sinful generation,
of him also shall the Son of Man be ashamed,
when he comes in the glory of his Father with the holy angels.`"
This has been put into my heart in love towards you: in the same love it is written,
and in which I trust it will be received, from your affectionate friend,

[.signed-section-signature]
Daniel Wheeler

My son Charles unites with me in an assurance of grateful
acknowledgment and regard for your kind remembrance of him.

P+++.+++ S.--The oppressed condition of the natives of this island is truly affecting,
and prompts me to remind my constant friend Hiram Bingham,
of the address that was presented to the king Kinau, etc., at his house,
to whose care the printing of it was committed.`'

[.signed-section-context-close]
Henry Freeling, in the road of Waimea, Isle of Tauai, 27th of Sixth Month, 1836.
