== Chapter XXX.

[.chapter-synopsis]
* Re-Cross the Equator
* Hervey Islands
* Visit the Island of Rarotonga
* Friendly Reception
* School
* Native Meetings
* Kindness of the Natives
* Sail for the Friendly Isles

Without entering into the particular details of this voyage,
which can be but of little interest to those on shore,
we directed our course towards the equator,
endeavouring as much as circumstances would permit, to keep to the eastward,
in the hope of fetching the island of Rarotonga, one of the Hervey Isles,
in latitude 21° 31' south of the line, and longitude 160° west.
After witnessing the usual variety of changes in the winds and weather,
and the thunder-storms to which these latitudes are subject,
we were favoured to cross the equator about three o'
clock in the morning of the 19th of Seventh Month,
in health and safety, and at noon were in latitude forty miles south;
longitude by lunar observation 160° west.
Not a single vessel was seen during the whole passage;
and although we must have passed near several of the
islands scattered upon the surface of the ocean,
both north and south of the line, yet none of them were sighted until First-day,
the 31st;
when at day-break in the morning the island of Rarotonga was
discovered about seven leagues to windward of us.

The morning was then calm,
but at nine o'clock a.m. we stretched away to the east north-east, with a light breeze,
there being no alternative, but that of endeavouring to beat up to it;
although it was a little mortifying to perceive,
that the settled trade-wind blew directly from it.
Having by dint of exertion gained ground,
one of the missionary stations could plainly be
discerned to leeward on Second day afternoon.
This was known by the appearance of a large building, which, with some others about it,
was whitewashed, and had a neat appearance.
We then stood to the southward until the other missionary station was open to our view,
and near enough to observe a number of the natives upon the look out,
who had no doubt descried the approach of a strange vessel to their shores.
As the wind still blew strongly against us,
we could not get sufficiently near the coast to entice
the canoes to come off before the night closed in;
so we hovered within a short distance of the island until the next morning,
the 2nd of Eighth Month: when, at an early hour a boat was seen coming from the shore,
from the first station observed yesterday, which in due time reached the Henry Freeling.
We were enabled to understand from our visitors,
that we were off the station of Charles Pittman the missionary,
with whom and with his wife, we became acquainted at the island of Tahiti last year.
They were at that time in a weak state of health,
and it seemed very doubtful whether they would ever be able (
particularly Charles Pittman,) to return to the island of Rarotonga.
It was very satisfactory to find they were restored to their duty in improved health;
more especially as our way seemed at once fairly
opened to enter upon this new scene of labour,
by the means being thus marvellously provided,
as there was no other resident missionary at that time upon the island.

I sent a note back by the boat to say,
we were now permitted to greet them from the very edge of Rarotonga;
and only waited information,
as to the practicability of our vessel finding a place of safe anchorage.
This boat was soon discovered to be again coming off, and on near approach,
Charles Pittman himself proved to be on board of her.
We had scarcely time to congratulate each other after he had reached the deck,
before he became sea-sick from the tossing of our vessel.
As he was unable to converse, we concluded to return to the shore with him immediately:
he remained in the air while we threw off our sea-garments,
and we then put off together for the shore.
He began to revive as we got into smoother water,
and after landing he soon came round again.

As we drew nigh the strand,
it became densely covered with an innumerable host of children,
who at once hailed us as their friends:
it was with difficulty that we could pass along for them,
as these delighted little naked fellows completely
choked up the avenue through a grove of bananas,
which leads to the mission-house, struggling who should first get hold of our hands;
and if but a finger could be laid hold of, it seemed quite to satisfy them:
this banana grove was of Charles Pittman's own planting.
Soon after reaching the house,
the floor was studded over with natives squatted on every side,
the elders of the people coming forward to salute us, and welcome us to their island.
After some consideration and inquiry had taken place,
it was concluded that the people should be generally
convened tomorrow morning in that district,
and a meeting held at eleven o'clock a.m. The afternoon, towards sundown,
would have been preferred on some accounts,
but this would unavoidably have thrown us into the dark,
and thereby rendered our return to the Henry Freeling doubly hazardous.

After partaking of some simple refreshment, we looked round the village of Gnatagnia,
and then prepared to return to our vessel.
When leaving her in the morning, we took with us an English union jack,
for the purpose of hoisting upon a lofty bamboo, or cocoa-nut tree,
as a signal for Captain Keen to stand in as close to the reefs
as was prudent on seeing this flag displayed upon the shore,
to save the labour of the people in the boat,
and to afford us every chance of smooth water.
When this flag was put up,
we were told that it was the first time the English
flag had been planted upon the island of Rarotonga;
very peaceable possession had been taken of the island on this occasion at any rate,
and one in which a most cordial reception was strongly evinced,
in a degree of that love which casts out fear from every breast,
and makes every man a brother.
We were favoured to get well on board,
and then purchased a few fowls and vegetables of the native crew,
more with a view to please, than from a lack of fresh provisions.
Our meeting with the natives tomorrow is now entirely dependent upon the elements,
a shift of wind may compel us to seek safety,
by flying from the island before the returning morning; but having done our best,
we must cast all our burden and all our care upon Him, who alone can bring it to pass;
before whom my mind is humbled and bowed down, imploring help and strength;
that the righteous cause may not be tarnished in our feeble hands,
but rather that the Lord's name may be exalted and glorified,
and the gospel of the dear Redeemer's spiritual
kingdom faithfully declared to these people;
until the thanksgiving of many shall redound to the glory and praise
of the riches of that all-saving grace and truth which came by Him,
bringing salvation unto all mankind the world over.

Eighth Month 3rd.--The morning was beautifully fine,
but having crept a long distance from the island during the darkness,
and the breeze now being very light, our progress shoreward again was very slow.
Although about one-half of our masts only could
be seen above the horizon when the day broke;
yet the natives had the sagacity to perceive, by the position of our sails,
that we were steering towards the shore,
and immediately put off with Charles Pittman's boat.
Our own boats had been too long in a dry state, to be trust-worthy;
and as there was no harbour that could be entered with prudence,
all our hands were required on board,
as the vessel was liable to be blown off to sea at all times.
Charles Pittman's boat, although a clumsy one,
was therefore regarded as a privilege and addition to our comforts.
From our distance in the offing, it was nearly nine o'clock a.m.,
before this boat got to the vessel;
but desirous of rendering every assistance in his power,
Alexander Cunningham (a person whom we had known last autumn at Eimeo,
and now endeavouring to establish a sugar plantation on
his own account at Rarotonga,) came off in her:
having some knowledge of the language,
he came principally to interpret between us and the natives, should occasion require it.

While the breeze freshened a little,
and the vessel was enabled to steer towards the mouth of the channel through the reef,
we kept on board; but on approaching the coast the wind began to die away,
and we then proceeded more rapidly in the boat.
On landing we were met by several hundreds of the natives,
a large proportion of them boys; and after remaining some time at the mission-house,
we looked into the school for the least scholars:
some of whom read to all appearance very readily.
In the large school we heard several of the boys and girls
read verse after verse alternately in one of the Evangelists;
and were informed that fifteen hundred copies of the Four Evangelists,
had been recently received from England, via Tahiti: some of these were read audibly,
and we were told correctly.
After some further examination by catechising, a hymn was sung;
the schools then broke up in an orderly manner, and proceeded towards the meeting-house.

While a silent spectator in the schools,
the love of the Divine Master flowed in my heart towards these
dear children,--an encouraging and sealing evidence,
that strength and ability would not be lacking
to proclaim the glad tidings of his gospel,
in his time.
The house was filled, and held upwards of two thousand people.
We remained upon the floor of the building, while Charles Pittman read my certificates,
and explained to the people the nature of my visit, I believe to the utmost in his power.
During this time it was very evident,
that if Charles Pittman had been speaking by my side,
half of the people at least could not have heard him,
and therefore I thought it best to promote his
remaining in his pulpit by joining him there.
I remained quiet, however, until he had thoroughly finished,
and then went up and stood in silence by his side, for a short interval:
when it was with me to turn the attention of the gazing islanders to
the "`God and Father of our Lord Jesus Christ`"--that the great
object of our thus being permitted to assemble together,
might be fully realized,
and the blessing which prevailed to the utmost bound of the everlasting hills,
might rest upon us.

After this, I had largely to declare the things which belong unto their peace,
and to turn them to the "`Lamb of God which takes away the sin of the
world--that they might know Him to be so in blessed reality,
by believing in the light of the Holy Spirit, which shines in every heart,
as a light in a dark place; that by taking heed thereunto,
they would be made sensible of the darkness of their own hearts.
It was for this the Saviour died, that mankind might no longer walk in darkness,
but in the light of life; that as sin has heretofore reigned in us unto death,
so now might grace reign through righteousness unto eternal life,
by Jesus Christ our Lord.
It was a solemn season; the power of the Lord reigned over all,
and his own works rendered living praises unto Him and the Son of his love.
After the meeting broke up, some time was occupied in noticing the people,
who remained in crowds about us.
It was agreed with Charles Pittman, that the people at Aaron Buzacott's station,
about eight miles distant,
should that evening be informed of my intention to visit them tomorrow;
and that the meeting should be requested to gather at an early hour in the forenoon,
to allow sufficient time for my return to the vessel.
While we rested and refreshed, the preconcerted signal was made,
and the Henry Freeling coming pretty close to the island,
we got safely on board before dark.

4th.--Having an overland journey to perform, I repaired to the shore in good time,
and with the assistance of eight stout natives,
to bear me alternately four and four upon their shoulders when wearied,
this journey was accomplished with comparative ease.
The great heat of the sun when it shines,
renders the exercise of travelling on foot too fatiguing to the European constitution,
and highly imprudent to be persisted in beyond short distances.
At this station (Avarua,) we had a fine meeting, more than 2500 persons being present.
My certificates were read as usual,
and I had largely to publish the glad tidings of the everlasting gospel amongst them,
to my own peace.
Although at first standing up I was much depressed,
as one that had no might and was ready to faint;
yet as I endeavoured to keep close to my heavenly guide,
strength proportionate to the day, and confidence, were graciously extended,
to my humble admiration.
Many blessed and encouraging truths were given me to spread before the people,
to the exaltation, I humbly trust, of the Most High God;
and his name and power were magnified,
who in the greatness of His love and strength came to
seek and to save that which was lost,--if believed in,
looked for, and yielded unto, in the obedience of faith.

The meeting held late, and the people were very solid and attentive;
my sympathizing and faithful interpreter could not help acknowledging the blessing,
with which we had that day been favoured, as a crowning evidence.
The people seemed reluctant to separate;
and many of them followed us to the dwelling of the absent missionary,
where we partook of a repast, which had been kindly prepared for our accommodation.
The king or principal chief Makea, joined us;
he was desirous of making a present of supplies for the vessel;
this however was declined, and his kind intention acknowledged with gratitude.
This chiefs sister, once dined on board the Henry Freeling,
with Pomare the queen of Tahiti,
when we were lying in the bay of Papeite at that island a year ago;
and she was mentioned in my Journal of that day, as the sister of the king of Rarotonga.
She was at the meeting,
and came to me in a very kind and agreeable manner before it commenced,
and after it was over;
Charles Pittman gave me a pleasing account of her stability of conduct and example.
Several questions were put to us on religious subjects through Charles Pittman,
by Makea and others who attended;
and I had an opportunity of telling them what great things the Lord had done for them,
and that the principal work they had to do in return,
was to labour in the vineyard of their own hearts, etc.

We got back to the Gnatagnia station before sun-setting,
when for the first time I found that there was an out-station
twelve miles distant on the other side of the island,
the people of which had not been at either of the meetings that had been held.
I rather shrunk at the receipt of this information,
principally I believe owing to the continued exposed situation of the vessel,
and perhaps the weak state of my Charles might throw an additional
weight into the scale of discouragement on the occasion.
Without making any remark, I concluded not to stop over the tea which was then ready,
but return immediately on board,
under a faint expectation of being on shore again tomorrow,
and perhaps getting to the out-station in question, called Aroragne, on the Seventh day;
to be in a state of forwardness to leave the range of
the island altogether late in the evening,
if that was permitted, which on many accounts appeared desirable at the moment.
I was favoured to reach the vessel at the edge of dark.
As the evening advanced, blackness and darkness began to gather to the southward,
incessant lightning followed with distant peals of thunder;
at the same time the wind began to freshen from the westward, a very unusual quarter,
as the regular trade-wind almost constantly prevails from the south-east,
over all others.
It was now apprehended that this unexpected change in the weather,
and the wild appearance of the atmosphere,
would prove the forerunners of a heavy tempest; the captain thought it advisable,
under these circumstances, to haul away from the island under a press of canvass,
which would at any rate remove every apprehension of suffering from its crags and reefs.
We passed a very rugged night, and at four o'clock in the morning,
were assailed with a tremendous squall of wind,
which seemed to dispel in great measure the most
threatening indications of the atmosphere.

5th.--Heavy rain and rough weather ushered in the new morning,
and when the day was thoroughly established, we were found to be so far off the island,
as to render the whole length of day insufficient for us to resume our former position,
so as to have the usual interaction with its inhabitants.
This being conclusive,
the day was expended in preparing and collecting many commodities wanted as presents,
and to purchase supplies of some articles the most needed;
also in searching out a stock of clothing and materials,
for the purpose of relieving the needs and sufferings of the poor naked children,
who were often shivering with the present cold.
The climate of this island is stated to have become much cooler
within the last three or four years than it was formerly:
the heat of the sun is excessive during the day, but the nights and mornings are chilly,
and the dews very heavy.

6th.--After a very tossing and almost sleepless night,
I felt much cast down at the situation of things around us,
and seemed inclined to lay aside every attempt to effect a landing upon the island today,
although we had got into an eligible position for the purpose during the night.
I did not feel clear of this out-station at Aroragne;
and yet there had been no opportunity for an arrangement to be made for it,
or the needful notice given of an intended meeting; but before getting up,
the way was made plain before me that would lead to peace and tranquillity of mind;
to insure which I found that I must land today at Gnatagnia,
attend the meeting there tomorrow,
and on Second day go off to the out-station at Aroragne: to this I felt resigned,
and told Charles, that this was the only way for me to proceed with safety.
Every exertion was made to push the Henry Freeling
within the range of tolerably smooth water;
and the natives who had been anxiously watching our motions, on seeing this,
launched the boat and put out to sea to meet us.
The health of my Charles was so favourably restored, as to allow him to accompany me;
and having got our stores, etc. safely into the boat, we again pushed off for the shore,
and on landing were welcomed by the cheerful countenances of the islanders as usual.
On reaching the missionary dwelling, I told our kind host and hostess,
that we were now come to take up our abode with them in earnest.
On explaining the prospect then before me,
Charles Pittman expressed much satisfaction at the
probability of the Aroragne people being visited.
I left directions with Captain Keen,
to stand close in with the island once every day if practicable;
and when we were ready to embark, the flag should be hoisted by us as before agreed upon.
The remaining part of the day was fully occupied among the people,
in making trifling purchases and bestowing rewards, etc.

7th. (First day.)--After breakfast this morning, the Bible was laid before me,
according to the usual practice of giving preference to the stranger,
who at once undertakes to read a chapter, and afterwards to go forward with a prayer.
When I had finished reading, we remained in silence.
I had a secret hope this circumstance might lead
into serious consideration at a future day,
as to the practice of Friends on these occasions;
and perhaps point out the difference between those whose time is always ready,
and others who can only move in the ability given by Him,
who said "`without me you can do nothing.`"
I sometimes feel much for some of the former,
from a conviction that they themselves are at seasons brought under a
very humiliating sense of being numbered with those who "`ask and
receive not but while anxious to be found in the path of my own duty,
my desire is to be clothed with the heavenly garment of
charity towards others in these matters.

The time of the native meeting now drew nigh,
at the thought of which my mind was greatly cast down;
and yet I felt a sustaining confidence that my being here was in the right ordering,
for if my own inclination could have been gratified and followed,
we should have been this morning out of sight of the island altogether.
Charles Pittman might have observed my sunken condition:
for previously to setting out for the meeting,
he seemed desirous to ascertain whether I should speak to the people or not.
I told him this was very uncertain;
but from the manner in which this thing had been brought about,
which was certainly not in my own will,
it was by no means improbable that I might have something to say to them.
The house was well filled when we reached it,
and Charles Pittman at once ascended the pulpit, but I remained on the ground floor,
as one having no part to take in the matter; and, I trust,
in a state something similar to that of passive clay, willing to be any thing or nothing,
to do or to suffer in secret with the suffering seed.
Charles Pittman went on with the usual services,
as if he had little expectation of any interference on my part;
but when the second singing was concluded,
the way seemed at once to open for my going to him.
On my getting into the pulpit, such was my blank condition,
that I told him we must proceed slowly;
for I should have to look well for the stepping stones to get along with safety.
We stood some time in silence together,
when my mouth was opened with our blessed Lord's declaration,--
"`there is joy in heaven over one sinner that repents,
more than over ninety and nine just persons that need no repentance.`"
Such is the everlasting mercy, and boundless love of God to his creature man,
that he wills not the death of a sinner; but rather that all should repent,
forsake the evil of their ways, return unto Him, and live forever.
For this the Saviour came; not to condemn,
but to save a guilty world:--Jesus Christ came into the
world to save sinners from the wrath to come;
that we might have life, and that we might have it more abundantly.
He purchased for poor, lost, finite man, the unspeakable gift of the Holy Spirit,
by the sacrifice of himself on the blood-stained cross, "`the just for the unjust,
that he might bring us unto God;`" who "`so loved the world,
that He gave His only begotten Son, that whosoever believes in Him, should not perish,
but have everlasting life.`"
But none can be benefited by the coming and sufferings of the Lord Jesus,
without an implicit belief in him.
A mere belief in the outward fact of His coming in the flesh upon the earth,
will not suffice: we must believe in the coming of His Holy Spirit into our hearts,
and in His power to cleanse and save his people from their sins.
How many in this our day,
fall short of the knowledge of the only "`true God and Jesus Christ,
whom he has sent,--which is life eternal,`"--through an evil heart of unbelief!
When the Saviour of men was personally upon the earth,
and men beheld his glory as of the only begotten of the Father, full of grace and truth,
his mighty works were few in some places,
because of the unbelieving hearts of the people;
and he had frequently to upbraid the doubting, unbelieving multitude,
for their hardness of heart; there were also found among his own disciples,
those that were slow of heart to believe respecting Him.
"`Except you see signs and wonders you will not
believe,`"--was his language on one occasion;
"`but blessed are they that have not seen, and yet have believed.`"
Great indeed was my desire that these simple-hearted islanders might not be faithless,
but believing,--that joy unspeakable and full of glory might be
theirs,--that Christ might dwell in their hearts by faith,--even He,
whom not having seen, they yet desired to love.
For about an hour and a-half, I was drawn forth to plead with these dear people,
in the love of the gospel; that they might be reconciled to God, for Christ's sake,
for their own souls' sake, and ours also, because of the Truth as it is in Jesus.
It was indeed a glorious meeting,
and ought to be commemorated with humblest gratitude and praise.

My faithful interpreter was almost overcome with the
sense of the working of the Lord's almighty power.
When the spring was closed up, he spoke to me in allusion to my having said,
on first going into the pulpit,
that 'I should have to look well for the stepping-
stones to get along with safety,'--saying,
that he soon found I had got upon good ground, from the feelings he experienced.
But the sentence of death was mine;
and though I have truly nothing to boast of but weakness and infirmity,
both of late much and evidently increased,
yet how can I do less than cause the voice of the praise of my God to be heard,
by faithfully testifying to that loving-kindness, which is better than life:
His work is honourable and glorious,--His righteousness endures forever.
I sat down in nothingness and weakness; the creature was laid in the dust,
as one that owed unto his Lord,
far more than "`five hundred pence`" many times multiplied,
and who had nothing to pay with;--self-convicted too,
and as one to whom all that had been spoken most fully applied.
Although the meeting had held long, before I took any part in it,
and was then prolonged to an unseasonable length, the people retained their seats,
as if fearful of disturbing the covering which was permitted to overshadow us;
and they continued in stillness, after we came down upon the floor to them:
but on my remarking to Charles Pittman, that they did not seem willing to go away,
he said a few sentences to them, after which they quietly withdrew.

8th.--Rose at the earliest cock-crowing this morning,
and prepared to set forward for Aroragne.
The night having been squally, and the morning opening with showers of rain,
it was thought the exposure and fatigue would be more than my Charles could support,
as the present state of his health rendered unwarrantable any thing bordering on risk;
it was therefore concluded best that he should remain at Gnatagnia.
Charles complied with this determination rather reluctantly,
being desirous of rendering assistance in any way within his power,
and not liking to be so separated from the scene of duty.
Charles Pittman and myself moved forward, he on horseback, and myself in the usual way,
with a body of natives, ten in number.
In the morning the rain made the work cooler, and seemed to make no impression,
as it fell on their well-oiled skins:
the burning and dazzling white sand on which we travelled,
was nicely cooled by the showers,
and retained a refreshing temperature while the atmosphere remained cloudy;
but on our return in the afternoon, the sun was burning hot,
and the weather totally changed.

Notice having been timely given, we found the people prepared to receive us,
and the meeting was soon collected, to the number of fifteen hundred persons.
Being a stranger on this side the island,
my certificates were read as usual at the commencement;
an arrangement always preferred by myself,
from having so often witnessed it to bring the people into stillness and attention,
and also to renew a fresh feeling of the precious unity
and sympathy of my dear brethren and sisters far away;
the remembrance of them under these circumstances,
in the love and fellowship of the gospel, brings strength, while it softens the heart.
I remained upon the floor, with a crowd of natives squatted about me,
and having now no one near me, that I had ever seen before,
I felt like a stranger indeed.
When the time arrived, I went to Charles Pittman, and eventually broke the silence,
by reminding the people of Him, who knows our down-sitting and up-rising,
and understands our thoughts afar off; yes, there is not a word in our tongue,
but He knows it altogether: "`all things are naked and open to the eyes of Him,
with whom we have to do.`"
"`None of us can by any means redeem his brother,
or give to God a ransom for him;`"--our salvation must be wrought out by ourselves,
and that with fear and trembling.
But sinful and impotent as we are, the means for the accomplishment of this great work,
are mercifully placed within the reach of all, through the unutterable love of God,
in Christ Jesus, our crucified, risen, and glorified Lord.
In order to partake of this great and universal salvation,
conferred upon mankind by the "`God and Father of our Lord Jesus
Christ,`" we must come to the experimental knowledge of Him,
who is the eternal author of it all.
He tasted death for every man; and by the awful sacrifice of himself,
not only procured for a guilty world the remission of sins that are past,
but the unspeakable gift of the Holy Spirit.
"`I am the light of the world,`" said Christ;
"`he that follows me shall not walk in darkness, but shall have the light of life.`"
Those who believe in this light, and walk in this light, who bring their thoughts, words,
and deeds to it, and obey its manifestations,
are they who love Christ and keep his commandments; for Christ is the light:
and in thus doing, they love God,--for God is light:--"`I and my Father are one.`"
"`If we walk in the light, as he is in the light, we have fellowship one with another,
and the blood of Jesus Christ His Son cleanses us from all sin.`"

The spring of the everlasting gospel flowed freely to this people,
and in its authority I was enabled to appeal unto themselves,
and make them their own living witnesses to the in-shining of "`the
light of the glorious gospel of Christ`" in their own hearts.
That although it was their lot to dwell in a remote part of the globe,
on a small spot in the midst of the ocean,
they were alike the objects of everlasting and redeeming love,
with those who inhabited every other part of the Lord's earth;
and for them the precious blood of Christ was shed, as for me, and mine, and all mankind.
The people were invited to repent, believe, and obey the gospel,
and they would find it to be the power of God unto salvation, through the Holy Spirit.
And as they came to enjoy the blessedness of those who believe in Jesus,
and walk in His light in obedience to its discoveries, their hearts would be changed,
and become more and more turned towards their dear children, than is at present the case,
that they also might with them partake in the joys of God's salvation.
It was a memorable season, and I trust will not soon be forgotten.
After noticing the people we repaired to a native teacher's house,
and partook of some cooling refreshment of which we both stood in need.
On our return to Gnatagnia, we stopped to examine a new place of worship,
sixty feet square, which is building of coral, or agglomerated sand and shells,
and is nearly complete to the roof.
This structure is carried on under the direction of A. Cunningham.
We reached the mission-house too late to embark,
on account of there being several matters yet to attend to,--though the Henry
Freeling was at the time hovering pretty near the southernmost end of the island.

9th.--Several articles being now needed from the vessel,
in order to discharge the debts contracted, and yet to be incurred, for hogs, vegetables,
and labour in the overland journeys and in the boat.
etc., it was concluded that Charles should go on board to procure these things; while I,
with the assistance of Charles Pittman, endeavoured to procure what was lacking,
and made every arrangement calculated to forward my intention
of quitting the shores of Rarotonga towards evening.
I cannot omit mentioning the kind behaviour of the
natives last evening after our return from Aroragne:
they were probably aware that the time was at
hand for our final departure from the island,
and the house of the missionary was like a fair the whole time;
they seemed to vie with each other in doing any thing they thought would please.
Several of the young women applied, through Charles Pittman,
for permission to rub my feet, legs, and knees,
in the manner in which they are accustomed to perform
the operation on the persons of their chiefs,
when greatly fatigued; saying, that I had had a very long journey that day,
and must be weary, and in need of what they could do.
I was not very partial to this method of relief,
but did not like to appear to slight their simple offer;
but I was afterwards surprised to find in how short a time all aches
and pains of weariness were entirely removed by their persevering
diligence,--several of them were at work at the same time,
and trying who could do the most.
On this island we had the satisfaction to see a great increase of population,
the children swarmed about its shores like bees, and I think Charles Pittman said,
the schools were attended by 3000 of different ages and both sexes.
The houses of the natives are mostly constructed with some degree of uniformity,
neatly white-washed, with roads to many of them made of broken shells,
and a public road for travelling upon;
and the people seem to live generally in a state of enjoyment.
The fruit and vegetables usually found upon the isles of the Pacific abound,
as the island is like a well-watered hot-bed.
The lofty mountains in its centre, obstruct the passage of the clouds,
and cause an abundant supply of rain.
But what conduces most to the comfort and real happiness of the people,
and causes an increasing population,
is the circumstance of there being no good harbour for shipping; they have, consequently,
very slight interaction with the English and American sailors,
and are therefore free from that dreadful disease, the blasting influence of which,
is fast depopulating every other isle which our footsteps have traversed:
to this truth may be added another,
originating in the same cause,--there is no rum dealer upon the island;
ardent spirit is a curse entailed upon most others by these scourges of the human race,
either publicly or privately introduced by the shipping.

The remains of the wreck of the Charles Doggett, an American vessel,
were lying upon the reefs of Rarotonga; it appears that no lives were lost; the cargo,
consisting principally of pearl shells, and cocoa-nut oil, was saved by the natives,
and the crew had been happily shipped off shortly afterwards.
This vessel we met with at Tahiti last year, she put in twice,
and was then in the very act of diffusing her rum, muskets, and gunpowder,
amongst the islands, for cocoa-nut oil, pearl shells, arrow root, etc.
She was prosecuting another voyage, and had been fitted out at Sydney, New South Wales,
where one or more of her owners reside,
and where many others reside who are accumulating wealth by a
traffic which promotes the destruction of their fellow-men.
After discharging all our debts, and affording as many supplies to our friends,
and for the benefit of the dear children, as we could spare,
we took our last meal with Charles and Elizabeth Pittman;
we then bade a final adieu to the shores of Rarotonga, and its swarthy tribes,
as to the outward, but to memory lastingly precious,
though as far distant as the east is from the west.

The Henry Freeling anticipated our movement, and stretched in upon the coast,
when the boat made its appearance;
and we were favoured to get safely on board at half-past three o'clock in the afternoon.
A+++.+++ M'Donald, and Alexander Cunningham accompanied us,
and returned with the boat again to the shore.
We got in our numerous articles without being materially injured by the spray of the sea,
and at four o'clock filled our sails and bore away to the westward;
cleared the southernmost point and its crags before dark; and at midnight,
were at least fifty miles from this interesting and highly favoured little island.
Besides Rarotonga there are four small islands inhabited,
which comprise the Hervey group; but not one missionary amongst them all.
Our friend, Charles Pittman, feeble as he is, would, I have no hesitation in believing,
have freely devoted his remaining strength to our service,
and united in a visit to them with us,
had his fellow-missionary Aaron Buzacott been at his own station at Avaruu;
but the absence of the latter deprived us of an interpreter, without which,
such a visit would have been in vain:
I think I should not have been satisfied to pass them by, could one have been obtained.
The names of these islands are, Mangaia, Atiu, Aitutaki, Mitiaro, or Mauki;
their population is estimated at 5900 people.
These islands are now and then visited by a missionary from Rarotonga;
such a circumstance must, however, be very rare,
as it can only occur when a vessel comes down from the Georgian or Society group,
to range amongst them, and collect cocoa-nut oil, arrow-root, etc.; there are, however,
some native teachers distributed among them from Rarotonga.
This group was first discovered by our countryman Captain Cook,
and was afterwards named the Hervey Islands.
It is with much satisfaction I have learned, that our valuable interpreter Samuel Wilson,
who accompanied us round Tahiti, in 1835,
is now an appointed missionary by the London society to the station of Aroragne,
on the south side of Rarotonga.

Our visit to Rarotonga cannot, I think, on various accounts,
be soon obliterated from our minds, or pass away as a tale that is told:
the retrospect of the highly favoured seasons,
so condescendingly permitted to crown the different assemblies of the people,
only brightens the more,
as the days are increased which throw the scene of such
love and such mercy still further and further behind.
The circumstance of the Henry Freeling having to beat about during the whole time,
rendered it doubly hazardous on her account,
and made our different trips to the shore much more difficult and protracted;
the boisterous state of the weather,
and the trade wind coming round both ends of the island, and then meeting,
placed the boat and ourselves in a precarious situation,
when getting in or out of the vessel;
and the wet necessarily encountered in passing to and fro by boat; these are occurrences,
which, although at the time somewhat irksome and hindering, when over,
are not worthy to be recorded;--such was the peace, and love,
and sweetness that flowed from the everlasting
fountain and source of all our sure mercies,
which even exceeded the hundred fold promised to those that leave all
for Christ's sake and his gospel:--to the praise of Him,
whose faithfulness fails not, be it spoken.
Before leaving Rarotonga,
I received several letters from some of the most
capable scholars in the school at Gnatagnia,
which were literally translated to us; one of which I subjoin as a specimen,
which will suffice for the whole, as they are nearly in the same strain.
It is from Tekori, a boy of about sixteen years of age.

[.salutation]
This is my speech to you, Daniel Wheeler,

Read it, that you may know great is our joy in seeing your face,
and in knowing your speech of God's great kindness to you.
Attend,--I will relate to you the coming of God's word to us.
We were heathens formerly,--we did not know the living God Jehovah.
At that time the devil was our god;--we worshipped him,
and did that which is agreeable to his will:--that was our condition formerly,
Daniel Wheeler.
Attend,--then arrived the season in which the word of
the great God came to us--even of Jehovah,
and the word of God spread among us in that season;--
still listen,--God sent his servants to us,
to inform us of the true way.
Then the light sprung up in the midst of us.
The word spoken by Isaiah the prophet was then fulfilled, chap.
lx. verse 1. "`Arise, shine, for your light is come,
and the glory of the Lord is risen upon you.`"
Behold, the light of Jehovah came to this land, and the light of Jehovah dawned upon us:
then the word of God spread on this land.
The children know the word of God.
Pittman taught us unweariedly, and in this likewise, behold the love of God to us.

Our friend and brother, Daniel Wheeler,
I think of the kindness of God in conveying you from your land--from Britain.
You have been directed by God to this land and that land;
you have witnessed his loving kindness,--you have seen
what has occurred in the deep,--the mighty power of God.
He will not forsake those who put their trust in Him.
Friend, when you go to visit this land and that land, we will pray to God,
that he may safely conduct you to the land where you wish to go,
and that He may carry you safely to your own land.
Friend, now go; we have met,--you have seen our face in Rarotonga,
and we have seen your face.
Observe, one thing yet remains.
When we shall be assembled with the word of God, of the blessed--in that world of joy,
the good people of Britain will know those of Rarotonga,
and the good people of Rarotonga, will know those of Britain;
and then will be known the true state of that land, and this land.
This is a little speech of compassion toward you: may you be preserved in your voyaging.
And now, may the grace of God be granted to us--even so--Amen.

[.signed-section-context-close]
From Tekori: that is all I have to say.

16th.--Since quitting the neighbourhood of Rarotonga, our course has been directed,
when the weather would permit, towards the Friendly Islands,
which lie in a westerly direction from the Hervey group,
at a distance of from eleven to twelve hundred miles;
but having now to traverse near the edge of the trade latitude,
the winds became much more unstable;
sometimes they are directly opposed to our proceeding, and often boisterous,
with as much sea as our little vessel could at times well bear.
Nothing material occurred on the passage from Rarotonga:
our devotional duties were attended to as usual;
and though Charles and myself had much to contend with, from the heat of the climate,
and our narrow limits in the cabin,
during our endeavours to draw nigh unto the Lord,--yet there is ample encouragement,
notwithstanding human weakness and frailty,
and the hindering things to which these poor bodies are subject,
for all to persevere in wrestling for the blessing,
with the noble resolution of the patriarch, "`I will not let you go,
until you bless me.`"
It was expected I believe by all on board,
that we should steer for the island of Tongataboo,
but a variety of circumstances operated upon my mind,
to produce a determination to aim in the first place at the northernmost island, Vavau:
this was so fixed with me, that I told Captain Keen, before we lost sight of Rarotonga,
the conclusion I had come to;
he made arrangements accordingly to accomplish the object in view.
At noon today, it was found from accurate calculation, that the island of Vavau,
was only distant about 102 miles.
As we were now making rapid progress towards our destination,
rolling away before a strong wind and following sea,
it was thought that the distance was too short, to warrant running on through the night,
and the more so, as the moon was too young to afford any light,
when that would be the most needed.
Our canvass was accordingly reduced, and at nine o'clock p.m., we hove to for the night.

17th.--At five o'clock a.m., bore up and made sail to the westward.
At nine o'clock we were cheered with a sight of the island,
and immediately stood for the northernmost bluff, with a fresh trade-wind in our favour.
At noon, we were abreast of the bluff,
and hauled round the different headlands as close as was prudent,
with a good look out from the mast-head for the breakers.
Although furnished with an ample number of nautical charts,
yet none afforded specific directions for approaching these shores;
and it was perplexing to find that a rough sketch printed by Mariner,
(who long resided among the Tonga Isles,
and published a history of them,) in our possession,
disagreed in toto with two first-rate charts we had on board;
and yet this imperfect sketch furnished to all appearance,
the best directions for entering Port Refuge,
although certainly never intended as a seaman's guide.
On reaching a head-land which we expected would form one side of a spacious bay,
in which we were hoping to find shelter, it was found on rounding it,
to our great consternation, that island after island began to show itself;
until every prospect of finding a port seemed closed up: it remained to be determined,
whether we should run out to sea again, or risk an attempt to find shelter,
by working into the heart of the group at a venture.
Every precaution was used to avoid sunken rocks and shoals,
and the colour of the water was our faithful guide.
In the course of a few tacks,
we seemed to be completely embarrassed amidst this host of enemies;
we looked in vain on every side for an opening to the place,
which we had before anticipated finding without any difficulty.

At last, as the sun was rapidly setting, there seemed no chance of success,
or option left, but that of taking refuge at sea,
instead of in the port that bears the name of Refuge.
Our captain would gladly have relinquished this hazardous pursuit,
and made off while there was day-light to see the way out again; but,
we had still some hope left, that the design would be accomplished,
and when as the day-light receded, that hope sickened within us,
the sight of a ship at anchor renewed it again like a charm,
and stimulated to more persevering exertion.
A second ship was now soon discovered near the first,
and seeing an English jack flying for a pilot, they both displayed the American flag.
It soon became dark, but there was as yet no anchorage, we had sounded in vain;
and though surrounded by islands on every hand there was no bottom to be found.
The place where these ships were seen, was now our aim,
and at length we succeeded in getting near enough to hail the Pacific, of Nantucket,
at anchor in twenty-eight fathoms water; but by running a little nearer the shore,
we found a sandy bottom, with sixteen fathoms upon it, which,
after tumbling about for two months since leaving the roads of Waimea,
at the Sandwich Isle Tauai, was accepted with thankfulness.
What shall we render unto the Lord Most High,
whose goodness and mercy still follow us in the way that we go?--Yes,
he delivers the poor, and him that has no helper.
What shall we say, or what shall we do, but wonder and adore,
in humble prostration of soul, the fulness and extent of that love,
which no tongue can set forth or declare: it is boundless,
as His everlasting mercy,--filling all space, and unfathomable as the ocean we traverse.
