== Chapter XXXIII.

[.chapter-synopsis]
* Tongataboo
* Meeting with the Foreigners
* Parting Interviews with the Natives and Missionaries
* Sail from the Friendly Islands
* New Zealand
* Anchor in the Bay of Islands
* Visit the Mission Family
* Native Meeting at Koua-Koua
* Desolating Effects of Interaction with the Shipping

Eleventh Month 3rd.--While on shore yesterday afternoon for exercise,
we saw many fine healthy plantations of yams coming forward;
but the poor natives are suffering grievously for lack of food at present,
and yet they do not seem to exert themselves to procure an extra quantity of fish,
which we find no difficulty in taking.

Today, sent a quantity of tracts on board the Chieftain, a London whaling vessel,
having become acquainted with her captain.
Got on shore in the afternoon,
but the state of the tides just now renders these excursions both tedious and difficult.

Taufaahau, having accomplished his object of escorting
Josiah Tubou back in safety to his own islands,
sailed again with his numerous fleet very early this morning;
but towards evening he was compelled to return by opposing winds and rough weather:
and to be ready to put to sea again, on the first appearance of a change in the weather,
he anchored his canoes in the neighbourhood of the heathen settlements,
to the very great alarm of those miserable people;
who now fully concluded he had returned to chastise them for the provoking
and insulting conduct of which they had been guilty in the morning,
when he was about to take his departure.
The missionary, however,
assured us that Taufaahau had no intention whatever of meddling with them.
From what we saw,
it is very evident that a trifling cause would at once set them all in a flame:
both parties carry warlike weapons about with them.
There are at present seventeen garrisons upon this island;
such are the fear and suspicion on both sides,
that they dare not live out of their strong holds.
The heathen party in Tongataboo,
although much superior in number to those who call themselves Christians,
are the weaker body, in consequence of their own internal and perpetual broils,
and the dreadful ravages of disease brought amongst them by the shipping;
which is indeed as the "`noisome pestilence,
that walks in darkness,`" and as "`the destruction that wastes at noon-day.`"

These remarks have reference to Tongataboo only:
at Vavau and the other islands which compose the Hafulauhau group,
and those of the Haabai,
the people almost if not altogether are subject to missionary control,
with their king at the head of religious affairs, nominally at any rate.
It is from these islands that the heathen of Tongataboo, have every thing to fear,
while Taufaahau lives: they know that he is a desperate warrior,
and never fails to carry all before him, when once roused up.
Josiah Tubou is a very different character, and though leaning to the missionary party,
is more despised by the heathen, than feared;
his power is much greater than that of Taufaahau, who being a much younger man,
is very submissive and subservient to him.
If Tubou inclined to go to war, the other would probably unite with him at once;
and furnish strength and skill not to be resisted, which the heathen are well aware of.
It seems that a number of these poor people have
now gone on board the canoes of Taufaahau,
that they may get to Vavau, and Lifuka, and become Christians,
without risking the loss of life from their own kindred;
and we are told that many of them would be glad to lead peaceable lives,
but dare not join the missionaries here, for fear of their neighbours:
at the same time the different tribes are imperceptibly mingling together by marriages.
All these circumstances serve to diminish the strength of the heathen party,
and gradually to prepare them to renounce their abominable practices.

4th.--From the swell of the sea setting directly upon the landing-place for boats,
we remained on board all day; and Josiah Tubou, with his brother Abraham,
spent the afternoon on board with us.
I feel comfort when looking back,
that the opportunity of speaking to the people last First day,
was not suffered to pass over unembraced on my part.
It is plain now, that if the return of another First day had been waited for,
or an excuse from the state of the weather been listened to,
the precious moment would have been lost forever; and instead of a peaceful retrospect,
now at seasons vouchsafed in mercy to a poor unworthy creature,
an accusing blot of anguish would have rested upon my mind;
which the few yet remaining days of my pilgrimage would
have been too short to obliterate.
It was a remarkable circumstance,
that so many hundreds of the natives should be brought together at Lifuka,
and again at Tongataboo; with many of whom we had become acquainted,
first at Vavau and its neighbourhood, and at Tongataboo.
I recognised with heartfelt pleasure, Lazarus, the chief of the island of Otea,
also David Afu, the chief of Haalaufulu, and others, as people dear to my best feelings.
We have now been here more than a fortnight,
and I do not yet see a way open for leaving the island,
an event anxiously desired by some on board,
on account of the exposed situation of the anchorage, when some particular winds set in.
Two English vessels, and one American, have anchored off the heathen settlements,
while we have been here;
there the sailors can indulge their licentious habits unrestrained;
but as a striking proof of the utility of missionary establishments,
it is not so at Nukulofa.
I desire to stand in humble resignation, as to any further proceeding here,
or to leaving the place, and bending our course towards New Zealand;
and I trust to be enabled to decide with clearness before we sail.

5th.--The weather being more favourable for landing,
we went on shore at four o'clock p.m.;
and having found my mind drawn towards the
remnant of English and other white people here,
I told James Watkin on his inquiring about arrangements for tomorrow,
that I had nothing in view towards the natives; but to sit with the English,
seemed to be my present business, if that could be brought to bear.
This was readily assented to.
I have felt a poor creature indeed, for the last day or two,
owing perhaps to the increased heat of our vessel under deck; but the Lord can deliver,
and strengthen him that has no might, either in body or mind;
and can at his pleasure make quick of understanding in His fear,
those that trust and hope in his mercy.
May He be graciously pleased to cause the opportunity tomorrow,
to be a time of visitation to some; cause the earth to tremble at His power and presence,
as in days of old, when the sea saw it and fled, and Jordan was driven back;
so may every thing in us, comparable to the unstable element, flee before Him;
and the ever blessed truth reign over all to His glory.

6th. (First day.)--Landed about ten o'clock in the forenoon:
the natives were coming from their meeting as we approached the shore:
soon after this the white people assembled together.
On going into the place appointed for us to meet in,
I observed that James Watkin had taken a side seat,
to show the people that he had no part to take in that meeting,
and as no hymn book appeared in the hands of any one,
it seemed as if some pains had been taken to inform them,
that it would be held after the manner of the Society of Friends.
I sat down near a table, and as those who attended came in,
they joined in the silent sitting of the rest.
We had not remained long in this exercise,
before I was made sensible of that power being nigh,
which alone can soften the rocky heart,
and cause the earthly nature in man to bow before it; and abiding under it,
I had in due time to revive amongst them the language of the patriarch Jacob,
when wrestling with the angel,--"`I will not let you go,
except you bless me;`" desiring that we might
individually imitate his noble example this morning,
and like him prevail, and receive that blessing of the Lord which makes truly rich,
and satisfies the hungry wrestling soul with favour.
It was then with me to state the true intent and meaning of
our sitting together in silence before the Lord,
and the excellency of waiting upon God,
if we believe in the promise of the Most High God,
in the new covenant of life and power,--that he would write his law in the heart,
and put it in the inward parts of man; and that he would be their God,
and they should be his people: and they shall no more teach every man his brother,
and every man his neighbour, saying, "`Know the Lord,
for they shall all know me from the least of them,
unto the greatest of them,`" says the Lord; "`for I will forgive their iniquity,
and remember their sin no more.`"
We, therefore, desire to know the Lord for ourselves;
and the only way to come to this blessed knowledge, is to obey his commands and be still.
"`Be still, and know that I am God: I will be exalted among the heathen;
I will be exalted on the earth.`"
Here is the great and glorious privilege of the gospel dispensation:
"`the law of the spirit of life in Christ Jesus,`" is written in every heart,
to make free from the law of sin and death.
None are left without a manifestation of the Spirit of Christ Jesus;
by which all have access unto God the Father, who is a Spirit,
and must be worshipped in spirit and in truth.
We, therefore, in our religious meetings, have no confidence in the flesh;
we do not look to man as our teacher, whose breath is in his nostrils,
to assist us in the worship of Almighty God;
but we wait for the influence of the Holy Spirit of the Lord Jesus,
to prepare our hearts to perform this worship aright.
A manifestation of this heavenly spirit of grace is mercifully given unto all men;
it is "`the grace of God which brings salvation,
and has appeared unto all men,`" teaching all men that believe in it and obey it,
to deny ungodliness:
even the heathen have a measure of this heavenly gift dwelling in their hearts; by which,
and through which,
they can worship God in spirit and in truth;--"`for I
will be exalted among the heathen,`" says the Lord,
"`I will be exalted on the earth.`"

Before sitting down,
I told them that I did not feel at liberty to leave the
island without seeing those of my own colour,
to set before them the responsible station they held,
and how much depended upon them and lay at their door,
as examples to the surrounding natives:
the superior advantages they possessed over these would
be heavy in the scale of condemnation,
if corresponding fruit were not brought forth.
They professed to be Christians; had been brought up in Christian lands;
had long had in their possession the Holy Scriptures, a blessing invaluable,
for which we cannot be thankful enough: but they are a sealed book,
until our understanding is opened by the same Holy Spirit,
which inspired those holy men who gave them forth: even the followers of our Lord,
when He was upon the earth, could not understand them,
until their understandings were opened by Him.
Without Him, we can do nothing.
The Jews had the Scriptures; and yet they were the enemies of Him,
of whom they so faithfully testify: they felt themselves secure,
and thought they had in them eternal life;
but what said the Prince of life,--"`Search the Scriptures,
for in them you think you have eternal life; and they are they which testify of me:
but you will not come unto me that you might have life.`"
So that although they are an inestimable gift out of the divine treasury,
bestowed upon man by the Holy Spirit, for his greatest outward heavenly comfort,
to strengthen his hope in the promises of God, of life eternal through that Saviour,
who is Christ the Lord,--and are "`profitable for doctrine, for reproof, for correction,
for instruction in righteousness, that the man of God may be made perfect,
thoroughly furnished unto every good work;`" and although they are
able to make wise unto salvation,--it is only "`through faith,
which is in Christ Jesus,`" of whom they so abundantly testify from their earliest pages.
And yet,
if we could repeat them from the beginning of Genesis to the end of the Revelations,
they cannot save one soul, nor blot out one sin.
But they direct us unto Him, unto whom all power in heaven and earth is given:
who only has the words of eternal life; who is Himself that eternal life.
To Him, then, we must go to be saved; in Him we must believe;
to His Holy Spirit in our hearts we must turn, whose light shines in all.
His long-suffering and goodness will lead us to repentance; when we look on Him,
whom we have so grievously pierced,
and from whose merciful reproofs we have so long revolted,
and which we have disregarded with hardness of heart and unbelief in his power to save.
This light in us, will not only set all our sins in order before us,
that we may repent of them, and forsake them;
but as we abide under the righteous judgments of the Lord's redeeming love, they will,
though they may have been as scarlet and crimson, be made white as snow and wool,
by the blood of the Lamb, and be remembered no more by Him,
who redeems our life from destruction,
and crowns us with loving-kindness and tender mercy, for His great name's sake.
Behold then the blessedness of those, who know the Lord for themselves;
who have come to the knowledge of the only true God, and Jesus Christ whom he has sent,
by believing in the power of the Holy Spirit,
and sitting under its heavenly teachings:--"`this is life eternal.`"

The foregoing, although but a part, contains I believe,
the substance of the whole I had to say to them.
We remained on shore until sunset,
by which time the water had arisen high enough
to allow our boat to come close to the shore.

7th.--Fixed with James Watkin to visit Fakafonua the heathen chief, tomorrow,
in his own fortress of Maofanga.

8th.--Landed early, and called upon James Watkin,
who accompanied Charles and myself to Maofanga; the sun was very hot,
and having little or no shelter, the walk was very fatiguing,
though the distance is comparatively short.
On reaching the fortress, we found the entrance closely blocked up;
and the keeper inside could not be prevailed upon to open to us,
declaring that Fakafonua was on board the American ship,
which we afterwards found to be correct.
James Watkin returned with us on board; and on canvassing the subject over,
he advised me not to attempt another visit.
I did not however feel satisfied, or as if I had done all that might be done,
without making further trial;
and proposed to James Watkin our endeavouring to fix a time with the chief for my coming,
if that could be accomplished,
by sending a confidential person over for the special purpose of doing it.
We landed in the evening, and after some inquiry, Nathan a nephew of the king,
was fixed upon to arrange the business altogether.

9th.--Nathan having fulfilled his engagement, came off to us at an early hour, to say,
that he had been to Maofanga,
and succeeded in getting into the fortress from a bush entrance;
but could obtain no tidings whatever of Fakafonua.
On considering the matter I concluded to land after breakfast,
and inquire whether there were any other places where we could go,
which was done accordingly.
James Watkin said that the natives residing to the westward,
came to the meeting at Nukulofa,
and that the few heathens towards the other side of the island,
were scattered at distances too considerable for us to attempt to go in search of them.
With me, however, there yet remained something to be done;
and I believed it safest for me to tell James Watkin,
that notwithstanding the trouble already incurred,
and the disappointment we had witnessed, I should like to go again to Maofanga,
and if our object again failed, as regarded seeing Fakafonua,
I believed that I should then have done what I could.
It was not a pleasant task to tell James Watkin this,
as I knew he was very averse to having any thing further to do with this man: I believe,
however, he saw that I was bent upon going again to Maofanga,
and kindly agreed to make another trial to accomplish what I had in view.

On reaching the fortress we found the entrance blocked up as before;
but James Watkin proposed that we should try another passage, more private,
which he had got a hint of: this we reached at last, and found it open,
but so narrow that only one person could pass through at a time.
We soon met with a native who told us the chief was there;
and having obtained directions to his house, a short walk brought us to the place,
where we found seven or eight American sailors hanging about.
It was not long before Fakafonua himself made his appearance.
Having seen him on board the Henry Freeling,
we were not altogether strangers to each other.
I took a seat on a log at his right hand,
and the natives took their stations upon the floor,
with the American sailors and some others.
James Watkin entered into conversation with the chief,
while I endeavoured to keep my mind retired in a waiting frame.

At length I requested that Fakafonua might be told,
that I had been among many of the islands in the Pacific Ocean
with glad tidings of great joy to their inhabitants,
and I was not satisfied to leave Tongataboo,
without giving him a like opportunity with others to repent and believe the gospel:
believing that it was not too late for him to be saved,
if the terms of offered mercy were accepted on his part;
for the Almighty Creator of man would have all to be saved,
and that He had provided the means, that all might repent and live,
by his Son Jesus Christ, the light of whose Holy Spirit shines in every heart.
I was fully persuaded, that at times he had known something of this light in himself,
which had shined upon and shown him his sinful state and condition,
and which had reproved him, and convinced him of his evil deeds;
and though in his wickedness and hardness of heart he had
rejected and resisted the strivings of the Holy Spirit,
grieved it, and wounded it,
yet a day would overtake him at last when its
convictions would be too heavy for him to bear.
"`The spirit of a man may sustain his infirmities,
but a wounded spirit who can bear?`" I exhorted and entreated him for some time,
to repent, believe, and obey the gospel;
to turn to the light of Christ Jesus in his own heart, follow it, and live;
he would then no longer walk in darkness, but in the light of life.
Fakafonua interrupted me once or twice to express his thanks; and when I stopped,
he told James Watkin again to thank me, and said, 'I know very well it is true.
I have thought of these things, and understand,
and am convinced that it is better to be a Christian; but I can never be one,
I am too great a sinner to be saved:
I must remain as I am.' I told James Watkin to tell him,
that as he knew and understood these things,
his condemnation would be greater on that account;
and certainly his destruction would be of himself.

James Watkin then said he thought I had better speak to the sailors,
who sat and listened with great attention, I replied,
'there is no occasion for that,--they know very well.' James Watkin replied,
'he thought they did not.' 'Yes,' said I, 'there is not one of them, but knows very well,
that he ought to fear God; and knows when he commits sin, and that he ought not to do it,
for that which may be known of God, is manifest in man:
He has showed it unto him.' Afterwards I found my mind drawn towards these men,
and I was strengthened to declare the Truth among them as it is in Jesus.

We then took leave of this poor benighted heathen chief,
who with his people thanked me and shook hands very kindly;
and I believe we parted better friends than we met.
We were offered the juice of the cocoa-nut, and the stupifying kava,
both which were declined.
Although nothing may come of this visit, yet it is not for me to calculate upon results,
but to leave them.
I felt relieved, and rejoiced that I had made the effort;
and I believe that James Watkin was not sorry at having accompanied me on this errand,
now that it was well over.
On looking round, my way seemed now clear for leaving the island,
and before reaching the mission-house, I told James Watkin and Charles,
that I knew of nothing to prevent our sailing on the following day.
We called upon Thomas Wellard and his wife,
and found their luggage could be embarked in the afternoon,
and that they had kept themselves in readiness
to leave their habitation at a short notice.

We returned on board before dinner, and informed Captain Keen,
that all things would be ready with us, for leaving the roads of Nukulofa tomorrow.
In the afternoon we collected our linen, etc., from the shore,
and took leave of James Watkin's family,
he himself intending to be on board at the time of our departure.
Isaackee the pilot, was agreed with to conduct us into open water,
and we bade a last farewell to a mass of the poor natives, men, women and children,
who had crowded to the spot of embarkation, having learned probably from the pilot,
that we were about to leave their shores finally.

10th.--Our decks were crowded at an early hour with the natives,
bringing vegetables and fowls,
and a collection of their war clubs and other implements of destruction,
which we rejoiced to take out of their hands.
The morning was, for the first time since arriving at Tongataboo, calm and cloudy.
It afforded, however, an opportunity for the natives to dispose of what they had,
which the usual trade-wind would wholly have prevented,
as they must have hurried out of the vessel on our beginning to move.
James Watkin and our passengers came on board before eight o'clock;
but the forenoon proving showery, and windless,
there seemed no probability of our getting off to sea.
James Watkin returned to the shore, intending to come off again tomorrow morning,
to see us under weigh; but at three o'clock p.m., the clouds began to disperse:
a signal was made quickly for the pilot,
and a nimble native dispatched to the mission-house to state that we were about to sail.

By the time the last anchor was up, the parties were on board;
and leaving the last of the Friendly Islands, (though not the least of them,
as an object of our tender solicitude and regard,) we steered
through the wide spreading reefs towards the open ocean.
James Watkin accompanied us a considerable distance,
until the shore of Nukulofa could be but dimly seen;
but however painful the task of separating, the moment was come for it to be done.
We waved to each other, while our movements could be seen in the twilight;
and I believe we parted with sincere regret on both sides.
If I mistake not, we can mutually acknowledge--'though lost to sight,
to memory dear.' The day beginning to close upon us, and the wind continuing light,
rendered it impracticable for the Henry Freeling to get
completely through the passage before dark,
when our faithful compass became as heretofore, the only guide remaining to us.
Our pilot, who had been at the mast-head for three hours looking out for the reefs,
left his post when the sun went down, wishing to be set at liberty,
in order to take up his lodging upon a small island at no great distance from us,
as he could not get back before morning to his own island of Tongataboo;
and if he had been compelled to continue on board until we had got completely out to sea,
which is the common usage,
it would have been too dark for him to have found the small island,
and he might have perished in his canoe, if the wind had got up strong.
He told us in broken English, but very intelligible,
'Me no like go dead in canoe.' This is the same man who ran no trifling risk
to gain us admittance into the heathen settlement at Mua.
He was of course well paid for his useful services,
and his request to leave us immediately granted.
Towards ten o'clock p.m.,
the breeze freshening up we got nicely clear of the island of Tongataboo,
and its many lurking snares; and before midnight hauled round its most western point.

11th.--Stood to the south-west, close to the wind.
I stood resigned as to our destination, whether it should be New Holland or New Zealand,
and endeavoured to leave it to my heavenly Father to
dispose of us according to his own good pleasure;
believing if it was right for us to go to New Zealand, we should be enabled to fetch it,
though the wind was opposed to it at that time.

12th.--My mind is much weighed down this morning, with a load of exercise,
which none about me know of; and this is not a little aggravated, by an open avowal,
that nearly every one on board was in hopes we should not go to New Zealand.
It was suggested to my mind by the grand adversary,
that as the wind was unfavourable for New Zealand, we might safely keep away for Sydney,
in New South Wales, for which it blew sufficiently free.
But I was preserved from listening to this, and strengthened to conclude,
that it would be time enough for me to bear up when the distance was accomplished,
and no prospect remained of fetching the Bay of Islands.
Thus strengthened and supported, we held on our way.
Soon after this, the wind became more favourable;
but the current and leeway together had set us so far to the westward,
that it was deemed advisable to run still further to leeward
to make sure of escaping the Pilstart's and Nicholson's shoals.
This circumstance, to appearance,
would almost set aside the New Zealand question altogether.
When night came, our captain was so fearful of the shoals that the sails were reduced,
and the head of the vessel turned again towards Tongataboo: this was mortifying, though,
perhaps, the safest policy, notwithstanding the wind had now become much more favourable.

13th. (First Day.)--A fresh wind sprung up from the old trade quarter, at noon:
the latitude 23° 37' south, by observation.
Our sailors were collected twice in the day for devotional purposes.
Today is the third anniversary of our leaving London; we reached the Henry Freeling,
soon after nine o'clock p.m., at the Lower Hope in the Thames.
Many have been the trials and conflicts permitted to overtake us;
but abundantly more have been the mercies of the Lord since that time,
overshadowing us by night and by day:
and truly our strength has been proportioned to
the necessity in the darkest hour of dismay.
There has been no lack of any needful thing; all our needs have been abundantly supplied;
and that loving-kindness which is better than life,
has at seasons been eminently displayed for our comfort and consolation;
causing the Lord's own work to praise Him,
and enabling us to give thanks at the remembrance of his holiness; and I trust,
in humble resignation and devotedness, to renew our covenant, and say,--"`Not my will,
O Lord, but yours be done:`" if you will be with me in the way that I go,
here am I a poor unworthy creature.

14th.--Beautiful weather, with the wind free.
This day completed 180° of west longitude.
At noon we were in i 79° 54' east longitude, latitude 25° 8' south, Cape Breton;
New Zealand distant 640 miles.

16th.--Yesterday, the latitude at noon 26° 59' south.
Today the wind baffling: a heavy squall and the threatening appearance of the atmosphere,
with a heavy swell of the sea from the southward, brought us under double-reefed canvass;
but the wind did not materially increase.

19th.--Since the 17th the weather has been rugged, and the wind so scant,
that there seemed considerable doubt whether we
should fetch the north Cape of New Zealand;
but we still persevered in keeping close to the wind.
Today the weather is more moderate, with less sea, and the wind in a slight degree,
more favourable.
We sensibly feel the cold, since coming a few degrees to the southward of the tropic.
We trust that we shall not be forgotten by Him, who cares for the sparrows,
and causes the day-spring of the morning to know his place.

21st.--Yesterday, assembled the crew for devotional purposes, both before and after noon.
The weather clear and the wind gentle from south-east to east south-east.
Today several birds have been seen, of kinds that indicate that land is not very far off;
and in the afternoon it was rumoured to be in sight,
but this could be nothing more than a fog-bank.

22nd.--In the afternoon land was discovered from the masthead,
but too distant to determine, with certainty, whether it was the North Cape or not.

23rd.--The wind being light and scant for our purpose,
it was noon before we got close in with the
coast a few miles to windward of the North Cape.
Towards evening the wind became more favourable, but there was so little of it,
that we could not approach the entrance of the Bay of Islands,
before the breeze died away altogether.

24th.--Becalmed until nearly noon, when a breeze sprung up from the north westward,
which soon freshened, and enabled us to push for the Bay.
Before six o'clock, anchored in little more than three fathoms water, on a muddy bottom,
near the entrance towards Koua-Koua, after a passage of fourteen clays from Tongataboo;
thus we have to acknowledge that through the lovo and mercy of Him,
who upholds all things by the word of his power,
we have been brought in safety to the desired haven: the Lord of Hosts is his name.
Several ships under English colours are near our vessel, belonging to London and Sydney,
and one American whaler.
Before dark some of the principal store-keepers came on board;
it appears from their statements, that an internal war is raging amongst the natives,
and that some of the missionary stations have been totally destroyed,
in the neighbourhood of the Bay of Plenty; and the country around laid waste.
I find that James Stack, a missionary with whom I was acquainted in England,
had been compelled to fly, (with his wife,
who was then on a bed of weakness,) from the
scene of blood and carnage to this neighbourhood.
We learnt from a person, lately arrived from Sydney,
that our dear friends James Backhouse and George W.
Walker were in that neighbourhood a few weeks ago.
A few of the natives have been on board,
but their barbarous and filthy appearance is enough to discourage any stranger; perhaps,
these may not be a fair specimen, because of their interaction with civilized nations,
and their acquaintance with rum.

25th.--In the morning five or six natives came off, but with the exception of a hog,
they had nothing to sell worth purchasing.
Two of them appeared to be much out of health with the prevalent influenza, which,
it is said, has been very general.
We intended to give each of them a dose of salts; the first who tried them,
drank nearly the contents of a tumbler glass, but the other before venturing,
would taste only what his comrade had been drinking,
and was quite satisfied with what was remaining at the
bottom of the glass without wanting a further quantity.
They seemed desirous to possess a steel pen, and one was given to each,
with which they seemed pleased.
They appear to suffer very sensibly from the cold, as if a large dirty Witney blanket,
worn loosely about the shoulders and body was insufficient for them.
Before noon the Post-master Gilbert Maer came on board;
and very kindly offered to conduct us to the
resident missionary at the station of Paihia,
engaging to call for us in his own boat, which he did accordingly:
accompanied by our passengers we set out,
and landed opposite to the missionary establishment, consisting of several good houses,
occupied by its members, also one place of worship: this belongs to the Church Mission.
The senior and only ordained minister at this place, Henry Williams, being from home,
endeavouring to restore peace among the contending tribes to the southward,
we were conducted to the habitation of the lay minister, Charles Baker:
we were kindly received by his wife, who was engaged amidst a large family,
one member of which was not more than a year old.
Before tea was finished, our host arrived, and confirmed the kind treatment of his wife,
in a friendly manner: when the repast was over, Charles Baker took me into his study,
when the object of my visit was fully entered into,
and an offer made me of all the assistance in his power.
After attentively reading my certificates, he said,
he hailed me as a minister of the gospel, and a father, etc.
Before leaving Paihia, we visited for a short interval the wife of the absent missionary,
Henry Williams, formerly a lieutenant in the British navy: they have ten children.
We were much gratified with this family.
It proved a very dark and rainy night, but we got well on board.

26th.--In the forenoon Charles Baker came on board,
and while with us proposed our calling upon the British resident, James Busby:
having known his father when at Sydney, this offer was gladly accepted.
James Busby is the only person legally authorized to act for the British government here;
but as he is wholly destitute of power, instead of being recognized as Consul,
he is styled the British resident; as such, a visit was due to him,
as well as on account of his being our countryman.
We were kindly received, and remained several hours under his roof,
before he would permit us to leave him.
His wife and children are now on a visit at Sydney.
My Charles having a serious pain in the side, owing, perhaps,
to the wetness of the preceding evening, remained on board through the day;
but on my return to him in the evening I found him much recruited.
Finding, while with Charles Baker,
that there would be on the morrow a good opportunity to
visit one of the native congregations,
and that a young man, who is a competent interpreter,
would be furnished with a well-manned roomy boat,
I did not feel satisfied to let the opportunity pass away without availing myself of it.
The prospect of moving, as it were, upon new and untried ground felt indeed weighty,
but I was enabled to cast my burden upon the Lord;
for truly he has hitherto sustained me,
and borne up my head amidst the floods of many waters.

27th. (First Day.)--We left the Henry Freeling about six o'clock a.m.,
in a boat belonging to the mission, which had arrived with our interpreter.
It had lightened and rained most of the night,
and the morning had every appearance of wet weather.
It would have been a relief to me,
if my Charles could have been satisfied to remain on board,
but I did not like to urge it upon him,
being aware that he was desirous of attending the meeting:
though I rather dreaded the consequences if he got wet,
and thought if the rain kept off until after the meeting,
and we had dry weather to return to our seats in the boat again,
it was all I could desire.
After rowing about two hours and a half,
we reached the point of destination at Koua-Koua,
and found on our arrival at the building, that the customary service was going forward,
conducted by a native teacher: he was at the moment, as we were informed,
reading the nineteenth chapter of Matthew: we went quietly in, and sat down near a table.
This was a rough building, lately erected, with a few seats for the females only.
When the native preacher had finished,
William Colenzo explained to the people the cause of our visit,
which we could ascertain by the names of the different
islands in the Pacific which he mentioned,
to enable them the better to understand its real object.
We had not agreed on any particular mode of proceeding; but when a suitable time arrived,
I stood up by his side, leaving the event to my never failing heavenly Helper.
After a solemn pause,
I warned the people of the necessity of our
humbling ourselves under the mighty hand of God,
the judge of the whole earth, whom they had professedly met together to worship.
"`God is a spirit,`" and without the aid of his Holy Spirit, we cannot draw nigh unto Him.
How can we worship Him in spirit and in truth,
without the help and assistance of the Holy Spirit of truth,
when we cannot of ourselves think a good thought, or restrain an evil one.
After enlarging on the nature of true spiritual worship,
I had to turn them to the Holy Spirit of the Lord Jesus--the
light of truth which shines in every heart.
My heart was greatly enlarged on this occasion,
though a very poor empty creature on going into the meeting.

When the meeting was over, most if not all the people, came about us to shake hands,
which though somewhat irksome to my exhausted frame,
was much to be preferred to the practice common among
the New Zealanders,--of rubbing noses together;
of which we only witnessed a few specimens among themselves.
I felt unwell in the morning, before leaving the vessel, and much cast down;
but was now greatly relieved, though pain still continued in my head.
The rain kept off until we had got through the coarse herbage
and rushy plants on our way back from the meeting;
but we had no sooner resumed our seats in the boat than it began to drop,
and soon fell smartly: we were, however, well prepared for it,
so as to keep ourselves comfortably dry over head, and about the seats of the boat.
The Lord sustained me through all this day,
and magnified his own name among the people at the meeting.
It was indeed a day which the Lord had made memorable to myself, for divine favour;
and on which I completed my sixty-fifth year.
Thus is the thread of my life lengthened out; and O! says my soul,
that it may be to the praise and glory of Him,
who has so marvellously redeemed it from destruction,
and crowned me with loving-kindness and tender mercies.
How can I sufficiently declare unto others, what has been done for myself;
that they also may come to taste and see for themselves His goodness and His love;
and be able to say from heart-felt living experience,
"`mercy and truth have met together, righteousness and peace have kissed each other!`"

In a letter to a friend in England written from the Bay of Islands some weeks afterwards,
the following passages occur:--

The day my sixty-fifth year was completed,
I was strengthened to proclaim the glad tidings of the gospel, for the first time,
to a body of New Zealanders at the Koua-Koua station, through an excellent interpreter,
to my own peace,
and I trust the exaltation of the dear Redeemer's kingdom in the hearts of the people.
My soul rejoices in that I have lived to this time, and to see this day,
though truly life is only desirable, as we are found living "`unto Him who died for us,
and rose again.`"
And although bound by earth's tenderest and strongest tie, that of a precious family,
whose present and eternal welfare claims our earnest prayer and anxious thought; yet,
without we are living "`unto Him who died for us,
`" our prayer and solicitude are all unavailing;
because if we are not living unto Him, he lives not in us; and therefore we receive not,
because we ask amiss, in our own way and will of self, and not in His name, His power,
and for His sake, who died for us and rose again.

"`Verily, verily, I say unto you, he that believes on me, the works that I do,
shall he do also; and greater works than these shall he, do,
because I go unto my Father.`"
John 14:12. In the first place,
have we believed in the power of the Spirit of the Lord Jesus,
and witnessed it to work mightily in us!
Have we known those great works fulfilled in us,
which are promised to him that believes in the Son,
when He shall have gone to the Father? Have we
faithfully resisted all the temptations of the enemy,
and overcome,
as Christ overcame? The blessed Saviour of the
world "`was in all points tempted like as we are,
yet without sin.`"
"`He knew no sin, though made to be sin for us.`"
And if we, who are born in sin, and have lived in sin,
shall endure temptations at all points, and overcome as He overcame,
the works that He did, we shall have done also,
and shall have witnessed our part of the greater works that should be done;
not in our own strength, or might, or power, but through believing in Christ,
in the power of the Holy Spirit of the Lord Jesus in our hearts,
strengthening our inner man "`unto all patience and long suffering,
with joyfulness,`" to resist every temptation of the enemy,
being stedfast in the faith that works by love and overcomes.
"`The works that I do shall he do also, and greater works than these shall he do,
because,`" said Christ, "`I go unto my Father.`"
After his precious blood was shed for poor, lost, sinful man,
He "`ascended on high`" to his heavenly Father,
"`led captivity captive,`" and "`received gifts for men; yes,
for the rebellious also,--that the Lord God might dwell
amongst them:`" and it is through these inestimable gifts,
received of the Father, that these great works in us are accomplished.
"`The Comforter,
which is the Holy Spirit,`" is thus sent by the Father in the name of Him who said,
"`because I go unto my Father.`"
Now if we have received this promised Comforter in the name of Jesus,
let us "`pray without ceasing:`" this name is the power and efficacy of prayer,
and what we ask in this name, we shall receive,--"`because I go unto my Father;
and whatsoever you shall ask in my name, that will I do,
that the Father may be glorified in the Son.
If you shall ask any thing in my name, I will do it.`"

28th.--The weather rough, and to us cold.
Some of the natives came on board in the afternoon.
Being desirous of purchasing a canoe paddle as a specimen,
I was very soon offered one for a shilling.
Having no money about me I went below, and found some quarter dollars,
of rather more value than a shilling each.
One of these quarter dollars was given, and a paddle received in return;
but the man perceiving that I had still a quarter dollar left,
made signs that he wished to have that also.
I supposed for another of his paddles, which he held in his hand;
but on giving him the money, and taking hold of the paddle at the same time,
with a stern countenance he refused to let me have it,--
keeping both the quarter dollars for one paddle only.
I thought it would not be well to suffer this imposition,
and demanded one of my quarter dollars back again; but he persisted in retaining both.
The other paddle was then returned to him, which he took into his hand,
and I then insisted by signs on having my money back again,
and the bargain made altogether void.
He hesitated for some time; but seeing that I was determined to carry it through,
at last returned me the money, and we parted without any further trafficking.
I have no doubt that he will behave in a more reasonable manner when he comes again.
Upon inquiry, I found that nothing will do with these people, but firm decided measures;
they are daring, ferocious,
and insulting if they think that a stranger is afraid of them,
and are sometimes prompted to commit outrages; but calmness,
and steady firmness generally prevail with them.

29th.--Breakfasted early, and proceeded to the missionary station at Paihia,
where taking in Charles Baker, we pursued our route to Tepuna,
where the first missionary station was originally established.
Here we saw John King, one of the first missionaries that trod the shores of New Zealand,
but now so far advanced in years, as to be considered at liberty from the general work.
He has a family of ten children;
the two oldest sons are cultivating land on their own account.
The natives now surviving, are so few, and widely scattered,
that Tepuna is now scarcely considered one of the stations.
Our visit did not seem to amount to much more than just seeing the family,
by whom we were kindly received and entertained.
They appear to have taken up their residence here for life.
At one time, a considerable congregation used to assemble,
but the whole is now laid waste, and the natives, owing to war and other circumstances,
seem swept off the soil.
By the wreck of the establishment now remaining, it is obvious that this station,
at one period, must have been an important one.
We returned on board by six o'clock p.m. Before parting with this ancient missionary,
he asked me, if I had with me, No Cross, No Crown, of which I thought we had a copy:
as he seemed desirous to see this book, from a former knowledge of it,
care was taken to forward the volume,
the receipt of which was afterwards gratefully acknowledged.

Tomorrow we expect to go to Korarareka,
but are a little apprehensive from every appearance at present,
that this will turn to small account.
Today, sent a parcel of tracts on board the Nimrod whaler, of Sydney,
and the American ship Martha, of Nantucket, also a whaling vessel.
Arrived, the Diana South Sea whaler, from London in sixteen weeks.

30th.--The day being cold and showery,
and there being no prospect of any opportunity of speaking to the people,
I seem unwilling to run any risk by going to Korarareka, merely to look at the place,
which is all that the journey holds out.

This afternoon a large ship beat into the bay; her name not yet ascertained.
The pleasure formerly arising, on the first glance of a vessel,
more especially when under the flag of our own nation,
is now superseded by feelings bordering upon disgust,
from a knowledge of the accumulated weight of sin and wretchedness they are
introducing amongst this already depraved and degraded race of barbarous natives;
who, like those of all the isles we have heretofore visited, with one solitary exception,
are rapidly wasting from the face of the earth,
by loathsome disease brought amongst them, and renewed again and again,
by these circulating mediums of evil.
In this dreadful picture, the noble natives of the Friendly Islands are not included,
except at some of the heathen settlements at Tongataboo.
At the other islands of that group,
the interaction with shipping has been but small hitherto;
but it is greatly to be feared that this evil is on the increase.

The majority of the people of England,
and that of the most virtuous part of the community at home,
little know the ravages their own countrymen are
making in these distant parts of the world,
nor can they possibly estimate the depth of the misery,
suffering and aggravated distress they are inflicting
upon these unhappy and helpless islanders.
I have no doubt that there are many who, if they could see what we have seen,
would wash their hands of the guilt of partaking of luxuries,
and even of supposed necessaries of life,
furnished from distant and foreign climes through such a channel;
much less be found deriving a profit through the exertions of these agents of Satan,
who are thus extensively and destructively contributing
to afflict the human race wherever they go.
I would say to all, individually, who love the Lord Jesus in sincerity,
and are openly professing to follow Him before men,--"`cry aloud, spare not,
lift up your voice like a trumpet,`" and make known the transgression of the people,
and the magnitude of their sin.
"`Let every one that names the name of Christ depart from iniquity
for the Lord himself will assuredly plead the cause of the afflicted
and helpless,--He will hear the voice of their weeping,--He will
regard their supplication,--He will receive their prayer.
When going last First day to the meeting at Koua-Koua,
we met a native taking his wife or daughter in his canoe, to one of the ships.
Our young friend and interpreter remonstrated earnestly with him,
and endeavoured to dissuade him from his dreadful purpose, but it was all in vain,
the man pursued his wretched and miserable errand to the bay.
The chiefs are the principal contractors between the parties,
and reap the reward of iniquity, which, though comparatively small,
is sufficient to induce these miserable people to
continue their infamous and abhorrent traffic,
which is regularly systematised through the bay: a few hours only elapse,
after the arrival of a vessel,
before she is amply furnished with these poor devoted victims.

Twelfth Month 1st.--In the forenoon we sat together as usual,
and were favoured to feel a degree of strength sufficient to turn the battle to the gate,
and check the torrent of dissipating thought, that prevents the sacrifice from arising,
which is acceptable only, when offered in spiritual purity.
In the afternoon went to the mission-house at Paihia; while there, Henry Bobart,
a missionary and an ordained minister of the Church of England arrived,
sent apparently on purpose to conduct us to the Waimate settlement.
The fatigue of this journey, though considerable, would shrink into nothingness,
if any thing bordering upon certainty might be looked for,
of an opportunity being realised for the exaltation of
the dear Redeemer's kingdom among the people;
but from what we have already witnessed,
this place is more an establishment of missionaries and their families,
than of a body of seriously disposed natives.
It will be cause of rejoicing if it proves otherwise; but without going over the ground,
the retrospect at a future day may be darkened with gloom,
from a consciousness of not having done all in my power to serve the best of Masters,
in the best of causes,--by losing an opportunity which can never be regained,
of declaring Christ in man, by His Holy Spirit, the hope of glory,
to these affectingly benighted islanders,--alike with others,
the objects of the love of God,
and part of that inheritance purchased by the Saviour's precious blood.
