== Chapter XXXV.

[.chapter-synopsis]
* Attends the Yearly Meeting in London of 1838
* His Prospect of Religious Service in America
* Visits His Family in Russia, Eighth Month, 1838
* Sails to New York, First Month, 1839
* Travels in the United States
* Attends Yearly Meetings of Philadelphia, Virginia And New York

Shortly after leaving England on my way to the islands of the Pacific,
an unfading evidence was granted me that I should have to visit North America,
after the service on which I was then entering should be accomplished.
Such a marvellous unfolding of the Divine will as to the future,
so condescendingly vouchsafed and permitted to make an
impression on my mind at so great a length of time before-hand,
could not fail to support, comfort,
and strengthen me in every season of trial and conflict both inward and outward,
which I had afterwards to pass through;
and although at seasons my mind was put closely to the test,
it was again and again renewed from the heavenly treasury of living faith,
to strengthen my confidence in its holy Author and Finisher:
for the brightest gleam of that soul-sustaining
lovingkindness which is better than life,
soon loses its lustre,
unless renewed from time to time by Him in whose presence only there is life.

The statement which I felt called upon to render to the Yearly
Meeting held soon after our return to England was very short,
as my beloved friends were already in possession of the extracts from my Journal;
and the time was not come for me to disclose how I had been favoured with
such an evidence beforehand of a safe return to the land of my fathers.
My exercise of mind during the Yearly Meeting
may more easily be conceived than described:
and though my countenance might sparkle with joy at once more
beholding my brethren and sisters in religious fellowship,
my heart was full of a subject which nothing could relieve but disclosure;
and that seemed denied,
until the appointed days were fulfilled that the seal should be opened,
and the thing proclaimed as on the house-top.
At times I would gladly have taken counsel as to
the right path of proceeding with my concern;
but it seemed my place not to confer with flesh and blood,
but to keep my eye steadily fixed on that Almighty power,
which alone can qualify us like the left-handed sons of Benjamin,
to throw a stone to a hairs breadth.

Eventually my way opened with clearness to attend Balby Monthly Meeting,
and York Quarterly Meeting in the Sixth Month;
and having returned the certificates granted five years and a half ago,
after a brief statement of my late journey,
and mentioning the earnest of a return in safety, which the Lord had granted me,
I had to inform Friends that I no longer stood before them as one returning,
but as one requesting a certificate to enable me to visit various parts of North America.
As regarded my children, for whom I think I felt more than for myself,
I remember telling York Quarterly Meeting when my concern was laid before it,
that though human nature keenly felt the separation from,
and would gladly remain in possession of its greatest earthly treasure,
yet I did believe I could not promote the welfare of my
beloved family in any manner so much,
as by my own faithfulness to what I apprehended to be the duty required of me.
A certificate was granted,
setting me at liberty to pursue the prospect then before the view of my mind.
That I might not be chargeable in the sight of any,
with neglecting to look after the affairs of my own household,
it seemed best for me before embarking for America,
to visit the residence of my family on the plains of Shoosharry;
although if my own inclination only had been consulted, I should have preferred,
on several accounts, proceeding immediately across the Atlantic,
after having passed the Morning Meeting in London.

+++[+++This visit to Russia was satisfactorily accomplished:
setting out on the 1st of Eighth Month,
Daniel Wheeler passed about as many weeks at his
former abode as he had been years absent;
returning through Finland and Stockholm,
he reached London again on the 22nd of Tenth Month,
and finally embarked from Liverpool on the 25th of Eleventh Month following.
It was no small trial to leave behind, in a drooping state of health, his son Charles,
the faithful companion of his long journeyings.
From the boyhood of the latter they had, with but little exception,
dwelt under the same roof; and after the very close association of the last few years,
almost by day and night,
the separation now demanded was more than ordinarily painful to him.
In a letter from Daniel Wheeler, written at sea, it is thus alluded to.]

[.signed-section-context-open]
Twelfth Month 26th, 1838.

Having for so many years had the society of my dear Charles, under all circumstances,
and through each wintry season as it revolved,
I have never before felt so friendless and childless, as is now my portion.
This circumstance,
and the recollection of the bereavements which have befallen us about this dreary season,
combine to darken the shade of the gloomy picture,
with a deeper hue than it often has had, when clad in its own natural and beautiful,
though cheerless garb.
Truly may I say,
"`I had fainted if I had not believed,`" to see the lovingkindness of the Lord,
and the greatness of his goodness, which is laid up for them that fear Him,
and that trust in Him before the sons of men.
In the time of trouble He does hide them in His pavilion,
in the secret of His tabernacle shall He hide them; He shall set them upon a rock.
Although weak and feeble, and utterly unworthy in my own estimation,
without might or power, storehouse or barn; yet,
through that "`mercy`" which is "`from everlasting to everlasting,`" I am at seasons,
while floating on the mighty deep, permitted to feel an inward support in the belief,
that I am moving in my heavenly Father`'s will,--for truly it is not
in my own,--there is one that knows and judges righteously:
of this thing I am sure and certain from incontrovertible evidence,
and herein is my rejoicing and hope.

Let none be cast down or discouraged; for greater is He that is for us,
than he that is against us: and although many are the trials of faith and patience,
the deep baptisms, and the tribulations which the Lord`'s children have to pass through,
yet He delivers out of them all; and He will deliver, and that to the very uttermost,
all that in sincerity trust in Him.
And how does He mercifully vouchsafe unto such, in the abounding of His love,
a blessed portion of that "`peace which passes all understanding,`"
to sustain them in the way that they should go.

[.offset]
+++[+++Towards the conclusion of his voyage to America, he thus writes.]

First day, Twelfth Month, 30th, 1838.
We have seventeen cabin passengers, and among this number,
several very dissolute characters;
who have passed most of the voyage in drinking and gambling, almost day and night:
but the succession of storms which have followed us of late,
and their disappointment at not reaching our port as they expected,
upon which event they have even risked several sums of money,--seem at
length to have brought them to their senses in a remarkable manner.
This morning, I found my mind brought into deep thoughtfulness; and was willing,
if way should open, either to do or to suffer on their account.
I thought of mentioning the subject to one of my fellow-passengers,
of whose integrity of life and conversation I have had some proof;
but no opportunity offered, until he came to me,
saying it would be very agreeable to some of the company, and to the captain,
if I would address them when assembled together.
I told him the subject had rested with me, and that if we could have a time of silence,
if any thing arose for expression, it should not be withheld.
This he readily undertook to arrange, and at a fixed time, the whole party was collected.
I was not aware that this person had previously selected a Psalm to be read by himself,
until all was quiet; he then opened the Bible and commenced:
it was the thirty-seventh Psalm, and it appeared very appropriate to the occasion.
A general silence followed,
until my mouth was opened to declare what arose in my mind in the "`word of
the truth of the gospel,`" setting forth the terms of discipleship,
and the necessity of a preparation of heart, before true worship can be offered;
it was at considerable length, and to my own peace and comfort.
They appeared measurably sobered, and have passed the afternoon in a rational manner,
some of them for the first time since coming on board.
We had a heavy blow last night, and lost the main-top sail before morning,
which I think contributed to humble them.

31st.--This evening we were saluted with the joyful sound,
from a fast sailing clipper schooner,
"`Do you need a pilot?`" which being answered in the affirmative,
"`then heave to`" was the word.
Our decks rang with the cheers of all on board I believe, but myself,
when our courses were hauled up, and the main-yard immediately thrown to the mast.
The pilot soon boarded us to leeward, and the "`guessing`" shortly commenced,--such as,
"`I guess you are from Liverpool?`" "`I guess you have had pretty smart weather?`" Etc.
For my own part, I "`guessed`" from the rapid motion of the clouds,
that we should have another rough night, and so it proved.
As the ship was beating to windward,
the crew were toiling incessantly through the whole of it; and such was the noise,
and confusion on board, that very little sleep could be obtained.

[.offset]
+++[+++The Extracts which follow are from Daniel Wheeler`'s Journal and letters.]

First Month 1st, 1839.--This morning the Never Sink hills were in sight,
and we worked up the bay amidst fields of floating ice,
drifting from the mouth of the Hudson river.
The morning was so foggy in the neighbourhood of the city,
that the signal of the telegraph announcing the approach of the George Washington,
was not discovered by the "`look out,`" so that we
were within three miles of the wharf at New York,
before a steamer came to assist us through the ice.
By the way, I think the method of steering the American steamers is admirable:
the helmsman is stationed in the forepart of the vessel,
where he can see all before him, instead of being in the after part,
where he can scarcely see any thing for the masts, etc. of his own vessel:
he is also sheltered from the weather in a large lantern, the windows of which,
he can open or shut at pleasure.
Before noon we were at our desired haven,
and I trust that some of our hearts were filled with gratitude and thankfulness.

Though unexpected and a perfect stranger, as by some means I had left England,
without any introductions for New York, I was kindly received on shore by John R. Willis.
In the afternoon,
it was finally arranged that I should become an inmate with J. and P. Clapp.

2nd.--Attended the week-day meeting for worship and the Monthly meeting held at its close.
In the former,
I had a short testimony to bear to the faithfulness of that God with whom we have to do.

4th.--Had a most unexpected visit from my much loved friend Stephen Grellet,
who had come from his home at Burlington to see me.
He struck me as very little altered since we parted in Petersburg twenty years ago.
It was truly delightful to meet him again,
though the interview could not fail to awaken
many painful recollections of days that are past,
when our little family circle was unbroken, and,
as far as we can expect enjoyment while on earth, happy in itself.
But though many seasons of sorrow were brought to remembrance,
the never failing mercy of the Lord could be traced to
have compassed us about as with a shield,
for His great name`'s sake, from the time of our separation up to this very day.

6th. (First day.)--In the early part of the
meeting this morning I was greatly bowed down;
but in the Lord`'s time was raised up to declare the way of life and salvation,
and the necessity of the whole heart being given
up to follow the Son of Man in the regeneration.
In the afternoon I had to revive the words of the
apostle,--"`the weapons of our warfare are not carnal,
but mighty through God to the pulling down of strongholds,`" querying,
what we knew of this for ourselves.

15th.--We were favoured with a blessed meeting,
when the poor in spirit were declared to be those,
to whom the gospel was ever and is still preached.
Elizabeth Coggeshall afterwards knelt down, and gave the glory to Him,
who had thus condescended to grant us that drop of heavenly refreshment.

20th.--In the forenoon meeting,
I had to declare the necessity for all to come
to the knowledge and possession of true faith;
which can only be obtained from its ever blessed author and finisher.

23rd.--Attended the Select Meeting at Westbury,
where I had to encourage Friends to faithfulness in the maintenance of that cause,
which is as precious at the present day as when David
replied to the remonstrances of his elder brother,
"`What have I now done? Is there not a cause?`"
Although in the promotion of this dignified cause,
we may certainly have to drink of the cup which the Master drank of,
and be baptised with the same baptism that he was baptised withal.
The disciple is not above his master, nor the servant above his lord, etc.

24th.--Attended the Quarterly Meeting, in which I had to sound an alarm among Friends,
declaring that the Most High will have a church, He will have a people for himself,
that shall show forth his praise.
Many were willing and ready to join in the "`Hosanna to the son
of David;`" but how few were found to confess Him,
and to stand by Him, at the blood-stained cross: one betrayed his Master,
another denied Him, and they all forsook Him and fled.
I stood long on my feet, and had peace afterwards.

On the 25th, the meeting for public worship was again held,
and I was largely opened among them.
The young people were earnestly entreated to hearken to the voice of wisdom,
and offer an early sacrifice to the Lord:
and I had to acknowledge the lovingkindness of the Lord in
spreading the mantle of His heavenly presence over us,
to my own comfort, and I trust to the satisfaction of my brethren also.
In the evening, some opportunities were afforded to address large companies of Friends,
assembled at each other`'s houses.

27th.--Attended the meetings for worship, and had service in both, to my own peace.

28th.--Set out for Burlington,
accompanied by Samuel Clapp and Wager Hull by steam-boat to Amboy,
from there by rail-road: the route led by the house and grounds of Joseph Buonaparte,
on the banks of the Delaware.
A heavy storm of wind and rain on the 26th,
had raised the water in many parts to an unusual height,
and occasioned much loss of property by sweeping the quays even of heavy articles,
such as coal.
The rising of the Delaware had spread large masses of ice over the neighbourhood;
and the railroad by which we have travelled was in places entirely hidden by the water,
which was still too high to be confined within its usual limits.
The car in which we rode held about forty persons, with a stove in the middle of it,
well supplied with fuel, which made it sufficiently warm.
Reached Burlington as it became dark,
and were soon conducted to the abode of dear Stephen Grellet.
Remained here over their preparative meeting on the 31st,
and had an opportunity of calling on many Friends.

Second Month 1st.--Took leave of the family, where my residence had been delightful,
and which reminded me of dwelling in a nest of turtle doves.
Friends of this place appear to live in much harmony,
and have not witnessed many of those afflicting circumstances,
in which many other meetings have shared, from the Hicksite apostacy.
Proceeded to Philadelphia in company with my country-people Thomas and Elizabeth Robson,
S+++.+++ Grellet and other Friends; crossed the Delaware opposite the city by steam bridge:
we lodged at the house of Ellis Yarnall, a quiet retreat indeed.
Next day I attended and had service in the Select Meeting.

3rd. (First Day.)--Attended the meeting for the Western district in the morning,
and was largely engaged therein.
In the afternoon was at the Arch Street meeting,
and from the oppressive heat of the house,
had to labour under discouraging circumstances as to the body,
but was enabled to declare the way of the Lord among them.

4th.--The Quarterly Meeting was held this day:
it was the largest meeting of Friends I ever saw, except the Yearly Meeting in London:
the attendance was greater, perhaps by one third, on the women`'s side of the house,
than on the men`'s; and this is more or less the case wherever I go.
I had to press upon Friends the necessity of attaining that state,
which characterizes all the living members of the gospel church.

8th.--Attended the meetings in the northern and western districts,
and had good service therein.
The former is considered the largest in Philadelphia.

On the 12th, 13th, and 14th, I attended the North,
the Orange Street and the Arch Street Meetings, in all of which my mouth was opened.

On the 15th, I visited an afflicted family, the mother having died two days before.
After seeing the corpse, we had a contriting opportunity with the father and children,
under the wing of the Prince of Peace.
Coming to Philadelphia seems to have opened a wide door
for me in the minds of a large body of Friends,
and gives strength again to move forward:
leaving New York has I trust been in the right ordering,
in which I humbly pray to be preserved.

17th.--At the forenoon meeting under much discouragement.
Had to stand some time among the people,
and to insist on the necessity of our doing the will of the Holy Father,
if we would know the doctrine of the Son; unto those thus found in obedience,
his doctrine shall distil as the dew, and as the small rain upon the tender herb:
they shall inherit substance,
and shall certainly know that they have not followed cunningly devised fables,
but living and substantial truth.

[.offset]
+++[+++The following is a letter of Daniel Wheeler written about this time to John Wilbur:^
footnote:[This letter was taken from the Journal of the Life and Labour
of John Wilbur and included in this memoir by The Friends Library.]]

[.letter-heading]
To John Wilbur

[.signed-section-context-open]
Philadelphia, 2nd of Second Month, 1839.

[.salutation]
My Dear Friend John Wilbur,

When just on the eve of taking my departure from New York for this city,
your letter of the 22nd alt.
was received; and truly welcome it was to hear from you once more upon your own shores.
My time has been fully occupied ever since, in Burlington and its neighborhood,
until yesterday, when I left, and got here in the afternoon.
On leaving England for North America,
I had no defined plan in prospect of what I might have to do when I got there;
but it was clear to my mind that the first step which I
had to take was to make the best of my way there;
and since my arrival I have found that I must be content to live one day alone,
and am thankful to be able to say that thus far I have been graciously
supported and helped along to my own admiration and comfort and peace.
I am not, however, insensible that bonds and afflictions abide me;
and I do not feel any disposition to shrink from feeling the burden of them,
believing that if they be accepted for Christ`'s sake and his gospel`'s; in his own time,
if patiently abode under,
the freedom and liberty and consolations of the gospel will
also be permitted at seasons to abound to his praise.

Without anticipating more tribulation to be my portion
than what falls to the lot of other mortals,
I cannot conceive it should be otherwise than a day of suffering with
those who are called upon to fill up a share of that which remains
for the body`'s sake according to their measure,
when those things which make truly desolate, and destitute of the Divine presence,
stand where they ought not,
(in the place which should be holy,) instead of that pure
vital religion which the spirituality of the gospel
dispensation bestows upon all that believe in its teachings;
and it is these only that know it to be the power of
God unto salvation from sin and transgression.
How many are contenting themselves at this day,
even though making high profession of the Christian religion,
with a mere outward declaration of "`glad tidings of good things,
and great joy to all people,`" without coming to the heartfelt
knowledge of this very gospel within themselves,
though preached in and to every creature under heaven,
in language as intelligible as that of the angel which John
saw fly through the midst of heaven with it in his hand,
who cried with a loud voice,
"`Fear God and give glory to him,`" and which is only hidden
from those "`whose minds are blinded by the god of this world,
lest the light of the glorious gospel of Christ should shine unto them!`"
It is much more palatable to the creature to be fed
with pleasant food from the tree of knowledge,
which never can sustain the soul and was never intended for man to feed upon,
though good in its proper place, (and if to a proper extent cultivated,
allowable,) than to have the attention turned to that holy
principle of gospel light which shines in every heart,
which would set a man`'s sins in order before him without flattery or deceit,
whereby he might be induced to commence the great and necessary work,
and learn the first principles of the doctrines of Christ,
which is "`repentance toward God,
and faith toward our Lord Jesus Christ,`" by faith in the power of
the Holy Spirit to purify and cleanse the heart from every defilement.
"`Repent and believe the gospel,`" "`Repent and obey
the gospel,`" is coarse food in the present day.

Farewell, my dear friend; desiring my love to yourself and family,
I am your affectionate friend,

[.signed-section-signature]
Daniel Wheeler

Third Month 11th.--Since the last entry very much
confined to the house with an attack of influenza,
which has prevailed here very generally.
My mind has often been brought very low;
but my gracious Master has been pleased to enable me to
stand resigned to every dispensation of His holy will.
Many Friends have called to console and comfort me,
and the estimable family with whom my lot has been cast,
have lost no opportunity to administer to my relief in every way;
so that in everything I have abundant cause to give thanks to Him,
through whom all my needs have been so mercifully supplied.
Yesterday got to meeting,
and had a short testimony to bear,--that the path to the kingdom changes not,
but is the same now as in the beginning; and this way is Jesus, the first and the last,
the Alpha and the Omega, the beginning and the ending, the bright and morning star.

17th.--At the Western district meeting.
Shortly after gathering, the silence was broken by one of the Hicksite preachers.
His doctrine was guarded, and condemnable rather for what he had not spoken,
than for what he did speak.
I thought that those who really knew what he was,
were certainly blame-worthy in not apprising the elders,
so that the meeting might not have been disturbed by him.
The discourses of these people are frequently very extravagant;
denying the divinity of the Lord who bought them, in terms little short of blasphemy.

19th.--Attended the North meeting, after which the preparative meeting was held.
In the meeting for worship, seven ministers were present, but not a word spoken.
It is truly and sorrowfully a low time,
in which the rightly concerned must be willing to suffer with their suffering Lord,
and be crucified with Him, in the spiritual Sodom and Egypt of the present day.

20th.--Attended the Western meeting; after which the Monthly Meeting was held.
I have been silent in several meetings of late,
and at times much depressed from day to day.
In the meeting for worship,
a Friend from another meeting spoke encouragingly to my state,
as one acquainted with the Lord`'s dealings,
and the trials his servants have to pass through.

24th. (First day.)--Attended the Western district meeting in the morning,
which was much disturbed by the indisposition of a female who had to retire,
and by an alarm of fire.
My mind was under exercise, and a woman Friend standing up, led the way for my declaring,
that the Lord most assuredly is looking for fruit, even the fruit of the Spirit;
afterwards reciting the words of our Saviour to
his disciples,--"`Herein is my Father glorified,
that you bear much fruit; so shall you be my disciples.
Every branch in me that bears not fruit, He takes away;
and every branch that bears fruit, He purges it,
that it may bring forth more fruit,`" etc.
I felt somewhat relieved at the close of the meeting.

In the evening attended a meeting appointed by
Elizabeth Robson for the young people particularly.
Dear Elizabeth Robson had to speak of the blessedness of those who take up the cross,
and follow the Lord Jesus, and of the impossibility of serving two masters:
towards the conclusion she supplicated on their behalf.
It might be termed a solid meeting;
but it seemed to me that the minds of too many of our young people have already
been so much dazzled with the glare of creaturely activity and excitement,
as to have but little relish for the plain but incontrovertible
truths of the gospel in their primitive purity.
O! the beguiling influence of human wisdom! how does it
corrupt from the simplicity that is in Jesus:
it strikes at the very life of spiritual Christianity

25th.--The day rough and cold with showers of snow.
My health through favour is much restored:
my only need is more and more of the Divine presence,
and more ability to exalt the cause of truth and righteousness in the earth.

26th.--Attended the North meeting, after which their Monthly Meeting was held,
and my certificates were read.

27th and 28th.--Attended the Orange Street and Arch Street meetings,
after each of which the Monthly Meeting was held.
At all the Monthly Meetings I have recently attended,
it is very painful to witness the number of young persons who are leaving the Society.
These for the most part were minors when their parents became Hicksites;
and as they become of age, are disowned for non-attendance of meetings.
Others, again, are selling their birthright for a mess of pottage; and it is evident,
from the inconsistency of conduct of hundreds in this city,
how lightly they esteem the principles in which they have been educated.
Alas! Alas! what will they do in the end.

31st.--Attended the meeting now held as the wreck of
the once large and comfortable meeting of Merion,
consisting of thirty-six to forty persons.
I had to stand up among them and testify, that "`the law is holy,
and the commandment holy, and just,
and good`"--that the true worshippers are no longer under the law of sin and death,
but under the law of the Spirit of life in Christ Jesus,
which makes free from the law of sin and death.
They are not under the dominion of sin,
but under grace,--that grace and truth which came by Jesus Christ:
the Truth has made them free, and they are free indeed.
It is only such that can worship the Father in the beauty of holiness,
and in newness of life.

Fourth Month 1st.--Accompanied Israel Morris to Haverford.
Here is established a school for Friends`' children,
where the higher branches of learning are taught, at present to about seventy boys;
but as the vacation is near at hand,
and preparations making for an examination before that commences,
I saw no part of the usual routine of the institution.

4th.--Attended the meeting at Haverford.
It was a restless and trying time to me.
I had to revive among them the passage,
beginning--"`Let not the wise man glory in his wisdom,
neither let the mighty man glory in his might.
Let not the rich man glory in his riches; but let him that glories, glory in this,
that he that understands and knows me, that I am the Lord,
which exercise lovingkindness, judgment, and righteousness in the earth;
for in these things I delight, says the Lord.`"

7th. (First day.)--Attended both meetings at Burlington,
having come by steam-boat yesterday.
In the forenoon I stood up with these expressions,--the royal Psalmist,
than whom none could bear a more ample testimony to the lovingkindness, mercy,
and faithfulness of the Lord, had nevertheless his share of trial,
and had at seasons to mourn as a dove in the absence of his Beloved;
as when we find him making the solemn appeal,--"`Will the Lord cast off forever,
and will He be favourable no more?`" etc.
In the afternoon,
I revived the words of our dear Redeemer,--"`Strive to enter in at the
strait gate`"--which strait gate remains to be the only way to the kingdom.
If "`we live after the flesh, we shall die: but if we through the Spirit,
do mortify the deeds of the body,
we shall live;`" the life of the Christian is a
continual warfare,--the flesh against the Spirit,
and the Spirit against the flesh;
but the weapons of his warfare are inward and spiritual, and "`mighty through God,`" etc.

8th.--Spent the afternoon much to my satisfaction with our ancient friend John Cox,
eighty-seven years of age: he is a minister, and alive in the Truth.
In the evening +++_______+++ arrived from New York, whom it was very pleasant to meet again.

9th.--Returned to New York, and found J. Clapp and family well, and as kind as heretofore.
The next day attended the meeting here, which proved satisfactory.
I had to allude to the blessedness and peace that are the portion of the children of God,
who have been ransomed from their sins by the blood of Jesus,
and redeemed by submission to the operation of His Holy Spirit in their hearts:
reviving the language of the prophet,--"`Look upon Zion, the city of our solemnities;
your eyes shall see Jerusalem a quiet habitation,
--a tabernacle that shall not be taken down.`"
Several others spoke.

11th.--Returned by rail-road to Philadelphia,
having the company of Anna A. Jenkins and her companion from Providence.

12th.--Attended the Meeting for Sufferings, which was large,
nearly all the members being present.
The subject of slavery came before it; and the case of the oppressed slaves,
as well as of the slaveholders, was treated with much feeling.
Many Friends seem under much concern on this subject;
and on account of those of our numbers who have joined the Colonization Society,
which is not unlike sanctioning the continuance of this cruel system.
May the Lord be graciously pleased to break this inhuman yoke asunder.

13th.--Attended the first sitting of the Yearly Meeting of ministers and elders:
it was a low time with me, and I believe with others also.

14th. (First day.)--Attended the meeting in Twelfth Street,
in the fore-part of which Anna A. Jenkins appeared in supplication.
A young minister followed in a lively testimony;
after which I found an exercise which I was enabled to throw off,
and had to encourage the young man who preceded me.
A Friend who sat by me, afterwards said, that he was sensible when my concern came on,
it was suddenly '`like a flash,`' and so it was; under the feeling of which,
I stood up almost immediately, and was afterwards comforted.

15th.--The Yearly Meeting at large sat down.
I little thought that it would be my lot to break in upon the solemnity that prevailed,
until a short interval before I found that I could do
no other than petition on the bended knee,
that the Lord in his everlasting mercy would be pleased to
lift up the light of His heavenly countenance upon us.
After taking my seat again, my soul was melted in humble contrition before Him,
who lives forever and ever.

The Yearly Meeting continued by adjournments until the 19th instant inclusive,
and was an exercising time, on account of the too general departure from,
and ignorance of that light and truth,
which distinguished the meetings of our worthy predecessors in so eminent a manner.
On the subject of meetings for worship, I had one remark to make;
and to declare that if ever we suffered the righteous testimony to
the teachings of that Divine grace which has appeared unto all men,
to fall to the ground,
or be lowered by departure from a silent waiting upon
God for the blessed influence of the Holy Spirit,
to enable us to worship Him aright,--the glory would depart from our Israel,
and nothing be left us but an empty name.

On the morning of the 15th, before the sun was up,
the love of God flowed through my heart towards
our beloved sisters in their Yearly Meeting;
but this blessed visitation soon passed away as a morning cloud,
leaving not a trace behind: and yet it was in the same glorious manner,
but shorter and in a less degree,
as that which once prompted me to visit the distant isles of the ocean.
I felt no more of it,
although my mind often recurred to the manifestation during a time of great
sensible weakness and self-abasement for several successive sittings;
wherein was remarkably verified the necessity for the feet of the priests to
stand firm in the bottom of Jordan with the ark of the testimony,
until all the people had clean passed over.
When all the minutes were gone through, and the principal cases disposed of,
dear Elizabeth Robson came into the men`'s meeting:
before this scarcely any thing in the line of ministry was offered by any one:
but now the seals seemed to be loosed.
E+++.+++ R. was highly favoured, and bore an awakening testimony among us.
This opened the way for me to follow,
exhorting all to turn to the Lord with full purpose of heart,
in the very depths of humility.
My soul had mourned over the low state of things among us:
the sorrowful and manifest declension,
which had so greatly marred and defaced our religious Society,
might be traced to our having departed in heart
from that precious principle of light and life,
bestowed in redeeming mercy on every individual of the human race.
It is high time to lay aside the unfruitful works of darkness,
and to put on the whole armour of light; for the day is far spent,
and the night is at hand.

On the 19th, the prospect above-mentioned again revived before me,
and in the afternoon I thought I could not allow the meeting
to conclude without making some attempt to bring it about.
I hinted my situation to an elder in the meeting-house yard,
when our meeting was gathering, who advised me to proceed with it;
and as soon as the clerk had opened the meeting, I spread my concern before it,
and Friends rising in quick succession with a word of encouragement,
I was soon set at liberty.
I had full opportunity to clear my mind in a crowded meeting, to my own great relief;
and perhaps some longing desires might be raised in the hearts
of individuals after that purity of heart and life,
in which the Lord delights: the result I desire to leave to Him,
who sees the end from the beginning.
As the men`'s meeting gathered, my exercise had become stronger and stronger,
in tender mercy confirming me that it was of the Lord;
and truly His heavenly power and presence went with me,
and enabled me richly to open the way of life to my beloved sisters,
and to encourage them to press toward the mark for the prize immortal,
the high calling of God in Christ Jesus.
I understood afterwards, that no other time during the whole Yearly Meeting,
would have been so seasonable as the one I was pressed to resort to.
Trust in the Lord, O! my soul!

21st.--Attended both meetings; in the forenoon I had to deal very plainly:
in the afternoon was silent.

23rd.--Attended the funeral of Timothy Paxton, a worthy elder,
whom I had visited in the course of his sickness.
The crucified Saviour was declared to a large assemblage,
including I suppose many Hicksites, but all was quietly received.

27th.--Proceeded to Wilmington and was kindly received at the abode of Samuel Hillis.
This city is built in a well chosen situation, with the noble Delaware in its front,
and the Brandy Wine and Christiana rivers navigable up to the wharfs.
At the foot of the Brandy Wine, many mills are established,
where the bulk of the American flour that is exported is dried and ground.

Attended both meetings in Wilmington, in which I had some service.
In the afternoon an ancient Friend spoke,
which opened the way for me to quote the apostolic
declaration,--"`That which may be known of God,
is manifest in man,
for God has showed it unto him`"--making a solemn appeal to some present,
whether they were not treating the Spirit of the Lord in their hearts,
as His holy person was treated when on earth by the Jews;
when "`He was despised and rejected of men, a man of sorrows and acquainted with grief.`"
Assuredly, a day will come when He who now pleads with them for their own soul`'s sake,
in matchless love and mercy, shall be their judge.
"`I judge no man.
The words that I speak, the same shall judge them at the last day.`"

Fifth Month 3rd.--Went over two whaling vessels,
lately returned from the Pacific,--in one, found a poor solitary New Zealander;
of course little could be done in the way of conversation,
as he spoke but little English.
One of these vessels had been out only twenty-two months, the other nearly four years,
and at last returned with only a scanty cargo.

4th.--Attended the Monthly Meeting: to myself a lifeless season.
A number of young persons at schools kept by
Friends in this neighbourhood attend meetings;
which tends very much to make them unsettled and unsatisfactory,
as some of the boys particularly are very restless,
and appear insensible of the true intent of our meeting together.
I found that unless they came to meetings,
their teachers would have to remain at home with them,
and Friends on this account make allowances,
and bear these things with much Christian charity.

5th. (First day.)--Had good service in the forenoon meeting,
declaring the blessedness of those who do the will of the Father,
by hearkening to the voice of His well-beloved Son.
In the evening I had a public meeting, to which the inhabitants at large were invited:
a considerable number assembled, but the house was not filled.
It was an exercising time to myself,
arising in part from the weight of responsibility resting upon me,
and partly from having an intoxicated individual seated directly before me,
who fell asleep, and leaned forward so much that his hat fell twice from his head.
An attempt was made to persuade him to go home, but did not succeed:
he eventually roused up, I was informed, and listened attentively.
I sat pretty long before I felt strength to stand up.
At length the following expressions crossed my mind,
and brought with them the ability to testify,
that "`the God of Israel is He that gives strength and power to his people.
Blessed be God!`"
I had abundant cause as on many former occasions, to magnify that Almighty power,
which enabled me to declare His mercy and His truth among the people; enlarging my heart,
as I proceeded to speak with innocent boldness of the things of His kingdom.
It was with me to set forth the glories of the present gospel day,
and to query how far we were individually
contributing or otherwise to promote its fulness,
as we have each a responsible part to act in the great work.
My late visit to the South Seas was adverted to,
and the message with which I was charged by Paofai,
and of the principal chiefs of the island of Eimeo, was faithfully delivered.^
footnote:["`Go,`" he said, "`to Britannia,
and tell the people to have mercy on us;--and then go to America,
and tell the people there to have mercy on us;
for it is these countries that send the poison among
us;`" alluding to the introduction of rum, etc.]
I had to point out the dreadful national responsibility we were incurring,
and the imperative necessity for all earnestly to consider,
whether they were clear of contributing in any
manner to the sacrifice of those poor islanders,
who are fast vanishing from the surface of the earth,
in consequence of their interaction with foreigners;
reviving the words of the prophet of the Most High, "`shall I not visit for these things;
shall not my soul be avenged upon such a nation?`" It was a solemn opportunity,
and was overshadowed by the wing of everlasting love: so that my soul could truly say,
I trust with humble reverence,
at the end as at the beginning,--"`Blessed be God,`"
who alone gives strength and power to His people.

10th.--Attended the meeting this day, which was a highly favoured season.
A precious remnant was present,
capable of appreciating this signal instance of Divine
regard vouchsafed even in this degenerate day,
as a brook by the way.

11th.--Took leave of Friends, and left Wilmington by railroad, with a peaceful mind.
We crossed the noble Susquehanna river at Havre de Grace,
and several branches of the Chesapeak bay and the Gunpowder water,
on the way to Baltimore: we reached this city early in the afternoon,
where I am now kindly entertained at the house of Dr. Thomas.
The passage of the Susquehanna, which I have just mentioned is by steamer,
and is so managed that from leaving the railway car on one side,
till again seated in a fresh car on the other side,
the passenger is constantly under cover, so that whatever be the weather,
he is provided for.

12th.--In the forenoon meeting I was closely engaged,
standing up with the words of the blessed
Redeemer,--"`You worship what you do not know.`"
However abrupt and unpalatable the accusation might appear,
I found that I had no other course to take.
Many Hicksites were at the meeting,
for whom what I had to say might have seemed to have been previously prepared,
if I had known that they would have been at the meeting: it was, however,
a solid meeting.
The afternoon meeting was silent as to myself,
but we had the ministry of another Friend to satisfaction.

14th.--Believing that I could do no less than endeavour to meet the sailors,
and others connected with a sea-faring life, arrangements were made for this purpose;
and the privilege obtained of the use of the Bethel chapel,
when it was ascertained that the stranger for whom it was requested was not a Hicksite:
the meeting was held at a suitable hour in the evening, and was considered large.
As regards myself, it was a low season;
and I believed while sitting in silence before them,
that but few were present of the description whom my soul longed after.
I was strengthened to declare the everlasting gospel among them;
but seemed led along to a class making much higher profession
of religion than those whom I expected to assemble.
It was I believe, considered a satisfactory meeting;
but the feelings of the unprofitable servant were mine.

10th.--Called on some of the sick and afflicted, to my own comfort and peace.
In the evening a large number of Friends and others collected at the house of Dr. Thomas,
where a precious opportunity was vouchsafed to us.

16th.--The week day meeting held in course was small,
but very precious to a living remnant.
I had much to say among them of an encouraging and comforting nature;
but I hope it was done in such a manner,
that none could take that to themselves which belonged to another:
the terms were rigidly specified.
I had to commemorate the tender mercy of our God,
and the continued regard of our holy High Priest, Christ Jesus;
whose presence was livingly felt among us.
It was a blessed season to myself;
and I believe will not soon be forgotten by some others.

In the afternoon, took leave of my truly kind host; and accompanied by Samuel Carey,
proceeded by railway towards Virginia.
After crossing the Patapsco river, and passing through the city of Washington,
we were embarked on board a steamer; we proceeded down the spacious Potomac,
as far as the head of Potomac Creek, which runs up from Chesapeake Bay.
Here we were packed in crowded clumsy stages, and conveyed nine miles to Fredericsburgh,
where we were again seated in a railway car, holding about sixty persons;
many of them in rocking chairs, which seem quite a _sine qua non_ with all classes here.
We reached the station near Taylorsville about four o`'clock the next morning;
but as this is merely a boarded shed, where whiskey and cider are sold,
we walked on to the village, carrying our luggage with us.
Here we found comfortable quarters; but owing to some failure of letters,
a carriage which was to have met us here was not to be found.
We were now in a land of slavery, and the delay which this disappointment occasioned,
afforded some opportunity of remarking the effects of the system;
but although perhaps here, in its mildest form,
both the country and the people wear an aspect of wretchedness and poverty,
quite striking to a stranger.
The land has grown tobacco,
until in places it can scarcely cover itself with a plant of any kind.
Here and there a patch of Indian corn is to be seen, which, with hogs,
seems to constitute the principal food of the inhabitants.
In the afternoon we hired a pair of horses that had been ploughing,
a very old shabby vehicle, and equally shabby harness,
and set forward for Montpelier in Hanover county.
Had to ford a small river by the way, in the middle of which the horses became awkward,
probably from a desire to drink; when the harness broke,
and the poor animals drank their fill, while our negro driver repaired damages,
cutting up parts of the harness to strengthen what had given way.
The weather was very sultry, and we reached the mansion of Nathaniel C. Crenshaw,
just at the commencement of a heavy thunder storm.
We were most hospitably received,
although a large party of Friends had already assembled, like ourselves,
on their way to the Yearly Meeting of Virginia, to be held the next day at Cedar Creek,
five miles distant.

18th.--Attended the Select Meeting in the forenoon, which, though small,
was satisfactory; and afterwards the Meeting for Sufferings.

19th. (First Day.)--The people collected for the forenoon meeting in great numbers.
The neighbourhood of the meeting house exhibited such a display of equipages,
as I could not have supposed the country hereaway was capable of making.
Many of the coloured people also attended.
The meeting house was built before the separation, and therefore of large dimensions,
so that there was room for all;
but for a time we were much disturbed by the very loose
behaviour of some of our well dressed white visitors.
I was grieved with their conduct, and at length told them,
that in order to get into a settled state,
it would be well for each individual to consider in whose presence we were assembled,
as became men and Christians, etc:
we were afterwards favoured with a solemn season together.
A few went out, but the more solid part remained, until the meeting ended.
At my request a public meeting was held that afternoon.
It was not so large as that in the forenoon, but the company were much more solid;
and I humbly trust the great Name was exalted that day,
and His power felt to reign in the hearts of many.

20th. (Second Day.)--It is the practice for the
business of the Yearly Meeting to commence this morning.
The men and women usually sit together for a short interval,
and then the shutters are drawn up, which separate them into distinct meetings;
but before this could be done, the people flocked in so numerously,
as almost to compel the holding of a meeting for worship with them;
and through favour it proved a season worth coming several hundred miles to witness.
It was, I believe, a day of solemn warning and renewed visitation to many,
and particularly to the young people in membership with us.
I felt bound to revive among them the fatherly invitation of the Most High,
"`Come out of Babylon, my people, that you be not partakers of her sins,
and that you receive not of her plagues.`"
"`Come out from among them, and be separate, says the Lord, and I will receive you:
and I will be a father unto you, and you shall be my sons and daughters,
says the Lord Almighty.`"
Let not the Babylonish garment, nor the wedge of gold, be in our camp;
but save yourselves from this untoward generation, etc.
The Lord`'s power was felt to prevail among us, to the softening of many hearts,
and the encouragement of the faithful of this sequestered little flock.
On the way afterwards to the house of Walter Crewe, in company with his daughter,
and Samuel Carey,
we experienced a marvellous preservation from being hurled down a precipitous bank.
Owing to something being wrong about the harness, one of the horses got off the road,
and dragged the other with him; and had the driver attempted to turn them again,
we must have been overturned.
Our escape seemed brought about by the horses being kept as it were before wind and sea,
directly end-on, and almost on their haunches,
sliding straight down the hill to level ground below.
Had the carriage been turned ever so little on one side,
it must immediately have toppled over,
and probably would have rolled several times over before it reached the bottom;
and yet such was the mercy extended to us that no one was hurt,
and neither carriage nor horses apparently injured.
Such unmerited favours demand our humblest gratitude.

Attended the different sittings of this Yearly Meeting on the
21st and 22nd. In the afternoon of the latter day,
the business was nearly concluded, and I took leave of Friends,
being desirous of attending the Yearly Meeting in New York, which is fast approaching.
I was comforted in the belief, that in this Yearly Meeting,
although small indeed to what it formerly was, there is yet a living remnant,
to whom the cause of truth is precious.
May the Lord preserve them, in this land of oppression;
and may their hands be unpolluted by the blood of the suffering sons of Africa.
We set out the same afternoon, and were favoured to reach Baltimore the next morning,
and were again hospitably received by Dr. Thomas and family.
During the night there was a succession of thunder and lightning:
my attention was much attracted by the brilliant little lamps of the fire-fly,
which were perceptible between the flashes of lightning,
pursuing their nightly excursions,
and filling their place in the marvellous works of this beautiful creation,
according to their order and the part assigned them;
showing forth the praises of their Almighty Creator.

Rested on the 23rd, and the next morning, again left my kind friends of Baltimore,
and pursued my way alone to Philadelphia,
where I reached the abode of my ancient friend Ellis Yaniall the same night;
and finally got to my quarters in New York on the 25th:
here I found many Friends from Canada and other parts arrived for the Yearly Meeting.
Attended the various meetings as they came in course,
and sat for the most part in silence.

31st.--The last sitting of the Select Meeting was held.
In this I had to state in plain terms my fears as to the present state of the ministry;
and had to remind Friends of the devastation in our Society in England,
from this very cause of unsound ministry having crept in among us.
My mind found some relief.

In the evening attended a meeting appointed at the
request of Elizabeth Robson for the young people,
in which she had largely to labour among them,
in the love of the gospel,--I trust to the relief of her own mind,
and to the benefit of many.
It appeared from the different epistles,
that there is a prospect of a succession of burden-bearers among the young people,
which I sincerely desire may be amply realized;
but to myself the prospect is very gloomy as regards our Society in this land.

Sixth Month 2nd.--In the forenoon, +++_______+++ appeared at some length;
and greatly do I desire that lasting impressions may have been made on some:
but alas! how often does the ear listen with gladness,
and even the heart desire to become acquainted with
those things that accompany life and salvation,
while it still remains in the unregenerate state,
for lack of that self-denial and daily cross to our corrupt wills and inclinations,
without which we cannot advance one step nearer the heavenly kingdom.
