== Chapter XXXVI.

[.chapter-synopsis]
* Attends New England Yearly Meeting, Etc.
* Visits Nova Scotia and Canada
* Returns to Philadelphia and Proceeds to Ohio; Attends the Yearly Meeting at Mount Pleasant
* Returns to England

Sixth Month 7th.--Embarked in the steamer for Newport, Rhode Island,
with a company of two hundred and seventy-five passengers, including several Friends.
We were favoured with a beautiful night,
and rounded Point Judith next morning under the most favourable circumstances:
this point being exposed to the swells of the Atlantic,
is often a very rough part of the voyage.
We reached Newport at five a.m., and proceeded in stages towards New Bedford,
arriving by noon at Francis Tabor`'s;
where I found a family dwelling much in the ancient
style and simplicity of our early Friends,
both the heads being elders in the Society.
Here I was again a stranger, and without any defined prospect of duty before me.

The next day the 9th, being First day, my path was greatly opened;
and at the close of the forenoon meeting the way was clear for me to request
that a meeting should be appointed for the inhabitants generally,
seamen, and those connected with a seafaring life;
which was arranged for the following evening.
We were favoured with two comfortable meetings that day; and in the evening,
before separating from a large company assembled at the house of a Friend,
it was with me to recognise that Almighty power,
which "`makes the outgoings of the morning and the evening to
rejoice,`" and to acknowledge the unspeakable favour,
after a day full of mercy and full of love,
to be sensible that the heavenly wing still
overshadowed us,--a great and precious privilege,
demanding all our admiration, gratitude, and humble praise.

10th.--In the afternoon attended the funeral of
a young person who died after a severe illness,
occasioned by sitting on the ice, when heated and fatigued, six months ago.
Many were collected on the occasion, and after two other Friends had spoken,
I had to urge the necessity of our individually becoming acquainted with Him,
who is "`the resurrection and the life`" and thus be
prepared for the day of death appointed unto all men.
The meeting in the evening was largely attended, and proved a solemn season.
Friends of New Bedford were hearty in the cause,
and had taken great pains to apprize their fellow-townsmen by advertisement,
the circulation of hand bills, and in some instances, by personal application.
Notwithstanding the responsibility was heavy upon me, and the prospect truly formidable,
I was supported under it to my own admiration; well knowing Him in whom I had believed,
by His heavenly grace, to be sufficient for me in all things.
That Almighty power which is the crown and diadem of every religious assembly,
was mercifully pleased to own our gathering,
and this evidence of Divine regard was acknowledged, I trust, to His glory and praise.

I came here poor and low enough;
and now how eminently have I witnessed the gracious
dealings of the Lord for His great name`'s sake!
My heart feels more and more constrained to trust with humble confidence in Him,
and to cast all my care and burden upon Him alone;
desiring earnestly that self may be so kept down,
that the Divine glory may be the only motive to action,
in my feeble endeavours to promote the precious cause of truth among my fellow creatures,
as from time to time, I may apprehend required of me.

13th.--Came to Nantucket by steamer on the 11th,
and was kindly received by Prince Gardner and family, with whom I am now staying.
Yesterday visited several sick and infirm persons; I trust the time was profitably spent.
I tried the fleece last night until pretty late,
and at length concluded it safest for me to propose
that a public meeting should be held here this evening;
and Friends uniting in this prospect, notice has been given of the same.

This morning attended the week-day meeting,
and although a considerable body of valuable Friends was collected,
everything was like iron and brass about us; my mouth was completely sealed up,
until the meeting was about two-thirds over,
when a Friend stood up in the body of the meeting and expressed a few sentences.
This was what had to be waited for, and now my bonds were broken asunder,
and my tongue loosed.
Thus "`day unto day utters speech,`" and instruction is sealed to the mind,
more and more to cast our care upon Him, who cares for us,--although wholly unperceived,
until He is pleased to reveal Himself to our finite understanding.

Newport, Rhode Island.
Sixth Month 22nd.--Unable from a variety of circumstances to resume my pen until this day.
The public meeting on the 13th proved a highly favoured season,
and much larger than the one held at New Bedford.
Thus was this, (to me) eventful day rendered memorable to the very close,
through Him who does all things well.
At an early hour the next morning embarked with a goodly company of
Friends on our way to the New England Yearly Meeting;^
footnote:[Held at Newport, Rhode Island.]
and reached the house of Edward Wing at Tiverton the same evening, the 14th instant,
having travelled by land and water about one hundred miles.
Here I found a house apparently filled with guests; but was cheerfully accommodated,
our host telling us they were never so full, but that one more could be admitted.
In these parts,
their neighbours of other societies freely open their doors to Friends on such occasions.

15th.--Attended the Select Meeting, and the Meeting for Sufferings at Plymouth,
eight miles farther; and the same evening continued our course towards Newport,
reaching the house of David Buffam before sunset, about two miles from this town.
Here I found a hospitable family,
and many Friends with whom I had already become acquainted.

16th. (First day.)--Attended the meetings for public worship,
to which the town`'s-people flowed like a living stream.
The Meetinghouse holds, I was informed, about two thousand people;
and it was so filled before the appointed time,
that it was difficult to reach the gallery.
In the morning,
after our aged friend Elizabeth Coggeshall had broken
the silence by a solemn petition to the throne of grace,
I had largely to declare the way of life and salvation, to my own comfort and relief;
though no light matter to have to stand forward in the
presence of so many weighty ministers and elders of both sexes.

The Yearly Meeting was considered large;
and was favoured at seasons throughout its sittings with the Divine presence.
Although it comprises many living members, yet there was much found to mourn over,
and render getting along very heavy work,
when the true state of the Society was opened out by the answers to the queries.
There were many present I believe,
who could say with the prophet,--"`I was bowed down at the hearing of it,
I was dismayed at the seeing of it.`"
An address was drawn up by the Committee of Correspondence,
and sent down to the different Quarterly Meetings, containing much excellent advice,
very applicable to the state of things, in many of the meetings.
Non-attendance of meetings, lack of love,
and in several instances an attachment to military parade,
were the principal causes of mourning.

The last sitting of the Yearly Meeting was held yesterday the 21st,
and many Friends left Newport last evening;
but the foggy state of the weather having prevented the arrival of the usual steamboats,
some hundreds, I suppose, are still in the boarding-houses.
I met here my country-people Thomas and Elizabeth Robson; also John Wilbur,
my acquaintance in Old England.
Today I am lying upon my oars, and resting a little;
it is probable that Providence may be the next point of destination;
but I am waiting to see what tomorrow will bring forth.

While looking round a little at New Bedford, I met with Matthew Luce,
a captain who has made several voyages up the Baltic;
but what makes the circumstance worthy of record, and attaches me to him,
is the fact of his having been a fellow-passenger from
Constadt to England with my ever dear and lamented William,
a few weeks before his decease.
Finding that, during the voyage,
Captain Luce had rendered much kind assistance to this darling
object of my hopes in his weak and declining state,
I could not but feel him greatly endeared to me.
He spoke with much feeling of dear William`'s pious resignation,
and humble but firm confidence in the arm of everlasting strength;
and that although he had no caretaker with him,
or precious acquaintance to lend a hand of help, yet he comforted himself in the belief,
that this and every other lack would be supplied:
telling Matthew Luce that he considered him an instance of
what would be cast up for him in his friendless condition.
Matthew Luce said he considered it quite a privilege to have been with him.
To hear this from so authentic a source was
indeed very comforting and cheering to my heart,
in the midst of a renewed sense of the treasure I had lost;
and to find that he had been thus cared for, when in a peculiar manner cast out,
as it were, upon the wide world.
Truly,--"`as the mountains are round about Jerusalem,
so is the Lord round about his people,
from henceforth and forever,`" however widely
separated from their families and connections,
I can abundantly testify.

23rd. (First day.)--Attended both meetings at Newport:
in the forenoon many attended besides members, and I had good service.
In the afternoon meeting Elizabeth Robson was drawn forth to minister among them.

24th.--Attended a public meeting held at my request.
The evening proved wet; and the gathering not so large as was expected,
but remarkably solid: and I was favoured with an open time among them.
My mind afterwards felt peaceful;
and I think I never was more sensible that help and
strength had been administered in the needful time.

25th.--Came to Lynn by way of Providence and Boston, arriving about sunset;
and was kindly entertained at the house of Isaac Basset.
Before reaching Providence, the site of the dwelling,
and burying place of Mary Dyer was shown me;
and before crossing the ferry to East Boston, the place where she was executed,
with Marmaduke Stevenson and William Robinson.

26th.--Attended the week-day meeting of Friends at Lynn;
where we had renewed cause to bow in humble reverence to the great Preserver of men,
for the extension of His goodness to His poor unworthy creatures,
wherewith he was pleased to comfort us together in an eminent degree.
After a long silence, and a female Friend had expressed a few sentences,
I had to revive the sealed promises to the wise,
and to them that turn many to righteousness, in the words of Daniel the prophet;
and to declare the sure way for every individual to be numbered with those,
who inherit such transcendant glory.--"`Behold,
thus shall the man be blessed that fears the Lord.`"--"`The fear of the Lord is the
beginning of wisdom.`"--"`The secret of the Lord is with them that fear Him;
and He will show them His covenant`" of light, life, and truth;--which,
if obedience keep pace with knowledge, will make us wise in heart,
and enable us so to let our "`light shine before men, that others seeing our good works,
may glorify`" God in the day of their visitation;
and be strengthened more and more to follow after righteousness,
that their example also may produce the like happy result.
Thus many, by our faithfulness, may be turned to righteousness;
and the language of inspiration will be fulfilled,--"`They that be wise,
shall shine as the brightness of the firmament, and they that turn many to righteousness,
as the stars forever and ever.`"
The Lord was with us of a truth, to the tendering of the hearts of many.
Reached the house of Abijah Chase of Salem, that evening.

27th.--Sat with Friends of Salem, in their usual meeting.
I had a close testimony to bear, and, I trust,
did not withhold any part of what came before me.
Returned to Lynn in the afternoon.

28th.--In company with several Friends, went to Boston.
As no Friends reside there, we put up at the Marlborough,
which is one of the first hotels in the city; and is a Temperance house,
where we were well accommodated.
In the evening attended a public meeting appointed for me:
and for which arrangements had been carefully made before-hand.
We met in a house belonging to Friends, nominally at half-past seven;
but it was much later before the meeting became tolerably settled.
I had largely to labour among them, but found it heavy work: J. D. Lang,
a Friend from the State of Maine, was present, and his company very acceptable to me,
though he sat by me in silence.

29th.--Returned as far as Providence, in company with W. Jenkins; and next day the 30th,
attended meetings there.
In the forenoon it was a dull season;--one of those when deep calls unto deep.
E+++.+++ Robson was present, but both of us were silent.
The expectation of the people being too much upon the poor instruments,
was wholly disappointed, and found to end in vanity and vexation of spirit;
while we sat as fools among them: I would that this might operate as a sign,
that man can of himself do nothing.

In the afternoon a public meeting was appointed for Elizabeth Robson,
and good attendance given: E. R. had the whole weight of the service;
and was helped through to my admiration and rejoicing.
The day altogether was one that confirmed me in my belief of the
sympathy and fellow-feeling of the living members of the one body.
In the morning we shared the humiliating but wholesome season together;
and in the afternoon were favoured to share in the love of the Master,
which flowed to both in an encouraging manner.
Before E. R. had uttered one word, I believe I could have foretold what she would say;
such is the fellowship of the gospel flowing from the one holy Head:
and how precious is this unity, in the one Spirit,
even as we are called in the one hope of our calling,--
in the one faith and baptism of the same gracious Lord.
It was a highly favoured meeting.

Seventh Month 1st.--Was conveyed by W. Jenkins as far as New Bedford;
and on the 2nd embarked in the steamer for Nantucket to attend the Quarterly Meeting.
Near one hundred Friends in company arrived the same afternoon.

3rd.--Attended the Select Meeting, which was a low time;
in which I had to speak of the awful responsibility attaching
to those in the stations of ministers and elders:
and to warn those present, of a day of farther trial awaiting our Society; which,
from its nearer approximation to the world,
would have more difficulty to maintain its standing, than in former instances,
when Friends, like Israel of old, dwelt more alone.

In the afternoon attended the funeral of a young man
whom I had seen on his dying bed when last here.

4th.--The meeting for worship was held, and several searching testimonies were borne,
in which a warning voice went forth to the young people.
The business of the Quarterly Meeting was completed the same day.
Returned to Providence next day.

7th. (First day.)--Attended both meetings, in which I had some service.

8th.--Had a public meeting with the inhabitants.
It was not large, but proved a very solemn and favoured time.
Few, I believe, were present,
but such as had something of the true hunger begotten in them;
and I trust that these were fed with food convenient for them.
The Lord was my helper, in humble thankfulness be it spoken.

On reaching this place on the 5th,
I received accounts of the declining health of my dear Charles.
I trust that these things, although deeply painful, may not be suffered to trouble me,
nor hinder the service of the blessed Master;
but rather have a tendency to promote His cause, by keeping me clothed with humility,
and watchful towards Him in His fear and in His love;
who so often fills my heart with His praise.

10th.--In company with Anna A. Jenkins,
attended the meeting at a public school belonging to Friends,
and had some counsel to offer, which perhaps might hurt neither teachers nor scholars.

11th.--Shortly after the week-day meeting gathered, a thunder-storm came on,
and lasted for some time in a very awful manner,
doing considerable damage in the neighbourhood.
Had some service of an encouraging nature to the little ones.
In the evening, at a public meeting held in a Temperance boarding house.
It was well attended, and proved a comforting season,
although commenced under feelings of much strippedness.
Some sailors were present, and many of the wives and connections of seafaring men.

12th.--Accompanied by Reuben Peckham proceeded to Lynn.

14th. (First day.)--Had a public meeting in the evening,
which was well attended and proved an open time; utterance being freely given.
It was cause of thankfulness with me, and the more so,
as I had felt unwell during the afternoon,
and for a time had been doubtful whether I could attend the meeting.
But my gracious Master was pleased not only to raise me up for the work,
but abundantly to strengthen and furnish for it,
beyond what has often been vouchsafed to me.

17th.--Reached Portland by six o`'clock a.m., accompanied by Samuel Boyce.
Arrangements were immediately made for holding a public meeting that evening.
It was smaller than anticipated, but on the whole was a solid comfortable season.
I found it very hard and exercising work to bear a testimony to the Truth,
under existing circumstances at this place.
Lodged at Peter Neild`'s, expecting to leave in the morning,
but on rising did not feel satisfied without sitting
with Friends of Portland in their own meeting,
although most of them had attended the public meeting.

18th.--Attended the meeting, which was small.
After a plain stranger Friend had twice said a few words, I was opened out among them,
to my own peace of mind, though in much plainness of speech.

19th--Left early by stage for North Berwick, passing in the course of the day,
a large Shaker`'s settlement, and were favoured to reach the house of John D. Lang,
the same evening.
Since being in Portland my mind has been much turned
towards an infant people residing in Nova Scotia,
who make profession with us;
and I felt freedom to make several inquiries as to the best mode of getting there;
but did not see how I could proceed farther without a suitable companion.
At one time, I intended passing through North Berwick,
and endeavouring to reach Newbury Port the same night,
but not feeling quite easy to do this, I concluded to stop there accordingly.

The next day, the 20th,
I found that J. D. Lang had been looking towards
visiting Nova Scotia in the fall of the year,
and had a certificate from his Monthly Meeting, granted some months ago,
still in his possession.
It soon appeared that he had given up to accompany me.
To myself this was a confirming evidence that my going
to Nova Scotia was in the ordering of the great Master,
who had thus led me in a way that I knew not, and in paths that I had not heard of,
to a companion of his own choosing; of whose intentions,
and having a certificate in readiness, I had not had the slightest intimation.
Our hearts in this thing soon became as the heart of one man,
bound together in the bonds of the everlasting gospel.

J+++.+++ D. L. accompanied us to Newbury Port,
where efforts were made to arrange for a public meeting to be held the next day;
but it appeared that so many meetings of the
Universalists and Methodists would occur that day,
that it would be unwise to attempt it, however much desired.
As I had done all that I could to obtain a meeting with the inhabitants of this port,
having purposely come about eighty miles to the place, my mind felt easy on the subject.

21st.--Attended the meeting at West Newbury where the neighbours came in,
and a comfortable season was vouchsafed to us.
In the afternoon travelled about twenty-eight miles to Lynn,
and reached the house of Isaac Basset in good and I trust in safe keeping.
The next day took leave of J. D. Lang and went to Providence.

24th.--Attended the Monthly Meeting,
in which I had to bear testimony to the ample and
simple means for salvation bestowed on every mortal,
through Christ the Saviour, who died that we might live.
In the evening went by railroad to Stonington, and there embarked in the steamboat,
with two hundred and seventy-five passengers for New York.

25th.--Arrived at John Clapp`'s in good time this morning,
and after attending to some needful arrangements, left the city the same day,
via Providence and Lynn to Boston, where we arrived on the 27th,
and prepared to embark in the Boundary sailing-packet for East Port,
which is the boundary port of the United States, my friend J. D. Lang having arrived.

Left Boston on the 28th,
and entered the passage towards East Port on the 30th.
Saw several Indians in their canoes fishing,
as we entered the Narrows.
In the hope of meeting the steamboat on her way from East Port to St. John`'s,
in the British province of New Brunswick, had our luggage prepared and brought on deck.
The paddle of the steamer was heard for some time before she could be seen,
the fog was so dense; but her captain told me afterwards,
that he saw our mast-heads above the fog, and had steered for us.
We got safely on board the steamer, to my rejoicing,
having scarcely ever been more uncomfortable, or suffered more for lack of rest,
than while in this packet.
Reached the city of St. John`'s the same evening.
Here we found two members, and several more or less connected with the Society,
in all about twenty persons, with whom we had a sitting.
My companion broke the silence, and we were afterwards favoured with an open time.
I trust that some were encouraged to hold on their way, and the lukewarm and indifferent,
as well as those who had been wholly neglecting the Lord`'s talent,
were warned and entreated to avail themselves of their day of visitation.
Returned to the steamer, and started at midnight for Windsor, in Nova Scotia.
Arrived there early next day, and proceeded by stage to Halifax,
which we reached the same night, the 31st.

Eighth Month 2nd.--Having secured places to Picton yesterday at an early hour,
this morning repaired to the coach office, and found that instead of a covered carriage,
an open wagon was provided for our conveyance,
and this to all appearance very unequal to the journey.
After crossing the water by steam to Dartmouth, we mounted our vehicle,
and proceeded much better than we had calculated on,
through a very rough and uncultivated country.
The roads were in fair order,
and small detachments of a British regiment were employed for their farther improvement.
On reaching the first station, twenty miles distant, we found to our great mortification,
that at least one of the horses had to continue at its post,
though perhaps changed to another position in the team.
Lodged for the night at Truro, a pleasant country village.
Reached the neighbourhood of Picton next day, and when within three miles of the town,
a Friend seeing our garb as we passed, came out of his shop by the way side to greet us.
This was James Kitching; and we had intended stopping at the house of his brother,
some distance further on: but finding that he was from home,
we at once concluded to accept the hearty invitation of J. K., whose cottage was hard by.
The father of our host,
who made one of this large family and their apprentices in the shoe-making business,
was originally a member of Society,
and had emigrated from Whitehaven seventeen years ago.
In the evening after a portion of the scriptures was read,
we had a religious opportunity with the family, and were comforted together.

4th.--Sat down with the little remnant that meet
regularly at J. Kitching`'s. Several persons attended,
until every seat was occupied.
Notwithstanding there was a precious seed in this company,
we found it hard work to wrestle against those who are
making only a lifeless profession of the Truth,
and are led away by the pursuit of the perishing things of this world,
to the neglect of those which are of eternal consequence.
It was however a season, in which the Lord`'s faithful children were contrited together.

In the evening attended a public meeting in the
meetinghouse of the Seceders from the Scotch kirk,
for which arrangements had been made the day before.
For some time it was heavy work to labour among them, but towards the latter part,
the blessed Truth had the dominion; and although some went out,
yet a number of the weightier spirits seemed reluctant to
separate from under the precious covering that prevailed.

5th.--Early in the morning the stage stopped to take us up,
when we took leave of this family, who had become dear to us in the love of the gospel.
J+++.+++ Kitching accompanied us the first stage, where we breakfasted; and before separating,
we were refreshed together in that love which makes one in the Lord.
Travelled hard till nightfall, and got to Halifax by one p.m. the next day.
The 6th, having previously engaged horses, after dining on wild raspberries and milk,
we resumed our journey in an open wagon, and reached Windsor about midnight;
not without difficulty procuring a lodging place,
many persons having arrived to embark in the same
steamer with ourselves on the following day.
We had been travelling nineteen hours.
After it became dark, about fifteen miles from Windsor,
we found that a bridge over which we had to pass, was broken up and impassable.
As we drew near it, we were hailed by two negroes, who told us we could not go that way,
but must drive through the water, across which they had themselves waded.
These men were on their way to Halifax, and had it not been for them,
we must have been quite at a loss how to dispose of ourselves for the night.
My companion J. D. Lang, to lighten the wagon we rode in,
had at the last halting place agreed to join
another traveller who had overtaken us in a gig,
and like ourselves was going to Windsor.
As we were then in advance of the gig,
we waited on that side of the water till they came up,
as they were equally strangers to the state of the bridge;
and in due time we drove through the water in company.
I thought the Divine arm was in this thing.

7th.--Left Windsor in good time, but our progress was greatly retarded,
by having to take in tow a vessel, which had only just been launched.
Soon after ten at night,
the fog became so dense as to oblige us to anchor until day-light,
when we again pursued our way, still towing the other vessel,
and reached the town called St. Johns, by ten o`'clock a.m.,
of the 8th. We were kindly received at our former quarters,
and arrangements were immediately commenced to procure
a meeting with the inhabitants the same evening:
the Wesleyan Methodist meetinghouse was cheerfully granted for the purpose.
At the first collecting of this meeting, things appeared not a little discouraging;
but before its conclusion our compassionate Lord condescended
to magnify His power among us in a remarkable manner,
and to own it with the life-giving influence of His heavenly presence.

9th.--Early this morning we again embarked in the
steamer for Annapolis on the other side of the bay,
touching at the village of Digby by the way.
About twenty-five miles farther is Annapolis,
where we were favoured to land safely that afternoon.
This neighbourhood and for many miles up the river, is thickly studded with farm-houses,
at the foot of a high mountain.
On landing we were met by an individual connected with Friends,
who eventually took us to his residence, about fourteen miles up the country.

10th.--In the evening attended a public meeting
in the Wesleyan meetinghouse at Bridgetown:
being a Seventh day, and the hay-harvest in progress, it was small;
but a comfortable season was vouchsafed,
and the blessed Truth was freely declared to the people.

11th. (First Bay.)--Rising early, we crossed the North Mountain to Chute`'s Cove,
where a number of people were collected, some of whom profess with us.
Both my companion and myself had a searching testimony to bear among the latter,
and an awakening one also to others present, among whom were some tender spirits.
As another meeting had been appointed to be held at Bridgetown that afternoon,
there was but little more time than was necessary to take some refreshment,
and again to cross the mountain.
This was heavy work for both man and beast,
as the road in many places lay over steep bare rocks,
where it was difficult for the horse to obtain foot-hold.
The distance is said to be eight miles; but it took us three hours to perform it.
We were favoured to arrive in time for the meeting,
for which the use of the Baptist meetinghouse had been granted:
this proved the largest meeting we had in these parts,
and was mercifully owned by the Master`'s presence.
Both J. D. Lang and myself had largely to declare the word among them,
and I believe we both felt peaceful minds afterwards.

12th.--Returned to Annapolis by stage, which was merely an open wagon.
We soon found there was no probability of the people being collected,
so as to hold a meeting to profit,
as they were fully engaged in the fields with their harvest;
and to many of them it would have been difficult to convey the requisite information.

13th.--At two a.m. went on board the steamer,
not inappropriately called The Maid of the Mist,
on account of the misty atmosphere of the bay.
After touching at Digby,
where we waited an hour and a half before the mail-bags were given out,
we had to make a considerable round to take in tow a new vessel;
but on reaching the point, we had the mortification to find she was not yet launched,
and we should have to wait in an exposed situation until high-water,
then six hours distant.
Every appeal to the captain,
and even the threatening of a lawyer passenger were disregarded,
so that instead of getting to "`St. Johns`" by nine in the morning,
it was not till long after sunset that we entered the harbour.

14th.--Took passage in the same comfortless boat to East Port, State of Maine;
here our luggage was slightly examined, as coming from a foreign country.
Went forward again by stage to Bangor, on the Penobscott river;
from there by steamer to Portland on the 16th;
and finally reached the house of my dear companion J. D. Lang, at North Berwick,
on the 17th. I trust with feelings of thankfulness for the many
deliverances we had witnessed in the course of our journey.
A considerable quantity of religious tracts, and the writings of Friends were circulated,
and in some instances deposited as libraries, along our route.

18th. (First Day.)--At the meeting at North Berwick,
to which several seeking people came; we were favoured with a blessed season.
In the afternoon attended a funeral at Dover, thirteen miles distant.
The meeting was not held at the regular place, but at the house of the deceased.

20th.--Attended the Monthly Meeting at Dover.
The meeting for worship was a heavy season,
as when "`death is in the pot;`" the one succeeding it was equally painful.

21st.--Attended the Dover Select Meeting.
We sat long in a low state, as in the deeps;
when it was with me to break the silence with this language,--"`Awake, O! north wind,
and come, you south; blow upon my garden, that the spices thereof may flow out.
Let my beloved come into his garden,
and eat his pleasant fruits;`" endeavouring to show the necessity of our
being willing to pass through that stripped wintry state,
in which nothing can live that is not of the Lord`'s planting,
and which can prepare our hearts to bring forth fruit,
such as the beloved of our souls delights in.
Several others spoke to the edification of the meeting.
The Quarterly Meeting commenced with a large meeting for worship,
in which I had some labour: it was the first yet held in a new meetinghouse.

22nd.--Feeling bound to attend the Ohio Yearly Meeting,
and having the opportunity of accompanying William Deweese, we set out together this day,
and reached New York on the 25th;
the latter part of the journey in the steamer Lexington.
I was no stranger to the character of this vessel,
and had on a former occasion avoided travelling by her; but now I had no time to lose,
and trusting in that Almighty power, which has so often been my preserver,
we were favoured to reach New York without accident.
Here I found distressing accounts from my family.
In addition to the continued indisposition of dear Charles,
it appears that the health of my eldest son Joshua had so much declined,
as to oblige him to return to England.
I cannot but feel tried under this increased affliction,
but I desire to be resigned to the will of my heavenly Father,
in the belief that he does indeed not willingly afflict the children of men.
Attended the forenoon meeting for worship,
and was strengthened to declare among them the way of salvation from sin.

On the 26th, we reached the house of my kind friend Ellis Yarnall of Philadelphia.
While here, I felt best satisfied to write to my children,
holding out the probability of my returning to England after the Ohio Yearly Meeting,
if the way should appear to open for this measure with clearness.
Reached Harrisburgh, the capital of the State of Pennsylvania, the next day,
and from this place proceeded by packet drawn by three horses on the Pennsylvania canal,
along the beautiful valleys of the Allegany mountains,
eventually crossing the Susquehanna river by a long and well constructed bridge.
Beyond Lewistown the valleys become wider and better cultivated,
and the general appearance of things strikingly different to
what we had lately seen in the State of Maine,
in New Brunswick, and Nova Scotia.

28th.--After a night disturbed by passing many locks,
we are still winding our way through beautiful valleys,
backed although rather more distantly by well-wooded mountains.
Have employed the interval of leisure in bringing up my
journal which had fallen into arrear,
believing that I shall not soon have a more favourable opportunity.

On the 29th reached Hollydaysville, where the railway over the Allegany mountains begins.
Drawn sometimes by locomotive, at others by stationary engines, then by horses,
and eventually descended an incline, and again proceeded by canal to Pittsburgh.
From this town we proceeded by steamer along the Ohio river to Mount Pleasant,
where we arrived on the 1st of Ninth Month.
The Yearly Meeting is held here.

Ninth Month 2nd.--The Yearly Meeting at large commenced, when my certificates were read,
and I had to give the meeting some account of the Lord`'s merciful dealings with me.
The Yearly Meeting ended on the 7th, and was favoured to its close with great solemnity.
In the last sitting of the Select Meeting,
I had some remarks to make on the great responsibility of those in the station of elders,
who, if not anointed from on high,
are incapable of discerning from where the ministry proceeds; and to add my belief,
that there is a ministry growing in the Society, which, if not checked,
would fill the minds of the hearers with things like "`the abomination of
desolation,`" spoken of by the prophet,--that would stand in the holy place,
where it ought not,--in the place of vital religion,--and would make
truly desolate and destitute of the presence of the Lord.
It was the elders of Ephesus who were sent for, and charged to take heed to themselves,
and to the flock, by the great apostle.
Set out the same evening in company with several Friends,
on my return towards Philadelphia, which we reached on the 12th,
after a fatiguing journey.

15th. (First day.)--In the forenoon meeting I was
largely engaged in declaring the blessed Truth.
I had taken cold, and my cough troubled me during the early part of the meeting;
but on standing up, to my admiration, it was no more felt.
During the silent part of the meeting, it had been suggested to me,
when in expectation of having to speak,
that it would be in vain to attempt it on account of my cough,
which would be immediately excited by raising my voice;
but this I believe to have been the work of the enemy, who was a liar from the beginning;
for I stood long without once coughing, to my own great relief.

16th.--Went to Burlington, and spent the night at the house of dear S. and R. Grellet.
In the evening many Friends came in;
and we were comforted together by the life-giving presence of the gracious Master.

22nd. (First day.)--In the forenoon my mouth was opened,
and my heart enlarged to declare, in the love of the gospel,
the new and only way to the everlasting kingdom.
In the afternoon, silent.

25th.--At a marriage in Twelfth Street meetinghouse, Philadelphia,
which was numerously attended by the public;
I was strengthened to declare the day of the Lord among them,
and to show that it is not to the mighty or the noble, not to the wise or the prudent,
that the things of the heavenly kingdom are revealed; but to the weak and despised,
to the unassuming and childlike:
rehearsing the beautiful and instructive acknowledgment
of our blessed Saviour,--"`I thank you,
O! Father, Lord of heaven and earth,
that you have hid these things from the wise and prudent,
and have revealed them unto babes: even so, Father,
for so it seemed good in your sight.`"

26th.--Took leave of Friends as extensively as time and circumstances would permit;
and the next day proceeded to New York.
Here I examined the British Queen steamer, and the Mediator packet ship; and concluded,
for various reasons, to take passage in the latter.

Tenth Month 1st.--Finally embarked for England.
Several kind friends accompanied us as far as the vessel was towed out to sea,
returning with the steamer.
Forty passengers were on board, twenty of whom are in the cabin.
May the Lord preserve me in watchfulness and prayer among them.
We were favoured to get sight of the Scilly Islands on the sixteenth day,
when the wind changed and blew strong from the eastward,
so that we did not anchor on the Mother Bank till the 23rd instant.
The company on board proved one of the most agreeable that has ever fallen to my lot.

Left the vessel at Portsmouth,
and after writing to inquire where the wreck of my family were sojourning,
crossed the Isle of Wight to Niton,
where I was comforted by the particulars I gleaned of the close of my precious William;
and I had an opportunity of acknowledging personally,
the Christian kindness of several whose hearts had been
opened to administer to the comfort of his last days.
Spent a solitary evening at the hotel,
and occupied the chamber from which his immortal
spirit had returned unto God who gave it,
purified I humbly trust, through the blood of Jesus,
and prepared for an admittance into the everlasting kingdom.
