== Chapter XXXVII.

[.chapter-synopsis]
* Alarming Illness of His Son Charles, Then In France
* Daniel Wheeler Proceeds There Before the Death of Charles
* Returns to England
* Again Sails for New York
* Last Illness and Death

On the 25th of Tenth Month, I learned that my children had left England,
with the idea of wintering in the South of France;
but that my dear Charles had been so much exhausted
with travelling before they reached Paris,
that the hope of continuing the journey had been relinquished.
I also learned that they were accompanied by our
true friends Wilson and Charlotte Burgess,
which was quite a relief to my mind.
Having now accomplished my mournful purpose,
and visited at Southampton the grave of my first-born,
I should have proceeded immediately in the track of my children;
but that several circumstances compelled me first to return to London.
This detained me till the 29th, when having obtained my passport,
I went down to Dover by the night mail,
intending to join the steamer for Calais in the morning.
The day, however, proved so stormy,
that it was with some difficulty I could procure a boat to take me on board the steamer,
at that time hovering off the Foreland.
At length I succeeded in hiring a stout boat with five men,
who were willing to make the attempt.
The risk was not a little; but on viewing the storm,
and remembering the situation of my drooping child,
who had so faithfully shared all my toils and
cares during our long voyage in the Pacific,
the thought of danger was at once outbalanced;
and trusting in Him who knew my motive for making the attempt,
at a suitable moment we launched into the surf,
and were favoured to get well off the strand;
and the steamer being judiciously placed to enable us to reach her,
I was favoured to gain her deck without accident.
After leaving the coast the captain soon found that we could not fetch Calais,
and very prudently bore away at once for Boulogne,
without making any fruitless efforts to reach the other port.

After a lonely winterly journey, arrived in Paris late in the evening of the 31st,
and the next day was favoured to reach the bedside of my sinking Charles,
in the little town of St. Germains, twelve miles distant.
The peaceful feeling that pervades the atmosphere around him is, I humbly trust,
an earnest that the arms of everlasting mercy are open to receive him,
when the awful change shall come.
I found him apparently in a far advanced stage of consumption,
and my dear Joshua looking very much shrunk, and altogether in very delicate health,
although not actually confined to the house.

[.letter-heading]
Extract from a Letter to Sarah Smith

[.signed-section-context-open]
St. Germain`'s, +++[+++so called,] near Paris, Eleventh Month 2nd, 1839.

Little did I then anticipate that it would ever
be my lot to address you from this neighbourhood;
but I was very unexpectedly prompted to look towards crossing the Atlantic,
if only for a season,
should the way fairly open after the close of the Ohio Yearly Meeting,
and the step be approved by my American friends.
During the first sittings of the above meeting, I felt discouraged,
and doubts arose in my mind whether I could possibly clear myself
towards that large assembly so as to feel at liberty when it was over,
as I had been prevented by the lowness of the water in the
Ohio from arriving in time for the two public meetings held
previously to the sitting down of the Yearly Meeting;
but at the conclusion an opportunity was afforded me of seeing
the whole body of Friends collected under one roof,
I suppose two thousand persons; when to my unexpected consolation,
a most relieving season was vouchsafed.
During the last sitting, I had a full opportunity with women Friends,
and afterwards in the men`'s meeting, before the concluding minute was read.
I now felt perfect freedom to leave Mount Pleasant, and proceeded eastward the same night.

We have the comfort of having our friends Wilson and Charlotte Burgess with us;
so that amidst our sorrows we are still favoured
with many blessings which sweeten the bitter cup;
and when I reflect that I have not to grieve for the misconduct of my
children as having brought this affliction upon themselves,
my heart is humbled under a sense that the present dispensation is of
the Lord;--desiring to bow very low before Him,
and believing that it is by these things we live,
and in all these things is the life of our spirits.
Our dear friends will I hope remember us,
as I am sure we stand in need of the prayers and sympathy of the faithful,
if ever any poor creatures did, under the accumulated trials of a dark and cloudy day;
that so we may be preserved in humble resignation to
the unerring will of our heavenly Father,
and that others may see by our patience,
the blessed effects of the power of the Spirit of the Lord Jesus, "`in word,
in conversation, in charity, in spirit, in faith, in purity.`"

[.offset]
+++[+++Although it is not proposed here to record the details of
illness which follow in Daniel Wheeler`'s M.S. journal,
it was thought that the following sketch which occurs after the decease of our brother,
possessed sufficient interest to warrant its insertion.]

Although my dear Charles had been nearly two years in a critical state of health,
and for the last six or eight months rapidly declining,
he did not appear entirely to lose the idea of recovery,
until about a fortnight before his decease: of its great uncertainty he was fully aware.
In the early part of his illness he would say, "`if it be the will of my heavenly Father,
I could enjoy life a little longer`" but in its more advanced stages he would acknowledge,
that '`"`life is no longer desirable, under such an accumulation of suffering:
but the will of the Lord be done.`" About twelve days before his close, he said to me,
"`I am going,--I see it plainly`" and then adverted to a
check which had occurred in his disorder,
and had been the means of allowing him to see all his family;
speaking of it as a mark of Divine condescension, quite incomprehensible to himself.
"`It is one of the links in that chain of providences,
with which I have been so marvellously encompassed.`"

He used frequently to compare his own case with those
of others in the family who had preceded him.
Speaking about this time of dear William, he observed, "`I know little about his death,
but I know how he lived; he fed on heavenly food.
O! that I were as much prepared for the change as he was,--to him,
to die was but to sink into his Father`'s arms;`"--adding with much emphasis,
"`blessed are those who can die as he did.`"

He often spoke of his own unworthiness, saying,
that his only dependence was on the mercy of God in Christ Jesus;
and on this he seemed to rest without a sense of fear.
Once or twice, when referring to the composure he felt, he said,
"`surely I am not self-deceived;`" shortly adding, "`O! no; it cannot be that the mercy,
which has so signally followed me up to the present time, should now forsake me.`"

On one occasion, he said to one of his brothers, "`heed not the world,
nor the things thereof:
I wish I had heeded it less;`" and once when in great bodily extremity, he exclaimed,
"`here is the end of pride!`"

He frequently engaged in fervent prayer for patience and support,
for the pardon of all transgressions, and a release in the Lord`'s time.
Three days before his death, he was heard to say,--"`Bless the Lord,
O my soul! and forget not all His benefits.`"
Even though He slay me, I will trust in Him.
Blessed be His name, He has granted me a little relief.
One crowning mercy yet remains; and for this I desire to wait His time.
O! grant me grace for this.
You, O Lord! are full of compassion and gracious,
or you wouldest long ago have abandoned a wretch like me:
even yet I feel my proneness to rebel.
O! let your Holy Spirit support me through the few fearful hours that may remain;
and grant me patience to wait your time.
I ask it for the blessed Saviour`'s sake.`'

A text on which he frequently dwelt, was that in Revelations,
"`They shall hunger no more, neither thirst any more,`" etc.;
and perhaps his own sufferings from thirst, which were at times distressing,
led him to realize more fully the blessedness of those
thus set free from the infirmities of the flesh.
A few days before his death, when parched with fever, and much exhausted, he exclaimed,
"`I shall soon be where all is rest, and more than rest,`" referring to the passage,
"`Eye has not seen,`" etc.

One evening when in a very suffering state, he remarked,
that this was a new kind of conflict to him,--he
had long been accustomed to mental conflict;
but such positive physical suffering, he had neither known nor imagined.
On being asked which he thought the more difficult to endure, he replied,
that in his present state, he greatly preferred the contest allotted him; but,
that when in health, when the mind was vigorous,
he thought the mental struggle less severe.

On the morning of the 5th, (of Second Month, 1840,) we thought him very near his close;
but he afterwards revived, and seemed disappointed at being again delayed.
On the same day, when in severe pain, he supplicated thus: "`O! Lord, if it please you,
grant me a little patience; for without your holy aid,
it is past all mortal endurance.`" As evening approached,
he seemed to have an extraordinary dread of the coming night, exclaiming despondingly,
"`another night, another night;`" and truly it proved a season of severe conflict,
though the last of mortal suffering.
About nine p.m., a change was noticed, which he soon detected himself,--saying,
that he thought he was dying; and shortly afterwards, "`O! Lord,
if it please your righteous will, release me.
Blessed be your holy name!`" A short time before the close,
on being asked if he felt peaceful, he replied calmly,
"`I feel no fear.`" He bade us separately farewell;
and I believe his last connected expressions were,--"`You are very kind--the Lord
Almighty bless you.`" The pains of the body seemed all he had to contend with:
the struggle continued until four a.m., when he quietly expired,
being apparently sensible till within a few minutes of the last.

Dear Charles`'s desire that I should pray for him, when on the bed of sickness,
often tended greatly to my own humiliation,
it being at that time frequently my lot to be as one unable to pray even for myself;
and when the spirit of supplication was at seasons permitted to influence my mind,
it was not that length of days should be added to his life,
or that it should be shortened; but that the will of his heavenly Father should be done,
whatever it might be;
and that all his afflictions might be sanctified to his eternal benefit:
and strong were my cries to the God and Father of our Lord Jesus Christ,
that though the dear sufferer might not be permitted to give us any strikingly
comforting assurance of his being "`accepted in the beloved`" yet that an evidence
might be vouchsafed of his having been admitted into that heavenly kingdom,
which shall never have an end.
On looking at his remains some hours after his departure, to my unspeakable comfort,
I saw on his placid countenance that evidence for which I had besought the Lord.
In the midst of death, there was a sweet angelic smile,
surpassing that of life,--its loveliness none can describe.
In the course of the illness of my dearest Charles,
and the frequent opportunities we had of close
converse on subjects of the highest importance,
he never once brought into view his having forsaken all from an apprehension
of duty to accompany me on the long voyage in the South Seas.
To have reminded him of a sacrifice which had cost him so much;
and which I humbly believe was not only called for, but accepted at his hands,
by Him who had prepared the offering,
would but have raised a feeling of honest indignation in his mind,--
that an idea should be entertained of any merit being due to him,
or that he had any act of dedication to lean upon, or to plead his cause.
On the contrary, he seemed truly to possess nothing of his own,
but the infirmities incident to the frailty of human nature;
often dwelling on his own unworthiness of the
least of all the Lord`'s mercies extended to him,
and alluding to them in humblest gratitude.
Doubtless it was best that he should cherish so humble a view of himself;
and I never found it my place to throw out any hint,
by way of encouragement to his often drooping mind:
preferring to commit him into the hands of Him who judges righteously,
whose compassions fail not;
and who never fails freely to forgive all that have nothing of their own to
pay unto their Lord,--who are truly poor and of a contrite spirit.

+++[+++The remains were removed to Southampton, and]
interred within a few feet of those of his beloved brother William:
dear Maria S. Fox kneeling at the grave side,
offered the tribute of thanksgiving and praise to that gracious Being,
who had thus prepared and taken to Himself, him for whom we mourned.
The meeting afterwards proved a solemn, and I trust, an instructive season,
wherein the life-giving presence of the great Master was felt.

My attention was next turned towards finding a suitable situation for my dear Joshua,
whose declining health rendered it needful to remove
into some of the more sheltered parts of the island;
and the west being strongly recommended, we made our way towards Bristol,
and succeeded in obtaining apartments for him at the Hot Wells,
(sheltered by the stupendous cliffs from which the place above takes the name of
Clifton,) which were considered very suitable for him in his present weak state.

Third Month 8th. (First day.)--Attended both meetings at Bristol;
and in the forenoon had to declare the Truth among them, to my own relief.

Feeling my mind attracted towards Balby Monthly Meeting,
I set out in time to attend the Select Meeting at Sheffield on the 11th:
I was comforted in beholding the addition that
had been made to their numbers during my absence;
and my mouth was opened among them, in an encouraging manner.
Next day attended the Monthly Meeting.
In the meeting for worship that preceded it,
my heart was enlarged towards my dear friends;
and the way of life and salvation was proclaimed among them.

15th.--Attended the meetings at Dewsbury, in both which my mouth was largely opened.

23rd.--Bristol.
Through all the vicissitudes which have of late attended my tribulated path,
the inhabitants of the western world have been renewedly brought to my remembrance,
under a feeling of that love,
which would gather all mankind into the one great sheep-fold of rest and peace,--
though I have felt no liberty to take any decided measures till lately:
but the way has within the last few days so remarkably opened,
as to remove every doubt from my mind of the propriety
of making preparations for my departure there.

Finding it was in vain to attempt seeing my long
loved friends in other parts of Yorkshire,
I took leave of my Sheffield friends on the 18th, and proceeded to London,
where a place was secured for me in my favourite ship the Mediator.
After settling some affairs there, I returned to this place,
to spend with my children the few days yet remaining, till the sailing of the packet.

27th.--At the week day meeting in Bristol, I stood up with the words,--"`Then restored I,
that which I took not away;`" stating that these
expressions had attracted the attention of my mind;
and although the mysterious language of inspiration,
I believed they might be understood by all who had
passed through the great work of regeneration.
The Lord Jesus restores the heavenly image in man, which was lost by transgression:
and which the shedding of His precious blood had placed
all in a capacity to have restored to them,
who believe in Him,
and are willing to submit to the power of His Holy Spirit in their own hearts.
The poor of the Lord`'s people were encouraged;
and the heaven-born sons and daughters of Zion strengthened to trust in their God.

28th.--Took leave of dear Joshua,^
footnote:[Joshua Wheeler survived till the following spring.]
and accompanied by my dear S., went to Portsmouth to meet the ship,
which was to leave London on the 26th. The next being First day,
knowing of no Friends residing in this town, we remained at home,
and enjoyed a quiet and peaceful Sabbath together before the
Lord,--something like a little passover before the painful
moment of separation which was fast approaching;
it brought with it the bitter cup of which we had before so largely partaken,
but now under the pressure of more sorrowful circumstances.

30th.--Embarked in the Mediator; it was late before our final departure,
and it grew dusk soon after sailing.

31st.--Worked all day against a head-wind,
of sufficient strength to confine the major part of our company to their berths.
To myself, I seemed like a poor outcast among them;
and could I not have felt something like a foundation cause for being there,
sufficiently firm for me to ground an appeal in brokenness of
spirit to Him from whom nothing can be hid,
there would have been nothing for the feet of the mind to rest upon.
It is no light matter, at my age, to embark singlehanded for the American shore;
but I have been so mercifully led, guided, and sustained through all my late trials,
that I dare not for a moment doubt my being in my right allotment;
and particularly because of the peace and love which have not
infrequently been permitted to flow through my heart,
since having again forsaken all that is dear to
me in this world for the blessed Master`'s sake.

Fourth Month 1st.--The wind backed so far to the southward of west,
that we made a good slant down the British Channel.
In the night the Mediator was enabled to point to the right course,
though with nothing to spare.

2nd.--Wind to the eastward of south, and in the night became still more favourable,
when all sail was crowded to the breeze, and every advantage taken of it.
Eventually it became a strong breeze from the north-east.
The ship now made rapid progress, and but for an old north-west swell,
the motion would have been comparatively trifling.
On the 3rd we were found to be in longitude 13° 30`' west; and now the 4th,
being Seventh day afternoon, we are still rolling on with a fair wind,
though its strength has somewhat lessened.
Yesterday before breakfast the sea made its way through the cabin windows,
some of which had been raised for the admission of air.
Happily no material quantity of water got in,
though it ran to the far end of the main cabin; my cabin escaped,
which I consider a privilege and favour.

[.asterism]
'''

Here our dear father laid down the pen never to resume it,
except to address a few trembling lines to his children from his sick bed.
It appears that after he had been about a week at sea, he took cold,
which soon settled on the chest,
and was accompanied by great oppression of the breathing,
and inability to use a recumbent position.
As there was no surgeon on board,
he could not have the medical treatment which his symptoms so urgently demanded,
and though in every other respect he received the utmost attention and kindness,
his disorder gained a fearful ascendancy during the
three following weeks which he remained on ship-board.
A few days before the vessel reached her destination,
he was so extremely ill that his fellow-passengers
doubted his surviving till they entered their port.
He had himself, however, no apprehensions on this head; and on the 28th of Fourth Month,
he was landed at New York, in a very feeble and suffering state.
He was immediately taken to the house of his kind friend John Clapp,
from whose family he was favoured to receive the most unremitting and tender care,
during the remainder of his illness.

The change from the inconvenience of ship-board, to comfortable accommodations on shore,
combined with the tender assiduities of the dear friends around him,
appeared to be refreshing to him.
The night after landing he rested well, and the next morning seemed so much better,
that those around him felt quite cheered respecting him.
Towards the evening of the 29th, however, he became greatly oppressed,
and lay in a very suffering state.
After passing a restless night,
in the morning of the 30th the oppression returned with increased violence;
and from the coldness of the extremities,
and the state of exhaustion to which he was reduced,
it was thought by his medical attendant that he could not long survive.
On being informed of this by a dear friend, he replied calmly,
'`All has been done that could be done; only write to my dear children how it is.
The work has been going on with the day.
Love to all my friends on this side of the Atlantic, as well as the other.
It is a great thing to be clear of pain.
I want nothing but the love of my heavenly Father,
and I witness it.`' After remaining for some time in this state,
the oppression gradually subsided, and he enjoyed some hours of tranquil sleep.
This refreshed him much, and towards evening he had so far rallied,
as himself to address a few lines to his distant family;
they are written in a very tremulous and almost illegible hand.
In these he remarks, '`I have been landed a very sick man in this city;
but my most gracious Lord has borne me up in a marvellous
manner through a multitude of distress and difficulty,
for His great name`'s sake,
and for His dear Son`'s sake;--to His own
everlasting praise be it spoken:`'--thus evincing,
that thankfulness and love to our heavenly Father,
so conspicuously the covering of his mind in the time of health,
still pervaded his spirit on the bed of languishing.

For several succeeding days his disorder fluctuated greatly:
at times he appeared very comfortable, and then again laboured under great oppression.
On the night of the 1st of Fifth Month, a friend sat up with him,
whom he had not seen since his return to England the preceding autumn.
On observing him, he said,`' Ah +++_______+++, I have had a suffering time since I left America;
but I have been mercifully directed as to a hair`'s breadth.`' Then spreading out his hand,
he added, '`Yes, plainly,
as if I had had a scroll of directions in my hand.`' Towards morning,
when apparently in a very exhausted state, he said to those around him, '`Well now,
my dear friends,
I want to be left entirely alone with my heavenly Father;`' and
several times during his illness he made a similar request.

On the 2nd, he was bled from the arm,
which produced considerable relief to the breathing:
the following day the bleeding was repeated,
and again the oppression appeared to be diminished by it.
During the operation, he remarked to his medical attendant,--'`without blood,
there is no cleansing.`' Dr. Willet replied,--it is
"`the blood of Jesus that cleanses us from all our sins.`"
'`Yes,`' said his patient, '`but not in our natural unregenerate state:
when we are in the light, as He is in the light,
then I believe it will cleanse us from all our sins.
Yes,`' he added with much emphasis, '`I know it.`'

Through the day he appeared more comfortable; but in the evening the oppression returned,
accompanied by great prostration of strength.
This continued nearly an hour; when a little revived, he said,
'`I have had a hard struggle.
At one time I did not know but it was the cold sweat of death.`'

On the 4th, 5th and 6th, he remained in a suffering state.
On the morning of the latter day, after making some arrangements respecting his papers,
etc., he said he had now done with the things of this world; he had no wish to live,
but for the sake of his family,
and that the Lord Jesus might live in him;--He had been his guide for many years,
and he had declared His name unto thousands:
he had no hope but in Him;--He was the same Lord over all.
It was not the prospect of an immediate release that led him to speak thus,
for he did not see that; but it was in his heart, and he must say it while he had words.
Many other remarks he made at this time, in a very impressive manner,
and with a strong voice.
After this he had some refreshing sleep.

In the afternoon of the same day,
he received a visit from his beloved friend Stephen Grellet,
which proved an occasion of deep interest.
His mind seemed to overflow with admiration of the goodness of his dear Lord and Master,
which had constantly attended him in his varied pilgrimage.
He recapitulated briefly what had occurred since he left America,
alluding to the consolation he received at the death of his beloved Charles,
when he was made to rejoice in the midst of grief.
He added, '`the Lord is good to them that love and fear His name.
Great things has He done for me,--things so wonderfully marvellous,
that they would hardly be believed were I to tell of them.
If I have experienced any shortness in my journey Zionward, it has been on my side,
not the Lord`'s,--for He has been faithful, and his promises have been and remain to be,
yes and amen forever.
While I was on shipboard, and thought by some of the passengers to be nigh unto death,
how did the Lord appear for my help and consolation;
and since I have been in this chamber,
how has He appeared for my comfort in the night season;
and I have been enabled to sing hymns of praise and thanksgiving unto Him.
When the ship made her soundings, I made my soundings upon that Rock,
whose foundation is from everlasting to everlasting.
I saw that I should be safely landed, though extremely weak in body;
and I was enabled to say, should the Lord see fit to raise me up,
and strengthen me still to show forth His wonderful works to the children of men,
or cut the work short in righteousness, "`Your will O God, not mine be done.`"
I do not see how the end will be.`'

He spoke of the last First day he had spent in England,
and of the precious season before the Lord, which he had then enjoyed.
It was like a little passover, but whether unto death or unto suffering,
he could not tell.

For several succeeding days, the disorder appeared very stationary:
he lay in a languid state, but apparently suffering little positive pain.
On the 11th, he received a letter of sympathy from a kind friend,
who remarked that he felt a very comfortable assurance
that the Lord would still continue to protect him,
etc.
The dear sufferer said that he was too ill to write himself,
but wished those about him to do so,
and to tell his friend that he believed it would be as he had said; adding,
'`I feel the Saviour to be near me every hour of the day.`'

After this period, considerable mitigation of the symptoms occurred,
and for two successive weeks, he appeared to be slowly gaining ground,
so that his anxious friends were ready to take comfort
in the hope that his life might yet be spared to them.
For a time, he seems himself to have participated in this expectation;
and a very cheering letter written on the 13th to his children,
led them also to indulge the hope,
that the bitter cup might for the present be permitted to pass from them.
His full heart seemed to overflow with the love and praises of the Lord,
for all His rich mercies towards him;
and in the feeling of some degree of returning health,
he was afresh animated to pursue with unreserved dedication of soul,
the service of his dear Lord and Master.

On the 19th, he addressed a few lines to his family for the last time,
which breathed the same spirit of encouragement and thankfulness as his preceding letter.
The following is an extract.

[.salutation]
My Very Dear Children,

I wrote you a few lines on the 13th instant,
by the Stephen Whitney packet-ship for Liverpool; and again,
through Him who died that we might live,
I am enabled this day to send you a still better account of myself; at which,
with me you will rejoice in the true fear that keeps the heart clean.
You must accept it as it is, as in the present state of my convalescence,
it is impossible for me to delineate one-half of the Lord`'s gracious dealings with me.
I trust I shall be able to ride out for air daily in a short time.
The weather here is very hot,
which makes writing more irksome to me than it otherwise would be;
but I know that you will make every allowance for me.
Scatter abroad my love, wherever you go,--take as much as you can desire for yourselves,
and believe me,

[.signed-section-closing]
Your ever affectionate father,

[.signed-section-signature]
Daniel Wheeler

At this time he had rallied so much,
as for several days to be able to rise and be dressed,
and to walk with assistance into an adjoining room;
and the improvement in his appearance,
and the cheerfulness of his spirits quite encouraged those around him.
Soon, however, these pleasing prospects were overcast,
and the last fondly cherished hope of his restoration to health entirely faded.
On the 26th of Fifth Month, he appeared rather drooping, and more feeble than before;
and after passing a most restless night, on the morning of the 27th,
he sank into a state of insensibility,
accompanied by a convulsive movement of the hands and feet:
in this situation he continued several hours.
When partially recovered from it, a kind friend called to see him.
On being told she was present, he held out his hand, saying,
'`you see a poor creature.`' '`Yes,`' she replied;
'`but rich I trust in the Master`'s favour.`' '`If it were not so,`' said he,
'`I should be poor indeed.`' She was afterwards engaged in supplication by the bedside,
fervently imploring the continuance of Divine love and mercy towards him;
but he seemed scarcely sufficiently collected to be aware of what was passing around him.
Towards evening, the stupor was in degree relieved,
and he passed a more tranquil night than the preceding one.

In the morning of the 29th,
he laboured for some time under great oppression of the breathing;
when this had a little subsided, our friend Jacob Green,
who was about returning to his home in Ireland, called to take leave of him.
At the conclusion of their interview, our dear father observed that as to himself,
he had no doubt:--he had the same faith that had been with him through life,
founded upon the gospel of Christ; and which enabled him to say with the apostle,
"`nevertheless I live, yet not I, but Christ lives in me; and the life which I now live,
I live by the faith of the Son of God, who loved me and gave himself for me.`"

30th.--This morning,
in reference to the ship in which he had come over from England having again sailed,
he remarked that the captain had gone and left him; but added in a moment,
'`if my heavenly Father cares for me, I shall fear nothing:
He will carry me safely through:--He is my only hope.`' For several days after this,
the dear sufferer remained in a very sinking state,
and the measures resorted to in the hope of relieving the disorder,
added to his debility.

On the 3rd of Sixth Month, a friend from a distance who had come to see him,
remarking how glad he should be in any way to help him,
our dear father replied,--'`I have but one Helper, but He is Almighty.`'

On the 6th, when his kind hostess entered the room, he was engaged in vocal prayer,
but she was unable to collect much that he said.
On some friends who were leaving the city calling to bid him farewell,
he said they must leave him in the hands of his heavenly Father,--to his love and mercy.
He could not tell half what had been done for his soul;
but the time might come when it would be proclaimed as on the housetops.
On a previous occasion, when the same friends were seated by his bedside,
one of them remarked,
that it was a great favour to see him preserved in so much calmness and quietness.
'`Ah,`' he rejoined, '`you would think so,
if you knew all;`' at other times he intimated the favoured state of his mind.

For several succeeding days he remained in a state of great feebleness and exhaustion,
apparently without much suffering, except from occasional oppression of the breathing,
and generally in a drowsy state;
so that he entered very little into conversation of any kind.
During this period, he took extremely little nourishment;
and his weakness increased rapidly in consequence.
From the state of the mouth and throat, he could not swallow without pain and difficulty;
and on one occasion as one of his affectionate attendants was urging
him to take something,--saying she thought he stood in need of it,
he replied--'`I think not; and when there is need,
my heavenly Father will enable me to take it, for there is not a pang I suffer,
but what is known to Him; and I have evidence,
that though far from home and my native land,
I am not forgotten.`' Thus mercifully was he sustained,
and his faith and confidence permitted to remain unshaken, amidst the sinking of nature.

On the morning of the 12th, he appeared unusually feeble,
though not apparently worse in other respects.
He was wheeled into the adjoining apartment as usual;
and shortly afterwards remarked to one of the family,
who had most affectionately watched over him,
'`perhaps this day will end all your cares and troubles.`' It was an unusual remark;
but as it was supposed to arise from the feeling of present weakness,
it did not excite any particular alarm.
The heat of the weather being oppressive, he was placed in a current of air,
and was almost constantly fanned.
His mouth he said was better;
but still it was with difficulty that he was induced to
make the effort to take any nourishment.
In the afternoon,
one of those around him making some allusion to his returning to England,
he remarked,--'`it is very doubtful whether I shall be permitted to return to
England.`' His friend expressed her hope that it might yet be permitted;
for though he felt very weak at that time, his symptoms were better than they had been:
his only answer was an incredulous smile.
After this he was supported from one bed to another;
but it was observed that his steps were more faltering than before.

Between four and five o`'clock that afternoon,
a young friend who had been much with him during his sickness,
and had watched by him a part of the preceding night, called to take leave,
as he was about to attend a distant Yearly Meeting.
Our dear father acknowledged his kindness, adding,--'`give my dear love to all my friends.
God reigns over all: His mercy and goodness have never failed me.
The end I have not been able to see.`'

About eight in the evening, being offered some tea, he remarked,
that he could not see it; and it was evident that his sight had quite failed.
Shortly afterwards he fell asleep; but his breathing was more laboured than usual.
This being observed, he was twice asked if he was comfortable, to which he replied,
'`yes.`' The difficulty of breathing continued, and he was turned partly on one side,
which not arousing him, his friends became alarmed; various means were resorted to,
but nothing seemed to afford any relief.
In this state he continued, apparently breathing with the same difficulty as before,
till a little after twelve at night, when he gently passed away without sigh or struggle.

The funeral took place on the 15th of the Sixth Month: it was largely attended,
and proved a season of much solemnity;
in which survivors were loudly called upon to follow the departed,
as he had been concerned to follow Christ.
Afterwards at the grave side, the voice of thanksgiving and praise ascended to Him,
who had sustained His devoted follower through all the conflicts and
trials of his pilgrimage,--who had prepared him for Himself through
the sanctifying operation of His grace,--and had now been pleased in
His abounding mercy to gather him in peace into the heavenly garner,
even "`as a shock of corn comes in his season.`"
