== Appendix

[discrete]
=== Appendix A:
// Note in book here to insert this back into story --lint-disable

[.embedded-content-document.letter]
--

[.blurb]
=== Letters of the Empress Elizabeth to Her Mother, Relative to the Last Illness and Death of Her Husband, the Emperor Alexander of Russia.

[.salutation]
Dear Mother,

I was not in a condition to write to you by the post of yesterday.
Today, a thousand and a thousand thanks to the Supreme Being,
there is an evident improvement in the state of the Emperor,
this angel of patience in the midst of his sufferings: for whom, upon whom,
will God manifest His infinite mercy, if not upon him? Ah,
my God! what bitter moments have I passed.
And you, my dear mother!
I figure to myself your anxiety; you have received the bulletin,
you have seen to what we were reduced yesterday, and last night.
But Wylie^
footnote:[Sir James Wylie, a Physician.]
himself says today, that the state of our dear invalid is satisfactory.
He is excessively weak.
My dear mother, I confess to you that I am not myself, and that I cannot say more.
Pray with us, with fifty millions of men,
that God will deign to complete the restoration of our beloved invalid.

[.signed-section-signature]
Elizabeth

--

[.offset]
__Second Letter, which soon followed.__

[.embedded-content-document.letter]
--

I have lost all--the angel is no more;--dead, he smiles upon me,
as he so often did while living.
There now remains to me only you my dear mother, with whom I wish to come and weep,
and to be present at the interment.
I shall remain near the deceased, and shall follow him as fast as my strength will permit.

[.signed-section-context-close]
Elizabeth

--

[.asterism]
'''

[discrete]
=== Appendix B:
// Note here to omit Appendix B --lint-disable
In the Petersburg Gazette, of the date of Twelfth Month 15th, 1825,
is contained an account of this insurrection; the extract from which,
although originally intended for insertion, want of space has compelled us to omit.

[.asterism]
'''

[discrete]
=== Appendix C:

[.blurb]
=== Extracts from the Account of the Last Illness of Jane, Wife of Daniel Wheeler, Inserted in the Annual Monitor for 1835.

It was on the 10th day of the Twelfth Month, 1832, N. S.,
that the fever which was to terminate the life of our dear mother first appeared;
but its form was for some days so mild,
and our fears were at that time so strongly excited by
the situation of another member of the family,
who appeared to be on the very brink of the grave,
that at first little apprehension was entertained of its serious nature.
At length, however, the high degree of excitement which was obvious,
amounting to a degree of delirium, awoke us to a sense of the awful reality;
but rational conversation was already nearly impracticable,
and we have no reason to think that our beloved parent was sensible of her situation,
till within a few hours of her final change,
which took place on the 19th of the Twelfth Month.
During this brief period, she appeared quite free from delirium,
and remained composed and sensible nearly to the close;
but her strength was so completely exhausted, that her attempts to speak,
which were many, mostly ended in a tremulous inarticulate motion of the lips,
which left those about her painfully unconscious of the
meaning which she appeared solicitous to convey.
Her countenance was, at this time, beautifully serene and peaceful;
and once the words "`Jesus`" and "`God`" were clearly distinguished,
though the import of the sentence could not be collected.
At another time, observing one of her children in tears, she said distinctly,
and with the utmost composure,--"`Look up for help:`" thus proving at
once the tendency of her soul in the hour of extremity towards the
great object of the Christian`'s faith and hope;
her consciousness of her own situation, and of surrounding circumstances;
and her practical reliance on that Omnipotent Arm,
which alone was sufficient to support at such a moment.

At length her respiration, which for some hours had been laborious, became more gentle,
till the beloved sufferer passed away without sigh, groan, or struggle,
leaving those around her bed unable to fix the precise moment at which the spirit fled.
A holy calm spread itself over our feelings,
and we remained for some time as silent as she on whom we gazed.
The swell of sorrow seemed completely hushed,
and the silent tribute of thanksgiving ascended to Him who had
graciously led our departed mother all her life long,
and had at last, in infinite mercy, taken her to Himself.
It was a moment of solemnity and favour, never to be forgotten by us;
in which all doubting was swallowed up, and the soul reposed,
with a richness and fulness of peace, altogether indescribable,
on the boundless goodness of God.

The external circumstances of our bereaved family at this juncture, were,
in some respects peculiarly trying.
One of us was still alarmingly ill, and the others were shattered by disease,
or worn down with anxiety and watching;
in the middle of a Russian winter,--our beloved father, as has been stated,
absent,--and not having a single member of our own Society, out of the family,
within our reach, we could not but feel our situation:
and a new difficulty immediately arose respecting the
interment of the mortal remains of our departed parent.
No burying-place belonging to the Society of Friends existed here,
and the adoption of any of those possessed by other bodies of professors,
was not satisfactory to the minds of some of us.
But Divine goodness never fails those who trust Him, and desire to obey Him.
The precise path of duty became gradually plain, and way was ultimately made,
in a manner we had by no means anticipated,
for the enclosure of a small space of ground near our dwelling,
for the purpose of interment.
This necessarily produced delay,
and the successive illness of three of the survivors still farther
postponed the performance of the last sad duty to our deceased mother,
and drew our attention from the dead, by most painful solicitude for the living.
In mercy, however, the lives of these were spared;
and on the 28th day of the Third Month, 1833, our mournful and solitary band,
bowed down at once by sickness and sorrow, followed to her isolated resting-place,
the remains of our late venerable mother.^
footnote:[Some of our readers may not, perhaps, be aware,
that such is the severity of the frost near Petersburg,
that no difficulty would arise in keeping the remains for the long period,
which circumstances rendered expedient.]

He who had graciously promised,
that where two or three are gathered together in his name,
there will He be in the midst of them,
was pleased to support our afflicted and drooping minds,
and to strengthen us for the painful duty which succeeded.
Thus through the mercy of Him, whose "`compassions fail not,`" a day,
the anticipation of which had been so appalling, was crowned with peace;
and we felt in its close,
that the tribute of praise and thanksgiving was due to that Gracious Being,
who had thus been pleased to manifest His strength in our exceeding weakness.

[.asterism]
'''

[discrete]
=== Appendix D:

[.blurb]
=== The Following Statement of the Result of Daniel Wheeler`'s Agricultural Labours in the Neighbourhood of Petersburg, Was Received Too Late for the Insertion of a Reference to It In the Body of the Work.

The land placed under Daniel Wheeler`'s care in 1818 consisted chiefly
of certain parcels in the immediate vicinity of Petersburg,
the cultivation of which to private enterprize appeared impracticable,
on account of their barrenness, or their marshy nature.
At the time of Daniel Wheeler`'s departure in 1832,
about three thousand English acres were in full cultivation,
on part of which fifteen farms had been established,
varying in extent from thirty-five to one hundred-and-five acres each.
About two thousand seven hundred acres more had been drained,
the cultivation being either left to other hands, or was in progress,
when Daniel Wheeler resigned his appointment.
Besides the improvement thus effected in the neighbourhood of the capital,
the most satisfactory evidence of the utility of the undertaking had been afforded,
by the extensive adoption of various implements and methods of culture,
heretofore unknown in Russia;
and by the consideration which agriculture and rural economy in general had obtained.
The suggestion of letting out land to free tenants,
had not met with all the success that could have been desired.

[.asterism]
'''

[discrete]
=== Appendix E:

[.blurb]
=== Extracts from the Letters of Charles Wheeler, Relative to the South Sea Islands, Addressed To His Family.

South Pacific, Second Month 26th, 1835.--Some fresh marine phenomena were seen today,
among which none were more beautiful than a species of jelly fish,
(probably Pyrosoma Atlantica,) in form resembling a glass tube,
six or seven inches in length with one end closed, and covered with opaque protuberances.
With these the ocean was illuminated at night in a brilliant manner,
and many of those that we took exhibited, on being touched,
a splendid phosphorescent light, sufficiently strong to show the time by a common watch,
when it was placed near a single specimen.
They showed perhaps few signs of animation,
excepting this power of emitting or retaining light at pleasure.
Several other species varying in form and size, are numerous here,
but from their half liquid and perishable substance,
it is almost impossible to preserve them.
Probably most of these several varieties are luminous;
some of them are of a mushroom shape,
(medusa Pelluceus) and have the power to move along through
the water by dilating and retracting their richly fringed head.
Grampuses, sharks, porpoises, dolphins, and some small striped fishes,
called by the sailors, pilot fishes, are common in this part of the Pacific.
The little pilot fishes attract a good deal of notice
from their propensity to accompany the vessel:
they are seen for hundreds of miles,
(perhaps I might say thousands of miles,) frolicking close before the vessel`'s stem,
and occasionally darting aside after some particle that attracts them
for a moment from their favourite position in the van.

On the morning of the 27th, a sail was discovered a-head,
and watched with shipboard interest, as it gradually augmented in size,
till about noon a large whaler "`brought to`" close alongside us.
English colours were displayed on both sides, and Captain +++_______+++,
of the Elizabeth of Sydney, accompanied by the surgeon of the vessel, came on board.
They had been out eight or nine months,
and succeeded in securing 1200 barrels of oil--
which amounts to about one-third of a full cargo.
After obtaining a few fresh provisions for some of their oil, and accepting some tracts,
etc., our visitors returned to their ship,
and in a few hours we lost sight of each other.
The call from these marine sportsmen was quite an incident in our monotonous life;
though from the natural and acquired characters of the parties,
such interviews are not generally productive of much enjoyment.
What a strange life is that of a whaler,
roving the wide ocean for months and years in quest of fish,--banished from
almost every comfort that the humblest landsman may ordinarily possess!
But the prospect of gain reconciles to present privation,
and the promise of hope stimulates to exertion,
and supports them in their dangerous career.
There were five men at the mast heads of this ship, looking out for whales,
as she ranged over the blue swelling expanse.
The space of ocean surveyed by these rangers is incredibly large.
If we estimate the horizon as seen from the mast
head at about thirty six superficial miles,
which are changed every hour and a half,
nearly three hundred square miles will be overlooked in twelve hours;
and there are several hundred ships employed in the South Seas.
Each of these is probably out from two to four years at a time.

Third Month 5th, 1835.--The settlement on Norfolk Island, which is on the south shore,
has a neat and respectable appearance, the houses being built of limestone,
and with some degree of regularity.
The whole population is about one thousand persons,
and of these the greater part are prisoners of the lowest grade.
The boats which came off to our vessel were each
of them manned with six or eight convicts,
and two or three armed soldiers.
Two government vessels were cruising round the island,
waiting an opportunity to land their cargoes.
One of these had brought about seventy prisoners,
who had risen during the passage from Sydney,
and very nearly succeeded in taking the ship.
They would be tried,
and it was the opinion of an officer who was speaking of the circumstance,
that some of them would be executed.

Papeiti Bay, Tahiti, Fifth Month 1st.--There is nothing, perhaps,
in Tahitian habits more striking or pitiable than their aimless,
nerveless mode of spending life.
The community, with the exception of a few foreigners or foreignized natives,
might seem to exist to fish, pluck and eat fruit, bask in the sun, dabble in the water,
or frolic on the sand.
I mean to say that things have this appearance; and that according to our notions,
their habits are deplorably indolent;
and it is difficult to imagine any very different state under their circumstances.
From the size and strength of their frames,
they would appear to be of a stock capable of great exertion;
yet they seem to inherit all the lassitude and inactivity of tropical residents,
and the climate is so extremely hot, that by day every movement is an effort.
Their needs are few and remarkably supplied clothing being an incumbrance,
desired only because associated with ideas of superiority,
and tolerated occasionally in compliment to imported notions;--
and food of the kind most adapted and grateful,
teeming around them, almost independently of their care.
If the faculties were developed, and all effeminating indulgence discarded,
I cannot but think that an adult Tahitian would be a more respectable human
being than he now is even though external circumstances remained the same.

Their outward circumstances, there can be no doubt,
have derived material benefit from the introduction of
Christian teachers and civilized regulations,
so far as they have been introduced: these,
beside preventing certain Pagan enormities among the natives,
constitute a valuable check to the vicious and overbearing conduct of foreigners,
which so lamentably sullies the history of these islands.
Adventurers of all kinds are not now at liberty to take up their abode on shore,
without reference on the part of the government,
to their respectability and motives in coming;
but certain credentials or recommendations, as we are told, are required,
without which no one is encouraged or openly allowed to remain.
This is a very useful restriction, as previously to its adoption,
the most worthless characters have caused much disorder
and misery by settling among the natives and marrying,
to remain only till caprice has dictated the desirableness of a move,
when their families have been deserted without scruple or redress.

Trial by jury, which has been introduced here, is a great blessing,
and one which perhaps Englishmen are better able to appreciate than any others,
from their long experience of its value at home.
The Tahitian jury consists of six men instead of twelve; but the principle,
as I understand it, is precisely the same.

Fifth Month 13th.--After attending a missionary meeting held at Papaoa,
Charles Wheeler remarks: '`We were pleased with the appearance and manners of the chiefs,
and with what we saw of their queen.
Some of the former are fine intelligent men,
and in their general appearance reminded me of North American Indians.
Many speeches were made by the principal chiefs,
who avowed their sentiments with great animation; and throughout the whole affair,
very considerable order, and respectful demeanour were observed by all parties.
The queen is a decidedly intelligent looking woman,
of about four and twenty years of age: and has by no means an ignoble appearance;
though her artless, unassuming manner and simple attire,
accord little with our notions of regal dignity.
Her dress was much less showy than that of many of her inferiors, and far from inelegant.
A long robe of beautifully white muslin flowing loosely round her figure,
a little embroidery and silk about the neck, and a jet black bonnet,
comprehended all that was apparent.

We have since been visited by the king,
(properly speaking he is only the queen`'s husband,) and some of his chiefs,
who breakfasted on board our vessel.
The former appears to be about twenty years of age; and is a mild, intelligent,
unassuming youth.
His countenance is not strictly handsome, but it is truly Tahitian and pleasing;
and his slender form, dark expressive eye,
and gentle manner,--which are completely Asiatic,
--give something feminine to his appearance.
The chiefs who accompanied him were of a much sterner school,
and all of them considerably older than himself.
They behaved with great propriety and good nature, and conversed in a friendly,
sensible manner, expressing their satisfaction with the frank,
unceremonious way in which they had been received.
Before they left us, a telescope was presented to the king,
and a shawl to each of the party.
Nothing like selfishness was shown by the leading personage,
who did not attempt to select the best article for himself;
but taking that which happened to be next him,
he allowed the rest of the company to do the same.
The chiefs playfully vied with each other,
as to who should take charge of their master`'s property, which was left in their hands.
On going away, the king asked the steward for a little bread for the queen.
He had evidently relished this article himself as a rarity,
and therefore I suppose intended her to share.
They were all dressed in the native style, but in foreign articles of good quality.
A fine white shirt, and an ample piece of print wound round the waist,
and reaching to the knees, with a straw hat encircled by a broad ribbon or piece of silk,
seems to be the favourite dress.

16th.--We took a walk for exercise along the high road,
which is a path formed by the soil thrown out of two ditches, affording in dry weather,
a tolerable causeway.
The lack of bridges over the rivulets that cross
it on their way from the hills to the sea,
obliges passengers to wade through the water occasionally, or else adopt a mode,
to which,
on this occasion we were compelled to have recourse,--
that of getting a native to carry them over on his back.
The formation of these roads is an occupation in
which criminals are employed by way of penalty:
so many fathoms of the queen`'s road,
or so many fathoms of sea-wall on the queen`'s island,
are frequently imposed as punishments on male,
and the making of a certain quantity of native cloth or matting, on female delinquents;
and these punishments, if equitably put in force, are well adapted to the people.

It is a singular fact that there are no wild beasts on any of the Pacific islands,
lying distant from the continent of Asia.

Sixth Month 16th.--The remains of idolatry have been so effectually destroyed,
that scarcely a trace of them is to be found.
Perhaps the objects most intimately connected with them are the
natives who persist in rejecting the profession of the gospel,
a numerous class even now.
The government compels all to attend worship,
it is said on pain of forfeiture of landed property;^
footnote:[A respectable resident told us,
that one flagrant instance of this came within his knowledge some time back.
A poor man had been out Ashing, and returned too late for the week day service.
He was tried,
and his land was taken from him by men empowered to enforce this abominable regulation.
It is not enrolled in the Tahltlan code of laws, but is said to be a "`command`" only.
Remove the penalty, and the command might very safely remain unrepealed.]
but this coercion of course does no more than enforce a
ceremony,--if indeed from its unchristian character,
it does not operate rather as a hinderance to the progress of Christianity.
The portion of the community not professing the new religion,
often retain the true native dress,
and are thus conspicuous among their professing countrymen,
who have to a great extent adopted foreign articles of clothing.

Eighth Month 9th.--After a sojourn of three months and a half at Tahiti,
during which considerable opportunity for observation has been afforded,
I shall now offer a few remarks,
that may enable you to estimate more easily its present state.
Without reference to what it may have been,
my observations will apply simply to what it is at the present moment.

I need not describe the geographical position of Tahiti:
it is the largest island in the Georgian and Society cluster;
and considered to be about one hundred miles in circumference.
Together with Kimeo, (a small adjacent island to the westward,
subject to the same government and laws) the population
is estimated at upwards of 10,000 persons;
there is no doubt that the above is a tolerable approximation to the truth, and that,
however it may have been formerly, the islands are now very thinly peopled.
In fact, the interior of Tahiti is not inhabited at all,--the low lands next the sea,
which constitute but a small portion of the whole,
being universally selected by the natives for the place of their abode.
Upon this fertile margin along the coast, their little huts of poles,
mats and thatch are scattered with great irregularity,--
not in well defined clusters or villages,
but singly or otherwise as the course of a stream, or the boundary of a plantation,
may suit best.
The mountainous tracts inland are little frequented,
although from the luxuriance of the vegetation,
I conclude that many parts are capable of cultivation.
Some fruits are produced spontaneously,
and in the remoter valleys these are never gathered by human hands.
The highest ridges, reckoned about 7000 feet above the ocean,
are covered with rich forests, whose verdure never fades; and the deep shade of valleys,
vocal with the thunder of descending waters,
is of course still more prolific of vegetation.
But whatever the inland districts may produce, or may be capable of producing,
the low tract of country stretching along the circumference of the island,
seems to be fully adequate to maintain the present population,
without requiring much culture or care on the part of those who gather the fruits.
The taro, (caladium esculentum,) an excellent farinaceous vegetable,
the yam (Diotcorea alata) and the sweet potatoe
(Convolvulus batatas,) involve some little labour;
but many of the fruits demand only occasional
weeding from the overwhelming growth of guavas,
and protection from the ravages of hogs, with which the place is overrun.
The gigantic cocoa-nut tree bears fruit without intermission the year round,
and furnishes at once the means of shelter, food, and clothing.
The leaf is used for mats, and thatch, and fuel; the bark is converted into cloth;
the timber is valuable for many purposes; the nut shell is the native basin;
the kernel is ground up into a nutritious food; the milk is universally drunk;
and the ripe nut affords abundant oil, both for home use and exportation.
The bread fruit too is highly prized: as a vegetable it is both palatable and wholesome,
and from the bark of the large trees is made the cloth in common use by the Tahitians.
Oranges, lemons, limes, melons, vis+++.+++, (_tpondias dulcis;_)
papaw, (_carica papaya;_) bananas, (_musa sapientum;_)
pine apples and pumpkins abound among the
indigenous and exotic fruits and vegetables of this island.
If the shore is thus teeming with spontaneous provision for the needs of the inhabitants,
the surrounding ocean is not less prolific in affording an endless variety of fish.
Turtles, shell-fish, and many half-animated marine substances used as food,
are found within the reefs.

When I mention the reefs,
I cannot forbear making a few remarks on these extraordinary natural break-waters,
which are of the highest value to the South Sea Islands.
Take Tahiti for instance.
Without this coral breast-work there is not a single harbour in the island; but with it,
the coast, with few exceptions, is sheltered from the ocean,
and circumnavigated with safety in the smallest canoe.
In one or two places the coast is exposed; but excepting these openings,
and a number of narrow passes for boats or ships, a bank of sand and coral,
nearly even with the surface of the water,
varying in distance from the beach from half a mile to perhaps a mile and a half,
extends round the whole island, and defends it from the sea.
On this wonderful barrier, the mighty swell of the Pacific breaks in ceaseless thunder,
from age to age; but within the providential limit the raging deep is chained,
and all is tranquil as a lake: ships of the largest size may enter and ride securely,
and the light canoe of the native has a safe access to every part of the coast.
We have all heard of coral reefs long ago; but till we reached this place,
I may confess I had not the least idea of the characteristic peculiarity,
in the natural shelter furnished by them among the South Sea Islands.

The government of Tahiti is nominally vested in one person, but as might be expected,
the principal chiefs possess a large share of power.
The queen and two of the most influential chiefs entertain a
very friendly feeling towards the missionaries,
and consequently their wishes are consulted, and their interest supported in most cases;
but there is an opposite faction who would doubtless be glad if it were otherwise.
Although Pomare appears to favour the cause of the missionaries,
and by enforcing the laws against the sale of spirits, etc.,
to consult the welfare of her people,
she is by no means a woman on whose principles full dependence can be placed.
At a national assembly held annually,
when nearly the whole population of the island come together to see, hear,
and enjoy themselves,--which took place a week or two back at Papaoa,
she is said to have sanctioned great disorders,
and allowed some of the ancient heathen customs, of a shameful nature, to be indulged in.

In almost all the dealings which we have had with the natives,
one principle of action appears predominant, to obtain all they can:
and this is in precise accordance with the practice of our countrymen among them.
The people of the neighbourhood of the Bay,
labour under the disadvantage of being constantly
exposed to contact with unprincipled foreigners,
who encourage what is wrong, and introduce large quantities of ardent spirits among them,
in spite of the legal prohibition.
This fact alone is enough to account for the prevalence of vice, and sordid venality;
and the formal, unwilling conformity to established restrictive regulations.

But though much of evil may be underneath, and great thoughtlessness may be obvious,
yet there are doubtless alleviating exceptions;
and external tranquillity is for the most part preserved.

It is nearly impossible for a visitor, who cannot even speak the language,
to pronounce with much certainty on a subject of such moment,
as the religious state of the community.
Certainly appearances are unpromising; and however unwilling to adopt such a conclusion,
there is reason to apprehend that Christian principle is a great rarity.
Far, however,
be it from me to depreciate the labours of those who have been
the instruments of the change produced in this island.
So far from considering the beneficial results of their
efforts as unimportant and insignificant,
I regard them as of the highest moment,
and as fully equal to what could in reason have been anticipated.
In my opinion,
if nothing more had been effected by the Tahitian mission than the
translation of the holy Scriptures into the language of the country,
every sacrifice that has been made, would have been abundantly rewarded.
But the translation of the Sacred Writings is not all.
Idol worship, the adoration of nonentities or of supposed divinities,
in the form of images,
with all the frightful train of debasing ceremonies and human sacrifices, are abolished.
Open infanticide, which prevailed to such a dreadful extent, is done away;
and some degree of attention is paid to the improvement of the minds of children.
Many salutary civil restrictions have been introduced,
and a check imposed on the unbridled licentiousness of foreigners.

There is a singular custom prevailing in Tahiti, which I have not yet noticed.
Every child possesses an indefinite number of adopted parents, who, at its birth,
or perhaps even before, promise to cherish and assist it in after life, in case of need.
This practice confers great independence on the children,
who remain with their real parents, only so long as is agreeable to them;
and if maltreated or corrected, they take up their residence with another family,
to desert it hereafter in the same way.
This is a great barrier to the right management of the native children,
who can at once forsake their parents,
should the correction or restraints they impose become irksome to them.

The Tahitian mode of living is certainly very much in the simplicity,
or perhaps more properly in the rudeness, of nature.
Their houses afford a shelter from the rain, and a receptacle for their little property;
which consists of a few imported articles of clothing for special occasions, some food,
nets, sleeping mats, and a display of firelocks: comforts, conveniences, and luxuries,
(according to our ideas,) are for the most part unknown.
One apartment usually accommodates the whole household,
which generally consists of individuals of all ages, more or less related to each other,
and herded together in considerable numbers.
When at home,
the usual employment of the men appears to be the preparation of food or oil,
gardening and making nets, and that of the women the manufacture of native cloth,
cooking and sewing;
but both sexes are very frequently found unemployed,--perhaps smoking,
or playing with a ball and string.
The men ordinarily wear very little clothing:
the women a loose piece of print or calico thrown round the waist, leaving,
except in the presence of foreigners,
or when '`dressed out,`' the upper part of the figure nearly or entirely exposed.
The young children frequently go quite naked.
A true native hut contains neither table,
chair nor bed,--the reed-covered soil which forms a floor, serving the purposes of all.
The food is spread on leaves, and the people sit round on their heels,
squatted on the ground; and when recumbent, they lie upon mats,
covered with folds of their native bark cloth.
This cloth is made from the bark of several
trees,--a large proportion of what is used here,
from that of the bread fruit tree.
This is beaten into thin sheets, which are rendered tenacious by the gum they contain,
when properly dried in the sun.
When fit for use, this ingenious substitute for woven goods resembles coarse paper:
it is, however, less easily torn, and generally somewhat thinner.
It forms but a harsh, uncomfortable drapery, and will not bear properly washing,
being injured by moisture, without much friction;
but habit and necessity render it tolerable, and it is very readily made.
When dressed for chapel, the men generally wear a foreign shirt,
and a piece of print or blue cotton wrapped round the waist:
the women a similar girdle of some light material, and either a kind of loose gown,
or a shawl, of calico, thrown over the shoulders,
with a bonnet generally made of pressed paper, in imitation of straw,
and profusely decorated with broad bright coloured ribbon.
The last mentioned article is in very extensive use,
and is sold to great advantage by almost every body here.
I was one day trying to purchase a piece of ornamented native cloth,
and offered an equal length of English print for it;
but the owner refused this remuneration, demanding a similar length of ribbon instead.
The gay colours worn by the whites are, of course,
zealously imitated by the poor natives,
whose clothing seems to be adopted rather from vanity, or deference to foreign customs,
than from necessity or a sense of decorum.

Taloo Harbour, Island of Eimeo, Ninth Month 12th, 1835.--This is a most romantic spot,
surrounded by almost perpendicular hills, towering nearly four thousand feet,
with a broken fantastic outline.
As in Tahiti, there is a margin of lowland next the water,
which produces abundant crops of fruit and vegetables;
but the proportion of this fertile soil is small, and as a whole, probably,
this is the less productive island of the two.
Its scenery is wilder and more diversified,
and the ridges are much more angular and rugged than those of Tahiti, some of them,
where huge black rocks and foliage blend in the obscurity of distance,
resembling the broken fragments of a stupendous ruin.
Many parts are nearly perpendicular for hundreds of feet,
and of course quite inaccessible.
The summit of a mountain that skirts one side of Taloo Harbour,
extending for a considerable distance at an elevation of three thousand feet,
is yet so narrow, we are told, in some places, that a man cannot walk along it,
but is obliged to push himself forward in a sitting posture,
grasping the mountain with his legs.

On the 23rd, arrangements were made for visiting the opposite side of the island,
where a number of natives, and one English family reside.
The direction of the trade-wind rendered the longest route most eligible,
and we pursued our course among coral rocks within the reefs.
In a few hours we arrived opposite a famous entrance through the reef,
formerly held sacred on account of a large marai, called Orua,
situated on the beach near it.
Here we landed and explored the marai, with its ruined piles of rock,
its consecrated enclosures, praying-stones, and venerable grove of Aitos and Tamanus.^
footnote:[The Tumanu (calophyllitm Inophyllum,) was
formerly held sacred in the South Sea Islands.
It is a noble tree,--in general appearance something resembling the oak.]
The whole neighbourhood is overgrown with trees and climbers,
and the ruins are so completely dilapidated,
that it is difficult to appreciate the original design.
Many smaller heaps of stone, and the remains of pavements, steps,
and praying-stones are seen near the principal pile,--
the whole forming an enduring relic of superstition,
and a proof of the laborious zeal of idolaters.
After surveying this gloomy grove, once associated with scenes of horror and death,
we continued an intricate passage through innumerable beds of coral,
till we reached Afareaitu, and were cordially welcomed by the resident English family.

Ninth Month 27th,
1838.--We heard some days since that more ardent spirits have
just been brought to Tahiti by a schooner from Valparaiso,
which is now trading in them.
When we left Tahiti,
another American vessel was there selling all she could of this destructive poison;
in fact,
the chief articles of barter for cocoa-nut oil and arrow-root that she seemed to have,
were fire-arms and brandy, and these she was retailing round the coast.
Her supercargo told me himself, that he had sold all the brandy he could get rid of,
and between one and two hundred muskets.
He is quite a youth, but well enough suited for the task he has undertaken,
being a profligate, thoughtless fellow, initiated into the trade,
which he avows his intention to continue.
What could be more completely barbarous than this traffic,
carried on with uncivilized nations at the present day;
and that too by professing Christians!

During the afternoon of Tenth Month 15th, we rambled for exercise on the public road,
along the coast, and saw a curious salt-water lake,
situated about two miles to the northward of the harbour.
It is a magnificent sheet of water, encircled by mountains and tropical forests;
and probably would have been still more gratifying to
eyes less familiar with the water than ours.
There is, however,
an essential distinction between the prospects to which we are accustomed,
and inland lake scenery.
The characteristic of the former is ceaseless
fluctuation,--that of the latter unbroken tranquillity.

Among the enclosures of the natives here,
there is greater indication of industry than we remarked in Tahiti,
and many of the houses are built in the civilized manner, with windows, plastered walls,
etc.
Nevertheless the dwellings we have seen have by no means a comfortable aspect,
and the general effect of the native settlements is not particularly pleasing.
Unfurnished, dirty huts, surrounded with lumber, the remains of food, etc.,
naked children, and all but naked parents, working, or rolling about, smoking or playing,
sleeping or waking, as the case may be;
with groups of half starved hogs and dogs occupying every corner in the neighbourhood,
do not constitute the most delightful objects,
though viewed in the far-famed South Sea Islands.

Our afternoon ramble on the 17th, led to the site of William Ellis`'s residence.
The vicinity is completely overgrown with gnavas,
and the most authentic traces of its former occupant
are discoverable in some fine fruit-trees,
planted in the immediate neighbourhood of the house.
We afterwards took tea at the mission-house,
and were shown the press which is occasionally employed in printing native lessons, laws,
etc.

On the afternoon of the 24th,
we accompanied one of the missionaries on an excursion up the
salt-water lake mentioned before. After walking about two miles,
we embarked in a canoe,
and were pushed along the shore by a man with a long
pole;--a method adopted where the water is shallow,
as the most expeditious mode of propelling their light barks.
In about an hour we reached the farther end of the lagoon,
distant perhaps five miles from the place of embarkation.
The banks as we went along appeared thickly wooded and very thinly inhabited,
exhibiting little rariety, beside the occasional remains of marais,
of which there are a great number.
Our native conductor pointed out the particular
pile of stones appropriated to his family,
on which he had himself offered gifts to the supposed gods of Tahiti.
He mentioned having been present on one occasion when a human
victim was taken near this lake:--he was a boy at the time,
and was rambling along the bank, when a party of men, led by a chief,
approached the spot where he was,
and where also the object of their pursuit happened to be.
The chief, when he discovered his victim, bade him climb a cocoa-nut tree,
which he of course instantly did.
He ordered him to pluck some nuts for them, and when this was done, to break off a leaf,
and come down.
The leaf was to form a basket for his own body to be carried in.
On coming down he was quickly dispatched.
Our informant ran away in great fear, while the murderers laughed at his terror,
and exulted in their easy capture.

Fare Harbour.
Huahiru.--In personal appearance,
there is no perceptible difference between the
natives of this island and those of Tahiti;
and from what we have seen, their progress in civil, social,
and religious improvement is precisely similar.
I think more pains have been bestowed on their instruction; but,
as far as our observation has extended,
they occupy much the same position as their
Georgian neighbours in the scale of civilization,
mental development and morality.
On the whole,
I should suppose a larger proportion of the population is more
or less acquainted with the rudiments of reading and writing;
though many are ignorant of these,
and it is not impossible that less constant interaction with the
shipping may have prevented some of that licentious degradation,
which peculiarly characterizes the vicinity of sea-ports.
Only one ship has been here during our stay,
but in her case considerable irregularities were committed.
The use of spirits is just now generally laid aside,
and doubtless this salutary regulation will tend to prevent many evils.

Raiatea.--The natural scenery of Raiatea resembles what
I have already described in the other islands,
but is for the most part less picturesque than any other we have yet seen.
It is a much larger island than Huahine,
and is supposed to contain fourteen or fifteen hundred people; the whole of whom belong,
nominally, to the settlement of Uturoa,
though they are of course found scattered round the coast,
as most convenient to themselves.
Tahaa, a smaller island, containing a population of four or five hundred souls,
subject to the same government, is situated a few miles to the northward,
and is included within the same reef as Raiatea.
This reef is precisely similar to what we have before seen,
and extends round the two islands at a considerable distance,
affording several excellent harbours,
to which commodious channels furnish an easy access.
The one in which we are lying is entered from the eastward,
through a fine passage between two small islands, and is a spacious basin,
capable of containing a large fleet,
with a passage at the opposite end to leeward of the island.
Nothing could well be more convenient;
and although from the circumstance that its shelter, the reef, is as usual low and bare,
good tackle is required in the anchorage;
yet this stupendous barrier affords a most complete defence from the ocean.
Coral and shells are plentiful, but the latter rather dear.
Provisions seem to be rather lower than at Tahiti,
where more competition diminishes the value of foreign articles of barter.
Even there, things are very cheap for the most part.
The common price for a good sized hog is six or eight yards of print,
or from three to four dollars.
Horned cattle are plentiful in all the islands we have yet seen,
and are principally the property of the missionaries.
When several ships can agree to take an ox among them, beef is sold at about 2d. per lb.
Broad print, or cotton dyed a blue colour, is a favourite article of barter,
and is always sold by the fathom,
this length being convenient for the garment worn round the waist.
A fathom is reckoned to be worth nearly a dollar,--about four times its value in England.
Gaudy-coloured ribbons are about the same price.
A musket costing at home perhaps 12s. is sold at Tahiti for seven or eight dollars.

On the afternoon of Eleventh Month 2nd,
we walked out for exercise along the settlement of Uturoa,
which extends some distance by the seaside,
and called to see an old chief who is said to have been
the principal instigator of the last war with Bolabola;
to which perhaps more than to any other obvious reason,
the present deteriorated condition of this people and the
miserable falling away in Bolabola must be attributed.
Beside the numerous evils inevitably incident to a
nation engaged in hostilities with its neighbours,
it is from this fatal period that both islands date the general introduction of spirits;
which has proved no less detrimental to the community than fighting.
Here, happily, the law has been passed for their prohibition;
but in the other island their ravages still continue.
We saw four pieces of cannon taken from the Bolabolans,
which were used in the late contest;
originally brought by a trading vessel from New Zealand,
and sold to the poor natives at the rate of eighty hogs each.
They are said to have belonged to the unfortunate Boyd,
and to have been raised from her wreck by the New Zealanders.

On the 3rd of Eleventh Month,
we started in company with C. Barff and a little boy on an
excursion to the famous marai of Tabutabu Atea,--situated
// lint-disable invalid-characters
the district of Apóa. The wind being against us all the way,
it was a hard pull of about twelve miles, which occupied nearly three hours,
and unfortunately for us it rained at intervals most of the time.
The object of our curiosity is situated on a projecting piece of low land,
running from the base of a considerable hill to the beach,
and retains abundant features to identify it with the late system of horrors.
An enormous banyan tree grows quite near it,
and which could not fail to attract our notice and admiration.
Like all other specimens of this extraordinary tree,
it consists of a column of matted fibrous trunks, intersecting, supporting,
or distorting each other, surmounted by a fine head of foliage;
from which fall those slender, cord-like tendrils which connect roots and branches,
and thus furnish the means of continual increase in size.
Exclusive of these junior supporters,
what may be called the stem of this enormous and complicated fabric,
measured by paces forty-six yards in circumference;
and I should think at least twenty men might
conceal themselves in its truly gigantic mass.
Between this natural curiosity and the marai,
under the shade of a grove is seen the space of ground appropriated to the dances,
once so much in vogue here, in celebration of their abominable orgies.

Bolabola, Eleventh Month 11th.--In the afternoon we walked through the settlement,
and saw several sick and infirm persons.
My father distributed several pairs of spectacles where they seemed to be most needed,
among the more serious natives who could read.
One of these, a cripple, we found in his hut with his Bible before him,
and two muskets hanging over his head: he is a constant attender of the school,
acting as teacher as well as he is able.
On our walks here we have generally been attended by a group of children,
who frolic round the strangers, and afford much amusement by their sprightliness,
wildness and curiosity.
They are really fine, intelligent little creatures.
Some of them look healthy, but too many bear marks of the prevailing disorders,
which have been deplorably neglected among these islanders.
A more invaluable present could scarcely be sent to
them than a good supply of drugs,--particularly calomel,
salts, sulphur, ipecacuanha, opium and rhubarb.
It is true, in many places there is no one to administer them,
and in others they would not be administered to the greatest advantage,
for lack of professional knowledge; but if sent to the care of some of the missionaries,
they would confer a great blessing.
C+++.+++ B. does much in relieving the poor creatures around him,
by his own exertions in this way.

South Pacific, Eleventh Month 19th,
1836.--However deficient my accounts of the islands we have just left may appear,
it would be no difficult matter to add considerably to
the interest felt in their perusal,
had my object been merely to draw a pleasing picture.
I have noticed the causes which operate in producing the very false impression
which certainly is produced by reading the reports of some former visitors.
There are many circumstances connected with the South Sea Islands,
peculiarly fascinating and poetical,
and these have been made the most of by some of their delineators.
My wish, that a simple statement should produce a simple and correct impression,
has induced me to confine my remarks pretty much to matters of plain fact,
more or less intimately connected with our own progress or the object of the voyage.

Of Tahiti, I have already given you some particulars, also of Eimeo.
The government, laws, and people of the other Georgian Isles are essentially the same,
and the state of society not materially different.
The same compulsory system which obtains in Tahiti,
ensures for the present in Eimeo an external attention to the services of the chapel;
but the very existence of this detestable regulation indicates unsoundness.
The fact that the poor native is subjected to a
penalty if he absents himself from the chapel,
and the sight of a man with a stick ransacking the villages for worshippers,
before the hour of service,--a spectacle we have
witnessed,--are so utterly abhorrent to our notions,
that I cannot revert to the subject without feelings of regret and disgust.
The general appearance of the country, and of the inhabitants of Huahine,
is similar to Tahiti, and the popular habits seem nearly the same.
The soil is exceedingly prolific, demanding but little labour.
Hogs and domestic fowls are pretty numerous,
but horned cattle are only found in the possession of the missionary and a few others;
and indeed it is undesirable that they should increase much,
as they certainly are a great nuisance among the native plantations.
In Tahiti and Eimeo they abound and run wild,
preying upon the fruits and damaging the fences in parts that cannot be easily watched.

Both Raiatea and Tahaa are fine fertile islands,
capable of supporting ten times their present population;
but there is no prospect of increase under present circumstances;
and if the sweeping bane of ardent spirits is re-admitted,
the numbers will rapidly decline.
Even in Huahine,
where things are undoubtedly better managed and the people more instructed,
the number of births and deaths are just about equal.
C+++.+++ B. told us that he hoped during the present year there
would be a small preponderance in favour of the former.
The more abandoned portion of the community scarcely ever have families,
and many of the children that are born are miserably diseased,
so that a little aggravation of circumstances, such as a return to general intemperance,
would make existing causes adequate for a speedy extermination.
I trust, however, these islanders may be preserved,
after having survived the bloody era of human immolation, infanticide,
and other pagan atrocities,--from falling victims to
vices introduced and kept up by '`Christians.`'

But of all the islands in the Society group,
Bolabola exhibits at the present time the most melancholy spectacle.
It is indeed a lovely island, and lacks only a moral and industrious population,
and a consistent united government, to ensure its national prosperity.
But, exhausted by the late struggle with Raiatea, the chiefs divided among themselves,
all moral restraints disregarded by one faction,
and every excess openly sanctioned;--the other party,
who still adhere nominally to the cause of the missionaries,
left to support their own principles,--there is little
of a pleasing nature to be said respecting it.
The more sober part of the people seemed tractable enough;
but it is scarcely to be expected that they will maintain their ground,
associated with and related as they are, to the lawless faction.
At the time of our visit the fruit season had not arrived,
and consequently the means of distillation were not within their power;
but a few weeks would furnish them with an abundant harvest of bread-fruit, etc.,
and it was greatly feared, that last year`'s excesses would again be indulged in,
and a famine produced by the consumption of
every article of food in the making of spirits.

The people here have much less of foreign clothing than the natives
of the other islands,--possessing fewer opportunities of obtaining it,
and having wasted their means in drinking.
This circumstance alone prevents many from attending chapel, when a missionary is here.
Whatever their motive might be,
the better sort appeared extremely eager to supply themselves with clothing,
and would part with almost any thing they possessed, (which is not much,
poor creatures!) to obtain a bit of print or calico.

The settlement is composed of wicker huts,
with the exception of one or two dilapidated houses, the chapel and the mission-house.
The island is extremely fertile, producing vast quantities of bread-fruit;
but it is by no means well supplied with water,
and on this account can never become a general resort for shipping,
although it possesses a most magnificent harbour.
We saw a spring or two, which furnish a constant supply;
but the water usually found among the natives is nearly unfit for use,
except during the rainy season.

As a missionary station, it is at present abandoned;
but we saw nothing about the chiefs and people of the
more respectable party particularly discouraging.
On the contrary, I feel no doubt that a large portion of the inhabitants,
whose interest in every point of view it would certainly be to protect such a resident,
are capable of appreciating the value of a conscientious missionary.
The lawless faction are at present incorrigible;
but the removal of their leader would no doubt terminate their career,
and this is an event by no means improbable,
if he persist in his present intemperate habits.
One of his sons fell a victim to intemperance only a few weeks back.

Sandwich Islet, Oahu.--On the 7th of First Month, 1836,
we visited the mission establishment and looked through the printing, binding,
composing-rooms, etc.
Two presses are kept at work: at present printing the New Testament, a geography,
the Hawaii newspaper,--(Ke Kumu Hawaii,)--and a music-book for a volume of hymns.
The newspaper last year was twice its present size, and sold for twice its present price,
which is half a dollar annually: it was published every fortnight,
and 3500 copies were circulated.
Probably its circulation will be much increased this season.
It is a small but neat paper,
containing information on subjects calculated to interest the people,
such as natural history, and particular occurrences in the islands;
and the demand indicates a relish on the part of the
natives for such a source of instruction and amusement.
We were pleased with the machinery on the establishment, which is in good repair,
and is worked entirely by natives, under the direction of a foreign printer and binder.

There are at present residing in Honolulu, belonging to the American Board of Missions,
two '`ordained`' ministers, a doctor, a book-binder, a printer,
and a '`secular agent.`' A missionary from one of the
other islands is here just now with his family.
The above are all married men, although one or two of their number are quite young;
and they all reside in the same neighbourhood,
forming quite a community among themselves.

The end of the week is almost universally adopted in
Oahu as a time for riding on horseback;
and accordingly the roads and commons swarm with the gentry of the neighbourhood,
who vie with each other in risking their necks.
Foreigners, native nobility, and others, are seen galloping about in all directions,
to the discomfiture, or at least the '`bodily fear`' of sober pedestrians.
The Sandwich Island women are really very adroit on horseback;
but the posture in which these amazons choose to exhibit,
violates every feeling of refinement.

22nd.--Some efforts have lately been making on the part of both natives and foreigners,
in the way of petitioning the government here for the suppression of spirit-selling,
which is increased to a shocking extent.
The king, unhappily, is fond of drinking himself,
and moreover derives considerable emolument from
the licenses to vend this pernicious article;
so that surrounded as he is by ill-advisers,
there is little hope that any alteration will take place at present.
Many of the foreign residents defend the sale and use of spirits;
which is one principal source of profit with some of them.
The village of Honolulu is supposed to contain about two hundred foreigners,
and we can only hear of two houses among those who are traders,
not more or less concerned in the sale of spirits.
There are at present about fifteen grog shops,
where all kinds of distilled liquors are sold at a very low rate.
I have not yet seen a single native intoxicated,
and really believe the drinking is almost exclusively
confined to the foreigners and half-castes.

One of the white inhabitants was killed in a drunken quarrel just before our arrival;
and a captain narrowly escaped the same fate a few days since,
having the temporal artery cut in a fray on shore.

Among the sailors, the evil of drinking is greatly upheld by masters and owners of ships,
whose practice has a tendency to perpetuate the grievance which they pretend to deplore.
How absurd on board vessels lying at anchor, in a hot climate,
where the men are in a state of almost continual excitement in
consequence of what they get when on shore,
to give out regularly to each man, and even in some cases to each boy,
an allowance of rum every day!

On the 2nd of Second Month,
I accompanied Captain C. and his sister on an excursion inland,
to see the famous mountain pass of Oahu. It is situated
about seven or eight miles up a fine valley,
which stretches across the centre of the island, behind the village of Honolulu.
After crossing the plain of lava which lies along the coast,
our route was along a winding path, through brooks and foliage and steep ravines;
which by a very gradual ascent led us eventually to the verge of the precipice.
Here the most imposing spectacle is presented.
Before us--from the bare torrent-worn rocks which surmount this giant
barrier--was spread a wide undulated tract of country,
bounded by the then tranquil ocean, and varied by woods, meadows, and sheets of water,
all distinctly exhibited at one view beneath our feet.
The point on which we stood is the verge of a precipice,
perhaps eight hundred or a thousand feet high;
which is ascended from the eastward by a winding staircase track,
leading from rock to rock, in some places nearly perpendicular.
From this track the frightful depth is in many parts
concealed by bushes and projecting points of the cliff;
a circumstance which makes the danger of ascent
and descent much less than it could otherwise be:
but from the dizzy summit, the eye fathoms at a glance the tremendous void below.
On the left was seen the termination of a cliff,
which towers like a pillar from the vale beneath high into the air above our heads,
with a boldness and sublimity altogether indescribable: on the right,
a bank of rich foliage rose from the plain to the very summit of the mountain,
with a richness and grandeur equally beyond the
reach of words,--though less striking to the eye.
The huts of the natives scattered over the country below,
were seen like specks on the green surface;
and the white dwelling of the missionary at the Koloa
station was just discoverable on the distant shore.
Behind us lay the fine romantic slope, by which we had reached this truly imposing pass,
skirted by a chain of luxuriant hills on each side,
and covered with an exuberance of vegetation peculiar to the tropics:--the
harbour and its floating occupants and the dim expanse of ocean beyond it,
terminating the prospect in the west.
After collecting some curious plants and land-shells,
and feasting our eyes on the magnificent scenery of the place,
we commenced a return towards the inhabited world,
and arrived safe in Honolulu soon after sunset.

These islanders, like all the other uncivilized tribes whom we have seen,
are fond of tobacco, and carry the practice of smoking it to a singular extreme.
They inhale the fumes into the lungs, and quickly feel their stupifying effects.
In some of the islands, the use of it is made illegal;
and we have heard of an instance in which a strange expedient was resorted to,
in order to supply the place of this narcotic;--this was to press two
or three of the arteries in the neck till dizziness was produced,
and the individual fell down insensible, recovering after some time,
as from a fit of intoxication.
Thus stupor and forgetfulness are proved to constitute great
part of the gratification supposed to be afforded by smoking.
The missionaries are very often censured for trying to suppress the use of tobacco;
but the Sandwich islanders carry smoking to such an extent,
that their influence seems very properly directed to abolish it.

17th.--The harbour has been a good deal disturbed by
the yells of a band of north-west-coast Indians,
who are quartered on board a hulk at anchor near us.
These poor fellows come here to receive payment for their furs,
and for services which the ships obtain from them on the coast;
and they being fond of rum, and rum being very plentiful among their employers,
the result might be easily predicted.
Howling, dancing, and drumming on a piece of wood form their amusements,
to which quarrelling and fighting may be added.
One of them was drowned a short time since close to our vessel,
by falling into the water by night in a state of intoxication.

These Indians differ widely in character and appearance from the South Sea Islanders.
They are wary, intelligent people, rather Jewish in their expression of countenance,
and not so handsome as the Polynesians.
Their heads are remarkably large,--their faces broad and eyes deep,--hair long,
straight and black, and complexion swarthy.
Their language is particularly disagreeable to the ear:
few of their words are properly articulated;
but the whole business of enunciation is referred to the throat,
which seems half blocked up with spasms and contortions to produce the requisite sounds.
They have frequently been on board to sell shells, and appear very friendly and harmless,
though by no means so childish and simple as Tahitians.
Fire arms, rum, tobacco,
and clothing--for use rather than ornament,--are what they most crave.

Fourth Month 6th, 1836.--I was invited to join in another equestrian excursion,
with my former kind companions;
and a remarkably fine day proved highly propitious to
our enjoyment,--although previous rains,
which rendered the steeps less accessible,
prevented our ascending the mountains so far as had been proposed.
We reached sufficient elevation, however, to obtain a magnificent view of the coast,
village, harbour, and ocean, and to be surrounded by rich hills and dales,
which blend with indescribable loveliness.
The valleys--literally huge ravines between the heights,
which conduct the fertilizing streams to the shore, are but thinly inhabited;
but they teem with exuberant vegetation.
The mountains are very finely wooded,
and the more open parts of the hills are studded over with cattle.
As we were situated when at the highest point of our journey,
the deep vales spread beneath us with an enchanting variety;
and summit rising over summit into the clouds,
marked the multitude of hills which stretch towards the coast in wild fantastic ranges.
Punch-bowl Hill, a brown volcanic mound of a circular form,
probably about five hundred feet high,
looked quite diminutive from our superior elevation,
and its fortified top was completely exposed beneath us; though from the harbour,
this hill appears large.
You can scarcely form an idea of the exhilarating feeling,
which the mind experiences on these noble heights in a tropical climate.
Here all is wild, and bold, and majestic; the air is pure and cool,
and the solitude is unbroken by a sound less romantic than the lowing of herds,
the murmur of descending waters,
or the simple notes of songsters dwelling unseen in the wooded recesses.
The eye,--accustomed below to parched,
naked plains,--here luxuriates on the smooth slopes, the deep shades,
or the towering forest-clothed peaks and ridges,
and the lungs inhale new life and vigour in the free,
bracing atmosphere of a more genial clime.
If to the smiles of surrounding nature are
super-added the rare delights of congenial society,
the wanderer and the exile might almost be tempted to forget
for a moment that the wide world separates him from his home.
But such an illusion must be of short duration:
a descent soon restores the less pleasing reality of
common life in the desert of a strange land.

Island of Tanai, Sandwich Group,--Koloa Station, Sixth Month 20th,
1836.--Being kindly furnished with a steed and conductor,
I undertook an excursion along the sea shore to see a curious cavern in the rock,
through which the surf rushes to a considerable distance underground,
and hurls a column of foam with tremendous force into the air,
like a magnificent fountain.
There are several such cavities in the lava, on the shore of this island;
the largest we saw lies a considerable distance from the anchorage at Koloa,
to the westward.
The coast is composed of rude masses of lava,
extending in every rugged form along the margin of the sea,
and occasionally rising into huge perpendicular cliffs.
The phenomenon in question,
is merely caused by a passage which leads from beneath the surf,
when it rolls up the strand, and opens like a well, some little distance inland,
sufficiently removed from the breakers to give the fountain an isolated appearance.
When a heavy swell breaks on the shore,
the air in this unexplored cavern is driven with
tremendous noise through its sounding caves,
and from one or more mouths is projected a momentary blast of white foam,
to the height probably of twenty or thirty feet.
As the wave retires, all is still on the black broken rocks;
the mouth of the cave looks like a natural well, half-filled with masses of stone,
which conceal its depth; but as the rolling billow thunders towards the coast,
a deafening noise is heard underneath,
which increases in violence till it ends in a fierce loud hiss,
as steam discharged from the valve of a steam-engine; and in a moment afterwards,
a cloud of water and foam is driven high into the air.

The geographical position of the Sandwich Islands, in a commercial point of view,
is a valuable one;--in the North Pacific,
they form an intermediate link between two distant continents,
and thus facilitate an interaction which is now considerable,
and will probably become much more so hereafter.
As a resort of the whalers, and of traders to the north-west coast of America,
they are likewise important:
at Honolulu alone about one hundred and thirty ships touched during last year,
and at other places the number was very considerable.

A constant trade breeze,
which during great part of the year sweeps across the group from the eastward,
renders the atmosphere exceedingly salubrious:
probably between the tropics no situation is more healthy.
To an English constitution the climate is undoubtedly relaxing, and would probably,
apart from all causes which contribute to increase its
effect but which are not inseparable from it,
exhaust the animal system more speedily than a colder clime.
The human constitution, like the vine,
seems periodically to require a season of comparative repose,
which these seats of perennial summer do not furnish;
early maturity and premature decline characterize the residents in these sunny,
stormless regions.
The winter here, a cooler, more irregular, showery season than the summer,
is called '`the rainy season,`' but this epithet, as generally understood,
is not quite appropriate; the continued drenching rains that mark that period in Tahiti,
we certainly did not see.
The rain which fell during our stay,
(and the season was considered rather unusually wet,) did not I believe
exceed what generally falls in England during the corresponding season.

Eight islands constitute this cluster,
to which might be added several small ones lying near the others,
which are not usually enumerated; the present population of the group,
as determined by a census taken by the missionaries in the present year,
is 110,000. In 1826, it was said to be about 155,000,
so that if these numbers are correct, and the past is a specimen of the future,
it will not require many more years to depopulate the islands altogether.

In the instance before us, the injury is evidently to be referred,
not to a succession of open hostilities, but to a complication of causes,
in increasing operation.
Among these, disease and immoral habits are no doubt the principal;
but there are others of no trifling character.
Association with foreigners has increased the needs of the chiefs,
without furnishing any corresponding means of supplying them, and in consequence of this,
the poor people are more heavily burdened than formerly.
They are continually obliged to labour without receiving any remuneration,
and to furnish an indefinite amount of property in the form of taxes or tribute,
in order to retain an inch of ground;
and this last evil is increased by every addition to the size of their families.
A large number of the more enterprizing natives now avoid, at least for a time,
the impositions of their chiefs, by going as sailors in the whale ships; emigration too,
is said to be eagerly sought by the poor, dissatisfied people,
who are anxious to try a change, in the hope of amending their condition.

Many of the above evils arise, as you will perceive,
out of the moral degradation of the people, and I cannot for a moment doubt,
that could they be really formed into a temperate Christian community,
there would be no danger whatever of their national extinction,
so long as they retain their independence.
May the purifying influence of the gospel of our Lord,
which has already made some progress among them,
correct the disordered state of society which now prevails,
and avert the fate which threatens this people!

Of the Sandwich Islanders, as a race, I think highly.
They are intelligent, grave, inquiring, and peculiarly inoffensive and docile.
No one who has seen much of them, can, without great injustice,
refuse to admit that the minds of these natives
are quite capable of improvement and elevation:
there are difficulties connected with their instruction,
but the ground-work of natural capability is indisputably there.
Less volatile and playful than Tahitians, their gravity might in some cases,
be mistaken for moroseness;
but no people could be more conciliating and ready to oblige than they generally are.
Their curiosity is excited by everything new, which is brought under their notice,
and to prove their observation,
we need only look at the improvements and conveniences
which they have adopted or ingeniously imitated.
In connection with their docility, they sometimes appear childish;
but this apparent imbecility arises from their simplicity,
and a consciousness of their ignorance and circumstantial
inferiority to many whom they meet from the civilized world.
In some of their actions, however, where no such considerations weigh,--as for instance,
when they have to deal with lawless and abandoned foreigners,
they prove that they neither fear nor venerate a white skin, merely as such.

+++[+++Speaking of the dress of the islanders, C. W. remarks,]
the garland worn on the head by chief women, is a costly decoration,
it is said to be worth fifty or sixty dollars.
It is formed of yellow feathers,
which one species of mountain bird furnishes in small numbers;
it is said that each bird does not supply more than two or three small feathers;
these are arranged like the swan`'s down neck-bands of Europe,
and are glossy and silky in the extreme.
Lord Byron procured two of these costly garlands for some ladies of rank in England,
a few years since.
In the remoter parts of the islands, the females still retain their old garments,
which happily are very much out of use among the more civilized.
A piece of native cloth wound round the waist, and a loose, shapeless frock,
either of print or native cloth made in imitation of print,
extends from the neck to the ankles, with ample sleeves,
and sometimes with a frill or collar.
This dress almost entirely conceals the figure,
and is a very rational and becoming garment, in which they look well.
Their hair, which is usually strong and black, is allowed to grow long,
and either tied in a knot on the top of the head,
or regularly parted in front and set off with combs, curls, etc.
Shoes and stockings are scarcely ever seen.
Of course there are many of both sexes in the principal sea-ports,
who approximate very considerably towards the European style of dress,
and exhibit a great variety of costume; but these are exceptions to the general rule.

The Sandwich Island female countenance is often coarse and unfeminine,
--expressive,--but not of those qualities which we most admire:
in many, intelligence is conspicuous, and they have fine keen eyes.
Their movements are particularly awkward and ungraceful.
Like the Tahitians both sexes are accustomed to sit cross legged, or still more commonly,
squatted on their heels.

The appearance of the native dwellings, gardens, etc.,
is indicative of much greater industry than any thing seen at Tahiti;
but as to civilization or comfort, I will say but little.
The huts strikingly resemble in appearance old hay stacks,
having sides as well as roof of thatch: they are, however, well adapted to the climate,
being at once a protection from the heat and the cold.
One of the king`'s houses, and the native chapels which we have seen,
are composed of this very homely material.
The dwellings of the chiefs are more or less modelled upon those of the white residents.
Some of them are really quite respectably furnished,
and capable of containing the rare elements of comfort and convenience.
The American missionaries,
excepting in some places where stations have been but recently occupied,
are uniformly provided with comfortable houses, built,
as nearly as circumstances will admit, in home style and often of home materials;
neat stone, or coral, or mud-brick walled cottages, shingled or roofed with zinc,
plastered, and floored and ceiled; the woodwork in some cases imported from America,
whereby the natives are furnished with models, and they have already,
in several instances, availed themselves of the advantage.

Idolatry, so far as the adoration of images is concerned,
may be said to be nationally abolished in the Sandwich Islands.
This fact does not imply that all have even nominally embraced the Christian religion;
but a small part of the whole population belong to the church by any right of membership.
At one station, not very long ago established,
in a district where hundreds usually attend the services in the chapel, we were informed,
I think, that the number of church members did not exceed fifteen or sixteen.
The missionaries find it needful to be constantly on
their guard against hypocritical profession.

The influence of irreligious foreigners,
who are scattered over nearly all the islands of the Pacific,
constitutes probably the greatest external hinderance
to the moral improvement of the natives,
which the missionaries have to encounter.
They may be styled the missionaries of Satan,
diligently engaged in extending his kingdom,
and counteracting with the efficiency of well-instructed agents,
every attempt to diminish his power;--and unhappily these labourers are not few.
The Sandwich Island government has adopted certain regulations,
which discountenance the settlement of seamen, who might choose to leave their vessels;
but in one way or other many contrive to take up their abode.
Men arrested and confined in the fort at Honolulu are
bought out perhaps by a dram-shop keeper,
who can easily pay himself afterwards out of the wages of his purchase.
Dollars will effect almost any thing with the chiefs:
most of their sentences passed on criminals can be commuted for money, and that legally.

I am not aware of any public measures which tend to
discourage foreign traders from settling in the islands.
They cannot buy land it is true, but they may rent it for a stated term of years.
The steady determination of the government, not to sell an inch of ground,
is a measure of excellent policy;
and I hope neither king nor chiefs will ever be persuaded or frightened out of it.
Whenever they sell the soil, they give away their strength,
and this is already insufficient to govern their unruly white subjects.

The present is a critical time in the history of these islands,
and many of the more reflective and sagacious natives are fully sensible of the fact.
While the aboriginal inhabitants are rapidly on the decline in point of number,
the foreigners are increasing,
and acquiring an ascendancy which threatens the downfall of the former as a nation.
The government is inefficient, partly from the character of the king,
who is very much influenced by the whites and half castes,
whose interest leads them to encourage his dissipated,
thoughtless course of life,--and partly because his native simplicity and inexperience,
are ill adapted to cope with designing adventurers who are ready to take every advantage.
The remote locality of the islands in these seas,
so inaccessible to the eye of philanthropy and the hand of unbiased justice,
is greatly against them.
Who is to represent them in civilized countries? Who is to defend their insulted
rights in the respective islands,--to advise them what measures to pursue,
and with an impartiality that levels all petty distinctions of nation or complexion,
to stand forward in the cause of religion, equity,
and humanity? If foreigners encroach upon the common prerogatives of nature,
the laws of England and America are no laws in the Pacific;
but if Pacific islanders infringe on the assumed or
usurped privileges of the subject of a powerful nation,
a sloop of war is dispatched to inflict punishment--a
punishment too often dispensing ruin,
alike to the innocent and the guilty, by an act of bloody retribution.

The first missionaries who settled on the Sandwich
Islands arrived about fifteen years since;
and though several families have left the ground and returned home,
subsequent reinforcements have augmented the number to nearly thirty families,
including physician, printer, bookbinder, etc.
Some of the original pioneers have acquired an
excellent knowledge of the native language,
and by these it has been reduced to writing,
and numerous translations made from the English into it.
The New Testament is published in a neat 12mo. volume:
the Bible itself has not yet been circulated; but many parts have been printed,
and probably the entire Bible will appear before long.
A vocabulary, a grammar, a work on geography, the rudiments of arithmetic,
natural history, astronomy, mathematics,
with small works on several familiar subjects calculated to interest and instruct,
have been issued; beside selections from Scripture in various forms,
and several hymn books.
There is also as already noticed a semimonthly newspaper,
which is no doubt the medium of much information;
and is calculated to amuse and incite to application many of the young people.
Great interest is evinced in the new works as they appear,
and they are bought up with eagerness.

The time of the missionaries is devoted almost exclusively to their professional duties,
so far as the unavoidable cares connected with
recent domestic establishments will permit.
The principle on which they are supported,
leaves no inducement to engage in trade in order to maintain their families.
The board at home supplies them with everything they require
through their '`secular agent,`' a person whose office it is to
provide for all their necessities on the spot.
He is applied to for whatever they stand in need of, furnishes conveyances to and fro,
transmits their letters, books, etc.,
and in fact acts the part of general agent to them all.
But though all partake of the common stock,
no narrow prescriptions or restrictions in regard to
their several expenses and arrangements,
reduce the families to one level:
each one does as he sees best according to his habits and necessities,
with the understanding that all extravagance will be studiously avoided.

As an organized body, destined to operate in a given field,
and to prosecute a given object,
I think the Americans in the Sandwich Islands afford a highly creditable example;
and certainly, as regards the personal character of many of the labourers,
their evident exclusive desire to benefit the
natives by imparting what they themselves value,
their openness to receive the suggestions of others, whose ideas and views may differ,
and their intellectual qualifications,--they form a highly estimable community.
They are Congregationalists by profession,
and probably their acknowledged principles recognize the lawfulness of war;
but several individuals among them, with whom we conversed on this subject,
appeared practically convinced of its utter inconsistency with the gospel of peace.
Oaths are happily not in use in the Pacific,
so that our Lord`'s command in this respect is not, so far as I am aware,
judicially abrogated among the natives by presumptuous man.

In the public assemblies for worship,
the Sandwich Islanders generally behave with decent quietness,
without the vigorous application of sticks,
or even the exhibition in terrorem of these unhallowed
appurtenances of a house for religious worship.
Their habit of coming in and going out during the services, is not yet broken off,
although attempts have been made to correct it.

The wives of the missionaries are in the habit of meeting certain
classes of the natives for the purpose of instructing them;
some assemble the adult female members of the congregation,--some teach the children,
and one in Hololulu has charge of an infant school.
An effort is now making to teach the people to manufacture cotton cloth,
and some good common material has been already produced;
which if attainable by all would constitute an
important improvement on the present paper coverings,
and make the islanders less dependent on a foreign supply.
It appears to me that literary education alone, is not what this people most need:
a system adapted to benefit them, ought to exert a more general influence.
What they require at the present time for their moral and civil melioration,
is a class of plain, honest, industrious settlers,
who would furnish domestic models for their imitation:
not men who merely come to make money by their exertions,
but such as would come from a sense of duty to live among the people,
and by leading them on towards improvement and civilization,
through the silent but potent means of personal influence and example,
endeavour to raise their present low condition.
The mission families are of course now exerting an excellent influence in this way;
but their number is small, their efforts are divided among a variety of objects,
and they ordinarily belong to a class of society,
somewhat more refined and intellectual than the persons to whom I refer:
their sphere in fact is a different one.

The missionaries, wherever we have been,
form an important civil defence for the poor natives,
which the overbearing and unjust encroachments of foreign adventurers render needful.
They occupy the opposite scale:
while others combine to support their individual interests,
or the more general interests of commerce and national aggrandizement,
the missionary takes the part of the islander: he informs him of his just right,
remonstrates for him against injustice, and what is more important still,
he constitutes a continual witness of the lawless conduct,
in which unprincipled men indulge abroad.
We may perhaps have met with a few singular instances,
in which other foreigners occupy something of an equal,
neutral ground--not exclusively bent on the support of one side;
but I must confess I should find it difficult to
point out half a dozen cases of much efficiency,
independent of the missionaries.
The latter, from the very nature of their circumstances,
as agents of absent benevolence directed towards the native population,
in constant correspondence with the better part of the community at home,
almost necessarily serve as a salutary check.
This is perhaps indicated with sufficient clearness by the fact,
that they are universally hated and dreaded by the contrary faction,
wherever they reside.

And now before I finally leave the Sandwich Islands, I will just remark,
that our visit to them has afforded us an opportunity of
becoming acquainted with some of our trans-atlantic brethren,
which I cannot but highly value.
I own, in order to judge of the American character, we ought to see it in America;
but still, for obtaining a general idea of it, the white community we have left,
affords probably a favourable opportunity:
the numerical proportion of English residents with whom we had interaction,
is quite small.
To both classes indeed, we are indebted for much kindness and many polite attentions;
for which, as wanderers and strangers,
we could not but highly appreciate and feel grateful.
For myself, I can say,
I shall always recur to our visit to this remote corner of the earth,
with feelings of peculiar and lively interest.

On the 19th of Seventh Month, 1836, we re-crossed the equator,
and entered once more the southern hemisphere.
The sinking North star was watched with considerable interest,
although the Magellan clouds, and the beautiful Cross of the South,
more than compensate for his loss.
Perhaps the sky between the tropics never exhibits a more imposing
aspect than during a short space subsequent to the sunset.
The whole west is tinged with the most delicate shades
of colouring,--from the rich amber to the deep,
bright blue of ether, which intermingle from the gilded horizon that conceals the sun,
up to the regions of the starlit hemisphere above.
My father has a particular admiration of this evening exhibition,
and delights to contemplate it, in these almost cloudless latitudes.
The shades of colouring which encircle the bright region where the sun has just set,
have something of the prismatic hues about them; but they are less defined,
and spread richly from the ocean to the high vault of blue overhead,
with a vastness and beauty almost indescribable.
Before the sun sets, the atmosphere is usually mottled with light fleecy clouds,
which fly in the direction of the trade-wind till the heat of day is gone:
afterwards the cool air condenses them, and they are dissipated in the form of dew,
leaving an atmosphere of cloudless purity.

While crossing the trade latitudes this time,
it has appeared as though the wind is perceptibly affected by the rays of the sun;
for during the day the breeze is often light;
but when the heat of his beams is felt to the westward of our horizon,
and the air consequently rarified to leeward of us, the force of the wind increases.

South Pacific, Eighth Month 10th.--Rarotonga, or as in the charts, Orurule,
is the principal island in the Hervey cluster; all of which are inhabited.

Rarotonga contains a population of 7000

Magnica is supposed to contain 1800

Atui is supposed to contain 1600

Aitutuki is supposed to contain 1800

Mitiaro and Mauki together, about 700

Rarotonga is a lovely island, about thirty miles in circumference,
and nearly circular in form.
It is obviously of volcanic origin,
although I am not aware that any crater is known to exist on its surface.
Calcined stone and cinders are abundant; and the marked,
rugged outline of its peaks and ridges,
indicates significantly the convulsive agency which has been employed in their formation.

The shores are built up by coral architects,
and exhibit a curious instance of coralline formation
intermingled with upheaved masses of original rock,
which protrude in some places through the former,
in a way that would lead to the supposition that
sub-marine eruptions of comparatively recent date,
have encroached on a super-stratum of coral,
which has been progressively rising round the coast.
Coral sand and shells, etc., consolidated by the action of the elements,
in some parts of the shore, form beds of fine, available stone,
probably as durable as ordinary free-stone,
of which the natives are beginning to find the value, as a building material.

The highest mountain is, I should think, four thousand feet high,
possibly rather more than this;
and others of somewhat inferior elevation occupy the central districts,
and ensure a constant supply of moisture to the lowlands.
These districts team with bread-fruit, plantains, bananas, citrons, limes, vis, papaws,
taro, sweet potatoe, sugar-cane, cocoa-nuts, palms,
and many other tropical productions of majestic growth.
Everything flourishes with an exuberance and richness rarely surpassed.

The island is divided into four parts, governed by separate, independent chiefs.
These are at present happily united in the wish to
promote the tranquillity and improvement of the country,
by seconding the efforts of the missionaries.
It is now eight or nine years since the latter settled among them,
and although assailed by many difficulties and discouragements,
their residence has been cheered by continued kindness on the part of the people,
of whose friendly conduct and docility C. Fittman gives the most gratifying account.
It is doubtless the civil and political interest of the
islanders to retain their missionary instructors;
and therefore in the absence of particular causes of complaint or dislike,
it is not at all surprising that they should behave courteously to them: I think too,
that the character of the Rarotonga natives is
superior to that of their windward neighbours.
They appear to possess finer feelings, and less slothful,
effeminate minds than the Tahitians.
In their wars before the introduction of Christianity,
it is said they never practised any of those fiend-like barbarities, which the luxurious,
mild Tahitian was guilty of; such, for example,
as dealing out indiscriminate vengeance in cold blood,
on the defenceless and the innocent; beating the body of a dead foe to a pulp,
and when dried in the sun in a flat form, wearing it as a cloak, etc.
On the contrary, though furious and bloody in the moment of passion,
these warriors are said to have even relented of their deeds of death;
and in some instances,
to have repaired with their personal efforts the desolations of war,
which their enemies had suffered.
They appear to be more irascible than the Tahitians or Sandwich Islanders.
We hear that the boys are often seen fighting each other,
with a spirit and rancour that would probably frighten the children of Tahiti; although,
more docile, lively and harmless little urchins, than they are on ordinary occasions,
cannot well be imagined.
As proof of their sensitiveness and excitability of feeling, I may remark,
that it is no uncommon thing in Rarotonga, for the party who thinks himself aggrieved,
to commit suicide.
We were informed that such a death frequently occurs; and during our short stay,
one man hung himself in consequence of a quarrel with some other native;
even women are guilty of this crime.

As a people,
the natives of Rarotonga are certainly more energetic and industriously disposed,
than some of the other islanders.
They only need a motive, and they will not shun labour and persevering effort.
There is no difficulty in getting work done, if an adequate inducement is offered.
No sooner was it known that we wished to obtain curiosities,
than they set to work to furnish them: they refitted their neglected war-caps,
collected shells, brought specimens of timber hewn with great labour,
and actually manufactured a number of new drums out of solid wood.
Some of their sashes, mats, baskets, etc., are made with great labour;
and their large canoes, which were formerly used in war,
exhibited in their decorations great ingenuity and pains.
Some of the figures which form the heads of these canoes,
are really quite neatly sculptured, considering the tools with which they have been made;
and the carving is executed with considerable regularity of design.

The native dwellings are mostly situated along the shore, forming several straggling,
irregular villages, which are half concealed in foliage,
and are connected by raised foot-paths, wooden bridges, etc.,
so as to be easily visited from all parts of the coast.
Many of the more modern houses are wattled buildings,
and look respectable and capable of being made comfortable dwellings,
if the owners possessed but the requisite materials.
The original huts were constructed in the bird-cage style of Tahiti.
In some respects,
I think the modern plan of building greatly superior to the one formerly in vogue;
although really in point of comfort, with their habits,
the difference to the natives is not so striking as might be supposed.
White-washed walls, without glazed windows or boarded floors,
destitute of all furniture but a few mats,
and some dried reeds or grass for a carpet,--have a poor, stable-like appearance.
However, time will, I trust, introduce a change of habits,
and furnish with civilized conveniences,
apartments certainly better calculated to receive them,
than the open railed huts formerly in use, and which are still not uncommon.

Out of the seven thousand persons on this island,
about three thousand are estimated as children; they are, with few exceptions,
receiving some kind of instruction.
Great numbers can read and write,
and if the utility of these acquirements is not quite so obvious as could be wished,
at least it is probable that the time passed in school by so large a portion of the
young inhabitants is more innocently employed than it would be elsewhere:
a compulsion is used on the part of the chiefs to compel them to learn,
which is abhorrent to our free notions.
A considerable number of copies of the four Evangelists are now in circulation,
and one cannot but rejoice, that many of the people can read them with ease;
otherwise I confess their close application to the study of reading and writing,
when we know that neither pen, ink, nor paper, and but very few printed pages,
are within their reach, has appeared to me as of comparatively little value.
Corporal punishment is unhappily tolerated in the schools here.
Under the immediate eye of C. P. there is no danger of much severity,
but he cannot see everywhere: natives are empowered to act as teachers,
and it cannot be expected that moderation and discretion will always be observed,
particularly when the scholars are obliged to attend.
The influence of fear is in itself an evil, and therefore I regret its existence at all.

Out of the whole population of the island,
I understand not more than one hundredth part
are regularly initiated into church membership.
Candidates for admission pass through an ordeal of classes, as they are termed,
which is intended to prevent the easy introduction of hypocrisy and unsound profession.

The bulk of the people, I rejoice to say, are independent holders of property,
which is as much their own as the land belonging to the chiefs,
unless forfeited by a breach of the law.
But by virtue of a right acknowledged from time immemorial,
obtained by usurpation and superior power, and upheld by superstition and ignorance,
the word of a chief is absolute law among the uncivilized tribes;
and his views and wishes are studiously followed by the multitude,
who seem to feel a pride in maintaining his influence, and venerating his generally huge,
unwieldy person.
The chiefs of Rarotonga support the interests of the missionaries,
take part in person in the services which are performed in the pulpit or the desk,
and live on terms of intimacy and courtesy with the families of their instructors.

C+++.+++ P. is a zealous, active and amiable man,
whose individual influence is most salutary upon those by whom he is surrounded.
His health unhappily is extremely delicate,
but with care it is possible he may yet be spared to
his family and pastoral charge for a considerable time.

Some years back the manufacture of calico was introduced into this island and met
with more encouragement and success than under the protection of the Tahitians.
Some of the people learned to spin and weave tolerably well,
and traces of their skill are visible at this day;
but this most needful provision for the destitution of the islanders has not
become by any means so generally useful as could have been wished.
Under their circumstances,
destitute of the facilities for its manufacture which civilized countries would supply,
the natives find making calico a tedious and laborious affair;
and consequently it has been very much relinquished:
although for lack of the requisite supply of bark,
which has been rendered extremely scarce,
in consequence of a hurricane that destroyed
many of the bread-fruit trees a few years ago,
the poor people are miserably in need of clothing.
When a vessel touches for provisions,
cotton goods in the way of barter are easily obtained;
but this source is by no means adequate to the supply of a dense population.
The common dress of the adults is a piece of native
cloth wound round the waist and extending to the knee;
in-doors occasionally, and generally out of doors,
a large loose piece of cloth is thrown round the bust and held on with one arm.
They have little to say, but look very observing,
and display great acuteness and cheerfulness.
The women are more nearly white in complexion than any
other of the Pacific islanders we have seen,
and often have pleasing faces and well formed graceful figures.

The amount of disease among this people is exceedingly small,
when compared with other islands,
and the adult population generally look healthy and comfortable.
The place we visited literally swarmed with children,
and the population is rapidly increasing.
In two districts which contain about 3700 souls, between the Seventh Month 1834,
and Sixth Month 1836, the births and deaths were in the proportion of 248 to 100.

The mission establishment, at which we were kindly entertained during our stay,
wears quite a respectable, orderly appearance;
indeed the settlement of Gnatagnia altogether has a
flourishing aspect,--the houses being neat buildings,
and the chapel and school houses commodious structures.

There are several striking natural curiosities on one of the other islands.
Huge subterranean caverns, which extend under the body of the island,
and exhibit the most wonderful spectacle of its kind perhaps existing in the Pacific,
are said to be found in Atiu, where beautiful specimens of spar are also obtained.

But to take a final leave of Rarotonga:--the
island seems indeed to possess those features,
which imagination loves to trace in her ideal picture of a South Sea paradise.
The scenery is picturesque and the soil fruitful;
the natives retain much of their primitive simplicity,
uncorrupted by contact with the vile, sordid, money-hunting world;
who spread the vices and misery of civilization without its blessings, wherever they go.
It is true they are but half reclaimed from barbarism; their minds are untutored,
and their ideas low and childish;
but they at least appear willing to receive instruction,
and they are blessed with a missionary who is earnestly endeavouring to impart it.

Port Refuge, Vatau, Eighth Month 25th.--We were visited by the captain of a whaler,
who was not long ago embroiled in a quarrel with the natives of this place.
He insisted on cutting fuel without paying for it,
and landed with arms to accomplish his purpose.
But for the interference of the missionaries,
in all probability a contest would have taken place,
attributed no doubt at home to the ferocity of the Vavau natives,
who assaulted his men while procuring needful supplies for the vessel.
The last time this individual was here,
he carried off by force several natives of this island,
landing them afterwards at the Navigator`'s, where they still remain.
Other cases of the kind might be mentioned.

Ninth Month 1st, 1836.--Our route in visiting the station of Haalaufuli,
led through winding passages, between the groups of small islands,
which surround the mainland in the south and south-west directions,
and furnish considerable variety of wooded landscape and tranquil lake scenery;
but it is destitute of that boldness and magnificence of outline,
characteristic of many other South Sea Islands.
The shores are moderately low, and covered with dense matted forests,
which extend to the water`'s edge,
and seem to flourish amid masses of bare rock without a trace of soil.
In some parts there are precipices which exhibit stupendous
piles of stone thrown together in the utmost confusion about
these unexplored caverns and overhanging ruins,
the restless waters murmur, and the sea fowl finds an impregnable retreat.
The tide undermines the shore, and flows in some places far under the land;
we passed one insulated rock,
which is supported by a comparatively insignificant pillar,--
all the rest of the original base being washed away:
the appearance of this rock is the more curious,
from its being surmounted with vegetation and a large tree.
Coral of a thousand forms and colours is seen under water in the shallows;
and among its variegated branches the gorgeous fishes of the Pacific,
exhibiting hues as rich and brilliant as the peacock`'s train, or the butterfly`'s wing,
seem to sport secure from all enemies but those of their own kind.
Sharks are said however to find shelter in the thick coral grove,
where masses of consolidating roots and branches
become gradually overgrown with fresh vegetation,
which conceals the dark labyrinths below from the eye of day.
These monsters are numerous and occasionally destructive:
we have seen a man who has lost both his arms by the bite of one of them.
Since lying here, we have seen a number of them, and caught one of considerable size.
A hog which escaped from one of the ships lying near to
us was devoured almost as soon as he reached the water,
and before a boat could overtake him.
They were formerly deified here, as well as in Tahiti,
and were dreaded with more reason than many others of the South Sea dirinitia.

Ninth Month 8th.--About a mile from the place of
our reembarkation there is a large cavern,
which it was agreed that we should explore before returning to the harbour; so,
piloted by some natives who live near the spot, we coasted along towards the open sea,
till the object of our curiosity appeared in sight.
I had observed it as we beat up to the harbour on the day of our arrival,
and was glad of the opportunity now afforded of investigating such a wonderful recess.
The entrance is under a kind of natural portico of rock, of great height,
which leads into the principal cavern: the passage is broad and the water deep;
so that our boat and a canoe entered together with ease,
and navigated the interior of the vault, which is lighted from the entrance.
After passing the vast archway of rock which forms the mouth,
the scene is magnificent in the extreme,
and called forth an involuntary burst of surprise and admiration.
The roof is an amazing height, with pendant masses of stalactile,
which garnish with indescribable richness the variegated concave above.
Beneath, is a beautifully transparent surface of water,
which reflects the walls and arches in a moving mirror,
and reveals a world of submarine life and beauty beneath; caves, rocks,
beds of coral and petrifactions richly coloured,
and the painted finny tribes of the Pacific roving in perfect security,
among these romantic watery glens.
The walls are encrusted with spar of various colours, but principally of a bright blue,
whose descending columns look like the ruins of a marble edifice,
built not with the puny regularity of art,
but with the wild unstudied magnificence of nature`'s inimitable architecture.
On the left hand, is an arched passage into another apartment,
whose recesses are indistinctly visible, which can be explored in a similar manner;
and in front is a winding ascent, between high walls, which must be traversed on foot.
By stepping from crag to crag along the irregular sides of this passage,
and holding by projecting points and ridges for some distance,
you reach a floor of solid earth,
which leads at length to another circular dome of great height,
composed of somewhat darker materials,
which are but partially illuminated by a small opening at the very summit.
Here all is silent, dismal, and damp:
untraversed caves leading to an unknown distance in utter darkness,
open from the side of this gloomy vault.
We would gladly have attempted to penetrate further, but being destitute of torches,
it was impossible to proceed with any degree of safety.
We obtained specimens of the stalactite, and after rousing the echoes of the cave,
commenced a return to the anchorage.
This most imposing cavern is situated opposite the entrance of
the channel which leads to the harbour of Port Refuge,
and consequently is exposed in heavy westerly gales to the full lash of the ocean.
I leave you to imagine what a spectacle must be exhibited in the interior of the cave,
when it is invaded by an infuriated surf.

Ninth Month 16th.--The summit of Talau, in this island of Vavau,
is computed to be one thousand feet above the level of the sea,
and the ascent is rugged and circuitous, through a dense forest,
matted together with thousands of climbing plants, creepers and vines,
which very much increase the difficulty of traversing it.
Such a rich chaos of rock, foliage, gigantic ferns and cocoa-nut trees,
you can scarcely imagine;
and flying foxes and birds of brilliant plumage
gave animation to this splendid wilderness.

At Sea, Eleventh Month 12th,
1836.--The Friendly Islands is a name originally given by Captain
Cook when he first visited these comparatively friendly shores.
In this general appellation is included Tongataboo and
its inferior island neighbours,--the Fiji group,
which lies a few leagues to the westward, and is very little known,--the Haabai,
a cluster of low coral islands,
eighteen of which are inhabited,--Haafuluhau which consists of Vavau,
and above a hundred small islets by which it is almost encircled--the
Hamoa or Navigator`'s Islands which lie to the north-east,
and several less important insular tracts of land,
interspersed among the above enumerated groups.
Of these only a few have been occupied by missionaries,
and with some inconsiderable exceptions,
the profession of Christianity is confined to Tonga, Haabai, and Haafuluhau.
To these places our visit was confined,
and to them of course the following remarks exclusively apply.

To begin with Haafuluhau, which we first visited.
The island of Vavau includes the larger portion of the land settled on by natives,
which this group possesses, and is supposed to contain a population of 3000 souls.
The other islands of the group collectively augment this number to about 6000,
which is the whole amount of the native population,
according to the estimates of the missionaries.
The king has renounced idolatry and embraced the doctrines of Christianity;
he has put away all his wives but one,
become a local preacher and a class leader in the Methodist Society,
and seems willing to be guided and advised by the missionaries in every undertaking.
The queen is a class leader, and a teacher in the schools,
and nearly the whole population of these islands on which missionaries reside,
have been admitted into the church.
There are no less than one hundred and seventy native local preachers,
who are employed in all parts of the Haafuluhau group,
and thirty chapels in which there is service three times a week.
The people thus led by their king and chiefs,
attend diligently to the instructions of their teachers,
and have already acquired considerable Scripture knowledge,
and a taste for reading and writing.

The Haabai group is situated a little more than a degree to the southward of Haafuluhau.
They are inhabited by a similar race, who speak the same dialect,
and are now united under one government.
Very few ships visit this group, as it possesses no good harbour,
and the character of the inhabitants and the policy of
the rulers deter white men from settling.
Lifuka, although by no means a fine island, has been selected as the seat of royalty,
and it now contains a mission establishment.
This group which consists of eighteen inhabited islands,
is said to contain a population of 4564. The
profession of Christianity is universal here.

A few leagues to the southward of Haabai lies the island of Tongataboo,
at present under the government of Tubou, a relation of king George,
who is expected to succeed him.
The country and its inhabitants correspond very nearly
with what is found in the two before mentioned groups,
but the civil condition of the people is much less favourable.
The population is estimated at 7000 persons,
and of these upwards of 1000 are Christians by profession;
the rest still retain their old superstitions.
There are seventeen fortified towns or villages on the island,
one of which Nukualofa is occupied by the adherents of the missionaries,
at the head of whom is king Tubou.

One cannot but deeply regret that the pacific principles of the New
Testament are not fully professed by those who are sent to "`preach glad
tidings,`" and to "`publish peace`" among these teachable islanders.
However feelings of personal piety and benevolence may, and I rejoice to believe,
do actuate many, if not all of these individuals,
to desire and to labour for the continuance of harmony
and good-will,--still their doctrines are defective;
and they tolerate and recommend a dangerous middle course,--a course,
which the spirit of the gospel forbids, and which has never yet proved adequate to avert,
among Christians, the shocking incongruity of mutual destruction.
I never can at all comprehend how the doctrines of our blessed Saviour,
the Prince of Peace, and the right to destroy a brother mortal are to be reconciled;
nor have I ever been able to contemplate without a feeling of wonder,
men really lovely for the Christian graces they exhibit,
surrounded by instruments of death,
avowedly destined to be used with their own hands
against the lives of their deluded fellow-men.

Slavery,
that '`execrable sum of all villany,`' still prevails to
a certain extent among the heathen party;
although even this monster is rendered less
destructive by the proximity of a better system.
Tonga slaves are made such in the most capricious manner possible;
a word or any slight offence may subject a man to be condemned to the lowest servitude,
without any trial, and when once sentenced to slavery the curse is hereditary.

The natives who still remain in their heathen state are
more destitute of clothing and other foreign articles,
than their neighbours: they look less cleanly, and less regularly and adequately fed;
their persons are frequently mutilated by wounds received in fighting,
and disfigured with sores or burns, inflicted according to superstitious custom,
as indications of grief or respect for the dead.
From the very recent introduction of Christianity,
many of these external marks of heathenism are seen among the professing natives;
but these are not the effects of a cause every day in operation as in the other case,
but merely the relics of departed folly and madness.
Some of the poor women in the heathen settlements,
who torture themselves according to ancient usage, are really appalling objects:
their hair cut off, their cheeks burnt and bruised with a rough instrument,
till they look purple,
and other parts of the body more or less disfigured with wounds thus self-inflicted,
give them a frightful appearance,
and furnish a sad demonstration of the reigning power of superstition.
I have seen a woman spotted over with scars in this way like a leopard.
This practice was formerly in use among the men likewise:
they commonly have one round scar under each eye,
and some have many rings burnt in the flesh of the arms.
The custom too, of cutting off the little finger on the death of a relative or superior,
was very common;
and most of the older men are destitute of one or both of these minor members,
which have been thus sacrificed.
No, the absurd practice has extended to the children, and if a chief is dangerously ill,
many little fingers are even yet occasionally amputated to avert his death; but this,
like the cutting and burning of the skin,
is abolished among the professors of Christianity.

In a commercial point of view,
the three sections of the Friendly islands which we have visited,
are not of much importance, and probably never can be so.
The harbour in Vavau has great disadvantages from the
inconvenient depth of water for anchorage,
excepting in one small part;
also from the lack of good fresh water for the supply of the shipping:
among the Haabai group there is no secure anchorage at all.
In Tongataboo, though one part of the harbour is safe,
and the produce of the country is valuable for the whalers, the water is very inferior.
All three groups are subject to earthquakes, also to very destructive gales.

With the exception of Kao, Tufua, and Haufuluhau,
these islands furnish the most complete specimens of
coral formation that we have yet seen,
on a large scale.
I have no doubt they have been rendered habitable by the progress of marine vegetation,
and the subsequent accumulation of coral sand, and decomposed vegetable substances,
which covered the islands as soon as they reached the surface of the sea,
Coral obviously forms the fathomable ground-work: the soil is quite superficial,
and underneath is coral rock and salt or brackish water.
One of the Haabai islands is said to rock frightfully during heavy gales,
which tends to prove its incomplete solidity under water;
and some others exhibit various indications of hollowness.
Constantly recurring earthquakes, and the volcanic crater in Tufua,
which disgorges a vast quantity of combustibles
and smoke from the subterranean furnace beneath,
indicate the proximity of great igneous operations under ground;
and I think there is rational ground for concluding,
that the whole island has at some time been raised by this sub-marine agency.
They are for the most part fertile, producing abundance of tropical vegetation, which,
under different management,
might be increased and improved by culture to almost any extent.
The trees and plants most common, are similar to those found in the other groups,
with comparatively few exceptions.
The fruits most abundant are shaddocks, papau apples, pine apples, melons, and citrons.
The orange, so common elsewhere, is very scarce and of bad quality; but the papau,
introduced into these islands at the same time,
has more than compensated for the deficiency,--being produced in perfection,
and in exhaustless quantities.
To this exotic fruit the islanders are indebted for a valuable
supply of food during their periodical seasons of scarcity,
and their more formidable occasional famines,
which occur after the ravages of a hurricane or a strong westerly storm.
The yam is peculiarly obnoxious to injury from the wind, and on this precarious,
though excellent vegetable, which is the staple food of the Friendly Islanders,
their sustenance to a great extent depends.
Other more hardy vegetables have been hitherto most improvidently neglected,
the people have consequently been subjected to great scarcity after these violent storms,
and but for the papau fruit must have endured much greater hardships.
The cultivation of the sweet potatoe is becoming more common,
and will no doubt tend in future to prevent the evils alluded to.
The vegetables most cultivated are the yam, bread-fruit, taro, sweet potatoe, plantain,
and a root resembling the yam, which we had not before seen.
Cocoa-nuts grow spontaneously in great abundance, on almost all these low sandy islands.

The climate of the Friendly group, judging from what we saw,
is very fine,--preferable to that of Tahiti,
where several months of the year are rendered almost unavailable by incessant rains.
No season appears to merit the epithet rainy,
although the summer months probably furnish a larger
quantity of downfall than the rest of the year.
On the whole, there appears to be rather a deficiency than otherwise,
owing no doubt to the lowness of the islands, and the sandy nature of the soil.
During our stay the thermometer ranged principally between 75° and 85°:
a temperature very pleasant to residents in the torrid zone,
but somewhat enervating to the human constitution,
which as in the other islands of the Pacific, attains very early to a state of maturity,
and is subject to a correspondingly premature decline.

As regards the character of the islanders, I prefer that of the Friendly Isles,
to that of any other natives of the Pacific whom we have seen.
Such a preference may be more than is generally awarded them;
but several reasons might be alleged for the relative estimate
that has been formed of them and the other islanders.
Many of the voyagers who visit this ocean,
are men of miserably low moral feelings and habits, and as such,
they unite in eulogizing the natives whose manners are most congenial to their own.
On this account, the voluptuous effeminate Tahitians are spoken of in high terms,
though they certainly will not bear comparison with these more sober,
and manly islanders.
I think these people are less prone to sensual indulgence than either the Sandwich,
Georgian, Society or Hervey islanders.
But if less depraved,
I do not think them at all less sensitive or susceptible of the kindly emotions:
they evince quite as much affection towards each other, and towards their children.
They are not so volatile and frivolous as Tahitians,
and perhaps they may not be quite so quick and lively as the Hervey islanders,
but their gravity and good sense are accompanied by nothing particularly austere,
much less ferocious: on the contrary, they are gentle and affable as children.

Their domestic habits resemble those of the other groups.
Their houses are small fragile huts with thatched roofs and matted floors,--no windows,
or doors, and scarcely any furniture.
The flexible character of the building materials is a great security
to the inhabitants during the earthquakes which frequently occur,
and on this account it seems undesirable to alter the style of building which prevails,
although in themselves, Tongese dwellings are comfortless looking places.

The dress of the natives is almost exclusively native cloth,
loosely wrapped round the figure in irregular ample folds.
A few of the leading men who officiate as preachers, etc.,
and some of the females connected with the kings and chiefs,
possess articles of foreign clothing for particular occasions; but on the whole,
the national costume is much more completely retained
than in any other groups we have visited.
Individuals of both sexes wear the hair cut short,
so as to leave a thick covering for the head,
and this they friz out with great pains till it assumes the
appearance of wool;--using lime or white clay to make the
hairs stand out and exhibit the proper bushy appearance.
The women commonly wear much less than the men,
and the children have the top of the head shaved, or the hair cut very short,
leaving merely a fringe round the head, a few inches in width.

They make great use of cocoa-nut oil for anointing their heads and bodies,
and it seems probable this practice has a salutary effect.
It softens the skin,
which might by continual exposure to a hot sun become callous or irritable;
particularly as the people are so much in salt water.

Healing the sick is a most important means of
influencing the minds of the untutored natives of Tonga.
If a man has derived benefit from the medicine prescribed for him by a missionary,
he very naturally leans to the side of his benefactor, and often joins his party.
The value of English remedies is known and acknowledged among these islanders.

According to missionary information,
23,000 persons have renounced idolatry in this group, within the last ten years.
Of these 9000 are members of the Wesleyan Society, 329 are local preachers,
and 1100 are school teachers.

I cannot but acknowledge the kindness we received from the
Wesleyan missionaries and their converts in these islands.
Several of the former are interesting persons, whose society we enjoyed,
although as might in reason be expected, we could not on all points think, see,
and feel alike.

The Tonga dialect has been reduced to writing,
and large portions of the Bible are in circulation, but the whole has not yet appeared.
Several small books of a preceptive and devotional character,
and one or two intended for the use of schools, containing the rudiments of grammar,
etc., are printed, and no doubt others are in progress,
and will before long be published.

The Ilamoa or Navigator Island`'s dialect differs from the Tongese,
and the Fiji forms a third variety in the groups already occupied by the Wesleyans:
probably several others exist among the neighbouring islands,
but these are as yet little known.
It appears that the Fiji tongue has several striking peculiarities
quite unknown to the other dialects of the Pacific.
For instance, the sound of "`th`" is found in it, if I am correctly informed,
and syllables do not necessarily end with vowels,
as in all the other known varieties of the Polynesian.
But there seems to be quite a distinct character about the Fiji islanders altogether:
their appearance indicates a mixture of the black and the Asiatic races,
and their manners are very barbarous.
Their knowledge of several branches of manufacture is decidedly
superior to that possessed by any of the other tribes.
They display great labour and ingenuity in carving weapons, basket-making,
canoe-building, making a variety of showy ornaments for the person,
and in the manufacture of earthenware utensils for culinary purposes.
They evidently belong to a distinct family,
no doubt derived originally from the same source as the other Friendly islanders,
but amalgamated with the Malay or negro.
A few years will develop more fully the national character of these formidable warriors:
two missionaries are now among them with promising
hopes of success in their arduous undertaking.
I think it not improbable,
that this section of the group contains the most energetic and
intelligent division of the Friendly islanders,
although at present without doubt the most wayward and contentious.

New Zealand, Twelfth Month 3rd, 1836.--While halting at Keri Keri,
we visited a cascade situated on the river of that name,
which affords a highly picturesque spectacle.
The fall is about seventy feet perpendicular,
and the spacious valley beneath it beautifully verdant,
and furnishing a variety of vegetation which we had probably never seen surpassed.
The name of this cascade is the same in signification as one in Hawaii,
called the '`cascade of the rainbow,`'--no doubt in both cases in consequence
of the effect produced by the sun`'s rays passing through the spray.
Like the still more imposing fall in the Sandwich isles,
there is a deep cavern extending behind the projection of water,
which adds greatly to the effect produced on the eye.

First Month 13th, 1837.--We were told that all the merchants,
even the few who have renounced the sale of spirits,--deal in muskets and ammunition.
You can form little idea of the quantity of these
articles that has been brought to New Zealand:
it is astonishingly great.
I remember to have heard a missionary state,
that in one _pa_ or native fort,--of which he was speaking,
the chief had in his possession about a ton of gunpowder.
Many dreadful accidents, as you may suppose, occur with such a formidable combustible,
thus kept in the huts of these poor reckless natives.

While mentioning war,--the darling passion of uncivilized men,--I am reminded of a
remark made by a New Zealand chief to one of our mission friends,
who was conversing with him on the subject of a future world.
The warrior expressed his disapprobation of the opinion which
the missionary advanced respecting the life to come, saying,
'`If this be true, what is to become of the warrior?
If there are no pas to attack, he will have nothing to do.`'
How much more consistent are the
present practice and the anticipated paradise of pagans,
than the lives of the majority of Christians and their professed expectations of a
scriptural heaven? The warrior of New Zealand sees in a moment,
that his warlike tastes are incompatible with a world of peace and angelic blessedness;
while his more enlightened antipodes lay claim to both!

The notions of these aborigines on points connected with an invisible existence,
appear to be extremely vague and various,--much less definite and
refined than the superstitions of the other islanders we have seen.
A belief in a future state, and in superhuman agency, appear to be universal.
The New Zealanders cannot properly be called idolaters,
having no objects of adoration in the form of images or idols;
although there are many things to which they attach a sacred character,
regarding them rather as charms or spells than as divinities.
The term which in all the dialects of the Pacific islands that we have visited,
is used to express Deity--Atua, Odiia, Akiia,
etc.,--which are all but variations of the same word,
is here too used to designate something sacred,
but with an extent of application that renders it almost incomprehensible.
The New Zealand ideas of the Almighty seem to be much less
definite than those entertained by the other islanders,
and this term is correspondingly vague in its application.

My allusion to this subject recalls an anecdote which pleased me much at the
time I heard it from the lips of our venerable friend Samuel Marsden.
He was talking one day to a New Zealander of the ideas
entertained by these natives respecting a Supreme Being,
and asking him what their god was?--what he was like? The warrior placed his hand
so as to produce a shadow on the trunk of a huge tree that stood near them,
and told his interrogator to look at that.
'`There,`' said he,
'`is our god:--he exists but you cannot touch him or injure him;--he is before your eyes,
yet you can discern no substance in the form you
see and know to exist`'--or to this effect.
Is not this a beautiful illustration to come from a New Zealander?

A disturbance occurred today on board one of the ships lying by us,
which very nearly ended disasterously.
It happened on board an English whaler, commanded by a captain,
who appears to be much more of a gentleman in manner and conduct,
when among his countrymen,
than most of the masters of these ships,--but who countenances just as much
license on board his vessel as the worst of his profligate brethren.
A chief from a neighbouring pa, who supports all that is vile among the ships,
was on board this whaler,
with great numbers of his male and female dependents,--the
latter of whom were quartered on board,--when either he or one
of his men brought some spirits from their canoe,
which the mate of the ship immediately seized and threw overboard.
This irritated the natives,
and pistols were produced on the quarter-deck to intimidate them.
In a while however, the dissatisfaction appeared to subside,
and suspicion was banished from the minds of the whites.
When all was thus quiet, the old chief seized the mate by the throat,
and waving his tomahawk over him made a signal to his followers to occupy the deck.
In an instant, the ship was covered with naked men,
and every instrument resembling a weapon was in the hands of the natives.
Not one-half the ship`'s company was on board, and therefore no resistance could be made,
so nothing occurred likely to exasperate farther; and after some time,
an old man interfered,
recommending that the affront offered to the
chief should be made up over a glass of grog:
this was in some sort done, and the matter ended without any bloodshed.
One of our seamen was on board the ship at the time and saw the fray:
he determined if violence should ensue to jump overboard,
and try to regain his own more peaceable vessel by swimming,
in which resolution one of the ship`'s crew joined.
When the chief went away, he seemed still unreconciled, and threatened to be revenged,
and during the following night we heard muskets fired in his pa, indicating defiance,
in answer to which a cannon shot was returned by the vessel, with the idea, we concluded,
of proving to the excited natives, that she was ready to encounter them.
Had the whole ship`'s company been on board at the time of the disturbance,
there is little doubt but a bloody contest would have been the result.

First Month 16th--The white residents, missionaries and others,
are at present preparing a petition to the British government,
praying that the state of New Zealand may be taken into consideration,
and measures adopted for the protection of British property in this country.
The object of this petition is evidently to induce the
government to send a force into New Zealand,
which shall be able to secure the possessions of the whites from all injury,
in case of such being attempted;
and at the same time to compel the fighting tribes to make peace.
This is a most critical step in the progress of New Zealand civilization;
and I sincerely hope that no unjust measure will be adopted;--in fact,
without the most glaring inconsistency, our government cannot interfere, coercively,
at all.
It has long since declared the independence of New Zealand,
furnishing the chiefs with a national flag,
which has been formally recognized and honoured as such:
how then can an armed dictator be placed on the island,
who shall be empowered to enforce submission to his requisitions? As
for the danger to which British property is said to be exposed,
I do not believe it is now in any danger from natives in this part of the country;
and whites are amenable to their respective governments,
and consequently ought to be placed at the
disposal of proper agents of those governments,
who ought undoubtedly to be sent into the land.
The proximity of the colonies would render the authority of a Consul quite adequate.
In parts of New Zealand where property may be somewhat insecure,
there are no establishments of any moment,
excepting those which on their present footing,
ought to be prohibited instead of being protected,--being the sources which
supply those very arms that are liable to be employed in their demolition,
and which serve greatly to aggravate these very
contests with which we now wish to interfere.
By what possible right can we command the warriors whom
we have formally declared independent,
to desist from settling their disputes by force of arms,
while our own subjects are providing them with the means of
doing so? We cannot interfere with British subjects who
circulate rum and weapons among the conflicting clans,
and yet we think it very proper to compel those clans
to abstain from using the weapons so acquired.

About two hundred signatures are already procured to the petition in question;
and it is to be hoped that the proportion of spirit
dealers and traders in arms who have joined in it,
will be specified.
Do we wish to prevent New Zealanders from destroying each other,
which is assigned as one of the objects of the petition? Well, then,
stop the sources which furnish three-fourths of the means:
make it a crime to bring cargoes of these pernicious articles,
and to build stores round the coast for the traffic in
them--a traffic which we in fact protect,
if we revenge the destruction of property that consists of little else
beside these and the native produce obtained in exchange for them.
Let us prevent in this way, our own countrymen from spreading firebrands, arrows,
and death among the aborigines,
and we shall in great measure avert those wars
which threaten the extinction of the people,
even before the vices of Christians (which are no less infallibly
destroying the natives where war is not raging) have cut them off.
If disputes still arise, and native spears and clubs are used to settle them,
we are certainly not answerable for those who may perish; and in plain English, I think,
that so far as we are concerned,
the islanders have a full right to decide their
differences in the same way as Christian nations,
until by lawful means we can induce them to act more sanely than we do ourselves.
To compel them to remain at peace, (and that too,
without providing any other means of adjusting their quarrels in a more humane
manner,) is in my opinion no other than "`to do evil that good may come.`"
Not that we can for a moment suppose that good would come,
if such a policy were to be adopted; on the contrary,
if the fate of the New Zealanders be fixed now, it would be no less certain then.
If we endeavoured to prevent mischief by sapping the root of the evil,
as I have above said,
the people might no doubt be gradually influenced by
good men to change their present savage mode of life,
and so be preserved from extinction; but the moment a British force enters New Zealand,
the country becomes a dependency of Britain,
and as such the aborigines of the soil will
perish as in all our other colonial possessions.

While reprobating severely the attempt which is now being made,
I am aware that a wish to prevent disorder may have a place in some minds,
and that a zeal for the extension of Christianity may operate in others.
I likewise know that a petition for protection does not
necessarily specify the mode in which it shall be sent,
but these considerations are of little value.
No supposed good can sanctify evil means;
and if unjustifiable measures are not suggested to our government, they must,
judging by past experience, be calculated on as the only probable results.
I as heartily wish the warriors of New Zealand could be
induced to suspend their sanguinary operations,
as any one can do who deprecates the horrors and crimes of war;
but never will I subscribe to the doctrine,
that it is lawful for us to use brute force in compelling them to desist.

First Month 28th.--The Bay of Islands by no means
furnishes a specimen of New Zealand generally,
being the resort of numerous foreigners,
and its neighbourhood but thinly peopled with the aboriginal inhabitants.
There are various tribes in the vicinity of the Bay,
and scattered over the northern islands,
who occupy in peace their little potatoe-grounds and fortified villages,
which are studded over the fern-clad hills that mark
the country not covered with pine and caurie forests.
These tribes are not under one common government, but are independent fraternities,
subject only to their respective chiefs;
so that within a short distance you find natives
living soberly and professing christianity,
and barbarians with rudely carved figures stuck round their stockade fortifications,
their tabued ground, and all the brute license of heathenism.
Several villages quite near the Bay refuse to have any connection with the missionaries,
and these are of course the haunts of run-away sailors, convicts and grogsellers,
who in fact perpetuate the present wretched pagan abominations, and if possible,
degrade the natives lower than they would otherwise be.
It is said there are five or six hundred white men to the northward of the Thames,
thus scattered among the natives, and leading the most abandoned lives.

The '`Church Missionary Society`' has five stations on the northern part of this island,
where missionaries are at present residing.
Five stations have been formed on the river Thames and about the Bay of Plenty,
but two of these have been lately abandoned on account of the
unsettled state of the native tribes in that part of the country:
one mission house has been plundered and burnt,
and one or two of the missionaries have been exposed to considerable personal danger.
The latter circumstance cannot of course be wondered at;
it is rather remarkable that during these popular tumults the persons
and property of the Society`'s agents have been uniformly held sacred,
scarcely an instance of violence having occurred among them,
although they have been frequently placed in the heart of savage warfare.
These eight stations are managed by about two dozen missionaries,
most of whom have families with them.
A schooner belonging to the Society is kept constantly plying
between the several posts accessible from the sea,
transferring the families or their property, as expediency or necessity may dictate.
The contending clans have avoided making enemies of the missionaries,
regarding them as a neutral party, and as such even among barbarians,
entitled to protection;
an instance or two to the contrary have unhappily occurred recently,
in which the teachers appear to have been identified in some degree with their adherents,
though even in these cases their persons have not been injured.

The Wesleyans have occupied a part of the western coast,
their head quarters being at Hokianga, but we did not see any of their establishments.
We were told that the country where they are located is more populous than
those parts where the Church Missionary Society agents are employed,
some of whose stations are entirely deserted, Keri Keri and Tepuna more particularly.
Waimate, the inland agricultural settlement, has not many natives near it,
but there are several tribes scattered round the neighbourhood,
within a moderate distance, whom the missionaries visit and instruct.
The same may be said of Faihia;
though the villages near the Bay of Islands are hostile to the missionaries,
yet there are several places up the rivers Kauakaua and Waikate,
where the people listen to their weekly instructions,
and have made some progress towards improvement.
The whole numerical amount of these teachable natives is insignificant,
indeed one hundred persons is considered a large congregation in New Zealand.

The Church Missionary Society,
and several individuals belonging to the mission hold large parcels
of land which have been regularly purchased of the natives,
partly for the present use of the mission,
and in part as a provision for the rising families of its members.
The children are not as among some other missionaries whom we have visited,
destined to be sent home at a certain age,
nor do the parents anticipate the expiration of a term of years,
when they and their families will leave the ground,
and take up their abode in England or the colonies.
The church missionaries came out with the intention of remaining,
and of establishing their children after them in their adopted country,
and several of the sons of the earlier missionaries are already settled on farms,
from which they expect to obtain a competency.
In this way large portions of the country will soon be colonized by Europeans,
for it is an acknowledged fact that English stock flourishes abundantly in New Zealand.
Several of the mission families are very large,
and though the second generation will doubtless assume
something of the Creole temperament and appearance,
yet the Anglo New Zealand natives enjoy robust constitutions,
and suffer very little from disease.
With such prospects of a permanent residence in the country,
no attempt is made to prevent the children acquiring the native language;
although in itself I imagine familiarity with native
habits and intellectual and moral degradation,
must be nearly as injurious here as in any of the other islands,
where the policy of secluding the children from contact with barbarism,
has induced the parents to prevent their learning the language of the people.

The New Zealand missionaries keep great numbers of native servants about them,
and really this practice appears highly advantageous under present circumstances;
for from the character of the people it would be extremely
difficult to obtain much ascendancy over them in any other way.
Induced by motives of self-interest to submit while young to some degree of restraint,
and to receive instruction from their patrons, it is to be hoped their wild, wayward,
vicious habits will be corrected, while at the same time,
their situation brings them within the religious influence of the missionaries.

The New Zealandere are by far the rudest and most warlike islanders that we have seen,
(if I except the few natives of the Marquesas and Fiji groups,
whom we met with occasionally among their more docile neighbours;
and the accounts we have received from residents here,
confirmed every unfavourable impression,
that their appearance can make on the mind of a stranger.
I confess I never thought the difference between these and the other Pacific islanders,
was so very striking as it appears to be.
They resemble North American Indians to a degree that you would scarcely credit,
both in appearance, habits, and Jewish customs.
They possess an invincible determination,
an independence which acknowledges no restraint,
not reconciled by a supposed decree of fate, and a restless martial daring,
accompanied by an undying spirit of revenge,
perhaps never more strongly exhibited in the human character.
The heart of a New Zealander seems almost insensible, in many instances at least,
to the softer emotions, and he does not possess terms to express such foreign influences.
Gratitude, meekness, lowliness, grace, and repentance,
affection and thankfulness are alike unknown to him;
while martial epithets and words significant of cruelty
and violence are abundant and elaborately explicit.
There seems to be an untameable spirit and pride about them,
which renders a concession almost impossible:
they will rather die than yield,--a principle no doubt
greatly fostered by their Spartan education,
which is calculated to infuse into the minds of mere children,
the hardihood and recklessness of the tiger.
Their notions about '`satisfaction`' might have been formed in imitation of
the famous '`laws of honour.`' Every offence must be resented or expiated,
and where actual warfare is not the consequence of a false step,
plunder is liable to follow the smallest insult.
They are said to procure an insult or a false accusation
merely as a pretext for demanding satisfaction.
The intelligence of the New Zealanders is universally admitted,
and from what I saw of them I was led to conclude,
that they possess greater versatility of mind than their tropical neighbours,
and perhaps quite as much acuteness.
They seem to experience little or no difficulty
in acquiring a knowledge of reading and writing,
even in places unvisited by regular instructors.
I saw, just before leaving the country a very fairly written letter,
addressed to one of the missionaries by a native who lived at a distance,
and who had only occasionally visited the station.

Their appearance is very Asiatic,--swarthy complexions, bald,
marked and often spare countenances, with dark, restless eye, black, straight hair,
somewhat raised cheek-bones, and irregular broad mouths;
athletic but not generally graceful figures characterize the appearance of the men,
whose faces, hips, and thighs are often scored with deep tatoo.
A shark`'s tooth, a bird skin, or a piece of iron drawn through the ear,
and a filthy mat or blanket thrown round the figure,
and occasionally exposing every part,
in many instances complete the decorations of these aborigines,
and render their exterior far less pleasing than that of many other Pacific islanders.
The women, who have been praised as furnishing perfect models of beauty,
are I think more pleasing than most of the other islanders.
They are not however so gentle,
nor are their habits so accordant with our notions of female propriety,
being often extremely dirty in their personal appearance and domestic management;
but their countenances are expressive, and their features well formed.
The lips are frequently disfigured with tatoo,
which gives them a singular and unpleasant appearance,
like that of persons who have been eating black-berries.

The British resident has made one attempt to
unite the principal chiefs in a sort of council,
in which they might act collectively;
and in theory he succeeded so far as to induce them to
consent that each one should no longer act singly,
but that in affairs of importance the collective opinions of the chiefs of
the '`united tribes of New Zealand`' should constitute a decision.
The members of this national council signed a formal declaration of their independence,
and agreed to meet annually for purposes of government.
But unhappily these auspicious indications were very transient,
and the perverseness of some exasperated individuals,
who could not support the dignity of civil rulers, frustrated the design altogether.
On the occasion of a dispute about some land which had been sold,
the national assembly was convened at the '`resident`'s`'
place of abode near the Bay of Islands,
to decide the case.
This was readily done, but the vanquished party in the rage of disappointment,
flew to their more congenial arbitrators--their muskets--and fired upon the assembly.
Some lives I believe were lost on the occasion,
and it has never since been deemed expedient to
call together such unmanageable counsellors.
It is very much to be regretted that the untoward
conduct of a few lawless individuals has,
for a time at least,
set aside a noble attempt to benefit by justifiable means this distracted country.

[.the-end]
THE END.
