== Preface.

In presenting to the public the following Memoirs,
a few explanatory remarks may be requisite.

For some years previous to the decease of our honoured parent,
it was evidently a matter which he had much at heart,
to leave behind him some narrative of his life; no doubt believing that a record,
in which might be traced so many instances of Divine mercy and interposition,
could not but be instructive and strengthening to others.
This work, however, though commenced in the year 1831, was never completed;
and it has been our duty to supply the deficiency from
whatever sources lay within our reach.
From the period at which the autobiography abruptly terminates,
to the time of his removal to Russia, the recollections of his family, and,
in some instances, the memoranda of his intimate friends, have furnished the only data:
but it must be observed, that nothing has been allowed a place,
which could not be stated with entire confidence; more might undoubtedly have been given,
by including incidents not so distinctly remembered, and matter derived from traditional,
rather than personal knowledge, which in the present instance has been carefully avoided.

Of the succeeding sixteen years, viz.: from 1817,
the private correspondence of the deceased affords almost the only materials;
but as this was tolerably copious,
and generally written with the entire openness of friendship,
it constitutes not the least valuable part of the Work.

The narrative of his religious visit to the South Sea Islands, etc.,
has been carefully revised since its last publication,
and some additional matter from the original notes has been interspersed:
a map of some of the Islands, constructed from the best accessible authorities,
is also introduced.

For the closing years of his life, the private journal has again been quoted.
The brevity of the American portion of it, will perhaps be regretted,
though easily explained by the increasing age and infirmities of the writer;
but although short,
it was thought to contain matter of sufficient interest to warrant its insertion.
The record of his last illness has been furnished by the amiable family,
who were then his kind attendants.

The Appendix will be found to contain several articles
which though not actually a part of the narrative,
are yet interesting in connection with it.
The extracts from the notes of our brother Charles,
written whilst accompanying his father amongst the islands of the Pacific,
exhibit a somewhat succinct view of the condition of their inhabitants,
and are the more worthy of notice,
as their lamented author was not only himself well qualified to observe,
but also to estimate the evidence of others.

It will be seen,
that the present work is to be regarded chiefly in the light of a compilation.
From the nature of some of the materials, it will also be evident,
that it has occasionally been as much a duty to omit, as in other instances to insert;
but the reader may be assured, that the selection has been fairly and impartially made:
and that whenever any alteration has been attempted,
it has been merely a verbal correction, without affecting the sense of the passage.
It is hardly possible that so near a relation to the
deceased should be an entirely impartial Editor,
and if any passages should be found indebted for their
insertion rather to feeling than to judgment,
it is hoped that both the judgment and feeling of the reader
will combine to induce him to make some charitable allowance.

It remains for me to acknowledge my obligations to all
those who have in any way assisted in the present work,
and particularly to my esteemed friend A. R. Barclay,
who has kindly superintended its publication.

In conclusion,
I would express my hope that no passage occurring in the
present volume may give just cause of offence to any;
but that on the contrary, many may derive from it edification and comfort.

[.signed-section-signature]
Daniel Wheeler Jr.

[.signed-section-context-close]
Eighth Month 18th, 1842.
