== Chapter I.

[.chapter-synopsis]
* Introductory Remarks by The Author
* His Parentage, Education
* Early Becomes an Orphan
* Enters the Merchant Service, then the Royal Navy
* Is Paid Off
* Enters the Army

Having frequently derived much valuable instruction,
from the perusal of the narratives of those who have long
since exchanged an earthly for an heavenly inheritance,
the thought has at times occurred to me,
that a short memoir of my own life,--however evil "`the
days of the years of my pilgrimage`" have been,--might,
under the Divine blessing, be made in like manner useful to others.
But perhaps, from the humiliating conviction,
that days as without number have been miserably devoted to madness and folly,
in forgetfulness of a long-suffering Lord God,
who is abundant in goodness and truth,--the guilty mind would
gladly hide the remembrance of these forever in oblivion,
and pass over them in silent abhorrence; or,
conscious that there yet remains a stubborn and unsubdued
residue of human corruptions,--a sense of unworthiness and
unfitness may have hitherto operated to retard the undertaking;
lest the creature should in any degree be exalted,
to whom shame only with blushing and confusion of face must ever belong.

Whatever may thus far have impeded any attempt of the kind, I am induced,
not as a matter of choice, but as a duty, now in the sixty-first year of my age,
to commence the work; humbly imploring the assistance of Him,
who "`knoweth the thoughts and intents of the heart,`" to enable me,
as far as it may be carried forward, to accomplish it to his own praise and glory,
as a faithful testimony for the advancement of our holy
Redeemer`'s kingdom in the hearts of my fellow creatures.

Although no man can possibly be excusable for having done wrong,
because others may have been as bad as himself,
or even worse,--yet the magnitude of the present undertaking would, in my view,
be diminished, if on reviewing writings of a similar kind, any thing like resemblance,
or a parallel case could be discovered.
But, alas! all that have gone before,
appear to me to have travelled a much shorter time than myself,
in the broad way that leadeth to destruction.
Many have yielded again and again to the temptations of
the unwearied and insidious enemy of mankind,
and have been long in the fetters of sin and death;
yet I feel to have surpassed all others, that I have read any account of,
in having drawn "`iniquity as with cords of vanity,
and sin as it were with a cart rope.`"
I can adopt as my own, I hope in a degree of true abasement of self,
the acknowledgment of the apostle,--"`this is a faithful saying,
and worthy of all acceptation, that Christ Jesus came into the world to save sinners,
of whom I am chief.`"

I was born in London, the 27th day of the Eleventh Month, 1771: my parents,
William and Sarah Wheeler, were members of the established religion of the country,
and strict adherents to all its rites and ceremonies;
and although not particularly conspicuous as being more
religious than others of the same class,
yet they were highly esteemed and respected,
by a large circle of acquaintance for uprightness and integrity,--of
which there are at this day many living witnesses.
They had a large family of children,
whose minds they endeavoured to imbue at an early age with the fear of their great
Creator,--taking them regularly to attend the performance of public worship,
and also reading the Holy Scriptures in the family at home;
portions of which I well remember reading aloud when very young.

By a document now in my possession,
it appears that until some time after my father`'s marriage,
he was not in any line of business; but afterwards,
to meet the demand occasioned by a great increase of family,
he commenced the wine trade in a select way.
To enter into minute family details is not the present object, nor is it within my reach,
being too young, when deprived of both parents,
to be able to speak from knowledge of my own.
I have but a very indistinct recollection of my father`'s person,
not being quite seven years old when he died, at the age of forty-three years.
Some time before his death, our once large family of children was reduced to five only,
of whom I was the youngest.
We then lived in London, at the Bond Street end of Lower Grosvenor Street;
but those parts of the premises which looked into Bond Street,
were occupied by another person, as tenant to my father.

My mother was endowed with a large capacity,
combining great sweetness with firmness of mind:
and although an entire stranger to every kind of business,
she persevered in an extraordinary manner after the death of her beloved husband,
in carrying on the trade for the support of the family; and so long as she lived,
it continued increasingly to flourish,
our eldest brother being her assistant in the business.
When she was attacked by the illness that deprived her
family of their endeared and only surviving parent,
I was sent for home on the mournful occasion,
being then at a boarding-school at Parson`'s Green, near Fulham.
Of the loss of such a mother, I was very sensible,
being about twelve years old at the time;
and as I had a much greater personal knowledge of her worth and solicitous affection,
than I could possibly have had of my dear father,
the event of losing her made a deeper and more lasting impression.
I had had much of her maternal society,
and had largely partaken of her constant parental and tender care, of which, perhaps,
from being the youngest of the family, I had more than an ordinary share.

A clergyman related to my mother by marriage,
who resided on a living in the West Riding of Yorkshire,
had the whole management of our family affairs, being left sole executor.
He came up to London at this eventful moment;
and after having examined into the state of things,
it was judged eligible that the business should
still be carried on for the benefit of us all,
by our eldest brother; whose character at that period, and known capability,
seemed fully to warrant such a decision.
Shortly after, I was sent again to school; and our little family band,
although lamentably reduced, still remained awhile longer unbroken.

For a few months after this great bereavement,
all things went on as well as could be expected with our solitary family;
but the deep affliction into which it had been plunged, by degrees began to wear away,
although for a time it seemed as if it could scarcely be borne, much less forgotten.
Our brother, on whose conduct the welfare of the rest greatly depended,
thus left without parental control, became less and less attentive to business;
and gradually sliding into bad habits, and mixing with evil associates,
gave way to every excess and indulgence in his power.
From his extravagance and negligence,
the affairs entrusted to him at home became so much embarrassed,
that it was now determined by the executor in trust,
that the business should be disposed of; and the necessary steps were taken accordingly.
It was not long before a person came forward,
who was competent to purchase the stock on hand,
and enter into the trade on his own account.

Although by our brother`'s imprudence,
the family were now banished from a comfortable home, and separated,
never all to meet again in mutability;
yet the business itself received no material check,
nor was it for a single hour suspended;
but was afterwards carried on to advantage for several years by our successor.
When proper arrangements were made, our beloved but unhappy brother sailed for Jamaica,
preferring in all probability a foreign clime,
rather than endure the reflections which he so justly merited at home,
for having thus brought ruin and disgrace upon a family,
whose prospects had been less clouded than those of many others in similar circumstances.
It cannot be doubted that much sorrow of heart would be his portion:
but I had never an opportunity of obtaining much information respecting him,
from the time he left England until several years after his death.
He died at the age of thirty-eight years;
and it appears that he had been comfortably
settled for the last several years of his life,
and been frequent in correspondence with those branches
of our family that were more stationary than myself.
My other brother had previously settled in the West Indies.
At this time, my eldest sister went to reside with our relative in Yorkshire,
to whom she looked up as a guardian, until married:
my youngest sister was at a boarding school at Putney;
and I remained with the family which succeeded to the business.
Having been previously removed from school to assist my brother in the counting-house,
I had acquired considerable knowledge of its management;
it was therefore a convenience to them who were entire strangers to it,
and for a time no other occupation offering for me to engage in,
I was furnished with employment, and had still a comfortable home.

Our family compact was now forever dissolved;--we were
scattered and widely separated from each other,
without any near relative in the world.
My father was an only son, and my mother an only daughter,
so that we had neither uncles nor aunts; and I believe,
in the strict application of the term cousin, not one that could properly be called so:
neither were any of our grand-parents living, or had ever been known to us,
except our dear mother`'s mother,
who ended her days at our house three years before her daughter`'s decease.
Our family being thus severed from each other, we were cast upon the wide world,
as to relatives, in a peculiarly destitute situation;
but yet not altogether friendless,--for some who had long been
bound to the family by ties of strong attachment,
clearly evinced their sincerity, by never withdrawing from the orphan children,
(now overtaken by adversity,) that regard and kindness,
which had been extended to their deceased parents in the days of their
prosperity;--a test which the friendship of the world can but seldom bear.

Having brought my little narrative to this point,
it seems necessary to determine in what manner it shall be carried forward,
before we proceed any farther.
After due consideration,
I am of the mind that it should be hereafter confined
principally to events relating to myself;
only in future bringing into view other branches of the family,
when the hand of time shall, through the over-ruling providence of Almighty God,
have again led some of us into connection with each other at periods far remote:
one of which was made productive of the most striking
and important change in the history of my life;
and which I humbly hope will lead to the accomplishment of another,
transcendently greater and everlasting, at my death.
But, reader, if the power to choose were mine,
to draw an impenetrable shade over the next several
years would best suit my natural inclination;
it would save me many pangs,
and I should at once bring thee to the time when I could tell thee with delight,
"`what the Lord hath done for my soul.`"
But with these years omitted,
the long-suffering and unutterable goodness of
my gracious God and Saviour would be eclipsed,
his tender mercies would be ungratefully robbed of their lustre,
the riches of his grace obscured, and its glory hidden.

I must therefore, like the regular and progressive gradations of nature,
proceed from those days of childhood and youth,
at which I had now arrived,--would that I could say, of innocency.
But ah! at this distance of time,
I can painfully trace the springings up of the evil root,
which failed not at an early age to bring forth fruit of those things
"`whereof I am now ashamed;`" having sorrowfully found from woful experience,
that their "`end is death.`"
Canst thou then wonder at the shrinking of human nature from the task of thus
re-opening a dark picture of guilt? such as I pray it may never be thy lot to know,
or to have to render an account of as thine own.
Though now in full abhorrence of the same, through the mercy of God in Christ Jesus,
I have a hope that my sins, though many, will be forgiven,
and forever blotted out as "`a thick cloud;`" and that my tribulated
soul will yet be cleansed by the precious "`blood of sprinkling,
that speaketh better things than that of Abel.`"
This only "`cried from the ground`" for vengeance against the offender;
whilst the blood of Him, who cried--"`Father, forgive them,
for they know not what they do,`" cleanseth from all sin, and was shed for many,
for the remission of sins,--yea, for all that repent, believe,
and obey the gospel in the secret of their hearts revealed,
which is "`the power of God unto salvation.`"
But although ready to shudder at the prospect before me, I feel strengthened to proceed,
so far as I may rightly do, from a belief that the work in which I am now engaged,
is prompted in mercy, and will not be in vain, peradventure to myself, if not to another.
For if permitted to finish it, I shall have had another opportunity afforded,
even at this late hour,
for repentance,--a truly great and blessed privilege to every sinner.
And how much more shall I owe unto my Lord, if in the course of a diligent search,
it should please the "`faithful witness,`" in
condescension to discover to the view of my mind sins,
which, through the subtle working of the grand adversary,
have been partly hidden and imperfectly repented of.

For some time after the separation of our family before hinted at, had taken place,
my attention was fully occupied; until the party, who had taken to the business,
became acquainted with its usual routine.
The master of the house, holding a post in a public office under government,
which required his regular attendance, was absent every day until after dinner;
and as his family consisted only of very young children,
I had no associates but among the servants;
whose example did not fail to have in many things a baneful
influence on my thoughtless mind,--though at the time
imperceptible,--and the consequences unregarded.
Yet I was at times desirous that a situation in a well conducted family,
with whom in the days of my parents we had been intimately acquainted,
would offer for me; which in all respects would have been much more guarded,
than that in which I was; but in this my hope was disappointed.

There was a merchant in the city, who had long shown much friendship for us;
on whom without any particular reason I kept an eye,
as one who was likely to befriend me.
He frequently called on business: and one day on perceiving him coming,
it occurred to me immediately, that his business was on my behalf.
This proved to be the case: for in a short time I was sent for,
and informed that he had obtained a situation for me,
on board a ship then lying in the Thames, fitting out for Oporto,
commanded by a respectable man, a lieutenant in the navy, then on half pay;
she belonged to some merchants with whom he was connected in the import trade.
This offer was at once accepted on my part,
and I suppose that any other would at that time have been the same,
without regard to choice;
as I do not remember that one occupation had any preference with me rather than another.
I am not aware that any attempt was made to dissuade me from this undertaking,
by those whose sentiments would have been regarded, or by any other person;
so that the needful preparation was immediately
made for this unexpected change of station.

I should not feel easy without noticing in this place, for the benefit of others,
the manifold temptations to which young people are necessarily exposed,
when brought up to trades similar to that in which I was then employed.
From the nature of these trades,
there is scarcely a probability of escape from insensibly
falling into habits (much more readily acquired than shaken
off,) of tasting different kinds of wines and strong liquors,
which too often leads the way to intemperance.
The injurious effects of these practices, and of such exposure at an early age,
having been felt and witnessed by myself,
make me the more desirous to warn others against the business.

But a short time elapsed before I went on board the ship, which, in a few days,
proceeded to Gravesend.
The weather being rough, we were detained a day or two at the Nore;
and after reaching the Downs,
we were again hindered by boisterous and contrary winds for more than a fortnight.
From these and other detentions at sea,
the ship was too late to procure a cargo in Portugal,
which resulted in our wintering in the Douro; so that before we reached London again,
the voyage had occupied fully six months.
We were but a short time in the river, before we sailed again on the second voyage;
which was completed in less than half the time of the former.
During our stay in England, my time was taken up in learning navigation;
so that I had scarcely any opportunity of seeing either my sister,
or any of our old friends.
Whilst I belonged to this vessel, we had a providential escape from fire;
the danger was greatly increased by the river being frozen at the time:
but with prompt assistance from other ships then in the Thames, the ice was broken,
and sufficient water procured to extinguish the flames, before much damage was done.
By the time our second voyage was completed,
I had become tolerably accustomed to the situation;
and although we had experienced some rough weather,
I was reconciled to it as much as could be expected.

Soon after returning to London the second time,
I found that some of my friends had succeeded in procuring for
me the station of midshipman on board a ship of war,
then commissioned at Plymouth, and preparing for the cruising service.
This affair was brought about by an intimate friend of my late dear mother,
whose brother was appointed to the command of this vessel;
and it was considered by those who felt interested in my welfare,
as an important foundation-stone,
upon which my nautical career would at a future day be established.
The change, however specious in appearance at the time,
was to me but as an introduction to a school, which is not often equalled,
and but seldom surpassed for vice and immorality.
After the necessary equipments were provided, I took leave of my youngest sister,
who was still at Putney at school,
and of some of those with whom we were the most intimately acquainted,
and I joined the ship at Plymouth.
The situation I had now obtained,
was for some time much less comfortable than the one in which I had been engaged.
Before, I had been placed amongst only a few strangers,
but now the crew altogether consisted of many;
and being an entire stranger to naval etiquette, my situation was dull and mortifying;
particularly as from my not having completed my fourteenth year,
all those of the officers with whom I could use freedom,
were several years older than myself.
It was not long before we left the harbour, and sailed for the Isle of Man station.
This was a stormy and dangerous passage, in which, through Divine mercy,
we were favoured to witness a marvellous preservation from shipwreck,--the
dawn of day discovering to us just in time the small island of Grasholm;
towards which the vessel was drifting in a direct course,
and already within a short distance of the breakers.
We were lying to at the time under two or three storm sails;
but there happily being room to wear clear of the rocky crags,
the danger was soon left behind.
After remaining in these parts about fourteen months,
visiting alternately the coasts of Scotland, Ireland, and Wales,
and putting into a variety of harbours for provisions and water, as occasion required,
we reached Liverpool in a leaky condition.
Here we expected to be repaired:
but instead of being permitted to go into the dock for that purpose,
instructions were received from the Admiralty to procure an
extra pump and proceed immediately to Plymouth;
this, although attended with much risk, was at last accomplished in safety.

Whilst in this harbour,
interest was made on my behalf with an admiral of
considerable estate and influence in the neighbourhood,
with whom in former days some of our family had been personally acquainted.
Through this medium, I was in a short time received on board a ship of the line,
then bearing the flag of a rear-admiral.
This advance, under such patronage, was considered to hold out a promising aspect;
but whilst it seemed to pave the way to promotion,
it opened at once a door to an extensive range of acquaintance with officers on board,
whose circumstances in life enabled them to deviate with less
difficulty than myself from the path of virtue;
whose example I endeavoured to follow,
until nothing but the want of means prevented my going
still greater lengths than the worst of them.
Whilst in this ship, when about sixteen years of age, having been unwell,
and probably led to reflect a little on that account,
I was made sensible of a Divine visitation being extended to me:
disclosing with indubitable clearness the vanity and emptiness of every earthly station,
tarnishing the pride and glory of this perishing world in my sight; and which,
though little understood and less regarded at the moment, has since,
at different periods of my chequered life, been brought to my remembrance,
by Him "`who declareth unto man his thoughts,--who maketh the morning darkness,
and treadeth upon the high places of the earth,--the Lord,
the Lord of hosts is his name.`"
When this occurred, although then entered into the bond of iniquity,
I had not launched so fully into its dreadful abyss,
as was afterwards most lamentably the case;
and from what I have since witnessed in unutterable mercy,
of the strength and power of redeeming love, a belief is induced,
that if this warning voice,
then sounding in the secret of my sinful heart,--"`Behold I stand at the door,
and knock,`" had been hearkened unto, and waited upon, my footsteps, even mine,
would have been conducted from the horrible pit to which they were fast verging.

I continued nearly six years in the navy:
but were all the changes from ship to ship enumerated which took place during that time,
and the great variety of incidents which befel me,
they would swell this narrative far beyond the limits intended:
whilst however I am desirous of avoiding the error of gratifying self,
or merely amusing others,
I beg to be preserved from a greater,--in omitting any thing tending in the
slightest degree to make known the aboundings of that wondrous goodness and mercy,
which followed me all along through an unparalleled
course of presumptuous and unrestrained liberty.
It may therefore suffice for me to say,
that notwithstanding the many and great dangers I was exposed to,
and the hardships and suffering I had to endure,
through all which I was preserved and sustained
in a manner at this day inconceivable to myself;
yet none of these things were sufficient to soften the rocky heart,
or bring me to a sense of my lost condition: for whether on board or on shore,
in harbour or at sea, or in whatever country,
if I could meet with associates prone like myself to evil,
I was always ready to hasten with them to it, either in word or in deed.

An expected war with a foreign power had occasioned an
unusually large fleet to collect at Spithead;
but after a time, the differences being adjusted,
the ships were dispersed to their respective posts,
and that to which I belonged was paid off.
She was commissioned again the next day as a guard-ship,
and I have no doubt that I might have resumed my station as one of her mates,
had I made application: for with all my private failings as a poor sinful creature,
my public character had not suffered in any of the ships in which I had served,
but rather the contrary;
for my pride and presumption had often prompted me in moments of extreme danger,
in a daring manner to take the most hazardous post, even when duty did not require it,
or warrant the risk.
But instead of applying to be re-instated in my former birth,
I remained on shore in pursuit of sinful gratifications with increased avidity;
and going up to London, so much time elapsed before my return,
that I never afterwards attempted to procure a situation in the ship I had left,
or in any other.
In this way I left the service altogether; and would I could say,
that I left the service of sin at the same time:
but I had not then filled up to the brim the measure of iniquity.
For some time I remained without any employment;
at length I concluded to go to Canterbury,
without any other motive than what arose from examining the names of places
to which stage coaches ran from the inn at which I was then stopping;
and as I knew nothing of that place,
it is very probable that I thought no person there knew any thing of me.

I now found the disadvantage of not having been regularly brought up to a trade;
and although desirous of getting into some employ,
no matter what,--yet for want of this knowledge, I was alike unfit for all;
and I could not bear the thought of making my forlorn situation known
to those who had been the friends of my childhood,
amongst whom there is no doubt but helpers would have been found.
As my means became every day more scanty, I was at length reduced to complete poverty;
and after many fruitless attempts to procure a livelihood,
there seemed left to me no other alternative,
than that of entering as a volunteer into the army:
this plan was accordingly adopted without delay.

I must now digress awhile from the narrative, to mention a circumstance,
which the facts just related have afresh awakened and impressed on my memory.
Towards the latter part of the time of my being in the navy,
it was suggested to my lost and bewildered mind, by the subtle destroyer of men,
that nothing short of making away with myself,
could extricate me from the difficulties by which I was surrounded,
and shelter me from shame and disgrace;
and the method of its accomplishment was at seasons hinted at.
But,--blessed be the name of the Lord God of heaven and earth forever! his
invisible arm of merciful interposition preserved me from this dreadful snare;
and in the greatness of his love and strength he hath at this distant period,
put it into the heart of his unworthy creature to record his mighty acts,
to his praise and to his glory, with humble and reverend thankfulness.
Greatly do I desire,
that if this relation should ever fall into the hands of any
poor sinners and servants of the cruel taskmaster,
as was then my lot,--that such may be hereby strengthened and
encouraged to look unto the Lord their God for help,
even though they may be plunged into the very gulf of despair:
for "`his compassions fail not,`"--they are new every morning;
his tender mercies are over all his works; and he will give power to the faint,
and strength to them that have no might of their own, to resist this,
and every other temptation of that wicked one, who was a liar from the beginning.
