== Chapter III.

[.chapter-synopsis]
* Nimeguen
* Many Dangers
* Attacked by Fever
* Hospital Treatment, Heavy Mortality Among the Sick
* Disasters of the British Army
* Retreat to Bremen
* Returns to England

As the winter approached,
the health of the troops began to fail to an alarming and awful extent,
from exposure to cold rains which fell almost daily;
and yet we were compelled to keep the field,
being constantly on the retreat before the greatly superior force of the enemy.
As we drew near the walls of Nimeguen, the British forces made a stand,
probably to afford time for preparing a floating bridge across the Waal,
to secure our retreat behind that river.
At the same time, the French used every effort in their power to intercept our retreat,
by endeavouring to get between us and Nimeguen,
which from the strength of its fortifications was
capable of affording a cover for several days,
or until our army had passed in safety over the bridge.

The last two or three days the contest between the two armies became more severe,
by the continual arrival of fresh divisions of the French at this point:
on the last day the cannon scarcely ceased to roar from sun-rise to sun-set.
The regiment to which I belonged, was ordered on the reserve with three others;
two of which were British, and the third Hanoverian.
As the cannonade increased, the first regiment of reserve was called upon,
in two hours after the second was summoned, and by eleven o'clock in the forenoon,
the third.
The direction from which the sound of the conflict issued,
left no doubt that it was rapidly approaching the ground on which we stood; and although,
as the last reserve, we had not been ordered to march, yet our tents were struck,
and every thing prepared to move on the first alarm.^
footnote:[Our expedition landed without any tents,
but a supply was furnished about six weeks afterwards,
I think whilst we were encamped on the plains of Breda.]
I had been going about in the wet for several days previous,
without the practicability of obtaining dry clothes;
and this day being colder and more rainy than usual,
with the increased exertion necessary on account of the
threatening aspect of things close upon us,
might hasten an illness, the foundation of which had already been deeply laid,
and which began with shivering fits,
just in the interval of waiting for the expected
courier to call us to the field of slaughter.

About three o'clock in the afternoon, a light dragoon arrived with a dispatch,
but instead of its hastening us to the scene of action,
it proved to be an order for us to join the rear of
another regiment then retreating towards Nimeguen.
Our army, after sustaining for many hours with great loss the unequal combat,
was at length compelled to retire.
Thus were we preserved when on the very brink of danger,
in a manner as unlooked for as unmerited, from sharing in the disasters of a day,
in which much human life was wasted,
and which entailed great suffering and distress on many who survived it.
After we had moved forward two or three miles,
the coldness and shivering I had previously felt
were succeeded by violent heat and fever,
and my throat seemed almost closed up.
For several days I had found swallowing very painful and difficult,
from its extreme soreness,--but had taken little notice of it.
In this condition I was still able to keep up with the body of the regiment;
but after entering the gates of Nimeguen,
from the frequent stoppages which took place in the miry streets of the city,
owing to accidents constantly occurring with the floating bridge,
occasioned by the fire of the French upon it,--I became
more and more affected with something of the cramp kind,
which nearly prevented my standing upright.
As the night drew on, it became colder, and my pain increased,
but I kept going on as well as I could; at length we came in sight of the bridge,
when we were again stopped for some time.
I was near the colours of the regiment, and an officer who carried one of them,
made some remarks to me about the bridge; but feeling myself much worse,
I told him I should never go over that bridge.
He endeavoured to cheer me up, saying, that I should go over that and many more;
but however, my assertion proved correct, for before the line again moved forward,
I had left it, and was leaning against the wall of a house,
no longer able to proceed from increased illness.

In this position I remained for some time;
and after having painfully beheld the last of the rear
of the regiment pass on and leave me behind,
there seemed to be no hope left,
as the only men in the world from whom I could
expect a helping hand were all out of sight.
But, although apparently forsaken by all, and left to perish unseen and unknown,
yet that ever-compassionate Arm, which had so often been with me in extremity,
was again stretched out,
and did not long allow me to remain in this deplorable condition; but in adorable mercy,
my gracious Lord was pleased to put into the hearts of some of
the regiment who knew the real cause of my absence,
to send two of the men back to endeavour to find me out,
and render every assistance in their power.

As I had not gone from the place where I stopped, they had no difficulty in finding me,
although it was by that time nearly dark;
but as I could not possibly go forward to the regiment,
they at last concluded to leave me in the hands of a picquet of cavalry,
which was left to cover the retreat of the army through the city.
Having helped me to the place, and left me in charge of the picquet,
they made off with all haste to overtake their companions.
Here the wife of a soldier gave me some ground pepper mixed with heated spirits;
and although, from the state of my throat, I could scarcely swallow the fiery mixture,
yet it proved useful, considerably relieving the pain in my stomach,
and renewing the general warmth.
As it was expected that the enemy would attack the batteries in the night,
which however was not the case, although they kept up a heavy firing,
I was helped into a loft to be out of the way; here I remained until the morning,
and was then assisted on board of a galliot, provided for the reception of those, who,
like myself, were disabled by sickness or other causes.

The hold of this vessel was filled with as many people as could lie close to each other:
they were in the various stages of a violent epidemic disorder,
and from the heat occasioned by so many being crowded together,
the air was very oppressive, and difficult to breathe.
Two other galliots of a similar description, proceeded in company with us up the river,
in hopes of getting round a neck of land, at which the Waal and the Rhine unite.
But although considerable exertions were made by the sailors,
aided by such of the sick as were at all able to stand, of whom I made one,
they had not succeeded in warping round the point,
when a party of French hussars made their appearance on the shore.
It was fully expected they would endeavour to prevent our escape,
by opening a fire with cannon;
but before they had time to bring any near enough to bear on us,
we had got fairly into the current of the Rhine, and were soon beyond their reach.
Being much exhausted I went below,
but soon became very ill from the closeness of the place.
Whilst under this and other distressing circumstances, both of body and mind,
one of our companions who lay next but one to me,
was removed by death from all his troubles;
and although none of us could expect at the time,
but that a similar fate would in all probability soon overtake us,--yet,
in my own case at least, notwithstanding I was worn down with fatigue and sickness,
and without a glimpse of any thing to make life any longer desirable,
except the fear of death,--still nature could not but feel appalled,
when the dead body of a fellow-sufferer was dragged past,
to be taken on to the deck of the vessel.
As the evening came on, I became much worse; and although the night was cold and frosty,
I thought it better to get on deck, where I could breath more freely,
rather than remain any longer below:
accordingly three or four of the people helped me up,
for I was now so faint for want of support, that I had scarcely any strength left.
I remained on deck all night and got a little sleep; in the morning,
the cold compelled me again to go below, but I felt a little refreshed,
and better able to bear the closeness of the place, keeping near the hatchway,
where there was a greater circulation of air.
In two days more we arrived at Rhenin, a town close to the bank of the Rhine,
where an old monastery was fitted up as an hospital for the British sick.

Sometime after reaching this place,
a person came on board the galliot to see if
there were any amongst the newly arrived sick,
with whom he was acquainted.
He came down below, and after looking round was about going away,
when I made what effort I could for some one to stop him.
He had looked at me amongst the rest,
but I was so much reduced and altered in appearance that he had not recognised me,
but passed by, although he had once known me very well.
When brought back, he soon recollected me,
and feelingly expressed great regret at finding
his old acquaintance in such a weak condition.
He had been a patient in this hospital himself, and when restored to health again,
being found an active and useful person,
he was retained as a ward-master for the benefit of others.
Having had the fever, he was tolerably well acquainted with the best mode of treating it;
and soon after finding me, he administered a small quantity of strong cordial,
which had the desired effect for a short time, by enabling me to get on shore.

With his assistance I was conveyed to the hospital,
where he soon procured one of the surgeons to examine me,
and being very desirous to render every assistance in his power,
he suggested to him the propriety of giving some particular medicine,
which had often proved useful in bad cases; to which the surgeon replied,
not aware that I heard all that was passing between them,
'he will not want any thing long.' By this it was
evident that mine was considered a hopeless case;
which could not be wondered at, the disorder having been so fatal,
that those who had recovered were said not to average more than one in fifty;
and as my attack had been so long neglected, the conclusion was reasonable,
although it did not prove correct.
In a few days I was so much recruited as to be able to walk about the town:
but it was a distinguishing characteristic of this complaint, that having once had it,
was no security whatever against a second attack,--and
that those who got well through it the first,
or perhaps the second time, were frequently its victims on the third encounter.
I found by experience that this report was not without foundation,
for instead of being fully restored to health again,
as for the first few days seemed probable, the disorder returned a second time,
and with much more violent symptoms.

As a state of high delirium soon came on,
I was but a short time sensible of what transpired,
after the application of a large blister; except the workings of a terrified imagination,
some of the impressions of which, even at this distance of time,
are not wholly obliterated from my memory,--so deeply and strongly were they engraven.
From the treatment which followed when no longer delirious,
the disorder must have been of the nature of typhus,--
as at one time a liberal allowance per day,
of equal parts of brandy and port wine was given me, as hot as could well be taken.
How long this continued I am not aware,
but I was confined to my bed for such a length of time,
as to be wholly unable to move in any direction from extreme weakness;
and so generally was this the case in this disorder,
that a man was appointed in every ward to go round occasionally,
to turn from one side to the other,
such of the patients as were incapable of turning themselves.

I was at length brought so near the brink of the grave, that, to all appearance,
no alteration for the better could be expected.
I am not aware that I had even a wish to live;
but my mind was so reconciled to the prospect of death,
which then seemed near and inevitable,
that I had given my watch into the hands of the person who had visited the galliot,
with a request, that he would inform my family where I had ended my days.
Indeed, when some expectation of recovery was at last held out,
I could not help looking forward with a feeling of regret,
to the probability of having again to encounter the series of hardships and distress,
to which I should unavoidably be subjected.

As I regained a little strength, I began to take notice of the state of things around me;
and having daily heard a noise like that of a carpenter's shop,
I now ascertained the cause to be the nailing up of the coffins, each day,
of those who had died in the last twenty-four hours; and I found that the dead-house,
or place where the dead were deposited previously to interment,
when taken out of the wards, being opposite the windows of the room I was in,
afforded full opportunity for my beholding the striking and affecting scene,
which could not fail to excite feelings of horror and dismay,
in one so much enervated by the very disease,
which I now witnessed to be so fatal to others.
The average number of deaths was twenty-seven in a day and night;
but sometimes the number so increased,
that the Dutch could not furnish coffins sufficient for the demand of the day;
and then the method of sewing up the bodies in the bedding they had occupied,
was resorted to.
Several waggon loads of bodies were carried off every afternoon for interment.^
footnote:[The accounts of the deplorable treatment of the sick,
and of the disasters of the British army in their retreat to Bremen,
as given in the Annual Register of 1795,
more than confirm the description of the author of this biographical sketch.]

When able to walk about the room with the assistance of my stick,
it happened that the regiment to which I belonged,
was quartered in a village about two miles from the bank of the Rhine,
opposite to that on which the hospital stood.
Some of the officers came over to ascertain for themselves,
whether any of the missing from their regiment were amongst the sick;
at length they came into the ward where I was, and the second in command,
with whom I was well acquainted, being with them,
I requested his help to get me liberated from the hospital,--telling him,
that I had no chance of becoming thoroughly well whilst in it,
and of the danger to which I was constantly exposed of having another relapse.
He immediately applied to some of the medical staff on duty,
and conducted them to me through the wards; but it ended in his informing me,
that the doctors could not suffer my going out until farther recovered,
as I was quite unfit for exposure.

Not knowing how long I might be detained,
I was now determined to make my escape on the first opportunity;
and the next day being remarkably fine, I walked out two or three times into the air,
though with much difficulty.
The following morning I met with a person belonging to the regiment,
who was going to join it again the same afternoon; and as we were well acquainted,
I did not hesitate to disclose my intention of
quitting the hospital in a clandestine manner,
and resolved to accompany him, if possible.

I returned again to the hospital as at other times; and in the afternoon,
as if going to take another walk, I proceeded to the river side;
and the ferry boat being just ready for setting off, I got into it undiscovered,
and passed the Rhine,
arriving at the village of Kesterne soon after dark the same evening,
without taking cold, although the river was thickly frozen over,
and a passage cut through the ice,
to allow the ferry boat to cross backwards and forwards.
From this time I rapidly gathered strength,
and at the end of a week was so much recruited,
as to venture back to the hospital to see how those fared, whom I had left behind;
at the same time, it is very probable, to show how I had fared myself;
without any fear of being detained,
as I was evidently much stronger than when under their roof.

To lessen the fatigue, I procured a horse for the excursion,
and proceeded accordingly towards the river side.
The risk I then ran, however unwarrantable,
afforded me another opportunity of seeing the effect of
a renewed attack of this dreadful disorder,
upon a Scotch sergeant of the Highland watch, who had had the fever twice,
and both times recovered from it.
He was a very stout man, and when I left the hospital,
appeared in perfect health and strength.
In the interval of my absence, he had been seized with it a third time,
and when I saw him, had nearly finished his course; he was speechless,
and survived but a short time afterwards: I think this last time,
he was ill only three days.
Although I escaped any farther infection,
yet I was punished for my temerity before getting back again to Kesterne.
After crossing the river in the boat,
I had to pass through a small sheet of shallow water which had been frozen,
but was then broken up by the loaded waggons that passed that way.
On getting up to it, I found it in a half frozen state,
the old ice not being sufficiently strongly united again to bear the horse,
which refused to pass it; and on my urging him forward, he lay down with me in the water.
It was with difficulty that I could extricate myself from him,
and it is doubtful whether I should have succeeded,
without the assistance of another person then at hand.
In this wet condition I had a long distance to go, in a keen frosty night,
in an open waggon, which the day following threatened a renewal of my illness;
but by the timely use of medicines, I was favoured, not according to my desert,
to escape without any serious indisposition.

In looking back at the marvellous manner in
which I was sustained through all this conflict,
and again restored as one brought back from the dead,
I cannot avoid adverting to that period of my illness,
when my mind felt so reconciled to the prospect of death, as before-mentioned;
and I now fully believe, from what I have since been mercifully favoured to experience,
that so far from being in any degree prepared for such an awful event,
a deceptive feeling must have been superinduced by the
state of torpor and insensibility in which I then was,
and which totally benumbed any better feelings and desires as to the future.
To this may be added a predominating fear, of having to endure more of those sufferings,
of which I had had no small share; which,
the probability of being again restored to
health seemed to banish every hope of escaping.
Truly awful is the thought which this view of my then lost condition occasions,
when I contemplate the woe and misery which must have been my eternal portion,
if unutterable mercy and long-suffering had been withdrawn;
and if the soul had been required of one,
who had witnessed no repentance towards God the Judge of all,
except what at times the fear of punishment had extorted;
and who was a stranger to that saving faith in the Lord Jesus Christ,
as the "`Lamb of God that taketh away the sin of the world,`"--without which,
his precious blood would have been shed in vain
for me:--I should thus have died in my sins,
which unrepented of, would have followed after to judgment,
in terrible array against my guilty soul--and yet when
my end was apparently so near and inevitable,
if such questions as are frequently proposed on the like occasions had been put to me,
I have little doubt, but satisfactory answers would have been returned,
as to my belief and hope in the essential truths of the gospel.
But alas! this would have been from hearsay and traditional report,
and not from any heartfelt saving knowledge of my own:
for it is now plain to my understanding,
that no man can have saving faith in Jesus Christ, who is unacquainted with,
and does not walk in, the light of that Divine Spirit,
which is so justly styled the Spirit of faith.
It is through this alone,
that the death and sufferings of Christ and his whole sacrifice for sin are availing,
and truly applied to all those, who through faith lay hold of him,
the true Light and Saviour of them that believe in his inward and spiritual appearance.
These can say to others from sensible and blessed experience,--"`Behold the Lamb of God,
that taketh away the sin of the world they have received the atonement by Him,
and they reap the glorious fruit and benefit of his death and suffering for sin,
by the sacrifice of himself, and of his resurrection and ascension;
in that he ever liveth to make intercession for those,
who are thus willing to come unto God by him.
A man may yield an assent to all the great and solemn
truths of Christianity,--the miraculous birth,
holy life, cruel sufferings, ignominious death,
and glorious resurrection and ascension of our blessed
Redeemer;--he may believe in the abstract,
in his inward and spiritual appearance in the hearts of mankind by his Holy Spirit;
and yet he may fall short of the prize immortal,--unless he comes to
witness the saving operation of the Holy Spirit in his own heart,
and to know thereby, through faith in it,
a purifying preparation for the kingdom of righteousness, peace,
and joy in the Holy Ghost.
How can I sufficiently appreciate or declare the extent of the endless mercy,
which suffered me not to perish in the midst of my sins,
when so many were swept away by the same pestilential disorder?

After having mentioned the facts connected with my sickness and recovery,
it seems only due, however feeble on my part the effort,
to endeavour to commemorate such gracious dealings with humble gratitude and reverence;
earnestly desiring that no motive whatever may be
allowed to prevail with me for making the attempt,
but that of promoting the glory and honour of the great name; that others may know,
and fear, and believe in the all-sufficiency of that power,
which hath "`shewed me the path of life,`" and which alone can
bless for their instruction what has been written,
to press the necessity of contending for that
saving faith "`once delivered to the saints.`"
Without it, all religious profession is a dream, a shadow, and a doubt; but with it,
a glorious reality;--yea, "`the substance of things hoped for,
the evidence of things not seen,`"--even the salvation of the soul,
through Christ Jesus our Lord.

Whilst the severity of the winter greatly facilitated the operations of the French army,
by enabling them to cross the frozen rivers without difficulty,
and at almost any given point;
so it contributed most effectually to harass the
diminished numbers of the retreating British forces.
It was the more felt from the scarcity of provisions,
occasioned by the inhabitants withholding from us every supply,
in compliance with the intimidating threatenings of our victorious enemy;
so that we frequently could not procure needful food even for money:
whilst our opponents were supplied by the terrified householders at free cost.
In some places,
the inhabitants openly declared they were withholding
their provisions for the supply of the French,
aware of the cruel treatment they should witness at their hands,
if unable to provide for them when they arrived;
although they considered the British to be their friends, and were well treated by them.

Before I left the hospital at Rhenin, the French had approached so near,
that the windows of the place frequently shook with the discharge of their artillery.
Sometimes a waggon load of the wounded English would arrive at the hospital; when many,
whose recovery would in a healthy situation have been speedy and almost certain,
were carried off in a few days, by the infectious disorder which prevailed at the place;
and from the disastrous issue of the campaign, however greatly this was to be deplored,
it could not be avoided.
We were not long permitted to remain at Kesterne,
before being obliged to move towards the north of Holland;
when the town of Rhenin with the hospital fell into the hands of the enemy.
Soon after this event, the frost became more intense;
and the Dutch could no longer make graves for the interment of the dead,
but piled the coffins upon each other in great numbers, until a thaw took place.

Although my strength was considerably recruited before we left Kesterne,
I was yet very unequal to the subsequent exposure,
having to pass great part of the first night in the frost after leaving that place:
but although I slept in a cart with a canvass tilt, I do not remember taking cold,
or otherwise experiencing any injurious effects, either then or afterwards,
beyond what might have been expected from great fatigue and improper diet,
there being at that time little to be procured,
but coarse black bread and ardent spirits.
During this harassing march, at such an inclement season,
many of the poor men lost parts of their toes,
by imprudently sitting down in the frost for too long a time at once,
and from not having their feet properly protected.
I can well remember having been so wearied myself,
as to come to the determination to sit down,
and risk the consequence,--although fully aware of the
danger of falling asleep in such circumstances;
but I was prompted by a secret impulse to resist the inclination,
although nearly overcome with fatigue: then after moving about awhile longer,
I have again begun to give way, but still struggled on.
And when at last, it seemed as if human nature must give up,
the thought of relations in England, as if I had had a home, would cross my mind,
and stimulate me to try again in hope, until something has occurred, to bring relief,
and shelter, and repose.
Perhaps, if more food could have been procured, the propensity to sleep,
which exposure to cold occasioned, would have been irresistible.

In this manner the winter wore away:
but at length we got so far out of the reach of the French,
as to allow a longer space of time for rest at each place we arrived at.
The cold weather continued, until we reached the banks of the river Weser;
when the retreating wreck of our army was unexpectedly cheered with a
sight of the mast-heads of the British fleet lying off Bremen-leke,
and waiting to convey it from the shores of the Continent;
where it had witnessed so much distress, wasting,
and destruction,--to be attributed much more to hardship, fatigue, and pestilence,
than to the sword of the enemy, although greatly superior to us in strength,
and possessing local advantages, of which we were wholly destitute.^
footnote:[It is stated in the Annual Register,
that on the arrival of the British army at Bremen,
the kind and cordial treatment they received from its inhabitants,
was strongly contrasted with the hard-heartedness and hostility of the Dutch.
'It was something like a dream,' says a witness and partaker of their
sufferings:--'we who had lately been so buffeted about,
driven like vagabonds through frost and snow over the wilds of Holland; and who,
in our greatest extremities when we asked for any thing to refresh ourselves,
with the money in our hands,
were answered only with a shrug of the shoulders 'nothing for the Englishman!
'--now to be seated in the most elegant apartments,--servants attending,
ready to anticipate every wish,--beds of down to repose upon,
without being disturbed in the morning by the thundering of cannon,
or the usual alarms of war.
They omitted nothing that could contribute to either our ease or pleasure:
and a great number of the inhabitants accompanied us out of the town,
and showed us every respect.--Annual Register, 1795, p. 55, 56.]

[.offset]
+++[+++__Here ends the Author's biographical sketch of his own life.__]
