== Chapter IV.

[.chapter-synopsis]
* Sails with His Regiment to the West Indies
* Remarkable Preservation
* Serious Impressions
* Returns To England
* Becomes Convinced of Friends' Principles
* Received into Membership in 1797
* Settles in Business and Marries
* Acknowledged a Minister in 1816

It is matter of much regret, that for many years subsequently to this period,
no biographical memoranda appear to have been made by our dear father;
and it is impossible at this distance of time,
to supply any minute details of that important
change in his sentiments and manner of life,
which occurred shortly after the time to which the preceding narrative refers.

In the autumn of 1795,
he obtained a commission in a regiment destined for the West Indies,
and sailed with the expedition appointed to this service, under Sir Ralph Abercrombie.
After a most stormy and disastrous passage they were once in sight of the islands,
but were driven back by a dreadful hurricane: in which several of the vessels foundered,
and great numbers of the troops perished.
A malignant fever also raged with fatal violence among the crews of the fleet,
and in the ship in which he had embarked, no less than twenty-seven fell victims to it,
within a short space of time.

Our dear father experienced some remarkable preservations at this time,
to which he often referred afterwards,
as the merciful interpositions of an overruling providence in his behalf: of these,
one in particular appears to have arrested his attention.
The vessel in which he was appointed to sail,
and which was considered a remarkably fine one, was exceedingly crowded,
from the preference given to her by many of the officers.
One morning after they had been some weeks at sea,
a collier (being one of the vessels hired as transports,) coming alongside,
he proposed to one of his friends, that they should go on board of her.
His fellow-officers ridiculed the idea of preferring an
old collier to the noble ship in which they were;
but he and his friend persisted, and transferred themselves to her.
The same evening a hurricane arose,
and the vessel they had quitted was never heard of afterwards.
In connexion with this period, he once remarked to a friend,
on being questioned as to the means made use of in the Divine hand
for effecting "`a new birth unto righteousness`" in his heart,--that
he could not remember any outward means having been employed,
unless, indeed, he might except a storm at sea,
during which his mind was deeply affected; and when,
under a feeling of his own lost condition by nature,
he was mercifully enabled also to see the remedy,
and the entire spirituality of the Gospel dispensation.
In accordance with this feeling,
he remarked,--'I was at this time convinced of Friends' principles,
they being neither more nor less in my estimation, than pure Christianity.
I remember when the Friends visited me on my application for membership,
I told them I was convinced at sea; for I verily believed, in looking back,
that this had been the case:
no human means were made use of;--it was altogether the immediate
work of the Holy Spirit upon my heart.' Under these feelings,
he became dissatisfied with the military profession, and resolved that,
if permitted again to reach the shore,
he would endeavour to lead a life of more circumspection,
and which should tend to the glory of that Being,
who had thus so mercifully visited him by His free grace.
To this resolution he adhered:--he quitted the army in the early part of the year 1796.

For some time subsequently, to this event,
he became an inmate in the family of his eldest sister, Barbara Hoyland;
who was settled in the neighbourhood of Sheffield, in Yorkshire.
She had married a member of the Society of Friends;
and before the period of my father's joining them,
had herself become convinced of their principles, and united herself to them.
While residing with these near relatives,
his mind became renewedly impressed with the importance of Divine truth;
and in the course of a few months, he was led openly to espouse those views of it,
of which in after years, he was an unflinching advocate.
The little meeting which he attended in the early part of his religious course,
that of Handsworth Woodhouse, was usually held in silence;
and he has been often known to refer to some of those solemn seasons,
as times of peculiar instruction to his mind;
in which the power of the Lord was sensibly felt, and his Truth revealed.

Being made a partaker of the great privilege
enjoyed by those who are of the flock of Christ,
in being enabled to distinguish between the voice of
the Good Shepherd and that of the stranger,
he was earnestly desirous that obedience should keep pace with knowledge.
He waited patiently upon the Lord for instruction in his various stoppings;
and being brought into a state of deep humility and prostration of spirit,
he was made sensible, that the only path in which he could walk with safety,
was that of self-denial.
Much mental conflict was at this season his portion;
but peace was only to be obtained by an entire surrender of the will:
and in conformity with what he believed to be required of him,
he adopted the plain dress.
He once recounted to a friend in lively terms,
the trial it was to him to put on a different
hat to that which he had been accustomed to wear;
especially as in going to the meeting at Woodhouse,
he generally met a number of his former gay acquaintances,
whom he crossed on the way to their place of worship,
which he had himself previously been in the practice of attending.
In this instance, it was hard to appear openly as a fool before men;
he thought if his natural life might have been accepted as a substitute,
he would gladly have laid it down:--but this was not the thing required.
He diligently examined his heart,
and believed he clearly saw his Master's will in the requisition;
and that it was a discipline designed to bring him into
a state of childlike obedience and dependence.
In great distress he cried unto the Lord for help;
and a passage of scripture was powerfully applied to
his mind,--"`whosoever shall confess me before men,
him will I confess also before my Father which is in heaven:
but whosoever shall deny me before men,
him will I also deny before my Father which is in heaven.`"
His resolution was immediately taken:--he put on the hat,
and with his mind staid upon the Lord, set out to join his Friends at meeting.
His difficulties vanished,--sweet peace was his covering;
and he was enabled experimentally to know the fulfilment of
that declaration,--"`greater is He that is in you,
than he that is in the world.`"

In the course of the year 1797,
he was received into membership with the Society of Friends; and about the same time,
he entered into business in Sheffield, in the seed trade.
To this novel occupation he applied himself with that energy and assiduity,
which characterized all his pursuits; and by the Divine blessing on his exertions,
he soon succeeded in obtaining a business fully adequate to his very moderate desires.
It was striking to some of those around him,
to observe how readily he adapted himself to this total change of habits;
and with what true content and cheerfulness he engaged in the
drudgery and toil of a retail shop;--the daily attendance in which,
rested for some years exclusively on himself.
He has been frequently heard to refer to this period of his life,
as one of great peace and comfort; and it appears to have been a time,
in which his experience of the reality and power
of Divine grace was deepened and enlarged.
It was his daily practice,
at those intervals when the attendance in his shop could be dispensed with,
if but for a few minutes at a time, to retire to a small apartment behind it,
and in a prayerful spirit to explore the contents of the sacred volume:
the light which shone upon many passages as he read,
and the clear and strong views of religious truth which
were then unfolded to his seeking soul,
were such, as greatly to confirm his faith,
and strengthen him to persevere in that strait and narrow path,
into which his feet had been so mercifully turned.
The study of many of the prophetical books of holy writ,
was at this time the means of great comfort and encouragement to him;
and the extensive and accurate knowledge of these parts of Scripture,
for which he was afterwards conspicuous, was then chiefly acquired.

It was his uniform practice, from his first commencement in trade,
to close his shop during the hours of worship on week days;
and though this must have required a strong exercise of faith,
at a time when his future support seemed to depend on his assiduity and exertion,
he was never satisfied to neglect the worship of Almighty God,
from the prospect of any outward advantage; and he has often expressed his belief,
that a blessing had rested on this sacrifice of apparent interest to duty.

Soon after settling in Sheffield, the acquaintance with our dear mother commenced;
and they were united in marriage, on the 13th of the Sixth Month, 1800.
She was the daughter of Thomas and Rachel Brady, of Thorne;
and her family had been connected with the Society of Friends almost from its rise.
Being a person of peculiarly mild and amiable disposition,
and fully devoted to the promotion of the views and wishes of her beloved husband,
she proved a true help-meet for him;
and their union was productive of much solid happiness to both.
The great delicacy of her constitution, at times involved him in much solicitude,
and seemed to give warning of an early termination of that domestic felicity,
for the simple pleasures of which, few, perhaps,
have ever possessed a keener relish than himself;
but their union was mercifully protracted to the lengthened term of thirty-two years:
through all the vicissitudes that were permitted to attend them,
she evinced that deep and devoted attachment,
which led her cheerfully to forego every other enjoyment,
and cordially to unite in every step which he felt called upon to take,
however great the sacrifice it involved to her gentle and retiring nature.
She may be said to have possessed pre-eminently the ornament of a meek and quiet spirit;
and notwithstanding the great mildness of her disposition,
this was most happily tempered with a degree of firmness and moral courage,
by which she was enabled calmly to meet those dangers and difficulties,
before which a casual observer might have anticipated
that her gentle spirit would have shrunk.
As a wife and a mother, she has, perhaps,
rarely been surpassed in disinterested affection,
or in that constant and quiet consideration for those around her,
which led her habitually to forget her own liability to fatigue,
and cheerfully to put forth all her energies for
the promotion of their comfort and welfare.

Although my dear father for a series of years subsequently to this period,
was actively engaged in attention to business,
he was watchful to prevent its engrossing more of his thoughts,
than was consistent with higher duties.
As a tradesman,
he uniformly maintained an unblemished character for integrity and fair dealing;
and his daily course of conduct was characterised by an habitual
reference to a higher principle than that of mere interest;
which insured for him, in no common degree,
the respect and confidence of those with whom he was connected.
At length his health began to give way,
under the close attention which he had thought it needful to give to business;
and about the year 1809, he removed to a short distance from Sheffield,
for the advantages of greater quiet and more exercise in the open air.
This proved a great relief to him; but some time afterwards,
finding that his concerns in trade continued to increase upon him,
and demanded a closer attention than he felt satisfied to give,
he thought it his duty to relinquish a branch, and that a very profitable one,
of the business which he had so successfully established.
When his mind was once satisfied as to the path of duty in the case,
he hesitated not to yield a full and unmurmuring compliance; although,
with an increasing family dependent on his exertions,
and the comparatively slender means which he possessed,
this step must have required no small exercise of faith,
and in the eyes of the wise and prudent around him, appeared a doubtful one.
To him, however, it occasioned not one moment's regret;
and as he sought not great things for himself,
so the gracious and bountiful Master whom he served,
failed not amply to supply his every want,
and to grant him at the same time that blessing which maketh truly rich,
and whereunto no sorrow is added.

His attention was now a good deal turned to agricultural pursuits,
in the management of which he took great delight: indeed,
rural occupations and the simple pleasures of a country life,
harmonized peculiarly with his pious feelings;
and he loved to trace in the works and beauties of creation,
the goodness and power of the great Creator.
It appears to have been in reference to the step just adverted to,
that the following note, addressed to some intimate friends, was written:--

"`Forasmuch as it has pleased Almighty God,
in his unutterable mercy and great condescension,
in so eminent a manner to rescue my soul from
the paths of vice and inevitable destruction,
it seems incumbent upon me, in gratitude for such an unspeakable favour,
to endeavour as much as in me lieth, to make all the return I am capable of;
and as much as possible, through His Divine assistance,
to dedicate the residue of my days to so gracious and merciful a Creator.
I have at seasons for some years past,
when it has pleased the Lord to humble me and
make me sensible of my extreme unworthiness,
been made willing to make a surrender of my life
and my all to Him and His divine disposal;
and the query has often been raised in my heart,
what shall I render unto the Lord for all his benefits towards
me? As I have from time to time endeavoured to dwell near,
and abide in and under, the calming influence of His power, I have been led to believe,
that something sooner or later would be required as a sacrifice on my part:
and having for a considerable time past,
been fully convinced not only from my own feelings,
but from impressions made upon my mind by divers testimonies borne by exercised Friends,
of the necessity of my separating myself as much as may be from the
world and from the things of the world,--and having felt the force of
our Lord's declaration on the Mount,--'`Ye cannot serve God and
mammon`'--I am sensible that the time is at hand,
for me to put into practice what I believe to be an indispensable duty.
After having experienced such a wonderful and great
deliverance from the power of sin and Satan,
even as a '`brand plucked out of the burning,`' it cannot be
supposed that the remainder of my life ought to be spent in
the hurry and bustle of business of any kind,
and particularly in one which has so much increased as to
require more attention than I am capable of paying to it,
even if I had no claims of a higher and more important nature to attend to.
I have frequently thought of late,
that taking an active partner might answer the end intended,
and be a means of removing part of the weight and care from off my shoulders,
and at the same time set me at liberty to attend distant meetings,
and take exercise in the open air, which my health very much requires:
but having given this a solid consideration,
I have found that it would only be doing things by halves,--as
great responsibility and anxiety would still rest upon me:
it would seem also like making a reserve of the best of the sheep,
and the best of the oxen,
the bleating and lowing of which would be continually in my ears.
I therefore fully believe, that it will be most conducive to my present peace,
as well as future wellbeing, entirely to give up the trade I am at present engaged in,
and retire with my family into a small compass.
Not that I have acquired a sufficiency,
without doing something for a livelihood;--far from it.
I have still a prospect of maintaining my family comfortably, with care and industry,
leaving the event to Him who knows the thoughts and intents of the heart:
and though my income will be smaller than it is at present,
my expenses will be smaller in proportion.
It will no doubt be a matter of surprise to some,
that one who has so young a family should think of declining so prosperous a trade,
as many people, I believe, think mine is.
To these I answer, that I have no desire to accumulate riches for my children;
the blessing seldom attends it, and the baneful effects thereof are too often visible,
even in our society.
This is a matter of no small importance with me,--it is not a sudden thing.
I wish to consult my friends, and to take their advice in it.
It has been a long time growing with me,
and latterly has scarcely ever been out of my thoughts;
and not having frequent intercourse with my friends,
it seemed best for me to state in writing the principal grounds for taking such a step,
which might be readily handed to those most likely to impart counsel.`"

Perhaps the whole bearing of these impressions was never fully understood,
even by himself, till some years subsequently;
when he was called upon to make a still further
surrender of his will to that of his heavenly Father,
by quitting his native country, and the bosom of that society which he so much loved,
and going forth at the call of apprehended duty to sojourn in a strange land.
But to return to the period of which we have been speaking.
Though he had been necessarily much occupied with his own concerns,
he had not been a useless or inactive member of
the religious body to which he was united.
For many years he filled the office of overseer in the meeting to which he belonged;
and in discharge of the duties connected with it,
he was remarkable for his unwearied zeal and charity, his labour, his forbearance,
and brotherly-kindness.
The power of Divine grace having wrought so effectually on his own mind,
his benevolence extended to the whole human family.

For a number of years, the impression was strong upon his mind,
that he should be called to the work of the ministry;
but in connexion with this feeling he was long harassed with doubts and fears.
He was not rebellious, but his faith was weak;
he earnestly desired to have indubitable evidence that
such was indeed the will of his Lord and Master:
but He who knew the sincerity of his heart, graciously condescended,
in his own good time, to leave him without a doubt on this important subject.
He underwent deep baptisms of spirit; indeed such were his mental conflicts,
that his health materially suffered.
In referring to this circumstance at a subsequent period, he remarked to a friend,
that he regarded it as an especial blessing to him: for sometimes he slept little,
and frequently his nights were spent in prayer; at other times,
prayer being his last engagement previous to consigning himself to sleep,
he found in the morning,
(to use his own expression) his 'mind still covered with the same precious influence.
I think,' he added,' I at that time knew in measure what it was to
"`stand continually upon the watch-tower in the day time,
and to be set in my ward whole nights.`"
His mind at this time appeared to be particularly impressed
with the feeling of the great uncertainty of time;
so that he has been heard to acknowledge,
that for months together he seldom lay down in bed,
without endeavouring to commit his soul into the hands of the Lord;
feeling it very uncertain whether he should be permitted to see the morning's light.

In reference to this period, a dear friend remarks:--'Of that time,
and of many months previous to his appearance as a minister,
my recollection is very clear.
We were then confidential friends, and often together;
and during the lapse of years that has intervened, I have frequently reverted to it.
The exercise which then attended him,
almost bore down the natural cheerfulness of his disposition;--he was so serious,
so humble, so watchful,
lest at any time he should be thrown off his guard in the freedom of conversation;
and lest he should dissipate the influence of that heavenly love and goodness,
which often filled his mind, and led him into holy covenant with his Lord.
He one day took me to a small field nearly surrounded by trees,
on the south side of his house,
where he told me he was accustomed to retire alone at
an early hour of the morning and late in the evening,
and often at noon when at home;
thus adopting the resolution of David:--"`Evening and morning and at
noon will I pray:`" the spiritual communion he witnessed there,
and at many other times,
would strengthen him no doubt in his earnest endeavour
to perform the will of his Divine Master.
Yet it was only from his deportment that I judged my dear
friend to be under preparation for the work of the ministry.
He spoke of that exercise to no one, and when our friend, Sarah Lamley,
who visited families in Sheffield in the summer of 1813,
and in the sitting with his family,
told him she was sensible that he was called to that important work,
his dear wife heard it with extreme surprise.'

Sitting in meeting on one occasion,
he was particularly impressed with the language of our Saviour,
after he had cleansed the leper;--"`Were there not ten cleansed,
but where are the nine? I tell you there are not
found that returned to give glory to God,
save this stranger.`"
The remembrance that he had ever read such a passage in the
sacred volume was entirely obliterated from his mind;
he thought he felt the requisition of duty to address it to the meeting,
but he was perplexed; he knew not at the time where it was to be found:
he gave way to reasoning,--his dependence not being simply on the Lord alone;
and in great distress of mind, he allowed the meeting to break up.
He hastened home, and opening his bible,
the first passage that met his eye was,--"`were there not ten cleansed,`" etc.
He was deeply affected:--he entered renewedly into covenant with the Lord,
that if He would be pleased again to visit him, he would be more faithful;
and when again he felt the requisition, he was strengthened in much brokenness to comply.
A sweet and inexpressible feeling of peace was
mercifully permitted to follow this sacrifice;
confirming to his mind that it was indeed a sacrifice prepared of the Lord.
From this time he continued occasionally to
express a few words in the line of the ministry;
and not unfrequently he was permitted to derive comfort
from the united exercise of others engaged in this work,
who were occasionally led to express the substance of the burden he
himself was labouring under:--this was very confirming to his mind:
and he has been heard to recount with gratitude to God,
his condescension to him during this period of infancy in the work.

At one time, accompanying a female minister,
who had appointed a public meeting to be held in a Methodist meeting house,
he was prevailed upon to go with her into the pulpit.
He had never spoken in a meeting of that description,
and he had no apprehension that in such an assembly he
should be called upon to take any conspicuous part.
But his mind soon became involved in exercise; and being unwilling to yield to it,
the Friend's way was quite obstructed,--no door of utterance was given.
He saw and felt this, and arose, but under such conflict,
as made him involuntarily cover his eyes with his hands;
and in this attitude he addressed the meeting.
His companion followed; and through the Divine blessing,
the meeting was crowned by the sensible feeling of the
overshadowing love of their heavenly Father.

He was acknowledged a minister in the year 1816;
and shortly afterwards he accompanied another
Friend in a visit to the meetings in Lancashire,
and some parts of Yorkshire.
