== Chapter VI.

[.chapter-synopsis]
* Removes with his Wife and Family to Russia
* Voyage Thither, 1818
* Settlement at Ochta Near Petersburg
* William Allen and Stephen Grellet
* Agricultural Success
* Visit from the Emperor, Etc.

During the ensuing winter,
Daniel Wheeler was actively engaged in winding
up his affairs preparatory to leaving England.
Ample provision of agricultural implements, seeds and cattle, was also made; and,
at length, all being in readiness, he embarked for Russia, with his wife,
family and assistants, in all twenty souls, on the 22nd of Sixth Month, 1818.

The following memoranda are from the pen of a friend, and refer to this period.

On the 18th of Sixth Month, 1818,
we were agreeably surprised by seeing our dear friend Daniel Wheeler,
come into our meeting at Sheffield; for he had taken leave of us,
not expecting to meet us again before embarking for Petersburg:
towards the close of the meeting, he expressed himself nearly as follows:--

'`It has afforded me consolation once more to sit with my dear brethren and sisters,
though in great weakness; and painful my feelings have been,
when thinking that I may never have another opportunity of doing so;
being with my dear family about to be removed from scenes like these,
to a land of strangers, amongst a people whose language we know not.
I do not wish to multiply words unnecessarily;
but as there are perhaps few present who are acquainted with my motives for leaving,
I have believed it would be right for me, near the close of this meeting to inform you,
as ability may be afforded.
Nearly four years ago, in the vision of that light in which I believe,
it was clearly manifested that it would be right for me
to remove with my dear family to that land.
Many were the conflicts and deep the baptisms I passed through,
known only to Him who seeth in secret; but whilst abiding under these impressions,
for he that believeth maketh not haste,
I was brought into a willingness to give up thereto:
and thanks be to the Preserver of men, I can now say without boasting,
I am willing to go whithersoever He may be pleased to send me.
With these feelings, I went over last summer to see this strange land;
and though I met with many trials, my faith was not shaken, but remained fixed on Him,
"`who walketh upon the wings of the wind.`"

'`Painful as the separation is to me,
I would not have my dear friends think that I consider my lot hard;
for in sincerity I can adopt the language of,--"`What shall I render
unto the Lord for all his mercies?`" Few have received greater
benefits from His hand,--few have experienced greater deliverances;
and none more unworthy.
I am weak and frail; yet in me you behold a monument of His everlasting mercy.
He has kept me from the devouring sword;--He has preserved me from the raging pestilence,
when thousands have fallen by my side;--He kept
me alive in famine;--He saved me from shipwreck,
when the deep was ready to overwhelm, and the briny waves to swallow me up:--but,
above all, He has showed me his marvellous Truth.

'`To this Power, my dear friends, I commend you, which is able to do all things for you.
When we are far separated, we may still pray for each other;
and perhaps those prayers may prove more availing, than whilst we have been together.
In the words of the Apostle,--to His grace,
which is able to keep and preserve you alive in the most holy faith, I commend you,
together with myself and my dear family,--all that go, and all that stay;
and in the love of the everlasting gospel, I salute you,
and affectionately bid you farewell.`'

The last visit our dear friend Daniel Wheeler paid
before leaving his native country for Russia,
was at the house of Sarah Eglin of Hull, where he took his last meal on shore,
the 22nd of Sixth Month.
In a short opportunity, after dinner,
he told us that his mind had been gratefully affected,
in renewedly feeling the life giving presence of Israel`'s Shepherd,
accompanied with a belief, that he should not be deserted in the time of need; but,
that He who had been with him in six troubles
would graciously preserve him in the seventh:
under which precious feeling he had been ready to adopt the language,--
"`Surely goodness and mercy have followed me all the days of my life,
and I shall dwell in the house of the Lord for ever.`"

[.offset]
+++[+++He proceeded on his voyage;
in the course of which he addressed the following
letter to his friend the late Samuel Smith of Sheffield.]

[.signed-section-context-open]
Sixth Month 26th, 1818.

[.salutation]
My Dear Friend,

According to my promise, I have the pleasure of informing thee,
that we are now pushing for the roads of Elsineur,
and expect to anchor in about two hours, having had a passage of four days and nights.
It has been what the sailors call a fine run;
yet some of my company have thought it rough enough.
The supper-table was well attended the evening we left Hull,
and sailing was talked of with the greatest enthusiasm:
but a great alteration had taken place by next morning the land was out of sight,
the wind had got up, and we found a tumbling sea upon the Dogger Bank.
But little breakfast was wanted, and at dinnertime,
I had not one guest to bear me company.
The Arethusa has proved herself a noble vessel; and,
although much weighted upon her decks with water-casks and cattle,
she has borne her costly freight,
(to me not only costly but precious indeed,)
nearly seven hundred miles in this short time,
without any leakage, though sorely buffeted by wind and sea.
My dear wife has been very ill;
yet through all has been favoured with calmness and resignation,
and I fully believe has never once let in fear.

The sincerity and kindness of all our friends who have sheltered me and my family,
serve to make us the more regret being thus torn away from them.
But amidst these painful sensations, quietness has presided amongst us;
and in our silent meeting in the cabin yesterday, some of our hearts were tendered,
under a sense of the continued regard of the unslumbering Shepherd.

We were so amply provided with every article of provision
which our Hull friends could think of and prepare,
that our fare has been very different from what is usual at sea.
In short, we have so many things to be thankful for,
that there is some danger of our being deficient in
gratitude to the great Author of all our blessings;
but I humbly trust, we shall be preserved in humility and watchfulness,
and in that fear which can alone entitle us to Divine protection and regard.

[.offset]
+++[+++After his arrival at Petersburg, he again writes to his friend Samuel Smith, as follows:]

[.signed-section-context-open]
Ochta, near Petersburg, Eighth Month 19th, 1818.

[.salutation]
My Dear Friend,

I am fully aware that thou hast long before this time
heard of our being favoured to land in safety,
complete in number as when we left our native country.
After replenishing our stock of hay and water at Elsineur, we proceeded on our voyage,
and arrived at Cronstadt, on the 16th day from Hull: one day was lost at Elsineur,
so that we could not well have had a more favourable and expeditious passage; for which,
I humbly trust, all of us who are capable of reflection, are truly thankful.
Several things combined to detain us at Cronstadt,
so that it was eight days before we reached the habitation prepared for us,
which is situated on the bank of the Neva, nearly opposite the Smolny monastery.
It is a stuccoed brick house of two stories,
with the necessary stabling and outbuildings;
and we have now got it into tolerable order.

I have called upon my old acquaintances and friends of last year,
and have met with the most handsome treatment from all with whom I have had to do;
and I have found, to my great comfort,
the greatest sincerity in all those who made profession last year.
Sometimes I cannot avoid partaking of their sumptuous tables,
which I can assure thee is no treat to me, though I believe it has its use: and if so,
however mortifying, I hope I shall be willing to bear the cross of it.
I always look forward to such times, as if I was going to be tried by a court-martial,
or something of the sort; but if it was not for these feelings,
I should be afraid that the creaturely part would be in danger of exaltation,
from the caresses of these people.
So that although much strippedness and abasedness is my lot,
I believe that there only is my safety.
Truly there is a precious seed scattered up and down in this place;
and I think it is very remarkable,
that so many of those in high stations are not only great,
but are sincerely desirous of doing good, and are so little in their own eyes.

The greatest part of the time we have been here, it hath pleased Him,
who best knows what is best for us, to dispense a season of poverty and barrenness,
as far as relates to myself; and my dear wife has been pretty much in the same condition.
At the same time, a ray of light hath mercifully been permitted to shine upon the path,
sufficient to strengthen the belief, that our being here is in the counsel of His will,
without whose knowledge a single sparrow falleth not to the ground.
If it was not for a gleam now and then of this kind, though faint and transient,
how deplorable would our prospect be,--separated from those we dearly love,
surrounded by many persons disposed to take every advantage of us,
with a dreary half-year`'s winter gathering round us.

We are now making preparations for the winter,
and have laid in a large store of wood for fuel;
much more than I should have thought we could possibly consume.
But as many fears are entertained by our friends here,
lest we should suffer from the cold, we are forced to comply with their advice.
The Russians keep themselves much warmer than we shall like;
and I think it will be better to wear a little extra clothing,
than to keep our rooms so excessively heated.

We have lately had some frosty nights,
which have obliged us to try the stove in one room;
we are much pleased with its construction,
and think it preferable to our open English fire-places.

I have lately been inquiring the manner in which the winter here begins;
and am informed that, after some cold rainy weather, the English winter commences,
which freezes over parts of the Lake Ladoga: these are soon broken up by the wind,
when the ice comes down in large flakes, and blocks up the Gulf of Finland and the Neva.
Shortly after this, the winter comes in reality, and fixes the ice,
often in a very rough state,
just as it has been hurried down by the current,--many
of the flakes lying one upon another.
Often, the whole becomes solid in forty-eight hours;
after which roads are levelled over the rough ice,
at those places where the pontoon bridges and ferries have been,
which are marked out by fir trees set up in the ice.
These crossings, frequently remain passable until the Fourth Month;
for although the snow melts off the land three weeks earlier,
yet the river remains frozen,
owing to the frosty nights:--the roads are sometimes
dusty before the ice breaks up in the river.
This I believe is the season when people suffer the most,
as the days are so warm that they change their clothing,
whilst at the same time there are strong frosts by night.

Ninth Month 4th.--Finding I have yet time,
I feel disposed to lengthen my already lengthened letter.
I do not wish to tire my friends;
but I believe they are so much interested in our welfare,
as to accept it as an expression of that gratitude and love,
which I trust will never cease to flow in my heart,
whilst memory holds her place in this frail tabernacle,
and however distant we and our little ones may be exiled.
I alluded in the forepart of my letter to the stripped situation of mind,
that had for some time been my portion; and have now, with humble thankfulness,
to acknowledge the inexpressible comfort wherewith I am comforted;
which nothing short of the great and promised
Comforter could administer to the drooping mind.
Last First day, in our little meeting, the Master was pleased to preside,
and it was indeed "`a feast of fat things;`" and
the language which arose in my heart was,
"`Take eat; this is my body.`"
I never remember being under such a covering, and my desire is,
that I may never forget it: and oh! that the fear of the Lord may so prevail amongst us,
as to entitle us to His love, which can alone enable us "`to run through a troop,
or leap over a wall;`" and which at this time
enableth me to call every country my country,
and every man my brother.

[.asterism]
'''

[.signed-section-context-open]
To Balby Monthly Meeting.

[.signed-section-context-open]
Second Month 17th, O. S. 1819.

[.salutation]
Dear Friends,

In conformity with the desire expressed in your minute of the Fifth Month last,
we have endeavoured to render an account of
ourselves in the foregoing part of this letter.
It was thought that by drawing up answers to
such of the queries as were applicable to us,
the most correct statement of our situation would be obtained.

In thus drawing the attention of the Monthly Meeting to its distant members,
a belief accompanies my mind,
that tender sympathy and feeling are excited on our account;
and my heart is humbled within me, in the remembrance of the "`goodly tents of Jacob,
and the quiet dwelling places of Israel,`"--of those dear brethren and sisters,
with whom I can no longer assemble before the Lord,
and from whom my dear family and self are far separated,
as from the bosom and fostering care of the church.
Yet amidst a dispensation so painful to human nature,
I have abundant cause to acknowledge the continued
regard of Israel`'s great and compassionate Shepherd;
who faileth not to care for His sheep, however widely scattered,
and who at seasons is graciously pleased,
not only to afford the healing balm of resignation, but to replenish with His love,
which many waters cannot quench, nor distance diminish;
but which at times is sensibly felt to flow towards the flock at home,
even to the hindermost,--and to clothe with ability in
secret broken aspirations to supplicate on their behalf,
that "`not a hoof may be left behind,`" and that none may be missing in the great day;
but that all of every age and of every class, may hear His voice, be known of Him,
and follow Him: that when He, the Great Shepherd, shall appear, we may appear also,
and be all bound up together in the Lord`'s "`bundle of life;`" which is frequently,
fervently, and at this time, the desire of your friend,

[.signed-section-signature]
Daniel Wheeler

[.letter-heading]
To Mordecai Casson

[.signed-section-context-open]
Third Month 19th, 1819.

I do not know that we have ever had more than 21 degrees of frost by Reaumer`'s scale,
(16° below zero, Faht.)--indeed, but few of the Russians recollect so mild a winter.
I think we never passed a winter in England with less sickness in the family:
the merciful Dispenser of all our blessings has indeed
done more than we could have thought or asked for.
During four months of the darkest season, we have had the company,
generally two days in the week, of our beloved friends William Allen and Stephen Grellet;
through whom we have often been cheered and refreshed
as with dainties from the dear Master`'s table.
They have had a narrow path to tread in, yet are well satisfied with their labours here;
though they have been in a different way from what is
customary with those who move on such errands:
they have truly been led in paths that they knew not, and in ways that they had not seen,
to their own admiration, and to the praise of the great and excellent Name.
They left us ten days ago,
with minds full of peace,--beloved and regretted by all
who had the happiness to become acquainted with them.
The stream of gospel love, which was at seasons permitted to flow,
when channels were open to receive it, has made, I believe,
an impression on the minds of some, which will never be obliterated;
and which has clearly evinced, "`whose servants they are.`"
They were, I think, of all men the most fit to move in such a work, in such a place,
and under such circumstances.

I saw them set off from the city, just at the edge of dark, in a covered sledge,
in the midst of a heavy snow-storm.
They are furnished with letters and documents,
sufficient to open the way wherever they go:
they have also a document called a podorojni,
which obliges the post-masters to furnish them
with horses as soon as they arrive at a station;
so that they are not likely to suffer detention on the road.
Their luggage is put in the bottom of the sledge;
over it is a bed covered with black morocco leather, on which they can either sit or lie:
they have also provisions with them; and a servant who can speak French, German,
and Russian.

Since the departure of our friends, we have felt much poverty and strippedness;
yet at times a renewed evidence hath in unutterable mercy been vouchsafed to us,
that the Rock remains, and that the Foundation standeth sure:
so that there is still encouragement, even amidst the gloom by which we seem surrounded,
humbly to hope that we shall be preserved and enabled to maintain our ground;
however feeble our attempts may seem, and however much our weakness may be felt.
The responsible situation in which we are placed,
is at times almost enough to overwhelm me with fear;
lest I should let fall any of those precious testimonies given us to bear,
and thereby bring reproach upon the blessed cause of Truth.
I have however great consolation in observing,
that my eldest son also begins to feel the importance of this;
and it is a great favour when the eldest takes the right way,
as there is then a hope that the younger ones will follow after.

[.letter-heading]
To Barbara Hoyland

[.signed-section-context-open]
Ninth Month 22nd, O. S. 1819.

[.salutation]
My Dear Sister,

Since I last wrote to thee, our work has made great progress,
and being now widely extended, is not likely to lessen my fatigue;
but I am looking forward to a little respite,
as the winter is expected shortly to be with us.
Since the spring opened, I have been much harassed,
having been engaged from four in the morning until late at night, except on First days,
when I do not suffer any work to be done,
and of course I have no occasion to go out myself.
It is a common practice here to transact business,
and hold the principal markets on First days; but I made a stand against it,
as soon as I came,
and have been under the necessity to this time strongly to object to it.
On Fifth days also, I take the forenoons; so that our little meetings are regularly held,
which is a great comfort to me, as well as a respite from toil,
and when at seasons the Great Master is pleased to preside and own the slender few.

Since the spring opened, we have sown about forty acres with clover, and other grasses,
also with some oats, but merely to protect the smaller seeds from drought;
about four acres of potatoes have been planted,
and ten acres of turnips sown with the Northumberland drill.
On the whole, these have done well, particularly the turnips,
which are bought up at a high price, as fast as I can get them into the market.
But I am most surprised by the grass seeds,
which in twelve weeks after the sowing were in full flower, looking like a full crop,
the year after sowing in England; such is the astonishing quickness of vegetation here.

Amidst the numerous avocations of the Emperor,
time has been devoted by him for a thorough examination of the work carrying on by us;
which gave me full two hours`' time with him alone,
and another hour was occupied at our house:
so that I had an opportunity given of clearing myself,
and I hope nothing was kept back on my part.
I rejoice in believing, that a spark remains unextinguished in his noble bosom,
which I trust will never be suffered to go out or diminish;
but may be permitted increasingly to brighten, even unto the perfect day.
Yet I cannot help fearing, when dwelling on the critical situation in which he is placed,
the exalted station he fills, and the many besetments by which he is surrounded.
I will content myself with reviving his own
expression;--when speaking on the subject of war,
I alluded to the vast army in this neighbourhood, and the state of mankind in general;
he replied,--'`the things that are not possible with man, are possible with God.`'

We have also had a visit from the reigning Empress:
she is a very amiable woman,--so unaffected and unassuming,
that our fears of being embarrassed in her presence
were soon changed into admiration and regard;
and though she manifested great condescension and affability,
true dignity still appeared.
She came to the house, and afterwards went to view the work;
and I shewed her everything that I thought would please.
She walked for a considerable time on the land,
and was much gratified with its being so dry,
as well as with the apparent change in the face of the country.
The Empress speaks a little English, and had with her a companion who understands it well.

[.signed-section-closing]
I remain, etc.

[.signed-section-signature]
Daniel Wheeler

[.letter-heading]
To David Mallinson of Sheffield

[.signed-section-context-open]
Ninth Month 22nd, 1819.

How often have I thought of my beloved friend, and his dear wife and family,
when in a situation in which I could not possibly address a few lines to them;
and as often lamented and grieved, as month after month has rolled away,
when they have been again brought to my remembrance.

In the winter, my time was much occupied in making preparations for the ensuing campaign;
and since the ice left us, I have been constantly hurried and fatigued.
This year my labour has been much increased,
by my having been appointed to assist in the
improvement of some land of the Dowager Empress,
situated about twenty-four miles distant.
I have in consequence seen the Dowager several times;
and I find it a trying situation for a Friend,
to pass through the apartments of a palace, amongst a host of servants and military,
who stare as if I was not a fellow-man.
I sometimes think no one was ever in a situation similar to mine,
or so much like the pelican in the wilderness, or the solitary sparrow on the house top;
and am ready to query, whether my being here, can answer any good end.
Yet there are seasons, when I am comforted in the belief,
that some minds are led to consider and to inquire our motives,
for differing so widely from the rest of mankind; and I uniformly find,
when opportunities of this sort occur, something like an assent in the minds of such,
and a lamentation raised that a larger portion of mankind do not
follow our example.--Alas! little do they know how frail I am,
and how weak I feel;--often stripped of everything that can afford any real comfort,
and apparently left to myself to walk in slippery places.
Sometimes my mind glances at my dear friends at home; but there I must not dwell,
though I believe I shall always consider my country as my home,
--and I trust my friends will ever remain dear to me,
and that however separated or circumstanced, we shall be dear to each other in that love,
which is not subject to change, but "`hopeth all things, endureth all things,
beareth all things; rejoiceth not in iniquity,
but rejoiceth in the truth`"--which rests upon the meek as a diadem,
and crowns the humble sufferer with eternal life,
if constantly and earnestly laboured after and abode in.
However we may be permitted to feel our nothingness,
let us remember it is "`by these things we live:`" and truly, my dear friend,
and but lately very often my companion in tribulation,
I believe He is a strong rock and an irresistible fortress to dwell in.
For my own part, I need not ask the question,
"`whither shall I go;`" having no choice left, and consequently no merit,
if I should be found frequently turning unto Him,
who only "`hath the words of eternal life.`"

I know I am many letters in debt to many of my dear friends;
and I am afraid I should not be warranted in saying '`have patience and I
will pay you all:`' and yet as it is really my intention to answer them,
I hope they will be disposed to give me a little longer credit;
at the same time to attribute my long silence to the true cause,
and not that they are any of them blotted out of my memory,
or that my regard is in any way lessened.
For I think I may say, that all the members of your meeting,
with whom I have been acquainted during the time
I have been permitted to dwell amongst you,
are frequently the objects of my remembrance and regard,
from the oldest down to the little child.
But when my time is so limited, that I cannot keep up a regular correspondence,
even with those that I have had the most intimate acquaintance with,
I hope the charity of others will lead them to put the most
favourable construction upon my long silence in this way,
and I really believe they will be disposed to do so.

Well, my much loved friends,
it was once very pleasant to be with you and the dear children;
but those days are over and past, when it was often my lot to drop in amongst you;
they are departed as a shadow when the light is withdrawn;
but the Ancient of days remains: He changeth not, neither do His years fail.
May He be your happy portion, not only through time, but,
when the struggle is over and the warfare at an end,
through the never-ending ages of eternity.

Believe me, though the restless Baltic rolls between us, your affectionate friend.

[.signed-section-signature]
Daniel Wheeler
