== Chapter VII.

[.chapter-synopsis]
* Severe Winter of 1819-20
* His Affectionate Address to Balby Monthly Meeting
* Sundry Letters to His Friends in England
* Visit from the Emperor Alexander

[.letter-participants]
To David Mallinson

[.signed-section-context-open]
First Month, 1820.

[.salutation]
My Dear Friend,

Annexed are the answers to the queries from our slender meeting at Ochta,
which I hope will be received in time for the Monthly Meeting in the Third Month next.

We often wonder how you are going on in England,
whether you are sharing in any degree our cold winter.
I sometimes think yours must have been more severe than for several years past,
as the wind has been between north and east for
the greater part of the last three months.
I cannot possibly describe what we have had to encounter here: the Russians say,
there has not been so severe a winter since the year 1800.
It came upon us all at once; in the beginning of the Tenth Month,
we could not get the plough into the ground, and we were shortly driven off altogether.
The quantity of snow is great, and where it has drifted, it is very deep indeed,
and the frost has been intense.
This night we have twenty degrees,
and it has been as low as thirty-one degrees by Reaumur's scale (37° below zero,
Faht.) I was in the city on the coldest day, and did not suffer;
though when I shut my eyes, perhaps for half a minute,
it was difficult to open them again.
At one time our prospect was very gloomy,
as the children seemed as if they could not bear it,--and the four youngest
were ill at once with the scarlet fever;--but the Great Physician helped us.
I did not like the idea of sending for a doctor; it seemed like distrusting the hand,
that has so often been stretched forth for our deliverance:
but one of our Russian domestics being ill, on his account a doctor was called in,
and it was through him we learned what fever it was.
They are now, through mercy, in usual health; and are all enduring the cold,
I think as well as the Russians themselves.

We have abundance of wolves,
which are drawn by the severity of the weather nearer than usual to the abodes of men.
The intense cold sometimes drives them mad; six cases have occurred within our knowledge,
of people being bitten by wolves in this state,--four
of which proved fatal,--and in the other two,
the parties recovered, having had the parts cut out,
and the wound seared with a hot iron.
One man had his face torn by a wolf close by our house, but he succeeded in killing it;
we all saw it, and a terrible animal it is to encounter, I can assure thee.^
footnote:[This man though he submitted to the operation,
subsequently fell a victim to hydrophobia.]
When the frost is very great, the smaller birds fall to the ground;
I have several times seen this.
But though the wolf prowles round our habitation by night,
we are favoured to be quiet and peaceful within, and to partake of many consolations.

[.letter-participants]
To Balby Monthly Meeting

[.signed-section-context-open]
First Month 12th, 1820.

[.salutation]
Dear Friends,

Through the continued mercy of Him,
who "`crowneth the year with his goodness,`" I am once more permitted
to send you answers to the queries from our little meeting at Ochta.

As great poverty and strippedness of mind are often, and particularly at this time,
my portion,
I feel quite discouraged in attempting to take up my pen on the present occasion;
but in these dispensations, I have frequently to admire,
that a precious feeling of love towards my dear brethren and sisters at home,
is vouchsafed and permitted to remain,
when every other feeling of good is wholly withdrawn from me.
This being afresh brought to my remembrance, a hope is revived and cherished in my heart,
(although peculiarly situated,
and at times made painfully to feel the prevalency of the power of darkness
by which I am surrounded,) that a small spark of life is yet unextinguished;
and which, while I am writing, kindles an ability,
though under an humbling sense of great weakness,
to hold forth a word of encouragement to the afflicted, and to those among you,
unto whom it is not only given to believe in, but also to suffer for the name of Jesus;
which may have a tendency to strengthen minds that are often drooping,
and in their own apprehension,
no longer able to sustain the seemingly unequal combat,--who
know what it is to be plunged into the depths of indescribable
distress;--for such I am persuaded there are.
"`Fear not,`" was the gracious language of the Most
High to "`worm Jacob;`" and it continues to be so,
to all the Lord's children, who are endeavouring faithfully to abide under,
and patiently to endure the turnings and overturnings of His holy hand upon them:
and though for the present these trials are not joyous but grievous,
yet afterwards the peaceful fruits of righteousness will be
the blessed experience of all those who are exercised thereby.
It is indeed no other than the suffering path that leads to blessedness,
which the dear Master himself trod; and which all his tribulated followers must tread;
for the disciple cannot expect to be above his Master, nor the servant above his lord.
So that, my dearly beloved friends,
there is no real cause to be discouraged or to marvel at these things;
but rather to rejoice, in that you are counted worthy to suffer,
and in that you are at times made sensible of pain: for truly,
pain is a certain sign of life, as that which is dead can feel no more;
and it brings with it a consoling evidence,
that such are living members of one and the same mystical body,
whose members suffer not alone; but whether one member suffer,
all the members suffer with it,--or one member be honoured,
all the members rejoice with it, of which Jesus Christ our Lord is the holy head.
"`Fear not, therefore;`"--the kingdom is appointed unto you:
it is those that endure to the end that shall be saved.

The trumpet has often sounded amongst us, my dear friends;
but the alarming sound of late waxeth stronger and stronger; sufficiently so, I trust,
to arouse those who have long regardlessly heard it.
I would fain dismiss this painful subject, but in attempting to do so,
sadness covers my mind, and fear begins to shew itself,
lest I should be found wanting in my duty to any: if such there are,
who have long been neglecting the great business of their lives, and instead thereof,
pursuing with avidity those things which perish with the using.
Alas! what will be the situation of these in a day that is fast approaching,
when the heavens shall depart as a scroll when it is rolled together;
when every false delight will appear in its true colours,
and nothing will be left for the poor mind to rest upon,
not so much as a small island in the midst of this sea of
perplexity and trouble,--not a single act of dedication to the
Lord's righteous cause of Truth upon the earth to reflect upon;
when those things that have occupied the heart,
will serve only as memorials of past folly.
Let such be entreated by one who long hovered on destruction's brink,
and who hath known the terrors of the Lord for sin and disobedience;
and under a sense thereof, is now most earnestly desirous that others may take warning,
and thereby shun the fatal snares which keep the soul in bondage and in darkness.
Let such be persuaded to seek the Lord,
"`while he may be found,`" and endeavour to redeem the past and precious
time,--to acquaint themselves with God and be at peace,--to come to the
knowledge of Him in the secret of their own souls,--who is "`the way,
the truth, and the life,`"--whom to know is life eternal;
who willeth not the death of a sinner, but that all should repent, return and live.
Then let me beseech you, in the love of Him, who died for us and rose again,
for the peace of your never-dying souls, to accept the gracious invitation,
"`be ye reconciled to God,`"--before it be too late,
and the things that belong to your peace are hid for ever from your eyes.

There is another class to whom my attention is now turned,
for whose best welfare I feel an affectionate and tender solicitude;
in whose hearts the babe immortal hath been mercifully begotten,
creating therein new desires and breathings after soul-sustaining food;
whose spiritual eyes are in a good degree opened to behold the beauty
and excellency that dwell in the everlasting and unchangeable Truth.
To you, my dear Friends, many of whom are young in years,
my heart and pen are now directed,--earnestly
desiring your preservation in the alone path,
that most assuredly leads to peace in this world, and in that which is to come;
may nothing be suffered to turn you aside therefrom,
but may you be strengthened stedfastly to contend for the like precious faith,
which was once delivered to the saints,--that inestimable gift of God--that life of
the just--that substance of things hoped for and evidence of things not seen,
"`without which it is impossible to please God,`" and
of which Christ Jesus is not only the holy author,
but the blessed finisher.
Here let us make a pause,--lest any should spend their precious time,
that treasure of eternal consequence, in vain.
This most necessary and heavenly gift cannot be obtained from man,
nor from the doctrines of any set of men.
What saith the great apostle?--"`Faith cometh by hearing,
and hearing by the word of God.`"
Have not all heard? Yes, verily,--the blessed sound hath gone forth from sea to sea,
from shore to shore, and from the river to the uttermost ends of the earth.
But let none be misguided by an imposing appellation given, I sometimes fear by design,
to the Holy Scriptures, styling them "`the word of God.`"
Although the Holy Scriptures are replete with
the most sublime truths,--the book of books,
wonderfully preserved from the earliest ages of time,
"`given by inspiration of God`" and "`profitable for correction, for reproof,
for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works,`" and "`are able to
make wise unto salvation;`"--yet let us mark what follows,--it
is "`through faith which is in Christ Jesus.`"

For some of you this explanation may not be needful, but for me it is safe.
Faith cometh then by that all creative Word,
which was with the Father before the worlds were; "`all things were made by Him,
and without Him was not any thing made that was made,`"
who in the beginning changed the wild chaos,
when it was without form and void, into habitable earth; who spake,
and the worlds were made:--and it is by this Divine Word alone,
that we must all be changed from a state of nature to a state of grace,
and renewed again into the heavenly image that man was in,
before he by transgression fell.
Behold then the Alpha and Omega, the beginning and the end, the first and the last,
the root and offspring of David, the bright and morning star!
Behold the marvellous display of everlasting love! the all-powerful, saving Word,
the blessed medium by which faith and hearing come,
is nigh in the heart and in the mouth, as saith the apostle.
Search then, my dearly beloved Friends,--seek and I humbly pray the Father of mercies,
that you may be favoured to find.
Be of good courage;--humble yourselves before God:
ask in the language of unceasing prayer, and you shall receive; knock, with earnest,
faithful desires, and the door of boundless mercy shall be opened unto you.
"`For every one that asketh, receiveth; and he that seeketh, findeth;
and to him that knocketh, it shall be opened.`"
Remember it is on you that the weight of the law and the testimony must devolve,
when the faithful standard-bearers of the present day
are numbered with the just of all generations:
and that on your example greatly depends the future bias of
the tender minds of the dear innocent little children.
In so doing you will not only be a blessing to them,
but they will bring down a blessing upon you; and the Lord Most High,
in his infinite goodness and mercy will bless you altogether.

With the salutation of that love which desireth the good of all,

[.signed-section-closing]
I remain your affectionate friend,

[.signed-section-signature]
Daniel Wheeler

[.letter-participants]
To Samuel Smith

[.signed-section-context-open]
Second Month 2nd, 1820, O. S.

Thy account +++_______+++ of towards the close of his day was truly consoling;
and I trust the retrospect of this period would have a
tendency to comfort his dear widow in her affliction.
We feel much for her; but she has a strong tower,
into which the righteous have in all ages fled,
and found refuge and safety,--even the power of the Most High God;
who remains not only a judge for the widow, but will plead her cause himself,
and be a Father to her fatherless children,
if they are but willing to commit themselves into His holy keeping.
In love and tenderness this is what I very much desire on their
account,--that they may choose the Lord for their portion,
and the God of Jacob for the lot of their inheritance;
that so they may be taught of his ways, and walk in his paths:
and then the great loss they have been permitted in unerring wisdom to sustain,
will not only be sanctified to their dear bereaved mother, but to themselves also.
And if happily the elder are good examples to the younger children,
in humble walking with their God, and in uprightness and integrity amongst men,
and by ordering their conversation aright,--they will be the blessed means
of turning the feet of their dear little brothers into the paths of truth.
The Lord himself will not be wanting to draw their
minds into an early acquaintance with that light,
which is the life of men, in their own hearts;
which if attended to will lead them out of all error into all truth:
in righteousness will they be established, and great will be their peace.
Our love is to them all.

I will endeavour to give thee some idea of a plan which opened in my mind last autumn;
but I must in the first place make thee a little
acquainted with the state of things here.
The land belongs principally to the nobles,
who have immense estates cultivated by the peasants born on them,
who are the absolute property of their masters, man, woman, and child alike.
They either work for their proprietor, or they deliver to him a part of their earnings,
liable to be increased at his pleasure.
The result is, that they have no interest in any thing;
and I have heard it said among them, that life is not worth a copeck,
or the hundredth part of a shilling: this is a very affecting circumstance.
My idea is, to make a trial of placing peasants in farms at a moderate fixed rent,
on the land we have drained and cultivated; and if these are favoured to prosper,
I have a hope that the nobles will see it their
interest to divide their large estates in a similar way,
and place their peasants on the same footing;
and I am persuaded their incomes would be greatly increased.
If when each peasant had paid his rent either in money or produce,
the remainder was to be his own, he would be stimulated to industry;
there would be something worth living for.

It was intended that the whole of the land which we drain and cultivate,
should be farmed by us; but this is now in part set aside.
The land is now to be divided into small farms, of from thirty to forty-five acres,
to be let at a moderate rent, but sufficient to pay interest on the outlay for draining,
cultivating, and building;
the tenants to be under wholesome restrictions in the management of their land,
that their farms may be taken proper care of.
On each piece of land where there are farms established, a part will remain in my hands,
as an example for the small farms,
where a complete establishment for agricultural purposes will be built.
I have been very busy constructing a model for a farm-house,
suitable for the object in view;
and it is expected that several of these houses will be erected next summer.

I had the happiness to see the land which has been drained, quite free from vapour,
when all around it has been covered as with a cloud;
so that the surrounding neighbourhood cannot
fail to become more healthy from its expulsion.
This would be a pleasant picture for the mind to dwell upon,
if there was not mourning and lamentation on other accounts: but the state of things,
in a religious point of view, is very affecting and discouraging;
and the query often arises,
what can be done for these people;--to which the answer at this time is,
"`vain is the help of man.`"
And truly I am often fearful that the creaturely activity of man, instead of helping,
is marring the good work already begun in the tender minds of many;
causing them to stop very far short of that undefiled rest,
which is prepared for the people of God: but it is my most firm belief,
that their earthly wisdom will be confounded,
and that the Most High will scatter them as chaff is scattered before the wind;
and that He will magnify His own glorious power in the hearts of his children,
who in simplicity are turning their faces towards his
holy mountain,--taking of the things of Christ,
and shewing them to these his little ones.

For my own part I am a very poor creature,
and sometimes fearful that I myself shall become a castaway;
yet after times of deep suffering, and self-abasement,
love for the dear people here abounds more and more in my breast;
and often is the desire breathed,
that the cultivation in their hearts may not only keep pace with,
but abundantly surpass and excel, that of the wastes, by which we are surrounded.
Then would "`the wilderness be as Eden, the desert as the garden of the Lord;`" joy,
gladness, thanksgiving, and the voice of melody would be heard therein.

The question--when shall we meet again? I should
be glad to have it in my power to answer;
but it is only known to Him who seeth the end from the beginning,
whether again in this world or not.
Let us look up with humble confidence to Him,
to enable us through every dispensation yet to come, to say--"`not my will,
but thine be done at the same time labouring with unremitting assiduity to know,
what His righteous will is concerning us.
Evening, morning, and noon, let us pray, my much loved friend; and He,
who will not break the bruised reed nor suffer it to be broken,
in his own time will not only reveal it to us, but will enable us to perform it,
to the praise of His great and excellent name, and to our unspeakable peace.
Farewell in the Lord, my dear friend.

[.letter-participants]
To Richard Cockin

[.signed-section-context-open]
Doncaster, 21st of Second Month, 1820.

[.salutation]
My Dear Friend,

Hearing by letters lately received from England, that affliction had visited your abode,
I cannot help waiving all other considerations, however pressing at this time,
and endeavouring to dip into sympathy and sweet feeling with my long loved friends;
to whom my spirit is united in the binding influence of that love,
which extends from the river to the uttermost parts of the habitable globe:
humbly desiring that the God of all consolations may be with you,
and comfort you together, with the riches of peaceful resignation to His righteous will;
sustaining you in lowly patience, wrought by tribulation and suffering,
in mysterious wisdom dispensed for sanctifying purposes, to His own glory,
and the refinement of those who are precious in his Divine sight.
"`It is by these things men live;`" they have led the
righteous in all ages to blessed experience,
being productive of that glorious hope which maketh not ashamed,
because the love of God is shed abroad in their hearts;
which in the true dignity of its character,
animates the Christian travellers with innocent boldness,
to persevere in the tribulated path cast up for them,
to meet with unshaken firmness the yet remaining storms of time,
and to behold with the placid eye of faith,
the "`far more exceeding and eternal weight of glory`" about to be revealed,
and which awaits the ransomed and redeemed of the Lord in the kingdom of Christ Jesus,
that will never have an end; where pain and sorrow cannot enter,
and all tears are for ever wiped away.

I well remember the dear young woman,
who has terminated at an early period her innocent career,
and entered into everlasting rest; and fresh in my memory is every part of the family,
at whose hands I have so often had kindness shown me in simplicity and godly sincerity.
These circumstances may not have been thought of by you;
but in my memory they will long retain a lively and sweet fragrance.
This acknowledgment will apply to many of my beloved friends,
and I would gladly make it to all of them:
very pleasantly can I reflect on the intervals which I was permitted to enjoy,
when a sojourner amongst you,
when my mind has been refreshed with the countenances of my friends,
as "`iron sharpeneth iron`" with some of whom, though a weak and feeble helper,
I have been engaged in endeavouring to turn "`the
battle to the gate`" whilst united together in love,
and harmonizing in sentiment, as "`our bows abode in strength,
the arms of our hands were made strong`" by the mighty God of Jacob.
But as a dream vanishes when the sleeper awakes, so are these seasons departed;
leaving me to gaze in abasedness of self,
to adore and tremble at the gracious dealings of that Almighty power,
which has been with me all my life.
Though few and evil have been the days of my pilgrimage,
yet few lives have been more checquered with vicissitude and variety,
since cast upon the wide world an orphan boy;
then cradled on a boisterous element and nursed in the free-school of iniquity,
with sinners my companions,--but myself the chief!
Oh! wondrous mercy, signally displayed!--in saving from the fire a burning brand,
and following up from time to time with judgment's rod,
the far-fled wanderer!--flying still, and still pursued! until overtaken,
and in matchless love obliged to yield,
and reluctantly to retrace step by step destruction's
mazy track,--and to stop at many a place;
and, I hope in sincere repentance,
made to dwell on scenes of mispent time and sinful deeds innumerable,
"`gone beforehand`" (I humbly pray) to judgment;--not to "`follow
after,`" or where would be now my hope at this late hour,
if forsaken by that gracious Lord;--who in so great compassion, wrought the miracle,
and in the greatness of his love and strength,
has led my straying feet beside the still waters,
and made me to lie down in the green pastures of life:--
who brought me amongst the assemblies of his people,
with whom I now feel precious unity of spirit in the bond of
sweet consoling peace:--and though far separated from them,
I am at this day, I trust,
"`sitting and clothed and in my right mind,`" under a sense of my own unworthiness,
and of such great and unmerited mercy.

When I began this letter, I had not the most distant thought of saying what I have done;
but on looking it over, I believe they are words of truth and soberness,
and I do not feel at liberty to alter them.
Truly my mind is at this moment humbled as in the dust,
in taking a retrospective view of the things that have been,
and of our present peculiar situation.
I think I never knew a time, when watchfulness and prayer felt so needful,
in order not only "`to strengthen,`" but even to retain "`the things that remain,
that are ready to die.`"
It is like contending for every inch of ground in a well contested field,
and being unable at night to discover whether
the morning' s position has been maintained;
so that we stand in need of the prayers of our brethren in old England,
that we may be preserved watchful, humble and faithful,
amidst the various snares and temptations by which we are surrounded.
Believe me thy truly affectionate friend,

[.signed-section-signature]
Daniel Wheeler

[.letter-participants]
To Balby Monthly Meeting

[.signed-section-context-open]
First Month, 1821.

Dear Friends, I now enclose the answers to the usual Queries from our little company,
and at the same time acknowledge the receipt of your certificate on behalf of S. K.

I trust that none of my dearly beloved Friends will attribute the brevity of
this letter to any thing short of the true cause;--neither absence,
nor distance, have in any degree lessened my love or diminished my regard for you.
"`Can the children of the bride chamber fast,
while the bridegroom is with them? As long as they have
the bridegroom with them they cannot fast.
But the days will come, when the bridegroom shall be taken away from them,
and then shall they fast in those days.`"
To you who have experimentally witnessed the truth of this saying of the Saviour of men,
it is unnecessary to say more,
than that these days are my days;--the days are indeed come,
when strippedness and weakness are all that I seem to possess.
Should there be any of my dear brethren and sisters alike circumstanced,
it is with me to say, for the encouragement of such,
(although destitute myself of any claim,
and totally unworthy of partaking thereof,) that if this humiliating,
though purifying dispensation be patiently abode under,
the result will be unspeakably glorious.
Mourning will be turned into joy; the painful and perhaps protracted fast,
will become a precious and delightful feast,--even "`a feast of fat things,
of wine on the lees well refined:`"--"`know ye what I
have done to you,`" will be sensibly understood;
and a language will be excited by gratitude and love,
similar in kind to that of Simon Peter,
when the dear Master silenced his objections by explaining the terms of apostleship,
"`Lord, not my feet only, but also my hands and my head.`"

The tree of the field sustains no injury by the wintry season's rest, on the contrary,
it is invigorated, if sap remains in the root: so the foregoing dispensation,
if the precious life remains, however low and hidden it may be,
tends only to strengthen and establish the humble
Christian more firmly in the heavenly vine;
and when the spring of life and love is permitted to return,
buds and blossoms will again appear,
and new fruit will be brought forth by these chosen ones, which will lastingly remain,
to the praise and glory of the great and good husbandman, and their own eternal peace.

Let me remind my dear Friends of every age and class,
that another year hath passed swiftly over our heads;
this intimation is accompanied by an earnest desire,
that as days are multiplied and years increase,
an increase of heavenly treasure may be ours,
through an increasing knowledge of the only true God, and his Son Jesus Christ.

[.signed-section-closing]
I remain your affectionate friend,

[.signed-section-signature]
Daniel Wheeler

[.letter-participants]
To John Hipslby

[.signed-section-context-open]
Second Month 7th, 1821.

[.salutation]
My dear Friend,

The prospect of approaching intercourse once more with our beloved friends in England,
through the medium of the shipping, administered comfort to my mind,
as I was about to take up my pen to address thee, and brings to my recollection,
that this letter will probably reach thee about
the time of our Quarterly Meeting held at Leeds.
This circumstance awakens a feeling, which humbles my heart,
and afresh revives in my view days that will never return, and precious seasons,
in which I was permitted to assemble with my dear brethren and sisters,
and even to partake of the same food,
though unworthy to gather up the crumbs that fell from the table.
But from scenes like these I am now set apart,
and can no longer behold the venerable towers of Zion, nor mark her bulwarks,
nor consider her palaces,--except from the reports of others.
The accounts that have reached us in the course of the summer,
have excited painful sensations;
lest any thing should tend to "`divide in Jacob or scatter in Israel,`
" and cause a shyness amongst those who have been valiants in support
of the law and the testimony,--or embitter the latter moments of any,
who have laboured through a long life with uprightness and integrity of heart,
for the welfare of Zion and the enlargement of her borders.
I cannot contemplate these things, and divest myself of fear,
lest a root of bitterness should spring up, and many be defiled.
"`Watch ye, stand fast in the faith, quit you like men,
be strong;`"--is the language that presents itself on the present occasion;
and if not applicable to others, I am well satisfied it is to myself.
For the older I grow, the more needful I find the watch:
there is no other safe dwelling place;--there is no cessation of arms;
the warfare is continual, and must be continually maintained,
or there is no standing fast in the faith.
But to such as endeavour, through watchfulness and prayer, to quit themselves like men,
strength will be administered in due time, not only to stand fast in the faith,
but to become strong; yea,
they will be "`strong in the Lord and in the power of His might.`"
So that I very much desire,
that the minds of all may be clothed with the invincible armour,
wherewith they will be "`able to stand in the evil day, and having done all to stand.`"

The winter with us is considered a mild one.
I do not know that we have at any time had more
than twenty-five degrees of Reaumur's scale,
(24° below zero, of Faht.;) but there have been frequent changes,
and I think we have all suffered more from the cold than heretofore, owing partly,
we suppose,
to the high winds which have prevailed with little intermission all the season.
The roof of our house has been much damaged,
and at this time at least thirty square yards of it are uncovered;
and we are told it cannot be repaired until warm weather comes again,
as being made of sheet iron, the workmen cannot well handle it during the frost.

[.letter-participants]
To S. Smith

[.signed-section-context-open]
Third Month 12th, 1821.

Having now dwelt among these dear people nearly three years,
I think I can say with truth, that my love for them has not diminished,
but on the contrary greatly increased,
particularly for those who are of least account among men:
their simplicity and sufferings, which I often witness,
render them dearer than ever to my heart; though I have often to turn aside,
and lament in heaviness and mourning.
My heavenly Father has been pleased of late, in retirement,
to clothe me more and more with ability to pray,
not only on account of the many evils that are in the world,
but for His little ones wherever scattered; and,
for ever blessed be His great and adorable name,
to pray for one who seemeth to need help more than they all--even for myself;
whose backslidings cannot be numbered for multitude,
and whose sins and transgressions are more than the hairs of my head,
twice told;--whose day's work is drawing fast towards a close,--yea,
the shadows of the evening are beginning to appear.
Can it be any thing but Almighty love,
that thus awakens and makes sensible a poor frail
mortal? "`As an eagle stirreth up her nest,
fluttereth over her young, spreadeth abroad her wings,
taketh them and beareth them on her wings,`"--thus preparing them for flight;
so doth a compassionate and ever merciful Lord God, nourish, cherish,
and strengthen in the tenderest manner, his unworthy and often ungrateful children.
How often would He gather them;--but oh! they will not.
How often in love unutterable doth He strive to save, by convincing their understandings,
in the most indubitable manner, that "`there is a reward for the righteous,
and a God that judgeth in the earth,`" and, unwilling "`that any should perish,
but that all should repent, return,
and live,`" how often doth He alarm and shake the false rest of those,
who are dwelling carelessly and at ease,
and thus warns them of the uncertainty of their continuance here.
By His judgments, all in mercy and in truth,
how often doth He fill our hearts with sorrow,
which worketh repentance never to be repented of, to reduce and bring us into humility;
that He may draw us nearer and nearer into acquaintance with Him,
in whom humility and meekness are personified;--who said "`no man cometh unto me,
except the Father, which hath sent me, draw Him;--no man cometh to the Father,
but by me;--him that cometh to me, I will in no wise cast out.`"

Oh! that there was a willingness wrought in us to bear the
turnings and overturnings of our heavenly Father's hand:--what
blessedness would accompany that simple child-like state!
The dear Master would have many things to say unto us,
but we cannot bear them now,--we are unprepared
to receive the sayings of the heavenly guest.
Then what abundant cause there is for the tribulated weary soul,
to come unto the meek and lowly Jesus; and in humble resignation, to receive His yoke,
and learn of Him,
whose teaching is ever sublime and excellent;--peaceful and
easy is His yoke,--light the burden,--sweet the rest.
He can teach us to pray "`in faith, even unto Him,
who seeth in secret,`" and who will condescend to hear from heaven, His dwelling place,
and to accept the broken, humble, contrite breathings of the soul.

I perceive that much of what I have written, applies to myself,
which is often the case with what I write to others; my friends will, therefore,
have the better opportunity of knowing and feeling the
true state and condition of a poor shattered vessel,
that has partaken of a tolerable share of buffeting (great part of
which might have been avoided) through the voyage of life;
and is now drifting with a fleet of many others,
that are endeavouring to reach the same port,
but into which it is impossible to enter without a pilot.
Some knowing the danger of delay, and the difficulty of obtaining a pilot,
unless timely and earnestly sought after, prudently hearken to counsel,
and provide at setting out.
Such steer along safely, with wisdom at the helm; but too many neglect this,
till near the end of the voyage, when, as they begin to discover their great risk,
by certain indications of danger which cannot be mistaken,
they are continually making signals to other vessels, by way of warning them.
To some who follow, the warning may be quite unnecessary, as such may be amply prepared,
having a glorious prospect of an entrance being abundantly administered unto them.

[.letter-participants]
To Richard Cockin

[.signed-section-context-open]
Tenth Month 3rd, 1821.

It is necessary to make great allowances for those in high stations in every country,
but particularly in this, which is but just emerging from a state of barbarism.
The difficulties by which a few virtuous individuals here are surrounded,
make it a matter of astonishment to me,
how such are enabled to persevere in a tolerable degree of well doing,
amidst such a host of corruption and opposition.
Scarcely a day passes over but we have cause to mourn and lament:
but although there is much to grieve for, there is also a great deal to love and pity.

There are a number of foreigners here, and not least my own countrymen,
who have done a great deal of harm, by flattering some truly worthy characters;
and from self-interested motives,
making them think more highly of their religious attainments,
than otherwise would have been the case.
This helps to keep such wrapped up in false garments,
and renders the language of simple and undisguised truth more harsh and impalatable,
when they do meet with it.
Some time ago, a person of consequence and his secretary,
visited the land we are cultivating on this side of the city.
The crops were at the time in a very luxuriant state, with which they were much pleased.
They wished to ascertain what the people about thought of the improvements,
and asked several of them what they thought of it.
These all expressed their approbation; at last, one was asked, who said,
'if the Lord had not given the man wisdom to do it,
it would have been a morass still.' With this answer they seemed much pleased.
The secretary said, 'our people have always faith,
they ascribe every thing to God.' I said,
'I often hear them mention His name.' 'Always,' said he.
'But, I said,
I am sorry to hear them call the great name to witness what they say in the markets,
and in their trade.' It was easy to perceive he did not like my remark.
Almost invariably the people here, in asserting the price of an article,
which is often a great falsehood,
call upon the Almighty as a witness:--when rather than lose a customer,
they will come down to one-half the price they first asked.
Now, if I had assented to the observation of the secretary,
and called them' a good people,' (which is a common
mode of expression here,) he would have been delighted.
In short, they are so used to adulation and flattery, that they look for it every where,
and from every person;
which makes the way more difficult for those who
are not satisfied to feed them in this manner.

I had a conference with the Emperor a short time since,
and was never so much satisfied with any previous interview.
He has passed through much conflict of mind within the last twelve months;
the state of political affairs and many other trying circumstances combined,
have served to reduce him both in body and mind.
A knowledge of his peculiar situation renders him in my estimation,
an object of commiseration and sympathy.
Few, I am persuaded, are really aware of the difficulties by which he is encompassed,
or of what he has to contend with;
and when I consider the education he has had and training up altogether,
I am more than ever surprised that he should have any relish for serious things.
He had been absent about ten months at the Congress; and on my telling him,
he had been a long time away from his large family, he said,
'I have had a great deal to do.
It is a very difficult thing to act for a nation, but I hope I have acted under God;
and the measures I have taken I hope are approved by Him.
I am encouraged to believe so, because not a drop of blood has been spilled.
When the nations were in great distress and suffering during the late calamitous war,
they then prayed to God: but they are like the Jews of old, they have now forgotten Him.
There are societies of men in different places,
who are disseminating bad principles under the cloak of bringing in Christianity:
they are in many parts of Europe,--they are every where.
' I told him I had often thought of him,
and that a petition had been raised in my heart on his account.
'Yes;' he said, 'and I have often thought of you; there has not been one day,
not one day, but I have thought of you and of Messrs.
Allen and Grellet, and always felt myself united to you three in spirit.'

Previously to this conversation, we sat down in silence before the Lord;
and in the course of our sitting,
my mouth was opened to declare unto him the goodness of God, and His great mercy,
variously displayed to the children of men; and to speak of the precious promises,
which the humble heart only can sensibly partake of.
After which, we continued our sitting until I had cleared my mind a second time;
in this I had to recite the invitation of the dear Master;--"`Come unto me,
all ye that labour and are heavy laden,`" etc.
After having sat some time in silence, feeling myself at liberty,
I told him my mind was relieved; when he gave me his hand,
and attempted to describe his feelings, but was unable to utter any thing,
except 'I have felt it,' laying his hand on his heart:
I never saw him so brought down before.
He stayed with us, I think, nearly three hours,
and then left us in an affectionate manner, saying, 'I must leave you.
I hope this is not the last time that I shall come:
remember me in your prayers.' I attended him to his carriage, and as it drove off,
he said, 'God bless you.' Our large family Bible lay in one of the rooms;
on seeing it he opened it, and readily turned to the 119th Psalm,
which he said he had read that morning.
He had a copy of the Scriptures in the carriage, which he always carries with him.
My mind was so covered with sadness during the remainder of the day,
and at intervals long afterwards, that my dear wife said,
she thought I must have said too little or too much to the Emperor.
I told her, no;--I felt satisfied as to that: but I could not help lamenting,
that such a man should be in such a situation.
