== Chapter IX.

[.chapter-synopsis]
* Visits England, 1825
* Returns to Russia
* Death of the Emperor Alexander, and Occurrences Consequent Thereon
* Address to Balby Monthly Meeting, 1826
* Extensive Fires, etc

In the early part of 1825, Daniel Wheeler visited England.
He took the overland route, in company with Thomas Shillitoe,
and landed at Harwich after a fatiguing journey of thirty-six days.
His stay did not much exceed three months: during this time,
he attended the Dublin Yearly Meeting,
to which he had felt his mind drawn before leaving home;
also the Yearly Meeting held in London.

The following extracts are from letters written on, and after, his return to Russia.

[.letter-heading]
To John Hipsley, Hull

[.signed-section-context-open]
Alster, off the Spurn, Sixth Month 23rd, 1825.

The pilot being about to leave us,
I hasten to inform thee that we shall shortly shape our course for the Naze of Norway.
The vessel, I believe, will be very comfortable, when we get fairly out to sea,
and the decks cleared up.

It would have been very pleasant to have assembled once
more with my dear Friends on shore,
if it had been permitted; as it is, I have great cause to be thankful,
for having been allowed at seasons to partake, while on this side the Baltic,
of the streams of that river, which makes glad the whole city and heritage of God.
At the same time my heart is filled with gratitude,
at the prospect of returning to my dear wife and family,
with my health so much restored and renewed; which cannot fail to raise in all our minds,
the tribute of thanksgiving and praise to the great and good Shepherd;
unto whom not only every sheep, but the most helpless lamb, of the flock is known,
wherever situated, or however hidden.

[.letter-heading]
To One of His Family

[.signed-section-context-open]
Alster, Seventh Month 13th, 1825. In sight of Hogland.

[.salutation]
My Dear +++_______+++,

Within the last twenty-four hours we have only got about as many miles to windward;
but we must learn in all states to be content.
I little thought when I wrote from Elsineur,
that another fortnight would elapse without my reaching
home,--and several days may yet intervene.
There is, however, abundant cause for humble gratitude and thankfulness,
that we have been so far preserved from accident.
One night, since we have been in the Gulf,
we drove very near the rocks on the Finnish coast.
I had been up till after twelve o`'clock, which is my usual practice at sea,
as midnight often decides the weather we are likely to have:
the mate had had the first watch, and when he called the captain at twelve o`'clock,
he asked whether the ship should go about.
The captain said, '`No; let her stand on.`' I did not feel satisfied with this,
particularly as the mate went to his berth, and the captain did not turn out:
but I lay down in my cabin, and kept myself awake,
as it was highly needful that somebody should be ready, if wanted.
Before one, a.m., a sailor discovered the rocks, and had the captain alarmed,
who without waiting to put on his clothes, went on deck,
and immediately the sailors were called out, and the ship`'s head laid the other way.
Had it been much darker, we might have gone ashore,
before the ship could have been got round.
But our great and merciful Helper was nigh to deliver; to whom belongs all praise.

Seventh Month 21st.--After beating about two other days with a contrary wind,
in the night of the 14th the wind altered,
so that the vessel could lay on her proper course:
the captain carried as much sail as she could bear, and at six in the morning we hove to,
off the guard-ship; and as soon as they had boarded,
we filled sail and stood in for the Mole of Cronstadt.
I succeeded in getting a passport without delay, and proceeded in the afternoon steamer,
and was favoured to find thy dear mother and all the family in good health.
I trust we rejoiced together in humble thankfulness for being permitted to meet once more.

Now, my dear child, I must bid thee farewell.
Unite with me in grateful thanksgiving to the Lord Most High,
for all His gracious mercies to us,
and in humble prayer that he will be pleased to keep us meek and lowly in His fear,
watching continually; that so we may be favoured to discover and escape every temptation,
and be preserved from the many evils that are in the world,
and alive unto Him who liveth for ever, through Jesus Christ, the Saviour of men:
whose blessed Spirit dwelleth in the contrite and humble heart.

[.letter-heading]
To Richard Cockin, Doncaster

[.signed-section-context-open]
Moscow Road, Ninth Month 26th, 1825.

My late visit amongst my dear friends in England, very frequently furnishes us,
when the family is collected together, with a pleasant theme for conversation;
and when absent from them and alone, it is often with me the subject of contemplation.
But while it serves to revive affectionate feelings for those I love,
a sting of regret remains behind,
at having enjoyed their company for so short an interval,
and being again so widely separated from them,
as has been my allotment for the last seven years.
But, I trust, I have no disposition to murmur or repine;--on the contrary,
I am often favoured to feel that resignation of mind, which, as it is abode in,
has for its companion a feeling of sweet peace,
of more value and more to be desired than the wealth of nations.

No part of the journey leaves so much solid satisfaction when brought to remembrance,
as my visit to Dublin.
This was not a matter of choice,
but undertaken and performed in the cross to my own natural will and inclination: and,
although I am unworthy to be trusted with a sling and a few small stones,
yet was I permitted to see how my brethren fared,
and to take their pledge,--a pledge of love,
which I believe will be long treasured up in my heart, and cannot diminish;
being impressed with a belief, that it sprung from an inexhaustible source,
a fountain of eternal duration, constantly flowing through innumerable channels,
but still full to the margin of mercy and truth.
There are several dear Friends in that land, with whom I feel a precious unity;
and whether they ever remember the stranger or not, he often thinks of them,
with feelings which time and distance only serve to heighten.

From what I have said of Friends in Dublin,
my dear friend must not suppose that those in England are forgotten,
or that any thing like a transfer of affection has taken place on my part.
Such is the transcendent quality of true love, that whilst it embraces new objects,
it does not lessen for those, on whom it has long and deservedly been fixed.
Be assured my attachment has not lessened for those whom I have long known and loved;
on the contrary, it is strengthened by the renewal of intercourse.

I am informed on good authority, that John Gossner, the reformed Roman Catholic minister,
is now allowed to preach in any part of the Prussian dominions.
He has lately had an opportunity of preaching before the Crown Prince of Prussia,
and also before another great personage at that court, who was so much affected,
as to faint in the course of John Gossner`'s discourse.
The wife of the latter personage, it is said, has long been a serious character;
so that one cannot help rejoicing in the hope,
that the great and good work is going forward in the hearts of some,
and perhaps in the hearts of many,
where least expected or looked for by poor short-sighted man.

[.letter-heading]
To Samuel Stansfield^
footnote:[Samuel Stansfield had resided some years in Petersburg,
and been a constant attender of the little gathering at Daniel Wheeler`'s house.]

[.signed-section-context-open]
Fifth Verst, Moscow Road, Tenth Month 19th, 1825.

Thou wilt soon have been twelve months in England,
and by this time canst form a judgment of the
state of things in the meeting at Sheffield.
I shall much rejoice to hear that there is a prospect of the
younger branches coming forward to advocate the precious cause.
The burden-bearers are thinly scattered in that large and once flourishing meeting;
and some of those who yet remain on the watch-tower,
cannot be expected to continue much longer,
before they are called to receive the reward prepared for all,
who have fought the good fight, and kept the faith.
It so happened that I was not at a week-day meeting at Sheffield, when last in England:
there seemed no deficiency on First days as to numbers; but, then,
numbers do not always add to strength: on the contrary,
large meetings are often painfully laborious,
as it frequently happens that but a small remnant are rightly concerned in
endeavouring to roll away the stone from the well`'s mouth;
and there is reason to fear, on these occasions,
that many return home without having been sensible that
any of the assembly have been feeding upon that bread,
which alone can nourish the immortal part.
I think I have witnessed, in the course of my pilgrimage,
that the most favoured meetings I have been permitted to share in,
have been those held in the middle of the week, or on other days than First days.

At our little meeting here, seven or eight is the greatest number that now collects,
only one or two individuals besides our own family, ever attending.
We often sit as in low places; yet at times are permitted to feel that power,
which can subdue all things unto itself,
and enable us to draw near in the silence of all flesh to the
"`fountain,`" which is "`opened to the house of David and to
the inhabitants of Jerusalem`" to wash and to bathe in.
What a favour it is, although far removed from the fostering care of the church,
not to be deprived of the privilege of worshipping Him,
whose watchful unslumbering eye beholds the feeble endeavours of all,
who desire to seek his face in sincerity of heart; and who,
in matchless and unmerited love, hath provided the blessed means to help our infirmities,
which, though unutterable, are understood even in sighs and groans.

[.offset]
+++[+++In the next letter,
he gives an account of the death of the Emperor Alexander in the south of Russia,
and of the occurrences at the capital consequent upon that lamented event.]

[.letter-heading]
To John Hipsley, Hull

[.signed-section-context-open]
Twelfth Month 13th, 1825.

When the intelligence of the death of our much lamented
and justly beloved Emperor was made public in the city,
consternation soon spread among all ranks of the people.
At first, I thought it possible there might be some mistake,
as the health of the Empress had been for some time declining,
and had occasioned her journey to the south of Russia;
but the military being called upon to swear allegiance to the new Emperor Constantine,
removed every doubt.

I was favoured with peaceful quiet and resignation on this mournful occasion,
and felt but one desire--that the death of Alexander might have been a fair one;
and we have the most indubitable proof that it was
unattended with any of those horrible circumstances,
which, in some instances,
have terminated the existence of the crowned heads of this country.
I have often put up a feeble petition that the hand of
violence might never be permitted to touch him;
and although I cannot help deploring, with the many millions of Russia,
the loss of such a man,--yet a secret joy triumphs over every selfish feeling,
and raises in my heart a tribute of gratitude and praise to the great Preserver of men,
who hath been graciously pleased to remove him in so remarkable a manner,
from this scene of conflict and trouble.
We could scarcely have desired more than has been given:
I believe it has been the lot of few monarchs to end their days,
whilst in the meridian of power, in a retreat so quiet,
and so distant from all the pageantry of a court: it may be said,
that he died in the bosom of his family.
It appears, for the first two or three days of his indisposition,
that he considered it of no importance,
and could not be prevailed upon to take any medicine,--
he had a great aversion to medicine at all times.
It is thought by some here, that if he had taken timely precaution of this kind,
the fever, which is very prevalent in that part of the country, might have been kept off:
it is probable, its effects might have been less violent,
and its progress impeded in some degree;
but we learn from those who are acquainted with that neighbourhood,
that strangers seldom if ever escape an attack of it, and it is often fatal to them.
The climate immediately round Taganrog, where the Emperor died,
is considered very healthy; but at a very short distance from it,
it is considered quite the reverse;
and it seems that Alexander had been beyond the healthy boundary,
and had taken cold on the south coast.

It is very consoling to find, that his mind was so peaceful, as appears,
when he was persuaded to take what is called the sacrament:
it is probable that delirium came on afterwards,
but towards the last he was perfectly sensible.
On the morning of his death, the sun broke through the clouds, and shone into his room;
when he remarked,
'`how beautiful the weather is`'--and the manner in which he
committed the Empress to the care of Prince Volchonsky,
his faithful adjutant, although done without the assistance of words,
plainly shows that he was collected, though deprived of speech.

From concurring circumstances of late date,
my hope is greatly strengthened that he has exchanged an earthly crown for one immortal,
that will never fade away.
He had reigned about four months less than twenty-five years.
The Russians say he was too mild, and too good for them.

I enclose some translations of letters relating to the illness and death of the Emperor.
The two first are from the Empress Elizabeth.
Some of the expressions in them are not just such as we should use,
but we must make allowances, for education.
They were written to the Empress Dowager.^
footnote:[See Appendix A.]

This event will naturally bring about many changes.
I have endeavoured to look round as to myself and family,
but all is at present enveloped as in a cloud.
Every thing here has been conducted quietly.
The army have all sworn allegiance to Constantine.

First Month 1st, 1826.--Before finishing my letter,
another proof of the uncertainty of all human affairs is handed to us.
I shall insert the copy of a letter I received the day after the foregoing was written.

[.signed-section-context-open]
St. Petersburg, December 14th, 1825.

Little did I think of giving you today such weighty news,
as that of an accession to the throne of the Emperor Nicholas, who is proclaimed today;
and we are going to take the accustomed oaths,
as the Grand Duke Constantine has entirely renounced the crown.
I have not read the manifesto; but those who have seen it say, that amongst other things,
the Emperor tells the nation, that he will reign as his brother did;
and that his reign will be only a continuation
of his brother`'s. The Minister of the Interior,
whom I saw this moment, says that the Emperor has verbally assured them of the same.
Let God`'s will be done on earth, as it is in heaven.
Wishing you well, I am

[.signed-section-closing]
Most sincerely yours.

This letter I received about two, p.m.:--before five o`'clock,
the scene was entirely changed, and rebellion most artfully contrived,
had thrown off the mask.
As the army about us had most willingly declared for Constantine, only ten days before,
some hesitation in several regiments became visible.
This moment seemed favourable for the wishes of
some who were aiming at a general overthrow;
and they artfully spread a report among the troops,
that Constantine was only two hundred versts from hence,
but was prevented from coming forward;
and that the newly declared Emperor was only an usurper.
This had the effect of drawing several large bodies of troops into the snare;
and I believe many of these poor fellows considered they were
only acting faithfully to the oath they had so recently taken:
it was very evident they had no pre-concerted design against the government.
However, an armed force collected in the neighbourhood of the Senate House,
and were joined by a number not in military garb, and a mob of intoxicated rabble,
who had been stirred up to act on the occasion.
In vain did the new Emperor send to them,
to endeavour to persuade them to peace and quietness.
At last, the military governor, an old soldier and a popular character,
went to harangue them; and might probably have prevailed,
but the real plotters amongst them, fearing the soldiers would become reasonable,
had the audacity to fire upon him.
This poor Count Myloradovitch, who had been unhurt, it is said,
in thirty-four engagements, was now mortally wounded.
He rode off towards the Emperor, but soon fell upon his horse`'s neck:
he was carried home in a sledge, and died in the night.

This circumstance led to a dreadful carnage.
The Emperor was very unwilling to resort to force,
and at first a volley of blank cartridges was fired;
but this only causing the rebels to advance,
a fire of grape shot was opened upon them with terrible effect,
followed by a charge of cavalry.
As most of the rebels who were able fled towards the river,
the cannon were pointed in that direction;
and the Academy of Arts on the other side of the river was struck with the shot.
The carnage in the neighbourhood of the Senate House was dreadful,
but all was cleared away before morning, except the blood upon the snow,
which bore testimony to the great slaughter of the preceding day.
We cannot ascertain the number of poor creatures
who were thus hurried into another world;
it is believed, however, that several hundreds perished.
The city barriers were immediately closed, and no person allowed to leave the city,
in order to secure all those implicated in this diabolical plot:
the fort is full of prisoners.

My feelings on this night were such, as no one need or would envy,
except perhaps some of the wounded who were groaning in agony, exposed to the frost.
The night was long and dark enough; but we were favoured to pass through it,
without the slightest molestation, in quietness, and, I trust, in confidence.

The next morning, we found the whole of our neighbourhood patrolled with soldiers.
As it was reasonable to suppose we should not long remain without visitors at our house,
I had a little prepared my dear family for this; and about one o`'clock, p.m.,
a colonel with four other officers and seventy hussars entered our premises.
These poor fellows had been summoned from a distance the day before,
and were stationed on the roads near our house:
they had been twenty-four hours in the frost,
having passed the whole night in scouring the country to pick up the flying rebels.
They were almost famished with hunger and cold.
It was very well they came to us, as there was no other house in their whole range,
that could have provided food for both men and horses.
They behaved with great civility and thankfulness for their wants being supplied:
they had only a confused idea of Friends,
and inquired whether we came from England or Pennsylvania.
There was only one line of conduct for us to pursue in this situation of affairs;
as it was difficult for us to come at the truth,
whether these men were confederates in the plot, or faithful adherents to the government.
If the government had really been overthrown,
we should not have fared any better for having entertained a loyalist party; and,
on the other hand, if these men had been accomplices in the plot,
we might have been censured by the government.
In either case, we could do no less than relieve the great distress they were in:
and we have every reason to believe, they were true to the government,
as they talked amongst themselves very freely on the subject of the revolt in French,
which they supposed none of my family understood.
They had not been more than two hours with us,
when the appearance of a Cossack riding in haste along the high road,
caused their speedy departure.
We had no further visit,
although the roads were patrolled for several days and nights afterwards.

Thus we have abundant cause to bow in reverent and humble gratitude,
to the God and Father of our Lord Jesus Christ, for mercies innumerable,
and blessings which have from time to time been graciously showered upon us,
far beyond what we can ask or think.
In the midst of a convulsion which has caused such a waste of life,
and which will in a few days terminate the existence of
others only waiting to receive their doom,--and which,
from its extent,
must prove the ruin of thousands who have been
implicated and connected with the rebellion,
we have been permitted to remain undisturbed,
and almost as if nothing had happened;--favoured with resignation and peace of mind,
and supported and comforted beyond the reach of fear.
What can we render in return for such unmerited
favours? In this there is just cause to fear,
lest we should fall short in gratitude and humility of heart; and on this account,
I believe, I daily fear, and daily feel the necessity of prayer,
and am fully persuaded that I stand in need of the prayers of my dear friends in England,
that I may be preserved in watchfulness and faithfulness unto Him,
whose wondrous mercy has never been withheld,
from the days of my youth unto the present hour.^
footnote:[See Appendix B.]

[.letter-heading]
To Balby Monthly Meeting

[.signed-section-context-open]
First Month 19th, 1826, O. S.

[.salutation]
Dear Friends,

In forwarding the annexed answers to the queries at this time,
my heart is bowed down under a sense of the continued loving-kindness of the Lord,
and my own unworthiness to partake of the least of all His tender mercies:
yet I have abundant and renewed cause, to exalt His great and ever excellent name,
and to commemorate His wonderful works to the children of men.
"`Who can declare the mighty acts of the Lord?
Who can show forth all His praise?`" Truly,
in vain would such an attempt be on my part; but duty, gratitude,
and humble admiration prompt me to acknowledge His might, to magnify His power,
and to celebrate His praise, who hath been graciously pleased,
in unmerited compassion and mercy,
to preserve us in peaceful quiet and resignation of mind, beyond the reach of any fear,
except the fear of Him,--at a period replete
with events unusually affecting and appalling,
which have swept many away from this stage of existence, as in a moment,
and plunged thousands into inconceivable anxiety and fearful suspense.
Blessing, and glory, and wisdom, and thanksgiving, and honour, and power, and might,
be ascribed unto Him, who sitteth King for ever,--by all those who live in His fear,
and place their trust and confidence in Him.

And now, my beloved friends,
in a feeling of that love which would gather all to blessedness,
my soul salutes you once again; desiring for all, as for myself,
an establishment on the everlasting foundation, even Jesus Christ,
by and through the revelation of his Holy Spirit, in the secret of every soul.

Although deplorably deficient in this important knowledge,
which I daily feel and daily mourn on my own account;
yet I am fully and awfully persuaded,
that nothing short of this inestimable treasure can
purify from every defilement of flesh and spirit,
and can restore again that heavenly image, defaced and lost by sin and transgression,
in which man was originally created.
Nothing but this can reconcile the trembling soul to God.
Conscious of its own sad need,
my longing heart most ardently desires that all mankind
were brought to feel the force of this great truth,
and to behold its vast importance in the same unflattering mirror which presents it;
but without the same lamentable cause, which makes it doubly precious in my view.
Strong is the desire I feel for myself,
and for every member of our highly professing and highly favoured Society,
that we may so sanctify the Lord God in our hearts,
as to be ready always to give an answer to every man
that asketh a reason of the hope that is in us,
from sensible conviction, with meekness and fear--not from traditional report,
nor from education; nor like those of old,
who were such strangers to the Lord of life and glory,
that "`some said he was John the Baptist, some Elias, and others Jeremias,
or one of the prophets;`" but from the same living and eternal source,
that enabled Simon Peter to say,--"`Thou art the Christ, the Son of the living God.
Jesus said unto him,--Blessed art thou Simon Barjona,
for flesh and blood hath not revealed it unto thee, but my Father which is in heaven:
and I say also unto thee,`" continued our gracious Lord,--"`thou art Peter;
and upon this rock I will build my church,
and the gates of hell shall not prevail against it.`"

If what I have written has the effect of awakening in any of my dear
friends a serious consideration of this important subject,
such as are building upon the immutable rock will not be discouraged or dismayed,
but rather strengthened and confirmed in the hope of a sure and eternal reward.
And should there be any who have neglected to examine the foundation
on which the hope of their everlasting happiness is laid,
let me warn these in the tenderest manner no longer to delay,
not only to enter into a heartfelt inquiry,
but to begin an earnest search,--if happily they
may find the chief and precious corner stone,
elect of God,--whilst the day of visitation is mercifully lengthened out;
lest the night approach, when no man can work; and the language of our blessed Lord,
be sorrowfully applicable,--"`if thou hadst known, even thou, in this thy day,
the things which belong unto thy peace; but now they are hid from thine eyes.`"
But seeing the arms of wondrous and boundless mercy are
ever open to receive the returning penitent,
and the grace of our Lord is indeed exceeding abundant,--none need despair,
who are willing to come unto God by him.
It is indeed a "`faithful saying and worthy of all acceptation,
that Jesus Christ came into the world to save sinners; of whom I am chief.`"

In the love of the gospel, I remain your affectionate friend and brother,

[.signed-section-signature]
Daniel Wheeler

[.letter-heading]
To Richard Cockin, Doncaster

[.signed-section-context-open]
Dated about Fifth Month 30th, 1826.

In the first place, I sincerely congratulate thee on the recovery of thy dear wife,
and in the prospect of her being spared to thee and to her friends a little longer.
I am satisfied there is nothing in this scene of conflict and trial worth remaining for,
but that the will of our good and gracious Lord
God should be perfected in us,--excepting also,
the company of our near and dear connections,
to whom we have been long and affectionately attached:
with every thing else I could readily shake hands, and bid them a farewell for ever;
if but happily in a state of preparation to meet the great and awful event.
On this head, I have many fears, as regards myself,
from a knowledge of my own unworthiness; and I am thoroughly persuaded,
that if an attainment so high should ever be my happy experience,
it must be through the great and unmerited mercy of God in Christ Jesus.

What a change a few months have produced in this country!
The late reigning Empress has only survived her much
lamented husband five months and fifteen days;
she died at Beliof, between Taganrog and Kalouga, about 280 versts south of Moscow.
Her death has been as private, as her life was retired and hidden from the world.
She had arrived at Beliof much exhausted the preceding evening,
and retired to rest pretty soon, and about eleven o`'clock at night became seriously ill.
Her physician was sent for, but from some unaccountable circumstance, could not be found.
On her being informed of this, and that they were about to send off to some distance,
where he was expected to be, she desired them to desist, saying,
'`it is of no consequence.`' She then requested to be left alone;
and nothing further transpired, until three o`'clock in the morning,
when her confidential attendant went softly into her room, to see how she was,
and found to her great astonishment, that nothing remained but the frail tabernacle;
the countenance retained its usual composed and serene appearance,
but the spirit had returned unto God who gave it.
Her many virtues will long live in the memory of those who knew her worth; and,
although she has passed away as one almost unnoticed and unregarded,
yet her memorial is on high, and will never perish.
Her body is expected here about the middle of next month,
and will be laid by the side of her late husband in the Fort.
She had many enemies,
but they were only those whose luxurious habits and vain
inclinations were exposed and restrained by her humble,
simple, and virtuous example.
It may be said, she died generally beloved and regretted, and very deservedly so.
Her decease took place on the 4th of Fifth Month, O. S.

[.letter-heading]
To One Of His Family

[.signed-section-context-open]
Moscow Road, Ninth Month 13th, 1826, O. S.

[.salutation]
My Dear +++_______+++,

I have spent great part of this season on the bogs of Shoosharry,
returning home only on Fourth and Seventh day evenings,
and leaving it again at noon on Fifth, and in the morning on Second days.
I hope that all the drains will be cut before the winter drives us from the work;
but we look for an early winter after so unusually long and hot a summer.
On the 9th instant, we had a frost which froze the water in the drains, and on the 11th,
there was a considerable fall of snow, but it did not lie long.
We have had the advantage of being allowed to burn all the surface rubbish,
moss and brushwood: the large roots are preserved for fuel.
But owing to the uncommon dryness of the season,
we have been unable to burn until lately, for fear of setting the soil itself on fire,
as has been the case in many places around us.
The damage done by fire in the course of the summer is incalculable.
The woods have been on fire for fifty versts together;
in the neighbourhood of Ijora many regiments of soldiers have been employed,
in endeavouring to save the towns and villages:
several of the latter have been destroyed by the devouring element.
At times,
we were alarmed for our own buildings:--in vain
we tried to arrest the progress of the fire,
when at a considerable distance from us; but this could not be done,
as the heat and smoke prevented the people from working when near it;--so
that we were obliged to content ourselves with forming a defence,
in advance of the fire,
at a sufficient distance from the buildings that the flames might not endanger them.
This was done by removing the tree-roots and sods,
in short every thing of a combustible nature, from the surface down to the clay,
in the shape of a semicircle, about three-quarters of a mile in length,
to the edge of which the fire actually came.
Even with this precaution, it was necessary to station watchmen,
as the sparks flew over the barrier and set the earth on fire in several places;
and our safety depended on extinguishing these places immediately,
for if they had once gained strength, it would have been impossible to check them,
as every pool in the neighbourhood was dried up
by the long continuance of heat and drought.
For several weeks we were threatened by this formidable enemy;
but were favoured to escape without accident.

Latterly we have had some fine rains,
and have been burning in the fields at every opportunity.
The rubbish is piled up in lines a fathom wide, and nearly the same in height.
The other day, we had upwards of a mile of them on fire at one time,
which made a singular appearance when night came on.

It is very pleasant to us to hear that the coronation
has been attended with great satisfaction,
far more than was expected.
The unexpected appearance of the Grand Duke Constantine at
Moscow seems to have diffused quietness over the whole empire.
The generality of the people had an idea, that it was without his full concurrence,
that his younger brother was proclaimed Emperor.
We have heard from very good authority,
that the first interview between the two brothers was very affecting;
the behaviour of the Emperor was truly amiable and conciliatory,
whilst that of Constantine gave ample proof of a noble and generous mind.

As they rode together through the streets of Moscow on horseback,
the population of the place were witnesses of the cordiality that subsisted between them;
and shouts of joy resounded through the city.
In the course of a day or two, a review of the troops took place.
The army has been most of all dissatisfied, and were generally of the mind,
that Constantine had been forced aside to make way for his brother;
but when the two brothers made their appearance in front of the troops,
these were fully satisfied,
and their shouts of approbation continued an unreasonable length of time.
It is now generally supposed, that things will go on smoothly,
and that every spark of sedition will be extinguished;
the Emperor will begin to feel himself more firmly seated on his throne,
and will doubtless assume a more decided tone of character:
it will soon be seen what he is; from his abilities, much may be expected that is good.
Much blood was shed on his ascension to the throne;
and it is really wonderful how his life was spared,
when surrounded by violent and desperate men.
I most earnestly desire that he may lastingly remember his then humiliating situation,
and may be disposed to keep near to that power,
which so evidently and remarkably directed his steps,
and delivered him from the hands of his enemies.

[.letter-heading]
To Richard Cockin, Doncaster

[.signed-section-context-open]
Twelfth Month 14th, 1826, O. S.

In vain would it be for me,
to attempt to recount the multiplied favours and
blessings that have been showered down upon us,
since I last wrote.
Perhaps,
some might be disposed to think many of these circumstances too trifling to be noticed,
or if noticed at all, only as things which happen in the common course of events.
But upon my mind they make a different impression;
and I cannot but record them as so many additional
instances of the mercy and protecting care of Him,
without whose knowledge a single sparrow cannot fall to the ground.
At the same time, it is only proper that the effect should be more striking with me,
as few others have witnessed so many great deliverances; and none so unworthy,
in my own estimation, as myself.
I know not how it may be with others, who like myself are past the meridian of life,
and in the common course of nature,
cannot look forward to many days in this state of mutability;
but on looking over the actions and transactions in which I
have been engaged in the course of my pilgrimage,
few indeed are to be found,
that can bear examination when brought before
the penetrating and impartial glass of truth,
and which are altogether divested of selfish motives; although perhaps at the time,
when performed,
they may have afforded sufficient satisfaction to feed the creaturely part,
and keep that alive which ought to have been slain.
But what an unspeakable privilege it is,
that none of these things are permitted to pass unnoticed or lie concealed,
but are from time to time brought into remembrance; whereby self may be abased,
and judgment set over the transgressing nature;
which must not only be brought under condemnation, but must actually die in us,
before the lowly and precious seed can live and reign; which delighteth in purity,
and which will, if suffered to rise into dominion, wash, sanctify,
and justify the believing heart,
that is made willing to submit to the precious influence of its power.
Verily, herein is the love of God manifested, "`in the name of the Lord Jesus,
and by the Spirit of our God,`" through the one, great, sinless, spotless offering,
which hath perfected for ever them that are sanctified.

I regret it is not in my power to gratify thee
with any information as to our future prospects;
but things remain to the present time in the most clouded uncertainty.
My dear friends and my native land are often the subjects of my thoughts.
Sometimes I cannot help cherishing a hope that I may
once more be permitted to return with my beloved family,
and pitch a tent for a short time among them;
but I find it will not do to dwell much upon what I earnestly desire,
as it has only a tendency to unsettle the mind,
and disrobe it of that peaceful resignation,
which I can thankfully acknowledge is often my favoured portion.

The nature of our employment, and the wide field of labour before our view,
in which at times it appears as if we should be called to assist,
create a feeling of dismay; but again circumstances occur, which for a season,
darken any probability of this being the case: so that which ever way I look,
it is but toiling in vain.
"`He that abideth of old,`" only knows what is in store for us;
and unto Him I commit myself and my all: well knowing from long experience,
that a way can be opened, when perhaps there may be less expectation than at other times.
