== Chapter X.

[.chapter-synopsis]
* Address to Balby Monthly Meeting, 1827
* The Emperor Nicholas
* Address to Balby Monthly Meeting, 1828
* General Correspondence

[.embedded-content-document.epistle]
--

[.letter-heading]
To Balby Monthly Meeting

[.signed-section-context-open]
First Month 26th, 1827.

[.salutation]
Dear Friends,

Our little meeting being now reduced to only six members, who are those of my own family,
and three of these in their minority,
we have of late been brought more closely into the solid
consideration of our humiliating and stripped condition.
At our last meeting, under a painful sense of this,
and in a feeling of our peculiar situation and weakness, we were unitedly of the mind,
that the Monthly Meeting would not expect answers to the queries in the usual manner:
as in our apprehension it would be presumptuous to attempt it,
and too much like upholding a lifeless form.
I am therefore requested to give the Monthly Meeting
some general information of its distant members,
in the hope that our dear Friends will not only approve of this conclusion,
but that they will feel as we have felt on the occasion, and concur in its propriety.

But although the answers are not furnished as formerly,
the queries have nevertheless been duly read and considered;
and I trust we have endeavoured,
by individually applying the comprehensive particulars contained therein,
seriously to reflect and examine how far we are
fulfilling the important duties required at our hands,
in the faithful support of our different Christian testimonies.

Notwithstanding our depressed and disqualified situation,
our meetings are regularly kept up as heretofore;
and although some of us may feel at seasons as "`the owl of the desert,`" or
the solitary "`sparrow on the house top,`" yet there are intervals,
when that gracious power is witnessed,
which can set bounds to the tumultuous sea of thought,
and arrest the wandering imagination;--which can not only command the storm,
but at his pleasure rebuke it, and cause the restless waves to be at peace.
It is, my beloved Friends, a sensible evidence of this sustaining help,
that diffuses comfort to the mind in our exiled allotment;
and renders the lonely habitation a peaceful abode;
wherein we are permitted to dwell together in love and harmony,
whilst widely separated from the fostering care and bosom of the church,
and excluded from a share of that tender counsel and advice,
of which others so frequently partake in our highly favoured native land.
And although subject to many privations, and often under feelings of extreme poverty,
weakness and dismay; yet such is the mercy,
the goodness and compassion of a long-suffering and all-gracious God,
"`who maketh his sun to rise on the evil and on the good,
and sendeth rain on the just and on the unjust,`" that
all our wants are and have been abundantly supplied,
through Christ the ever-blessed and only Saviour;
to whom be the glory and the praise forever!

Lest I should be found deficient in love, gratitude, thankfulness,
and devotedness to the great and bountiful Author of
such multiplied and utterly unmerited favours,
the lovingkindness of the Lord maketh me even afraid,
from a deeply engraven sense of my own unworthiness.
In this state I earnestly desire to be preserved; for this,
my spirit often breathes in the language of prayer.
I find it, my dear Friends, a safe hiding place;
it is indeed that food which is most convenient for me, and daily needful,
because it leads into lowliness of mind;
and whilst it chains down self in every appearance,
the tribulated soul is preserved near to the innocent harmless life, which,
dwelling in the light, recoils at the slightest impurity.
Then our wants may all be plainly felt and seen;
how great is the need not only to implore for daily bread,
but for a qualification and disposition to forgive those who trespass against us,
that we also may be forgiven;
and that we may be permitted to feel a portion of that love,
which would gather all into the heavenly garner of rest and peace,--
even the love of God shed abroad to comfort and strengthen our hearts.

I trust in a degree of this love, I once more salute my dear brethren and sisters,
and remain their affectionate Friend,

[.signed-section-signature]
Daniel Wheeler

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John Hipsley, Hull

[.signed-section-context-open]
First Month 29th, 1827.

The Emperor Nicholas is indefatigable in his exertions to
support the interests of his people throughout the empire,
by strictly insisting upon the most rigid adherence to justice in all causes;
which has given great satisfaction.
His leisure hours, at least those absolutely necessary for exercise,
he makes subservient to the general good,
and is daily going about to inspect the hospitals and other public institutions,
in the most minute manner, which has already had a salutary effect.

I may be mistaken,
but I think that he is almost the first crowned
head that ever entered the doors of a prison,
with the benevolent object of inquiring into, and improving its state:
this he has lately done, and not in a superficial manner; having, in many instances,
entered closely into the examination of particular cases with great interest,
and caused many to rejoice in being set free.
This work is carried on without any parade;
he just steps into a sledge with a single horse, and no one knowing where he is going,
of course there can be no preparation made to receive him;
in this manner all are taken by surprise, and the real state of things fairly developed,
whether rough or smooth.
He has a great work before him; and stands in need of that wisdom,
which is better than rubies,
to direct and support him in such an arduous and responsible station.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To David Mallinso, Sheffield

[.signed-section-context-open]
Twelfth Month 7th, 1827.

I have duly received thy letter of the 13th ultimo, which was truly acceptable;
and particularly as it conveyed a more favourable
statement of the health of thyself and thy dear family,
than has been transmitted to us by any of our
correspondents for a considerable time past;
and we shall rejoice to hear, that this inestimable blessing is continued to you all.
It is indeed a blessing we cannot too highly appreciate, or be sufficiently grateful for;
as it enables us to bear the changes and
vicissitudes incident to this state of probation,
with greater calmness and fortitude,
than when both mind and body are suffering at the same time;
which is sometimes in best wisdom permitted to be our portion.
We have also great cause to number our blessings in this respect,
as we have been favoured to enjoy an almost
uninterrupted share of good health for many months past;
which I desire to be found daily sensible of, and humbly to acknowledge.

Thy mention of having visited the Isle of Man,
and of its having been of use to thee and thy dear +++_______+++,
is very pleasant intelligence.
The benefit, I trust, will be lasting to you both.
It brought afresh to my remembrance its rocky coast;
although it is more than forty years since I traversed its bays and harbours.
I was fourteen months on the station in a man-of-war cruiser,
and have good reason to remember Douglas, having been there in a heavy tempest,
when the light-house and eighty feet of the pier
were washed away by the force of the sea.
I was also riding in the bay,
when the Hawk packet of Liverpool was driven in by rough weather;
though at that time a stranger to the treasure she had on board,--having for a passenger,
that dedicated servant of the Lord, Sarah Grubb, on her way to Ireland in 1785.
(See her Journal). But she had finished her
glorious career and received the crown immortal,
some years before I heard of her name, or knew the Society of Friends.
Ramsay bay was another sheltering place, in which we occasionally anchored.
We sometimes stood in close to Castletown; but could not go in for want of water.
At other times, we looked at Peel and Port Iron on the opposite side of the island,
ranging on both sides, from the Point of Aire to the Calf of Man.
But I need not recount particulars, which will afford thee no satisfaction,
nor yield myself any other than painful reflections, in the consideration,
that so much valuable time was wasted,
which ought to have been employed in a more noble and important pursuit;
the fruits of which, I should not now be ashamed of,
nor have to remember with vexation of spirit.

Our dear Friend Jane Doncaster, is greatly to be felt for in the loss of her son,
who was a hopeful young man when I saw him last; and I rather looked at him,
as one likely to be a comfort to his poor mother in the evening of her tribulated day:
she has had many trials, and has borne them with that Christian fortitude and meekness;
which plainly evince in what school she has been taught,
and that her standing is on that sure and eternal foundation,
against which the storms and afflictions of time can make no impression,
beyond that of producing a renewed strain of acceptable devotion,
in the sublime language of "`Thy will be done.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard Cockin, Doncaster

[.signed-section-context-open]
Eleventh Month 16th, 1827.

It is long since I gave my endeared friend a
proof of affectionate remembrance in this way,
yet he may rest assured, this has not arisen from want of inclination.
On the contrary, it is often cause of regret,
that I cannot more frequently enjoy a privilege so congenial to my feelings,
as that of maintaining through this medium,
a more constant social converse with those I dearly love;
and with whom I am favoured at seasons still to feel a precious unity,
although not dwelling amongst my brethren in religious fellowship,
but in a land where nearly all around me seem insensible to such a source of comfort,
consolation, and strength.
This circumstance perhaps,
only serves to render that unity doubly precious to my often drooping mind,
imparting to it a refreshing fragrance,
as of the "`ointment poured forth`" for which my heart rejoices with humble thankfulness.
It is true I have numerous engagements,
which naturally occupy a considerable portion of time, and not a little thought.
But when at liberty from these things, there are hours afforded,
upon which my beloved friends in England have a claim;
and in which much might be done in the way of correspondence,
if it were not for the valley of humiliation in which it is frequently my lot to dwell;
where the past and the future are amply sufficient to
constitute the distress of the present,
and from their vast and awful importance,
cannot fail to absorb in the most appalling manner,
every faculty of sense and feeling in a poor worthless mortal;
and to bring down self into such a state of nothingness and abasement,
that the tossed mind is left almost without a ray of hope,
and ready to doubt whether the smallest progress has
been made towards "`the city which hath foundations,
whose builder and maker is God.`"
In these stripping seasons,
I feel a total incapacity for letter-writing or any
other thing that requires application of the mind;
which would gladly remain in a state of oblivion, rather than again emerge,
and take a part in the things of time.

These dispensations are far from palatable to the creaturely taste,
yet I believe are very wholesome and absolutely needful for all,
who like myself are encumbered with dross and tin;
in order that everything that cannot stand the fire, may be removed out of the way,
and the vessel be cleansed from those impurities,
which render it unfit to contain heavenly treasure.

But if these times of proving and trial,
are permitted in the end to rank amongst those afflictions, of which the Apostle speaks,
that work out for the tribulated soul "`a far more
exceeding and eternal weight of glory,`"--then,
indeed, they will appear light and momentary;
and they will be commemorated with humble gratitude,
as the choicest blessings of redeeming love,
administered in unutterable mercy to the sons
and daughters of men for their eternal welfare:
greatly do I desire to be patiently resigned to
these and all other dispensations yet in store,
however painful to human nature to endure.

Thy letters are at all times very acceptable to us,
and if deprived of such a source of information,
we should remain strangers to much that is
passing relative to the movements of our Friends.
Thy accounts of those dedicated servants,
who are labouring in the excellency of the gospel, for the restoration of backsliders,
and the general promotion of truth and righteousness in the earth,
as well as for the strengthening and comforting of the faithful,
afford much heartfelt satisfaction.
I trust we shall ever feel a lively interest in them,
although excluded from partaking of the refreshment which others are permitted to enjoy,
who have the privilege of picking up the crumbs which fall from the Master`'s table.

I should greatly rejoice,
if I had it in my power to render thee any satisfactory information,
as to the probability of our labours terminating in this country.
It is a subject on which my mind could dwell with great delight;
but when I have suffered myself to indulge in such a pleasant prospect,
I have felt a restraint which has compelled me to desist.
I have however been mercifully favoured with resignation,
in the midst of trials which have befallen us, since our lot has been cast here;
and when from peculiar circumstances,
home and dear relatives and friends have revived to my recollection,
under feelings which made them doubly dear, I have, I think,
uniformly endeavoured to commit myself to the Divine will,
and to behave in some degree "`as a child that is weaned of its mother.`"
But I must ever remember, with longing desires,
those ties of love and long continued friendship,
that neither length of time nor absence can efface or obliterate; and of late,
I have felt my mind in an unusual manner drawn towards my Friends in England,
in the binding influence of that love, which seeks the good of all mankind.
So that I have been almost ready to cherish a belief that the day is not far off,
which may produce a change, and liberate us from these frozen regions;
but when I look around,
it is beyond my finite comprehension to conceive
how such a change is to be brought about.
Yet I have abundant cause to know from marvellous experience,
that all things are possible with Him, who bloweth with his wind,
and the waters flow into every creek and inlet;
and when we are reduced to a thorough sense of our own weakness,
He is sometimes in gracious condescension, pleased to magnify His power,
and show forth His strength, to our humble admiration, far beyond our conception,
and still further beyond our deserts: and, therefore, I desire to wait in patience,
whether it be our lot to depart hence, or to remain in exile.

We have heard no particulars of the death of dear Mary Fairbank; who,
having lived the life of the righteous, has finished her course with joy,
we cannot doubt.
We have just heard of the decease of dear John Kirkham,--another standard-bearer,
summoned from works to rewards.
How many seem to be removed from our poor Society, and others in readiness to depart!
And when we look around for those who are to fill their places,
they seem very thinly scattered up and down.
The prospect is to me very discouraging and gloomy;
but although the fathers and the mothers may be taken away,
and the prophets do not live forever, I am consoled with the recollection,
that a gracious and compassionate Lord God remaineth; whose years fail not,
and whose power is the same today as yesterday, and will forever endure.
He can at his pleasure hasten the day, when a language formerly adopted,
may again be truly applicable;--"`The anointing
which ye have received of him abideth in you,
and ye need not that any man teach you.`"

--

[.embedded-content-document.epistle]
--

[.letter-heading]
To Balby Monthly Meeting

[.signed-section-context-open]
Second Month 4th, 1828.

[.salutation]
Dear Friends,

Being permitted to witness the dawning of another year,
I am desirous of again renewing a correspondence,
so justly due to those with whom I am united in the
bonds of Christian love and religious fellowship;
and unto whom I feel accountable in the same degree,
as if dwelling under their immediate care and oversight, as was once my favoured portion,
in days that are over and past.
Frequently, and I trust fervently, a petition is raised in my heart,
on my own account and on that of my beloved family,
that we may be preserved blameless in life and conversation; lest by any means,
through us, the precious cause of Truth should suffer,
and the important testimonies borne by the Society,
of which we enjoy the privilege of being members,
should be neglected and laid waste in a distant land.

Our meetings are kept up as heretofore,
and although mostly held under feelings of great discouragement and sensible
weakness,--yet there are seasons when a precious solemnity is witnessed amongst us,
which sustains a humble hope,
that the lovingkindness of our gracious Lord is not withdrawn from us,
in this forlorn and solitary situation,
unworthy as we are of partaking in the least of all his tender mercies.

Although it is still my lot to be absent in body from my beloved brethren and sisters,
they are often the endeared companions of my anxious thoughts.
On the present occasion,
my heart expands with a renewed feeling of earnest and
affectionate solicitude for their present and eternal welfare.
"`I write unto you little children,
because your sins are forgiven you for His name`'s sake.
I write unto you, fathers, because ye have known Him that is from the beginning.
I write unto you, young men, because ye are strong,
and because ye have overcome the wicked one.`"
This apostolic language, has unexpectedly fastened upon my mind;
I would to God that it was truly applicable,--comprehending,
not only every member of our religious Society,
but every age and every class of professing Christians, the world over;
then indeed there would be joy and gladness, and a good day,
as "`when the morning stars sang together, and the sons of God shouted for joy.`"
Mourning and heaviness are the present covering of my mind,
arising from fear and jealousy on my own account,
which produce a like feeling on account of others;
lest the day`'s work should not be keeping pace with the day of merciful visitation,
and that woful night of darkness overtake any of us,
when the Spirit of God ceases any longer to strive with his creature man.
"`How often would I have gathered thy children together,
as a hen doth gather her brood under her wings,
and ye would not,`"--was the language of our ever-blessed Redeemer,
when lamenting over the inhabitants of Jerusalem:
and such was his unutterable love and compassion
for the rebellious children of that city,
that on beholding it, he wept; saying, "`If thou hadst known, even thou,
at least in this thy day, the things which belong unto thy peace;
but now they are hid from thine eyes.`"
By this, it doth evidently appear,
that we may withstand the continued offers of Divine love and mercy,
until we are left desolate, and the day of our visitation is passed forever away.
"`If the tree fall toward the south or toward the north,
in the place where the tree falleth, there it shall be.`"
As death leaves us, judgment will find us; "`for there is no work, nor device,
nor knowledge, nor wisdom in the grave,`" whither we are all hastening,
and some of us apparently with lengthened strides.
Whilst reviving these awful and momentous considerations, I feel their vast importance,
and therefore long to impress others with a sense of
the necessity there is for us without procrastination,
(for we know not what a day may bring forth,) to "`use all diligence
to make our calling and election sure,`" before we go hence;
that so we may be amongst the happy number,
who have an entrance ministered abundantly into
the everlasting kingdom of our Lord and Saviour,
Jesus Christ.

Strong is my belief, that there are many amongst my dear Friends, to whom it may be said,
"`your sins are forgiven you,
for His name`'s sake`" who by patient submission to the cleansing and
sanctifying operation of Divine grace in their hearts,
are born again,--are "`become as little children,`" meek and lowly;
whose eyes behold their heavenly Teacher, who seek to know His will;
and in humble resignation of soul, endeavour to perform it.
These can testify from blessed and living experience, that peaceful and easy is his yoke,
light the burden, sweet the rest:
continuing in dedication and obedience to the pointings of duty,
these grow "`from strength to strength,`" from the state of little children,
to that of young men, strong in the Lord and in the power of his might;
because "`the word of God abideth in them, and they have overcome the wicked one.`"
Standing fast in the faith once delivered to the saints,
a more perfect stature is attained, even to that of fathers in the church,
because they "`have known Him that is from the beginning.`"
It is this knowledge that I greatly desire for my dear Friends, as for myself;
and I believe,
that those who have been happily favoured to make the
greatest advancement in this spiritual work,
still find their safety dependent only upon watchfulness and prayer:
nothing else can sustain the life of faith.
The soul cannot be nourished today with manna gathered yesterday;
the brightest gleam of hope soon loses its lustre, unless renewed again;
and no past experience can support the drooping mind,
when fresh trials are permitted to assail us.
It is the Lord alone who can renew and increase our faith, and preserve that alive in us,
which is "`born of Him.`"

I feel a desire which words cannot fully express,
that my dear young Friends may be entreated to engage
in this work of such great and individual importance.
A sacrifice in the morning of life is made with much less difficulty,
than if deferred till the day is more advanced,
and the mind encumbered with the things of this transitory world.
There are many things which although harmless and lawful in themselves,
indispose the mind for the simplicity of the gospel,
keep alive the evil propensities of fallen nature,
and if suffered to occupy that time and those talents
afforded in tender mercy for the most noble purpose,
will have to be remembered at a future day, with "`vexation of spirit.`"
Be willing then, my beloved young Friends,
to retire more frequently than the returning morning,
from the perishing things of time and sense,
to the precious "`gift of God`" in the heart;
and although you may have to descend again and again
into the humiliating depths of painful reflection,
there be willing to abide.
It is in the deep, that "`the mighty works of the Lord`" and his wonders are beheld.
It is here that the mind can clearly discern those things which serve God,
and those which serve him not; and here,
under the weight of trouble and affliction for the past, and anxiety for the future,
the acceptable cry is raised unto Him, who delivereth out of every distress.
The Lord alone is exalted in that day,
and the creature brought low and reduced to that humble childlike state, wherein only,
the knowledge of "`Him that is from the beginning`" is revealed.
Without this saving knowledge,
the ever blessed name of Christ can only be mentioned from hearsay or report;
but with it, you will be enabled to say from heartfelt experience,
that "`Jesus is Lord,`" even your Lord, and that "`by the Holy Ghost.`"
"`This is life eternal, that they might know thee the only true God, and Jesus Christ,
whom thou hast sent`" who is the "`beginning and the end, the first and the last.`"

[.signed-section-closing]
I remain your affectionate friend and brother,

[.signed-section-signature]
Daniel Wheeler

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard Cockin, Doncaster

[.signed-section-context-open]
Plains of Shoosharry, near Petersburg, Tenth Month 14th, 1828.

Thy welcome letter forwarded from the Autumn Quarterly Meeting,
reached me last evening in safety;
and although the perusal of it is not without
administering cause for mourning and lamentation,
yet many parts, at the same time, convey comfortable and consoling information,
and call for thankfulness.

I do not remember hearing, at any previous time,
of so many of our dear Friends moving to and fro with certificates.
There ought to be fruit appearing in many places, for truly much seed has been sown;
and I long that nothing may be permitted to stop its growth, or prevent its flourishing,
to the praise and glory of the great and good Husbandman;
who hath not been wanting in adorable condescension and mercy, to prepare and qualify,
and send forth to labour in his vineyard, both at home and abroad,
many faithful servants,
whose reward will be sure and everlastingly
joyful:--for "`he that reapeth receiveth wages,
and gathereth fruit unto life eternal; that both he that soweth,
and he that reapeth may rejoice together.`"
I think I may say, "`would God, that all the Lord`'s people were prophets;`" then,
whether they are ever called upon to prophesy or not,
the feet of all would be "`shod with the preparation of the gospel of peace which,
it is my belief, all ought to be,
and is the case with all who faithfully maintain the Christian warfare,
and obtain the blessed victory.

Our present residence would be thought by most a lonely one,
as it is several miles from any other house in the midst of a wild country,
and on the margin of a huge bog.
We have no water fit for use, but what is supplied from rain or snow;
and I have several times remembered the many draughts
of pure water that I have enjoyed when at Doncaster,
a glass of which would now be a treat indeed.
We have bored to a great depth in vain;
and from the nature of the sub-soil and other local circumstances, it is not probable,
that any spring will be found in our neighbourhood.
A very bad and almost unfrequented road leads to our habitation,
so that we seldom see the face of a visitor of any kind.
When it was fixed for us to remove hither,
I had the offer of some soldiers to guard the premises, but declined it;
as I consider that watchmen selected from our workmen are quite sufficient.
It is necessary to keep a good look out, as the whole of the premises are built of wood,
and are consequently very inflammable; and as the property belongs to government,
proper precaution is needed both against fire and robbery:
but I trust that my confidence in the all-sufficiency of the
Divine arm (which hath so often and so eminently preserved and
supported us,) will never be at so low an ebb,
as to induce me to place dependence upon the arm of flesh for protection.
Notwithstanding the dreariness of our abode, I should be deficient in gratitude,
if I were to omit saying, that to myself it is a peaceful retreat.
We have been here about four months,
and I do not recollect having been permitted to enjoy so much solid peace and comfort,
since my lot has been cast in this land,
as hath been at seasons graciously vouchsafed
within the wooden walls of our solitary mansion;
and I believe my wife has partaken equally with
myself in this comforting and precious privilege.
So that our greatest difficulties, which might appear to others like mountains,
are happily nothing but mole-hills,
and not worth recording for a moment in our remembrance;
except as they serve to keep us in an humble and dependent state of mind,
and produce the grateful tribute of thanksgiving and praise to an omnipotent, omniscient,
and omnipresent Lord God, for all the blessings, comforts and benefits,
which are permitted to descend upon the heads of such poor unworthy creatures.

I often feel a longing desire that a path would clearly open,
which would lead to a peaceful departure from this our exile; but, I trust,
that such a desire is never cherished, or dwelt upon,
without being accompanied by a willingness to submit, in humble resignation,
to the Divine disposal of Him, who knows best what is best for us; who knows our frame,
that we are but dust, and who pities our weakness.
If I know my own heart, no earthly motive, no plans for the future,
induce a desire to be released from this country;
but I do most earnestly desire that the remainder of my days, whether many or few,
may be devoted to the glory of God,
and the exaltation of my dear Redeemer`'s kingdom in the hearts of mankind,--
I need not add--and to the eternal welfare of my fellow creatures,
because the last must be the result of the first.
Ease and indulgence, I think, I despise;
although I sensibly feel the decay of this frail tabernacle.
My sight has failed considerably since I was last in England,
my limbs are stiffened by the damp to which I am daily exposed,
and are subject to pains on every approaching change in the weather;
and I find my strength is unequal to the fatigue, which but a few years back,
I could bear with cheerfulness, if not with pleasure.
But in the midst of all, my soul ventureth to hope in the goodness and mercy of God,
and that, through the merits of a crucified Saviour,
my sins--even mine--will be blotted out.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Smith, Sheffield

[.signed-section-context-open]
Twelfth Month 15th, 1828.

Although no great length of time has elapsed since some of my family wrote to thee,
yet I feel inclined to renew an assurance of unabated love and regard; which,
though not often expressed, never ceases to dwell in our hearts towards thee.
I desire to record with humble thankfulness to the All-merciful Dispenser,
the inestimable blessing of health, which is at this time our portion;
and I trust that thou art permitted to partake in the same enjoyment.

Thou art probably aware,
that we have changed our residence to a greater distance from the city,
than where we lived for the last eight years.
This has had the unavoidable effect of dividing our family,
and depriving us of the constant society of each other,
which is a privilege we have greatly enjoyed.
From the extent of our work, it was necessary,
in order to keep all the branches in proper motion,
to station some one in a central position,
and William being in all respects the most capable, remains at that post.
Although thus circumstanced, and living in a most dreary situation,
we are favoured with resignation and contentment of mind;
which sweeten the cup of solitude, and make the frozen desert a peaceful abode.
The longest span of life is short;
and to such as like myself cannot look forward to the addition of many years,
it is of little moment where we are scattered:
and if we bring into view the humiliating situation of the Lord of life and glory,
who "`had not where to lay his head,`" a quiet dwelling place in any part of
the habitable earth is more than a poor sinful mortal is entitled to,
and much more than he deserves.

I am now more than a month entered into my 58th year; and I think that thou,
my dear friend, art as far, or perhaps farther advanced towards the end of the race.
I often look round at my contemporaries,
particularly those whom I have long known and loved;
but am placed beyond the practicability of any thing like comparing notes with them,
on a subject in which we are all so deeply interested,
and on which nothing less is depending than the prize immortal.
If a sensibility of weakness, and a consciousness of utter unworthiness,
under a feeling of increasing bodily infirmity, can entitle any one to boast,
then I think it is allowable for me; for truly I am a very poor creature every way.
But when I contemplate the glorious gospel dispensation,
and reflect that a thoughtless being like myself,
nurtured in the very school of vice and folly, should ever have been brought,
in any degree, under its benign and saving influence,--it is marvellous in my view,
and none other than "`the Lord`'s doing.`"
It is easy for me to say, what can I render to Him? But the question is,
what have I rendered to Him? Here is an appalling query
indeed,--the consideration of which,
makes me shrink into nothingness,
and into fear of having fallen short of making an adequate return,
not only of humble adoration, gratitude and praise for such amazing mercy,
but lest dedication and obedience have not kept pace with the
knowledge that has been from time to time bestowed upon me.
At times,
a ray of comfort is permitted to glimmer on my drooping mind for a short duration;
but soon it is again veiled by self-abasing clouds of suspense,
which darken the whole atmosphere of hope.

But although I have thus to go mourning on my way,
yet a testimony lives in my heart to the all-sufficiency of that Divine grace,
by which "`I am what I am,`"--though nothing but a worm; and with my latest breath,
I would commend all mankind to seek after this pearl of endless treasure.

It appears to me, that there are many in the present day,
whose minds are constantly kept afloat by the great variety of
publications almost daily issuing from the press.
Many of these that I have seen,
although replete with moral sentiment and learned remarks,
which are not without Scripture foundation,--although very wide of
the true intent and meaning of the text,--are strongly calculated to
keep their readers in search of the lifeless shadow,
and to divert their attention from the living and eternal substance.
There are other persons again, who hare actually commenced a reform in great sincerity,
and have been drawn into solid and serious reflection; but these unhappily,
frequently fall into the way of a class of people,
whose writings and conversation lead them to expect,
that when they embrace the religion of Jesus,
they will immediately witness some delightful sensations of heavenly joy.
But, alas! they calculate on the reward before the warfare is begun.
If such, for a short season persist in communing with their own hearts, and are,
through condescending love and mercy, favoured to draw near to the Saviour of men,
their expectation is disappointed;
and they find that "`He is without form or comeliness,`"
and hath no "`beauty`" to make him desirable.
There is nothing to feed and support those airy and fantastic notions,
which their minds have previously and so perniciously imbibed.
Thus the inestimable pearl is overlooked,
or set at nought;--the language of the prophet is verified, and the blessed Master is,
I fear, at this day, by too many in this way, "`despised and rejected of men.`"

I am apprehensive,
that the enemy of mankind was never more effectually served than at the present time,
and in a way most admirably adapted to the refinement of the age in which we live.
The facilities for holding up the letter of the gospel,
were perhaps never before equalled at any period;
nor greater eagerness generally evinced to peruse and swallow the fascinating baits,
(particularly when garnished with declarations from the
undefiled lip of Truth,) which serve to amuse and allure;
and by their painful and deadening effect upon the mind,
prevent its coming under the influence of that pure and
"`quickening Spirit,`" which only giveth life.
By this stratagem, an easy and broad way is open for the poor deluded traveller,
so well accommodated to flesh and blood,
that there might seem to be no necessity for any to "`strive to enter in at
the strait gate,`" and yet the exaltation of the Saviour`'s kingdom,
is professedly the object of many of these authors,
without pointing out where it is to be found,
and the terms on which only it is to be obtained.
Regenerating grace is hinted at; but self-denial, and the daily cross,
are seldom heard of.
I am often bowed down under the consideration of these things,
and of what will be the end thereof; and am sometimes ready to conclude,
that a day of calamity will come,
when these chaffy imaginations and beguiling inventions will
be dispersed like withered leaves before an autumn blast;
when the minds of men will be brought low,
and humbled under the necessity of turning to Him,
who hath been so long smitten and afflicted,
and be made willing to sit under His holy teaching.
That so all men may be brought to know Him in all His heavenly offices,
not only as a reprover and convincer of sin, but as a Comforter,
and a gracious Redeemer indeed: and may the Lord hasten the dawning of that glorious day,
when He,
who "`was despised and rejected of men,`" shall become
the chiefest of ten thousand and altogether lovely,
saith my soul.

I should much like to know how thou farest amid the storms of time; thy day, I am aware,
hath not passed over without its trials;
but few persons have moved on more quietly and uncomplainingly than thyself,
and I trust the evening is peaceful and serene.

From the long continuance of severe cold, which we have witnessed,
I think it must have been felt in every part of Europe.
There has not been so intense a frost for so long a time together,
since we have been in Russia.
It was really impossible to make the house sufficiently warm;
so that we have had a suffering time, but have been mercifully supported through it,
and have renewed cause to be humble and thankful.

I don`'t know whether thou wilt be able to make out this scrawl;
but I cannot see to mend pens as formerly,
and in other respects the earthly tabernacle is failing;
which must be looked for as the awful moment draws nigh,
which I desire daily to keep in view.
No prospect of liberation^
footnote:[From his engagement in Russia.]
yet appears; perhaps it is too much longed for;
and the will of the creature must be slain, that the will of the Lord may be done,
and His name glorified.

Farewell, my dear friend; may heavenly goodness encircle, and comfort,
and strengthen thy heart.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
Shooshany, Third Month 15th, 1829.

Our mutual friend +++_______+++, who went last spring to the South of France and Switzerland,
for the benefit of his health, has lately returned to this neighbourhood,
quite recruited.
He says, that in several parts where he has been,
there are many people seriously disposed, and hungering after substantial food;
but it appears from his description,
that they are nearly all looking outward for that which can only be found within.
Many or most of them are expecting the millenium shortly to come;
and I believe none are so difficult to persuade as these,
where this peaceful reign is to take place; for their expectation is altogether outward,
and they consider the idea of looking into their own hearts, to find it there,
is quite presumptuous.
Nothing short of a great out-pouring of the Holy Spirit, it is said, will do for them;
but it is my belief,
that nothing but a day of calamity will bring these and many others to their senses.

I find, by a letter lately received from England,
that an eventful period is thought to be at hand for Christendom;
and perhaps the bringing forward again of the Catholic question, in the House of Commons,
may add a little to this apprehension.
The signs and seasons most certainly indicate great events; but whilst pride,
hardness of heart, excess and luxury, so generally prevail,
to which may be added the almost universal disbelief that the kingdom is within,
what can be expected but desolation? Our blessed Saviour foretold,
that many should come in his name and deceive many, with, "`Lo, here is Christ, or lo,
he is there.`"
I cannot help thinking,
that the signs of the present times bear a
striking resemblance to what was thus foretold:
for truly, there is great profession of religion in the present day;
and amongst the various professors,
scarcely any but who recognise the name of our blessed Lord;
but how few the number of those that are his followers
upon the terms He prescribed,--in a life of self-denial,
and the daily cross; or that can believe in that faith, which works by love,
to the purifying of the heart.
We often hear of declensions in the church,
which are said to have occurred in the long dark night of apostacy;
as if that night had passed away, and the true gospel light now shone,
and that day had dawned, which hath restored all things to their primitive beauty.
But, alas!
I cannot help fearing, that the apostacy still continues;
only the shade of darkness is a little varied from what it was,
and things rendered more plausible by this variation.
I verily believe,
that the light of the glorious gospel would shine forth abundantly in the present day,
if man would but look where it is to be seen; but instead of this, how many,
by not keeping their spiritual eye turned towards it, behold nothing but the shadow,
and yet think they are in possession of the substance.
For true it is, as regards the sun or moon in the outward firmament,
so long as we look directly towards them, we see no shadow;
but if we turn a little on one side, immediately the shadow begins to appear,
and if we turn our back on them altogether, it is all shadow,
and the substance is lost to our view.
I remember a simile of this kind, drawn by an eminent servant of the Lord in his day,
who has long since been numbered with the just of all generations, very descriptive,
and very applicable and beautiful.

There is no part of our dear Redeemer`'s doctrine, in my estimation, more plain, simple,
and easy to be understood, and less wrapped up in metaphor or parable,
than that the kingdom is within.
When he was demanded of the Pharisees, when the kingdom of God should come,
he answered them and said, "`The kingdom of God cometh not with observation,
neither shall they say,
Lo here! or lo there! for behold the kingdom of God is within you`"--again,
"`and I will pray the Father, and He shall give you another Comforter;
that he may abide with you forever: even the Spirit of Truth,
whom the world cannot receive, because it seeth him not, neither knoweth him;
but ye know him, for he dwelleth with you, and shall be in you.
I will not leave you comfortless, I will come to you.`"
Can there be any thing more clear and decisive than these assertions? And yet if we
read over the modern writings of men in high esteem for learning and piety,
we can scarcely find any allusion to them.
Much is said about fundamental doctrine and faith; but in many instances,
true faith seems altogether lost sight of,
and what are called the doctrines of the gospel brought into view, and I had nearly said,
substituted in lieu of faith.

Every sect of Christians seems to have its own peculiar faith or belief;
but the apostle tells us only of "`one Lord, one faith,
one baptism`" and all who profess any other faith than that of the apostle`'s,
must certainly be in a state of apostacy from the true, living, gospel faith.
Now until mankind are brought to an acknowledgment of the one true and holy faith,
it is no wonder that things remain in their present state;
and whilst they are thus permitted to continue,
in my apprehension "`the abomination of desolation`" is still set up,
and stands where it ought not,--even in the holy place,
or in the place where true and vital religion ought to stand, instead thereof.
It is no marvel then that the earth is so destitute of the presence of the Lord,
in whose presence only there is life.

I have no doubt that many are acting in great
simplicity of heart and sincerity of intention,
but certainly without proper reflection and due consideration,
on a subject of such eternal consequence.
If people were but willing to "`cease from man,
whose breath is in his nostrils,`" and turn inward to
the unflattering witness for God--the precious gift,
which as "`a light in a dark place,`" shineth more or less in every heart,
they would certainly be favoured in due time to discover where they are,
and in what they are trusting.
But poor finite man, in his natural strength and wisdom, can never effect this:
nothing short of an Almighty power can open the blind eyes,
and change the stony heart to a heart of flesh,
capable of receiving the impressions of the everlasting and unchangeable Truth.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John Hipsley, Hull

[.signed-section-context-open]
Fourth Month 2nd, 1829.

The signs and seasons with us are very appalling,
and strongly indicate an eventful period.
Some think that there will be a great outpouring of the Spirit;
others are looking for the millenium; but in the present state of affairs,
a day of calamity, to bring the unstable world to their senses,
in my apprehension is likely to take place, to check the torrent of vice and dissipation,
to silence the "`Lo! here,`" and "`Lo! there`"--and
banish from the earth those desolating scourges,
which make it so destitute of the presence of the Lord.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To David Mallinson, Sheffield

[.signed-section-context-open]
Shoosharry, Tenth Month 11th, 1829.

The removal of my beloved sister, Barbara Hoyland, has been very affecting,
and the more so, because our situation precluded our hearing of the awful event,
until several weeks after it took place.
Mary Hustler has kindly transcribed and forwarded to me the expressions,
which dropped from her lips at different times during her last days,
many of which are deeply instructive.
Her trials and afflictions have been many; but there is strong consolation in believing,
that they have worked for her "`a far more exceeding and eternal
weight of glory`" and that through the mercy of God in Christ Jesus,
her tribulated spirit now resteth in the joy of its Lord.
What poor short-sighted creatures we are!
I little thought, when parting with my dear sister in Liverpool,
on my return from Ireland, that it was a last farewell:
but I desire to bow in humble resignation to His Divine will, which is ever excellent;
and reverently and thankfully to bless His holy name,
who by the powerful operation of His all-sufficient grace, made her what she was.

What a variety of changes we have both witnessed,
since children together under the parental roof,
from which we were severed at an early age, by the loss of both father and mother,
and left in an orphan state to struggle in a wide and wicked world.
Many years have now passed away,
since we found a shelter in the bosom of our highly favoured Society;
but still changes have been our portion, though of different kinds,
yet all permitted in wondrous mercy, and ought to be sufficient abundantly to show,
that here there is "`no continuing city.`"
My beloved sister is now beyond the reach of conflict, where pain and sorrow cannot come;
and as she drew near the boundary of time,
she was mercifully supported by the everlasting arm of strength,
that sure foundation and eternal rock, Christ Jesus, in whom she had believed.
She is gone! but I am left a little longer,
a living monument of the same matchless mercy: and although encompassed by human frailty,
and conscious of manifold deficiencies,
yet I am enabled to testify for the encouragement of others,
that beyond the shadow of a doubt it is no
"`cunningly devised fable`" which we have followed,
but a glorious reality;
of which I feel more and more anxious that all should come to the saving knowledge,
and partake of the blessed and peaceful enjoyment thereof.

Since taking up my pen to address thee,
I have felt particularly interested on behalf of the dear young people of thy family,
with whom my heart seems interwoven, with an affectionate solicitude,
which words fall short either to express or convey to its full extent;
that they may unceasingly labour to know and experience for themselves individually,
the secret working of that power in their hearts, which is Divine;
and may be willing to dwell under its purifying influence,
until all things are subdued and brought into subjection to His holy will,
whose exclusive right it is to rule and reign in the hearts of the children
of men:--"`of the increase of His government and peace there shall be no end;`"
for the kingdom of Christ Jesus is an everlasting kingdom,
and the covenant made with the house of Jacob an everlasting covenant,
universal and ever new, in and through its blessed and holy Mediator.
There can be no stronger proof of sincerity in those who desire to fear, love,
and serve a good and gracious God,
than their perseveringly endeavouring to wait upon Him,
in a watchful humble state of mind; not only at set times and on particular occasions,
but making it at all times the chief business of their lives.
His unslumbering eye is ever open to regard the most feeble effort of the weakest child:
every gracious promise will be fulfilled for His great name`'s sake;--
"`They shall renew their strength,`"--"`they shall not be ashamed;`"--
the cry of wrestling nature will be heard on high,
by Him "`that speaketh in righteousness,
and is mighty to save,`" and "`able to deliver.`"
He will deliver from the horrible pit of sin, and from the things of time,
which cling like the adhesive miry clay:--yea,
He will set their feet upon an everlasting rock,
against which the combined powers of darkness in
vain may beat:--He will establish their goings,
and put the new song of praise in the mouth of
all who diligently and patiently wait for Him.
The heart is the field in which the hidden treasure lies;
and such is its inestimable value, that nothing short of all that a man hath,
can purchase it.
All must be surrendered to obtain the heavenly pearl:
the whole is required without reserve.
And what is all that we possess, when compared with the stupendous act of suffering love,
that purchased our redemption? it lies in a small compass,
yet it is capable of frustrating the Divine intention,
and therefore is of vast importance;
and I believe the unsubjugated will of the creature comprehends the whole.
Not a word or an action, which fills the catalogue of the deeds of the body,
can be conceived and performed without the assent and
will of the creature,--all have their origin in thought;
and therefore the ever-blessed Master at once pointed out a
remedy against every temptation to which we are liable,
in the general injunction,--"`What I say unto you, I say unto all, watch.`"
Here then is the Christian`'s only tower of safety, and the path that leads to prayer.
Oh! that I could induce all to this engagement of mind:
the tendency of every thought would be discovered by the light which shineth in darkness;
whatsoever is earthly and sensual,
and even the tendency of the heart in the natural state,
would be exposed;--"`the lust of the flesh, the lust of the eye,
and the pride of life,`" would be clearly distinguished to be "`not of the Father,
but of the world,`"--which "`passeth away, and the lust thereof:
but he that doeth the will of God, abideth forever.`"
Those who steadily and carefully maintain the watch,
will be strengthened to suppress every intrusive thought,
and will be more and more placed in a capacity to wait;
for there cannot be a true waiting, without a ceasing from our own imaginations,
that God may be all in all: in whose presence only there is life, and love, and peace,
and joy,--the blessed reward of all those, who fear, serve, and love Him,
in his inward appearance.

I was not intending to say so much, when I began with this subject,
but I think my pen could not be employed in a better cause, or for a better Master:
at the same time believing, that it will be accepted in the same love,
that prompted me to write it.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend, (residing In Finland.)

[.signed-section-context-open]
Shoosharry, Eleventh Month 29th, 1829.

I enclose the Yearly Meeting`'s Epistle,
and trust the perusal of it will afford thee satisfaction,
as it appears that assembly was owned by the great Head of his church,
to the consolation and comfort of the upright and faithful standard-bearers.
But O! my dear friend, I am fearful lest thou shouldest suppose,
that the number of those to whom is committed the weight of the law and of the testimony,
is larger amongst us, than is really the case.
It is a sorrowful fact, but not the less true,
that there are but "`two or three berries in the top of the uppermost bough,
four or five in the outmost fruitful branches thereof,`"
in the present day of our once flourishing Society:
it is indeed a truly mournful consideration, when we look back at what it was,
in the day when it first came forth.
If we look at the ancient writings of Friends,
we shall find that originally the Society consisted
wholly of such as had joined by convincement,
and were actually in possession of what they professed to be led and guided by.
When these were gathered to their everlasting rest,
their children became the burden-bearers:
many of whom stood firm to the principles of their fathers,
and the cause of Truth was precious in their eyes.
As this generation passed away, others sprung up, who entered into the privileges,
to procure which their worthy predecessors had laboured and suffered:
thus the Society gradually became composed mainly of members by birth-right.
Then persecution ceased in great measure, and worldly prosperity,
accompanied with ease and indulgence followed:
combining to induce a relaxation in their vigilance against
the attacks of the great enemy of man`'s happiness;
who did not fail to avail himself of the opportunity,
more widely and cunningly to spread his snares and baits against a people, who, perhaps,
of all others, had the most contributed to undermine his kingdom;
as it is always his aim to attack those from whom he is
the most in danger of being kept at a distance.
There is no need for him to be jealous of such as are the "`children
of disobedience,`" in whose hearts he already rules and reigns:
they may go on their way quietly, as he has them safe enough.
In this manner, things have been getting worse and worse, until unhappily it may be said,
that, to a great and lamentable degree, the glory has departed from our Israel,
and little is now left us but a name.

The picture which I have laid before thee is a very discouraging and appalling one;
but I was afraid of thy being dazzled by that which only glitters,
and is not the pure gold that has been tried in the fire.
Notwithstanding things are in this deplorable condition,
"`the foundation standeth sure,`"--the Rock of ages remains unimpaired,
and cannot change;
the precious seal is yet unbroken,--"`the Lord knoweth them that are his;`" and
there is a little remnant yet preserved alive in that which lives forever,
who are enabled to call Jesus their Lord, and that by the Holy Ghost.

The present state of our religious Society, in my apprehension,
very strikingly resembles that of the Jewish nation in
former days:--they were a highly favoured people;
and our Society has been favoured in a very eminent degree:--both have proved
themselves unworthy of the tender regard and mercy of a long-suffering Lord God.
I need not mention the final overthrow of the Jews to thee,
who art so well versed in these things; but it is my belief,
that unless the Father of mercies is pleased to stretch out his everlasting arm,
either to produce a thorough change in the hearts of our members,
or to send a day of winnowing that will scatter and disperse
the chaffy spirit that so widely and alarmingly prevails,
so that none can stand but such as are upon the true foundation;--I say, I believe,
that unless there is an interference superior to the power of man,
the major part of our members will be amalgamated with the general mass of the people,
when a few more fleeting years have passed away.
But as in the destruction of Jerusalem,
there was a place of refuge provided for the faithful Christians; so I humbly trust,
that if the bulk of our Society should be scattered, there will be a Pella^
footnote:[See Eusebius.]
cast up for the honest-hearted amongst us:
for the Lord will never forsake those that put their trust and confidence in him.

I remember a remark once made to me by an honest Friend in London,
during the time of the Yearly Meeting; he was probably lamenting the low state of things,
when I said, "`What would have become of me,
if it had not been for our Society?`" To which he replied,
"`What would have become of the Society,
if it were not for those who have come in by convincement?`" I
have since thought there is a great deal in what he said;
for I believe, many who have come in by convincement,
have been greatly instrumental in keeping the building together.
An individual thoroughly convinced of our principles,
and keeping close to that which has convinced him, will undoubtedly,
as he continues faithful, be converted by it;
and one such person is certainly of more value in the Society,
than many who are mere nominal members by birth-right only.
Such as these have bought the Truth,
at the price of becoming fools before men for Christ`'s sake:
they have believed in the sufficiency of His power revealed in the heart,
to cleanse and purify them from all sin;
and although they may have had to pass through many conflicts,
occasionally for several years, without appearing to gain any ground,
they have been strengthened to persevere, and still to wait for Him.
The weight of former sins and transgressions has been long and painfully
felt to rise in humiliating retrospect before the view of the mind,
time after time, in terrible array; working for each,
true sorrow and repentance never to be repented of.
But although at seasons he is ready to faint,
when faith and hope have been reduced to a low ebb,
yet the invisible arm of strength is still underneath unseen and unfelt,
supporting the tribulated traveller in the apparently unequal warfare:
until every sin has passed before-hand to judgment;
and at last the glorious day begins to dawn, when He, who has been "`as a refiner`'s fire,
and like fuller`'s soap,`" before whom nothing can stand (of a transgressing
nature) "`when he appeareth,`" or can "`abide the day of his coming,`"--is
now discovered to be "`the sun of righteousness`" arisen "`with healing in
his wings,`" to the joy and comfort of the wounded soul.
Then the love of God is truly known;
and until this blessed day is felt in the great and heartfelt work of regeneration,
none can experimentally and truly say,
that "`God is love:`"--they are mere words to all who have not
witnessed the inward workings of his power in their heart:--but now,
they feel him to be a God of love and mercy too,
and are renewedly made willing in the love of Him to wait for Him.
In this waiting, watchful frame of mind,
we come to the place where true prayer is wont to be made;
which rises as sweet incense before the throne of grace, because not of our creating.
Here is the Christian`'s watchtower,--his only place of safety,
which was pointed out by our ever blessed Lord to all,--"`What I say unto you,
I say unto all, watch:`"--again, "`watch and pray, lest ye enter into temptation.`"
The soul that faithfully watches, cannot be long without praying;
although but in the language of a sigh.
It is enjoined also by the great apostle,
where he says,--"`praying always with all prayer and supplication in the Spirit,
and watching thereunto with all perseverance.`"
Here every thought is detected in the light of Christ, and brought to judgment,
and into the obedience of Him, who casteth down every imagination,
and every high thing that exalteth itself against the knowledge of
God,--to the pulling down the strong holds of sin and Satan.

It is such as these, my dear friend, who have thus far advanced in the heavenly race,
that have had their hearts directed "`into the love of God,
and into the patient waiting for Christ;`" which, I trust, thou hast in part,
if not wholly, witnessed: and I think thou wilt agree with me,
that a single individual coming into our Society thus convinced,
and thus converted to the true faith in Jesus Christ, is of more value to it,
than a hundred members who have nothing to show but a birth-right.
And it is these that have followed their Lord and Master in the regeneration,
that are qualified from heartfelt experience to be employed in his service,
if it be His will to call for them,
and send them to speak a word in due season to others.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Son Joshua

[.signed-section-context-open]
Twelfth Month 12th, 1829.

What an unaccountable thing it is,
that when such pains are being taken to educate the lower orders of the people,
and such an earnestness apparent in pursuing plans of philanthropy and benevolence,
as has never been equalled in any former age,
and so many efforts made to spread the knowledge of the gospel;
yet there should be so bold a front and an atrocity in crime,
surpassing even barbarous and uncivilized nations!
To me, it seems as if many people were sensible of the tottering situation we are in,
and thought it necessary to be doing something that in
their apprehensions will be productive of good.

As to the increased efforts to spread the knowledge of the gospel,
but little fruit can be expected,
so long as they continue to be so blended with the inventions and contrivance of man.
I verily believe this is one great means of preventing the
people from coming to a knowledge of the true gospel,
which remains to be "`the power of God unto salvation.`"
If the minds of the people were turned to an inward and vital knowledge of this work,
there would be some hope;
provided the teachers themselves were really called to and qualified for the work;
and not, as is to be feared too many of them are,
strangers to the inward work themselves.

In my apprehension nothing short of a day of
calamity will bring the people to their senses,
and reduce them to a state of simplicity and humility;
which in the end would prove an unspeakable blessing,
if happily it were the means of turning their attention
to the true Teacher in their own hearts,
who giveth life to those that hear and obey him,
and would cause them to "`cease from man whose breath is in his
nostrils,`" by whom they have been so long kept in darkness.
That so those abominations which are set up,
and standing in the place of the true Christian religion,
and which make the earth so destitute of the presence of the Lord,
may forever be swept away from its surface.

Should such a day be permitted,
it will certainly try the members of our highly professing Society,
and show who are on the foundation that standeth sure;
these will be preserved as in the hollow of the Lord`'s hand,
from "`the blast of the terrible ones;`" but the chaff,--such
as have nothing but an empty profession to stand upon,
will assuredly be scattered before the storm.

To hear of thy welfare in those things that are of eternal consequence,
is the principal desire of my heart for thee; without this,
worldly prosperity will avail nothing in the great day of account.
But, little is enough, when our desires are bounded by moderation;
and I am fully persuaded that no good and necessary
thing will be withheld from them that walk uprightly.
As for myself, I can truly say, that when I began business, I had no artificial wants,
and my real wants were very few.
I never studied to keep up appearances, and be like other people;
all around me knew that I had but small means, and I made no other pretensions.
I endeavoured, I think, to the best of my ability to seek the Lord,
and positively did not look beyond a sufficiency of food and raiment;
and although an utter stranger to business in every shape,
yet my way was made prosperous; though perhaps what I thought prosperity,
would be despised by most in the present day, and probably by many in that day also.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To One of His Children

[.signed-section-context-open]
Shoosharry, Twelfth Month 18th, 1829.

[.salutation]
My Dear +++_______+++,

Truly there is nothing in this fading world to be
compared with an inheritance in another and a better,
which is to come, and into which we none of us know how soon we may be summoned.
But if we be happily found amongst the number of those who "`fear God
and work righteousness,`" we shall most assuredly "`be accepted of
him;`" and shall praise His great and ever excellent name through the
never ending ages of a glorious eternity:
which is my frequent and earnest prayer for us all.

The great apostle also enjoins "`praying always,
with all prayer and supplication in the Spirit, and watching thereunto.`"
What a privilege it is that we have this in our power at all times,
out of meetings as well as in meetings, and on all occasions whatsoever;
and as we know for our encouragement,
that we are constantly day and night in the presence of Him, "`in whom we live, and move,
and have our being,`" who "`knoweth the thoughts and intents of the heart;`"
we shall in this inward exercise be preserved in His fear and in His love:
for the Shepherd of Israel neither slumbers nor
sleeps,--His watchful eye is never closed.

Thou, no doubt, art present regularly during the family readings of the Scriptures;
but I would advise thee to read a portion in them every night before retiring to rest,
with an earnest desire, that it may be given thee to understand them:
for they will be but as a dead letter,
without the assistance of the Holy Spirit which gave them forth; with it,
they will afford thee great instruction and consolation,
and thou wilt be taught the true meaning and application of them.
They are the only treasure worth storing in memory:
this I can truly testify from long and sensible experience.

I have lately received a letter from thy uncle Charles,
giving but a poor account of his health, and that of thy aunt: they, like myself,
and thy dear mother, are feeling the infirmities attendant on advanced age;
and I hope these will serve as warnings to stir us all up,
to endeavour to be prepared for the change, that will certainly overtake us;
that we may be like the wise virgins,
provided with "`oil in our vessels with our lamps.`"

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Richard Cockin

[.signed-section-context-open]
Shoosharry, Fourth Month 30th, 1830, O. S.

Thy letter was, indeed, most heartily welcome to us all,
and as the harbinger of another returning spring,
afforded us much comfort and consolation,
after the long winter that has just passed over our heads.

Our work upon the land was suspended by the frost six months and nine days;
and if we reckon the rough weather previously to the setting in of the frost,
with what we have lately had, the winter has been more than seven months in length.

At the time when I have usually written to Balby Monthly Meeting,
I was not unmindful of my dear friends;
but alas! we were all laid by with sickness just then.
This, however, as to myself, was not of long duration;
but I found my mind entirely closed up,
not having a sentence of any kind to transmit to the meeting;
and yet I never witnessed a greater weight of exercise than at that period,
which remained with me for several weeks afterwards, and is yet at seasons my portion.
Thy letter has been particularly comforting to me on this head,
because it is now very evident,
that any communication from me would have been out of its place,
and altogether out of season,
and must have clashed with the address from dear Mary Hargreaves;
and the blessed Master is not the author of confusion but of peace,
and that in all the churches.
I wish to enjoy the privilege of being a member of Balby Monthly Meeting,
and therefore request on behalf of my family and self,
that thou wilt procure for us a copy of the address.

--
