== Chapter XIII.

[.chapter-synopsis]
* Prospect of Distant Religious Service
* Resigns His Appointment In Russia
* Leaves His Family, and Sails For England, 1832
* His Prospect of Visiting in Gospel Love the Inhabitants of Some of the South Sea Islands, etc., Laid Before His Friends

[.offset]
+++[+++About this time, under a prospect of distant religious service,
our dear father believed it right to resign his appointment under the Russian government,
and to repair to his native country.
The commencement and progress of this movement,
are alluded to in the following extracts from his letters.]

[.embedded-content-document.letter]
--

[.letter-heading]
To John Hipsley, Hull

[.signed-section-context-open]
Seventh Month 5th, 1832, O. S.

I hinted to thee some time back, the probability of a change being about to take place,
as to our prospects in this country; which is now so far developed,
as to enable me to inform thee, with some little certainty, how things are going on.

For many months past,
it has clearly appeared to be my duty to relinquish my engagements in this land;
and as way has from time to time opened,
I have gradually moved forward under this apprehension; and have been mercifully,
peacefully, and abundantly confirmed in this step, by the difficulties,
which at first appeared too mountainous to be overcome,
having shrunk into insignificant mole-hills, as the time approached to encounter them.
Now every obstacle seems to be removed: I have, I think, proceeded throughout,
as things were opened before me, consulting with my beloved family,
as each succeeding step has been taken; and in every instance,
what has been proposed to them, has found a place in their minds, and been assented to.
To break up all at once an establishment so
extensive as that in which I have been engaged,
would be attended with serious loss and inconvenience;
and when the unbounded confidence which has been reposed in us is taken into view,
extra care and caution seem the more needful,
that there should be no unhandsome conduct to complain of;
and I trust that I have always been anxious to avoid everything,
in the smallest degree calculated to cast a shade upon our religious Society,
the principles of which, I have good reason for believing,
are held in considerable estimation at this day by many high in office,
as well as by others who have had more frequent intercourse with us.
After stating undisguisedly my true motive for wishing to retire,
it was proposed that my eldest son should succeed me as head of this concern;
and that in all respects, everything else should remain on its original footing.

Although this outline seems to occupy but a small space on paper, it has,
from first to last, taken about seven months to bring all the particulars to bear;
but the Ukaze +++[+++or imperial edict]
is now actually signed.

I have frequently mentioned having arrived on the same day,
when coming here from England, viz. the 3rd of Seventh Month, O. S.;
and now it has come to pass, without the possibility of any contrivance,
that on that very same day I am liberated from Russia.
I have already had a parting and affecting interview with Prince Galitzin:
he particularly stipulated that I should write to him, saying,
'`What is good for your soul, is good for mine.`' I feel thankful in being able to say,
that there is no perceptible alteration in him, after an acquaintance of fifteen years.
He has ordered a certificate to be prepared for me in English,
for the satisfaction of my friends, which he will sign on behalf of the Emperor.

But although things seem to have been so far set in order,
as to enable me to leave this country in a comfortable manner; yet the trial of faith,
and patience, and of every affectionate feeling has still to be passed through,
as regards my dear wife and family here:
for though the way is clearly seen and opened for my going to England,
yet I have not the slightest prospect of any settled residence there;
but from the impressions which have been sealed upon my mind,
by day and night for many months past, very different scenes are open before me.
As I have from the first,
made my wife acquainted with the uncertainty to which I am looking forward,
she feels best satisfied to remain, for the present at least, in this country.

I have sometimes thought,
as so great a willingness has been wrought in my mind to part with every earthly thing,
that perhaps, when all was settled as to outward affairs,
it might be only as a preparation for quitting this scene of conflict altogether:
but I have been enabled to look forward to this result,
with the same calmness and resignation,
should it be the will of Him who hath done so great things for me,
and shown me the path of life; whose excellency is over Israel,
and who giveth strength and power to His people, to praise and "`glorify`" Him,
even "`in the fires.`"

--

[.offset]
+++[+++Soon after the date of the foregoing, he took leave of his family,
and set sail for England:--the following letter is written
when on the point of quitting the port of Cronstadt.]

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife

[.signed-section-context-open]
Cronstadt Mole, Seventh Month 20th, 1832, O. S.

[.salutation]
My Dearest Jane,

As the captain talks of getting out of the Mole in a short time,
I think it is advisable to scribble a few lines before the scuffle begins,
lest I should then be prevented.

I cannot, of course, have much to communicate as to fresh events,
the time is so short since thou and the rest of
my dear family have been removed from my sight:
I have, however, abundant cause to magnify that never-failing arm of power,
which has so marvellously supported us through a dispensation, not of an every day sort;
and which still continues to preserve in that lowly quiet of mind,
which subjects the will of the creature to that of the Almighty Creator,--
even to the binding of the sacrifice as to the horns of the altar,
without reserving any thing which might, like the "`bleating of the sheep,
and the lowing of the oxen,`" tend to self-condemnation,
or open a door for reproach and accusation, wherein the enemy could exult or rejoice.

I hope we shall have rather more settlement when we get to sea,
as the captain is now much harassed in concluding his arrangements with the Custom-house,
etc.
Last evening, both he and the mate stayed with us, whilst I read a psalm or two;
but it seemed as if they could scarcely be still during the reading,
and it was almost an impossibility afterwards.
This morning we have had it to ourselves in a comfortable manner,
as both captain and mate have been closely engaged.
I find my fellow-passenger a very agreeable companion.

I regretted to find thou hadst been writing so late the night I left home;
although it was very consoling to me to receive thy note,
which I did not read till this morning,
as I was not aware the packet contained any thing for me.
It has been indeed a trying circumstance for a long time past to me,
whenever I have looked forward to taking my departure from thee,
although I have endeavoured to keep it wholly to myself;
but I am comforted in a belief that has been graciously
begotten for some time past in my heart,
that no less reward will await thee and our dear children,
in thus fully resigning me up in meek submission to the Divine will,
than will be my portion, who have to leave you all,
if found faithful to the farther unfoldings of it.
A fresh evidence of this has been sealed upon my mind this morning,
in an encouraging manner; and I do greatly desire that we may all,
by keeping close to our heavenly Teacher in humble watchfulness,
be favoured to witness that peace, which "`the God of peace,
that brought again from the dead our Lord Jesus,
that great Shepherd of the sheep,`" alone can bestow.

[.signed-section-closing]
I am thine, very affectionately,

[.signed-section-signature]
Daniel Wheeler

--

[.embedded-content-document.letter]
--

[.letter-heading]
To The Same

[.signed-section-context-open]
Seventh Month 29th, in sight of Gothland.

[.salutation]
My Dearest Jane,

We have now been out of Cronstadt nine days, and with the exception of one day,
it has been so far, I think, the finest passage I ever experienced,
either of late or in former years.
Almost every day there has been a fair wind, but gentle; and when against us,
so light as scarcely to raise a desire for it to be otherwise.
I have spent much of my time on deck, both by day and by night,
and am thankful in being able to say,
that I can look back with renewed satisfaction and comfort,
at having thus far proceeded in an apprehended line of duty:
although at times I feel as the lonely sparrow on the house top,
or as the rambling swallow without a home,
and still only preparing to take flight for distant climes,
whilst pressing onward farther and farther,
from all that I hold dear in this transitory world.

We have been thus far enabled to keep up our readings twice a-day in the cabin,
although at times a little unsettled; the captain and mate mostly remain with us.
On First day, I furnished each sailor with a tract; either Thoughts by the sea side,
or The Lighthouse, with which they all seemed pleased;
and the captain requested to have one of each for himself.

Two or three days after leaving Cronstadt, I began to suspect,
from some remarks which I had made about the ship,
that she was not quite so tight as had been represented.
She had been pumped that morning in a superficial manner;
but after a few hours I took an opportunity of sounding the well myself,
when no one was near, and found there were twenty-two inches of water in it.
I then told the captain, when she had been pumped,
and what water was in her,--to his great surprise and mortification.
This circumstance made no small stir,
and every possible exertion was made to discover the cause, as it was no light matter.
The ship`'s company, who sleep under the forecastle,
declared that when she plunged into the sea, they could hear the water rush into her:
this led to further investigation,
and the carpenter cut his way down into the cargo so low,
that no doubt remained but this was the case.
Yesterday being fine, with little wind and a smooth sea,
the carpenter went overboard on a stage,
and actually found the leak under the surface of the water;
but not deeper than he could get at, by sitting up to the waist in the water,
except when she plunged him now and then up to the shoulders.
It is a great favour this was discovered before
a large quantity of water had collected in her,
and the cargo damaged, if nothing worse.
I intend, if permitted, to keep a sharp look out upon it still.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Sarah Smith, Sheffield

[.signed-section-context-open]
Ninth Month 3rd, 1832.

Through that loving-kindness which is better than life,
I am once more permitted to announce myself upon British ground,
favoured with the rich blessing of health.

It is six weeks this night, since I left my beloved wife at Shoosharry, and,
accompanied by my children, went down to Cronstadt to embark for Hull.
My dear wife was as well as usual; but remained at home,
as her going to Cronstadt would have been beyond her strength,
particularly at a moment when every feeling was
stretched as far as human nature could well bear;
it would have been adding anguish to the cup of
affliction and distress about to be handed.
"`Hath God forgotten to be gracious?`" Nay verily, my dear friend; His mercies,
unbounded as his love, enabled us to drink it with all its dregs,
bitter indeed to flesh and blood: but if He hath blessed it,
it will--it shall be blessed.
I am very thankful in being able to tell thee,
that my beloved wife was supported throughout the whole conflict in a marvellous manner;
and she evinced to her dear family a calmness, resignation, and fortitude,
not often equalled in like painful circumstances, and but seldom surpassed;
giving me up without a murmur, though without a glimpse of when we shall meet again.
Surely the incense is still burning,
and I humbly trust the sacrifice will be accepted by Him,
who more than thirty-two years ago brought us together;
and who now in the excellency of His will,
is pleased to separate us again from each other;
and who alone can sanctify to us and our dear children,
this and every other trial yet in store for us, to His own praise and glory.

I purpose returning to Doncaster in a day or two,
where I think I shall be more secluded than at Sheffield,
and out of the reach of numberless kindly intended inquiries,
which are at present likely to remain unsatisfied; besides,
my present situation renders me only fit company for owls and pelicans,
and other inhabitants of the wilderness,
to which the desert place is most congenial,--feeling as one born out of due time,
and as an alien even in my father`'s house.

[.signed-section-signature]
Daniel Wheeler

[.postscript]
P+++.+++ S.--What a favour it is, that my dear wife and family are strengthened,
not only to rise above every disposition to repine,
but rather to rejoice in that we are accounted worthy to suffer for the great name`'s
sake,--in the promotion of the cause of truth and righteousness in the earth,
according to the measure allotted us.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To His Wife

[.signed-section-context-open]
Sheffield, Ninth Month 5th, 1832.

[.salutation]
My Dearest Jane,

The meetings in this town on First day were both heavy laborious seasons;
but a public meeting held the following evening, was an open favoured time.
Being again permitted to sit in the meeting
house at Sheffield with many of our old friends,
was a circumstance which had never formed a part of my finite calculations,
when I left this neighbourhood last year;
and more particularly in so short a time as has elapsed:
it seemed for a season something like a dream.
I had no share in the labour of the public meeting (appointed by Elizabeth Robson,)
but the will of the creature was I think prostrated before its Almighty Creator:
and being emptied of self,
I was mercifully enabled to prefer a feeble
petition on behalf of thee and the dear children,
under a sensible evidence of near access being vouchsafed to the throne of grace,
in silent breathings for your preservation and welfare.

--

Ninth Month 22nd, 1832.

I informed the Select Meeting held at Doncaster on the 12th (nineteen
persons being present,) of the object which has brought me to England.
I had also to bear a short testimony to the worth of dear William Smith,
who it appeared had been appointed a representative for the last Quarterly Meeting;
but was prevented attending it by the sickness which preceded his death.
His loss has been greatly lamented by people of various denominations,
and I think it may be safely said, he was one in whom there was no guile.
His end was truly consoling;
although scarcely able to move hand or foot from extreme debility,
his mouth was filled with praises to the Lord; so that the physician who was present,
was quite struck with the scene.
He was interred, I think,
about six hours afterwards,--almost immediate
burial being insisted on in cases of cholera.

Next day, the Monthly Meeting was held; at the close of which,
members were requested to keep their seats.
Ann Fairbank returned a certificate which had been
granted her to visit the meetings in and about London.
When this was finished, I was strengthened to spread before Friends,
the prospect which had been presented to the view of my mind,
of visiting in the love of the gospel the inhabitants
of some of the islands of the Pacific Ocean,
New South Wales, and Van Diemen`'s Land.
I stood up with the words, "`the cup which my Father hath given me,
shall I not drink it;`"--and eventually laid the whole affair fully before the meeting.
A very solid and solemn interval succeeded.
I warned the meeting not to let affectionate sympathy bias their minds,
and recommended that all should endeavour to
sink down to the precious gift in every heart,
that so a right judgment might be come to;
seeing it was a subject in which much was implicated,
not only as regarded myself and the Society at large, but the Truth itself.
At length, a general expression of concurrence and near sympathy broke forth,
from the head to the uttermost skirts of the garment, as the ointment poured forth,
which draws down the heavenly blessing.
Many vocal petitions ascended on the occasion, as well I believe as universal mental ones.
It was, indeed, a memorable day,
and one in which I most earnestly desire you may all be permitted to share,
though far distant, through the influence of that Almighty power,
which is omnipotent and omnipresent.
A committee was appointed to prepare a certificate for me.

I do not know how I may fare in our Quarterly Meeting,
but I feel resigned as to the result.
I have enjoyed feelings, which are quite undeclarable,
since my concern has been brought forward; and greatly do I desire,
that all my dear family may come to the same blessed
experience,--which will most assuredly be their happy portion,
if they are but willing to resign all into the hands of the dear Redeemer,
and not be ashamed of acknowledging Him before men,
although they may be accounted fools by the worldly wise.
But I am thoroughly persuaded, that nothing short of the whole heart,
without the smallest reservation, must be offered,
however great the cross to the natural will;
for it is in little things that the enemy keeps the soul in bondage,
which answer his purpose as well as greater matters,
which would be too glaring to be submitted to.
For the Lord of life and glory will not dwell in the same temple with idols,
however insignificant such may be in our estimation; the day of the Lord "`will not come,
except there come a falling away first`" from these little things,
or a turning from them; "`and that man of sin be revealed,
the son of perdition:`" for "`he who now letteth will let,
until he be taken out of the way; and then shall that wicked be revealed,
whom the Lord shall consume with the spirit of his mouth,
and shall destroy with the brightness of His coming.`"
The heart thus cleansed, will become the secret place,
or the holy place of the tabernacle of the Most High;
through which the crystal river flows,
and in which nothing but unmixed sacrifice is accepted:
the least impurity in our affections will be beheld in its transparent stream.

I am obliged by the kind messages from +++_______+++ and +++_______+++;
and feel greatly desirous that they may all be
favoured to see beyond the shadows of things,
to the living and eternal substance, which is durable as the days of heaven;
that they may indeed be able to say, from living and heartfelt experience,
"`We know that the Son of God is come, and hath given us an understanding,
that we may know Him that is true; and we are in Him that is true,
even in His Son Jesus Christ.
This is the true God, and eternal life.`"
"`He that believeth on the Son of God hath the witness in himself:`"--yea,
"`he that hath the Son hath life; and he that hath not the Son of God hath not life.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To His Children

[.signed-section-context-open]
York, Ninth Month 28th, 1832.

[.salutation]
My Dear Children,

On Fourth day, the 26th, the Quarterly Meeting was held.
After a solemn meeting for worship,
it was proposed that the women Friends should keep their seats.
After the clerk had opened the meeting with the usual minute,
and called over the names of the representatives from each Monthly Meeting,
this large assembly again dropped into silence, which remained uninterrupted,
until broken by myself nearly in the following words:--'`No wonder if
a trembling mortal feels appalled at approaching conflict,
when the dear Son of God himself exclaimed,
"`Father save me from this hour:`"--for although we may at
times feel a willingness to go with our Lord and Master,
as unto prison and unto death; yet such is the frailty and weakness of human nature,
that when the trying hour cometh, we are ready to deny Him.
But we have a great and glorious High Priest, whose most precious attribute is mercy;
who will not break the bruised reed, nor suffer it to be broken;
who is touched with a feeling--a compassionate sense of
our infirmities,--is mighty to save and to deliver,
and who will deliver out of every distress,
all those that put their trust and confidence in Him.`' And thus, eventually,
was laid the whole weight of the concern upon the shoulders of the Quarterly Meeting.
As I thought you would like to have minute particulars,
I have endeavoured to remember what passed, and I think the above is almost verbatim.

The meeting now began to feel the weight of the responsibility cast upon it,
and again settled down in great solemnity.
A considerable number of Friends expressed their unity and concurrence;
and my dear wife and family had a full share in
the prayers and sympathy of their friends,
to my great rejoicing and thankfulness.
After a full hour occupied in this manner,
it was concluded that a committee should be
appointed to express the sense of the meeting,
in an endorsement of my certificate.

--

[.offset]
+++[+++The same letter contains the following account of a
remarkable communication made in the Yearly Meeting of 1832.]

[.embedded-content-document.letter]
--

Thinking the substance of a testimony borne in the Yearly Meeting this year,
will interest you, I shall transcribe it, as follows:

In a striking and awful manner Sarah L. Grubb adverted to the
permitted visitation of the pestilence in this country;
and afterwards she had a very close and powerful testimony to the meeting,
on the present state of our religious Society,
by way of solemn warning of the approaching judgments
of the Lord upon us for the neglect of those things,
which in a peculiar manner, were given us to bear in the early times of our Society,
when Friends were called out from the world to be a separate people.
Her concern was, that we should return to first principles;
but her more especial warning was,
that if there were not a coming down from the heights to which many have climbed,
there were those amongst us who might be compared to the golden vessels of the temple,
such as had really stood the fire, and had not only been rightly filled,
but employed of the Lord to communicate to the people,
who would be permitted to be carried away captives to Babylon.
That there was and is amongst us, a Babel now building,
whose top is intended to reach unto heaven, which must and will come down; that there is,
(though not clearly seen by ourselves,) a peeling and scattering amongst us,
which is clearly shown in the vision and light of the
Lord;--and that if we did not repent and return,
we should be left very few in number.
But that the Lord would not leave himself without a people, etc.
She spoke farther in reference to some,
who had been rightly gifted to speak the word of the Lord as from the mouth of the Lord;
but who for want of dwelling low and deep enough,
had had their brightness dimmed,--adding, "`when Ephraim spake trembling,
he exalted himself in Israel, but when he offended in Baal, he died.`"

It does seem as if what has hitherto been dispensed,
had made but little impression on the minds of the people in this land;
and I fear this is the case in many other places.
What could have been done, that hath not been done,
to bring mankind to the knowledge of Him,
who is the author of eternal salvation to all
them that obey him? but if they will not hearken,
how shall they obey? How ready and willing most are,
to hearken to the teaching of poor finite man;
but how reluctantly they will submit to hearken to the voice of God!
Like the Israelites of old, they would rather hear the voice of Moses than of Him;
and if we consider the hundreds who are busily engaged
in turning the attention of the people to the letter,
to the traditions and ordinances of man, "`after the rudiments of the world,
and not after Christ,`" what must be the end thereof?

--

Sheffield, Tenth Month 8th.

I was at both meetings at Sheffield yesterday;
that in the forenoon was large and satisfactory.
I had to set forth the beauty, purity, and loveliness of the gospel church,
and to put the people upon considering whether they were members of this glorious church,
that is without spot or wrinkle, or any such thing;
because if not attained to happily whilst here, it cannot be done hereafter;
for as the tree falls, so it will lie,
whether it be to the south or to the north:--that such
a state is evidently attainable in this life,
from the language of the apostle Paul to the Hebrews,--`"
`For we are not come to the mount that might be touched,
and that burned with fire, nor unto blackness, and darkness, and tempest,
and the sound of a trumpet, and the voice of words;`"--"`but ye are come unto Mount Zion,
and unto the city of the living God, the heavenly Jerusalem,
and to an innumerable company of angels,
to the general assembly and church of the first-born, which are written in heaven;
and to God the Judge of all, and to the spirits of just men made perfect;
and to Jesus the Mediator of the new covenant, and to the blood of sprinkling,
that speaketh better things than that of Abel.`"
The blood of Abel cried from the ground for vengeance upon the offender; but,
"`Father forgive them, they know not what they do,`" was the cry of Him,
whose precious blood was shed for the sins of all mankind.
I had to query of them,
what they knew of "`this blood of sprinkling,`" which "`cleanseth
from all sin;`"--pressing the necessity of living faith,
which could only be obtained by coming to Jesus,
who would beget in them "`the faith of the
gospel,`" and would be found not only the author,
but the finisher thereof.
Without this, the highest profession of the Christian religion is but a dream, a shadow,
and a doubt; but with it, a glorious reality,--the life of the just,
who "`live by the faith of the Son of God,`"--the very "`substance of things hoped for,
the evidence of things not seen,`"--even the salvation of the soul.

On the 27th of Tenth Month, I returned to Tottenham,
and attended both meetings there next day, as to myself in silence;
but several others were engaged to advocate the great cause.
The next morning the Committee of Friends appointed by the
Yearly Meeting to revise the Book of Extracts sat down,
consisting of some members from almost all the Quarterly Meetings in England,
who with the members of the Meeting for Sufferings, formed a numerous body.
My concern could not be brought forward till the
regular time for the Morning Meeting to assemble,
which was that day fortnight;
so that I had to struggle on under its weight as well as I could.
I have however great cause to be thankful for the
privilege of attending so memorable a conference;
particularly as it appeared that only one other individual besides
myself had been at the last revision of that book thirty years ago.
It is remarkable, that one so circumstanced as I have been,
should have been permitted to share twice in so solemn and exercising an occasion.

After attending twenty-two sittings of the conference, also a Monthly Meeting,
and six meetings for worship,
the day arrived which brought the seal of confirmation to what had
already been sanctioned by my own Quarterly and Monthly Meetings.
But before entering on this description, I must tell thee, that the conference,
although at seasons truly painful on account of the visible
and alarming stature of the uncircumcised in heart,
was at times highly instructive and eminently
favoured with the life-giving presence of Him,
who abideth of old, who did not fail to give power to the faint,
and to increase the strength of those that have no power of their own;
according to the prediction of the evangelical prophet, He was indeed,
for a crown of glory, and for a diadem of beauty unto the residue of his people,
and for a spirit of judgment to those that sat in judgment,
and for strength to them that truly turned the battle to the gate;
and to His own praise and glory did He marvellously enable them that fear Him,
to display the banner which He had given them, "`because of the Truth.`"
The conflict of mind which I had to pass through,
early in the day that I had to stand before the Morning Meeting,
is utterly undeclarable by the tongue of any mortal;
and I could not at the time account for it:
but I was afterwards favoured to see that this dispensation was highly needful for me.
I stood up with the words,--"`I have a baptism to be baptized with,
and how am I straitened until it be accomplished`" adding,--'`but
the God of Israel is He that giveth strength and power to His
people,--blessed be God.`' I then proceeded to state,
that my mind had been long preparing,
in order to loosen me from every earthly occupation,
and to wean me from every social tie,
of which I had been blessed with more than an ordinary share;
and that shortly after my return from this country last year,
to a land of desolation and sorrow,
my heart was at times filled with the love of God in a
remarkable manner;--that in one of those delightful seasons,
a prospect was opened before me, the magnitude of which made human nature shrink.
But He who had redeemed my life from destruction,
and crowned me with loving-kindness and tender mercies,
was graciously pleased to beget in me a willingness to
go wheresoever He was pleased to lead.
My engagements were at the time such,
as seemed to preclude the possibility of my being extricated from them for this work;
but the pathway was clearly defined, in which as I moved step by step,
the mountains became mere mole-hills,
and I was at length enabled to lay my concern
before my own Monthly and Quarterly Meetings,
etc.:
and that although some relief had been obtained by casting a
share of the weight upon the shoulders of my Friends,
yet the burden still remained with me day by day, and at intervals in the night season;
desiring that a right judgment might be come to,
whether this thing was of the Lord or not.

After a long pause, it was thought that the Morning Meeting could not set me at liberty,
without knowing what I expected to do in those distant parts.
To this I replied, that no specific line of duty was pointed out to me,
in this early stage of the business; but that what had passed in my mind led to a belief,
that I should have to turn the people "`from darkness to light,
and from the power of Satan unto God,`"--and to teach them that they lived, and moved,
and had their being in that God, whom they worshipped, it was probable,
as at a distance:--that as to the missionaries I might meet with,
I could embrace them with open arms, as fellow-men, countrymen,
and labourers in the same great work, although, perhaps in a different stage of it.

The certificate will show how the matter issued.
The meeting ended in a truly solemn manner.
Our dear aged friend William Rickman, was constrained to declare,
that '`the Truth reigned over all.`' Many prayers were put up for you all,
as well as for myself and others, who may be engaged to the same work.
