== Chapter XIV

[.chapter-synopsis]
* Correspondence Attends Norwich Quarterly Meeting
* Receives Intelligence of the Decease of His Wife and of the Severe Illness of Others in His Family
* Letters to His Absent Children

[.letter-heading]
To Sarah Smith

[.signed-section-context-open]
Tottenham, Eleventh Month 24th, 1832.

I have been told by a respectable ship-owner this morning,
that I should not be later than the Second Month in leaving this country,
or it will be too late to reach Cape Horn, before the winter sets in,
when sailing becomes hazardous in those latitudes.
He can speak feelingly on this head, having just lost that fine ship the Science,
on her homeward passage, which carried out our friend James Backhouse and his companion.
I should much regret, if this account should reach my beloved wife and family,
lest it cause painful forebodings on my behalf; for believe me when I say,
that the most painful feelings I have to encounter are on their account.
I can look forward with composure to hardships and privations, as regards myself;
but for them and over them I yearn,
and reverently crave in humble prostration and brokenness of
spirit the blessing of preservation and support,
and that my ever-gracious Lord will condescend,
in the multitude of his everlasting mercies,
through the all-sufficient power of his grace, to be a husband and a father to them;
and in the mysterious workings of His wondrous Providence,
abundantly to supply all their wants,
shedding abroad in their hearts a portion of that heavenly love,
which banisheth fear from the innocent habitation,
and at seasons causeth even the widow and the fatherless to sing,
in praise of the majesty of the Lord and the glories of his kingdom.

Although surrounded with many dear friends, both brethren and sisters,
yet I feel amongst them as one born out of due time,
and wading in secret silence under a burden, known only to Him,
who beholds the inmost recesses of the heart,
and who with an invisible hand sustains under its heaviest pressure;
whilst according to His loving-kindness, which is better than life,
my tribulated soul is humbled into nothingness,
and therein brought nearer and nearer to my meek and lowly Saviour,
and taught from sensible feeling to magnify His all-redeeming power,
and to bless his holy name in the depths of self-abasement.
Thus my dear Lord and Master is leading me along,
and I trust preparing me to do his righteous will,
which can in no other way be accomplished, than by the total surrender of our all to Him,
without reservation.

[.letter-heading]
To His Wife

[.signed-section-context-open]
Cancood, Twelfth Month 11h, 1832.

[.salutation]
My Dearest Jane,

At the close of the last letter,
I mentioned having been invited to attend the remains of our late valued friend,
Martha Smith, to their long home.
I reached Doncaster the next day,
and found a large number of Friends collected for the same object.
Her long residence at Doncaster, and extensive acquaintance in the Society,
to many of whom she had long been very dear, caused a large assembling;
about sixty persons came from other parts, besides the Friends of her own meeting.
According to instructions she had left, the coffin was taken into the meeting-house,
agreeably with the ancient practice of the Society.
It was truly a memorable and solemn opportunity,
I believe both to her friends and to many strangers present.
M+++.+++ T. and another minister were engaged in the fore-part of the meeting,
but the weight of the service pretty much
devolved upon myself:--"`Daughters of Jerusalem,
weep not for me,
but weep for yourselves and for your children,`" were the expressions opened to my mind;
after which I had to declare a belief that if the voice of our dear departed sister,
which had so often proclaimed within those walls the wonders of redeeming love and mercy,
could then be heard, the language of her purified spirit would be "`weep not for me,
but weep for yourselves and for your children;`"--and as she could not return to us,
but we must follow her, that we should endeavour so to follow her,
as she had endeavoured to follow Christ, in the path of self-denial and the daily cross,
without which there would be no crown.
I had afterwards to declare at the grave side to a crowd of fresh faces from the street,
the day of the Lord, which would assuredly try the foundation of all their works.
The remainder of the day was I trust profitably spent.

I set off the next morning for Hull, in company with John Hipsley and I. Casson,
who had also been invited to the interment:
we were favoured to reach Hull in safety that afternoon.
I attended their meeting next day to my comfort, and started for York the day following.

Tottenham, Twelfth Month 17th,
Seventh day.--I have again taken up the pen to resume my
delightful employment of conversing in this way with thee,
not I think without a degree of thankfulness, that such an alternative is permitted,
however short it may seem of the reality so much desired, I believe by each of us.

I reached Nottingham on Fourth day evening as intended.
We had a very comfortable meeting there next day: at this as at other places,
the hand of time has swept away many, with whom I was well acquainted.
It was a solemn meeting:--"`He that abideth of old,`" was graciously
pleased to crown the little company with His presence.
Being the week-day meeting, it may be presumed that few were present,
that had not made more or less sacrifice to attend it;
and I believe all these were rewarded.

A Friend largely concerned in the South Sea fishery,
has suggested a plan altogether unthought of by any of us; and that is,
the purchasing a vessel in all respects adapted not only to the voyage out,
but also to conveying us from island to island.
He particularly recommends her being quite a small cutter,
both for safety and expedition,
and because capable from her small draught of water of
running into shallow harbours and creeks,
which a large vessel could not enter.
He thinks a crew could be procured, who would be willing to substitute cocoa, tea, etc.,
for spirits, except for medicinal purposes; and that when no longer required,
she would be readily sold in New South Wales.
I quite approve of the plan, believing it would have many advantages;
but particularly as on a moderate calculation,
it would save a year in the time of absence, which is to me of too great importance,
to allow the idea to be dropped without further scrutiny.
It may yet be proved that much expense would be saved by it;
and that the object in view would be more completely embraced in all its points.

Do not fail to write, that I may hear of you whilst I remain in the way of doing so.
In dearest love, believe me, however circumstanced, or wherever placed,
daily found in prayer to Almighty God for the preservation and welfare of you all.
In truest affection,

[.signed-section-signature]
Daniel Wheeler

[.letter-heading]
To His Children in Russia

[.signed-section-context-open]
Norwich, Twelfth Month 29th, 1832.

[.salutation]
My Dear Children,

Last Third day, the 25th, I attended the Quarterly Meeting for London and Middlesex,
held in Devonshire House Meeting House, which was crowded to excess;
many could not be accommodated with seats,
although every avenue was furnished with temporary forms,
and I understood that a considerable number could not gain admittance in any way.
It fell to my lot to revive amongst them some expressions,
which occurred at the memorable interview between the Saviour of the world and Martha,
soon after the death of Lazarus;--opening the subject with--"`Lord,
if thou hadst been here, my brother had not died: but I know that even now,
whatsoever thou wilt ask of God, God will give it thee.`"
"`Thy brother shall rise again,`" our Lord replied.
"`I know,`" said Martha, "`that he shall rise again,
in the resurrection at the last day.`"
"`I am the resurrection and the life;
he that believeth in me,`" declared the Saviour of men, "`though he were dead,
yet shall he live; and whosoever liveth and believeth in me, shall never die.
Believest thou this?`" The explanation of these words was opened in this manner:
he that believeth in Christ, though he were dead in trespasses and sins,
yet shall he live; and whosoever liveth,
after having been thus quickened from spiritual death unto life,
in the hope of His everlasting mercy,
and in the belief of His inward and spiritual appearance,
and in obedience to His will therein made manifest, shall never die.
"`Believest thou this?`"--They shall have part in the first resurrection;
and the second death will have no power over them.
They must share in the common lot of mortality,--
the separation of the soul from the body;
but they will never be separated from their God.
For "`neither death, nor life, nor angels, nor principalities, nor powers,
nor things present, nor things to come, nor heights, nor depths,
nor any other creature will be able to separate them from the love of God,
which is in Christ Jesus our Lord.`"
After this,
I had to branch out into the necessity not only of performing the Divine will,
but also of endeavouring to prove what is that
good and acceptable and perfect will of God:
that knowledge however will verily profit us little,
without obedience keeps pace with it, as it is not the hearers of the law,
but the doers that are justified.

I went down by mail the same night to Norwich;
and attended the Quarterly Meeting for Norfolk and Norwich on
the 27th. After E. F. had appeared in supplication,
I had to declare of the mercy and goodness of the Lord to those that fear him;
and to point out the inhabitants of that heavenly city, Mount Zion,
which he hath chosen and founded,
and which the poor of his people shall trust in,--all of whom are redeemed with judgment,
and her converts with righteousness:
the judgments of the Lord having been suffered to pass
over the transgressing nature in their hearts,
in order to redeem therefrom,
and they having believed in the righteousness of Christ Jesus,
and being converted by the sanctifying power of his grace.
W+++.+++ F. spoke for a considerable time after I sat down with instructive clearness.
At the request of John Wilbur, +++[+++a minister from America,]
a meeting was held the next day, and was well attended.
I found it my place first to break through its solemnity,
and to supplicate that the great Name might be exalted,
and the kingdom of Christ Jesus established in the hearts of the people.
John Wilbur had full opportunity to relieve himself,
and stood nearly an hour and a half to the satisfaction of the meeting;
and I trust to the peace of his own mind.
He had in true gospel authority, like the well taught scribe,
to bring forth from the treasury of wisdom and knowledge things new and old.

[.offset]
+++[+++The above was written at the house of Joseph John Gurney, at Earlham,
where during some weeks of indisposition,
he was attended and cared for with a tenderness of
which he ever retained a grateful recollection.
It was during this period,
that intelligence arrived of the decease of our beloved mother,
and the alarming illness of three other members of the family.

Perhaps it may be desirable,
in order to elucidate some passages in the succeeding letters,
to enter into a short explanation of the series of domestic afflictions,
with which that part of the family left at Shoosharry was visited at this time;
and the difficulty of making public the details of private sorrow,
seems greatly diminished by the fact,
that the parties to whom they relate are no longer our fellow-probationers;
but were all called to precede our beloved parent to that better world,
where we reverently believe their spirits are now eternally blessed.

About the 20th of Eleventh Month,
our brother Charles was attacked with an inflammation of the lungs,
which for a time threatened his life:
the complaint had at length yielded to the means employed,
when our dear mother and sister Jane were at the
same time stretched on a bed of sickness.
Our mother`'s disorder proved to be fever, and though apparently of the mildest kind,
it terminated fatally within nine days.

At this time dear Jane was lying in a very alarming state from inflammation of the brain.
For several days the issue appeared doubtful; but through mercy her life was spared,
and space allowed her for the all important work of repentance and reconciliation.

At the time of our dear mother`'s death,
our eldest brother William was suffering from an affection of the chest,
which shortly afterwards reduced him to a state of great exhaustion.
Whilst both he and Jane continued unwell, and the former in a very precarious state,
Charles was seized with the fever, which had already deprived us of our mother,
and of two other members of the household.
For three weeks his disorder raged violently, and when it had in some measure abated,
whilst he was still extremely weak,
all hope was again destroyed by the re-appearance of inflammation of the lungs.
Once more he was permitted to rally;
and after being forty-eight days entirely confined to his bed,
he was gradually restored to a comfortable state of health.
To him also, through the visitations of infinite love,
the season of sickness was made one of deep instruction;
and during the remainder of his brief career of life,
he was strengthened steadily to pursue a heavenward course.
It was after receiving the account of Charles being attacked with fever,
that his father resolved on returning for a season to Russia.
On his arrival there on the 12th of Fourth Month, 1833,
he was favoured to find the invalids of his family gradually recruiting.
But to proceed with the correspondence.
The announcement of the decease of our beloved mother is thus described by himself.]

[.signed-section-context-open]
First Month 11th, 1833.

Some days ago,
when dear Mary Gurney came to my bedside (a sweet spirited Friend,) I told her,
that I quite enjoyed the rest I was permitted to partake of;
that I had been looking towards home,
and had been favoured with a peaceful feeling respecting you all;
that I did believe all was right, and in the ordering of the Master,
or something to that effect.
When she replied,--'`it is a rest of preparation.`' I do
not recollect that she added more at that time.
On the 9th instant, several letters were brought into my room,
when I said,--"`No letter from Petersburg?`" to which I got no answer.
In the evening, as I lay on a couch, J. J. Gurney adverted to the health of my family,
hinting that later accounts than my own had been received.
I heard it without much suspicion,--little expecting what was in store,
and that a cup filled with the wine of astonishment, was about to be handed to me.
By degrees something more was unfolded;
until I requested to know the whole that awaited me.
But who can picture my distress and anguish of soul,
when the awful reality was discovered? But the everlasting
arms of mine Almighty helper were underneath to bear me up,
that the waves of affliction should not overwhelm beyond the decreed limits,
nor infringe upon the margin of mercy and compassion.
After a time I was enabled to say, '`it is a bitter cup:
but I accept it at the hand of the Lord;
for I am sure there is a blessing at the bottom of it.`' The whole letter was then read;
and to my unspeakable comfort, I was enabled to perceive,
that my peaceful feelings about you all,
were abundantly confirmed by a consoling evidence,
that everlasting love and mercy had conspicuously covered the judgment seat,
even to a hair`'s breadth:--that the beloved and precious partner in
all my joys and sorrows for more than thirty-two years had passed,
not from life to death,
but from death unto life eternal;--and that my darling Charles and Jenny are yet spared,
I humbly trust and pray,
(whether their time here may be longer or
shorter,) so to believe in the Lord Jesus Christ,
as to be saved with an everlasting salvation.--And may
we all be enabled to say in the language of the apostle,
"`I am crucified with Christ; nevertheless I live, yet not I, but Christ liveth in me;
and the life that I now live in the flesh, I live by the faith of the Son of God;
who loved me and gave himself for me,`" that in the winding up of time,
we may all be permitted to meet again,
with the purified spirit now fled--of her we dearly loved,
with palms and harps in our hands,--those emblems of victory
and praise;--joining a numberless multitude in the never-ceasing
anthem of "`Hallelujah unto the Lord God and the Lamb,
who liveth and reigneth for ever,`" who giveth the victory,
and to whom belong the praise and the glory!

I shall anxiously expect another letter.--I have been
mercifully strengthened to say,--"`the Lord gave,
and the Lord hath taken away, blessed be the name of the Lord.`"
Not a wish dares to intrude upon the peaceful resignation of my mind.
I only regret that I had not a personal share in the
general distress and conflict of the occasion.

[.letter-heading]
To His Children

[.signed-section-context-open]
First Month 19th, 1833.

[.salutation]
My Dearest Charles And Jane,

When I quitted Shoosharry, I thought I had given up much;
and when fairly away from Cronstadt,
I seemed to have parted with everything in this world:
but I have since sorrowfully found,
that there remained ties which bound the soul to earth,
which were yet to be dissolved before the sacrifice was complete.
The visitation was so unexpected and sudden,
that for a time every effort to bear up against the overwhelming reality,
seemed altogether unavailing.
It is indeed a cup exceeding in bitterness all that had
previously been handed,--filling my heart with anguish,
indescribable and irresistible.
Yet, blessed be the name of the Lord God of heaven and earth for ever, He,
who had commanded the storm, was, in gracious condescension and compassionate mercy,
pleased to rebuke its raging billows, and to bear up my helpless head above them all;
enabling me to glorify His holy name "`in the fires`" of this baptism of suffering,
to His own praise.
And although the dispensation is altogether incomprehensible at present,
yet I firmly believe, the merciful design of the Divine Will,
as it is patiently abode under, will be more and more developed to our understandings,
and will not fail to raise in us a grateful tribute of thanksgiving.
"`What I do, thou knowest not now,
but thou shalt know hereafter:`"--and O! that we may all be
found worthy to be entrusted with the heavenly secret,
whether it be to be laid up in our own hearts, or to be declared to many.

When I have been led to contemplate the suspense and anxiety,
which my long silence must have unavoidably occasioned to your dear mother,
when more distantly separated by mighty oceans,
together with the expectation of my being amongst barbarous nations,
and exposed to various hardships,--how often have I desired that
opportunities might occur for me to send at frequent intervals,
some even short account of my safety and preservation;
that she might be comforted from time to time,
and not be permitted to droop with hope again and again
deferred;--feeling a willingness to suffer myself,
and to trust her and my precious family to the tender care of our heavenly Father,
though months and months might pass away without a probability
of hearing of or from them,--if only they might be cheered and
animated now and then with but a gleam.
But whilst human nature deeply feels,
and every chord of tenderness and affectionate remembrance
vibrates at the recollection of what we have all lost;
yet my soul doth secretly rejoice and magnify my good and gracious God,
in humble thankfulness,
that her lamb-like spirit is now spared this painful dispensation;
and that the suffering will be only mine; and,
mingled with many other tribulations which may yet await me,
serve to fill up the allotted measure;
in which I humbly trust I shall be permitted to glory,
from the certain knowledge that tribulation worketh patience and
experience and that hope "`which maketh not ashamed,`" nor afraid,
"`because the love of God is shed abroad in the heart.`"

I think the finger of the Divine Artist may already be
traced in the present afflictive dispensation,
as regards us all; but more particularly in the effects which have already resulted,
both to thee and to dear Jenny,
giving you to see in a remarkable manner and in wondrous mercy,
that everything in this world is but vanity,
and will most certainly end in vexation of spirit,
if we have not an interest in the Saviour,
and if destitute of that knowledge which alone can save.
It is therefore my most humble prayer, that you may both endeavour to the utmost,
to keep near to that Power which hath so graciously opened your
understandings to perceive his tender mercy and loving-kindness,
which is better than life,
in thus gathering your beloved mother into everlasting rest and peace,
removing her from the troubles of time to the enduring riches of eternity,
in holy quietness, because death had lost its sting, and the grave its victory.
I am very sure that you must both have had convincing proof of the necessity
of seeking after an acquaintance with the precious gift of God,
which is so mercifully vouchsafed in measure by Christ Jesus in every heart;
and which is sufficient, if attended to,
to restore every son and daughter of Adam from a state of nature to a state of grace,
into the heavenly image from which man by transgression fell.

I think you must both have seen how insignificant this
world and all that belongs to it appear,
when the pale herald of the grave hovers around us.
Nothing short of that Divine power, which thus showeth us these things,
can prepare and purify us for an "`inheritance undefiled,
and that fadeth not away:`" and be assured of this,
that however homely this unflattering Witness may appear,
though it seem but "`as a tender plant,
and as a root out of a dry ground,`" and when perceived there
is no beauty to render Him desirable to the unregenerate mind;
yet this, my dear children,
is nothing less than a manifestation of the Spirit "`of the Lord of life and glory,
which is given to every man to profit withal;`" and well will it be for us,
if we are profiting thereby, and faithfully occupying therewith.
This Holy Spirit hath long been oppressed and afflicted in all our hearts,
whilst we have been employed in perishing pursuits,
and altogether regardless of Him or his secret touches and reproofs,
until perhaps cast upon a sick bed,
or brought into a situation where His voice will be heard.
It is to this power that we must be willing to turn,
and it is by this power only that we can be saved,
seeing it is the Spirit of Him our dear Redeemer, whom "`God hath highly exalted,
and given him a name which is above every name;
that at the name of Jesus every knee should bow, of things in heaven,
and things in earth, and things under the earth;
and that every tongue should confess that Jesus Christ is Lord,
to the glory of God the Father,`" either in mercy or in judgment.
And O! saith my soul, that our confession may be to His wondrous love and mercy,
and not in the acknowledgment of His just judgments for our
hard-heartedness and unbelief in the day of his visitation,
wherein he would have gathered us,
"`as a hen doth gather her brood under her wings,`" and we would not.
For true it is, that if we are willing to attend to this in-speaking,
heart-searching voice, to turn at its reproofs,
we shall find that they are full of instruction, and the way to life everlasting.
It will not fail to show us the deceitfulness of sin, the sinfulness of sin,
and the wages of sin, which is death.
As we patiently abide under the turnings and
overturnings of the Lord`'s hand thus upon us,
however humbling and painful to the unsubjected mind,
we shall indeed know the Saviour of the world in all his offices;
not only as a convincer and reprover of sin through His Spirit,
but as a purifier and cleanser from it:
and as the great work of regeneration gradually advances,
our spiritual eye will at last be opened to perceive
and to look on Him whom we have so long pierced,
and to mourn in godly sorrow unto unfeigned repentance not to be repented of.
Then indeed shall we bow to His name, which is His power,
on the bended knees of contrition and self-abasedness;
and be enabled from living and actual experience to say,
"`I have heard of thee by the hearing of the ear, but now mine eye seeth thee;
wherefore I abhor myself, and repent in dust and ashes.`"
Here then is "`repentance toward God,
and faith toward our Lord Jesus Christ,`" whereby we forsake sin,
and believe in the efficacy of that power which alone can save from it.
Then, indeed, shall we become willing to confess Him before men,
not being ashamed to acknowledge His power and His might,
nor afraid of being thought His followers,
by the votaries of a world which "`lieth in wickedness;`" but to boldly take
up the cross--a daily cross to our own corrupt wills and inclinations,
and follow Him whithersoever He may be pleased to lead;
remembering for our comfort and encouragement his gracious declaration,
"`whosoever shall confess me before men,
him shall the Son of Man also confess before the angels of God:
but he that denieth me before men, shall be denied before the angels of God.`"
This indeed will be confessing to His name in the belief of His power,
and in the hope of His mercy; and a bowing in earnest in obedience to His holy will.
But if unhappily unwilling to bow the knee of our minds,
we should stubbornly resist the offers of unutterable love and mercy,
refusing to confess with the tongue "`that Jesus Christ is Lord,`" by
the acknowledgment of His power in our hearts to save,
and by submissive obedience to it,
in the way of the cross,--we shall one day find to our indescribable distress,
when it is too late, and the language is uttered, "`he that is filthy,
let him be filthy still.`"

But although it is with me thus to write,
yet my prayers are incessant on your behalf for better things,
even things that accompany life and salvation; that mercy and truth may meet together,
that righteousness and peace may kiss each other, in our heart-felt experience;
which most assuredly will be the case, if the fault be not our own.
We shall find that watchfulness, prayer, and fasting, are the Christian`'s strength,
his safe retreat, and never-failing weapons of defence;
even a constant watch over all our thoughts, tracing from whence they spring;
for thoughts are the origin of all our words and actions.
As we thus maintain the watch we shall soon begin to groan,
being burdened with the frailty and helplessness of human nature;
which unavoidably and happily for us, cannot fail to incite to prayer,
though perhaps but in sighs and groanings which cannot be uttered;
but which are accepted and recorded by Him, who is a God ever hearing prayer,
and who will in tender mercy strengthen us, if on our parts we are but willing,
to pray always, "`with all prayer and supplication in the Spirit,
watching thereunto with all perseverance.`"
This will almost imperceptibly lead us habitually to
fast from the gratifying things of time and sense,
which do but serve, however insignificant they may appear in the world`'s estimation,
to prevent the sacrifice of the whole heart;
and as nothing short of this will be accepted, in the Divine sight,
the enemy`'s purpose is still effected.

I have craved in the tenderest manner for you,
that you may henceforth be preserved and strengthened
in faithfulness to resist those things,
whatever they be, that were burdensome to you when on a bed of sickness,
the fruit of which is bitter indeed, and productive only of shame, remorse,
and anguish of spirit.
Let the time past suffice, and the future be employed not in living to ourselves,
"`but unto Him who died for us and rose again.`"

First Month 30th.--I am thankful in being able to say that I am nicely recovered.
I have met with such unfeigned love and kindness from the family here,
as can never be repaid, either by me or mine.
On First day afternoon,
I found that the time was fully come for me to take leave of the Friends of this place;
when they were commended in apostolic language "`to God and the word of his
grace,`" in which all their beloved families as well as my own were included.
The meeting concluded with earnest prayer,
and we separated under feelings of thankfulness and praise.

I must now bring this letter to a conclusion,
earnestly desiring that nothing may be permitted to
prevent your unremitting pursuit after that kingdom,
which our Lord declared to be within;
and that "`no man may spoil you through philosophy and vain deceit,
after the rudiments of the world, after the tradition of men,
and not after Christ,`" is my earnest and constant prayer for you.

P+++.+++ S.--Second Month 4th, Stamford Hill.--On arriving at this place,
I found dear William`'s letter containing the painful intelligence of
dear Charles being seized with the prevailing fever.
My situation is very trying,
seeing I have not the power of rendering the
smallest assistance to the wreck of my family.
I can only put up a feeble petition for him and for you all;
and with you wait and lean on the bosom of the beloved and only availing Comforter,
in humble prostration of soul; trusting that I shall be favoured to stand resigned,
to whatever may be the Divine will.

[.letter-heading]
To One of His Children

[.signed-section-context-open]
Stamford Hill, Second Month 20th, 1833.

[.salutation]
My Dear S.

All the part that I seemed capable of performing during the
turnings and overturnings of the Lord`'s holy hand upon us,
has been, as it were, to turn my face to the wall,
and labour after humble resignation and patient submission of soul,
and therein wait until he should be graciously pleased to say, "`It is enough.`"

The interest that has been awakened amongst our friends in this country,
has burst forth on all sides in letters of
condolence and sympathy in our great bereavement,
and in the accumulated affliction which has
continued to press upon the wreck of my family:
I believe that more heartfelt solicitude was
never felt on an occasion of a parallel nature,
when only individuals in humble life have been concerned;
and I have no doubt that the prayers of many have been put up on our account,
to the God of all comfort, for his Almighty help and deliverance:
I humbly trust they have been permitted to ascend as
sweet incense before the Lord Most High,
whose ears are ever open to the prayers of His people;
more especially of such as dwell continually in His temple,
and behold His beauty in the holy place.
And be assured that my feeble,
though frequent petitions and aspirations have been
mingled amongst others for your preservation,
and for the restoration of the dear invalids,
in this day of visitation and sore conflict.
From an accurate knowledge of circumstances as well as place,
I believe I have been enabled to travail with and for you,
and to wade in the depths of distress in degree,
through the same conflict,--not only as to the
bodily sufferings of dear Charles and Jenny,
having myself had to pass through sickness and distress,
under circumstances of hardship which I am totally unable to describe,
and when recovery was equally doubtful;
but I have also had to pass through the same agonizing conflict of mind,
heightened to a much more dreadful degree, because charged with sins of deeper dye,
than I fully believe have laid at their door.
And though I can say with the great Apostle,--"`this is
a faithful saying and worthy of all acceptation,
that Jesus Christ came into the world to save sinners,
of whom I am chief;`" yet to the praise of the riches of His grace,
I can also say,--"`behold the Lamb of God,
that taketh away the sins of the world,`"--He that speaketh "`in righteousness,
mighty to save.`"
And I do most earnestly desire,
that my dear Charles and Jane may not suffer themselves to lose sight of the
wondrous mercy that has been so plainly and marvellously extended,
nor let the remembrance of it depart from their minds;
but that they may faithfully wrestle to maintain the watch,
and may become of quick understanding in the fear of
the Lord,--that fear which keepeth the heart clean,
and endureth for ever.

I do exceedingly crave, that if comfortable health is permitted to return,
they will endeavour to keep low in their spirits, and dwell near the root of life,
with Him who declared himself to be, "`meek and lowly in heart.`"
And O! that they may not suffer doubtings to arise,
as regards that power which has thus in matchless love and
mercy said unto them "`live;`" or be disposed to question,
or to say, is this "`He that should come,
or look we for another,`"--like the disciples of John formerly.
For surely their blind eyes have received sight, their lame ideas, notions,
and comprehensions are changed; and the feet of their minds strengthened,
and prepared to walk in a new and living path.
Have they not witnessed the leprosy of sin to be searched into, and brought into view,
in order to be cleansed by that which alone "`searcheth
all things?`" Have not their deaf ears been unstopped,
so that even the still small voice could be heard in the soul,
and is found to be powerful, a mighty and irresistible voice,
causing a guilty conscience to tremble; as described by the kingly prophet, when he said,
"`the lightnings lightened the world,
the earth trembled and shook,`"--when that "`light which lighteth
every man that cometh into the world,`" so shines in our hearts,
as to discover the earthly nature,
and make it tremble,--bringing all our sins in order before us
in terrible and to our awakened understandings fearful array.
When personally on earth, after He had said to John`'s disciples,
"`the blind receive their sight, and the lame walk, the lepers are cleansed,
and the deaf hear, the dead are raised up,
and to the poor the gospel is preached;`"--He added,
"`and blessed is he whosoever shall not be offended in me.`"
So that I feel more than I can embody in words,
that with those on whom such miracles have been wrought,
who have been raised up as from the dead in sins and trespasses,
as well as rescued from the grave, and who when brought low, humbled, broken, contrited,
and made poor in spirit, have had the gospel preached to them,
demonstrating in a manner incontrovertible,
that it is "`the power of God unto salvation,`"--that nothing may be
permitted to turn them aside from the blessing promised to those,
who are not offended at this heavenly visitant.
For this I pray; and that they may be strengthened, saith my soul,
to give up all to follow Him in the regeneration faithfully:
for it is only those that endure unto the end that shall be saved,
and it is only those that give up all, who can endure all things for his sake.
Whatever interferes with His Holy Spirit,
whose right it is to rule and reign in our hearts, must be given up, be it what it may.
"`He that loveth father or mother more than me, is not worthy of me;
and he that loveth son or daughter more than me, is not worthy of me.`"
Whatever is suffered to occupy our attention,
tending in any degree to draw aside from watchfulness, prayer, and waiting upon Him,
beyond what is allowable and needful in our passing through this pilgrim state,
either in thought, word, or deed,--robs us of a sense of His inestimable presence,
and of a share of the soul-enriching peace which flows from Him,
and lessens our love towards Him, to whom the whole heart belongs;
who "`will not give His glory to another,`" nor His praise to graven or any other images,
which we may suffer to be set up in our minds,
however innocent and insignificant we may think such to be.

And though it may please Him in inscrutable wisdom for his own great purposes,
to withdraw at times the sensible evidence of his life-giving Spirit,
so that we may have to deplore with Mary,
that "`they have taken away my Lord;`" yet as we remain stedfastly endeavouring to wait,
and watch, and pray towards His temple, He will in his own time,
most assuredly return to us,
as the morning breaking through and dispersing
the heaviest clouds that may have gathered,
to the strengthening of our faith in Him, and the increasing of our love:
proving himself the ever-blessed and ever-living Comforter, the Spirit of truth,
and leading out of all error into all truth;
whom the world cannot receive because it knoweth Him not.

I am not surprised to hear, that my dear William has been dipped again and again,
into a state of feeling something like that of baptism,
on account of the sufferings of others;--for unless this was the case,
how should we be capable of entering into their joys and sorrows.
And now that the whole weight of responsibility and
care of the family devolves upon his shoulders,
it is no marvel with me, that this increased burden should be felt.
I think this has a very instructive and significant meaning;
and although in degree inferior, is notwithstanding the same in kind,
as that felt and witnessed by the several members of the gospel church, where all suffer,
rejoice and sympathize with and for each other.
I believe that the head of a family or tribe,
when endeavouring to act under the guidance of Him,
who was touched with a feeling and compassionate
sense of our manifold weakness and infirmities,
may be favoured to administer, according to the ability given,
to the wants and necessities of those about him, entering into their feelings,
and sharing in whatever conflicts may be allotted to them.

I wish to make a grateful return to all those kind friends in Petersburg,
who have lent their aid in any shape in the day of your distress.
I am indeed one of those who owe much unto their Lord, both in these respects,
and in things more nearly connected with eternal consequences;
and having nothing to pay with, I do humbly trust,
that as he that administereth a cup of cold water only to a disciple,
in the name of a disciple, shall in no wise lose his reward;
so also that all who have administered to the
necessities of these little ones that believe on Him,
will witness the Divine blessing to rest upon them; inasmuch as they,
however unconsciously, "`have done it unto me,`" was the declaration of our Lord himself.

As to myself, I have truly little to communicate,
for since it has pleased our heavenly Father to magnify his power in
the midst of our long unbroken and highly favoured circle,
but little has transpired with me.
I told the Committee under whose care I move along, at their last meeting,
that in consideration of the state of my family,
I should be best satisfied to lie upon my oars at present,
until these calamities are overpast; of which I think approval was expressed.
I have attended the meetings in and about this metropolis, in all of which,
I have had to proclaim the spirituality of the dear Redeemer`'s kingdom,
and to direct the people to the Holy Spirit in their own hearts, of a crucified, risen,
and glorified Lord.
It is indeed a day of lamentation, mourning,
and woe,--for the expectation of the people is almost altogether outward, from man,
although vital Christianity was never more talked of.
