== Chapter XVI.

[.chapter-synopsis]
* Departure from the British Channel, with a Fair Wind, 15th of Third Month, 1834
* Voyage to Rio de Janeiro

[.offset]
+++[+++The succeeding extracts are from his journal and letters, commencing with the last date.]

After despatching our letters by the pilot on the 10th of Third Month,
we made sail into the offing at half-past four, p.m.,
and stretching from under the shelter of the Isle of Wight,
soon partook of a strong and favourable breeze: great progress was made during the night;
next morning brought an increase of wind along with it.
From the state of the weather and the harassed
situation of the crew and other circumstances,
although it was the First day of the week,
we were compelled to give up the idea of assembling together in the cabin,
and to content ourselves with reading the Holy Scriptures
twice in the course of the day with the captain and mate.
At five o`'clock, p.m. we were abreast of the Lizard light-houses on the Cornish coast,
from whence our final departure was taken: as the night approached,
the land was lost sight of, and the wind being strong and fair,
we launched rapidly away from the mouth of the British Channel.

On Second day morning, the 17th, the wind veered more to the southward,
and considerably increasing, soon raised a heavy sea,
which occasioned one side of the vessel to be frequently buried under water.
Until now she had scarcely leaked at all;
but it soon became needful to pump freely every two hours, and occasionally every hour.
This was a little discouraging to most of us;
but I recollected having heard from a carpenter who had formerly sailed in her,
that she used to let in a quantity of water in rough weather, whenever on that tack.
On considering the matter, and knowing the great pains that had been taken,
by our friend W. T., to make her sea-worthy, and having witnessed the caulking, felting,
sheathing and coppering that had been bestowed upon her,
I felt satisfied that this leak did not exist in
any part which is constantly under water,
but could only be in her upper works.
This conclusion, I have good reason to believe will be found correct,
for as the wind and sea have been more behind her, and that side not so deeply buried,
less pumping has been required.

Third Month 18th.--Our situation in the cabin was rendered more uncomfortable,
as from the frequent bursting of the sea over our deck,
it became necessary to secure the sky-light to prevent accident.
This reduced us into almost total darkness in the day-time,
as no light could now penetrate, except through the thick glass bull`'s eyes in the deck,
and these were covered with a body of water,
which rushed continually from side to side as the vessel rolled;
so that reading or writing, except by lamp-light, was laid aside altogether.

The 20th, being Fifth day, our usual meeting day when at home,
my dear Charles and myself sat down together to wait upon the Lord;
but although we were scarcely able to retain our seats from the motion of the ship,
yet I humbly trust we were favoured, poor outcasts as we seemed to be,
to look towards His temple,--to fear Him, and to think upon His name.
Notwithstanding the weather became more and more tempestuous,
yet the fair wind never once forsook us; but on the 22nd the sea ran so high,
that it was dangerous for any one to be upon deck,
and Captain Keen began to fear that we should be under the necessity
of turning the head of the vessel towards the sea and wind;
accordingly the storm canvass was prepared in readiness to use,
when it should become no longer safe to run before a sea,
which now followed in mountainous succession,
rising to an alarming height above the stern of our little flying bark,
and threatening at times to overwhelm us altogether.

23rd.--From the boisterous state of the weather, although First day had again revolved,
we were prevented from collecting the crew for devotional purposes;
and could only read some portions of Scripture as before.
By this time our little vessel had been pretty roughly handled and tried,
and had given full proof of her capability.
The captain acknowledged that she had done wonders,
and had greatly surpassed the idea he had formed of her,
and the crew to a man expressed their satisfaction;
and I saw myself no cause to alter the favourable opinion that
I had constantly entertained from the first sight of her.
We are all aware of the advantage which would have resulted,
had she been large enough to have carried a greater supply of fresh water and coals,
without being so deeply buried in the water,
which continually exposes us to the drench of the sea,
even in what may be termed favourable weather; and in rough,
we are frequently debarred from all exercise upon deck in fresh air,
to avoid the risk of being injured by the wash of the sea.
I feel, however, grateful and thankful in my present allotment,
and for the accommodation thus rendered by my dear friends;
humbly trusting that we shall be sustained through all
to declare the mighty acts of the Lord,
and to show forth His praise in the presence of a people who have not heard His fame,
nor seen His glory, neither conceived the majesty of His kingdom within,
of "`righteousness, and peace,
and joy in the Holy Ghost;`" which stands mercifully revealed in the hearts of those,
who are concerned above all things to seek first this heavenly kingdom,
and to believe therein, to the saving of the soul.

On the 24th there was an evident change in the temperature of the atmosphere;
the sun shone brightly, and its warmth gladdened our hearts,
as we sat on a small space near the stern of the vessel,
which had been preserved pretty free from the spray of the sea: the wind,
although still favourable, had lessened;
the white-topped billows had considerably diminished,
and our deck was this day more free from water rushing from side to side,
than had been the case for more than a week past.
Some turtle were seen floating near the ship,
and things altogether around us began to wear a brightening aspect;
but what tended most to enliven and make all things smile,
was the marvellous condescension of my dear Lord and Master, who,
in the greatness of his love, was graciously pleased,
for the first time since I had offered up my all to
follow Him in this untrodden path of apprehended duty,
to open my spiritual understanding, and permit me to behold, to a certain extent,
the nature of the service upon which I should have to enter,
in some places where my lot may be cast.
I now plainly saw that before leaving England,
I was not fit to be entrusted thus far with the secrets of my Master.
I believe I could not have refrained from imparting
them in degree to some of those whom I dearly love;
but happily I am now beyond the reach of such a temptation.
Perhaps I was not then sufficiently reduced into a state of preparation
suitable for the reception of so much of the Divine Will being revealed,
nor sufficiently humbled into a state of abasedness of self.
Greatly do I desire for myself and all my dear friends,
that we may be brought more and more into such a state as to be fit and able to
bear further portions of the many things which our great and heavenly Teacher,
in his wondrous and never-erring counsel, has to say to such as fear, and love,
and follow Him in the great work of regeneration:--"`I have many things to say unto you,
but ye cannot bear them now:`" and if we were but
sufficiently willing to hearken to his voice,
He would still, I am persuaded, not only have many things to say unto us as individuals,
but unto the church also, by that "`Holy Spirit which searcheth all things, yea,
the deep things of God.`"
Then may all our hearts be so cleansed and purified through the efficacy of his grace,
as to be prepared to receive the promised and ever abiding Comforter,
who "`will take of the things of Christ, and show them unto us,`" yea,
"`He will show us things to come.`"

Third Month 30th.--The weather beautiful, and wind favourable.
Assembled the ship`'s company both morning and evening in the cabin.
Whilst sitting together in silence in the forenoon,
I felt an engagement of mind to magnify the
lovingkindness of our good and gracious helper,
and to turn their attention as witnesses to the
unmerited mercy and favour bestowed upon us,
by the Lord`'s having so evidently and eminently prospered our way;
desiring that gratitude and thankfulness might be felt by every individual;
and declaring, unhesitatingly, that if we fear and love Him,
He will bless and prosper us altogether.
It was also with me to remind them,
that although from circumstances of one kind or other,
we might not be able to collect together in this way,
yet nothing should prevent us from fearing and loving the Lord;
that in the darkest night, our thoughts were not hidden from Him:
quoting that expression of the Psalmist,
when under a constraining sense of the omnipresence of the Deity,
"`Whither shall I go from thy Spirit?`" etc.
May the Lord be pleased to lay his Fatherly hand upon them!

Fourth Month 7th.--The sea being tolerably smooth,
the cabin sky-light was opened a few inches,
as our health began to suffer from want of air.
The sun being almost vertical, has been very hot and scorching.
The effect of being transported in about three weeks
from the cold winds which blew at the Mother-bank,
to the burning heat of the sun near the equator,
can be estimated only by those who have witnessed such
a change in so small a vessel as the Henry Freeling.
The night air seems to come off the heated deserts of Africa,
charged with dampness most unwholesome.

21st.--After having been nearly twelve whole days and
nights within five degrees of the equator,
we were favoured to get to the southward of it at an early hour this morning.

Fifth Month 5th.--Although hitherto favoured with a passage,
such as no person on board had ever before witnessed for favourable winds and weather,
yet it now became considerably lengthened out from the
prevalence of calms and light airs of wind,
not only whilst in the neighbourhood of the equinoctial line, but at a later period.
This circumstance seemed to point out at once the necessity of our abandoning the
intention of aiming at the Cape of Good Hope for a supply of water,
etc., on account of the advanced state of the winter season,
and the probability of not being able to reach
that place before those heavy gales set in,
which render its approach so difficult: it was also remembered,
that if we once made the attempt, there was then no alternative left to us,
but that we must continue to hover about until we did accomplish that object,
let the weather be ever so tempestuous,
as we must undoubtedly perish at sea for want of water
before we could possibly reach Van Diemen`'s Land,
a distance from the Cape of Good Hope of more than 6200 miles;
and from our present situation to the Cape it is full 3500 miles.
After deliberately weighing these considerations,
it seemed expedient (however contrary to our wishes,
to visit a place where superstition and slavery appear with open face,) to
bear down towards the South American continent for Rio de Janeiro,
and thence procure the needful supplies, if permitted to reach it in safety.

10th.--At sun-set a brig was seen upon our lee quarter,
steering the same course as ourselves, perhaps three or four miles distant from us;
she was soon covered up by the night, and no more thought of.
Being upon the deck,
(an usual practice with me the fore-part of the night,) between nine and ten o`'clock,
the carpenter suddenly exclaimed, '`Why here`'s the brig!`' Upon looking,
I saw the vessel at a considerable distance from us; but soon perceived by the stars,
that she was approaching with uncommon rapidity in a most suspicious direction,
as if intending to cross our fore-foot, and cut us off.
We watched her very narrowly, expecting every minute she would open a fire upon us.
She continued to haul directly across our head at a very short distance from us;
but we steadily kept our course, without the slightest variation,
or manifesting any symptoms of hurry or fear, or noticing her in any way.
I felt our situation to be at the moment very critical, knowing that these latitudes,
and particularly this neighbourhood, are exceedingly infested with piratical vessels,
which find shelter in the Brazilian harbours as traders,
where they fit out occasionally for Africa with merchandize,
and return with whole cargoes of oppressed Africans for sale,
landing them on private parts of the Brazil coast; at other times, they act as pirates,
when it suits their convenience, or are in want of stores.
This was indeed a trial of faith of no common kind; but my mind was staid upon the Lord,
feeling a good degree of resignation to his Holy will,
whatever might be permitted to befall us.

After watching the vessel with anxiety for some time, she passed away,
without making the least apparent stop.
On considering the matter, we concluded, that when she saw us at sun-set,
we were taken for a Dutch galiot, that might fall an easy prey to her;
but when she came up to us in the dark,
near enough to examine with telescopes the real shape of our vessel,
we were found of such a suspicious build of a non-descript kind,
not seen before in these seas,
as led to the supposition that we were intended as a decoy;
and though very tame looking without, yet perhaps fiery hot within, if meddled with.
From the position she took,
there is no doubt she expected to throw us into confusion by firing into us, and then,
in the midst of it, to have boarded us on the weather side.
There was not the least glimmer of light to be seen on board of her;
whilst the Henry Freeling was well lighted up in both cabins and the binnacle,
and the reflection from our skylights was well
calculated to puzzle and intimidate the crew,
as this circumstance would be sufficient at once to
show that we were not a common merchant vessel.
The captain, cook, steward, Charles, and myself,
were all additional persons upon the deck, besides the regular watch,
which would give an idea of strength, unusual in so small a vessel as the Henry Freeling.
Every thing was conducted with great quietness,
not the least hint given to any one on board to prepare for an attack:
the watch below was not even informed of what seemed to await us.
The Lord only was our deliverer,
for she was restrained from laying a hand upon our little bark;
and to Him alone our preservation is with gratitude and thankfulness ascribed.
The crews of these pirates consist in general of desperadoes of all nations,
who frequently commit the most dreadful atrocities on board the ships they seize,
putting to death all those who oppose their boarding them:
they are mostly crowded with men amply sufficient in number to
take and destroy some of our large armed traders.
This vessel was doubtless a selected one for the work:
we thought she actually sailed twice as fast as the Henry Freeling,
which is far from being a slow vessel.
We saw no more of her, and after midnight I partook of some refreshing sleep.

[.offset]
+++[+++It may be here observed, that during their stay at Rio, an American captain,
who had seen them at a distance at sea, going on board,
he was asked what he thought of the Henry Freeling,
when he saw her and his own vessel becalmed, near the equator: his answer was,
that he did not like the look of her,
and was glad when he could get farther away from her.
There is little doubt that we were taken for a pirate by all that saw us,
which perhaps might be of advantage,
except that it deprived us entirely of sending letters by any homeward-bound ships,
as none would have liked to come near, to ascertain what we really were.]

11th, First day.--The weather being beautifully fine,
the crew were collected upon deck twice in the course of the day,
for devotional purposes, etc.

12th.--Fine weather, with a fair wind all the day,
and a prodigious swell of the sea from the south-east.
The swell was so immensely large,
that we concluded that the summit of one wave was at
least half a mile distant from that of another.
A little before five o`'clock, p.m., land was proclaimed by the man at the mast-head;
shortly after,
we were able to behold from the deck the lofty cliff of Cape Frio on the coast of Brazil,
about sixty miles east of Rio de Janeiro,
just in the position and about the distance it was calculated to be,
from the true time of our chronometers, the lunar observations, and the dead reckoning;
all combining to prove the accurate navigation of the vessel,
and the nautical skill we possess on board of her.
Although we seem to be destitute of all interest upon this coast,
beyond that of the welfare of mankind the world over; yet,
after being fifty-eight days from England, during fifty-seven of which,
nothing was to be seen but water and sky; without having spoken another vessel,
or even seen more than six, the sight of Cape Frio was cheering and animating,
and raised in my heart a tribute of thanksgiving and praise to our never-failing Helper,
who hath in mercy sustained us in perfect safety,
across such a prodigious expanse of mighty waters.

Fifth Month 13th.--The wind continuing favourable, although not very brisk,
the whole of the night, considerable progress was made to the westward;
but when the day broke,
it was discovered that a strong current had swept us farther off the
land several miles than was the case the preceding evening.
Every possible exertion was made throughout the day,
and the different headlands and rocky islands upon the coast were so far recognized
as to enable us to steer with confidence towards the mouth of the river,
which we entered about three o`'clock,
p.m. We had intended to run up the harbour of Rio till nearly opposite the town;
but soon after passing the fort of Santa Cruz, from which several questions were asked,
we were compelled immediately to anchor, by an order from the guard-vessel.
In a short time after this, a bill of health was demanded, and a certificate,
signed by the Brazilian Consul in London, but as neither of these could be produced,
the vessel was at once declared under quarantine; and as it was in vain to remonstrate,
quiet submission was all that was left in our power,
which was manifested by our immediately hoisting a yellow flag.
Although somewhat prepared for this event, I was a little disappointed,
having anticipated that we should be once more
enabled to stretch our limbs upon the shore,
an exercise from which we had long been debarred.
For my own part,
I had not landed or been absent from the vessel for upwards of six months,
except the short interval of enjoyment in the company of our dear friends of
the Committee from the Meeting for Sufferings at the town of Ryde,
in the Isle of Wight; but I trust,
whether we are permitted to land or not on these shores,
that the same Almighty arm of strength will continue to uphold us,
which has been hitherto so marvellously stretched out for our support.
For although we have been fifty-nine days from the Mother-bank,
yet out of that time twenty-one days have been expended in calms and light breezes,
fifteen of which occurred, while near the equinoctial line, without intermission.
But the most remarkable thing is, that we have never made one tack,
from the time of leaving England to our anchoring here this day,
notwithstanding we have passed over more than fifty degrees of north latitude,
and twenty-three degrees of south,
(at sixty miles to a degree,) with upwards of forty-three degrees west longitude.
Would it then be accounted presumption in any one to hope, that He,
under whose constraining influence, in love unutterable, this voyage was prompted,
will be graciously pleased to prosper it, from the beginning to the end,
and cause it ultimately to tend to the advancement of the Redeemer`'s kingdom,
in the hearts of some of the benighted sons and daughters of the human family;
although such blessed effects may never be permitted to
come to our knowledge or to gladden our hearts.

[.offset]
+++[+++Here they performed a quarantine of five days.]

24th of Fifth Month.--To-day several hours have
been spent on shore by Charles and myself,
for the purpose of expediting the shipment of the needful supplies;
in the course of which we had much satisfaction in
unexpectedly becoming acquainted with two serious persons,
both natives of Scotland, at the house of James Thornton,
a relation of our kind friend William Tindall,
whose family is one of the solitary few in this place,
who are desiring to do the thing that is right.
Although we were amply provided with introductory letters, etc.,
to all the ports of importance throughout the whole voyage, viz.: the Cape of Good Hope,
the Derwent or Hobart Town, New South Wales, Lima, Valparaiso, Coquimbo, and others;
besides letters from the London Missionary Society`'s Secretary William Ellis,
to that Society`'s correspondents upon many islands of the Pacific Ocean,
where missionaries are established;
yet at last we were in some measure compelled to enter a port for which,
with all our contrivance, we do not possess a single document,
and are even unfurnished with a bill of health.
After considering the subject, I told my son Charles,
that I thought our coming here would not be without answering some good end,
though at the time there might be nothing in view,
nor had any thing occurred to give rise to such a supposition;
but on our meeting with the two serious persons above-mentioned,
an opening for some service presented to my mind,
and from the conversation which took place while we were together,
it seemed pretty clear to me that we should see each other again.
Before we parted, I was invited to attend a meeting,
which is held by the well-disposed English of this town
every First day evening at seven o`'clock,
which by them is termed a prayer-meeting.
I told them, after acknowledging their kindness,
that I could not give an answer at the moment,
that I must wait to see what to-morrow would bring forth;
and that if the way opened for me to accept the invitation,
I would take care to be in time.
Although it was very evident to me that it was no light thing
for a member of our religious Society to attend such a meeting,
and faithfully support the different peculiar testimonies given us as a people to bear,
and which to some might appear like opposition to or slighting
the forms and ceremonies which they have been trained,
perhaps from early youth, to the daily practice of,
yet it did not seem a time for me to shrink or hold back on that account:
leaving the matter altogether unfixed, we returned to our vessel for the night.

25th.--Both forenoon and afternoon the crew were assembled in the usual manner:
at both seasons a quiet feeling seemed to prevail.
In the course of the day, the prospect of attending the meeting on shore,
as a burden upon my shoulders, increased as the day wore away;
and believing that I should not be clear without giving up to it, accompanied by Charles,
I set forward, and reaching the shore just as it became dark,
repaired immediately to the house of James Thornton, where the meeting was to be held.
I thought there would be a propriety in speaking to some of
the principal persons privately before the meeting commenced;
so taking them aside, I told them,
that although we might have the same great and important object in view,
yet it was probable that we might not all see exactly alike,
and therefore I should prefer their going on with their meeting as usual; and if,
after it was over, we might be allowed to come in and sit down amongst them,
it would perhaps be the most agreeable on both sides; at the same time,
I candidly stated, that we could not engage to kneel when they did,
neither was it our practice to sing: and that we were desirous to offend neither Jew,
nor Gentile, nor the Church.
After some further conversation, it was concluded that they should proceed as usual,
and that we should sit by, and act, as was most easy to ourselves.
Accordingly, at the time appointed,
the company repaired to another room prepared for the occasion,
where some others were seated in readiness; and amongst these,
were several young black people that understood English.
It was previously arranged, that when the meeting was quite over,
the certificate furnished me by my dear friends of the Morning Meeting in London,
should be read, in order to account to all present for the appearance of strangers,
and to open the way for any communication on my part that might arise.

We retained our seats the whole time,
and my mind being under considerable weight of exercise, it was a relief to be left,
as it were, in the quiet.
The meeting being concluded, James Thornton read the Morning Meeting`'s certificate;
and after commenting awhile on its contents,
we were favoured to drop into solemn silence,
which continued until interrupted by my having to state,
that it had never been contemplated before leaving England,
that we should have to touch at a place where bigotry, superstition,
and slavery stalk unmasked with open face,
particularly as it had not come within the range of the prospect before us.
I acknowledged having mentioned to my son some days ago,
that I thought our coming here must be for some object unknown to us at that time;
but since we had been sitting together, I found that the Lord had a seed,
even in this place, that fear Him and think upon his name;
and unto these in an especial manner,
my heart was enlarged in the love of the everlasting gospel,
that love which would gather all mankind into the heavenly garner of rest and peace.
I had not proceeded much farther in the expression of a desire
that their "`faith might not stand in the wisdom of man,
but in the power of God,`" before I had to turn their
attention to the solemnity so evidently spreading over us,
as the crown and diadem of every rightly gathered religious assembly;
a feeling not at our command, nor in the power of man to produce,
and which could only be felt,
when the Great Head of the church fulfils his gracious promise,
--"`where two or three are gathered together in my name,
there am I in the midst of them.`"
After this the way seemed fully opened,
and a door of entrance also for the doctrines of the gospel in plainness and freedom.
I had particularly to speak of the nature of true spiritual worship,
and waiting upon the Lord,--the necessity of knowing for ourselves
the great work of regeneration to be going on,--the true faith of the
gospel as it is in Jesus the Author and Finisher thereof,
which worketh by love, purifieth the heart, and giveth victory over death, hell,
and the grave;--stating that I had nothing new to offer,
--that "`other foundation can no man lay,
than that is laid,
which is Jesus Christ;`"--reviving the terms prescribed by Himself to those who
would become his disciples and followers:--"`the poor in spirit,`" were reminded,
that to them the blessing appertains,
and the kingdom belongs:--the woful sentence to the unprofitable servant,
was contrasted with that of the faithful occupier of his Lord`'s talents;--the beauty,
purity, and spirituality of the true gospel church,
and the necessity and practicability of becoming members thereof, while here on earth,
was held up to view.
Considerable brokenness appeared in some individuals; and I believe it may be said,
that Truth rose into dominion, and reigned over all.
For my own part,
I never recollect being more sensible of continued
weakness and fear from the beginning to the end;
the creature was laid low,
and I trust was only desirous that all praise might be
ascribed to Him to whom it belongs for ever.
This was indeed a precious opportunity,
and although not obtained without ploughing a
furrow six or seven thousand miles in length,
across the unstable surface of the ocean, yet the love, joy, and peace that remain,
are a rich and ample reward.
We reached our little bark in perfect safety, with hearts full of comfort,
pretty soon after ten o`'clock at night, while a torrent of rain was falling;
in the midst of which the water was so remarkably luminous,
that every stroke of the oars seemed to dash the fire about us,
and the tract of the boat was like frosted silver.
The boat was manned with natives of Africa, now held in cruel bondage in this place;
they are, however, treated by us as fellow-men and brethren,
and truly my heart abounds with love not easily to be described,
towards these poor creatures.

Fifth Month 27th.--We were invited to meet some of the individuals,
with whom the meeting had been held the preceding First day evening,
at the house of one of them,
to afford them an opportunity of asking some questions
on particular points of Scripture doctrine.
To this there was no difficulty on my part in complying,
feeling more than usual freedom towards these people.

After having previously taken what exercise on foot the interval would afford,
about the time fixed upon we repaired to the place appointed.
One of those whom we thus met, is an individual of ardent and capacious mind,
and of a most amiable and benevolent disposition;
possessing at the same time all the advantages of a
scholar being acquainted with several languages,
and well versed in the Sacred Writings; and yet with all his good qualities and talents,
he is lamentably bewildered and carried away by enthusiastic ideas of the
time being near when the Messiah will reign personally upon the earth.
He brought forward several texts of Scripture to prove the correctness and
solidity of the argument upon which this hope was established,
which, according to the impressions upon my mind,
simply relate to the great and important work of conversion
and regeneration in the hearts of all true believers,
and which all have to pass through according to their measure, who are washed,
sanctified, and justified, "`in the name of the Lord Jesus,
and by the Spirit of our God.`"
It was with me to show him the snare by which he was so thoroughly entangled,
and the effect which it had of causing him to be
altogether looking without for that kingdom,
which can only be found, and must, as an indispensable duty first be sought for,
"`within.`"
It occurred to me as a suitable opportunity to bring forward the subject of
the Scriptures being so frequently termed by professing Christians '`The word
of God,`' that although many persons might not be in danger by this practice,
of attaching more to the letter than belongs to it,
yet it was much to be feared that its tendency was highly injurious,
and opposed to the spirituality of the gospel dispensation.
I found there was an openness to receive this remark,
which was not confined to this person alone, but extended to another present;
and that they had previously felt some doubts on this very important point.
At last one of them, as if at once convinced in his understanding,
exclaimed in the words of the apostle Peter, "`And this is the word,
which by the gospel is preached unto you.`"
Several other questions were put to us,
which I believe were answered satisfactorily to them.
I trust that the time expended was to some edification,
and that the noble cause did not suffer, though in the hands of such feeble advocates.

A copy of Bates`' Doctrines +++[+++footnote?]
and a pamphlet were thankfully received by an individual of the place, who,
I am persuaded, will not be disposed to keep them to himself.
I was in hopes whilst here,
of having an opportunity of distributing part of
our stock of Bibles in the Spanish language;
but I could not find any person willing to undertake
the risk of their being found in his possession.
In the course of inquiry on the subject,
it appeared that a considerable number of copies of the Scriptures in
the Portuguese language were at one time brought into this country,
and it is supposed were destroyed,
under pretence of their being too imperfect a translation to be circulated.

29th.--Having informed Captain Keen last night, that we were ready for sea,
at an early hour this morning, every preparation was made for our departure,
and a countersign obtained from the commandant of the uppermost fort in the harbour,
to enable us to pass the outermost fort of Santa Cruz.
At this place our shackles were all struck off, and the ocean set open before us.
When we arrived within hail of the fort, some questions were asked, amongst others,
'`where are you bound?`' To Tahiti was the reply, which,
agreeing with our entry outwards at the Custom house in London, was accepted.
The countersign was then demanded, and which was immediately given by us.
This was demanded and answered a second time,
when '`I wish you a good voyage,`' closed the ceremony.
Our captain having acknowledged the good wish, we took in our boat,
again trimmed the sails to the breeze, and bidding farewell to the coast of Brazil,
stretched into the southern ocean.
As rounding Cape Horn was my first intention, it has at times passed before me,
that if on our leaving Rio de Janeiro,
the wind should be strong and favourable for steering towards it,
I should feel a little difficulty in deciding which route to aim at;
but I believe I have felt desirous to be guided aright in this particular.

It being Fifth day, Charles and myself sat down together in the cabin as usual;
and after deep wading, a degree of that spiritual strength was graciously vouchsafed,
by which only the thoughts and imaginations of the heart can be cast down and subdued.

We were informed on respectable authority,
that two-thirds of the population of the neighbourhood
of '`St. Sebastian,`' consist of coloured people,
and that nothing could keep them in such a state of cruel and abject slavery,
but their having been taken from different tribes in Africa,
amongst whom a most inveterate enmity has constantly existed;
and care has industriously been taken to keep perpetually
alive such a spirit of revenge against each other,
as cannot be destroyed even by slavery itself.
This is spoken of as a politic measure, lest they should unite and set themselves free:
dreadful indeed would the day be to the majority of their white masters,
should such a thing come to pass, unless controlled by a higher power.
The slave-trade, though nominally abolished, is still carried on to a dreadful extent,
in an underhand manner.
Many ships go away loaded from hence to Africa,
and return with large cargoes of these unhappy victims,
which they land on distant parts of the coast, and then come into the harbour,
with perhaps a few elephants`' teeth, as if from an unsuccessful voyage.
This is well understood, and winked at.
We were informed, that five hundred newly imported negroes,
might be purchased in the neighbourhood at any time.
Although our tarriance at Bio do Janeiro was little more than a fortnight;
yet many of the poor negroes who had been connected with us by employment or otherwise,
had become much attached to us: and some hours after having left the coast,
it was fully ascertained that only a very slight occurrence had prevented
three of these people from being secreted on board our vessel.

The Roman Catholic religion appears to be rapidly declining in Brazil;
but alas! the religion of Jesus is still afar off to the human eye.
In two of the principal orders of friars,
we understood that no vacancy occasioned by death is permitted to be filled up,
so that these must finally die away altogether in a few years;
and they are now compelled to render an account of their finances,
as the property of the monasteries (at one time immensely rich)
is undergoing a regular transfer to the public treasury,
in proportion as the original holders diminish.
