== Chapter XIX.

[.chapter-synopsis]
* Sail from Sydney
* Arrive Off Norfolk Island
* Parting with James Backhouse and George Washington Walker
* Sail for the Society Islands
* Equinoctial Gale
* Enter the Torrid Zone
* Maitea
* Arrive at Tahiti
* First Interview with the Natives
* Visit from the King
* Prohibition of Ardent Spirits
* Meeting of the Missionaries and Natives at Papaoa

The day we first landed in New South Wales,
we were saluted by a most appalling volley of dreadful oaths and imprecations,
from some of the poor intoxicated creatures, in the garb of sailors,
who were standing about the stairs; but now, on quitting its shores,
I am thankful in believing that we have the prayers and good wishes of many,
however weak and feeble those are who offer them; and I think we can say,
that under a deep sense of utter unworthiness,
on leaving we were honoured with many honours, on the part of some.

We sailed on the morning of the 13th of Second Month, 1835, and at noon,
we stretched off the land into the Southern Pacific, with a strong opposing wind,
which increasing, soon raised a troublesome swell of the sea.
From the 14th to the 20th, we continued to beat against adverse winds,
although the weather remained fine for the most part.
The heat below was oppressive,
which kept all our passengers but myself in a sickly state for the first four days;
since which, they have been far from well,
as a considerable swell of the sea from the north-eastward
kept up an incessant motion of the vessel.^
footnote:[The following extract from the journal of our friend, James Backhouse,
between Sydney and Norfolk Island, relative to the seamen on board the Henry Freeling,
will, it is thought, not be out of place here.
{footnote-paragraph-split}
'`It is pleasing to see the seamen of the Henry Freeling
instructing one another in nautical observations and calculations;
the carpenter is a good navigator,
and since he became a steady man he has taken pleasure in instructing the other sailors,
who appear to be improving in knowledge and conduct.
They strongly exemplify the benefit of temperance principles on board ship.
They are allowed beer, when it is to be had, and as much tea, coffee, or cocoa,
as they like.
There is no swearing to be heard; and the men have the appearance of comfort,
and spend their leisure in improving themselves, reading, etc.
Happily neither the captain nor mate make a
foolish mystery about the course of the vessel,
such as is common on board many ships, by which the sailors are kept in ignorance,
to no purpose,
unless it be to enable the captain and officers to puff themselves up
with an unworthy conceit of knowing more than those under them,
and keep the sailors in a state of degradation,
inimical to good morals and conduct.`']

Second Month 22nd.--Yesterday the weather was fine and clear, but the wind contrary.
Several flying-fish made their appearance;
also an albatros and some smaller birds in the course of the day.
Today the weather is still beautifully fine:
our invalids pretty much restored from sea-sickness, and being the First day of the week,
portions of the Holy Scriptures were read to the ship`'s company assembled upon the deck.
During the time of silence in the morning,
James Backhouse compared the management of a ship at
sea with the spiritual progress of each individual,
showing the constant attention at all times necessary in both cases,
in order to be enabled to steer a true and steady
course towards the great object of our voyage,
both as regards an earthly and a heavenly port.
The latter part of the forenoon we sat down together in the cabin;
towards the conclusion,
I thought I was made sensible of a renewal of strength to wrestle for the blessing.

26th. (Fifth day.)--In the forenoon we sat down together in the cabin,
to wait upon the Lord: much poverty and weakness were sensibly felt.
The wind still adverse, with considerable swell of the sea,
but fine and pleasant weather.

Third Month 1st. (First day.)--Today we assembled the crew,
both in the forenoon and afternoon.
James Backhouse alluded to a text of scripture which had been
read,--"`Except ye eat the flesh of the Son of Man,
and drink his blood, ye have no life in you`"
--explaining the spiritual intercourse
and communion of the Holy Spirit with the soul of man,
and that the blessed partaking of the flesh and blood of the Son of Man,
'`can be witnessed by those only, in whom Christ dwells, and they in him,`' etc.
After dinner the wind became more favourable, and gradually increased to a fine breeze.

4th.--At day-light, we got sight of land, and gliding rapidly towards it,
Mount Pitt on Norfolk Island and Philip Island,
were both plainly in sight soon after breakfast.
When near enough to the Penal Settlement station, we made the private signal,
according to written instructions received from the government at Sydney.
Soon after this, a boat was discovered coming from the shore,
in the direction of our vessel, which at length arrived with a military officer;
who brought us a hearty welcome from the commandant Major Anderson,
accompanied by an invitation to his house.
On ascertaining that, although the landing was dangerous,
it was yet practicable in a suitable boat,
James Backhouse and George Washington Walker concluded
to make an attempt to return with this officer.
When all things were ready,
and my letters for England delivered to the care of James Backhouse,
we were thus hastily and unexpectedly torn from each other, at a short notice;
and although time was only afforded to take an abrupt farewell,
yet we all keenly felt the moment of separation,
but I trust with feelings that will lastingly remain,
through the frequent renewal of Divine love.
As the boat was not adapted for taking more than two or three passengers,
it was agreed that upon its reaching the shore, if then practicable,
a larger boat should be sent off immediately for the luggage.

5th. (Fifth day.)--The boat not reaching us yesterday in consequence of rough weather,
at an early hour this morning we edged down towards the Penal Settlement,
and a boat was shortly afterwards discovered making towards us from the shore,
which eventually proved to be the conveyance for the luggage of our dear friends;
being safely loaded, and a few lines written to James Backhouse,
requesting him to acknowledge the kindness of the commandment on our behalf,
the boat put off from the vessel;
when we immediately began to beat off the coast in earnest,
and passing between the islands of Nepean and Philip, at ten o`'clock a.m.,
once more launched forth on the capacious bosom of the Southern Pacific.
Nepean Island is little more than a large barren-looking rock,
but said to abound with rabbits: Philip Island exhibits more fertility,
and abounds with hogs.
The officer who came on board informed us,
that a party had been sent from the settlement the preceding week over to Philip Island,
and had succeeded in shooting and returning with eighty of these animals.
Norfolk Island appears from the offing to be about half the size of the Isle of Wight,
and is richly covered in places with a beautiful pine, peculiar to the island,
which we had seen growing in the neighbourhood of Sydney,
having been transported thither by the Governor and other individuals.
The valleys abound with lemons, limes, grapes, guavas, etc.

For some days previous to making Norfolk Island, my mind was at times drawn to consider,
whether I might not have to land upon it myself, and remain a few days;
but I believe I may venture to say,
that I did not in the slightest degree perceive
that it formed any part of my duty to do so;
neither on receiving the commandant`'s invitation,
nor afterwards on an expression of regret communicated by note from James Backhouse,
did any thing arise in my heart, as if I flinched from that service.
His note says, '`Much regret is expressed, that you did not come on shore,
and I hope if you feel inclined to come, you will yet do so;
though I do not regret you did not come with us, as we got a surf on our backs,
and the boat`'s nose upon a rock: but though thus permitted to feel the danger of landing,
by the good providence of our merciful heavenly Father,
we were preserved from further suffering.
If we do not see you again before you proceed to Tahiti,
I will once more bid you farewell in the Lord.
May He continue in condescending goodness still to be with you,
and qualify for every good word and work, to His own glory and your peace;
and may His good Spirit still more and more work into
subjection to Himself the shipmen of your vessel,
that you may have increasing comfort in them.`' Having thus been favoured to
accomplish the landing of our beloved friends and brothers,
with their luggage, without a detention of more than twenty-two hours,
however much their absence may be felt,
the suspense and anxiety with which my mind had been filled,
from a knowledge of the great risk which at all times attends such an undertaking,
where there is no shelter from the surf of the wide ocean,
was wholly relieved and removed.

It being our usual meeting-day,
dear Charles and myself sat down together in the forenoon,
and although stripped indeed as to the outward, yet comforted from a sensible evidence,
that a most merciful and gracious Lord remains to be "`God over all, blessed forever.`"

Third Month 8th. (First day.)--Yesterday the weather continued unsettled and showery,
and today the wind is contrary, with fresh gales and clear weather.
We read portions of the Holy Scriptures twice in the course of the day in the cabin;
as the state of the weather and a heavy swell of
the sea prevented our assembling upon deck.
At sunset we fell in with a shoal of spermaceti whales,
one of the largest in sight passed by the side of our vessel,
at a distance of ten or twelve yards.
This fish would contain about fifty barrels of oil.
There were at least twenty of them within a small compass around the Henry Freeling,
and it is probable they formed but a small part of the shoal.

10th.--Since leaving Norfolk Island,
but more particularly within the last three or four days,
it has been to me at times a trying, proving season.
The loss of the company of our dear friends,
with whom we had been closely and sweetly connected for more than five months,
either by sea or land,--the steady opposition of the winds since we separated,--the
great distance we have yet to go,--the advanced state of the season,
towards the autumn in these regions,--and yet above all,
the absence of Him in whom my soul delighteth,--
combined to weigh down and oppress my poor,
tossed mind, beyond the usual degree.
But in the depths, although unable to draw nigh,
I endeavoured to look towards the holy temple: I remembered the Lord, and my prayer was,
I trust, permitted to come in unto Him; and He remembered a poor unworthy creature,
and in His own way and time, was graciously pleased to speak comfort,
and to seal instruction.
The affecting instance of the dear Son of God himself, was brought to my remembrance,
"`who was made sin for us, who knew no sin,`" and died, "`the just for the unjust,
that He might bring us to God;`" when,
in the very act of child-like and lamb-like obedience,
and meek submission to His holy Father`'s will,
from the extreme depth and weight of suffering upon Him for the sins of poor, lost,
guilty man, He poured forth the agonizing query, "`My God, my God,
why hast thou forsaken me?`" and I am renewedly persuaded that these present trials,
and proving baptisms, are all in unutterable and inconceivable love and mercy,
dispensed for the preservation of that precious life which is hid with Christ in God.

15th. (First day.)--Assembled the crew twice in the day, for devotional purposes.
During the latter part of the interval of silence in the afternoon,
petitions were raised in my heart to the throne of grace,
for the best welfare of our little company.
A whole year has now passed away since we sailed from the Mother-bank,
and although more than seven months of that time have been spent upon the mighty deep,
and with the exception of a few transient intervals, out of sight of land altogether;
yet such is the boundless and unmerited mercy of Him with whom we have to do,
that if the question were asked, '`Lackest thou any thing?`' '`Nothing,
Lord,`' would immediately be responded.

Third Month 16th.--This afternoon we were in the latitude of Cartes Island,
Macauley`'s Rock, and several others of recent discovery,
extending from this latitude northward for more than 200 miles,
and some of them level with the surface of the sea; therefore at six o`'clock p.m.,
we tacked, and stood to the southward,
rather than risk being driven too near such treacherous neighbours.

Fourth Month 1st.--By nine o`'clock last night, the wind became quite fair;
but in a short time it began to blow strong, and the sea rose so rapidly,
that at midnight we again hove to under storm-sails.
As the mercury continued gradually to lower in the tube,
and the storm to increase with appalling violence,
there now seemed no doubt but an equinoctial
gale had overtaken our often-tried little bark.
It raged with great fury throughout the night,
and returning day seemed only to increase its strength.
At noon the sea wrought in an awful manner,
and frequently the white crests of the mountain billows,
were carried off by the sweeping and irresistible tempest,
and uniting together flew in one continued mass
of drift several yards above the rugged surface,
with incredible force.
Yet on this, as well as on former occasions,
the Divine Arm of everlasting love and strength was not only near for our support,
to compass us about as with a shield,
but mercifully to overshadow us with a canopy of peaceful resignation.
Not a sea was permitted to injure our vessel,
and even the weaker part of her upper works remained unbroken through it all.
How correct is the animating declaration of the
Psalmist,--"`The Lord sitteth on the flood;
the Lord sitteth King forever.`"
And is it not encouragingly verified? "`The Lord will give strength unto His people:`"
those that fear, love, honour, and obey Him, these are his people;
and "`the Lord will bless his people with peace.`"

Fourth Month 15th.--Fresh and favourable gales; we made great progress,
and to all appearance, the wind we had been so long expecting was fairly set in,
and we were once more venturing to look forward to a termination for a time,
of our "`perils by sea.`"
But the pleasant anticipation was shortly afterwards disappointed,
by its being ascertained that from our present position
a dangerous reef lay directly across our path;
which, at the rate we were sailing, we should probably get close upon by the setting sun.
As the sea was running pretty heavy it seemed doubtful
whether we could pass to the southward of this reef,
it was therefore concluded best, as suggested by my Charles,
that our course should be forthwith altered sufficiently to
insure our passing it in safety to leeward,
which was accordingly done.
As the exact position of this reef cannot be fully relied on,
any more than that of our vessel, owing to the clouded state of the atmosphere of late,
we seem to have no outward prop to lean upon through the cheerless gloom of darkness;
but we well know there is a Power almighty and all-merciful,
whose compassionate eye never slumbers.

Fourth Month 23rd. (Fifth day.)--At two o`'clock p.m. yesterday,
we passed the tropic of Capricorn, and entered the torrid zone.
The latitude at noon was 23째 38`' south: by lunar distance, well taken this morning,
the longitude was found to be 142째 36`' west.
The latitude of Tahiti is 17째 29`' south, longitude 149째 28`' west.
As the wind now blows, our being so far to the eastward is an advantage,
in making it completely fair for us.

27th.--Yesterday, though heavy rain fell near us throughout the day,
we were not prevented from assembling in the usual manner twice in the course of it,
it being First day.
At noon today, the island of Maitea was distant fifty miles.
It would have been relieving to have come within sight of this island before dark;
but although the horizon was pretty clear at sunset in that direction,
it could not be distinguished from the mast-head.
Many birds have been daily with us latterly,
a fact which strongly indicates our approach to land;
and the course which these take for their evening flight,
speaks in plain language where it lies.

28th.--At day-break this morning, Maitea was in sight;
but the wind being light and fickle through the day,
it was nightfall before we had fairly passed it by.
This island is now used as a penal settlement for Tahiti.
Last evening a sufficient number of albicoas and bonitos were caught by the sailors,
to furnish the whole of us throughout the day with fresh meals;
and as it was more than six weeks since we had had one, they proved very acceptable.

This morning, 29th of Fourth Month, about half-past one o`'clock,
the mountains of the long-looked-for Tahiti,
were discovered through the gloom upon our lee-bow.
It will be eleven weeks tomorrow since we left Sydney,
and with the exception of the equinoctial gale, we have during the voyage,
for the most part been favoured with fine weather,
but with an unheard-of proportion (for these seas) of
contrary winds during nearly the whole time,
completely setting at nought all former experience.
After leaving Norfolk Island we traversed from
twenty-nine to forty degrees of south latitude,
in the hope of finding the westerly winds, which usually prevail,
to waft us to the eastward; but could never meet with them to any purpose,
and since we entered the trade latitudes, to this day,
we have been in constant expectation of meeting with the south-east trade-winds,
to enable us to fetch the island of Tahiti, and have in this been equally unsuccessful.
We have, however,
after traversing various zigzag courses over more than 5000 miles of ocean by the log,
since leaving Sydney, been guided to a hair`'s-breadth, in so remarkable a manner,
as to get the first sight of the island when nearly
dark;--the moon not being twelve hours old at the time.
The darkness and the light are both alike to Him, who hath been with us,
to bless and preserve us;
enabling us in degree to "`glory in tribulation,`" and even to bear
privation for His name`'s sake,--indeed as not being worthy to be recounted,
because of the love, and peace, and joy, which at seasons have been our happy portion.

30th.--At noon passed through Matavai bay.
A canoe with four of the natives came off to us, bringing oranges, guavas,
and other kinds of fruit; these we purchased, after much bargaining,
for a hank of thread and three small needles to each individual,
although the price they first asked was a dollar for each basket;
there were five baskets of fruit.
We were all pleased with the openness and simplicity of these people.
At two o`'clock p.m., we took the pilot on board,
and immediately entered the channel within the reefs;
but after getting through the most dangerous part, it fell calm,
which obliged us to drop an anchor for the night,
directly opposite the house of George Bicknell, so close to the shore,
that a mooring hawser was made fast to one of his coconut trees.
By this time our deck was covered with the natives.
Just as we were ready to go on shore to take tea at George Bicknell`'s, to whom,
as deputy Consul, the mail brought from New South Wales had been delivered,
the young king (or perhaps it is more correct to say,
the husband of the queen) came on board, with his younger brother and uncle,
and several others; they behaved with great openness and cheerfulness,
and seemed highly pleased to see us.
Our captain was personally known to them already.
They soon looked round the vessel, apparently delighted; left us a basket of oranges,
and said they would come again tomorrow.
To my great rejoicing, the pilot soon after coming on board,
informed us of the entire disuse of ardent spirits in Tahiti;
saying '`rum is no good here.`' The total prohibition of
spirituous liquors has been so strongly enforced,
that they have taken them out of private houses without exception, and thrown them away;
and the natives have carried it to the length of smelling the breath of people,
to ascertain whether they had been used, and if found to be the case,
a severe fine was imposed;
so that a person well known to lead a thoroughly sober life
was not allowed to have such a thing in his possession,
but was liable at any time to undergo a search.

Fifth Month 1st.--At day-break the pilot came on board, and the breeze being favourable,
the vessel was got ready, and run gently down to Papeete Harbour: the water was so clear,
that the beautifully spreading branches of coral could be plainly
distinguished as we passed over the most shallow parts of the reef.
About nine o`'clock a.m., we took up our station in a well-sheltered cove or harbour,
surrounded by straggling houses and plantations of the coconut tree, banana,
breadfruit, orange, and sugar cane, ranging along the edge of the sea,
on the level land at the foot of the mountains.
In the forenoon, George Pritchard, the resident missionary came on board;
for whom we were bearers of many letters and parcels, which proved very acceptable:
in the afternoon we visited his habitation,
and were kindly received by his wife and family.
George Pritchard very kindly inquired whether I
wished to be at the worship of the Tahitians,
next First day;
but I informed him that I believed it would be
best for me to be with my own crew on that day.

Having endeavoured to keep my mind exercised to ascertain the will of my Lord and Master,
it was with me to tell George Pritchard that the first step which I had to take,
was to request a conference with the whole of the missionaries in this district;
asking him if they had any stated times for meeting together by themselves:
he said they had, but a special meeting could be convened for the occasion.
On considering a little,
he found that their next quarterly meeting in regular course
was to be held the second week in the present month.
As the month was already come in,
I thought it would be unreasonable to subject the
parties to the inconvenience of meeting on purpose,
as their own meeting would still necessarily have to be held on the appointed day;
more especially as I had several affairs to regulate, and preparations to make,
to enable us to barter for supplies, etc.
At present, I see no further than to attend this conference,
and there produce the certificates furnished by my dear Friends in England;
humbly trusting,
that the path of my future proceeding will be graciously manifested in due time,
and strength and perception mercifully afforded to enable me to walk faithfully in it.
I had been unwell on the 12th instant, but having passed a more favourable night,
on the morning of the 13th instant, I felt no hesitation about proceeding to Papaoa,
as the day was fair overhead.
George Pritchard called with a boat,
to take Charles and myself with him,--he finding three natives to row, and myself two.

Having understood that on the present occasion,
the principal chiefs from all parts of the island would be there,
and a large muster of the inhabitants residing in this district,
it occurred to my mind that it would be a favourable medium,
through which my arrival might be publicly announced to all the distant districts,
if at a suitable time my certificates were read.
On mentioning this to George Pritchard,
and showing him the translation so kindly made before I left London by William Ellis,
he at once saw the propriety; but said it would be necessary to consult Henry Nott,
the senior missionary, resident at Papaoa,--George Pritchard himself being a junior:
this was a matter of course, and had I been aware of the distinction,
I should myself have proposed it.
From the wind having sprung up a fresh breeze against us,
we were rather late in reaching our destination;
and Henry Nott had taken his seat in the meeting before we got to it.
We followed George Pritchard through a large number of people already assembled,
until we got up to Henry Nott; who, on being consulted,
immediately consented that it should be done, when their service was over.
We then took our seats, having kept on our hats until that moment:
but the heat of the climate renders it too oppressive
to keep them on for any great length of time.
We heard of no remark, however, having been made on this head,
whatever might have been thought.
They commenced by George Pritchard giving out a hymn,
then part of the epistle to the Ephesians was read,
after which George Pritchard kneeled down and prayed; another hymn was then sung,
and was followed by the sermon, delivered by Charles Wilson,
from a text out of the same epistle; when this was finished, another hymn was given out,
at his request, and he afterwards finished with prayer.
Some business then came on relating to the affairs of the Missionary Society,
when the queen of the island took her seat as its president.

We merely sat as silent spectators through the whole of this,
which from beginning to end was conducted in the Tahitian language.
As only George Pritchard sat between myself and the queen,
I observed that she was employed in reading my certificates,
which had been previously laid upon the table.
The whole of my certificates were then audibly read in
the Tahitian language by George Pritchard;
who took great pains to give ample explanation whenever needful.
The marked attention and solidity of countenance manifested by the Tahitians,
was both striking and comforting;
and the solemnity which spread over this large assembly
had previously covered my mind as with a mantle,
contriting my spirit under a sense that the great Master himself was there.
After the reading of the certificates was gone through, profound silence reigned.
I asked if I might say a few words, which was at once permitted,
and George Pritchard agreed to interpret for me.
I requested him simply to repeat what I said,
and I have reason to believe this was faithfully done;
and was to the best of my recollection after this manner:
'`I have no wish to trespass upon the time of this meeting.
I was desirous that these documents might be read,
which would account for a stranger being present,
and inform all that I came not here in my own will,
but in the will of my Lord and Master, whose I am,
and whom I desire to serve to my latest breath; and would also let you know,
that I came with the full unity and consent of
that branch of the Christian Church in England,
of which I am a member.
And now, grace, mercy, and peace from God, the Father, and our Lord Jesus Christ,
be multiplied upon all the inhabitants of this land; and may the God of peace,
who brought again from the dead our Lord Jesus, that great Shepherd of the sheep,
through the blood of the everlasting covenant, keep our hearts and minds,`' etc.

After I sat down, a solemn silence again prevailed, until one of the natives,
a supreme judge, broke it by addressing me by name,
which he had caught from the certificates;
and declaring on behalf of himself and the islanders,
that the manner of my coming among them was very satisfactory,
because what had been read and spoken, was in accordance with the gospel,
which they had been taught, and were acquainted with.
He also at considerable length touched upon the great
distance I had come over the deep waters to see them,
and to do them good; that in return, their hearts, and arms, and habitations,
were open to receive me;
duly appreciating the disinterestedness of the motive that had induced the step;
having no trade, nor other object in view.
He hoped I should visit all their schools, and stroke the heads of the children;
that he should now deliver them all into my hands.
I told George Pritchard to say, that the dear children would always have a strong hold,
and a strong claim upon my heart.
Much more transpired that was truly consoling and comforting;
and the missionaries who spoke on the occasion, I truly believe,
most fully and cordially cooperated in endeavouring to
explain my views to the people in terms of strong approbation.

Although the above may not be exactly verbatim, it is the substance of what passed.
When it was all over, Henry Nott kneeled down,
and concluded the meeting with prayer in the Tahitian.
The natives then generally rose from their seats, and began to flock round us,
and to shake hands with Charles and myself in a very hearty manner,
and without regard to order, age, or sex,
from the humble peasant to the bronze-coloured queen, her two aunts,
and the numerous chiefs, who, I think, are the stoutest,
most giant-like men I ever saw assembled together.
About 800 persons were collected at this meeting;
but the house was so large that it seemed impossible to make any accurate estimate;
for my own part, I should have supposed the number not less than a thousand.
The judge before spoken of, in one of his speeches,
(for he spoke three times,) hinted that they perceived I was not exactly of
the same description of Christians that had hitherto come amongst them,
or I belonged to a different body.
This, however, did not seem to stand in the way.
Some days previously to this meeting being held,
the young king and several chiefs came on board to breakfast, six in number.
After breakfast, our usual reading in the Holy Scriptures was introduced,
during which they behaved with great attention and propriety; sitting as still,
in the time of silence, both then and at the pause before breakfast,
as if accustomed to it.
When they were about going away,
a telescope and a piece of handkerchiefs were presented to the king,
and a shawl to each of the others; with which they seemed highly pleased.
Through the medium of an Englishman, who had been sent for on the occasion,
the king was told, that I had something in reserve for Pomare, the queen,
expecting she also would pay us a visit.
They behaved with much openness and affability,
and told us in plain terms that they liked us, because we were like themselves,
and did not make ourselves very high to them.

I had a conference with the missionaries of the Papaoa district, who,
although only four in number,
are capable of rendering me much assistance in forwarding my views,
and interpreting to the people.
I was fully aware the missionaries were under an impression,
that I was come out to inspect the state of the missions,
and particularly that of the schools;
private letters had reached them some months ago to that effect from London;
but they were informed that now the missionary meeting was over,
I was waiting as at the posts of wisdom`'s gate,
not knowing to what I might next have to turn my hand:
this explanation at once placed me in a fresh point of view.
An expression of desire to do all in their power to cooperate in the work,
in any manner I could point out, was, I think, avowed by each individual;
and we parted in brotherly love.
