== Chapter XXIII.

[.chapter-synopsis]
* Visit from Missionaries
* Baron de Thierry
* Meeting in the Chapel
* Sail For Eimeo
* Letters from Home
* Arrive at Eimeo School
* Native Meeting

Seventh Month 29th.--This day arrived the Frances of New Bedford, John Briggs master,
whose vessel rode by our side, fourteen months ago, when at Rio de Janeiro:
it is like meeting with an old acquaintance, as we were known to each other at that time.
The chief Paofai came on board this morning; he stayed breakfast, and our reading.
He was desirous to buy cloth, and to possess one of our iron boxes;
neither of which could be spared to him.
In the afternoon, Charles Pittman the missionary from Rarotonga, came on board.
Our two invalids have been reported in a convalescent state.

30th. (Fifth day.)--In the forenoon, Charles and myself sat down in the usual way,
but under a renewed sense of dryness and barrenness;
which perhaps was the food most convenient for us,
to keep the creaturely part in subjection.
Charles and Elizabeth Pittman, Eliza the wife of George Pritchard, and Mary Darling,
paid us a visit.
The impaired state of the health of Charles Pittman has
compelled him to quit his station at Rarotonga for the present,
being no longer able to attend to the duties devolving upon him.
His wife is also far from well.
They have resided about ten years upon the island,
where their united labour has been eminently crowned with success.
The circumstance of there being no harbour for shipping,
except for vessels of very small tonnage, and that insecure,
although the means of subjecting them to many privations,
is a great blessing to the people of that island;
because they are thereby preserved from the contaminating example and effects,
which the sailors invariably introduce wherever they go; and to this may,
in great measure,
be attributed the success of Charles and Elizabeth Pittman`'s endeavours:
at the same time, it is only just to say, they are a truly devoted couple,
and well qualified by example as well as precept, to fill the station they have occupied.
They hope to return to the island in a few months;
and being desirous that the natives might be furnished with cotton dresses,
for want of which they evidently suffer much in their winter seasons,
it seemed a good opportunity afforded for me to
furnish them with a stock of knitting-needles,
as cotton grows spontaneously and plentifully upon the island: this was accordingly done,
together with a knitted worsted vest, as a pattern to begin the work with.
They need only to commence the work, and their wants will soon be supplied;
industry would also be promoted, of a kind not too fatiguing,
and which they are capable of sustaining: hard labour cannot be borne in this climate,
and I think the ample supply of food provided for them by a bounteous Creator,
plainly indicates it was never intended or required.

31st.--This morning arrived the barque Active from Panama.
Wishing to ascertain whether she had picked up any letters for us on the road,
and other particulars respecting her, Captain Keen went on board to make these inquiries;
he soon returned, bringing with him Charles, Baron de Thierry, as he styled himself,
who with his wife, five children, and servants, had arrived in this vessel,
which had been chartered by him at Panama.
The baron`'s object in coming with our captain, was to inform me,
that he was going out to New Zealand, exactly as our predecessor William Penn,
went to establish the government of Pennsylvania; but I found,
on investigating his views,
that he was a perfect stranger to the principles which
actuated William Penn in his government of that colony:
as he was taking with him a military force, with arms, ammunition, etc.,
and a Polish major, (Edward Fergus, formerly employed in the staff of Russia,
and at Petersburg,
with whom we soon became acquainted,) to organize these troops in New Zealand,
and direct their operations as needful.
I told the baron that I could enter into his plans,
just so far as they went upon gospel principles, and no further;
informing him that no weapon more formidable than a constable`'s staff,
was made use of for more than sixty years,
for the support of the government of Pennsylvania,
or while the peaceable principles of William
Penn and his friends were suffered to prevail.

Eighth Month 1st.--Today,
I did not feel as if I dared omit endeavouring to hold
another meeting on board the Charles Carroll tomorrow,
if that ship`'s deck could be again procured: I did not mention this until the afternoon,
wishing to try the fleece both wet and dry.
On a request being made to Reuben Weeks, the master of the said ship,
for the use of her deck, it was immediately granted,
and the crews of the different ships in the bay invited to attend the meeting.
In the evening the invitation was extended to the shore.

2nd. (First day.)--At half-past ten o`'clock, a.m.,
a warning-flag was hoisted on board the Charles Carroll:
and about eleven o`'clock the meeting was completely gathered.
The number of sailors who attended was considerably
increased by those from the newly arrived vessels.
Charles Pittman, Mary Darling, and Eliza Pritchard, attended from the shore,
with Charles de Thierry, his wife, and the Pole, Edward Fergus.
After the attention of the people had been arrested by
the object of our meeting together being explained,
a general silence prevailed.
At length, I stood up with the words; "`The wolf shall dwell with the lamb;
the leopard shall lie down with the kid;
and the calf and the young lion and the fatling together:
and a little child shall lead them,`" etc.
After alluding to the fulfilment of this prophecy in the gospel dispensation,
as shadowed forth by Isaiah,
I had to tell them that these are the very days in which we live;
every individual had a share in it, and a part to act in it,
though of general application:--that the gospel was not
a mere outward declaration of good things,
but "`the power of God unto salvation,`" to all who believe, repent, and obey it;
and that its privileges could only be attained through Christ:
that the early promulgators of the Christian religion
were constrained to turn all men to Christ.
"`We preach not ourselves, but Christ Jesus the Lord;
and ourselves your servants for Jesus`' sake,`" was the
apostle Paul`'s declaration to the primitive believers,
on behalf of himself and fellow-labourers:
but he himself had a more special and divinely authorized commission,
communicated immediately by the voice of that Saviour,
whom he had so long and cruelly persecuted, wherever His appearance could be found:
it was stamped with a double seal, for a two-fold purpose,
as a minister and a witness of those things which he had seen,
and of things which were hereafter to be shown to him;
in which his Lord would appear unto him, to open the eyes of mankind,
to turn men from darkness to light, and from the power of Satan unto God.
That Christ was the Light, the true Light,
that lighteth every man that cometh into the world; unto whom all mankind must be turned,
and must come, if they are saved, etc. etc. It was a highly favoured, solemn meeting,
and owned by the great Master of assemblies; whose power reigned gloriously amongst us,
causing thanksgiving and praise in many hearts.

7th.--Walked in the evening to George Bicknell`'s,
and had an opportunity of seeing the master of the Olivia schooner of Boston,
lately arrived from the Paumotu islands.
He seemed in the last stage of consumption, was unwell when he left home,
and has been exposed to great hardship amongst those islands.
His complaint has been much increased and aggravated by
having long to subsist on fish and cocoa-nuts.
He appeared glad to see me; and after sitting awhile by the bedside,
I began to advert to his appalling situation, winding gradually on as matter opened.
On saying it was little matter how soon we leave this world of trouble,
if we are but prepared for the event; he said, '`I am not prepared,
and cannot prepare myself.`' I told him I was even rejoiced to
find he was thus sensible of his own inability and weakness,
because it was a conscious feeling of the want and necessity of the Saviour`'s help.
I endeavoured to turn his mind to the dear Redeemer; but he said,
'`the time was too short to expect to accomplish the great work,`'
and spoke as if it had been too long deferred.
I reminded him that the invitation was extended even as late as the eleventh hour;
and then mentioned the thief upon the cross, with the words,
"`Today shalt thou be with me in Paradise.`"
He seemed a little encouraged before we parted.
I was afraid of staying too long, and of causing too much excitement,
but a prayer ascended in secret for him both then and since.
When about to leave, he expressed a wish for me to come again,
and I hope to comply with it.
I was comforted in finding he had got into a place where he would want for nothing,
and be well attended to.
I consider it an act of true Christian benevolence in George Bicknell,
with his large family, to take in, without solicitation, this poor, exhausted,
sick stranger; and cheerfully to administer to all his wants,
without any prospect of remuneration.

8th.--Busily employed on board, closing our letters for England,
to be despatched this day by the Active, for Panama.
Got some exercise on shore in the evening.
It has occurred to me, since the last meeting held on board the Charles Carroll,
that the chapel on shore would be the next place for me to be in;
although I mentioned it to no one, desiring to see the way clearly open,
before any steps were taken.

Charles Pittman came on board yesterday: and in the course of conversation said,
that it had been thought whether I would not come on shore the next sabbath-day,
to have a meeting; and that he himself was desirous that some arrangement should be made,
in which he expressed a willingness to assist.
I told him it was yet uncertain,
but that I intended calling at George Pritchard`'s house in the evening.
On arriving there, I found Charles Pittman under the verandah, talking to a sailor,
who had belonged to the Charles Carroll,
and had then come to have some conversation on the subject of religion.
It appeared that this young man had been reached,
at the last meeting held on board that ship, and was desirous of help and advice.
He found it very hard work to stand against the strong current of evil,
to which he was exposed on ship-board, amongst a rude and wicked company,
who continually annoyed him in one way or other.
He was encouraged to watchfulness, and to perseverance in resisting every temptation;
and if faithful, he would doubtless overcome them all, through the strength of Him,
who for our sakes "`endured such contradiction of sinners against himself.`"

Whilst at George Pritchard`'s, I inquired whether any missionary was expected,
or whether any meeting would be held there tomorrow,
which was replied to in the negative.
I said that I felt a little difficulty about their meeting-house,
as it belonged to the people on shore,
and they might be disappointed at not finding one of their own ministers there;
and I could not answer, if I attended the meeting, but that it might be a silent one,
which to some would be a disappointment; but Eliza Pritchard said, they know very well;
I suppose she meant, the manner in which the meetings of Friends are usually held.
Having believed it right for me to hold a meeting there, previously to leaving the ship,
what had passed served only to show that the way was open before me; and going out,
I said,--'`Then I think we must venture to give notice to the shipping,
that a meeting will be held at eleven o`'clock
tomorrow forenoon.`' As we returned on board,
some information of the intended meeting was given by ourselves,
and our captain engaged at once to invite the crews of the shipping generally,
and to spread the information more widely on the shore.

Eighth Month 9th. (First day.)--At the time appointed, repaired to the shore,
landing at George Pritchard`'s,
whose family with Charles Pittman and wife accompanied us to the meeting.
The attendance was much larger than at any time before.
The baron, his wife, and the Pole, appeared amongst others.
We sat long in silence; when I stood up,
with--'`It was never said to the wrestling seed of Jacob, seek ye my face in vain;
"`for the sighing of the needy now will I arise, saith the Lord.`"
Let us remember the example of Jacob,
who wrestled for the blessing until the break of day, although the angel said,
"`Let me go, for the day breaketh;`" but the patriarch refused to grant the request,
saying, "`I will not let thee go, except thou bless me.`"
The result of his faithful perseverance was, that his name should be no longer Jacob,
but that he should be called Israel; for, said the angel,
"`as a prince hast thou power with God and with men and hast prevailed.`"
After urging upon all present,
the necessity of our wrestling for the blessing this morning,
that so we might be numbered amongst the princes of Israel, and like him prevail, etc.,
with some further addition, I sat down.
The meeting then settled down in quietness, and remained long under a solemn feeling;
when I had again to stand up and declare the
blessedness of those who trust in Mount Zion,
the city which the Lord hath founded, which can never be moved;
whose children are joyful in their King; because poor in spirit,
to whom the gospel was preached, and is still preached:
these are filled with good things; but the rich and the full are sent empty away.
It is the poor of the Lord`'s people--the poor in spirit,
whose provision will ever be abundantly blessed.
Yea, they shall be satisfied,--and no wonder,
when made to partake of that bread which cometh down from
heaven,--whosoever eateth thereof shall live for ever;
for this soul-sustaining bread is Christ, who said, "`I am the bread of life:
he that cometh to me shall never hunger,
and he that believeth on me shall never thirst.`"
There is nothing in this perishing world to be desired,
or worth hungering or thirsting after,
by those who have tasted of this true and living bread that cometh down from heaven.
Who would not desire to be a citizen of that city which hath foundations,
whose maker and builder the Lord is?--this Sion,
which he hath founded for the poor of his people.
There is no other way to accomplish this, but that of doing the will of God,
and not our own, through Christ Jesus, by the help of his Holy Spirit in our hearts, etc.
I was largely opened to declare many great and heavenly
truths to these people for about an hour,
under a weighty feeling of a power to myself irresistible;
all seemed brought down and laid low under its dominion,
and the pillars of my frail tabernacle were shaken.
I had to rise a third time to say, that if words would avail any thing,
I was willing to spend and be spent amongst them;
for I had been poured out as water for their sake,
etc.--turning their attention to the Word nigh in the heart and in the mouth,
of which the apostle spoke;--commending them to God, and to the word of his grace, etc.
Returned on board after the meeting.
In the afternoon read portions of Scripture to our own crew,
who had been on shore to the meeting in the morning.

14th.--Yesterday afternoon, Charles being too feeble to go on shore for exercise,
I took with me a native boy, and went on shore.
This boy was born at the Paumotu Islands,
and had been very useful to us for several weeks,
and ready on all occasions to plunge into the sea,
or to bring down the cocoa-nut from its lofty tree;
and never more delighted than when permitted to accompany us on excursions for exercise,
or to search for shells among the coral reefs.

Eighth Month 27th.--For several days past but little
has transpired to vary the customary routine of duties.
As regards myself,
I have not been able to discern any particular line of service called for at my hands;
and hope to be preserved watching and waiting as at the posts of wisdom`'s gate.
Vain, indeed, would be an attempt to move forward, while the cloud thus, as it were,
rests upon the tabernacle.
In the afternoon went to Taunoa to visit the American captain,
who is not expecting to survive many days.
Here is an affecting and mournful instance of the great
business of life being neglected or little thought of,
until brought upon the bed of death.
The Olivia, of which vessel he is part owner, sailed yesterday,
and I thought he would now have nothing left relating to worldly matters to harass him,
which induced me to make the present visit.
I humbly trust, yea, I pray,
that this poor dear man may yet so bow in humble
resignation to the name and power of Jesus,
and from heart-felt conviction confess that He is Lord, to the glory of God the Father,
as to obtain the salvation of his own soul.
For, though he is now bowing, under heavy judgment, to this power, great is my desire,
that he may yet bow to it under a sense of the Lord`'s everlasting mercy, and forgiveness;
for mercy still covers the judgment seat, even to a hair`'s breadth:
with God all things are possible to them that believe.

Ninth Month 10th.--I told the captain yesterday evening,
that I did not see any thing to prevent our sailing this morning for Eimeo.
At an early hour the pilot came on board, when the vessel was unmoored;
and there being a light breeze off the land, the last anchor was weighed.
We were towed out of the bay by a boat kindly sent by Captain Davies,
of the ship Balance of Bristol, Rhode Island.
Just as the anchor was weighed,
a man came from the shore with a packet containing letters, the Yearly Meeting`'s Epistle,
etc., from England, which had been brought by an English whaler,
to the Marquesas Islands, from which George Pritchard had arrived in the night.
We could not but admire how exactly we had been cared for,
in being permitted to receive accounts from our beloved family at Petersburg,
contained in four letters; which, though old dated, were truly acceptable,
with letters also from some of our dear friends.
Having discharged the pilot, cleared the reefs,
and begun to stretch away from the island,
the delightful employment of reading our letters commenced.
While sitting on deck, the vessel made a formidable pitch,
which occasioned a loud and sudden crash, as in a moment.
It was soon ascertained that our mizen-mast was gone by the board,
and had fallen over the very centre of the stern.
Not only the man at the helm escaped unhurt, but every other person on board;
and nothing short of an Almighty, all-merciful,
and all superintending Providence could possibly
have screened and sheltered us from every harm.
My Charles had been sitting for some time quite near the mast,
but had removed just before from the place of danger.
Our captain immediately represented the vessel as so crippled, that she would not stay,
or tack, and wished to know whether I thought of proceeding,
or of endeavouring to return to the bay of Papeete, which we had just left.
I paused for a moment, and then signified that we might safely proceed,
although at the time it was nearly calm, and a heavy tumbling sea heaving around us.
In a few minutes, however, the regular trade-wind sprung up,
with a fresh gale in our favour,
which in a few hours drove us to the desired haven of Talloo;
into which the Henry Freeling worked as well as could be desired,
notwithstanding she had lost one of her wings;
but it became dark before she reached the proper anchorage.
The wreck of the mast, rigging, sails, etc., were all cleared away, and got on board,
before the strength of the trade-wind set upon us,
and before the sea had time to rise under it,
which soon afterwards became unusually heavy.
The great superiority of a small vessel over a large one was fairly proved today,
as we were beating through a channel beset with coral reefs, in a masterly manner,
our pilot frequently cried out '`Maitai,
Maitai!`' '`good,`' '`good!`' to denote his approbation; and would occasionally say,
in tolerable English, '`She works well.`' He told us,
that one of the American ships now here, beat about for five days in the same place,
and was towed in at last by six boats, when the wind died away.
We just looked into the harbour, as we passed, where Cook had formerly anchored,
but it is more exposed to the heavy seas,
which some particular winds occasion at times on the coast.

11th.--Talloo Harbour, Island of Moorea,
or Eimeo.--This morning sent on board the American ships,
for assistance to repair the damage recently sustained in the loss of our mast.
We were soon visited by the captains of those two vessels,
who brought their carpenters along with them.
It appeared that the dry rot, even with the deck, had been the cause of the accident.
On examination, it was concluded best to make the same mast do again,
which could be accomplished by making a tongue below the deck,
and securing it with strong iron bands,
which would only reduce its original height five feet.
Though this reduction will not improve the look of the vessel, in other respects,
it may be considered a decided advantage.
In the afternoon we landed,
and for the first time visited the school,--the residence of Alexander Simpson, his wife,
and their little daughter.
The children, about twenty-two in number,
were at play upon the grass-plots in front of the house,
which gave the place quite an air of English comfort:^
footnote:[This is an establishment for the children of missionaries.]
this ground is fenced in with strong stone walls.
We did not purpose stopping long, not being acquainted with the safest landing places,
nor sufficiently so with the road from Alexander Simpson`'s,
to find our way back to the boat in the dark.

In one of our letters recently arrived from England,
was found a copy of a short account drawn up at Shoosharry in Russia,
by my beloved children, of that illness which deprived them of their sainted mother,
intended to have a place in the Annual Monitor for 1835.^
footnote:[See Appendix C.]
The perusal of this document brought afresh to my
recollection the days of distress and affliction,
which my endeared family had to pass through in the loss of their precious parent,
when already almost fatherless, from my having previously left home,
to pursue the path of apprehended duty in the South Seas: a wound so deep,
and but slightly healed, that it can never be forgotten when touched.
But, I believe, that bitterness and anguish of soul is not offensive,
when not accompanied with repining at the will and
pleasure of my gracious and compassionate Lord;
who when passing through the straits and difficulties of humanity,
wept in love divine at the tomb of Lazarus.
His compassions fail not;
neither is the greatness of His faithfulness to
a poor frail mortal one particle diminished;
who, in the depth of affliction and anguish,
still endeavours to breathe in humble resignation and sincerity,
the language of "`thy will be done.`"

12th.--This morning the natives began to visit our vessel, but only few in number.
One man brought a hog, but seemed rather shy at first:
taking but little notice of him soon brought him to reasonable terms.
Having been paid for the hog, he went away; but he soon returned with bananas, guavas,
ninitas, etc., in ample quantity, demanding for the whole, forty small sized clasp nails,
which were given him with a little addition.
When the heat of the sun lessened,
we went on shore and drank tea at the school with all the children.
When about to return on board,
Alexander Simpson asked me if I would favour them with a few words tomorrow;
meaning the sailors that might come on shore, the few white residents,
and the school family.
I said that I thought of being at the native meeting at nine o`'clock,
to which there was no objection; but he still urged my speaking to the English,
after the native meeting was over.
I told him I could not answer for that, even if there, as I had nothing, and was nothing;
I said I intended to come in time for the native congregation, and then asked,
if he would interpret for me, to which he at once assented.
Thus my way is open and provided for upon this island,
if it please my heavenly Father to qualify me for the work, and open my lips;
that in the ability which He alone giveth, I may show forth His praise,
and cause the thanksgiving of many to redound to His glory:
for truly without Him we can do nothing as it should be done.

13th. (First-day.)--Although we landed apparently in ample time,
we found Alexander Simpson`'s house shut up, and the family gone to meeting;
and when we reached the place of worship, the singing had already commenced.
We remained at the door until this was finished, then went in and sat down on a form.
When the Tahitian exercises were all gone through,
Alexander Simpson began reading my certificates; when these were finished,
I went and stood by his side, to be ready; and when all was gathered into stillness,
alluding to what they had heard read,
I said,--they were now aware that I had left all that was near and dear to me on earth,
to visit them; that I had sailed over the trackless ocean,
during many moons for this purpose,
in order that I might be found standing in the counsel of that most holy will,
which is ever excellent; and that the desire of my heart was,
that the gospel might not be to them an empty sound,
or a mere outward declaration of good things, but that they might believe, repent,
and obey it; and that it might be to them indeed "`the power of God unto salvation.`"
As I proceeded,
I was strengthened as by "`the mighty God of Jacob,`"
by the extension of that love which enlargeth the heart,
to declare to the people the unsearchable riches of Christ,
and the necessity of their coming to the knowledge of Him in whom they believed,
by the Holy Spirit: that nothing short of their being born again,
not of corruptible seed, but of incorruptible, by this Word of God,
which liveth and abideth for ever, could make them members of His church,
which is without spot, or wrinkle, or any such thing.
That, unless they came to hear the voice of the true Shepherd,
and know it for themselves, they could never be His sheep, nor be known of Him.
"`My sheep hear my voice,`" said Christ:--"`I know them, and they follow me;
and I give unto them eternal life; and they shall never perish,
neither shall any man pluck them out of my hand.
My Father, which gave them me, is greater than all;
and no man is able to pluck them out of my Father`'s hand;`"--turning
their attention more and more to the Holy Spirit of the Lord Jesus,
that great shepherd of the sheep, whose light shineth in every heart;
that so they might come to sit under His teaching,
and know the voice of the only true teacher of His people, who speaketh in righteousness,
and is mighty to save His people from their sins,
but never in them;--appealing to the islanders,
if they had not heard his voice in their own hearts,
reproving them when they had committed evil, etc.
That they must be willing to hear it and obey it,
and to bear the indignation of it for sin and for transgression;
until their cause was pleaded, and judgment executed,
and themselves brought forth to the light,
the light of Christ Jesus,--"`the true light which lighteth
every man that cometh into the world,`" in the secret of the
heart;--the Holy Spirit of Him that speaketh in righteousness,
mighty to save:
that they might know Him experimentally to be the "`Lamb of God that
taketh away the sin of the world,`" from having witnessed their sins
and transgressions to be washed white in his blood,
and remembered no more, etc. etc.

The people were very attentive in the general; and although the house is large,
and was more filled than usual by natives from distant parts of the island,
and others from Tahiti,
I felt as if I could penetrate its most distant crevices with comparative ease.^
footnote:[It is an octagonal stone building, with lofts running entirely round it.]
There might be twelve hundred persons present.
A boat was waiting to convey us on board;
but after having passed through the ceremony of shaking hands with a wholesale number,
on retiring to the school, I did not feel altogether clear of the people;
so concluded to send off the boat, and remained on shore to attend the afternoon meeting.

The meeting gathered again at three o`'clock, and was well attended,
though somewhat smaller than in the morning.
An opportunity was afforded at this meeting for us to
witness the ceremony of baptizing a new convert,
who had applied for admittance into the church as a member.
A child was also baptized, the offspring, it was said, of one believing parent,
the mother being then present.
When the proper moment seemed come, I placed myself by the side of Alexander Simpson;
and when all was quiet, I began to inform the people,
that a fear of not being clear of the blood of my
fellow creatures had induced me again to stand before them;
but it was in that love,
which would gather all mankind into the heavenly garner of rest and peace;
testifying the endless duration of the Lord`'s mercy,
and the unbounded extension of his love to all,
by sending his only begotten Son into the world,
that "`whosoever believeth in him should not perish, but have eternal life.`"
My mouth was again opened to declare largely amongst the people the truths of the gospel,
and in a pressing manner to urge the necessity of the hearts
of the parents being more and more turned to their children,
in order to bring them up in the fear of the Lord;
or else all the privileges and advantages which they had witnessed to
result from the attempts to introduce Christianity amongst them,
would in all probability be totally lost to their children,
when their own heads were laid low.
Without this care, things would soon be as bad as they had been formerly,
when there was no place of safety nor of security upon the island;
when every man`'s hand was against his brother, and the way of peace unknown.
I had much to say to them of an arousing, encouraging, and warning nature and tendency,
with the same undiminished strength as had been
vouchsafed me in the morning,--to the comfort,
peace, and relief of my own mind, and I trust, with humble thankfulness,
to my Maker`'s praise.
