== Chapter XXIV.

[.chapter-synopsis]
* Eimeo
* Meetings with the Natives
* A Marai
* Return to the Henry Freeling
* Native Meeting and with the Mission Families
* Sail For Huahine
* Prohibition of Spirits There
* Social Meeting of the Authorities
* Distribution of Tracts
* Sail for Raiatea

Talloo Harbour, Island of Eimeo, Ninth Month 18th,
1835.--Called upon Alexander Simpson to consult
about going to the other side of the island,
to Afareaitu, of late called Griffin`'s Town; but as he had a serious sore throat,
it was not prudent for him to undertake the journey on the following day.
I now perceived,
that if I had not given up to attend the afternoon meeting at Papetoai last First day,
when it opened upon my mind,
that I must have waited a week longer for want of an interpreter,
on account of Alexander Simpson`'s present indisposition.
Truly it may be said, that the present moment is all we have to trust to, or depend upon;
the future may, to us, never come; and time, once past, can never be recalled.
Then may we be diligently seeking to improve the present,
with thankfulness for being strengthened to yield obedience to every pointing of duty.

19th.--Finding my attention turned to the children at the school,
it seemed that tomorrow at eleven o`'clock in the forenoon,
would be a suitable time to propose for our meeting together,
if no difficulty should appear.
I accordingly mentioned to Alexander Simpson and wife,
that if it would not interfere with any of their arrangements,
I thought of paying a visit to the children tomorrow morning, at eleven o`'clock.
They at once expressed satisfaction with the proposal,
and said it would be very acceptable.
I said, '`Then we will sit down together, and see what will be done for us.`'

20th. (First day.)--Landed in the morning,
so as to have ample time to walk to the school,
and afford an interval sufficiently long to
allow us to cool before going into the meeting,
the weather being extremely hot.
When the time came we assembled, as proposed, the children and the family, at the school.
I fully expected that we should sit down in silence before the Lord:
but when all were seated, it was proposed that the children should read a chapter,
and the first chapter of the epistle to the Romans was read accordingly.
The children were then examined, by questions respecting the moral law,
and the object of our Saviour`'s coming upon earth.
After these were gone through, we were favoured to get into silence.
Having sat for some time, I found my mind getting deeper and deeper under exercise,
until the time came for me to rise, with the words, "`We, through the Spirit,
wait for the hope of righteousness by faith.`"
Sitting in silence may seem a little strange to those unaccustomed to the work;
but it has been the practice of the religious Society
of which I have the privilege of being a member,
from its earliest rise, to wait upon the Lord for the influence of the Holy Spirit;
to be taught by the great Teacher of his people, Christ Jesus,
the minister of the sanctuary and of the true tabernacle,
"`which the Lord pitched and not man.`"
I had to tell them that there is no alteration in the Christian life;
it is a continual warfare, but with the spiritual weapons of burning and fuel of fire,
which, if patiently submitted to,
would purify and prepare us for an incorruptible and never-fading inheritance.
The universality of Divine grace was freely spoken of,
and the necessity of watchfulness and prayer urged with earnestness,
even unto "`praying always, with all prayer and supplication in the Spirit,
and watching thereunto with all perseverance.`"
The dear young people were tenderly invited to
seek after that knowledge which is life eternal:
to "`commune with their own hearts and be still.`"
I wanted them to witness the gospel to be glad tidings of great joy to themselves,
not a mere outward declaration of good things to come,
but "`the power of God unto salvation,`" to every one of them.
None could be insensible to the weight of solemnity which prevailed,
and I had to acknowledge the condescending mercy of that Almighty power,
which was pleased to own the work;
and also to appeal to those present as witnesses to the
circulation of that "`life,`" which is "`the light of men.`"

23rd.--With the exception of taking occasional exercise for the last three days,
have been busily employed in preparing despatches for my beloved friends in England,
information having been received that an English whaler, homeward bound,
had arrived at Tahiti.
On going on shore this evening, we found Alexander Simpson so much recruited,
that it was concluded to set off tomorrow morning for the distant station of Afareaitu.

24tA.--Rose early, and left the vessel at half-past six o`'clock,
in the Henry Freeling`'s long-boat, with a hired crew of natives.
We took in Alexander Simpson opposite the settlement, at seven o`'clock,
and immediately proceeded towards Afareaitu.
Some parts of this passage are hazardous,
owing to immense masses of coral lying near the surface of the water,
upon which boats are not unfrequently stove; but by keeping a good look-out,
we were favoured to pass through the whole of these places, which extend several miles,
without touching with much violence upon any of the rugged cones.
About three p.m., we reached Afareaitu,
and were kindly received and entertained by Thomas Blossom and his wife,
the former originally came out of Yorkshire,
and with some of his connexions I was acquainted in England.
He came out in the Tuscan several years ago with Tyerman and Bennet,
as an artisan belonging to the mission.

25th.--The bell for the sun-rise worship rung early, and when the people were collected,
we went to the meeting.
At a suitable opportunity my certificates were read by Alexander Simpson;
after which I had a full opportunity to clear my mind amongst these people:
and although I had had nearly a sleepless night,
and felt in the morning sunk both in body and mind,
below the usual level of depression in such cases, yet my Lord was to me in truth,
strength in weakness, riches in poverty, and a present helper in the needful time;
and I had largely to declare of his love, of his mercy, and of his Truth;
and to show forth his salvation to the people,
as it is wrought in the heart through faith in the operation of the Holy Spirit.
I had also close things to say amongst them,
and to show them the dreadful consequences of drawing down the Divine wrath,
if their return for his love and mercy was only neglect, disobedience,
and rebellion against his heavenly and righteous invitation,
so largely extended towards them:
and to point out the snare which had been laid by the great enemy,
in the introduction of spirituous liquors amongst them,
and how they had fallen under the temptation, from which, if they had obeyed the gospel,
they would have been preserved.

Notwithstanding a messenger had been sent beforehand to invite the inhabitants of Matea,
a distant village, said to be more populous than Afareaitu,
yet I think it was reported that none had made their appearance at the meeting.
On considering the subject,
I thought that although they would not be at the trouble of coming to me,
I should not fully discharge my duty without going to them.
This circumstance seemed likely to bring upon us the
sacrifice of another night`'s absence from Papetoai,
which is by no means desirable on several accounts;
yet I felt resigned to give up every selfish consideration,
if I should only be found in the path of duty.
It was at last concluded for us to proceed to Matea, about a league along the coast,
but in a direction that our boat`'s crew did not approve,
as they hoped we should have returned to Papetoai by a route several miles shorter,
which may sometimes be taken with safety when the wind and weather are favourable.
We got ready immediately, and set out, taking with us Thomas Blossom and wife,
their little boy, and a daughter of George Bicknell`'s of Taunoa on the island of Tahiti,
about ten years of age; they intending to walk home again in the cool of the evening.

Having reached Matea we landed, and soon met with the principal chief:
some rather shuffling excuses were made on behalf of the people for
not attending the meeting in the morning at Afareaitu;
and upon being asked where the people were then, he first said, in the mountains,
procuring food for the queen of Tahiti, who we knew had arrived at Papetoai:
but when he found there was a disposition in us
to go into the meeting-house and sit down,
there being no seats in the house where we then were, he began to alter his tone.
Whether he thought we intended to wait for the people, or from what other cause,
I am not aware, unless he supposed the falsehood would afterwards be detected,
but he then said, the people were all in their huts,
and he would send round to them to meet us forthwith.
They assembled in as short a time as could be expected, and when well settled,
my certificates were read by Alexander Simpson; who, when he had finished,
and given ample information respecting me to the people, said, turning to me,
'`If you have any thing to say to them, I am ready to interpret.`' I drew towards him,
and just stated that I hoped to have seen them in the morning at Afareaitu:
but although this had not been the case, I was not willing to pass them by.
I then told them, that I had brought nothing with me,
and had neither store-house nor barn,
but that whatever my great Master might be pleased to give me to speak,
I hoped to do it faithfully amongst them.
From this I went on step by step, until my heart was so enlarged, and my tongue loosed,
that I declared the Truth amongst them for the space of an hour.
I have since been comforted in believing, that although many slept at the time,
yet there were many awake, unto whom my message belonged;
and whose countenances bespoke that they were not only awake,
but awakened to a sense (I humbly trust) of their
situation;--that they had a soul to be saved,
and that "`no man can save his brother, or give to God a ransom for his soul.`"
When I sat down, I thought I was clear, but had to rise again in a while, and tell them,
under its contriting influence, that I had felt the love of God since I sat down,
to fill my heart; and that I never knew an instance,
where a message had been sent to any people,
but that the love of God was still extended towards them; adding,
that I was not about to multiply words,
but merely to express a desire that the Lord might direct their hearts into this love,
and into the patient waiting for Christ.

The wind was against us,
and the boat`'s crew very sulky at their disappointment
in not going the shortest way back,
as they wanted,
supposing they should have had less work in rowing if they had taken that course.
Presently the breeze died away,
and I made signs to them that we should soon have a favourable wind,
but one of them said, '`No,`' in an unpleasant tone.
In a short time, the breeze sprung up fair for the boat, when they became more cheerful,
and before we had got many miles farther, they said,
it was well for them to go with these strangers,
for they had brought a fair wind with them.
They then remembered,
that we had a favourable wind the preceding day when going in the opposite direction,
which is regularly calculated upon;
but that we should have it fair again today was much more remarkable,
because directly opposite the point from which the trade-winds almost uniformly blow.
We were favoured to get through the most intricate and
dangerous parts before it became quite dark,
although we several times touched upon the reef:
after landing Alexander Simpson at the settlement, we reached the vessel in safety,
and I believe with thankful hearts,
though from the lateness of the hour and darkness of the night,
our return was not expected until the following morning.

On the passage from Papetoai to Afareaitu,
we landed to examine the remains of the largest Marai (Orua) in the South Seas,
and not so much dilapidated as many of them.
Much of the hewn stone work is yet to be seen;
and the upright stones are still remaining,
placed in a position best adapted to accommodate the backs of the priests when praying,
and from whence they could witness the sacrifices of the wretched human victims.

Ninth Month 27th. (First day.)--This morning awoke early,
and on endeavouring to ascertain what path I should have to move in,
I found that the openings which had yesterday floated before the view of my mind,
were now altogether out of sight;
so concluded that I must remain on board the Henry Freeling.
Just as we were about to assemble together in the forenoon, was seen on the shore:
a boat was immediately dispatched for him,
when it appeared that he was coming on board on purpose to sit with us.
In the course of the time of our being together, my mind was brought under exercise,
and I had a short and encouraging testimony to
bear to the faithfulness of our gracious Lord;
standing up with words to the following effect:--although our company is small,
and in a remote corner of the globe, yet we have the word of a King for it,
even the "`King of saints,`" that "`where two or three are gathered together in his name,
(in His power,) there He is in the midst of them.`"
But it is only such as are gathered under a sense of
this constraining power and with sincerity of desire,
who will be benefited.
"`The race is not to the swift, nor the battle to the strong.`"
"`Not by might, nor by power, but by my Spirit, saith the Lord of Hosts.`"
"`Let not your heart be troubled, neither let it be afraid; ye believe in God,
believe also in me,`"--was the language of the Saviour to his disciples formerly;
and I trust, there are none among us but who believe in God and in his Son Jesus Christ.
Then let us be willing to believe in the Holy Spirit of Christ Jesus.
Let us believe his words--"`It is expedient for you that I go away; for if I go not away,
the Comforter will not come unto you: I will pray the Father,
and He shall give you another Comforter,
that he may abide with you for ever,--even the Spirit of Truth;
He will guide you into all truth.`"
There is nothing like an interest in the Master of the storm;
if we have Him on board with us, though in the hinder part of the ship,
asleep on a pillow, it is enough; for nothing then can harm us.
In an earthly race, although many may run, but one obtaineth the prize,
and that but a corruptible, perishing crown; but in the heavenly race it is not so,
for all may run, and all may win a crown incorruptible,
that will endure,--a prize immortal.
"`Then let us lay aside every weight, and the sin which doth so easily beset us,
and let us run with patience the race that is set before us; looking unto Jesus,
the author and finisher of our faith: who for the joy that was set before Him,
endured the cross, despising the shame,
and is set down at the right hand of the throne of God;`" where he ever liveth to
make intercession for those who are willing to come unto God by him.
Even so run that ye may obtain!
Whilst we continued in silence after I had sat down,
I believed it required of me to attend the native place
of worship at three o`'clock in the afternoon.

Before two o`'clock, Charles and myself landed,
and reached the school just as the children were moving off in train towards the meeting.
The school principally consists of the children and grand-children of the missionaries.
We followed, previously telling Alexander Simpson,
that if I should have any thing to say, when he came down from the pulpit,
I would come and stand by his side.
I found that I had a heavy burden to throw off; but my trust was in the Lord Jehovah,
in whom alone is everlasting strength.
I sat while they were proceeding with the regular service, in much conflict of mind;
but as has often if not always been the case,
casting a thought towards my dear brethren and sisters in England,
as if they were in degree sensible of my situation:
and I cannot help thinking that such is the precious unity in spirit of the faithful,
that petitions are constantly ascending from one or other,
as a lamp that burneth and never goeth out, to the throne of the Majesty on high,
on behalf of a poor weak brother, separated as an outcast,
almost as far from them as the east is from the west.
For, however distant from each other the members of the mystical body may be placed,
nothing can separate them from the love of God, as it is in Christ Jesus,
their crucified, risen, and glorified Lord: and therefore, if one member suffer,
all the members suffer; if one member be honoured,
all the members rejoice in heavenly sympathy and joy,
in which a stranger cannot intermeddle.

When Alexander Simpson came down from the pulpit, I went and stood by him;
and shortly after he had prepared my way, by telling the people to be still,
I said,--"`Verily there is a reward for the righteous:
Verily He is a God that judgeth in the earth.`"--"`Righteousness exalteth a nation,
but sin is a reproach to any people.`"--"`The work of righteousness shall be peace;
and the effect of righteousness, quietness, and assurance for ever.`"
'`I was not aware that my voice would be heard any more among you,
but my Lord and Master hath put it into my heart to stand before you once again.
As what I speak must be in faithfulness before my God, so I must be honest,
and deal plainly with you.
I am come to warn you to flee from the wrath to come;
and to show you a snare which the grand enemy, both to God and to man,
that old serpent the devil, has prepared for you: he has tried it before,
and found it to answer.
It is that of throwing strong drink or spirituous liquors in your way.
You have it in your power to resist the temptation;
for no temptation will be permitted to assail us without a way being made for our escape.
Then "`draw nigh to God, and He will draw nigh to you:
resist the devil and he will flee from you.`"
The scene of riot and confusion has already begun upon the sister island, Tahiti,
and the poison will soon reach to this island: if you do not resist it,
your destruction will be of yourselves.
If those in authority do not know it, they ought to know it;
and if the authorities do know it, and with those under them in power,
are conniving at it or winking at it, or deriving emolument from it,
most assuredly the Lord will punish these: He will visit for these things.
"`Shall I not visit for these things,
shall not my soul be avenged on such a nation as this?`" was the language of
the Lord through his faithful prophet to a rebellious people formerly.
Yea, He will sweep them from the face of the earth as with the besom of destruction.
Nothing is so calculated to destroy the happiness of
the people as this curse of the human race,
and to aggravate that awful disease which is now rapidly depopulating these islands.
If you do not set shoulder to shoulder in resisting this evil,
what will you do when the wrath of the Lord is
appearing? "`He will laugh at your calamity,
and mock when your fear cometh;`" and the denunciation
of the prophet against a people that had revolted,
and forsaken the Lord their God, will be applicable unto you:
"`Hast thou not procured this unto thyself,
in that thou hast forsaken the Lord thy God when he led thee by the way? And now
what hast thou to do in the way of Egypt,`" in following the fashions and follies,
and vanities of this world,
and in drinking the dark and polluted "`waters of Sihor,`" etc.--"`Thine own
wickedness shall correct thee,--thy backslidings shall reprove thee:
know therefore, and see, that it is an evil thing and bitter,
that thou hast forsaken the Lord thy God, and that my fear is not in thee,
saith the Lord of Hosts.`"
Come, then, my beloved people, in the fear, and in the dread, and in the love,
of the Lord Jehovah I warn you,--your only refuge is in Jesus: then turn inward,
to his Holy Spirit in your hearts, to "`Christ in you the hope of glory.`"
Submit yourselves to Him as little children,
and He will leaven all in you into his own pure and heavenly nature,
and prepare you for a kingdom "`consisting not in meats and drinks,
but in righteousness and peace,
and joy in the Holy Ghost,`" a kingdom into which it is
declared that nothing that is unclean or impure,
nothing that worketh an abomination, or that maketh a lie, must ever enter: there,
the wicked cease from troubling, there, the weary are at rest; there,
the morning stars sing together; there, the sons of God shout an endless anthem; there,
all is love and joy, and peace, and that for evermore.`'

Several of the people went out when strong drink was mentioned,
but the queen and her party, with all the principal authorities and judges from Tahiti,
as well as those of this island, were present, and remained to the last.
Alexander Simpson told the people that they must not consider me their enemy,
for it was in pure love that I had spoken to them:
and after he had put up a prayer on the occasion, he dismissed the assembly.
Only one man and one woman ventured to shake hands with me.
I told A. S. that I had placed him in an awkward situation, but the truth must be spoken:
it was not a time to withhold it.
He expressed his satisfaction at what had been done,
and said it was much better for it to come from a stranger.
I certainly did not know that so many of the authorities were present from Tahiti.
I was aware that Pomare V. was in the neighbourhood; but though in the meeting,
I did not see her, or know she was there.
I was afterwards informed, that Paofai, one of the principal chiefs,
was desirous to have spoken to me in the meeting by way of reply,
but was deterred through fear of giving offence.
When the meeting broke up he attempted to get to me,
but could not succeed for the crowd of people.
He told Alexander Simpson, my informant, that he wished,
in reply to my testimony borne in the meeting, to have said,
on behalf of the natives of these islands and himself,
that "`he hoped I would go to Britain, and beg the people to have mercy on them;
and then go to America, and beg the people there also to have mercy on them;
because it was these countries that sent the poison amongst them.`"
A fact not less true than lamentable.

Tenth Month 3rd, 1835.--Nothing suitable for recording, of a religious nature,
has occurred since last First-day.
In the course of the past week our stock of wood and water has been completed,
but it is very difficult to procure a supply of vegetables,
owing to Pomare and her numerous attendants remaining so long upon this island;
and we are told they will not depart until they
have consumed all the food in the neighbourhood.

8th.--From the 4th instant employed chiefly in preparing letters for England.
In the forenoon today, Charles and myself sat down together as usual.
Much oppressed with heat and heaviness in the forepart of our sitting.
Towards the end more lively, and strengthened to maintain the watch,
even unto prayer at times.
Had close conversation with the heads of a family, where we afterwards drank tea.

10th.--My mind for the last two or three days has been
looking towards fixing a time for sailing for Huahine,
but nothing could be clearly discovered.
While on shore yesterday, spent some time at the school.
Today another opportunity with the children and family
at that institution has come much before me,
to take place tomorrow after the native meeting is over in the forenoon.
After closing in with this prospect, the time appeared come for me to tell our captain,
that if the deck of the vessel were all ready,
and the spars secured in the course of the day,
there would be no difficulty in being ready for sea on Second-day;
which he readily admitted, and gave orders accordingly.

11th. (First-day.)--Much rain fell during the night,
but after day-break the clouds began to disperse, and the day became fine as it advanced.
This being the case, I felt liberty to convene the two families aforesaid.
We proceeded to the shore in good time,
expecting to have to wait for the breaking up of the native meeting; but we found,
soon after landing, that the meeting was over, and Alexander Simpson had returned home.
After sitting awhile, I told him, that we expected to leave the island tomorrow,
and queried whether we could not sit down together once more,
to which he readily assented.
We then settled down into comfortable and silent waiting:
at length the time came for me to stand up, though under a sense of much weakness.
After the silence was broken into with a short remark,
I told them there might not be many words, but the desire of my heart was,
that we might be sensible of the power which was before words were,
and would remain when words shall be no more: for words shall cease,
and declarations come to an end; but the "`word of our God shall stand for ever.`"
I had to urge the necessity of seeking to know for ourselves the Divine Will,
and then to do it: that this was the great business of life, etc.
But knowledge only makes our condemnation greater, without obedience keeps pace with it:
and truly this knowledge can never be attained in the
noise and bustle and mixture of this world;
nor while we are living in conformity therewith.
Nor can we expect to be entrusted with such great knowledge as the will of God,
whilst in a carnal,
unrenewed state of mind,--according to the testimony of the apostle to the Romans,
when beseeching his brethren, "`by the mercies of God,
to present their bodies a living sacrifice, holy,
acceptable unto God,`" as "`their reasonable service.`"
"`And be not conformed to this world,`" said he,
"`but be ye transformed by the renewing of your mind,
that ye may prove what is that good, and acceptable, and perfect will of God.`"
I had to declare the blessed state of the inhabitants of Mount Zion,
where every one appeareth before God:
they go from strength to strength.--God is in the midst of her;
she can never be moved:--He is known in her palaces for a refuge.
The stream of gospel love flowed freely and largely to all present,
and great was the solemnity that prevailed over us;
such was the condescending mercy and loving-kindness of
the Lord to his poor unworthy creatures.
We then took leave of the whole, not expecting to visit them again;
and we returned on board to dinner, under feelings of gratitude and thankfulness,
and in peaceful serenity of mind,
not being conscious myself of having any further service to attend to in this island.

12th.--The Henry Freeling being ready for sea, and the pilot coming off at an early hour,
at five o`'clock a.m. began to weigh the anchor,
and at half-past six o`'clock she was safely outside of the reef.
Having discharged the pilot, we bore up and made sail, with a fine fresh trade-wind,
for the island of Huahine.
At four o`'clock, p.m., this island was discovered,
but as some part of the land is very high, and may be seen many miles distant,
it was considered impossible to reach it before dark; on this account,
it was judged most prudent to shorten our canvass,
and haul to the wind in good time under easy sail during the darkness,
with plenty of room to drift until the dawn of the morning.
At day-break we edged away towards the island,
and by keeping a good look-out from the mast-head,
we were favoured to distinguish the outermost point of the projecting reef,
upon which the white foam of the breakers served
as a beacon for us to steer by with safety.
We beat safely through the narrowest part of the channel,
and about eleven o`'clock on the 13th instant we anchored in Fare Harbour,
and moored with a chain-hawser made fast to a cocoa-nut tree upon the shore,
there being thirteen fathoms of water close in with the strand.
Two American ships left this neighbourhood yesterday afternoon,
one of them homeward bound:
a sail had been seen by us the preceding evening before sun-down,
probably the homeward bound vessel.
The Zone, Captain Russel, only remained in the harbour.

Huahine.--Soon after anchoring in Fare Harbour, a well-dressed person came on board,
as a constable,
to prevent petty thefts and depredations being
committed by the natives who came on board;
but we did not consider such a person at all needful:
and having never suffered any material inconvenience of the kind at the other islands,
his attendance was declined; I thought it would look like distrust on our part,
and might have an unpleasant, if not injurious, effect upon the people.
In the afternoon, Charles Barff the missionary, came on board;
he seemed very sociably inclined towards us,
and disposed to render every assistance in his power,
when I might feel inclined to see the people collected.
He translated the queen of Tahiti`'s letter to two of the chiefs of the island of Huahine,
then on board;
who appeared glad at having an opportunity afforded to take off the port charges, saying,
they should be sorry to have been worse thought of than the neighbouring islands.
I told them it was a very trifling affair,
but I thought it would not have been handsome treatment,
if the option of choosing for themselves had not been afforded.
At midnight there were tremendous gusts of wind from the mountains,
with heavy showers of rain.
We were informed,
that a short time ago some of the principal persons who
had given away to the temptation of strong drink,
were the first to come forward to propose that its use should be entirely abolished;
which eventually was unanimously agreed to by the inhabitants.
The reason given for making this proposal, was the conviction,
that it was taking away their lives.
Captain Russel told us that there are no spirits to be found on shore.
One part of his crew go daily for exercise,
and return every evening in an orderly manner,
which would not be the case if drink could be purchased.
How I should rejoice to hear,
that these islands are strengthened to stand firm against
every thing of the kind being landed amongst them;
which might easily be effected,
by supplies being withheld from any vessel attempting to trade with it.
Every Christian government ought to come forward for
the protection of these defenceless islanders,
from every cruel outrage of such vessels as might
attempt to enforce by arms the exchange of supplies,
for rum, muskets and gunpowder.

Tenth Month 18th. (First day.)--Last evening my certificates
in the Polynesian language were handed to Charles Barff,
to read at the native meeting this morning, if nothing should prevent my attendance.
May the Lord be pleased to exalt his ever excellent name,
and magnify his power amongst us, until the blessed Truth shall rise into dominion,
and reign over all, to his glory.
After an anxious, restless night, in which little sleep could be obtained,
we arose early, and went on shore in good time,
to look into the children`'s school before the meeting took place.
All our sailors accompanied us, leaving only the Spanish cook and the captain,
to take care of the Henry Freeling.
The meeting was large; but the building would have accommodated a much larger assembly.
The whole population is said to be, by a census lately taken,
seventeen hundred and sixty persons, including every description;
but I cannot suppose that many more than one thousand were present.
I sat in much conflict of mind: it was a low time with me;
and when my certificates were read, and Charles Barff came down from his pulpit,
there seemed little before me to stand up with;
but after the attention of the people was attracted,
and a general stillness prevailed throughout the assembly,
I expressed a desire that "`grace, mercy and peace might be multiplied,`" etc.,
upon all the inhabitants of this island; and then proceeded to declare,
that for the sake of Christ and his gospel,
I had been induced to leave all that is near and dear to me in this world,
that "`the fulness of its blessing`" might be theirs;--desiring that they might not
rest satisfied with making an empty profession of the religion of Jesus,
but that they might come to the full possession of the Truth as it is in Him;
that so they might be washed, sanctified, and justified by His power, in His name,
and by the Spirit of our God: that Christ might dwell in their hearts by faith;
that they, "`being rooted and grounded in love,
might be able to comprehend with all saints, what is the length, and breadth, and depth,
and height;`" and know for themselves, the "`love of Christ, which passeth knowledge,
and be filled with all the fulness of God;`" and not be
members of an outward and visible church only,
but of the new Jerusalem church--the church triumphant of the first-born:
regenerated and "`born again, not of corruptible seed, but of incorruptible,
by the word of God, which liveth and abideth for ever.`"
I had to point out the inward purity of heart that must be attained,
and is attainable by all, through the precious blood of sprinkling,
which cleanseth from all sin; showing them, as ability was graciously afforded,
the gradual and progressive work and nature of their being turned from darkness to light,
and from the power of Satan to the power of God in their own hearts;
earnestly appealing to them,
if they had not at seasons witnessed the workings of this power,
and the in-shinings of this light, that reproves for sin,
and makes manifest every deed of darkness.
When the meeting broke up, the people flocked round us to shake hands,
with much apparent warmth and sincerity, of which we partook in a large degree.
On parting from Charles Barff, I told him, that if I was there in the afternoon,
I would endeavour to be in time.
We returned on board immediately.
In the afternoon, saw no other way than that of going again to the native meeting,
and went early on shore for that purpose.
Before going into the meeting, I mentioned to Charles Barff,
that if I found any thing on my mind to say to the people,
I intended to come and stand by him, at a suitable time.
During part of the meeting, it seemed as if I should have something to communicate,
but this prospect eventually closed up altogether.
When the meeting was about breaking up,
I suspected that Charles Barff was telling the people to stop,
taking it for granted that I should have something to say, and catching his eye,
I desired that he would not detain them on my account:
he had then to tell them they might retire.
I sat as a fool among them, though with a calm and peaceful mind.
Some smiled; others said, '`poie,`' i.e. '`it is over, there is no more.`' I felt however,
quite satisfied through all,
and I trust that my apparent folly will be a
subject long remembered and wondered at by many,
and lead some to inquire into the cause.

22nd.--Early in the morning received a few lines from Charles Barff,
accompanying a translated copy of a note, with the original, from Mauiui,
our pilot through the reef, as follows:--

'`As I know not the names of you two gentlemen, I address you thus generally.

'`Dear Friends,--All peace to you after diving through the waves all the way to Tahiti.
This is my little word, to which I desire you two to agree.
Compassionate me, and come to my little dinner,
about one or two of the day--a little friendly meeting.
May you two be saved by Jehovah.`'

[.signed-section-signature]
Mauiui

An answer was returned to Charles Barff,
that rather than disappoint the intended kindness of Mauiui,
we purposed accepting the invitation.

It being Fifth day, we sat down together to wait upon the Lord.
As regards myself,
I thought I was sensible of something like a renewal of
strength to struggle against the infirmities of the flesh,
in drawing nigh to the everlasting fountain.
About the time fixed, we repaired to Mauiui`'s house, and found the company assembled,
consisting of the lawful queen of the island and her husband, the young queen Maihara,
(who is to have full possession of the island next week,) and her husband,
brother to the husband of Pomare the queen of Tahiti,
also Mahine the governing chief and his wife,
and the two chiefs next in rank upon the island and their wives,
the king of Raiatea`'s eldest daughter,
and several younger branches of the chief families.
A plentiful supply of provisions was set before us, with a variety of vegetables,
such as yams, plantains, sweet potatoes, bread-fruit, taro, etc.; cocoa-nut milk,
sweetened lime-juice and water, with plain water, were the beverages made use of,
though several flasks of wine were on the table.
The company appeared upon the same level; no distinction of persons was visible:
harmony and good will were the prevalent feelings throughout.
The host and his wife waited upon their guests with much delight and unwearied attention.
It was afterwards ascertained that this female had been
brought up in the family of Charles Barff.

23rd.--The authorities of this island are in the
practice of meeting together occasionally,
and they usually solicit the company of such strangers as may be among them,
taking care to fix the day for collecting, when these can attend.
Several days ago we were informed that such a meeting was in contemplation,
and today being agreed upon for holding it, Charles and myself were invited.
The children were collected in the forenoon at the meeting-house,
and afterwards formed no insignificant part of the guests at the dinner-tables.
We dined out of doors, under the shade of large trees adjoining the queen`'s apartments.
More than one thousand persons were present, including lookers-on,
and the festival altogether was highly interesting.
The company was exhorted by several of the principal speakers,
and the dear children were again and again reminded of the privileges
enjoyed by these islands in their day and generation.
They were told,
that in the days of superstition and idolatry many of them would have been offered
as human sacrifices,--that some of the boys might have been permitted to live,
if their parents were of high rank; but the girls were often sacrificed,
and many of the boys thus preserved would be afterwards killed,
being kept only for the purposes of war.
But now look round, said one of these orators, at the comforts and blessings we enjoy;
and how did they all come,
but by the introduction of Christianity amongst us? It was all the goodness, and mercy,
and love of Jehovah, in sending the gospel among us.
Several of these speakers, on beginning,
addressed themselves to us in terms of welcome and approbation.
One said, alluding to myself,
'`Your address to us last sabbath-day in the chapel astonished us:
I thought you had got the bible in your head.
We are happy to have a teacher come among us, then we have two teachers,
one within and one without.
You told us, that a mere outward profession of religion was nothing;
that it would not benefit us.
The Holy Spirit of the Messiah in the heart is what we must learn to be acquainted with,
and that all the work is within ourselves,`' etc.
He said, '`We have formerly been a very wicked people;
our island has been worse than any other island in these seas.
Captain Cook said so: he found us so; we were the greatest thieves he met with.
Captain Cook shot several of us; and if we had provoked him further,
he would have shot more of us.^
footnote:[It was at this island that Captain Cook caused the ears of several
of the natives to be cut off for committing petty thefts on board the ships,
and in other respects used them very cruelly.]
But your visit to us is not like his; yours is in love to our souls,`' etc.
In this manner the time was occupied for the space of two hours, when a hymn was sung,
and afterwards a short prayer made by one of the chiefs;
when the company dispersed with as much order and quietness,
as the breaking up of a Friends`' meeting in England.
I could have said on the spot,
"`It is good for us to be here;`" for the love
of the blessed Master flowed through my heart,
and softened the creature, as into clay fit for the potter`'s use.

25th. (First day.)--For the last three days, at intervals,
the prospect of attending the native meeting this morning has been heavy and humiliating;
but there seemed no other way of clearing my mind,
and of being at liberty to leave the island, than by standing resigned,
and willing to be any thing or nothing; to go or to stay,
according to the good pleasure of that holy will, in the counsel of which, I trust,
it is my heart`'s desire to be found walking.
Rose early to be in readiness,
but for want of the means of keeping to any fixed time on shore, we found on landing,
that the children were coming away from school,
although half-an-hour before the proper time for the meeting to gather.
We remained outside until Charles Barff and his wife came.
He asked, if I wished to have the order of things any way altered.
I told him, no, but that if I found it needful,
I should come and stand near him at a proper time.
I sat under much exercise until near the conclusion,
when I began to see my way sufficiently clear to encourage me to leave the seat,
and go to the table; which Charles Barff perceiving,
exhorted the people to stillness and attention.
A solemn silence prevailed, until broken by my saying,
"`Blessed are they which have not seen,
and yet have believed`" in the only begotten Son of God;--enlarging on the
love unutterable of our heavenly Father in sending his Son into the world,
that "`whosoever believeth on him, should not perish but have eternal life.`"
I had largely to speak of the dear Redeemer`'s kingdom,
and the necessity of every individual coming to
the saving knowledge of it in his own heart;
for it had been declared by the Saviour himself to be the thing above all others needful,
and the righteousness thereof first to be sought for.
He has also told us where it is to be found: the kingdom of God is within you:
that all things needful should be added to those who obeyed this Divine
command of--"`seek ye first the kingdom of God and his righteousness.`"
I had to set before them the gracious dealings of the Almighty,
and the blessings and privileges by which they are surrounded,
and the return that is called for at their hands.
Before sitting down, I had to speak in a close manner to the heads of families,
respecting the rising generation; that their offspring might be placed in a capacity,
to inherit the privileges and advantages which they themselves enjoy:
being confident that if they, the parents,
were so favoured as to be permitted to enter the kingdom of heaven,
none among them could be found who would not desire to have their dear children
there also:--therefore it was their bounden duty to lay these things to heart, etc.
The meeting concluded in a solemn manner.

Tenth Month 20th.--The queen and her husband, with two of the principal chiefs,
and several others, came to dinner; they remained until near five o`'clock p.m.,
apparently well satisfied with their visit,--although
to ourselves it seemed almost like a day lost;
yet it is needful to bear and have patience with the childish behaviour of these people,
however irksome it may be;
it is more especially trying when much disposition to avarice is displayed.

27th.--Engaged on board until four o`'clock, p.m.; many of the natives constantly with us,
among them several young women and younger children of both sexes.
They seem to enjoy themselves, and I like to see them so comfortable and unsuspecting,
considering themselves quite safe on board.
But I cannot help viewing their confidence with suspicion and fear,
lest the treatment they meet with in our vessel,
should induce them to venture on board of others at a future day,
in the same unsuspecting and unprotected manner.
In the afternoon, took exercise on shore,
and ascended a considerable height up one of the mountains;
Charles Barff having joined us, we accompanied him home to tea.
In the course of the time we were together at his house,
the circumstance of the females coming so freely
on board the Henry Freeling was mentioned,
and the fears that I entertained on their account; but he said,
'`Yours is called the "`Praying ship which is the reason of their venturing
on board as they do.`' However pleasant and satisfactory it is to know the
reason why our decks are so crowded with this description of female visitors,
yet we find to our great regret,
that the practice of others in going off to the shipping is carried
on to a greater extent than their missionary is aware of;
although things in many respects are much better regulated at
Huahine than in other places which we have visited.
What can be expected,
while these poor islanders are exposed to the notorious crews of the shipping,
the vicious practices of whom cannot fail to subvert and banish every virtuous feeling;
they are like a swarm of destructive locusts,
that eat up every green thing wherever they come.

Although I was favoured with an open relieving season
in testimony at the forenoon native meeting,
on First day last,
yet I did not feel myself at liberty to leave the
island without attending one of their meetings,
held on other days of the week.
Although the number of persons who attend on those occasions, from various causes,
is mostly very small; it appeared to me probable, that such as did get to them,
might be considered the most valuable part of the community.
Before leaving Charles Barff, I told him that I did not feel,
as I had a little anticipated would be the case,
at the conclusion of the meeting last First day morning;
and that I believed it best for me to be at the meeting tomorrow afternoon.
Both he and his wife gave me to understand that the company would be very slender;
yet it did not appear right for me to hesitate on that account.

28th.--We repaired to the meeting-house about the time that the people assembled;
and although but few were collected when we got in,
yet the whole number at last was far more considerable
than had been looked for or expected.
I had to revive the holy promise to them "`that feared
the Lord;`" that "`spake often one to another,
and that thought upon his name.`"
"`They shall be mine, saith the Lord of Hosts, in that day when I make up my jewels;
and I will spare them as a man spareth his own son that serveth him.`"
I expressed to the people my belief, that they who attend on all such occasions,
are in general desirous to serve the Lord in their day and generation;
and although the number may be few, I would not have them discouraged.
"`The righteous shall hold on his way;
and he that hath clean hands shall be stronger and stronger.`"
That much depended on their conduct and circumspect walking through life;
as they would be looked up to by others,
and therefore they had the greater need to take heed unto themselves.
On returning to the vessel,
I told Captain Keen that I knew of nothing to
prevent our sailing for Raiatea on Sixth day,
the 30th instant.
The American ship, Commodore Rodgers, arrived today, after a passage of six weeks,
from Oahu, one of the Sandwich Isles; a full ship with spermaceti oil, homeward bound;
she had been out thirty months from New Bedford.

29th.--After dinner Charles Barff came on board: and towards five o`'clock, p.m.,
we went with him to the shore, to take leave of his family,
in the prospect of leaving them tomorrow.
Charles Barff purposes not only accompanying us to Raiatea,
but also to Tahaa and Bolabola: without this provision,
our touching at any of the islands to leeward of
this place would have been wholly in vain,
there being no missionaries residing upon them.
The wife and children of George Platt are now living at Raiatea,
during his absence at the Samoas, or Navigator Islands,
whither he is gone with Samuel Wilson.
The circumstance of Charles Barff going with us,
I cannot but regard as a singular interposition of Divine Providence in our favour;
as it came about without any intervention or contrivance on our part,
but originated entirely with himself,--not a hint having been
given nor a desire expressed that this might be the case:
it is however in full accordance with the many great
and marvellous works which our eyes have seen of Him,
"`who causeth his wind to blow, and the waters flow.`"
A large parcel of religious tracts, and several of the writings of Friends,
were selected this evening for Charles Barff,
to be distributed as opportunities may offer;
as the shipping in general are eager to receive every thing of
the kind while on these long and tedious voyages.
