== Chapter XXV.

[.chapter-synopsis]
* Raiatea
* Native Meeting
* A Place of Human Sacrifice
* Bolabola
* Desolating Effects of Intemperance
* Meeting with the Natives
* Meeting with the Rebel Chief and His Idolatrous Party
* Wretchedness of the Inhabitants
* Distribution of Clothing
* Sail for the Sandwich Islands
* Flint`'s Island
* Oahu

Tenth Month 30th.--At nine o`'clock, a.m.,
Charles Barff having been summoned on board by our making the signal for a pilot,
the Henry Freeling weighed and made sail from Fare Harbour.
When clear of the reef, we '`hove to,`' discharged the pilot, took in our boat,
then bore up, and made all sail for Raiatea.
Soon after one o`'clock, p.m., we passed between the islands,
which form the entrance to the roadstead;
and at two o`'clock anchored in eighteen fathoms water off Uturoa,
the missionary establishment at the settlement on the north side of the island.
Charles Barff went on shore to dinner, in order to announce our arrival,
and be in readiness to attend a meeting which
was to be held in due course that afternoon.
As only a small portion of the people would be there,
it was concluded best for me not to be present,
so that the reading my certificates might not take
place until the whole congregation was assembled,
the day after to-morrow, First day.
Towards evening we landed, and went to the mission-house,
where we were kindly received and entertained by
Judith Platt in the absence of her husband:
she had a son and daughter at home with her,
and her eldest son was expected from Bolabola.
A considerable number of the natives, with Tamatoa the king, or chief of the chiefs,
with some of the governors of the island, soon made their appearance.
All the seats in the room, which was large, were occupied,
and many of the guests were seated on the floor: they came to greet us on our arrival,
and bid us welcome;
at the same time it served as a plausible pretext for some to gratify their curiosity,
and to scrutinize the strangers.
We were, however, gratified ourselves, to find that many of them seemed alive to inquiry,
and apparently desirous to improve.
We have again been favoured to pass in safety from one island to another, and I trust,
I have not left any thing undone that should have been done.
Although desirous to move on,
yet I am anxious not to be found imprudently hastening forward in my own will,
instead of patiently and resignedly abiding the Lord`'s time.
We brought with us from Huahine the son of one of the principal chiefs,
whose mother is now on a visit to this island, attending the death-bed of her father.

31st.--In the course of the day I have been a good deal depressed,
at the prospect before me of the native meeting tomorrow morning;
but my trust is in Him whom I have been favoured to know, in whom I have believed,
and who said, "`Counsel is mine, and sound wisdom: I am understanding, I have strength.`"

Eleventh Month 1st. (First day.)--Although half-past nine o`'
clock was the time fixed for the native meeting to begin,
yet the people were observed moving along by the edge of the seacoast,
in small parties towards the meeting-house, by half-past seven o`'clock in the morning.
On this account we landed earlier than the time agreed upon,
that they might not have to wait long before our arrival,
seeing they could not be blamed for not keeping near to the time appointed,
not possessing the means of ascertaining the hour.
On reaching the place we found the meeting nearly gathered, and Charles Barff at his post.
Perhaps the number collected did not exceed materially one thousand persons.
Charles Barff began at an early period of the meeting to read my certificates.
I had been under a heavy load of exercise during
the time we had been in the meeting-house,
which indeed had been the case from an early hour in the morning:
but now the cloud seemed, as it were, to rise from off the tabernacle,
and my way seemed clear to stand up.

A profound silence reigned;
when my soul saluted all present in the love of
the everlasting gospel in the apostolic language:
"`Now the God of peace, that brought again from the dead our Lord Jesus,
that great Shepherd of the sheep, through the blood of the everlasting covenant,
make you perfect in every good work,`" etc.
A pause now followed, and when the attention of the people was firmly fixed,
I proceeded with--"`Launch out into the deep,
and let down your nets for a draught,`" showing the result of willing obedience to this,
and every other command of our Lord, even though we may, as it were,
have toiled all the night and taken nothing: such had been the case in reality formerly,
as we may conclude from the reply of Simon Peter.
That the blessing Divine might perhaps be witnessed amongst us this morning,
if such a disposition was happily wrought in our hearts, and increase and extend,
as from vessel to vessel, until all were filled.
"`I am the light of the world,`" said Christ;
"`he that followeth me shall not walk in darkness, but shall have the light of life.`"
To this I wish to turn the attention of all mankind,
that Christ may dwell in their hearts by faith, which is in Him:
then indeed would they be effectually turned "`from darkness to light,
and from the power of Satan`" to the power of God;
and witness for themselves the light of the knowledge of the
glorious gospel of Christ so to shine in their hearts,
as to be to them the power of God unto salvation.
This was the most attentive audience that I have yet stood before as a spectacle:
my heart was greatly enlarged, and utterance abundantly given me,
far beyond what I can convey an idea of here;
tending to turn the people more and more to the
teachings of the Holy Spirit of the great,
heavenly, and only true Teacher in their own hearts;
which would tell them all things that ever they did,
and by which they must be converted and born again,
or they could not enter the kingdom of God.
The solemnizing power of Truth with which we were highly favoured,
and of which I trust there were many sensible witnesses, reigned over all:
under the covering of which the meeting broke up, in great quiet and order.

When the people were fairly at liberty,
many of all ages and both sexes crowded round us to shake hands,
in numbers beyond all practicability of ascertaining.
I scarcely remember any previous meeting after which I felt so much heated;
and a long walk, exposed to the scorching rays of a vertical sun nearly at noon-day,
helped not a little to increase this inconvenience.
I told Charles Barff that I preferred remaining on shore,
as I was looking forward to attend the afternoon meeting at three o`'clock.

By keeping in the quiet, I was refreshed and ready when the meeting-time came.
The people assembled early,
and in number far exceeding what usually attend in an afternoon.
I had again to turn them to that holy Word, which liveth and abideth for ever,
by which they must be born again.
This was the hope of David; he waited patiently for it: he said,
he waited for the Lord more than they that watch for the morning.
"`My soul doth wait, and in his word do I hope.`"
After the meeting broke up,
we were spared the ceremony of shaking hands by
a discussion which took place among the people.
As this was in a tongue unknown to me, and no interpreter came forward,
I felt myself at liberty quietly to retire.

It afterwards appeared that a proposition had been made to
provide a '`feeding`' for the strangers on the 5th instant.
Upon inquiry,
I found that it is a voluntary and free-will offering of the people themselves,
and not arising from any constraint or order of the chiefs.
This being ascertained, I feel a willingness to accept the kindness intended to be shown,
at the same time hoping that good may come out of it.
As regards the body of the people at large, this '`feeding,`' as it is termed,
amounts to little more than the great bulk of the
company bringing their vegetable food with them,
and eating it when collected together, by general consent at the same time.
The seamen of the Henry Freeling attended both these meetings in an orderly manner.
Returned on board to tea, under a feeling of poverty and unworthiness.

2nd.--In the morning, engaged on board.
Charles Barff came off, bringing with him John Platt, the eldest son of the missionary;
he had returned late the preceding evening from Bolabola,
to which island he had been with a small native-built schooner,
to bring from thence a part of his father`'s cattle,
many of which are still remaining there.
The mission is entirely withdrawn from Bolabola,
the people having generally given themselves up to intoxication,
converting even their bread-fruit into spirit by distillation.
In the afternoon, went on shore for exercise: met with Charles Barff;
and after going with him to see a patient labouring
under a dreadful attack of the elephantiasis,
went to look at the grave of the late James Loxton,
with whom I became acquainted when in London about two years ago;
he was then a fine young man.
In this comparatively short space of time,
a fourth part of which had been expended on the passage out in the Tuscan,
or thereabouts, he had arrived at this island, commenced his work,
and finished his course: his widow has since become a mother,
and returned to England with her infant charge.

3rd.--Visited the ancient and extensive Marais at the east end of the island,
accounted the most celebrated in the South Seas,
and upon which the sacrifice of human life has been witnessed to a horrible extent.
One of these was styled sacred to the god of wars, another to the god of thieves, etc.
A native not far advanced in years, who accompanied us,
had himself been twice present at an exhibition of these dreadful realities:
many human bones were lying about.
To-morrow afternoon a meeting is appointed to be held on the island of Tahaa,
not many miles distant from Raiatea, and sheltered within the same coral reef.
It being the usual time for holding the native meeting,
and notice having been sent yesterday of our intention to be there,
it is hoped that those islanders will generally attend on the occasion.
Tahaa is under the control of the government of Raiatea.

Tahaa.
4th.--After dinner set out in company with Charles Barff for Tahaa, in a whale-boat,
with a fine breeze of wind.
On landing, we stopped at the chief`'s house, while the people had time to collect.
On repairing to the meeting-house but few had come;
and for some time the prospect was discouraging, particularly to myself,
as I felt much depressed, and in a state of more than usual desertion and barrenness.
As the number of people increased,
their general behaviour indicated them to be strangers to the important
object for which they are in the common practice of assembling;
a circumstance which may be readily conceived and for which allowance should be made,
as they are seldom even visited by missionaries at the present day.
Since the death of James Loxton, and the absence of George Platt on the Samoa mission,
they have even been without a native teacher.
After my certificates were read, I seemed to have little to communicate beyond remarking,
that it would be understood by what they had heard,
I had not come amongst them from any sinister or private motive of my own,
but that I might be found standing in the counsel of the Divine will:
that I sought not theirs but them,--the welfare of the immortal part in them.
That the special object of my coming was to turn their
attention to the power of Divine grace in their own hearts.
That they were not beyond the reach of that eye, which neither slumbereth not sleepeth.
"`He that keepeth Israel shall neither slumber nor sleep;`"
and although they were left without an outward teacher,
yet if they turned to this light of Christ in their own hearts,
in earnestness and sincerity, they would have a Teacher indeed,
that teacheth as never man taught; which could never be taken away or removed; and which,
if sought after and obeyed, would make them the Lord`'s children, "`heirs of God,
and joint heirs with Christ`" in his heavenly Father`'s kingdom.
They would then be members of the Lord`'s church, because the Lord`'s children;
all of whom, it is declared, "`are taught of Him:
in righteousness shall they be established, and great shall be their peace.`"
I had largely to speak to them on the great and momentous work of regeneration,
and the only blessed means by which this can be effected;
that of obedience to the manifestation of the light of Christ,
which shineth in every heart, through his Holy Spirit,
by which we must all be born again.

I had also to speak on the incalculable value of the Holy Scriptures:
that "`all Scripture is given by inspiration of God; and is profitable for doctrine,
for reproof, for correction, for instruction in righteousness,`" etc.;
and they refer to the Saviour of the world from the earliest ages of time,
as the "`seed of the woman, that shall bruise the serpent`'s head.`"
They show forth the gracious dealings of the Almighty, and testify his love to man,
and are replete with heavenly precepts, examples, and parables:
still the Holy Spirit that inspired the holy men, who in former ages gave them forth,
is greater than the Scriptures.
They are a blessed book, the book of books, setting forth the revealed will of God;
but they point to the Holy Spirit,
that takes of the things of Christ and shews them unto us.
And truly there is nothing that can manifest and
prove to the transformed and renewed mind,
what is that good and acceptable and perfect will of God,
but the power of the Spirit of the Lord Jesus, which "`declareth unto man his thought.`"
It is not every one that saith, "`Lord, Lord,
that shall enter into the kingdom of heaven,`" said Christ,
"`but they that do the will of my Father which
is in heaven;`" and the will of the Father is,
that we should believe in, hear, and obey the Son.
"`This is my beloved Son, in whom I am well pleased, hear ye him.`"
The meeting at first seemed as if it would be unsettled,
but it sunk down into quietness as I proceeded; and before it closed,
was eminently owned by the Divine Master.
I think I never observed more attention and interest exhibited;
and the countenances of many bespoke the solidity of their minds.
After noticing several of the people, we proceeded towards our boat,
which the natives had tolerably well loaded with food.
After taking a final leave, we were favoured to reach Raiatea before dark,
and drank tea at the mission-house.

5th.--This morning our decks were crowded with the Raiateans,
who began to bring on board an abundant supply of pumpkins, pine-apples, fowls, etc.,
for which they bartered at a low rate.
At noon, went on shore to partake of the feeding at Tamatoa`'s new house,
which was opened, for the first time, on the occasion of this public dinner.
The building, although extremely large, was well filled;
and the whole affair was conducted throughout in an orderly manner.
Many able speakers among the people enlarged in an
impressive manner upon the privileges they now enjoy;
contrasting their present state,
however much below the Christian standard of morality and virtue,
with the state they were once in, when heathenism reigned unmolested,
and every man did what was right in his own eyes.
When these had apparently finished,
I told Charles Barff that I wished to speak to the people at a suitable time;
this he communicated to them, and a general silence soon prevailed:
my mouth was opened freely to declare the day of the Lord amongst them,
to the great relief of my own mind;
standing up with,--"`behold how good and how pleasant
it is for brethren to dwell together in unity!`" etc.,
declaring the blessedness of those that believe the gospel, that repent and obey it.
Such find it not to be a mere outward declaration of good things to come;
but the power of God unto salvation, from sin here,
and to their everlasting comfort hereafter: it proved a solemn opportunity.
May it long be remembered, to the Lord`'s glory and praise,
by the humble thanksgiving of many.
Under a peaceful feeling took leave of the people and the chiefs,
and returned forthwith to the vessel.

Found a canoe from Tahaa, with the native school teacher and family,
who paid us a short visit, and to whom some trifling presents were made.
The natives on shore perceiving our return on board,
came off with every kind of supply in their power to offer,
and kept us very busily employed until it was time again to go
on shore to pay a farewell visit to Judith Platt and family,
whose uniform kindness could not well be exceeded.
At eight o`'clock p.m. we took leave, and on reaching the Henry Freeling,
prepared for sailing in the morning, if nothing arose to prevent.
The natives were on board at an early hour of the morning on the 6th;
and I felt desirous to accommodate them by taking their different
articles that were at all likely to be of use to the ship.
As soon as the signal was made for sailing, Charles Barff came on board,
when all our payments were nicely arranged with the bartering parties;
and having taken in the pilot, the anchor was weighed,
and we proceeded from Uturoa towards the western passage through the reef.
For several hours we were baffled between the two islands of Raiatea and Tahaa,
the wind often light, and shifting from side to side every few minutes.
At length a fresh breeze sprung up,
and after making a few tacks we got clear of every shoal, and into the open passage;
discharged the pilot, and made sail to the westward,
with a fine trade-wind for the island of Bolabola,
at half-past one o`'clock a.m. Soon after five o`'clock we
entered a fine opening in the reef which encircles this island,
and worked up into a beautiful and well-sheltered haven,
sufficiently extensive to contain a great part of the British navy.
Anchored in fourteen fathoms water,
opposite the once flourishing missionary settlement at Vaitape,
in latitude 16° 27`' south, 152° 8`' west longitude.

Bolabola, Eleventh Month 6th.--It was ascertained,
after anchoring in the haven of Teavanui,
that there is a pilot for the accommodation of such ships as may incline to enter;
but as it seldom happens that this place is visited at the present day,
he was engaged in fishing on the other side of the island when we arrived.
One of the principal chiefs and many of the people have
relapsed into their former idolatrous practices;
and the intoxicated state of the people has latterly deterred ships from calling here,
not only from a fear of receiving damage,
but on account of the few supplies to be obtained.
Such vessels as do come are mostly American,
and they generally '`stand off and on,`' at a distance, to dispose of rum,
in exchange for what the islanders can furnish.
There is, however, at present but little to be had,
as the thoughtless part of the community (and these unhappily are in power)
have converted even their bread-fruit into ardent spirits by distillation,
and many families are now in an unclothed and famishing condition.
Charles Barff has no doubt but they will be kindly disposed towards us;
and I do not feel the least hesitation in coming amongst them.

We found here John Platt, son of the missionary family at Raiatea,
who has brought over a small cargo of plantains, as food for the people.
In the schooner with this young man, our kind friend and interpreter, Charles Barff,
looks forward to return to his family at Huahine, after doing all he can for us:
he is now on shore endeavouring to collect the scattered people at the meeting to-morrow.
There is a little remnant of serious natives yet remaining,
who have hitherto stood firmly against the practices of those in authority;
and several of them are nearly allied to the notorious chief whose name is Mai,
to which the letter O is often prefixed:
this little band there will be no difficulty in convening.
We could not have arrived here at a more favourable moment,
as the stock of spirits is exhausted,
and the growing crops are not yet ready for the process of distillation.
May the Lord work amongst them, to the exaltation of his own great and adorable name:
may now be the accepted time,--may now be the day of salvation
to these poor people,--saith all that is within me!
In the afternoon landed with Charles Barff for exercise.
Saw the relics of several Marais, where human sacrifices were formerly offered:
continued our walk until a bay opened on the other side of the island.
Passed by one of the dancing-houses,
which has been established since the introduction of strong drink amongst them.
A message was despatched in the course of the day to the head of the rebellious party,
who has been their leader into every mischief
and distress that has overtaken them of late;
to invite him and his company to attend the meeting to-morrow.
These people have now taken up a position in a distant valley,
for the purpose of carrying on their abominable practices more free from restraint:
the invitation was stated to be at the request of two
strangers just arrived from the island of Kaiatea.
They returned for answer that they could not come to-morrow,
but would certainly attend on the following day.
By this it was understood that they are in such a reduced, impoverished,
and suffering state, from their evil habits and ruinous practices,
as to be for the most part without clothing,
and their resources exhausted by purchasing rum and other strong drink.

8th. (First day.)--From appearances upon the shore this morning,
considerable hopes were entertained that the
people in the neighbourhood of the settlement,
would generally collect to attend the meeting.
By nine o`'clock went on shore, and on reaching the meeting-house,
(a large and commodious building,) we found that the children were in school,
and singing a hymn before separating.
When they had finished, we went into the meeting-house,
where about five hundred of the natives were soon assembled,
but none of the rebel party were there.

When Charles Barff had finished and come down from the pulpit into the reading-desk,
I took a station at his left hand.
The house being very large, and the people seated in a straggling manner,
I suggested their drawing nearer together and to us;
which was immediately complied with in a very rough and disorderly manner: and,
as they continued unsettled, and talking pretty loud, I said a few words,
which produced a general silence.
My certificates having been read,
after a pause it was with mo to say:--Let us humble ourselves under the
mighty hand of God this morning,--let us prostrate our minds before Him,
as a people conscious that to us belongs only blushing and confusion of face:
peradventure He may condescend to lift up the light of His countenance upon us,
and bless us together; for "`God is love.`"
"`As an eagle stirreth up her nest, fluttereth over her young,
spreadeth abroad her wings, taketh them,
beareth them on her wings,`" so the Lord is with his people.
I told them, that I had passed over many miles of trackless ocean to visit them;
that I had come among them in the fear and in the love of God:
in that love which embraces all,
and would gather every son and daughter of the human
race into the heavenly garner of rest and peace:
that this love constraineth us, "`because we thus judge that if one died for all,
then were all dead; and that He died for all,
that they which live might not henceforth live unto themselves, but unto Him,
who died for them, and rose again.`"
The burden which rested upon me was to turn them from darkness
unto the Holy Spirit of Christ Jesus in themselves,
to "`that light which lighteth every man that cometh into the world;`" the
same that the apostle John so fully mentions in his first chapter.
That this light would show them where they are,
and make manifest the state of their hearts, setting their sins in order before them;
that so they might repent of them, and forsake them.
That nothing short of "`repentance toward God,
and faith toward our Lord Jesus Christ,`" will be availing.
That this light is Christ: and if they believe in it, and have faith in its power,
they should not walk in darkness, but should have the light of life,
according to His word; "`I am the light of the world,`" said He;
"`he that followeth me shall not walk in darkness, but shall Lave the light of life.`"
Have you not heard the voice of the Holy Spirit
in the secret of your hearts? I know you have!
I am sure you have!
Which of you that has come to years capable of
reflecting upon your past and present life,
can say that you have not heard this in-speaking voice, striving with you,
and reproving you, when about to commit sin,
and for sin committed,--reminding of sin after sin,
committed perhaps many years ago? This light not only discovereth unto man his sins,
but as he turneth to it, and followeth it in obedience and heartfelt repentance,
his sins are remembered no more against him; they are taken away and forgiven,
and though once of the darkest hue, are now made white in the blood of "`the Lamb of God,
that taketh away the sin of the world.`"
And those who thus turn to hear and obey the voice of the Son of God in spirit,
although dead in sins and trespasses, yet shall they live,
and have a Teacher that cannot be set aside, or be removed into a corner;
but their eyes shall see their teacher, and their ears shall hear a voice behind them,
when about to turn to the right hand or to the left, saying in effect, "`this is the way,
walk ye in it such shall no longer walk in darkness, but shall have the light of life, etc.
Although poor and low enough before standing up, yet now my tongue was loosed,
and my heart expanded in that love and strength,
which alone clotheth with authority to set the truth over all,
and cause even the earthly tabernacle to rejoice
in the midst of the tribulations of the gospel;
because its consolations are known and felt to abound,
and create renewed sensations of gratitude and praise, to the glory of God the Father.
It was a blessed meeting.
When it broke up,
the people crowded round about us in their usual way to greet the strangers.
When going to the afternoon meeting, I told Charles Barff, from present feeling,
that I believed I should have nothing to say to the people; and so it proved,
for I sat as a sign amongst them;
but peace and resignation to the Divine will were my dwelling-place.
Our captain and seamen attended both these meetings.

Eleventh Month 9th.--A messenger was dispatched early this morning to ascertain
whether the rebel chief and his party were likely to keep their word and come to us;
as I had concluded, if they failed in fulfilling their promise,
to visit them in their own valley.
The messenger however reported, on returning,
that the chief would come to us in the forenoon.
By ten o`'clock a.m., information was received that he was near at hand; when we,
accompanied by Charles Barff, landed to meet the party.
They soon arrived, and knowing that the chief had objected to go into the meeting-house,
this was not urged;
but we took up our station immediately under the shade of an immense tree,
under the wide-spreading branches of which,
several hundred persons could be sheltered from the scorching heat of the sun.
The chief, at the head of a large banditti of females, first made his appearance;
and on coming near to us, said, '`You are come at a good time,
and I hope that one or both of you will remain with us and be
our teachers.`' I told him we were not at our own disposal;
that we must go wherever it is the will of the Lord,
and that I believed we had many places to go to beside that island:
we then shook hands with him and all his followers.
The females were decorated in the true ancient heathen style,
with garlands of flowers upon their heads,
and were persons employed to perform for their chief`'s amusement,
those disgraceful and abominable dances practised in these
islands before the introduction of the missionaries.
A body of men then followed,
each of them throwing one or more cocoa-nuts at our feet as they came up;
and those couples which had them suspended from a pole,
threw them upon the ground in a ludicrous manner, which kept the whole assembly,
and the rabble that attended on the occasion, in constant laughter and confusion.

Upon the chief beginning to ask some questions about us,
I proposed that my certificates should be read, which Charles Barff at once assented to,
when silence was immediately proclaimed.
Before the reading was finished, these wild,
thoughtless people were measureably changed into an attentive audience.
When the reading was finished, all remained silent; and after a pause,
I exhorted them to let the Lord God be their fear,
and let him be their dread.--"`He is not far from every one of us,`" said I;
"`for in him we live, and move, and have our being:`" adding,
that I had hoped to see their faces yesterday
with the rest of the inhabitants of the island,
who gave me their company; but as this was not the case,
it was my intention to-day to have visited them where they dwelt,
as I could not think of leaving the island without seeing them; for the Lord God,
whom I serve, is a God of love and of mercy, and willeth not the death of a sinner,
but rather that all should repent, return, and live.
For this he sent His only begotten Son into the world,
"`that whosoever believeth on Him should not perish, but have everlasting life.`"
It is a fearful thing to fall into the hands of the living God;
for if the righteous scarcely be saved, where shall the sinner and the ungodly appear.
That for the sake of Christ and his gospel, I was come amongst them;
for His inheritance is still the heathen,
and the uttermost parts of the earth His possession.
That I was a stranger, and knew nothing of the existing differences amongst them,
and desired to know nothing amongst them,
but "`Jesus Christ and him crucified;`" but this I do know,
that you have not obeyed the gospel: "`for if ye live after the flesh, ye shall die;
but if ye through the Spirit do mortify the deeds of the body,
ye shall live.`"--"`Be not deceived; God is not mocked; for whatsoever a man soweth,
that shall he also reap.
For he that soweth to his flesh, shall of the flesh reap corruption;
but he that soweth to the Spirit,
shall of the Spirit reap life everlasting.`"--"`Turn ye, turn ye,
why will you die?`" Your only refuge is in Jesus;
a measure or manifestation of His Holy Spirit is given to every man to profit withal;
this is the light of Christ in your hearts, which if taken heed to,
will place your sins in order before you, in matchless love and mercy,
that you may repent of them, and be saved from them.
But if you continue to disregard this light, and to rebel against it,
it will be your condemnation; and the wrath of God will overtake you.
He will laugh at your calamity, and mock when your fear cometh:
"`the wicked shall be turned into hell, and all the nations that forget God.`"
I warned them, in the fear, and in the dread, and in the love of God,
to flee from the wrath to come,--to repent, believe,
and obey the gospel,--to seek the Lord while he may be found,
to call upon him while he is near.
"`Let the wicked forsake his way, and the unrighteous man his thoughts:
and let him return unto the Lord, and He will have mercy upon him, and to our God,
for He will abundantly pardon.`"
They were warned of the judgments of the Lord that would
overtake them if they continued in their wicked practices,
and entreated to turn unto the Lord;
to acquaint themselves with Him and be at peace,`" etc.
All was chained down and laid low;
their haughty and airy looks were changed into those of
serious thoughtfulness by that Almighty power,
which controlleth the hearts of all men.

When we separated, the chief came to Charles Barff and told him,
that old thoughts had been brought into his mind, and seemed kindly disposed towards us.
We remained on shore while some medicines were prepared and administered to the sick,
and on returning to the vessel, found the chief had got there before us,
with two of his sons-in-law of the solid party, who stayed dinner.
One of the females had the audacity to make her appearance in the cabin at dinner-time;
but Charles Barff knowing the vileness of her character, she was forthwith dismissed.
The visit of this man was far from satisfactory, but it was submitted to,
in the hope that hereafter good might arise out of it.
Our decks were crowded in the afternoon by the natives,
but we were favoured to pass through it without any unpleasant occurrence.
They are a proud, haughty people, that delight in war;
and since the introduction of strong drink amongst them,
and the practice of distillation,
the missionary George Platt deemed it no longer safe to reside upon the island,
and removed with his family to Raiatea, as before-mentioned.
It is affecting to witness the degraded and miserable
appearance they now make for want of clothes, etc.
Fowls, hogs, cocoa-nuts, pine-apples, etc.,
were brought on board by the solid party in tolerable abundance.
Towards evening we went on shore,
and called with Charles Barff to see several of the sick people, of whom there are many,
mostly wasting away by the disease brought amongst them
by the licentious crews of the shipping.

10th.--To-day our deck has again swarmed with the natives,
and although the principal part of our crew with
our captain are engaged on shore procuring water,
(a scarce article here,) yet there was nothing to apprehend from their numbers.
Perhaps the treatment met with in our vessel is such as they never witnessed before,
and we were far from entertaining a thought of danger,
although the average number on board was ten of them to one of us;
but their deportment has hitherto been uniformly gentle and harmless.
They are naturally a ferocious people, and when not at war with their neighbours,
are frequently engaged in broils amongst themselves.
Great is the love I feel for them, as a stream in my heart,
and particularly towards the poor neglected children.
To-morrow morning a meeting is to be held,
to which I have been looking at times since last First day afternoon.
All my springs are in the Lord Most High: when He is pleased to shut,
who can open? Unto whom shall I look,
or whither shall I go? for the words of eternal
life are only with the Lord Jesus--the crucified,
risen, and glorified Saviour.

Eleventh Month 11th.--Attended the meeting held
at the settlement at nine o`'clock this morning;
but the persons present were few in comparison with those at meeting last First day.
I was strengthened to declare amongst them,
that one hour in the Lord`'s presence is better than a thousand
elsewhere:--"`I had rather be a door-keeper in the house of my God,
than to dwell in the tents of wickedness;`" for in His presence only there is life,
and at his right hand are pleasures, durable as the days of heaven.
I felt much for the upright-hearted little remnant amongst them,
who are desirous to serve the Lord in their day and generation.
I wished them to be encouraged to hold on their way,
for in due time they will assuredly reap if they faint not;
although they must expect many temptations and snares
to be laid for them by the great enemy of God and man,
and also by their brother islanders; for those that live godly in Christ Jesus,
ever suffer persecution.
The invitation of the Saviour, given when on earth,
is still extended for us to come unto Him in Spirit:
it is there we must learn of Him.--"`Take my yoke upon you, and learn of me,`" said he,
"`for I am meek and lowly in heart: and ye shall find rest unto your souls.
For my yoke is easy, and my burden is light.`"
We shall be taught how to pray to the holy Father in faith,
believing in the name of the Son; and what we ask, when thus qualified and influenced,
we shall most assuredly receive for Christ`'s sake;
and we shall know from living experience, that peaceful and easy is his yoke,
light the burden, sweet the rest.
The watch tower is the Christian`'s only safe retreat, his only refuge from the enemy.
It is the place where prayer is wont to be made,
appointed in love to man by Him who said, "`What I say unto you I say unto all, watch.
Watch and pray, lest ye enter into temptation.`"
I had much more to express amongst them: it was to my own relief, and peace, and comfort;
and I humbly trust, if none were benefited, that none would be hurt,
for it was the Lord`'s doing, and to Him alone belongs the praise;
man is altogether shut out and excluded.

Busily employed on board until evening,
then landed and explored the neighbourhood for exercise.
In the course of our travel, drank some excellent juice of a cocoa-nut,
taken from a tree in our sight, which with three others,
were planted about twelve years ago by George Bennet.

12th.--This morning our deck again teemed with the natives:
they are so eager to obtain some article or other from us,
that they bring with them for sale the very utensils out of their huts;
useful to themselves, but to us of no value whatever.
The poverty, disease, and wretchedness of many of them is truly affecting,
and although mostly of their own bringing on, yet they are deeply to be felt for.
It being Fifthday, we sat down together in the cabin, as usual;
and although there was much noise upon the deck with these people,
it served to make us sensible of our own weakness,
and to awaken feelings of humility in commiserating the sufferings of others,
in contritedness before the Lord.
It would have afforded great satisfaction to
clothe the poor naked children of this island,
had I possessed the means; but the number is too great for my resources:
it would have been a difficult matter to effect,
without creating jealousy or envy between the two parties.
The children of the most unworthy parents were the most destitute, as might be expected;
and yet more seemed due to the children of those parents who
are struggling to stem the torrent of iniquity and dissipation,
so alarmingly threatening totally to lay waste the
already much decreased and emaciated population.
I was in great hopes that the children of sober parents
would furnish a plausible pretext for being rewarded,
by having learned to read and write;
but this did not prove to be the case with such as came on board the vessel,
except in one instance of a little girl, who came with her father to sell her own fowl;
on trial, it was found she could write very well with a pencil on a slate.
After having fitted her with a child`'s robe,
she brought me the fowl as all she had in her power to make me recompense;
but to her increased delight, I then bought the fowl for a thimble, two or three needles,
and some thread.
Dresses were also fitted upon two other children, the next deserving;
but in order to select more objects suitable for our purpose, Charles Barff was employed,
who readily undertook to procure a list of the
most diligent scholars from a native teacher:
forty-four garments were appropriated in this manner.
In the evening visited the shore for the last time.
Charles Barff being anxious to return to his family at Huahine,
any further stay at this island would have been
useless on my part without our interpreter:
but its suffering inhabitants will not be easily effaced from my memory;
for whose welfare my heart is deeply interested,
and for whom I must long mourn in secret,
not having at any time felt a greater drawing of love for any people,
amongst whom my lot has been cast in this southern hemisphere,
than for those of Bolabola.
As we passed along the skirts of the harbour,
we were followed by groups of the scarcely clad, famishing, dear children,
who from their eagerness to get near enough to us,
might have known that the time of our departure drew nigh:
their pallid though quick and intelligent countenances met us in every direction.
We returned on board at the close of day-light, and made some preparation towards sailing.

13th.--After breakfast, a chapter in the Testament was read, as usual;
and having spent a short interval in retirement together,
Charles Barff and John Platt prepared to leave us.
As soon as the anchor was weighed, our kind friends pushed off for the shore; and,
quitting the well-sheltered haven of Te-ava-nui,
we stretched through the opening of the reef, and once more committed ourselves to Him,
at whose command the vast Pacific rolls.
After getting from under the lee of the island, the weather proved rugged,
and the wind scant: this day two years ago,
we embarked from London to join the Henry Freeling at the Lower Hope,
about seven miles below Gravesend.
Many have been our tossings, and buffetings, and provings, since that time:
but through that loving-kindness which is better than life,
we have been delivered out of them all; and are still left to acknowledge,
in the grateful language of the Psalmist,
that "`the goodness of God endureth continually,`"
and his love and his mercy unceasingly flow,
"`from the river to the ends of the earth.`"

Eleventh Month 14th.--To-day at noon the island of Bolabola seventy six miles distant.
Strong breezes against us, with squalls and heavy showers of rain.
The best hog in our stock was so tired of his situation,
that he sprung overboard and was lost;
there being too much sea running for a boat to attempt to save him.
Towards evening strong squalls, with much thunder, lightning, and heavy rain.
The foot-rope of our jib gave way, but was discovered in time to save the sail.

16th.--Yesterday the roughness of the weather and the harassed state of our people,
(several of them still sea-sick,) compelled us to relinquish
meeting together in our customary manner on First days.
To-day the weather boisterous, and the wind contrary; after dark,
frequent flashes of lightning from east to west.
Birds of two kinds settled on the mast and suffered themselves to be taken,
apparently nearly exhausted with fatigue.
The very unsettled state of the weather, the opposing blast, debility of body,
and poverty of mind, seem to unite in producing fresh trials of our faith and patience;
but I trust it will be seen hereafter that all
things have been working together for good.
Had we known what awaited us,
it is probable we should have still clung to the shelter of Bolabola,
although for want of Charles Barff our situation would have been far from pleasant there.
It is not long ago since an attempt was made by the rebellious party to seize a vessel,
which had put into the harbour for supplies: this, however,
was frustrated by the sober part of the community, who armed themselves,
and came forward in time to prevent its success.
While we were there,
the natives came on board without restriction by forty or fifty at a time:
they were received in full confidence;
our boarding nettings were entirely kept out of sight,
and we felt perfectly safe among them.
Some trifling thefts were committed, not worth noticing,
although a good look-out was kept by our men.
The three chiefs next in authority to the present vicious ruler, Mai,
are all his sons-in-law by marriage, and stand opposed to his shameful conduct;
they are at present the means of preserving the degree
of moral order still existing upon the island:
they have been applied to, to destroy their father-in-law, and rule themselves;
but they say, '`He is our father; we cannot do that: we must bear with him.`'

18th.--Yesterday the strength of the wind abated,
but it remains still contrary with a heavy swell.
At noon our latitude by observation, 12° 54`' south.
To-day the weather fine; but the wind still northerly.
The Magellan clouds about the South Pole are seen every night,
but visibly getting lower and lower.
We hope soon to get in sight again of the North Pole star,
which has for many months been hidden from us.

19th.--The wind still contrary.
Endeavoured to commit my cause to Him who knows the depth of the
motive that induced our steps being directed to the Sandwich Islands.
The protracted adverse winds and humiliating state of mind at present my portion,
could not fail prompting to a strict examination
of the foundation cause of this movement.
I had, previously to finishing our visit to the Georgian and Society Isles,
looked different ways as to the next route to be pursued: Rarotonga, Tongataboo,
and New Holland,
seemed the places in regular course and succession in the nature of things;
but the Sandwich Islands were often before me.
However undesirable to the natural inclination
of flesh and blood in this the evening of my day,
the prospect might be,
of adding several thousand miles to our already lengthened distance from home,
which must be the result of our going thither; yet,
no light or brightness shone upon any other track: and therefore, without hesitating,
as the time of finishing at the southern islands drew nigh,
I took care that the vessel was provided with water, hogs, and vegetables,
to be in readiness to proceed, as the way should open;
and at length left Bolabola with a peaceful mind,
under a belief that to proceed to the Sandwich
Islands was the only safe path for me to pursue,
and therefore we at once shaped a course towards the equator.
This being Fifth day,
it was a great comfort to have the privilege of sitting down to wait upon the Lord,
who knoweth the secret exercises of my mind on the present occasion.
After our sitting was over, I felt relieved; and, I trust,
resigned to the dealings of our heavenly Father.

20th.--Last evening, being in about the latitude of Flint`'s Island,
mentioned in Norte`'s List, a good look-out was kept for it during the night.
This afternoon, just before sun-setting, the appearance of land was announced.
Upon examining the latitude by observation at noon,
and the course of the vessel since made good,
there is no room to doubt that the land in sight is Flint`'s Island,
in latitude 11° 30`' south, and may be considered as accurately laid down.
After dark edged away to give this land a wide berth,
it being uncertain how far its coral crags may extend from the main body of it.
This island bore from us, when last seen, east by north, about ten miles distant;
and appeared in the form of three small islands close together.
It is cause of humble thankfulness that we have not met with it in the dark,
or under circumstances unfavourable and dangerous.
To-day abiding through favour in the low and peaceful valley;
although under more than ordinary circumstances of discouragement,
by reason of the increased swelling of the lower part of my legs and ankles,
from the great and constant heat to which we are subjected,
together with the want of exercise,
which the incessant motion of the vessel almost precludes the possibility of obtaining:
but in my straits and difficulties,
I am endeavouring to "`set the Lord always before me,`" believing He will
not permit me to be greatly moved at what he may be pleased to dispense to a
"`worm and no man,`" as is often my state of feeling and condition.

23rd.--The weather much the same since the 20th instant.
Yesterday very wet and squally, and although the First day of the week,
we were forced to let it pass over without assembling the people.
As regards myself, poor and low; endeavoured to keep my mind staid,
watching unto prayer towards the Lord.
At our evening reading, my understanding was renewedly opened,
to comprehend in a spiritual sense some texts of Scripture which were read,
to my comfort and edification, and I hope to my Maker`'s praise.
To-day fair weather,
which afforded our people an opportunity of drying most of their wet clothes.

26th.--Latitude 9° 44`' south.
Since Second day many changes have taken place;
but we have only altered the latitude about two degrees.
This forenoon we held our little meeting,
and notwithstanding previously to sitting down I felt hemmed
in outwardly and inwardly by discouraging circumstances;
yet as the struggle was maintained,
a gleam of comfort seemed to shine as from the Sun of Righteousness,
which alone can avail and cheer the drooping traveller in the Christian course,
and strengthen him more and more to walk by faith and not by sight;
and less and less to look for support and comfort from the perishing "`things that
are seen`" and only "`temporal;`" whilst the blessed realities which endure,
are "`not seen,`" but are "`eternal.`"

27th--We were favoured this morning, soon after breakfast,
with a sight of Caroline Island, about three leagues under our lee.
Although from the present wind and relative positions both of the vessel and this island,
we could never have touched it;
yet it is comforting and relieving when permitted to
have a distinct view of such lurking neighbours,
as it at once places all risk of running upon them in
the darkness of the night beyond the shadow of a doubt.
Caroline Island,
like many others of those beautiful spots which
stud the capacious bosom of this vast ocean,
is so low that nothing was apparent but the tops
of the trees that grew upon its coral foundation:
it is said to be uninhabited.
This day my sixty-fourth year is completed;
and when I look at the lateness of life`'s hour, and consider my present situation,
contending with winds and waves on this side the globe,
and my hands ready to hang down under a sense of weakness and increasing infirmities,
it is truly appalling.
I feel at times ready to faint at the magnitude
of the prospect still widely spread before me,
and certainly I should have fainted long ago, if I had not believed to see,
and also been permitted to see, to my finite admiration, the mercy, the goodness,
and the faithfulness "`of the Lord in the land of the living.`"
He beareth up my often drooping and helpless head above the strife of the mighty waters:
He sustaineth and upholdeth me by the word of His power, for His great name`'s sake.

29th.--The weather still rough and unsettled.
This is the third First day in succession that we have
been prevented from meeting together in the usual way;
a circumstance that did not occur during the long and
stormy outward-bound passage from England.
In this climate, such is the closeness and heat of the cabin below,
that our toiling sailors soon become drowsy,
which renders almost useless our assembling any where but on the deck,
which the weather of late has not permitted.

Twelfth Month 4th.--Since the 29th nothing to record,
(excepting those mercies which are new every morning,)
besides a series of rough and unsettled weather;
on the 2nd instant a sight of the sun was obtained,
and our true latitude found to be 11° 46`' south,
having drifted about two degrees to the southward,
owing to the prevalence of strong northerly winds,
and the swell of the sea against the vessel.

Yesterday the weather and wind more favourable, which was succeeded by a calm.
It being Fifth-day,
we held our usual meeting in thankfulness for the quiet
opportunity afforded by the more gentle movement of the vessel.
Supported in humble resignation to Divine disposal.
In the afternoon a shark was taken, about seven feet long.

10th.--No material alteration in the weather since the 4th instant,
although some progress has been made.
On First day, the 6th, portions of Scripture were read to the crew in the forenoon;
in the afternoon, this was prevented by the state of the weather.
To-day we sat down together in the morning, and I was favoured to feel refreshed.
We have now a steady trade-wind from the eastward,
sufficient to allow our making a north course good against an opposing swell;
but we are greatly annoyed by another swell more heavy upon the quarter,
which makes the motion uneasy, and at times violent.

14th.--Steady wind from the east and fine weather.
Yesterday, assembled the crew twice in the day for devotional purposes.
About eleven in the forenoon, the Henry Freeling entered the North Pacific.
At noon our latitude 0° 6`' north of the equator; longitude about 147° west.
This morning we have got through a strong current which in the course
of a few hours had swept us twenty-eight miles to the westward,
as indicated by the chronometers.

For more than three weeks after leaving Bolabola,
our progress was greatly impeded by an almost constant
succession of contrary winds and rugged weather;
and yet I could never see my way to bear up and run back to the islands for shelter.
I believed on setting out that the track towards the
Sandwich Islands was the right one for me to pursue;
and yet every thing combined to obstruct and frustrate our best attempts to persevere.
Winds from quarters whence they are seldom known to blow in these seas,
were permitted to buffet us at times strongly, with considerable sea: these,
together with a succession of drenching heavy thunder rains,
made the prospect additionally discouraging and gloomy to some on board.
Although I never hinted it to any one, yet I had pretty much concluded that,
on reaching the equator,
if the northerly blast should then appear to be fairly established strongly against us,
I should be satisfied to bear away before it for the nearest port;
rather than any longer persist in beating our little vessel to pieces,
by contending against its overwhelming force,
as having done all I could to endeavour to follow the
line of apprehended duty cast up before me;
not doubting but the will would be accepted for the deed,
by Him who knows the integrity of all hearts,
and who had witnessed our faithful striving, week after week,
to accomplish its fulfilment: but, on reaching the utmost bound of south latitude,
yesterday, instead of boisterous and contrary winds,
we were favoured to cross into the northern hemisphere with a leading breeze,
and as beautiful weather as could be imagined:
and such has been our progress through the night, that at noon this day,
our latitude is 2° 28`' north, and 146° 59`' west longitude by lunar observation.
This change in a prospect so lately and so darkly clouded,
has brought with it comfort and strength,
and caused gratitude and thanksgiving to spring in my heart to
our all-merciful and faithful Creator and Preserver.

17th.--Continued to make rapid progress, since the 14th instant,
to the northward with a side-wind.
Yesterday the appearance of the weather became very threatening,
and the swellings of the ocean much increased.
A considerable quantity of rain fell in the course of the day;
but the clouds most heavily charged rode past us altogether unbroken.
Charles and myself sat down in the forenoon, and towards the latter end of our sitting,
a small portion of strength was felt, to draw nearer to the Fountain of life.

Twelfth Month 21st.--The wind rather more in our favour.
Our progress somewhat retarded by changing several of our sails,
being too old and thin to trust to, when exposed to heavy gusts from mountainous land.
Yesterday the assembling of the crew for devotional purposes was not omitted.
At ten o`'clock p.m. last night shortened sail,
for fear of a supposed island being in our route, called Hirst`'s Island.
This island is mentioned by Norie, in a chart published in 1833, belonging to our mate;
whilst our own private chart, and the ship`'s atlas are silent on the subject.
It is probable this island may exist, but certainly not in the place laid down;
for we must have passed in the dark, nearly over the spot where it is said to be,
and met with nothing.
This circumstance cost us several hours of a beautiful wind,
without the satisfaction of being able to establish the
fact of there being such an island or its true position,
for the benefit of other wandering pilgrims on this expansive watery waste.

On the 19th, did not fail, and, I trust, allowably so,
to remember the mercifully-bestowed,
and long-entrusted and beloved partner of my bosom;--a bosom friend indeed,
guileless and faithful; whose loss to me was indeed great and irreparable,
but her gain eternal:--humble resignation to the
Divine will is as a canopy of peace around me,
although the loss was such, that even time does not lessen its extent.

23rd.--Yesterday the wind fresh and favourable: we got on rapidly also through the night,
and to-day are still hastening onward with a following sea.
At noon the latitude 19° 41`' north; at four o`'clock p.m., longitude 153° 18`' west.
This morning hauled a little more to the westward, to endeavour to make the land.
Just before sun-set, the sight of land was announced from the mast-head;
but the haze about the water`'s edge made it very indistinct,
and not visible from the deck to myself, until the sun had sunk below the horizon;
when not only the stupendous mountain of Mouna Kea, with its snow-clad top,
which is more than 13,000 feet above the level of the sea;
but the lower land towards the north cape of the
island of Hawaii could be plainly distinguished,
at the distance of more than eighty miles.
Here is a renewed call for thankfulness,
after such a winding and intricate passage of six weeks,
thus to be favoured with such a defined,
and decidedly excellent land-fall before the night
closed upon us,--which is now long and dark,
the shortest day, in this region, being just over,
and the moon but in an infant state at present.
The mercies of the Lord are indeed from everlasting to everlasting,
and blessed for ever is He, the Lord God of Israel, who only doeth wondrous things;
blessed be his glorious name for ever, and let the whole earth be filled with his glory:
and who can refrain from saying with David, "`Amen and Amen!`"

24th.--This sight of the land enabled us to run through
the dark under whole canvass without fear,
thus making great progress; and this morning the lofty mountain upon Hawaii,
from our having approached at least fifty miles nearer to it,
appeared twice as high as it did last evening.
Before noon the island of Maui was discernible from the deck,
and at sun-down Tauroa was plainly to be seen.
At eight o`'clock p.m., off the west end of Maui; reduced the canvass for the night.
Our getting into Oahu to-morrow is at present uncertain; the day must declare it:
at four o`'clock p.m. this afternoon, we were one hundred and thirty miles distant.

+++[+++In a note subsequently written, Daniel Wheeler adds:]
some of my beloved friends may be at a loss for the reason of our
passing by some of the largest islands in the Sandwich group,
(particularly Hawaii,
formerly considered as the chief of the cluster,) and aiming directly at one,
not one-third its size, and much less than Maui.
This decision seemed to arise from the circumstance of
Captain Keen`'s being a stranger to the other islands,
and from the information obtained,
that there was no safe anchorage for a vessel in the winter season, except at Honolulu,
in the island of Oahu, where there is safety at every season of the year.
It occurred to me at the same time,
that if we should be favoured to reach Oahu in safety,
and then find it necessary to proceed to the other islands,
some person might be found well acquainted with their different bays, roads, coves,
creeks, etc., and be easily obtained to accompany us on such a visit.
These were my motives for what might seem, and did seem to some people,
beginning at the wrong end of the work, by going to leeward,
and having to come back again against the tradewind, which is no easy matter.
But I have since found,
that I should have been wrong altogether if I had stopped short of Oahu;
for here I found the seat of the government of the islands;
and also the head quarters of the American missionary establishment: in short,
here was the only means of access to the authorities of the other islands,
and to the missionary stations; and, in some instances,
we could not have procured supplies for the vessel without an order from the government,
or an agent of theirs sent along with us.
I mention the missionary stations as needful to have access to,
because it is only at them that I can look for an interpreter,
and through him that I can speak to the native tribes.
We therefore passed by Hawaii, Maui, and Morakai,
at all of which are several missionary stations, except the last mentioned,
where there is only one.
And it now fully appears that the step of coming in the first place to Oahu,
has opened the way in a most satisfactory manner in
every respect for a visit to the other islands.

I feel it no light thing to be, as it were,
upon the eve of again landing upon shores by myself as yet untrodden,
amongst thousands and thousands of my fellow-creatures,
in whose sight I must unquestionably appear,
"`as one born out of due time;`" but when I trace the
motive of my coming to its utmost source,
I am favoured to find a foundation firm enough to bear me out:
and the prospect of another opportunity being afforded me,
for the exaltation of the dear Redeemer`'s kingdom,
at seasons warms and gladdens the heart,
rekindling a measure of that love which desires
the welfare of all mankind the world over;
many of whom have long since heard of the name of Jesus, the Messiah, at a distance,
but know him not as a Saviour, nigh in the heart to save them from their sins.

25th.--The breeze continued until midnight, after which it gradually lessened,
and at four o`'clock a.m., we were becalmed.
In the forenoon made some progress with light winds, and before noon got sight of Oahu;
but the prospect of our getting in is now doubtful, the wind having become variable.
Towards evening the breeze freshened,
and enabled us to get considerably nearer to the island.
The whole of the Sandwich group in sight, except Tauai, or Atooi,
which lies ninety-four miles to leeward of Oahu.
Before dark, a sail hove in sight from the westward,
the first and only vessel we have seen at sea for the last eight weeks,
or since leaving Huahine.
