== Chapter XXVII.

[.chapter-synopsis]
* Interview with the Queen
* Public Meeting
* Half-Caste Boys School
* Address to the Rulers of the Sandwich Islands
* Visit from the Mission Families
* Meeting at the Chapel
* An Infidel Ship`'s Company
* Appointed Meeting
* Departure from Honolulu
* Hawaii
* Anchor in Kalakakua Bay
* Public Meeting
* Interesting Opportunity with the Mission Family
* Proceed to Kailua
* Native Meetings
* Visit of the King
* Departure for Waimea

Second Month 17th,
1836.--This evening repaired to Hiram Bingham`'s by appointment to meet Kinau,
the reigning chiefess, or queen.
Her husband Kekuanoa was there, and Kanaina another principal chief and his wife,
a woman of higher rank than Kinau on her father`'s side.
It proved an interesting season;
they were desirous of being instructed in the best mode of governing the islands,
and benefiting the people.
I told them, there is but one way to effect this,
and that is upon the principles of the gospel; nothing else will stand.
Kinau has long been desirous of prohibiting the
importation and use of ardent spirits altogether,
and requested some advice upon this head.
It would require caution, I said;
but that the first step would be to stop all further importation;
and that they themselves had better become purchasers of the stock on hand,
and empty the ram into the river,
than that the people should be destroyed by its effects;
the dealers would then have no cause to complain:
that best wisdom should be sought for to direct,
and that all these things should be conducted throughout in a Christian spirit.
It is high time something was done to remove this evil from amongst the people.
They expressed satisfaction with the interview,
and suggested that we should meet again for the
further consideration of this important subject,
viz. the best manner of governing the islands and benefiting the people.
Both these females are tall, portly women, of shrewd understanding,
and have a gentleness in their demeanour not
usually possessed by others of the same rank,
though on first appearing they assume much reserve and austerity.

18th.--Some time back my mind was attracted towards preparing something like an address,
to be left with those that bear rule over the inhabitants of these islands;
which might serve to remind them at a future day,
that I had not omitted to warn them of those evils, which, if suffered to continue,
will undermine every effort to improve their condition, both civil and religious.
The conversation which took place last evening seems to
have opened the way for something further,
and confirmed me in believing myself required, as ability may be afforded,
to draw up and leave some written document for the clearance of myself towards them.

20th.--Before retiring to rest,
I began to feel a little towards the evening meeting at the Mariners`' chapel to-morrow,
and the love of the gospel flowed in my heart so encouragingly,
that a willingness was at once begotten,
to give up to a meeting being appointed on my account.

21st. (First day.)--This morning I received a note written at seven o`'clock a.m.,
from the American preacher, offering his place of worship for an evening meeting.
On solidly considering the subject, I believe,
with an honest desire to do the will of my gracious Master,
I did not feel easy to let the opportunity pass away without availing myself of it;
and therefore, in due time sent written information,
in order to insure its being held as a Friends`' meeting.
In the course of the day our sailors were assembled twice for devotional purposes;
and in the evening they attended the public meeting at a quarter past seven o`'clock,
an hour best adapted to the climate and the people.
The meeting was larger than looked for, as the weather was showery;
a number of strangers were present, who had arrived two days previously from Boston,
also the most seriously inclined of the residents,
several branches of the missionary establishment, with an increased number of sailors,
and many of the islanders.

We sat long in silence, but under a feeling, solemn beyond expression,
which chained down opposing spirits.
When the time came for me to stand up,
I had to contrast the worship of Almighty God under the
Jewish dispensation in the outward temple,
with that of the gospel in the inner temple of the heart;
the latter altogether spiritual, because "`God is a spirit, and they that worship him,
must worship him in spirit and in truth.`"
How can we so expressively manifest our fear and love
in approaching the presence of infinite purity,
as in solemn, awful silence, in humble watchfulness of mind,
endeavouring to detect and suppress every creaturely desire? Words are inadequate,
and not essential in the performance of worship to Him who is a Spirit,
for his Holy Spirit searcheth all things;
the most hidden and secret thought is known to this all-penetrating, all-searching Power.
No offering is acceptable to Him, but what He himself prepares;
for "`the preparation of the heart in man, and the answer of the tongue,
is of the Lord,`" and the entire prostration of the will of the creature,
under the preparing sanctifying influence of his Almighty power, constitutes the pure,
unadulterated offering; which, free from human contrivance and performance,
rises a spiritual sacrifice, acceptable to God,
through the Holy Spirit of the Lord Jesus Christ,
the great and everlasting high priest of our profession.

The people were called upon to behold what manner of
love the Father hath bestowed upon his creature man,
that we should become his sons: for who can comprehend the greatness of that love,
wherewith "`God so loved the world, that he gave his only begotten Son,
that whosoever believeth in Him should not perish,
but have everlasting life;`" who can contemplate
the fulness and extent of love like this,
and not feel a grateful tribute to arise,
of "`thanks be unto God for his unspeakable gift?`" My soul longeth that all
mankind may become acquainted with the preciousness of this costly gift.
It is the same which was testified of in the memorable and instructive
conference of the blessed Saviour with the Samaritan woman,
when He condescended to answer her question, "`How is it that thou, being a Jew,
askest drink of me,
who am a woman of Samaria? for the Jews have no dealings with the Samaritans.`"
"`If thou knewest the gift of God,`" our Lord replied,
"`and who it is that saith unto thee, Give me to drink; thou wouldest have asked of Him,
and he would have given thee living water.`"
"`The woman saith unto him, Sir, thou hast nothing to draw with, and the well is deep;
from whence then hast thou this living water? Art thou greater than our father Jacob,
who gave us the well, and drank thereof himself, and his children,
and his cattle? Jesus answered and said unto her,
Whosoever drinketh of this water shall thirst again;
but whosoever drinketh of the water that I shall give him, shall never thirst;
but the water that I shall give him,
shall be in him a well of water springing up into everlasting life.`"
The poor woman perceiving the great advantage of possessing water,
of which "`he that drinketh shall never thirst,`" said, "`Sir,
give me this water that I thirst not, neither come hither to draw.`"
Her expectation was thus raised, and her understanding opened more and more to discern,
from what followed, that she had met with one, from whom nothing was hidden,
and that knew all that was in her heart; and perceiving that He was a prophet,
and by inquiry having elicited for the lasting benefit of all mankind, the declaration,
that the hour was come,
"`that the true worshippers shall worship the Father in
spirit and in truth;`"--confounded and self-convicted,
she concluded by saying, "`I know that Messiah cometh, which is called Christ;
when he is come, he will tell us all things.`"
Then the Lord of life and glory was pleased to reveal himself, telling her,
"`I that speak unto thee am he.`"
From what she had heard and felt, she could not for a moment doubt;
and leaving her water-pot, went her way into the city to proclaim his power,
and declare Him to her brethren;--"`Come,
see a man which told me all things that ever I did:
is not this the Christ?`" I was strengthened to make a
solemn and confident appeal to all present,
who had attained to years capable of serious thought and reflection,
if they had not at seasons heard the voice of this
"`unspeakable gift,`"--bringing to their remembrance "`all
things that ever they did,`" in order that they might repent,
return unto God, and live forever.
This is the grace that brings salvation,--in this we
must all believe,--to this we must all come,
and hearken and obey its teachings.
The above is the substance of what was declared amongst them:
the people were very attentive, as has been uniformly the case at every meeting.

Second Month 24th.--This afternoon the Columbia barque and
Beaver steam-vessel prepared to proceed to the Columbia river.
Before sailing, they were furnished with a supply of tracts,
viz. those printed for Friends, for the Religious Tract Society,
and a number of temperance tracts, which were received with apparent kindness.
The crews of these vessels are amongst the most profligate
that have visited the port of Honolulu since our arrival;
they are both in the employ of the London Hudson`'s Bay Company.

Whilst on shore this evening in the direction of Diamond Hill,
I was suddenly attracted by an appearance of light over the hills,
which I supposed to be the rising moon; but I soon found it was a beautiful meteor,
appearing like two splendid bars of light, parallel to each other,
travelling towards the north.
The natives shouted on seeing it,
considering it a forerunner of the death of one of their principal chiefs.

25th.--Held our week-day meeting as usual, which proved a low,
stripped and barren season; but we must be content to suffer with a suffering Lord;
and truly the state of the people in this place is affectingly dark,--
the prince of darkness reigns unmasked,--the lives and conduct of the
major part of the white residents declare it openly,
to whom these remarks principally refer.

26th.--To-day visited the school of half-white boys.
As our calling was altogether unexpected,
there could have been no contrivance whatever to show off to the best advantage.
Sixteen boys were present: we heard them read, spell, and answer a variety of questions,
and saw specimens of their writing.
This school has been established rather more than three years,
and although no great progress has been made by any of the scholars;
yet when we consider the habits in which they have been trained,
and the baneful examples to which they are daily and almost hourly exposed when at home,
of drinking, swearing, gambling, and every evil that can well be imagined,
it is surprising that they are as they are.
Several of the parents are grog-sellers, and keepers of gambling-houses.
Some of the children are the offspring of the principal inhabitants, American or English,
on the father`'s side, who live with native women, but unmarried.
In point of intellect these children are equal to any in the world,
and some of them particularly quick and intelligent;
but none more so than one trueborn native boy, adopted by a white resident,
from supposed motives of policy.

On hearing them read some manuscript verses on '`a little boy
that never told a lie,`' also a paper against committing sin,
I perceived something gathering upon my mind,
and told the master that I wished to say a few words before we separated,
as we might never meet together again.
I wished them fully to understand,
that the knowledge they were acquiring would in reality be of no benefit,
but render their condemnation greater, unless obedience kept pace with it;
reviving the Saviour`'s words,--"`If ye know these things, happy are ye if ye do them.`"
That those verses on '`a little boy that never told a lie,`' or
those '`against committing sin,`' even if they had them by heart,
would be of no avail to them, if they gave way to telling lies,
or to committing any other sin: for "`nothing that is unclean, nothing that is impure,
that worketh an abomination, or maketh a lie,`" shall enter the kingdom of heaven.
That the only way to escape falling into temptation, is at all times, as much as may be,
to consider ourselves in the presence of Almighty God;
who sees and knows all our actions, and the most secret thoughts of the heart,
by His Holy Spirit, which searcheth all things, even the deep things of God;
every imagination of our thoughts is known to Him, nothing can be hid.
That some of them were old enough to know when they did wrong,
either in telling untruths, or when in any other way they committed sin;
they then felt uncomfortable and unhappy in themselves:
that these are the reproofs of the Holy Spirit for sin and disobedience,
and if attended to would lead to life; and to these I wished them to take heed.
That the Lord loveth an early sacrifice: He delighteth to regard it:
that they must have heard what the voice of wisdom saith in the Holy Scriptures;
"`I love them that love me, and they that seek me early shall find me.`"
That they could not begin too soon to seek an acquaintance
with the Lord`'s Holy Spirit in their hearts,
that so they might become truly wise.
That the great end and object of all teaching and all learning,
should be to make wise unto salvation.
The boys were very attentive, and behaved in a solid manner.
We remained until the school was dismissed, and then returned on board.
In the evening we were again on shore, and were detained there until after nine o`'clock,
by a violent storm of thunder, lightning, and rain.

29th.--Yesterday, First day,
collected the crew twice in the cabin for devotional purposes:
our intervals of silence were solid and consoling.
This afternoon came in the Gryphon, from St. Blas, bringing intelligence from America,
via Panama, in sixty-eight days,
of the destruction by fire of a large portion of the city of New York.

Third Month 1st.--Having completed an address to those who
bear rule over the inhabitants of the Sandwich Islands,
it seemed best to consult the senior missionary on the
subject of getting it translated into their language.
After having perused it, he very kindly undertook to translate it,
in readiness to lay before the king and chiefs when convened for the occasion,
in the course of a day or two.

11th.--This morning Hiram Bingham came on board to say
we were expected this evening at his house,
as Kinau the governing chief, with her associates, and the king himself, would be there;
and that my address would probably be read.
May the Lord incline their hearts to render unto him His due.

12th.--Soon after sunset last evening, we repaired to Hiram Bingham`'s,
where the whole of the expected company assembled, with some others.
After tea the address was introduced, and read in the native language:
the greatest attention was manifested by the principals present,
and a solemn feeling prevailed over us.
Shortly after the reading was finished,
one of the females proposed that it should be printed, which was confirmed by Kinau,
and it appeared to be the mind of all the parties concerned: unless this were done,
it is scarcely probable that the end intended would be answered,
as to the future rulers of these islands.
Kinau remarked, that it was very easy to be understood.
Having done what I believed to be my part, I can peacefully leave the result to Him,
who alone can make it subservient to any purpose for his own praise and glory,
and the well-being of the workmanship of his hands.
The following is a copy of the address:--

[.blurb]
=== Address to the Rulers of the Sandwich Islands

As the present and eternal well-being of the inhabitants of the Sandwich Islands,
is often the fervent and ardent desire of my heart,
my attention has of late been arrested by the belief,
that it will be best for me to leave behind a written memorial; which,
under the blessing of the Almighty parent of the whole human family,
"`the God and Father of our Lord Jesus Christ,`" may have a tendency
to remind the governing chief and her associates in authority,
or those into whose hands the government of
these islands may be entrusted at a future day,
of their great responsibility and indispensable duty to God, to themselves,
and to the people over whom they preside.

In order to draw down the Divine blessing both upon prince and people,
or upon rulers and people, let it never be forgotten,
that "`he that ruleth over men must be just, ruling in the fear of God.`"
The fear of God is the foundation-stone,
upon which every Christian government ought to be erected:
upon this only it can stand secure and prosper.
This fear at once makes it safe and permanent, because it "`is clean,
enduring for ever`" for where the true fear of
God prevails over every other consideration,
the heart is kept clean and watchful against every
temptation to let self-interest or partiality bear sway,
either in the case of ourselves or others, when decrees or laws are made or enacted,
or when judgment is called for between man and man.
Impartiality is the life of justice, as justice is of government.

When every thing is conducted in this fear in the sight of God,
divested of partiality and every sinister motive,
without feeling any painful sense or evidence of
condemnation after a decision of importance is come to,
(and every case is important because it demands strict
justice;) then have we confidence towards Him,
inasmuch as our duty is performed towards Him, and justice has assuredly prevailed;
and having done our duty towards God in this decision,
it is done also to ourselves and to the people.
"`But if our heart condemn us, God, who knoweth all things,
is greater than our hearts`" and we may rest assured,
that such a decision is not in righteous judgment: it hath not been come to in His fear,
nor in that love which is first of all due to Him, and then to our neighbour or brother,
as unto ourselves.
This love would not fail to prompt us to do unto others,
as we would that others should do unto us; and for want of this,
an unjust decision has been made,
for which we are condemned by the Lord`'s holy and pure witness in our hearts;
it has been made contrary to the commandment in the old law,
and also to the benign principle and precept of the glorious gospel,
both which are distinguished by the heaven-born characteristic of love to God,
and love to man.
"`God is love, and he that dwelleth in love, dwelleth in God, and God in him.`"
Such are the excellent of the earth, and they compose the blessed in heaven:
they are come "`to the spirits of just men made perfect,`" and are fit to rule over men:
their judgment is just and righteous; they rule "`in the fear of God.`"
The religion of Jesus at once qualifies a man for every station of life,
in which it pleases Almighty God to place him;
but it is the ever-blessed truth in possession, in the inward parts,
which alone can safely guide out of all error into all truth, and make us to know wisdom.
A mere profession only will avail us nothing,
if we are destitute of the true fear and love of God, demonstrated by good works:
and faith is the root of all, for without this we cannot please God;
nor can we fear and love that, in which we do not believe.
The Saviour of the world was holy, harmless, humble, meek, and lowly, just, merciful,
and full of love; yea, love itself personified,
when among us to teach what we should do when He was gone.
But He is amongst us still, and in us too,
an ever-living and perpetual preacher of the same grace,
by His Holy Spirit in our consciences; and by this alone kings and others,
whose province it is to rule over men,
are qualified to promote amongst the people whatsoever things are true, honest, just,
pure, lovely, and of good report; and where these are the fruit and works produced,
such a government and such a people must be lovely indeed to every beholder.
But now let us examine whether our justice is complete in the fear and love of God,
and to our fellow-men, lest we should be deceiving ourselves,
and endangering the well-being of our own immortal souls; while those we are ruling over,
shall be finally admitted, with Abraham, Isaac, and Jacob, into the kingdom of God,
and ourselves thrust out: "`For whosoever shall keep the whole law,
and yet offend in one point, is guilty of all`"--in like manner,
"`he that is unjust in a little,`" is at once
upon a level with him who is unjust in much.
And although we may be faithful and strictly just in
the administration of the laws themselves,
without partiality or respect of persons; yet,
if these laws are such as to sanction covetousness on the part of rulers,
and to allow them to grind the faces of the poor
by unwarrantable oppression and extortion,
or to uphold and support themselves in vice, luxury, and extravagance;
then this calculation may be safely made,
that sooner or later the oppressed people will take the
reins of such a government into their own hands,
and rule in their turn after the example of injustice and oppression,
which has been set before their eyes,
and under which they have so long groaned and suffered, unheeded and unregarded;
unless the merciful and righteous Lord should please, in wanted compassion,
to gather them to Himself from the face of the earth,
and permit strangers and foreigners to possess these fruitful islands,
who for want of firmness and justice on the part of the rulers, towards God,
to themselves, and to the greatly injured aborigines of the soil,
are rapidly establishing themselves upon it, and prosecuting commerce,
some branches of which are obviously pernicious.
Therefore, they who rule over men must be just, ruling in the fear of God:
and where they are happily thus ruling, they will be truly great,
and their reign glorious; every act of injustice will be avoided: love, joy, peace,
and comfort will prevail in the land; the population, instead of diminishing,
will increase and multiply abundantly, and the blessing of the Lord will rest upon it.

'`Happy those rulers,`' said a wise man, '`who are great by justice,
and that people which is free by obedience:`' and
they who are just to the people in great things,
and humour them oftentimes in small ones,
are sure to have and keep them from all the world.
The members of an obedient well-regulated family,
treated with every act of affectionate kindness,
never meet with any home so sweet as their own; besides,
long experience and holy example tell us,
that goodness raises a nobler passion in the soul,
and begets and gives a more exalted sense of duty, than cruelty, oppression,
and severity.`' Sore and heavy judgments are denounced
by the Most High in the Scriptures of truth,
against oppression,
and oppressors of the poor and of him that hath no helper,--
"`He that oppresseth the poor is a reproach to his Maker;
but he that honoureth Him hath mercy on the poor:`" and the justice
and mercy of rulers should shine conspicuously in all their actions.
The wicked and unjust man and his oppressor,
have their portion and inheritance appointed of the Lord, and it is declared,
"`they shall receive it of the Almighty: if his children be multiplied,
it is for the sword, and his offspring shall not be satisfied with bread;
those that remain of him shall be buried in death, and his widows shall not weep:
though he heap up silver as the dust, and prepare raiment as the clay; he may prepare it,
but the just shall put it on, and the innocent shall divide the silver.`"
The Israelites were sorely oppressed in their day,
but what was the result? the destruction of Pharaoh and all his followers.
If the poor people of this island and the surrounding ones are grievously oppressed,
either by burdensome claims or taxation, they that rule over them cannot be just,
ruling in the fear of God;
and however they may reconcile these things to their own consciences for a time,
the Lord`'s righteous judgments will assuredly overtake them:
He will plead the cause of the poor and of the
oppressed with a mighty hand and stretched out arm;
and will rid them of their oppressors, for His great name`'s sake.
Now, that justice and judgment in which the Lord delighteth,
would at once loose the bands of wickedness, undo the heavy burdens,
let the oppressed go free, and break every yoke of exaction and extortion.
The people would then enjoy the comforts and blessings,
which the Lord in mercy hath bountifully showered down upon them;
they would then feel an interest in the welfare of their neighbours,
and in their country at large: but if afflicted by the pressure of heavy burdens,
every feeling of sympathy and social interest is benumbed;
they have nothing to loose and nothing to gain,
and it matters little to them who are their rulers;
they can scarcely be worse off than they are.
If their privileges as men and brethren be not consulted and respected,
the profession of Christianity is but mockery; instruction only serves to show them,
that their rulers are not just, nor ruling in the fear of God:
and the pretensions of such rulers to religion are vain,
more calculated to produce disgust and abhorrence at its restraints, than piety, virtue,
and holiness.

Although much has been said, and might still be said,
yet it all centres in one point at last;--"`He that ruleth over men must be just,
ruling in the fear of God.`"
Such as are desirous of ruling in His fear,
can only be advised to take council of Him on every occasion,
by invariably consulting the holy witness in their own hearts,
which will neither flatter nor deceive.
If we are truly desirous of obeying the royal law,
of doing to others as we would ourselves be done unto,
let us endeavour to place ourselves in the situation of others,
and act for them as if acting for ourselves, in all cases and at all times,
without partiality, or respect of persons, whether rich or poor, high or low,
bond or free, old or young, stranger or friend;--for the same justice is due to all.
It would be as presumptuous and assuming, as it would be altogether in vain,
for any individual to take upon himself to advise in a matter,
which involves so great a responsibility as that of ruling over men;--
beyond simply referring all parties to the righteous and only true
and safe principle of justice in the fear of God.
To fear God and keep his commandments,
is the whole duty of man in every station upon earth,
from the loftiest prince to the humblest peasant; and the way to fear Him is,
for all of us to bring every thought, word and deed,
to the light of his Holy Spirit in the secret of the soul; and to watch and pray,
and wait in this light, to know His holy will,
which would clearly discover whether the action or
transaction we are about to undertake or engage in,
or decide upon, (whether we be rulers or people, for the question bears on all,
and the light shines in all,) is done or committed in the fear of God,
and in obedience to His commandments,--which are,
that we should love Him above and before all, and our neighbour as ourselves.
If we do not act upon these manifestations, in faithfulness and truth,
our heart will condemn us; because what we do, is not done in the fear of God,
who is greater than our heart, and knoweth all things.
But if our heart condemn us not, then have we confidence toward Him;
and whatsoever we ask we receive of Him, because we are walking in His fear,
and keeping His commandments,
and doing those things which are pleasing in His Divine sight.
From the best observation I have been able to make,
whilst hearing the sentiments of persons high in authority over these islands,
in addition to an evidence upon my own mind abidingly sealed,
I am thoroughly convinced by their own remarks upon things of the highest concernment,
that they know +++[+++what is right]
well enough: "`for that which may be known of God is manifest in them,
God hath showed it unto them,`" to the praise and glory of his grace.
All that is wanting on their part,
is a constant dwelling near to this precious gift of God in their own hearts,
watching unto prayer; "`praying always with all prayer and supplication in the Spirit,
and watching thereunto with all perseverance.`"
Then their councils and deliberations will be blessed:
they will be qualified to judge righteous judgment at all times and in all cases,
against every false tongue,
even to the giving "`the living child to its own mother,`" and
no weapon formed against them by Satan or his agents,
shall be suffered to prosper; for the Lord Most High will be their "`shield,
and their exceeding great reward.`"

It is an evident sign of a corrupt and unchristian government,
when any of its subjects are permitted to suffer persecution,
either directly or indirectly,
on the score of religious dissent from any particular established form,
so long as the public peace is undisturbed;
as the "`sword of the magistrate should be a terror only to evil-doers,
but for the praise of them that do well:`"--"`by their fruits ye shall know them.`"
To persecute others, because they do not see or think as ourselves,
is the sure and hateful mark, which can never be mistaken, of the false church,
over which the devil presides in full power: but the true church,
whose holy head is the Lord Jesus Christ, never persecuted any; but "`suffereth long,
and is kind; beareth all things; believeth all things; hopeth all things;
endureth all things; rejoiceth not in iniquity,
but rejoiceth in the Truth,`" its sure and immovable foundation:
love and mercy being the chief corner-stone,
upon which no other principle shall ever be displayed,
than that of "`doing to others as we would that all men should do unto us.`"

Let none consider me an enemy, because I have spoken the truth.
I pray that the foregoing hints may be accepted in a
measure of the same love in which they are written,
by one who desires the eternal salvation of all mankind.

[.signed-section-signature]
Daniel Wheeler

[.signed-section-context-close]
On board the Henry Freeling, in the harbour of Honolulu, the 1st of Third Month, 1836.
Sandwich Isle, Oahu.

13th. (First day.)--Remained on board through the day with our own people.
Strippedness and poverty of mind are my present portion, and perhaps,
food of all others the most needful for me.

18th. It having been a subject of consideration,
whether there would not be a propriety in our
showing kind attention to the American mission,
by inviting some of each family on board the Henry Freeling,
as best suited their convenience,
lest by an apparent non-intercourse of a social kind betwixt us,
malicious reports might get circulated by the white residents,
calculated to injure them in the estimation of the natives;--and also,
in the hope of setting aside some false impressions detrimental to their interest,
of which there had been already no slight indication;--
it was concluded to adopt such a measure:
we therefore called yesterday evening upon the two oldest families,
who readily accepted an invitation to visit us.
When leaving the senior missionary`'s habitation, a newspaper was put into my hand,
said to contain the great '`Missionary Question,`' accompanied with a
desire that our sentiments might be given on the subject.
On examining the paragraph alluded to, when returned on board,
I found this question had been propounded by the
said missionary himself to the American board,
in these words:
'`We are often led to inquire (can you tell us?) why it is that
so few who hear the gospel in Christian countries,
and in the fields of missionary labour, are savingly converted to Christ?`' querying,
if the cause of this acknowledged and deplored evil arose from
such and such circumstances as he enumerates at full length.
Both, or parts of both families came on board the 19th instant, as invited.
The weather boisterous, with frequent heavy rains.

22nd.--Yesterday and to-day some of the members of the missions, both male and female,
came on board, but the roughness of the weather necessarily shortened their visit.
In the evening attempted to take exercise on shore,
and although we reached the landing-place, the rain fell so heavily,
that we did not quit the boat, but returned to the vessel again.
In the night heavy gusts of wind from the mountains; at one o`'clock a.m.,
the brig Bolivar drove down upon us, but no injury was sustained.
Two vessels from Boston are now at anchor outside the reef;
this is the third day of their being in this exposed situation,
and the wind is still so strongly opposed that they cannot enter the harbour.

26th--But little communication with the shore since the 22nd instant,
owing to the state of the weather.
By a newspaper brought out by one of the vessels just arrived from America,
we are furnished with the Epistle of the Yearly Meeting, held in London in 1835,
of which a present has been made to us in great kindness:
it was a treat no less welcome for not having been anticipated,
and to myself particularly consoling,
being replete with explanation of the principles and views of our religious Society,
as held by our worthy predecessors when they first came forth;
and declaring them to remain unalterably the same at this day.
I trust the pure mind will be stirred up in many
of our members to a serious consideration,
whether we are endeavouring to uphold them in their original purity and simplicity,
to the eyes of the world, and in faithfulness and gratitude to Him;
who called and separated those ancient worthies from the many
"`Lo here`'s,`" and "`Lo there`'s`" of their day and generation,
to be a people to His praise.
We also obtained a copy of an article contained
in a late Petersburg Journal of Agriculture,
in which our own name is mentioned in connexion with the
improvement of the lands in the neighbourhood of that capital,
etc.
To hear of my beloved family being still there, at least when the account was printed,
which was much later than any tidings we had ourselves received,
although nothing could possibly be gleaned of their present state and welfare,
yielded a satisfaction, which those only can appreciate,
who have been long and distantly separated from
all most dear on earth to memory and life.

27th. (First day.)--The weather still very boisterous.
Assembled the crew in the cabin twice in the day.
In the forenoon it was a dull, heavy season; in the afternoon more lively.
I have been much cast down of late by several discouraging circumstances.
The continuance of heavy rain not only confines us more on board,
but within the narrow limits of our little heated cabin below deck.
In addition to this, I do not see my way clear for leaving the island of Oahu;
while most persons around are impatient to be gone,
and cannot exactly enter into my feelings.
The Lord alone knoweth, and to Him I commit my cause,
and desire to bow in humble resignation to His holy Will:
if only now and then favoured with a glimpse of His heavenly, life-giving presence,
(however short, if certain,) it will be enough.

Fourth Month 21st.--Received a visit to-day, by invitation,
from a white resident and his wife; whom we were desirous of noticing,
on account of the good example they hold forth to the other white residents,
their neighbours: his wife is a native of the island, and of good character.
They have been regularly married, a very rare occurrence here in such cases;
and what is still more rare, they are in repute for their moral and orderly conduct,
whilst most of the white residents are a disgrace to a skin of any colour,
and frequently have three or four native women as wives.
Of course I do not include the mission families in these remarks.

23rd.--In the afternoon the king came on board to take leave of us,
being about to sail for the island of Maui,
and his vessel at the time waiting with her canvass spread,
in readi ness to convey him away.
He gave me a pressing invitation to visit him at Waiaruku on the other island:
the shores were crowded with natives to witness the departure of their king.
The artillery of the fort announced his final embarkation;
whilst the shipping in the harbour, and his own brig, kept up an occasional firing,
as she passed through the channel between the coral reefs.
One hundred and fifty persons accompanied him as retinue.
No exhibition equal to this, we are told,
has occurred since the departure of Rio Rio for England.

24th. (First day.)--In the morning wrote a note to John Deill,
enclosing a written notice,
which he was requested to read to the people at the breaking
up of the forenoon meeting;--that a public meeting for worship,
after the manner of the Society of Friends,
would be held in the Mariners`' chapel that evening, at the usual hour;
to which the company of all persons who inclined to attend was requested.
Our captain delivered this note to John Deill, and no difficulty appearing on his part,
notice was then personally given in such directions as
seemed most likely to insure full publicity.
Read portions of Scripture to our seamen twice in the course of the day.
At the time appointed, landed to attend the meeting: it gathered slowly,
but in the end was well attended.
After sitting a while in silence,
it was with me to point out the desirableness of our
endeavouring to get into a quiet state of mind;
that we might be sensible of the influence of the Holy Spirit,
to solemnize our minds together,
if He should be graciously pleased to lift up
the light of His heavenly countenance upon us,
and bless us therewith: we then settled down into silence before Him.

After a time, one or two persons went out,
but stillness generally prevailed over the company.
When the time came for me to stand up,
I told them that I had had no expectation of my voice being heard
again among them;--that my mouth had for several weeks been closed up,
and that a heavy burden had rested upon my mind;--to what shall I compare it,
but to "`the roll that was written within and without, with lamentation, and mourning,
and woe,`" for the inhabitants of that place;
who are crucifying to themselves the Son of God afresh,
and by their example putting him to open shame in the
face of the benighted islanders among whom they dwell.
It was probable that those who were the principal causes of this travail of soul,
were not among that company; but I could do no less for the clearance of my own mind,
than publicly advert to this lamentable state of things;
lest I should be found short of doing my own duty,
though the cause of suffering might not be removed:
but the disciples of Christ must be willing to suffer with their suffering Lord,
and to fill up that which is behind,
that which remains of the afflictions of Christ in the flesh, for his body`'s sake,
which is the church.
Notwithstanding the extent to which sin and iniquity abound,
such is the wondrous love of God to his creature man,
that he willeth not the death of a sinner, but that all should repent, return unto Him,
and live for ever: for this, He gave his only begotten Son,
that whosoever believeth on Him should not perish, but have everlasting life;
and blessed are they that have not seen,
and yet have believed in the only begotten Son of God.
I trusted that there were many such believers then before me,
who profess to be His followers:
but a bare profession only of Christ would do little for any of us;
nothing short of the possession of the unspeakable gift of His Holy Spirit,
will avail us.
It is no matter under what denomination of religion we are walking before men,
or to what outward and visible body of professing Christians we may belong,
if we are not members of the mystical body,
of which Christ Jesus is the holy Head and
everlasting High Priest,--the church triumphant,
whose names are written in heaven: and there is no other way of attaining to this,
but by and through Christ Jesus,--by receiving Him in the way of his coming.
We must be willing to take His yoke upon us, and learn of Him meekness and lowliness;
we must be willing to submit to the restraining yoke of His Holy Spirit upon us,
and to bring our deeds to its light, which will show us our sins,
and our exceeding sinfulness, and cause us to feel our miserable condition.
As this yoke is patiently abode under, the effect will be godly sorrow unto repentance,
never to be repented of: the glories of eternity will be gradually opened to our view,
and we shall be permitted to behold the blessedness of those,
who have found rest in Jesus.
Our sins will be removed from us as far as the east is from the west,
and blotted out for ever for His sake;
and we shall be numbered among those who have returned, "`and come to Zion,
with songs and everlasting joy upon their heads,`"--ransomed
and redeemed from our sins by the blood of Jesus,
the new and living way, and the only way of initiation into membership,
with those whose names are written in heaven.
Unless we witness this for ourselves,
and know from heart-felt experience Christ Jesus to save us from our sins,
He is no Saviour of ours: and if we die in our sins, where He is, we can never come.

I stood long among them:
and although in the forepart of the time it seemed heavy getting on, yet towards the end,
the life spread over us in an eminent manner, and reigned over all.
The people seemed as if riveted to their seats, instead of rising up and hasting away,
when I sat down.
After this I had to appeal to themselves as
witnesses of the power which prevailed over us.
They still remained stationary after I again sat down,
until informed that the meeting was over.
Such was the renewed goodness and mercy of Him, to His poor unworthy creatures:
but He is "`God over all, blessed for ever.`"
Amen.

25th.--The way seemed now clear for me to direct that the
vessel should be completely furnished with wood and water,
and prepared for sea.
In the evening, I went to Hiram Bingham,
to say that I wished to see the people once again collected; at the same time querying,
whether, if the meeting in the middle of the week was held in the evening,
there would not be a fuller attendance, especially if the occasion was made known.
He immediately proposed,
that as their week-day meeting consisted principally of Church members only,
they should come together as usual on the Fourth day;
and that he would then give notice of a meeting to be held on the Fifth day evening,
at half-past seven o`'clock.
This proposal was gratefully accepted on my part.

On observing the +++_______+++ of Boston preparing for sea,
our mate was dispatched with a parcel of tracts, etc., for the use of the ship`'s company;
when he got upon her deck, the chief mate came forward,
and seeing what he had in his hand, said, '`We do not receive any of those things;
we are all infidels: we do not want any thing connected with the Bible:
but if you will bring us any of the writings of Voltaire, Tom Paine or Rousseau,
we shall thank you for them: give Captain '`s compliments to Mr. Wheeler,
and say we don`'t want any thing of the kind; and if you persist in leaving them,
they shall be thrown overboard.`' Our mate returned on board quite disconcerted,
having never before met with such a reception in the Pacific.
There is great reason to fear that there are many of this description in these parts;
but such an open avowal is rarely to be found.
Upon inquiry, it appeared that no sailors are admitted on board this ship,
but such as deny the existence of an Almighty Being.

26th.--Receiving stone-ballast, to supply the weight of iron, hardware, tin, and nails,
disposed of from time to time.
As soon as our wants were communicated to the government,
without waiting for an arrangement being made by our captain for the stone,
and its transport,
eight canoes of large dimensions were loaded and dispatched to our vessel.
Writing-paper and nails were sent in return for this accommodation,
to the full extent of its value;
it had been previously ascertained that
writing-paper was very scarce with those in authority.

27th.--Until now,
every thing like a present to any of the parties with whom we have been connected,
was studiously avoided on our part,
as gifts often open a door to blindness and perversion;
but the time of our departure being at hand,
several articles likely to be useful were selected and presented to Kinau,
and her associate chiefs,
as a token of esteem and gratitude for the uniform
kindness shown us while in the port of Honolulu;
these were courteously received.
With the assistance of the British Consul,
a pilot well acquainted with all the principal bays, coves,
and creeks of the islands was procured to accompany us.
He could talk a little bad English, was a native of Oahu,
and went by the name of Sugar-Cane.`' Being an elderly man, and very asthmatical,
one of his sons was brought to assist in caring for him,
and to take his share of duty with our crew.

28th.--Felt much depressed at the weight of the
prospect of meeting with the natives in the evening,
as before appointed;
but endeavoured to bear up in humble reliance on the everlasting Arm of strength;
which is magnified in proportion as the creature is laid low,
and made sensible of its helpless condition and utter inability.

Sat down together in the forenoon as usual;
in the afternoon a native schooner through mismanagement ran directly against our vessel.
Serious injury was anticipated on all sides,
but it was so ordered that the violence of the shock was
broken by first one rope giving way and then another,
as the pressure increased; until her stem came in contact with one of our main shrouds,
which made such a powerful resistance before breaking,
as materially to check her progress, when about to strike our hull;
so that the whole damage was comparatively trifling.
Her commander came on board immediately, with tears in his eyes,
in great fear lest any on board of us should have been killed.
This man and his people so fully expected that one or both of the vessels must be sunk,
that he dispatched a man to the shore for boats to save the crews;
this messenger immediately sprung overboard, and swam so quickly,
as to reach the shore before the two vessels began to
show signs that they were not seriously injured.
The spectators could scarcely believe that we had sustained so little harm.

After taking tea at Hiram Bingham`'s we proceeded
to the meeting appointed the preceding evening,
and found a large concourse of people assembled in readiness.
As this was an extra meeting appointed on my account,
the people were informed that it would commence with silent waiting,
and were exhorted to stillness.
Although it is probable more than three thousand persons were present,
and many of them strangers to the practices of Friends;
yet such was the solemn feeling graciously vouchsafed on the occasion,
that the greatest order and quietness prevailed.
However long the interval of silence might seem to others,
to myself it was remarkably short;
before I was strengthened to set forth the necessity of silent
waiting upon God for the sanctifying influence of His Holy Spirit,
to enable us to worship Him acceptably, "`in spirit and in truth.`"
I had also to bear testimony to the all-sufficiency of
that "`grace which bringeth salvation,
and hath appeared unto all men; teaching us that, denying ungodliness and worldly lusts,
we should live soberly, righteously, and godly, in this present world;
looking for that blessed hope,
and the glorious appearing of the great God and our Saviour Jesus Christ,
who gave himself for us, that he might redeem us from all iniquity,
and purify unto himself a peculiar people, zealous of good works.`"
I was enlarged and strengthened to testify the
gospel of this grace of my good and gracious God,
which bringeth salvation, and hath appeared unto all men;
a word of encouragement was strong in my heart to the dear people,
and I had to remind them, that it was not the rich, nor the mighty,
nor the noble to whom the call was limited;
not many of these were called,--nor many that were wise; but the poor,
simple-hearted and unlearned, and fishermen like themselves;
and that they were the people unto whom the call is still extended.
After having sat down awhile,
it was with me to endeavour to make them sensible of the power,
that so eminently reigned over all; recommending them to keep close to it,
and it would be with them for ever; because it is "`the power of an endless life.`"
None attempted to rise up when the meeting was over:
I requested Hiram Bingham to dismiss them, but they still kept their seats,
and the same precious solemnity prevailed.
When we left our seats they began to draw round us to shako hands,
and bid us '`farewell.`' Most of the missionary families were present,
and five of their preachers.

29th. Believing myself clear of the island,
every exertion was made to be in readiness to leave the harbour on the morrow;
and although much impeded by persons coming on board,
we persevered in making the attempt.
Towards noon, Kiuau, the reigning chiefess, sent on board,
to ascertain what supplies we were most in need of; and her husband,
the commander of the fort, seemed a little disappointed,
on finding that hogs and goats were already purchased.
They provided us, however, with eggs, cabbages, water-melons, onions, turkeys, and fowls,
sending them off in good time.
In the afternoon, saw all our accounts settled: drank tea at the Consul`'s,
and called upon the whole of the mission, to take leave of them.

30th.--Made the signal for a pilot, according to the rules of the port,
and at eleven o`'clock a.m., slipped off under easy sail.
The morning had been cloudy and squally, but the trade-wind was now steady,
though strong and scant for our purpose.
The motion of the vessel was soon sufficiently
violent to make almost all on board sea-sick.
For my own part, although not sick, I was otherwise unwell.
Towards evening the wind forsook us, when we had Ranai Point, and the islands of Morakai,
Maui, and Tauroa in sight.
Calm most of the night,
but we had the mortification to find that our vessel
required much pumping to keep her clear of water,
owing to her having been so long in a heated and dry atmosphere,
although almost constantly covered with awnings.

Fifth Month 1st. (First day.)--Early in the morning a strong trade-wind set upon us,
and soon raised a heavy sea.
From the state of the crew and other circumstances,
the usual practice of assembling together was necessarily abandoned;
the vessel still continued to require considerable pumping.

2nd.--Strong gales all the day, with a heavy breaking sea,
which kept our decks in a constant wash,
and rendered it impossible to secure and preserve the
things in the cabin from the salt water.
Towards nightfall, we had an indistinct view of the island of Owhyee, now called Hawaii.

3rd.--Notwithstanding the scantiness of the trade-wind, we had the satisfaction to find,
soon after day-light this morning,
that there was a probability of our fetching into the neighbourhood of Kalakakua Bay.
About three o`'clock p.m., we dropped an anchor in ten fathoms water,
close in with the shore, and near the place where the affray occurred,
in which the British commander, James Cook, was killed.
This bay is exposed to the sweep of the Pacific, from south to west:
but there is a marvellous provision for the safety of vessels which touch here,
and for enabling the natives to procure a plentiful supply of fish.
A sea-breeze sets in almost as regularly as the day revolves;
but before the swell of the sea has time to rise to any material height,
the land-breeze comes off the mountains,
and restores order again upon the ruffled surface: at some seasons of the year, it would,
however, be very unsafe for a vessel to anchor here;
a few hours is generally sufficient for those which do come, to obtain a supply of hogs,
goats, etc.
No canoe came near us for a considerable time after the anchor was down,
and then they came off very sparingly;
but when the first adventurers had had time to return to the shore,
and report that they had been invited on board, and that we had articles for barter,
our deck was presently crowded with almost all ages and sizes, of the male natives,
bringing with them pineapples, pigeons, bananas, ninitas, etc.,
with the different varieties of shells which this part of the coast furnishes.
They remained with us until sun-down, and seemed well satisfied with their visit.
It appeared that it would be best to visit the missionary station without delay,
and to request that a meeting of the islanders might be convened purposely,
without waiting for their usual meeting-day,
as a few yards of cotton print would be an ample reward
for those who took an active part in this business,
for the extra fatigue it would occasion.
By this step a much larger attendance would be secured, besides the saving of time,
which was now particularly important,
as the missionaries were shortly to leave all the stations upon this island,
to attend their annual meeting at Oahu, which holds three weeks or more; and generally,
from one or other circumstance,
nearly two months are required to restore the parties to their respective stations again.

4th.--Our deck was crowded in good time this morning by the natives,
bringing with them abundance of their simple varieties for barter.
In the forenoon we landed, and ascended a steep more than two miles in length,
and by places almost inaccessible.
The great heat of the sun, reflected from a nearly black surface of volcanic rock,
smooth, and glassy, was almost insupportable.
The native boys and girls were very desirous to help me up the hill:
some pulled me forward by the arms, and others pushing behind,
contributed to lessen the fatigue; although this had a ludicrous appearance,
I could not well reject their kindness.
On reaching the mission-house,
we were welcomed in a friendly manner by Cochran Forbes and his wife,
who occupy this secluded habitation.
As the native meeting was to be held in regular course in the afternoon,
it was concluded that notice should be given of
a public meeting to be held to-morrow morning,
for our accommodation, in the hope of collecting a large number of the people together;
but a chief woman who sat by, stated,
that as the king and his large retinue were at Kailua,
(the next station,) the people who were now at home, in their huts,
would be engaged in procuring a supply of food,
and in transporting it to these visitors both tomorrow and the next day also.
On this account it seemed best to hold the meeting this afternoon,
and to take measures to spread the report of our being come to attend it.
A considerable number of the people were collected at the hour appointed,
and in due time my certificates were read, and translated by the missionary;
and after calling their attention to the importance of
the object for which we were assembled,
ability was afforded me to declare the Truth amongst them, fully and freely,
for the space of an hour;
directing them to the light of the Holy Spirit of the Lord Jesus,
which shineth in every heart; which would not only show them their sins, but would,
if taken heed to, save from them, with an everlasting salvation.
That as no sin is committed without the thought of the heart for its origin,
it is the heart that must be watched over;
because every thing that defileth a man cometh from thence.
First of all, before wickedness is committed,
proceed "`evil thoughts,`" and if these are cherished, then sin followeth,
and darkness and death reign; but if the watch is faithfully maintained,
it will lead unto prayer, and that light which is "`the true light,
that lighteth every man that cometh into the world,`"
will make manifest the tendency of every thought,
from what root in us it springs, whether good or evil;
and as we choose the good and refuse the evil,
we shall be strengthened more and more to watch and to pray, even always,
"`with all prayer and supplication in the Spirit,
and watching thereunto with all perseverance;`"--the light will shine
brighter and brighter,--we shall no longer walk in death and darkness,
but shall have "`the light of life.`"
In this way the glad tidings of salvation were proclaimed amongst them in gospel love.
Nothing could exceed the attention and solidity manifested by these Hawaiians,
I humbly trust to the glory of Him who wrought
and crowned the work by his solemnizing presence.
On the left of the ascent to the missionary station,
about half a mile from the rocky margin of the sea,
stands a rough but substantial monument, erected to the memory of the late James Cook,
with the following inscription.
'`In memory of Captain James Cook, R. N.,
who discovered these islands in the year of our Lord 1778;
this humble monument is erected by his fellow-countrymen, in the year 1825.`'

5th.--This morning the natives thronged the deck of our little vessel.
We had agreed to visit the missionary station again this afternoon;
but the violent exertion of yesterday rendered my dear Charles
unfit to risk another such fatigue in the heat of the day;
and I thought it best, in order to prevent suffering myself from the same cause,
to submit to being conveyed upon the shoulders of the people,
in the same manner as they are accustomed to
transport their chiefs on particular occasions.
Having landed by myself, and procured some willing natives,
upon promise of rewarding each of them with some blue cotton print,
I proceeded on my journey.
On reaching a very steep part of the road, and making signs that I wished to walk,
they at length consented to set me down;
but they seemed quite uneasy until permitted to resume their toil.
This I did principally on their account, to make the work lighter;
but I found it very difficult to persuade them to do it a second time at the next steep,
until a determination was manifested to get down,
when I was reluctantly permitted to alight:
they then would not allow me to climb the hill,
without some of them pushing behind to help me along.
I succeeded in getting set down four times:
at last my entreaties were altogether disregarded, and they persisted in hurrying along,
until we reached the missionary door.
My labour was richly rewarded by a truly interesting
opportunity with these newly acquired acquaintances,
whose minds were open to receive all that I found in my heart to communicate to them.
They expressed a desire to understand the principles of our Society,
and inquired if we had any writings of the Society in our possession:
they were satisfied on this head, with a promise of being well supplied,
before we left the Bay.
The evening proved very wet;
but several serious women came and took their stations on the floor in the usual way.

6th.--To-day the natives seemed to bring on board, to all appearance,
all that they possessed, in their eagerness to obtain some of our useful articles:
their poverty and want of clothing are extreme.
I purchased many things from them of no use whatever to myself or the vessel,
rather than send them away empty-handed.
The missionary family came on board about noon, and were furnished with some of our books.
A variety of things calculated to be useful for children`'s wearing apparel, etc.,
were presented at the same time, and gratefully received.
May the Lord direct their hearts into the love of God,
and into the patient waiting for the Lord of life and glory,
until they know him indeed for themselves to be in them, the blessed hope.
After they returned to the shore, the number of natives began to diminish.
In the evening we got all secure to be ready to
avail ourselves of the land-breeze in the night,
to enable us, if permitted, to stretch along the coast towards the Bay of Kailua,
the next missionary station.
Various specimens of native cloth were procured to-day:
even the frames and implements used in making it were brought off,
in the hope of their being accepted in barter.

As the king, Kauikeaouli, has arrived in Kailua Bay,
the body of the people will be necessarily
attracted towards that neighbourhood from hence,
and many of them engaged in keeping up a supply of food and transporting it thither,
for his large establishment;
on which account several hundreds will assemble at the place of worship next First day,
on the occasion of his being there: my mind is bending towards that spot,
in the anticipation of being strengthened to declare
the mercy and goodness of my Lord amongst them;
and it is my soul`'s desire that His heavenly presence may be with us.

At nine o`'clock, p.m., got under weigh with a fresh land breeze,
and stood off from the coast to secure an offing sufficient to
warrant our steering with safety shore-ward in the dark,
clear of all crags.
Heavy rain fell just after leaving the bay of Kalakakua;
but the rising of the moon soon after midnight dispelled every cloud,
and the weather continuing beautifully clear, favoured our design.
About eight o`'clock a.m., on the morning of the 7th instant,
we anchored near the king`'s brig, which, with three native schooners,
was lying in the roads of Kailua.
This anchorage is more exposed to the swells of the ocean than that of Kalakakua,
having twelve points of the compass without a sheltering point of land.
In the forenoon, the resident missionary, Artemas Bishop, came on board,
to welcome us on our arrival; we returned with him to the shore,
and on reaching the mission-station were kindly received by the family.
Here we found a Dr. Gardner, in a declining state of health,
who had been in the employ of the Hudson`'s Bay Company, on the Columbia river,
but had retired in the hope of being benefited by the mildness of the air at Hawaii.
In the afternoon we called at the residence of John Adams, alias Kuakini,
the governor of the island, with whom I became acquainted at Oahu;
but he had not returned from his favourite employment of fishing,
at which he is considered very expert.
On our way back we sat some time on the floor with a chief`'s widow, who was sick.
On the fort established by Tamehameha are yet remaining two enormous idols,
which were formerly worshipped by these people.
They have been evidently cut out of the solid part of two immensely large trees,
and carved into forms hideous and disgusting, and truly gigantic:
and they must have cost excessive labour.
Several pieces of heavy cannon were lying about, with the G. R. upon them,
which could only be viewed with regret.
While together, Artemas Bishop very kindly tendered his services, placing every thing,
as regards the meeting to-morrow, at my disposal,
and declaring his willingness to act as interpreter.

On the passage from Honolulu,
although our little vessel became more leaky
than at any time since leaving New South Wales,
(excepting during the heavy tempest encountered on the voyage from Sydney to
Tahiti,) we were in hopes that the leaks would close up in a few days,
but it was discouraging to find it still necessary to have recourse to our pumps.
Whether the Henry Freeling was more injured than
appeared at the time when the schooner ran into her,
before leaving Honolulu,
or whether the leaking had been occasioned by a seam just above the margin of the copper,
which may have opened from long exposure to the sun in still water, is uncertain;
we cannot, however, take any measure to ascertain this,
until again sheltered from the never-ceasing swells of the Pacific;
but our hope and trust are in the Lord alone.
It was remarked this morning, although riding in about thirteen fathoms water,
that the rocky bottom might be plainly distinguished
intermingled with patches of what was to all appearance hard,
solid, white sand, supposed to have coral underneath:
our anchor had fallen upon one of these white places,
and as it could be seen plainly that the bill had made scarcely any impression,
nor perceptibly sunk, they were thought to be beds of white coral, free from sand.

8th. (First day.)--Reached the shore in good time,
and accompanied the missionary and his family to the meeting;
it was held in a large temporary building close to the seashore, open on all sides,
and widened for the purpose, with rows of pillars on the longest sides,
supporting the thatched roofs of this extra skirting.
Large as it was and well packed, it could not accommodate the people,
and dense bodies were ranged quite without the shelter of the roofs;
but being open on all sides, those without could hear almost as well as those within.
When all seemed gathered, the people were informed by Artemas Bishop,
that if we should remain silent, they were to keep themselves quite still and quiet.
As I have uniformly witnessed the beneficial effects of my certificates being read,
I had previously handed them to the missionary, who read them audibly in English,
as many of our nation were present, and afterwards translated them,
I believe very ably to the islanders, who were very attentive.
A salutation in the love of the everlasting gospel was
in my heart to every individual present,
when I stood up; desiring that the dew of heaven might rest upon them, even unto life,
and that for evermore.
After declaring the fulness of the blessing of the gospel of Christ Jesus,
if they turned to its light and obeyed it, I had to speak of the nature of that true,
spiritual worship, which only is acceptable in the Divine sight.
Vain is the attempt of any to draw nigh unto God in praise and prayer with the lips,
if the heart is not prepared by the Holy Spirit;
pointing out the necessity of our waiting for this preparation, in humble,
reverential silence before Him, who is a Spirit,
and discerneth the thoughts and intents of every heart,
before we can "`worship Him in spirit and in
truth;`" this He requires in this gospel day,
which long since dawned upon benighted man.
It was the travail of my soul that they should all come unto Christ,
who is "`the true light that lighteth every man that cometh into the world;
and is given for God`'s salvation unto the ends of the earth.`"
We had a highly favoured season together,
and the language of "`peace be unto you,`" flowed in my
heart richly towards these dear people.
When the meeting was well gathered, the king and some of his followers came in,
and stayed the whole time, behaving in an orderly manner.
When the meeting broke up,
those with whom we had been previously acquainted at Oahu flocked about us,
and many others followed their example of shaking hands.
Being informed that a bible-class was about to assemble in the same building,
we resumed our seats again:
it was conducted on the system of learning one verse each day, through the week,
the whole to be repeated on the First day of the week.
The children and adults repeated the same words aloud at the same time.
After this, questions were asked by the teacher,
to which all the parties answered with one voice.

Not feeling any warrant to request that the afternoon
meeting should be held exclusively on my account,
it took its usual course, although it did not seem safe for me to omit attending it.
I sat near the missionary, and when the usual services were gone through,
I told him that I wished to say a few words; on standing up,
he rose to be ready to interpret, which arrested the attention of the people.
After a pause,
the way opened for me to declare the necessity
for "`every one that nameth the name of Christ,
to depart from iniquity,`" without which the highest
profession of the Christian religion is in vain;
and that nothing short of the regenerating power of the
Spirit of the Lord Jesus in the heart of man,
can cleanse and purify, and prepare him for that kingdom which shall never have an end.
It is in the heart that sin hath its origin and root; and where the disease is seated,
there the remedy must be applied.
Out of the heart of man proceed "`evil thoughts`" and it is these
that must be watched for and detected in the light of the Holy Spirit.
I stood up in much weakness, but was greatly strengthened,
and largely opened before sitting down, to testify the gospel of the grace of my God,
and to ascribe all to the Lord God and to the Lamb, who sitteth upon the throne;
who loved us, and washed us from sin in his own precious blood, to whom dominion,
and glory, and praise belong for ever.

9th.--This morning Kauikeaouli, the king, came on board,
and fixed to come again in the afternoon to dinner;
this he did to our great satisfaction,
bringing with him a confidential person of respectability.
Every opportunity that could be desired was afforded to put the king in full
possession of our opinion as to the real state of things upon the islands,
and to apprize him of the artful designs of those persons who are
constantly endeavouring to prejudice him against the missionaries,
by raising evil reports against them on every trifling occasion,
under pretence of being his best friends;
while they are at the same time his worst enemies, and those of his people.
They would rejoice to see the missionaries banished from the islands,
the latter being the only persons capable of counteracting
their desire to reduce the people to a state of slavery:
by introducing an extensive growth of sugar-cane,
and permitting the chiefs to share in the profit with them,
they would at once compel the natives to labour for them, or in other words,
to be slaves to their sordid avarice,
while a set of mercenary foreigners would be enriched,
altogether regardless of the waste of life they occasion.
The king listened with great attention, and from the questions he asked,
there is no doubt, but that he thoroughly understood the substance of the whole matter.
Although Kauikeaouli does not speak English with facility,
yet he understands it tolerably well; and the young man who accompanied him,
having had a good education, was able to give every explanation required.

In the evening we drank tea at the mission-house,
where again Kauikeaouli was one of the company.
I sat next to him, but he was now like another person,
and took no interest in any thing that went forward, seeming quite absorbed in thought.
During the day, the natives were bartering their shells, fowls,
and vegetables upon the deck, for our knives, handkerchiefs, needles, and fish-hooks.
The weather was very hot, and the incessant tumbling about of our little vessel,
from the swell of the ocean unceasingly rolling into this exposed bay,
contributed to render it very exhausting and
fatiguing to attend to the wants of the natives;
upon whose well-oiled skins the heat seemed to make no impression.
The number assembled at the meeting yesterday was more than 2000;
but many of them had come from the neighbourhood of Kalakakua Bay.

A large stone building, for a place of worship, is nearly ready for roofing at Kailua:
on my remarking the very great thickness of the walls, I was told,
that unless this was the case it could not stand,
on account of the violent shocks which earthquakes frequently occasion:
at times the tables and chairs rattle on the floors of the missionary dwelling.

10th.--Our deck again crowded with the natives.
The missionary with his wife and two children, accompanied by Kuakini,
the governor of the island, paid us a visit in the forenoon, and stayed dinner on board.
In the evening went on shore;
and seeing nothing to prevent our proceeding to the eastward,
took leave of those we knew, and returned on board after dark.
Preparation being made for sailing, and the landbreeze springing up,
we left the bay of Kailua about midnight, and stretched off under easy canvass,
not having the advantage of moon-light.
In the morning of the 11th instant, the weather clear and hot, with light breezes,
but not from a favourable quarter.
Low in mind, but in the enjoyment of peaceful poverty,
trusting in Him who only knoweth the extent of what is before me.
My desire is, to be found in the way cast up for me, and that I may leave nothing undone,
and no place unvisited where it is His will that the ever-blessed Truth,
by the power of the Holy Spirit, should be proclaimed,
though it be in weakness and in fear, by such an one as myself, frail indeed,
and my days fast numbering to a close:
but the strength of Israel is sufficient for all things required at our hands;
and if we are faithful, I am persuaded, that as our day is, so shall our strength be.

12th.--From the lightness of the wind, and the adverse set of the current,
at sun-set last evening we had nearly drifted to the bay of Kailua.
The wind having freshened and become more favourable,
we are this morning in sight of Towaihai Bay.
In the forenoon we anchored as near the coast as seemed prudent,
with a heavy swell setting into the bay.
With the help of '`Sugar-Cane,`' our pilot,
a native was despatched to the missionary station at Waimea,
with a letter to make arrangements with Dwight Baldwin and Lorenzo Lyons,
the resident missionaries, for collecting the people together as early as might be,
in order to expedite us on our way to Hilo, in Byron`'s Bay,
situated at the southern extremity of the island of Hawaii;
and that our vessel might be no longer exposed than was absolutely needful,
to the risk of encountering, what are called by the islanders, Moomookoo.
These are furious blasts which run between the two lofty mountains,
with irresistible force, turning the surface of the sea into a white foam,
and blowing a vessel entirely away from the coast;
and though perhaps not producing any serious results,
yet it may require several days to get her back
into the place from whence she was driven.
As the distance over the mountains from the coast to Waimea is more than fourteen miles,
the return of our messenger cannot be looked for till to-morrow morning.

On reaching Kalakakua Bay, several days ago, we were informed that the station of Waimea,
near which we now are, was vacant,
the missionaries having sailed away for their annual meeting;
so that there seemed a probability we should have to pass by it:
but at Kairua we learned, that the vessel they were in,
had met with such boisterous weather, that she was compelled to put back again;
and the indisposition of one of the parties prevented
their making a second attempt at that time.
On inquiring of a native this morning through the pilot, this report was found correct;
and that the two families, had again returned to their station at Waimea,
and were now there.
This evening the master of the missionary packet came on board,
and said he was to proceed towards Hilo to-morrow, to bring away the missionaries:
that he was to call here on his return for the two families at Waimea,
and then to call at Kailua for the family resident there;
but that he could not execute the order he had received,
as there were five families at these places, and he had only accommodation for three.
I told him,
that if the missionaries at Waimea could stay to render me the needful assistance here,
I should then proceed immediately to Hilo,
and after I had visited the people of that place,
we would then transport the two families from thence to the island of Maui;
from which place they would have no difficulty in getting to Oahu,
as vessels are frequently passing to and fro between those two islands.
To-morrow it is probable this matter will be decided;
I desire to stand resigned to whatever is the will of my heavenly Father,
believing it will not be required of me to go to any part,
where there is no one capable of interpreting between myself and the natives.
From what we have seen of the people hero in the course of the day,
they appear to be more haughty, and more exorbitant in their demands,
than at either of the two bays we have previously anchored in;
owing perhaps to their having had more intercourse with foreigners,
and more frequent communication with Oahu.

Charles and myself sat down together in the forenoon as heretofore,
and I believe shared together in a long, heavy, lifeless season:
but I humbly trust that I have, in some degree, learned in all states to be content,
and desire to bear cheerfully every dispensation of the Divine Will;
a knowledge of which, when moving along in the counsel thereof,
is at once the strength of my life, and food,
administering consolation and comfort to the wayworn traveller.
