== Chapter XXVIII.

[.chapter-synopsis]
* Waimea
* Native Meeting
* Sail for Koala
* Volcano
* Byron`'s Bay
* Native Meetings
* Sail with the Mission Families for Maui
* Island of Maui
* Anchor at Lahaina
* Proceed to Wairuku
* School
* Meetings at Lahaina
* School
* Sail for Oahu

Fifth Month 13th, 1836.--The messenger dispatched yesterday to Waimea,
returned at an early hour this morning, bringing a letter from Dwight Baldwin,
(with whom we became acquainted when at the Georgian
Islands last year,) which contained a welcome message,
and stated that a horse was sent down for my son Charles,
and a sufficient number of the natives to transport
myself upon a sort of litter to the station;
at the same time informing us,
that a meeting might be held with the people in their district the same evening,
if we left the coast in good time after receiving the letter.
This being ascertained, we hastened to the shore, taking with us '`Sugar-Cane`' the pilot,
who, from his knowledge of the neighbourhood,
could point out a landing place most free from the breaking surf.
Having accomplished our purpose in safety,
we soon found the natives who had been engaged as burden-bearers,
and there seemed every probability of our setting forward without delay;
but when all seemed ready and I had taken my seat,
some demur began to show itself on the part of the natives; and we began to discover,
that nothing would satisfy them but the sight of the cloth,
which they were to have as payment,
and a knowledge of the quantity that each man was to receive for his labour.
Supposing that these matters had been fully arranged
for us by the missionaries as had been requested,
we were quite unprepared to answer this demand; and as far as we could understand,
the parties were determined not to proceed, without it was complied with:
as the affair could not be adjusted, I left my seat again,
expecting to have to return on board.
A number of the natives by this time gathered round us,
and amongst them was an American sailor;
and finding that he understood a little of the language,
I requested him to inquire whether any other
persons then about us would undertake the work.
After much debate some consented,
and being informed that whatever the missionaries decided upon as their wages,
they should be fully paid, a sufficient number came forward,
and we soon began to move on in earnest.
The sun by this time had become very hot, and the journey altogether extremely fatiguing,
from the road passing over mountain after mountain with
continual ascent nearly the whole distance of fourteen miles.
I was desirous to lessen the labour of the people as much as was in my power;
and walked perhaps more than was prudent for a stranger in such a climate at noon day.
It was late in the afternoon when we arrived at Waimea;
and on reaching the mission-house were kindly received by Lorenzo Lyons,
and Dwight Baldwin and their families.

Feeling much exhausted with the heat and the harassing journey,
I should have rejoiced if the meeting had been appointed for the next morning:
but found on inquiry, that the people would soon begin to collect,
and that if postponed until to-morrow, but few persons would be able to attend,
as they would necessarily be widely scattered in
collecting food for the First day of the week,
so that they might have nothing to prevent their attending the places of worship.
I was informed, that on First day the meeting would be larger if the weather proved fine;
but if wet, the people would not come.
These things considered, it seemed best to take the opportunity which now presented,
rather than by delay to run the risk of faring worse,
or perhaps losing my labour altogether.
After some refreshment we repaired to the meeting,
which proved quite as large as was expected.
The senior missionary thought it unnecessary to do more
than explain the nature of my certificates,
and this in a brief manner; but perhaps sufficient for the understanding of the people.
When he had finished, I stood up in great weakness,
desiring that we might endeavour to draw nigh unto the Lord in humble reverence of soul.
The people were very solid and attentive;
and although I do not remember having felt less ability to minister,
or having less matter in prospect, as I proceeded,
strength sufficient was mercifully and timely afforded,
to endeavour to turn them from darkness to the light of the Holy Spirit of the Lord
Jesus in their own hearts,--that they might know Him to be a Saviour indeed,
to save them from their sins; that so He might be theirs, and they might be His,
through the never-ending ages of eternity: it is He who bringeth unto God the Father,
and raiseth up at the last day.
I stood long among them, and though to myself the life never seemed to rise and spread,
as at some favoured seasons,
and my own exhausted state of body was sensibly felt,--yet I afterwards found,
from the testimony of others,
that the power of the blessed Truth had been felt amongst them:
let the Lord be glorified and let them rejoice:
but the feelings and the sentence of the unprofitable servant most certainly were mine.

Spent an agreeable evening with the two families.
From the vast quantity of rain which falls on this side the island of Hawaii,
the dampness of every thing in and about the houses is extreme:
the bed we lay on would have been very justly considered in England,
not fit for those who have any regard for their health, but we had no alternative;
and after using all the means we possessed to prevent being injured,
we were favoured to witness no ill effects in the morning,
though our clothing was as if it had been hung in the midst of steam during the night.
We were, however,
glad to see the light of the returning morning to
liberate us from the consequences which threatened.

14th.--Being desirous of returning to the coast as soon as circumstances would allow,
we rose early in the morning,
and after breakfast it was concluded by the missionaries (who had the
direction of the movements of the Missionary Packet,) that instead of
proceeding round the southern part of the island to Byron`'s Bay,
where Hilo is situated, she should sail immediately for Kairua and Kalakakua Bays,
and return with the mission families from those stations back again to Kowaihai Bay;
when, if the two families residing here were ready,
they would accompany their brethren to the island of Oahu,
to be in readiness for the approaching annual
meeting of the whole mission about to take place.
By this measure, the missionary families at Hilo were left entirely at our disposal,
which at once removed every doubt of being able to speak to the people.
How bountifully are we dealt with by Him,
who "`openeth His hand and satisfieth the desire of every living thing.`"
At nine a.m., taking leave of Waimea, we made the best of our way to the coast,
expecting to put to sea the same evening; but the night proving rainy and rough,
it seemed best for us to remain under the shelter at present
afforded by the projecting land in the neighbourhood of Koala.

15th. (First day.)--From the state of the weather,
it is probable if we had remained at Waimea,
but few of the people would have attended the meeting to-day.
Twice in the course of the day our seamen were assembled for devotional purposes,
as we had no communication with the shore;
although I thought if an interpreter had been present some of
the straggling natives might have been collected together.
At sun-down got under weigh, and proceeded towards Koala with a light breeze;
but on opening the mouth of the passage, between the islands,
we found plenty of wind and sea.
We stretched off the land until two o`'clock in the morning,
and then stood towards Hawaii again, under double-reefed canvass,
anticipating that before we could possibly reach any of its stupendous crags,
the day would have sufficiently dawned to expose them to our view.

16th.--Employed through the day endeavouring to beat through
the passage formed by the islands of Hawaii and Maui,
about twenty miles wide, with rough blowing weather,
and the trade-wind directly opposed to our course.
Maintained a central position between the islands during the night;
but gained very little ground.

17th.--Early in the morning stood in for Hawaii,--the weather rainy through the day;
at six o`'clock P M., stood off again for the night.
Torrents of rain appeared to be falling all the day upon the mountains of Hawaii:
twenty-six different cascades were counted at one time
rushing towards the ocean down the rocky cliffs:
every part of the island which we have seen seems to
consist of huge masses of volcanic substance,
and the leeward side is truly dreary and barren in appearance.

18th.--After beating to and fro through the night, the weather became more gentle;
but the wind was so fickle that there seemed no probability of
our rounding the point that forms one side of Byron`'s Bay,
at the bottom of which stands the village and missionary station of Hilo.
In the course of the day, made several advantageous tacks close in with the shore,
there being no appearance of broken water on the margin of the coast.
The weather proved much more bright and favourable than we had anticipated:
we heard a well attested fact related by a missionary
who had formerly dwelt some years at Hilo,
that while residing at that station there were only six
days wholly without rain during the space of two years,
as by record duly kept of the weather.
Fifty-six cascades of water pouring off the land
into the sea were in sight at noon to-day.

This evening, whilst under feeling of poverty and weakness,
I was reminded that this day the Yearly Meeting of Friends at large sat down in London.
This brought afresh my dear brethren and sisters,
who are endeavouring to do the will of our heavenly Father,
very near to me in the covenant of life and peace;
and a belief that we ourselves shall not be forgotten
by some who compose that large assembly,
when drawing nigh in spirit to the footstool of mercy and love,
is very precious and animating,
though removed from them almost as far as the east is from the west.
But although thus outwardly severed from each other,
we have a never-failing source of comfort and consolation, in knowing,
that the one great and heavenly Parent of the universe
is equally near unto us all,--that in Him we live,
and move, and have our being,--and that His tender mercy is over all His works;
of which my only earthly treasure, and my all on the solitary Plains of Shoosharry,
form a part.
May the blessing of the Most High be felt, through the power of the Holy Spirit,
to rest richly upon us all; then shall we be in that glorious unity,
which inherits life and that for evermore; from which nothing can separate,
because it is in the love of God, in Christ Jesus our Lord.^
footnote:[Having had of late a number of letters handed to us
by way of introduction from one missionary to another,
in order to procure the needful aid from station to station,
I have thought it might afford satisfaction to others,
to know how we stood in their estimation,
after having sojourned nearly five months within their borders on the Sandwich Isles.
As they are all of the same tenor, a copy of one may suffice for the whole.]

19th.--Towards midnight, the flashes from the great volcano illumined the atmosphere,
and at times had the appearance of a stationary light on that part of the coast.
At three o`'clock a.m., it visibly spread and increased its light;
but was eventually lost sight of in the beams of returning morning.
Having made a successful in-shore slant during the night,
at breakfast-time weathered the northernmost point,
and edged away for Byron`'s Bay,--the wind now shifting more and more in our favour.
At half-past two o`'clock p.m., dropped an anchor in seven fathoms water,
behind a small reef,
which affords a good shelter from the swell occasioned by the usual trade-wind,
which though constantly blowing in during the day,
through the wonderful provision of an all-wise Providence,
never is permitted to blow hard for at least nine months out of the twelve,
which seasons are pretty well ascertained.
During the intervals of unsettled weather,
no vessel would be warranted in attempting to seek shelter here.
In the afternoon, a double canoe came off from the shore,
and returned again loaded with stores,
which our vessel had received from the Missionary Packet at Kowaihai Bay,
and collected at other places since leaving Oahu.
Taking our pilot '`Sugar-Cane`' for a guide to
that part of the strand the most free from surf,
Charles and myself landed and made our way towards the mission-house,
meeting with David B. Lyman and Titus Coan before reaching their abode.
Both the families assembled at David B. Lyman`'s, where we partook of some refreshment.

20th.--This morning the principal chief and his wife came on board to breakfast,
and stayed our reading.
This chief is descended from the late Tamehameha, and certainly,
if bulk and weight can add dignity to high birth,
his wife must also be a first-rate personage; and we are told,
that her rank is considerably higher than that of her husband.
On leaving us,
she very uncourteously took to herself the power
of proclaiming the Henry Freeling under Tabu,
when the natives who had come on board with shells, eggs, etc. to barter,
immediately sprung into their canoes, and pushed off from the vessel.
Through the medium of Sugar-Cane,`' we were made to understand that all
traffic could now only be carried on at a sort of market upon the shore.
On inquiry made afterwards,
it appeared that this woman had not the power of preventing the natives from trading;
and that she had ventured to usurp this authority,
in the hope of monopolizing the whole traffic herself.
It happened, however, that we were not in want of many supplies,
as we were not intending to recruit our stock of fuel at this island,
on account of the extra risk to the vessel which
delay might incur in such an exposed roadstead.
In the afternoon David B. Lyman and Titus Coan came on board;
we returned with them to the shore, and after a walk to an old crater not far distant,
took tea at Titus Coan`'s, where the other family joined us.
At nine o`'clock in the evening,
the flames of the volcano gave the atmosphere an unusually bright tinge of light.

21st.--This morning the circumstance of the vessel being '`Tabued,`'
was fully ascertained to be enforced with a view to
exclude the natives from a share in the traffic,
and no other than an unauthorized violation of their privileges; against which,
we thought it right to make a stand.
A person who could speak a little English came on board at an early hour,
with a present of a fowl and some potatoes from the chiefess.
I told him it was a pity she had been at the trouble of sending them off,
as presents were things we did not accept,
and therefore must pay for what he had brought with him.
This man was told to inform us, that if we accepted the present,
it would be considered that the chiefess was entitled
to furnish what supplies might be wanted;
but if these terms were not acceded to, and the present was declined,
he was then to return to the shore to know its value,
and the price was to be sent off by a native then upon the deck, who was pointed out,
that he might be known again by us;
word was soon brought that the price was a quarter dollar, which was paid forthwith,
to preserve peace and put an end to the matter.
The man who brought off the present was highly
gratified at our declining the terms altogether;
and there is no doubt but the affair soon gained publicity,
as canoes kept coming through the day with fowls, turkeys, cabbages, bread-fruit,
pine-apples, watermelons, etc., in an undisguised manner.
We afterwards fully ascertained that this arbitrary
proceeding was a violation of the laws of the island,
no person whatever, but the governor John Adams, alias Kuakini,
having the power of interfering with the traffic carried on by the inhabitants;
yet such is the servile state of these poor people,
having been trained from infancy to view their chiefs
as a race of beings superior to themselves,
that they would patiently have borne this act of oppression,
if it had met with our sanction.

Drank tea at David B. Lyman`'s,
who has kindly undertaken to accept the office of
interpreter between myself and the people to-morrow.
Notwithstanding I have now stood before so many
thousands of these islanders on both sides the Equator;
yet the prospect of to-morrow is formidable in my sight.
If the weakness of human nature was not thus felt, there would, I believe,
be a danger of our not sufficiently and devotedly seeking after,
and imploring the strengthening influence of that power,
without which "`we can do nothing,`" but with it all things.
May the Lord be our helper, and cause his own works to praise Him,
to the glory of the riches of that grace, which came by Jesus Christ.

22nd. (First day.)--This morning I felt as has uniformly been the case,
when about to meet for the first time a large body of the people at a fresh place;
but I was comforted from believing that we should be
remembered by some at a time and "`place where prayer is wont
to be made;`" where the Lord is in the purified temple,
the earthly nature silent, and the heavenly Intercessor`'s only availing help experienced.
Attended the meeting at the time fixed: sat as one that had lost all strength,
until David B. Lyman had nearly finished reading the Morning Meeting`'s certificate,
when I seemed ready,
and only waiting the termination of the concluding paragraph to stand upon my feet,
with my mind centred and the fear of man banished far away.
After the people were requested to settle down in stillness,
and endeavour to draw nigh unto the Lord with humble reverence,
I was strengthened to declare amongst them the way of life and salvation,
in the word of the truth of the gospel,
in the love of which my heart was greatly enlarged.
Repentance toward God, and faith toward our Lord Jesus Christ,
the only way to obtain forgiveness of sins that are past,
and freedom from the thraldom of sin in future, were largely pointed out,
and the light of the Holy Spirit of Christ Jesus, which shineth in every heart,
as the only blessed medium by which this path is made manifest;
by reason of the darkness which prevaileth in man, while held in a carnal,
and unregenerate state, in bondage to the power of Satan, the prince of darkness.
The burthen which rested upon my mind was,
that they might be delivered from the power of darkness,
and translated into the kingdom of the dear Son of God,
through the shedding of whose precious blood our redemption is sealed,
even forgiveness and remission of sins that are past,
and an interest mercifully granted in that Holy Advocate,
always present to plead with our heavenly Father,
the weakness and infirmity of our nature, for the time to come, for all those who,
in belief and obedience, are willing to come unto God by Him.
Such, and such only, are turned "`from darkness to light,
and from the power of Satan unto God.`"

The meeting was not so large, we were told, as at some other times;
but the people were very attentive,
and bowed down under the mighty hand of Him whose power reigned over all.
After the meeting broke up, we attended a Sabbath school for Bible scholars,
of all ages and both sexes.
It commenced with a prayer by a native teacher,
and finished with another from one of the missionaries.

We partook of some dinner with Titus Coan and wife,
as I felt an engagement to attend the native meeting again in the afternoon.
It began at three o`'clock,
and I had again to testify of the gospel of grace and truth which came by Jesus Christ,
from which, such is the universal love of God, none are excluded.

23rd.--By a canoe that came paddling round the vessel,
it was ascertained that the tabu was still enforced; and the natives,
though invited on board, thought it safest to keep aloof.
Before noon a person was sent to inform us that
sundry articles were in the market for sale;
but as they belonged to the chiefess as before,
he was told that nothing would be purchased belonging to her,
at the same time it was stated, that if the natives had anything to sell,
we would buy from them what was wanting.
In the afternoon landed, and visited a magnificent and stupendous waterfall,
called the '`Cascade of the Rainbow.`' The sun was hot and the walk fatiguing;
but the exercise was needful before again putting to sea,
as from the wetness of the weather since anchoring in
the bay but little had been obtained.
We passed by three distinct craters, situated in a line stretching inland from the shore,
apparently at exact distances from each other,
and the same size and shape in every particular,
all declaring the wonderful works of the same Almighty power.
The cascade of the rainbow exceeds the description given of it,
and at once excites wonder and admiration,
exhibiting a mighty torrent of foaming water in perpetual roar,
rushing down a perpendicular steep of more than one hundred feet into
a basin of sufficient magnitude to receive this never-ceasing deluge.
At the back of the fall, towards the bottom,
a large arch is formed probably by the rushing torrent;
and the enormous weight of water falling such a depth,
caused a mist to arise two-thirds of the whole height of the surrounding cliffs,
which with the sun in a certain position, gives rise to the name of the cascade,
by displaying a beautiful rainbow.
While Charles was taking a sketch of the outline of this sublime spectacle,
I placed myself on a stone in its front, surrounded by nine of the natives,
who seemed not fully satisfied without being so near as to touch me occasionally.
One of the oldest of them took no small pains to make me understand that in former days,
when there was plenty, plenty of water,
(probably after great rain) little native children were hurled by their
parents into this rainbowed gulph to check the increase of population.
Afterwards, on mentioning to the missionary, Titus Coan,
what I supposed this native meant,
describing as well as I could some of his actions and words, he said,
that the construction I had put upon them was correct.

Not feeling any thing to detain me further upon this island,
we look forward to leave this interesting bay to-morrow night,
when the land-breeze comes off the mountains, for the island of Maui,
and expect to take with us the two missionary families
so far on their way to the annual meeting at Oahu:
they will probably escape a portion of sea-sickness by
not coming on board until near the time of sailing,
as the motion of our vessel is incessant, from the constant swell of the ocean,
which ranges round the reef into the bay.
It compels us to keep every thing secure nearly as much as at sea.

24th.--To-day procured what supplies were needed.
In the afternoon took exercise on shore,
and towards sun-setting the baggage was embarked in a double canoe, which,
with the assistance of our boat brought off both the
families and ourselves with two native servants.
About eight o`'clock p.m., the mountain breeze sprung up,
when the vessel was got under weigh, but the wind soon became lighter,
and the great wash of water off the land and out of the rivers,
combined to sweep us towards the reef:
before ten o`'clock the water began to grow shallow,
and diminishing from ten to three fathoms, obliged us to anchor for the night.
The hollow ground swell upon the edge of the reef caused violent and constant rolling,
without a possibility of preventing it in that position.

25th.--Soon after eight o`'clock a.m., the sea-breeze made its appearance,
but before setting in, a canoe came paddling off in great haste to reach the vessel,
with a couple who were desirous of being married
before the departure of the missionaries;
but having neglected to obtain the permission of the principal chiefess,
this could not be accomplished.
There was no alternative but that of returning again to the shore about three miles off,
to obtain the needful sanction;
and having been told that we should not wait for
them if the wind should spring up in our favour,
they paddled off again with all the speed in their power.
Before the wind was strong enough to warrant the risk
of getting under weigh and clearing the reef,
this canoe was seen again returning to the vessel from the shore.
They would gladly have been married in their canoe,
but the motion was so violent that the parties could not possibly
stand upright while the missionary performed the usual ceremony.
They were then taken on board, and to make it easy to both parties,
were brought down into the cabin,
where the rite was performed by one of the missionaries
demanding answers to several important questions;
the other offering up a prayer.
The captain, mate, and ourselves, were witnesses of this curious exhibition,
the vessel rolling about in such a manner that they were
forced to hold themselves by the table and each other,
when they stood upon their feet:
they were both so drenched by the sea that had washed into the canoe,
that measures were necessary to clear the cabin floor from the quantity of water on it,
after the ceremony was concluded.
The husband was clothed in a European shirt, with a belt round him;
and his wife in a loose cotton robe, reaching nearly to the floor,
which comprised the whole attire of the parties.
I felt a degree of satisfaction at what had transpired, and to myself,
our detention last evening was accounted for.
Nothing short of a fear let in by some on board, of losing the vessel upon the reef,
would have induced a willingness to anchor for the night to
avoid the apparent danger that seemed to threaten.
On looking over all the circumstances of the case,
there seemed a providence in it that these poor people might be saved the
temptation of violating the laws of their country by an illegal procedure,
without waiting the return of the missionaries, which might be most of two months.
A marriage thus consummated upon the mighty waters, is not an every-day transaction,
and especially, as I humbly trust it may be said, in a place of worship,
which the cabin of the Henry Freeling has been in many instances,
as well as a place of prayer and praise; from whence the spiritual sacrifice has,
we hope, at times acceptably ascended unto God through Jesus Christ,
though we be as nothing in his sight, and in our own,
utterly unworthy of the least of all his tender mercies.
As soon as the married couple had left the vessel, we at once made sail,
with a delightful breeze in our favour, for the island of Maui.

We witnessed last evening a scene, in the embarkation of the two missionary families,
both affecting and highly interesting.
When the moment for their leaving their habitations approached,
the natives crowded into their houses to take leave of them;
and as the train proceeded towards the beach, the company increased to a large number,
perhaps hundreds.
When arrived at the edge of the cliff, there was a solemn pause,
and a prayer was eventually offered up by D. B. Lyman; after which,
the final separation took place.
The people seemed to consider us also as friends about to leave them,
and extended their good wishes, shaking hands very freely as we retired to the boat.
Some of them assisted us to launch into the surf, and I have no hesitation in believing,
that they would have risked their own lives to save ours.
How different their present state to what it was,
when these shores were visited by the first navigators of the Pacific:
but what might the situation of these simple hearted natives have been at this day,
if only men of Christian principles had trod their soil,
instead of the wicked and barbarous crews of the shipping;
who have committed every possible excess and outrage, shameful and brutal,
upon these helpless islanders, to the lasting disgrace and infamy of the white skin.

Before leaving England, I was applied to by our mutual friend Thomas Bigg,
to make inquiry, should opportunity present,
for an Englishman supposed to reside on the island of Hawaii;
and a letter from his poor mother was committed to my care for him.
It appears that the individual in question lived in the neighbourhood of Kalakakua Bay,
and obtained a livelihood as a pilot to the vessels,
which occasionally come to that side of the island for supplies.
He died in the fall of 1832, leaving a native widow and two children, who,
I should suppose, were afterwards supported by her relations.
The youngest child died last year, and the eldest has since been carried off, say stolen,
by the captain of an American whaler,
who pretended to have received orders from the god-parents (so
called) to bring these children to them in America.
It is probable that this impostor was aware of the lad`'s abilities;
and that by this fabricated tale he might be obtained without any cost,
now that he had lost his father.
In this manner was this poor helpless boy torn away,
in spite of his tears and entreaties to remain with his mother,
under pretence of being provided for much better in America, than would be the case here.
The whaler has never returned to this neighbourhood since the theft was committed.
This account has been principally given me by one of the missionaries;
and I cannot for a moment doubt that it is substantially correct.
The injured native mother is now removed by death,
beyond the reach of the monsters who perpetrate
these horrible deeds of cruelty and injustice;
but their day will also come, and will not tarry.

26th.--In hauling round the point of the island, the wind became light;
but a fresh breeze springing up from the southwest,
enabled us to stem the current and reach the roads of Lahaina, soon after twelve o`'clock;
we anchored near the American ship Newark,
a whaling vessel put in for fresh provisions and vegetables.
The smooth water having recruited our passengers, the men went on shore,
but soon returned, bringing with them the resident missionary, William Richards.
The captain of the whaler coming on board at the same time,
kindly made the offer of his boat, which conveyed all our passengers on shore at once,
with ease.
In the afternoon Charles and myself landed,
and remained at the mission-house until sun-down.
It appeared that William Richards and family had intended to
leave Lahaina on the evening of the following day for Oahu,
in a small schooner lying near at hand;
this being the only opportunity likely to offer for their
conveyance to that island in time for their annual meeting.
Although I had not disclosed what was upon my mind to any one:
yet I had long believed that I should not be clear of the Sandwich Islands,
without making an attempt to see the whole of the missionary families,
when collected together for their annual meeting at Oahu;
and it now sprung in my heart to tell William Richards,
that if he would consent to remain at Lahaina,
and assist me over the approaching First day,
I should feel myself bound to convey himself and family,
in time for their meeting at Oahu if practicable, in the Henry Freeling.
These terms being accepted,
it was with me to inquire whether the missionary at the station of Wairuku,
on the south side of the island, had sailed for Oahu;
and finding there was considerable probability of his being still at his post,
it seemed best to make the necessary arrangements for proceeding thither without delay.
A messenger was forthwith dispatched with a letter,
requesting that the inhabitants of that district might
be collected tomorrow at the place of worship,
as early in the day as could conveniently be done.
A whale-boat was procured from the governor Opeli,
as the conveyance best calculated to accomplish our object,
in contending with the wind and weather in rounding one point of the island,
where strong blasts prevail from the set of the trade-winds,
during the greatest part of the year.

27th.--By two o`'clock a.m., the whale-boat manned with a native crew came alongside;
and at the cock-crowing as agreed upon by all parties,
we left the vessel properly equipped for the journey.
The morning was serene and beautiful, and when the day broke the wind began to rise,
and to increase as the day advanced.
On reaching the most critical point, the wind was so strong and the water so rough,
that for a time it seemed doubtful whether the strength of our rowers would hold out:
they succeeded however in getting under the shelter of the coast;
but not without all of us being well drenched by the spray of the sea.
By eight o`'clock, we reached the boundary aimed at,
beyond which the boat was of no further service; here we landed and hauled it up;
and the men corded the oars to a chair we had purposely brought with us.
I was thus speedily furnished with a land conveyance,
and Charles being provided with a horse, we pursued our route towards Wairuku,
about eight miles distant; he on horseback, and I riding and walking alternately,
for the relief of my bearers, as well as for a change of position.
We got to our destination about noon, and were kindly received by the missionary family.
While some refreshment was preparing, we visited the school,
consisting of a large number of children of both sexes.
The meeting gathered at three o`'clock,
which we attended accordingly,--myself in much weariness and emptiness;
but I was strengthened to stand up shortly after the reading of my certificates,
and remind the people that we were in the presence of
the Most High God of heaven and earth;
before whom "`the nations are as a drop of a bucket:
He taketh up the isles as a very little thing.`"
He not only seeth all our actions,
but knoweth the most inward thoughts and imaginations of every heart.
I was carried forward to unusual length,
and without any prospect of drawing to a conclusion;
the blessed truths of the gospel unfolding in continued
succession to the view of my mind for about an hour and a-half:
I afterwards found that the meeting had kept increasing, far beyond what was anticipated.
It was to me a very memorable season, the Lord`'s power was over all;
and I humbly trust His name was honoured and exalted,
and the kingdom within proclaimed to the dear Redeemer`'s praise.
The desire of my heart was,
that the gospel message might be "`glad tidings`"
indeed--"`of great joy`" to these people,
through "`repentance toward God,
and faith toward our Lord Jesus Christ,`" wrought by believing
in the appearance of His Holy Spirit in the heart,
and by the operation thereof cleansing and purifying
from every thing that is offensive in the Divine sight:
that thus they might be made meet to be partakers of an
inheritance with the saints in light,
in the everlasting kingdom.
My mind felt peaceful and refreshed,
and the fatigue of the journey was remembered no more.

We had to shake hands with a large body of the natives
between the meeting-house and the missionary`'s dwelling.
After spending some time with the family, and the night drawing on,
we were compelled to renew our travel towards the place
where the boat had been left in the morning;
and though it soon became dark after leaving Wairuku,
we succeeded in getting to the right spot.
After the people had rested themselves, the boat was launched,
and we were favoured to reach our little vessel
about half-past one o`'clock in the morning.
It was to me a memorable day of goodness and mercy, and the more so,
as it was the anniversary of my dear William`'s birth,
which kindled in my heart towards our heavenly Father,
renewed desires for the welfare of my precious family.

28th.--Engaged on board until afternoon,
then landed and arranged with the missionary to meet the people,
at nine o`'clock on the following morning; at the prospect of which,
I felt as a worm and no man: but whither could I look for help, but unto Him,
who hath so often covered my head in the day of battle, for His great name`'s sake.

29th. (First day.)--Got some rest in the night;
but was awakened early by the remembrance of the
great weight of responsibility resting upon me;
but the voice of my supplication was heard,
and my prayer was not permitted to return again into my bosom in the hour of trouble.
At this place we found a noble meeting-house, teeming full of people,
both in the galleries and upon the ground-floor, more in number than two thousand,
according to the missionary`'s statement:
the will of the creature was laid low as in the dust;
but I felt the comforting influence of that power,
whose "`strength is made perfect in weakness,`" to be nigh,
though the earth trembleth and shaketh at the presence thereof.
Though a stranger to the language of these people,
I was sensible that my kind and willing interpreter took more
than ordinary pains to impress their minds with a belief,
that I had brought with me well attested letters of recommendation;
and as the name of William Ellis was well known and remembered among them,
he took care to state that I had a letter from him also, among others;
his competent knowledge and fluent expression of the language,
while it at once commanded attention, raised a degree of confidence,
both in them and myself, which was of a strengthening tendency.

On standing up I told them, although for the most part we were strangers to each other,
yet we were all of one blood and members of the same great human family,
and in the presence of the Almighty and everlasting Parent of the universe,
"`who seeth not as man seeth; for man looketh on the outward appearance,
but the Lord looketh on the heart:`"--pointing out the necessity of
our endeavouring to get into an humble waiting frame of mind,
and be still; that His power might be known and magnified,
and felt as a crown of solemnity over us:--that I had come amongst them in
the love of the gospel,--that same love of which the great apostle spoke,
when he said, "`the love of Christ constraineth us; because we thus judge,
that if one died for all, then were all dead: and that He died for all,
that they which live should not henceforth live unto themselves,
but unto Him which died for them, and rose again.`"
Strong desires were raised in me and expressed,
that these people might be brought to an acquaintance with the Holy Spirit of Him,
who thus "`gave his life a ransom for many.`"

I had to lay open some of their besetting sins as a people,
and to point out the only way for their deliverance from the
power of darkness by which they are bound,--which is,
to believe in the light of Christ Jesus, which shineth in every heart;
for this indeed is He, who by His Holy Spirit, speaketh unto them,
and telleth them all things that ever they did;--who convinceth the world of sin,
and by His light makes manifest every evil deed, every evil thought and word,
and leadeth man to repentance, whereby he is strengthened to forsake sin,
and to live unto Him, who died for us and rose again.
It was with me to tell them, that the day of their visitation was come;
and that salvation by Jesus Christ was freely offered to them who believe and receive it,
and who open the door of their hearts that the
King of glory by His Holy Spirit may enter in.
Ability was richly afforded to exhort, warn,
encourage and beseech them to turn from darkness tothat light,
which would show them their sins, and bring them unto God the Father;
and which would raise them up at the last day,
to an inheritance with those that are sanctified
by the like precious faith in His beloved Son.
It was indeed a high day, a day of light and joy and gladness of heart,
as when the Bridegroom`'s voice is heard.
The meeting held long; and when over,
we were invited to attend an English service to be conducted by Titus Coan;
which I was most easy to decline, and return forthwith on board the Henry Freeling,
to collect our own sailors.
Some of the seamen of the American whaler were present,
and my mouth was again opened to speak of the way of life and salvation by Christ Jesus,
to this little gathering.

Soon after three o`'clock p.m., we again returned to the shore,
to attend the afternoon native meeting.
Not more than half the number of the people were present who had assembled in the morning.
I had again to minister unto them;
but the current of life was weak in comparison to what
had flowed so freely and strongly in the first meeting.
The "`gospel of the kingdom,`" was again declared to them;
and I trust the great name was magnified, by the praises of His own works, to His glory.
After taking some tea at the mission-house, we again removed to our vessel for the night,
as to myself, under the feelings of the unprofitable servant,
being lamentably deficient in too many instances,
and in having done that which was my duty to do.
Blessed be the Lord God, the God of Israel, who only doeth wondrous things:
and blessed be his glorious name for ever;
and let the whole earth be filled with his glory; Amen, and Amen.

30th.--In the forenoon landed to purchase fruit, vegetables, etc.,
in the market appointed for the sale of these articles.
Made a present of a small sized telescope to governor Opeli.
William Richards having kindly furnished a light waggon,
Charles and myself proceeded to Lahaina Luna, where the high-school is established;
we were kindly received by the principals of this institution, who are missionaries;
and specimens of the books which have been printed here, charts of the Sandwich Islands,
and a general atlas, (the plates which these were taken from,
being the work of the native scholars at this school,) were presented to us.
The buildings were undergoing alterations and repairs during the vacation,
on which account the scholars had been dismissed some days previous to our arrival.
Returned on board soon after noon,
but had some difficulty in getting safely through the surf,
which had greatly increased since the morning,
owing perhaps to its being about high tide.
At four o`'clock p.m., the missionary families came on board,
consisting of William Richards and wife, with eight children, David B. Lyman and wife,
and two children, Titus Coan and wife,
and an unmarried female in the employ of the mission, who, with the native servants,
and their wives, and young children, amounted to twenty-three in number:
the whale-boats of the American ship were procured for their embarkation.
At five o`'clock the Henry Freeling left the island of Maui;
after reaching the Morakai channel, the breeze forsook us,
and we were left to tumble about all the night in a heavy swell.
Nearly the whole of our passengers were sea-sick;
several of the females had with them sofa-beds, which were fixed upon the deck,
and in which they remained the greatest part of the time they were on board.

31st.--Having the advantage of a fine trade-wind in the course of the day,
about five o`'clock p.m. we anchored outside the reefs at Oahu in ten fathoms water.
Having previously announced by a white flag at the mast-head, when passing Diamond Hill,
that missionaries were on board,
a fine doublecanoe belonging to the king soon reached the vessel,
sufficiently large to convey all our passengers to the shore at once, with their luggage,
besides a number of the natives who worked the paddles,
and had been employed on the occasion.
Just after the canoe left,
a shark from eight to nine feet in length was taken by our sailors;
a large portion of which was sent on shore by the pilot,
'`Sugar-Cane,`' for the use of his family.
These islanders are so fond of the flesh of the shark,
that it will always fetch a high price in the Oahu market, when offered for sale.
