== Chapter XXXI.

[.chapter-synopsis]
* Vavau
* Wesleyan Missionaries
* Native Meetings at Neiafu, Feletoa, and Haalaufuli
* Appointed Meeting for Seamen
* Visit to the Island of Otea
* Meetings At Hihifo
* At Matika
* Embarkation of the Mission Families
* Sail for Lifuka

Vavau, Eighth Month 18th.--This morning the natives began early to visit us,
flocking on board with their simple articles of shells for barter.
Although we usually hold our little meeting on this day of the week,
yet the unsettled state of our affairs compelled us to relinquish the attempt,
from the confusion around us, produced by the novelty of our vessel,
and the unfitness of our own minds.
At noon, left the vessel in quest of the missionary station.
On reaching the head of the bay,
two missionaries were observed coming towards us in a canoe;
and on seeing our boat they returned again to the shore,
to point out the most suitable place for landing,
and to conduct us to the settlement at Neiafu.
These were Stephen Rabone and John Spinney, who had lately arrived from England,
via Sydney, with their families.
In a short time we reached the habitation of John Thomas, the senior missionary,
who has been for several years engaged upon these islands.
Here we met with a kind and friendly reception,
and the same offer of assistance as had been extended towards us at other places.
We found the whole mission belongs to the Wesleyan Missionary Society exclusively;
these individuals are the first of its members whom we have met with in the Pacific.
I left my certificates with John Thomas for translation;
and after having been cheered by hearing of our dear
friends James Backhouse and George W. Walker,
and of others whom we had known at Sydney and Hobart Town,
at which places the recently arrived missionaries had spent
some time waiting for a conveyance to the Friendly Islands,
we returned on board.

19th.--Notwithstanding the weather was so wet as to confine us on board,
yet the deck was crowded with the natives from morning until evening.
Small hogs, vegetables,
and abundance of shells seem to be the whole of their saleable property.
They are a fine manly race of people, of the most perfect form we have yet seen;
and having as yet had but little intercourse with foreigners,
they are not the victims of wretchedness and disease,
which the seamen every where introduce.
Their skins are clean and well oiled, and in general appearance they are healthy.
The length and roughness of their hair, which is uniformly black,
gives them rather a wild and ferocious appearance;
but they are in reality as gentle and docile as little children.
With the exception of an apron of long wiry grass about the waist, they are mostly naked.
Taofaahau, on whom the title of King George has been conferred by the missionaries,
is now absent at Lifuka, one of the Haabai Islands.
He is spoken of very highly, and declared to be a preacher of the gospel to the people;
and the queen, Charlotte,
fills the station of class-leader among the female part of the community.
It is said, the whole population of the group Haafuluhau,
(pronounced Haah-foo-loo-how,) of which Vavau is the largest island; of the Haabai group,
of which Lifuka is the most considerable, and a part of Tongataboo,
have embraced Christianity;
the remainder upon this last island are still called heathens.
John Hobbs and William Allen Brooks, missionaries from the station at Feletoa,
came on board this afternoon to make our acquaintance.

Went on shore this evening,
principally to inquire at what time I could see the people collected to-morrow morning,
my mind having been turned towards a meeting with them.
Finding no difficulty in the way,
and having the promise of John Thomas to interpret for me, we returned on board.
The evening proved wet, with thunder and lightning; and the vermin,
which have greatly increased since we have been in these hot climates,
being joined by a fresh supply of mosquitos from the shore, annoyed us extremely,
so that there was but little rest to be obtained; to which,
the prospect of having new ground to move upon, did not fail to contribute.

21st. (First day.)--Got ready in good time this morning,
and taking the mate and four men in the boat, proceeded to Neiafu.
On reaching the meeting-house,
it appeared that the native worship had commenced much earlier than usual,
to allow of more time for what might succeed it.
We remained outside the building, lest our appearance should tend to confuse,
until it was finished, when John Thomas came out and took me to his seat.
After my certificates were read and explained, I had, after a pause,
to turn the people to the great Teacher of all mankind--Christ Jesus; who, when on earth,
spoke as never man spoke, and taught as never man taught:
the light of whose glorious gospel bringeth salvation to all that believe in and obey it.
I had been induced to leave all to bring them the glad tidings of this gospel,
which is the power of God unto salvation from sin;
that the fulness of this heavenly blessing in all its riches, might be theirs for ever.
I was abundantly strengthened by the might of my ever gracious Master,
to proclaim to these noble islanders,
who form but a small portion of His "`inheritance,`"
the grace and truth which came by Him.
Under a feeling of great solemnity their attention was riveted,
while listening to the endeavours of a way-worn stranger,
to turn them from darkness to the light of Christ in their own hearts,
and from the power of Satan unto God; whose mercy endureth for ever.

22nd.--In the forenoon, John Thomas, Stephen Rabone, and John Spinney came on board;
and the afternoon proving very rainy, we could not get on shore.
By their coming, however,
arrangements were made for attending a meeting at Feletoa about noon to-morrow.
This evening we were informed that the Active schooner, a vessel well known to us,
had been wrecked upon a reef among the Fiji Islands.
The captain and three others escaped with their lives;
but the remaining four who were saved from the wreck,
were afterwards stripped and murdered by the natives.
Their destruction appears to have resulted from their
harsh and imprudent conduct towards the islanders.
They are said to have been four very wicked people.
The Fiji group is considered as part of the Friendly Islands.
This vessel was in the employ of the Wesleyan Mission,
and had brought out missionaries from Sydney to
this place but a short time before we arrived;
and from hence proceeded to land missionary stores at the Fiji Islands,
and was expected to return again shortly to Port Refuge.
This dreadful circumstance will tend to stagnate for a time the affairs of the mission,
as regards their supplies on these islands;
and may possibly retard the intended establishment of a mission at the Fiji group.

23rd.--This morning John Hobbs arrived in good time,
bringing with him two canoes with six natives,
who were to paddle the Henry Freeling`'s long boat to Feletoa
for the purpose of conveying us to the intended meeting there.
We were late in reaching our destination,
owing to a strong current setting against the boat.
John Thomas was preaching to the people when we arrived,
and when he had finished we went into the meeting, and sat down.
When John Thomas had finished his explanation of my certificate,
I stood up in great weakness and fear, and solemn silence prevailed over the assembly,
which was large.
I had to declare unto them the truth as it is in Jesus,
even in Him who in due time died for all, that all might live;--the same blessed Jesus,
who came on earth in the greatness of his love and strength,
to seek and to save that which was lost;--who once taught the people in a body of flesh,
but now teaches all mankind by His Holy Spirit of grace,
and is the Saviour of all that believe,--the life and
light of men;--mighty to save the soul from sin,
and lead it up to God the Father.
I seemed to have little or nothing before me but the supply of the moment,
from the time of standing up to the end.
After dining and spending some time in the family of John Hobbs,
we returned to the boat which was left about a mile off;
but the declivity of the foot path was much worse to descend than I expected,
though its ascent had been hard work in the morning.
All the missionaries, except John Thomas, accompanied us down towards the bay;
but they were put on shore before we came in sight of the shipping.
On arriving at Port Refuge, we were cheered by the sight of an English flag,
on board a vessel coming in from sea, which proved to be the Lady Wellington,
whaler of Sydney, out three months on a whaling cruise.

27th.--Most of yesterday engaged in bartering with the natives.
The king`'s brother, who is a useful man to the missionaries, dined on board with us.
To-day, cloudy weather;
heavy rain fell in the night with strong squalls from off the high land: the John Adams,
of New Bedford, drove from her anchorage, and was compelled to let go a second anchor.
Our vessel was moored with two heavy anchors.
The afternoon again showery.
The natives brought several hogs in the course of the day,
and a tolerable supply of yams and cocoa-nuts.
Having been confined on board several days by the state of the weather,
which of late has precluded the performance of any distant visits,
and nothing having arisen in this immediate neighbourhood,
it has been a time of something like resting on the oar.

28th. (First day.)--Long before daylight my mind was engaged to
examine whether there was any particular track for me to move in,
as regarded the natives`' meeting on shore; but I felt, as the morning opened,
a poor forlorn creature, enfeebled and ready to droop by the way, as one that fainteth,
though without having any defined prospect in view;
but abiding under the humbling influence of that power which softeneth the flinty rock,
I have found it to be a place of safety,
and one that prepares the tribulated mortal to
partake of a blessed portion of that strength,
which is perfected only in weakness;
while it prompts to watchfulness and resignation to the Divine will.
For the last two or three days,
while most on board are gladdened with the hope of soon seeing the coast of New Holland,
and entering again the port of Sydney,
I cannot discover the probable time of our leaving this place,
nor what may be our next destination: on which ever side I look,
obstacles of no small magnitude present themselves;
but I am desirous to leave all to Him,
who alone can make me quick of understanding in His fear.
"`My soul, wait thou only upon the Lord.`"
Spent the day on board with our own crew, in the usual way.

31st.--Yesterday arrived the American ship Wiscasset, of Wiscasset, Captain Macey,
from a whaling cruise, to secure her oil by coopering, etc.
In the afternoon,
some steps were taken towards prosecuting a visit to one of the smaller islands,
which the weather had prevented our attempting last Fifth day.
We found to-day,
that John Thomas had ascertained from some of the most intelligent natives,
that the tide would flow to-morrow,
sufficiently early to allow us to pass over the
flats and reach the meeting in seasonable time:
we were also informed that general notice had
been given to the people of two other stations,
viz., Tanea and Eueiki, to assemble at the central station of the three,
called Haalaufuli, where the meeting is appointed to be held.

Ninth Month 1st.--Left the vessel before sunrise, and called upon John Thomas,
who accompanied us through the journey.
We proceeded across a neck of land to a sandy bay,
where two canoes were soon in readiness to convey us forward;
but as the wind blew strong against us,
the natives very kindly suggested the propriety of a third canoe being procured,
to divide the weight more equally; and by rendering the canoes lighter,
to lessen the danger of our getting wet by the feather tops of
the little waves blowing on us from the stroke of the paddle:
this occasioned some delay, but was no doubt a saving of time in the end.
At length, however, we were equipped,
and proceeded with three skilful natives in each canoe, which contained one of us;
the canoe with John Thomas leading the way.
The first object was to cross an arm of the sea,
to obtain the shelter of a high bluff on a headland which we had to pass,
with numerous islands on our right,
which broke off the swell of the ocean almost entirely from our route:
some of these islands are inhabited.

About ten o`'clock a.m., we landed again on the island of Vavau,
after a very circuitous passage,
but the only one by which the extremity of this island can be got at from Neiafu.
We were soon met by the principal chief, Daniel Afu, and several of his people,
who welcomed us to their neighbourhood;
and after spending a short time at the chiefs house,
the meeting was assembled by the sound of heavy strokes upon a hollow piece of wood,
a sort of native drum, which may be heard at a great distance.
The people were soon collected,
and after John Thomas had opened the meeting in the usual way,
and read one of my certificates, all became silent.
I had largely to declare amongst them the
"`unsearchable riches of Christ,`" the beloved Son of God,
and Saviour of men; whom all men are commanded to hear:
whose Holy Spirit speaketh in every heart,
to bring us to repentance and amendment of life in the fear of God.
To this heavenly Teacher I was concerned to turn them,
and to exhort them in the love of the gospel to "`believe in the Lord Jesus Christ
and be saved;`" to believe in the power of His Holy Spirit in their hearts,
and wait for it there: we were favoured with a solemnity,
which nothing short of this irresistible power can produce.

Many of the people came to us in a loving manner, when the meeting broke up,
and hung about while we remained in the neighbourhood.
It was matter of very painful regret to us to find,
that these dear people are in the practice, as they feel their minds affected,
of breaking out into clamorous groaning, and saying '`Amen`' with a loud voice;
until a stranger is at a loss to conceive in what this dissipating practice may end:
it is evidently encouraged by their teachers.
They were this day turned to the teachings of that grace in their own hearts,
by which all such as happily take heed to it, will learn to "`worship God in spirit,
rejoice in Christ Jesus, and have no confidence in the flesh.`"
May the Lord hasten the dawning of that day,
when true spiritual gospel worshippers shall abound in
the earth to the glory and praise of Him,
who is alone worthy to be worshipped in spirit and in truth;
when living spiritual sacrifices shall ascend, acceptable unto Him by Jesus Christ;
and in every place incense shall be offered to his ever great
and excellent name,--even the sacrifice offered in the
"`beauty of holiness and newness of life,`" from the pure,
contrite, and humble heart, produced by the power of the Spirit of the Lord Jesus.

After meeting we partook of some refreshment at the chief`'s house,
in true native style upon the floor on mats,
with the milk of the cocoa-nut as a beverage,
and the pulpy shoots of the banana bruised between the fingers,
to answer the purpose of washing the hands;
some native cloth from the dress of the chiefess served for a towel:
this was found a very needful and agreeable part of the entertainment,
having had literally to tear the food to pieces with our fingers.
When our repast was finished,
we took leave of the chief and his family and others present,
and returned to the sea-side,
and were safely paddled back again to the sandy bay near Neiafu.
On the way from the canoes to the mission house, we called at the king`'s habitation;
his daughter, usually styled the Princess Charlotte, was at home,
a young woman about sixteen years of age, with an intelligent countenance;
she was seated on the floor in simple native attire; her brother, a boy,
perhaps twelve years old, was playing about.
When returning to the vessel,
it occurred to me that some of the ships now in the harbour would soon be ready for sea,
and I felt as if I should not be clear of the crews,
without endeavouring to collect them together next First day forenoon:
to this I stood resigned, in hopes of feeling some further impression in the morning,
if it should be required.

3rd.--Yesterday, the subject of a meeting with the seamen still rested upon me.
On awaking this morning I endeavoured to watch over every thought that arose;
and after remembering my great Creator in humble
gratitude for the mercies of the past night,
my mind seemed as a blank,
until the prospect of holding a meeting with the seamen of the fleet came before it;
this was not a little in the cross to the unmortified part,
which seemed now ready to shrink.
I kept the matter close until after breakfast,
and then told Charles that I believed it safest for me
to appoint a meeting for worship to-morrow,
at eleven o`'clock a.m., to be held in the native chapel at Neiafu,
if that could be obtained.
On stating this to John Thomas, he said that a missionary was coming down from Feletoa,
to preach at the hour proposed for holding our meeting;
but that he had no doubt of his being willing to accommodate me.
In that case, I told him that I should give notice to the shipping,
that they might know what to expect;
as the meeting would be held after the manner of the Society of Friends,
and would not commence with singing;
but we should wait in silence for the influence of the Holy Spirit upon our minds,
before we could move.
In the afternoon a sufficient number of written notices
were prepared and distributed amongst the shipping,
leaving the result to Him who knoweth all things;
desiring that His great name alone may be exalted,
and the gospel of the heavenly kingdom may be
proclaimed in the heart of man to the Saviour`'s praise.

4th. (First day.)--This morning much cast down and a poor creature,
but as one bound to the work of the dear Master; from which I dared not hold back,
however human nature might be ready to shrink, as the hour of trial approached.
Landed in good time, and proceeded to the meeting-house at Neiafu.
I felt depressed from a sense of something like a spirit of opposition being present;
but was soon comforted by an evidence which I could not mistake,
of that power being nigh to strengthen the inner man,
the all-sufficiency of which to sustain in time of trouble I have so often witnessed.
I had to sit long in silence,
but eventually stood up with those instructive expressions of
our Lord to his disciples,--"`Herein is my Father glorified,
that ye bear much fruit; so shall ye be my disciples.`"
"`He that abideth in me and I in him, the same bringeth forth much fruit; for without me,
ye can do nothing.`"
From this I was enabled to show,
that without the blessed influence of the Holy Spirit of the Son,
we can do nothing,--much less be capable of bearing that fruit,
by which the holy Father is glorified;
and the impossibility of performing that worship
which only is acceptable in the sight of Him,
"`who is a Spirit,`" without the help of the Holy Spirit:
that therefore it is indispensable,
in order to the performance of true spiritual worship,
to wait in reverential silence for a renewal of that strength,
which is mighty through God to the casting down imaginations,
and every high thing that exalteth itself against the knowledge of God,--to
the "`bringing into captivity every thought to the obedience of Christ,`"--
even to the obedience of the Spirit of Truth in our hearts,
without which none can worship God in Spirit and in truth.
It is this influence which can alone prepare our hearts to worship, praise,
and glorify the God and Father of our Lord Jesus Christ; who is a Spirit,
and must be worshipped in Spirit and in truth.

I had to set forth the admirable adaptation of the glorious
gospel dispensation to the condition of man the world over,
and the blessed superiority of true spiritual worship in the inner temple of the heart,
over that which is left in the outer court to be trodden under foot.
My mind was particularly turned towards those "`that go down to the sea in ships,
that do business in great waters,--that see the works of the Lord,
and his wonders in the deep.`"
Although such may often feel excluded from their fellow-men,
shut out from every opportunity of religious instruction,
and destitute of the '`means of grace;`' this is evidently not the case,
but a delusion of the great enemy of God and man;
although it may be often held out by those who have a zeal for God,
but not according to knowledge, of whom the great apostle speaks.
For notwithstanding it is the lot of seafaring men to
spend their days in roving upon the mighty ocean,
yet the only true and blessed means of grace are still within their
reach,--even that grace and truth which came by Jesus Christ,
which hath appeared unto all men, and teacheth all men that believe in it.
No class of men have a better opportunity of attending upon the means of salvation;
and although their allotment may be thought solitary,
yet they are saved from many temptations,
and out of the reach of the contaminating example of wicked men,
to which those on shore are daily exposed.
They have less to draw their attention aside from the great work,
and more time to work out their souls`' salvation,
than many of their fellow-mortals:--their nightly
watches may be turned to everlasting account,
in waiting upon the Lord,
in looking for the blessed hope and glorious appearing of the great God and Saviour,
by His Holy Spirit of grace.
No men have greater need to acquaint themselves with God and be at peace;
they are in jeopardy every hour,
which plainly bespeaks the necessity of their being prepared to meet their God,
as with their lives in their hands.
The Lord most High, in his infinite goodness and mercy,
hath vouchsafed a day of visitation to all men, for the salvation of all men;
and it is this visitation that preserveth the life of the spirit in man.
"`Thy visitation,`" said Job, "`hath preserved my spirit.`"

The meeting held long, but proved a searching solemn season;
and although at first a gloom seemed to hang over it, eventually every cloud,
or feeling of this kind, was scattered by that power, whom winds and waves obey;
and it ended well.
A considerable number of seamen from the different ships with their captains attended,
also the whole of the missionary families here, and one from Feletoa,
with many of the natives, and some New Zealanders connected with the shipping,
who understand English pretty well.
Two of the ships in the harbour had intended sailing this morning,
but were prevented for want of wind.
The crews of both were furnished with an ample supply of tracts and Friends`' writings,
with two Spanish Testaments, for two men of that nation employed on board of them.

7th.--Notwithstanding the security of the harbour in which we are privileged to ride,
yet the scanty supply of fresh water is a serious inconvenience,
the nearest spring being four miles off,
on an island where the empty casks have to be rolled up half a mile; and when filled,
which requires much time to accomplish, they are rolled back again to the water`'s edge,
and towed on board as a raft.
Having had no opportunity to procure any of this most necessary
article since leaving the last of the Sandwich Islands until to-day,
the stock on hand is very small,
and can only be recruited by small quantities once in the day.
Since First-day,
we have arranged for a visit to the two congregations at the island of Otea to-morrow;
it being agreed that they shall meet at the same time under the same roof.
May the Lord be graciously pleased to go before,
and open the way in the hearts of these people,
to receive the ever-blessed Truth in the love of it; and through the workings thereof,
bring forth fruit that shall lastingly remain, to His praise and their peace.

8th.--As our vessel was anchored in the track from Neiafu to Otea,
we waited the coming of John Thomas; who arrived before ten o`'clock,
bringing with him John Spinney and six natives,
who were then taken from the canoe and placed in our boat with their paddles,
for the better accommodation of the whole party.
On landing at Otea,
we proceeded towards the other side of the island where the meeting was to be held.
In crossing the sandy beaches, two of which were in our route,
exposed to the full blaze of the sun nearly at noon,
the heat and glare of light were almost insupportable,
and the want of air when passing through the bush was still more oppressive.
We stayed a short time at the house of the chief, whose name is Lazarus,
a steady going man among the people; and when cooled a little, proceeded to the meeting,
where the natives were assembled in readiness.
Exclusive of the pulpit,
there did not appear to be a seat in the whole neighbourhood except on the floor;
some of the people at last brought part of an old canoe into the building,
for Charles and myself to sit upon.
I felt in a very low and feeble condition, both as to body and mind;
but when my certificates were read,
I stood up with a salutation of love in my heart to the people; which having expressed,
I had to turn their attention to Him,
"`Who seeth not as man seeth,`" but who is a Spirit, and looketh on the heart:
He searcheth all hearts, and understandeth every imagination of the thoughts;
and to this man will He look, even to him that is poor and of a contrite spirit,
that trembleth at His word.
The Christian religion is a heart-felt work;
it is in the heart we must work out our own salvation with fear and trembling,
through submission and obedience to the power of the Spirit of the Lord Jesus,
which dwelleth in the contrite and humble heart,
without respect of persons or of the colour of the skin.
"`Cease from man whose breath is in his nostrils,
for wherein is he to be accounted of:`"--man cannot save his own soul,
nor blot out a single sin; and can he do the work for another,
which he cannot do for himself? My heart was greatly enlarged towards the people;
and they listened with apparent attention:
but there was a feeling of deadness over the meeting,
greater than we had yet witnessed on these islands.

After remaining some time at the house of Lazarus to refresh and rest,
we again crossed the island, and resumed our station in the boat:
we proceeded round the northern part of the island, and visited a splendid cavern,
into which we rowed with the boat, having a canoe to lead the way, conducted by Noah,
one of the chiefs of Otea,
and two chosen natives also well acquainted with the
position and entrance of this wonderful place.
The great height of the vaulted arches above our heads, which are almost of gothic shape,
from which are suspended a variety of huge spiral masses of ponderous weight,
apparently ready to fall,--the amazing depth and clearness of the water under us,
together with the dark and deep recesses,
which could not be explored for want of a light,
exhibited a sublime and magnificent spectacle and a
specimen of those great and marvellous works,
incomprehensible to mortal man.
Fish of large size swam about beneath us,
without the least appearance of being disturbed by the boat,
so great was the depth of water between us and them.
In knocking off some of the spiral crags within our reach to bring away with us,
the echo produced was alarming,
and as if the whole roof was in danger of falling upon us.

9th.--King George having arrived from Lefuka, one of the Haabai Islands,
this morning paid us a visit: a Saul-like man in truth,
being higher than the rest of the people perhaps by the head and shoulders; he was naked,
with the exception of some native cloth round his waist.
His moral character is highly spoken of,
and the great prosperity of the Christian profession here,
is said to be owing to his promptness in the due observance of its rites and ordinances:
the laws are said to be good, and he insists upon their being executed with rigour.
If any disobey, or in any way are guilty of a misdemeanour, they are severely punished.
It is much to be regretted,
that the punishment of flogging should have been introduced here:
it has been inflicted lately on several offenders, including one woman.
This barbarous practice, we have been told,
has proved beneficial to the people in a moral point of view;
but I believe its tendency is rather to blunt the feelings, and harden the heart.
In the afternoon took exercise on shore until dark.
Captain Macey of the Wiscasset, a serious man, drank tea with us.

11th. (First day)--Spent a peaceful day on board,
collected the crew both fore and afternoon for devotional purposes;--
none of them seemed disposed to attend the meeting on shore.

13th.--Yesterday sailed the brig Lady Wellington: previous to her departure,
the crew were furnished with a set of Friends`' tracts, and a Summary of our principles.
This morning, John Thomas came on board at eight o`'clock;
when we immediately proceeded down the harbour in the usual way,
and landed on the western coast of Vavau.
The meeting was to be held at Hihifo, about a mile from the landing-place;
whither we went, and met with the chief Solomon, at his own habitation;
and as soon as the people were collected, repaired to the meeting-place.
The places of worship at the stations distant from Neiafu are like large sheds,
standing upon props, and open on both sides;
but the ends are made tolerably close with coarse matting.
As there was no seat in the meeting, I remained near John Thomas,
who occupied a considerable time in the native language, before reading my certificates.

When he had finished we stood by each other in silence, and the people seemed unsettled,
as if they did not know what to expect next, or to whom they should hearken,
first looking upon one of us, and then upon the other;
until it was with me to caution them against a dependence upon the creature,
but to endeavour to fix the attention of their minds upon the Creator,
who is a Spirit and knoweth all things.
The darkness hideth not from Him,--the darkness and the light are both alike to Him,
before whom the night shineth as the day.
My desire was,
that nothing might be permitted to beguile them from the
simplicity of the gospel of Christ,--that they might not rest
satisfied with a mere hearsay knowledge of his name,
as a Saviour, but come to the knowledge of his Holy Spirit in themselves,
and know for themselves His gospel to be the power of God unto salvation.
It was with me to query,
what a profession of the Christian religion had done for them?
There had been time for some of them to have witnessed
something like fruit to be brought forth in themselves;
for without a change of heart is known, their religion will profit them nothing.
I felt an earnest engagement of mind to turn them to the power
of the Spirit of the Lord Jesus in their own hearts;
which would, if believed in and obeyed, cleanse them from sin,
create in them a clean heart, and renew a right spirit within them.
Although I had full opportunity to clear myself,
yet so great was the stream of love that flowed towards the people of Hihifo,
that after the meeting was over, I found no relief:
the desire of my heart was as strong as ever,
that they might not be beguiled by lifeless forms and shadows,
from the simplicity that is in Christ, the living and eternal substance.
After spending some time with Solomon, the chief,
who spread a table plentifully for our refreshment, according to native custom,
we repaired to the boat, and proceeded forthwith to the Henry Freeling.

15th.--It was with difficulty that an opportunity could be found,
on account of the increased number of natives upon the deck, to sit down together;
notwithstanding which, the way opened to our comfort.
We understand that earthquakes frequently occur among these islands,
at times so violent as to stop the clock at the mission-house.
On First day last, whilst in the meeting appointed for the seamen of the fleet,
and before standing up amongst them,
a considerable shock was sensibly felt by the missionary families then present.
Of this, I was not myself aware,
although the frame work in the roof of the building we
were in was heard to make a cracking noise at the time.
Last Second day evening, about nine o`'clock, another shock was witnessed at Neiafu,
but was not perceived by us upon the water: we are told, however,
that they are sometimes felt on board the shipping, and occasion a rumbling noise,
as if the vessel was passing over a rugged rock, and sufficiently loud to alarm the crew.

16th.--Remained on board the fore part of the day, while Captain Keen and Charles,
accompanied by Philemon an intelligent native,
ascended Talau a considerable hill on the island of Vavau, to form a plan of Port Refuge,
for the benefit of those who may follow us at a future day.
From this point they were enabled with sufficient accuracy to
describe the position of this group of islands,
which are said to be one hundred and two in number, known by the name of Haafuluhau;
so that any stranger may direct his course to Port Refuge in perfect safety,
by keeping a good look out,
which is of course one of the means dictated by common prudence in such cases.
The depth of water varies at the anchorage from sixteen to thirty-six fathoms,
with holding-ground of sand and coral.
From the direction in which the trade-winds usually blow,
a vessel has generally to beat against it as soon as she comes
round the southernmost bluff upon the main land of Vavau.
The deepest water appears to be on the left hand, the whole way up to the port;
the distance from the entrance point may be from ten to twelve miles,
and there is ample room for the largest ship to work with common care.
In the evening went on shore to consult with
John Thomas on the subject of leaving our cook,
Pedro Nolasko, a Spaniard, who is desirous of getting to the Fiji Islands,
having heard of the probability of meeting with a vessel bound to Manilla,
his native place.
As he is a man of good character, and not likely by his conduct to injure the natives,
and there being no objection in the minds of the
missionaries and the authorities of the place,
there seems no good reason for refusing to discharge him, agreeably with his wishes;
more particularly,
as we have just taken on board one of the
survivors from the wreck of the Active schooner:
this man was intended to work for his food while with us,
but he will now come in for regular wages,
by filling up the vacancy which the discharge of Pedro Nolasko will occasion.

19th.--On Seventh day, with the exception of taking exercise on shore towards evening,
we were employed on board through the day; yesterday,
(First day,) remained on board all day with our own people,
having no attraction to the shore.
It was a season of self-abasedness and poverty; but however humiliating,
I trust not altogether unprofitable,
and one that I have found not unfrequently to precede,
and perhaps prepare for further service in the Great Master`'s time;
for which the prayer of my heart is, that I may be ready; confiding in Him,
whose power can raise up from utter weakness, and make strong for His use.
To-day sailed the American ship Wiscasset, Captain Macey.
This vessel was supplied with some tracts and writings of Friends.
This evening it seemed best to arrange to attend a native meeting at Matika,
a few miles from hence; the greater part of which distance can be performed by boat.
As John Thomas was not likely to be at liberty,
John Hobbs kindly offered to supply his place as interpreter;
but the situation of the neighbourhood is such,
that the weather must be consulted in the first place.

20th.--The weather apparently likely to answer for our going to Matika;
and John Hobbs having arrived with a suitable crew of natives,
by nine o`'clock we proceeded on our way,
and landed at Feletoa before eleven o`'clock a.m. Here we got a cool resting place,
and after an early dinner proceeded to Matika.
Feeling unwell soon after,
I was not in very good trim for moving forward in the hottest part of the day,
nor for attending the appointed meeting;
but I well knew that He who had sustained me thus far,
could strengthen me at his pleasure,
to stand before the people for His great name`'s sake.
Having now an interpreter,
to whose abilities and qualifications in the native language I was a stranger,
it seemed like venturing upon untried ground.
I soon found that I had no cause to fear on this head,
but rather to dread the quickness with which he at once
comprehended the drift of what I had to say,
and interpreted it to the people; however, although every sentence as soon as uttered,
was rapidly conveyed to them without hesitation on his part,
yet with thankfulness I can say, that I never felt less difficulty in getting on.
I had to caution them particularly,
not to be deceived in looking without for that which is only to be found within;
that so they might come to the knowledge of Christ,
the light of whose Holy Spirit shineth in every heart;
and that they might believe in it to the saving of the soul,--that so Christ
may dwell richly in their hearts by faith,--that He might be theirs,
and they might be His, in His Father`'s kingdom for ever.
It was a comfortable meeting, and ended well.
Great is my desire for these people,
that their hearts may be directed to the love of God,
and to the patient waiting for Christ.
How great the responsibility of those,
who take upon themselves to introduce the religion of
Jesus amongst a simple-hearted people,
lest its beautiful simplicity be hid from them,
by forms and shadows of man`'s own invention!

21st.--This morning the Mary Anne, of London, sailed for the whaling grounds;
sundry tracts were furnished for the crew, also a French Testament for one of them,
a native of France.
A few days ago a native offered amongst other articles for sale,
a copy of the Holy Scriptures in English.
I found on examining it, that it had been given by the Seamen`'s Bible Society in London,
probably to some ship`'s library.
I purchased this book for about eightpence, merely to show the necessity of inserting,
not only the donor`'s name, or that of the institution by which it had been bestowed,
but the name of the person to whom it was originally given,
or the ship`'s library to which it belonged: it would, I think,
help to deter from such a misapplication.
It is very probable that this bible had belonged to the library of the Mary Anne,
of London, but this was not specified,
or it might have been returned to that vessel before she left the port,
and have served to prevent a similar occurrence in future.
We find that sailors, our own not excepted, regardless of the future,
do not hesitate to give articles for a shell or two, far exceeding the value of them;
they will part with a woollen jacket, as a thing perfectly useless to them,
because at that particular time, in a hot climate, it is not wanted;
and the natives will accept of almost any thing for their shells.
If books of a pernicious tendency in the English
language are found in the hands of the natives,
such are immediately destroyed;
and books of various kinds fall into their hands when bartering with the shipping;
they are pleased when they can obtain writing paper, pen and ink, or a pencil.

Ninth Month 22nd.--Although many natives were on board,
we were enabled to set aside our bartering, and sit down to wait upon the Lord,
but it required firm struggling to get into quiet introversion of mind;
towards the end a little of that strength was witnessed,
by which only the foes of a man`'s house can be cast out,
and himself left in peaceable possession.

24th.--Both yesterday and to-day,
with the exception of taking the needful exercise on shore, as the sun declined,
we were engaged on board getting things into train,
with the prospect of shortly sailing for the Haabai group of Tonga isles.
Since it has come to my knowledge that the strength of these
islands is to be assembled at Lifuka with king George of Vavau,
and Josiah (Tubou), the king of Tongataboo,
I have not seen the way open for me to move in any direction but to Lifuka;
and the more I have dwelt upon this subject,
the more it appears to be the right track for me to pursue.
Owing to existing circumstances connected with persons and places,
it doth not seem practicable for me to complete the object which brought us to Vavau,
of visiting the people, before the end of this month;
and allowing that it could be satisfactorily accomplished at an earlier period,
it would be useless to sail for Tongataboo,
as those competent for the important office of interpreter,
will have left the island to join their brethren at the
general assembly about to take place at Lifuka.
My earnest desire is, to be found in the counsel of the will of our heavenly Father,
to be preserved in faithfulness and humble resignation thereunto,
and favoured to possess my vessel in patience to the end of the race.
Could I have contrived for myself, I should certainly not have selected Lifuka,
as the Haabai group is a dangerous archipelago of small islands, shoals, and reefs,
without any secure place of shelter from every wind that blows,
and not the least dependence can be placed on the published charts of it.
But if He that "`bloweth with His wind,
and the waters flow,`" is graciously pleased to direct our way amidst
the lurking dangers of the deep which await a stranger vessel,
who hath so mercifully and so often in appalling seasons said in effect, "`It is I,
be not afraid,`'`"--and this too accompanied with
an evidence so indisputably strengthening,
that a poor helpless mortal could exclaim in that humble faith and
confidence which condescending heavenly love alone inspires,
"`It is the Lord,`"'`--all fear is then cast out, except what is filial.

26th.--Yesterday (First day,) spent the day on board.
Collected the sailors twice in the course of the day for devotional purposes.
Engaged the fore-part of to-day on board, and in the afternoon went up to Neiafu,
to endeavour to arrange for visiting the natives on the north shore.
The weather sultry and rainy, making the clay soil,
of which the neighbourhood of the landing place is composed, almost impassable;
and the steep descent down to the boat extremely difficult and unsafe.

27th.--Much rain during the night and this morning, which prevented my going on shore;
Charles landed for a short time opposite the vessel, but was soon compelled to return.
About nine o`'clock this evening,
a shock of an earthquake was sensibly felt on board by the trembling of the vessel;
Captain Keen stepped upon one of the chain cables, by which we were riding at the time,
when the shock was more evident,
from the connection of the anchor with the earth at the bottom of the sea.
This is the fourth shock that has been felt since our arrival at Port Refuge.
Would that the earthly nature in the hearts of all around us, yea the world over,
were so shaken, that that only which cannot be shaken might remain,
to the praise and glory of God.

Ninth Month 28th.--Still rainy weather.
John Hobbs called on board to-day,
with whom an arrangement was made to visit a native meeting to-morrow afternoon,
should the weather permit us to proceed and the people to collect.
We learn from John Hobbs that the shock of the earthquake last evening,
was the most severe he had known since his coming to these islands;
it was felt on board the American ship Mussel,
quite as much as on board the Henry Freeling.

29th.--In our solitary sitting this forenoon,
we were favoured to witness a degree of strength sufficient for the day,
to wrestle for the blessing.
Soon after three o`'clock, John Hobbs and ourselves set forward in our own boat,
with six able natives to paddle;
on account of the falling tide we landed at a place much more
distant from the meeting to which we were going,
than would otherwise have been necessary.
It was, however, much safer for the boat,
with which it behoves us to use every precaution, to enable her to hold out to the end;
she is now leaky and much worse for wear, and was not a thoroughly good one when new.

The heat of the afternoon made the extra walking very fatiguing;
and the current of air to which I was afterwards exposed,
occasioned considerable pain in my head: but such was the engagement of my mind,
that this bodily annoyance was little regarded.
After resting awhile at a house built for the
special purpose of accommodating the teachers,
the meeting commenced; and although I was as an emptied vessel,
while the translation of my certificates was read:
yet shortly after the reading concluded,
my mouth was opened to turn the attention of the people to that Almighty power,
which "`is not far from every one of us,`" dwelling in our hearts by his Holy Spirit,
except we be reprobates; "`in whom we live and move and have our being.`"
He that abideth of old, with whom a thousand years are but as one day,
and one day as a thousand years,--from everlasting to everlasting he is God,
and changeth not.
My desire for this people was, that they might become wise in heart,
by seeking after that knowledge which is life eternal,
through the operation of the Holy Spirit, which shines in every heart;
that they might inherit glory,
and be numbered among those that shall shine as the brightness of the firmament,
and with them that turn many to righteousness, as the stars for ever and ever.
The gospel of the everlasting kingdom was freely preached to these dear people:
it was a memorable season, and yielded peaceful relief to my mind.
We reached our vessel soon after dark.
What, indeed,
can we render unto the Lord for all this! being nothing ourselves and possessing nothing,
but what we have received from Him, the God of love and praise.

Tenth Month 1st.--Yesterday engaged on board most of the day,
making ready for sailing for the Haabai.
My attention has been drawn at times, in the course of yesterday and to-day,
towards again attending the native meeting at Neiafu to-morrow;
and John Thomas and Stephen Rabone calling on board this afternoon,
afforded me an opportunity of mentioning the subject.
John Thomas kindly agreed at once to make way for it,
and offered his assistance as interpreter.
Although so often a partaker of heavenly help and goodness, I am still imploring more;
being increasingly sensible of the want of it, when looking towards this meeting;
that the name of the Lord Jesus may be exalted, to the glory of God the Father.

Having now every prospect of bending our course towards Lifuka,
I deemed it expedient to make an offer to convey as many of
the missionary families as inclined to go to the congress;
telling John Thomas,
that if they were willing to put up with the want of accommodations
to which they would be subjected in our small vessel,
the whole of them might go with us.
He expressed a fear that such a number would put us to great inconvenience;
but I told him, it was themselves that would have to suffer the inconvenience,
as they would have literally to stow themselves
as they could upon the cabin sofas and floor;
but, perhaps, we might not be out more than one or two nights,
which would depend upon the wind.
The distance is sometimes performed in a few hours,
when the trade-wind is strong and favourable.

The shock of another earthquake was felt on the night of the 29th ultimo.

2nd. (First day.)--This morning I felt a very poor creature, both in body and mind;
but "`knowing in whom I have believed,`" and unto whom "`all power in heaven
and earth is given,`" I prepared to attend the native meeting at Neiafu.
We reached the mission-house before the bell rung;
and accompanied John Thomas to the meeting in due time.
I sat for some time in a pew constructed for the missionaries;
and when John Thomas had finished speaking, I went and stood in front of the people,
upon the base on which the pulpit is erected.
John Thomas then came down to me, and a general silence prevailed over the assembly,
which was large, until broken by myself with the words;--"`Watch ye,
stand fast in the faith, quit you like men, be strong.`"
The burden which rested upon my mind was,
that these people might become the Lord`'s people, formed for himself,
to show forth his praise,--that they might become his children, and be taught of Him;
for all the sons and daughters of men, which form His church,
are taught of the Lord himself: in righteousness they are established,
and great shall be their peace.--That they might indeed be sheep of the one fold,
and of the one great and heavenly Shepherd, hear his voice, be known of him,
and follow him; and thus be enabled individually to say, from blessed experience,
"`The Lord is my shepherd; I shall not want.
He maketh me to lie down in green pastures; he leadeth me beside the still waters.
He restoreth my soul; he leadeth me in the paths of righteousness for His name`'s sake.`"
But the sheep must first learn to know the voice of the great Shepherd,
when they hear it, from the voice of a stranger;
that so they may follow him with safety whithersoever he leadeth:
those that are the sheep of his fold know him, and are known of him.
"`My sheep,`" said Christ, "`hear my voice, and I know them, and they follow me:
and I give unto them eternal life; and they shall never perish,
neither shall any man pluck them out of my hand: My Father, which gave them me,
is greater than all; and no man is able to pluck them out of my Father`'s hand.`"
Thus, the security and blessedness of the Lord`'s children, which compose his church,
are set forth by its holy Head, the Lord Jesus, that great Shepherd of the sheep:
and there is no other way for any of us to become of this happy number,
but that of sitting under the teaching of His Holy Spirit, to learn of Him,
to know His voice and be known of Him, and be His sheep and follow Him.
He will teach us humility, meekness, and lowliness of heart.
Such are formed for himself, do show forth His praise, and glorify Him before men,
by producing the fruit of the Spirit in the sight of those around them;
openly declaring by life and conversation,
that the gospel of Christ is the power of God unto salvation,
even to those who beforetime were in darkness, hateful and hating one another.
I was largely opened among them;
and if it was possible to recapitulate all that was uttered,
words would still fall short,
and fail to describe the heart-tendering solemnity which crowned the meeting.
Towards the conclusion when about saying farewell to these dear people,
as one never to see their faces again,
that Almighty power which alone can soften the heart was eminently conspicuous;
tears could not be restrained,
but silently and undisguisedly rolled down the swarthy cheeks
of the sons and daughters of this isle of the ocean.

3rd.--Early in the morning the Henry Freeling unmoored, and prepared for sailing:
by twelve o`'clock the whole of the missionary families,
with their servants and luggage being on board,
we left the well-sheltered harbour of Port Refuge;
and retracing our course through the maze of islands into the open ocean,
stretched away from the shore of Vavau.
A large number of the natives attended to the last,
and hung round the sides of our vessel until compelled to let go their hold,
evincing sincere regret at her departure.
One of the chiefs of the island of Otea, named Noah, a noble man in person,
with whom we were particularly acquainted, and whom we highly esteemed,
wept aloud when he left us, and was heard when the canoe was at a considerable distance.
He was affected by the whole circumstance of parting with all his friends;
but principally on account of losing an adopted daughter,
who was leaving Vavau for Tongataboo:
she had been for a long time an inmate of the mission-house.
Our passengers consisted of John Thomas, Stephen Rabone, John Spinney, John Hobbs,
(going to reside at Lifuka,) and William A. Brooks, with their families,
in all eighteen persons, besides nine domestics.
We had also William Bunubunu,
nephew of the late Finau the conqueror of these islands in former days,
selected by King George, as our pilot for the Haabai group.
Soon after getting fairly out to sea, the whole of our guests,
except two of the youngest children, became sick;
and some of them remained so the whole time.
The wind became unfavourable in the night,
and prevented our seeing the isle of Aano next morning as was calculated upon.
+++[+++Haanna in the Map?]

4th.--When morning came, it was found that we had drifted towards the island of Kao,
in appearance a lofty mountain of regular conic shape rising out of the sea,
and evidently of volcanic origin.
By ten o`'clock a.m., the island of Toofoa was fairly opened,
and the action of the volcano at the north end plainly to be seen,
vomiting clouds of smoke into the atmosphere,
which occasionally burst forth with increased strength.
It was soon ascertained that getting to Lifuka by night, as before anticipated,
was quite impracticable, as the wind continued to baffle us;
but shifting two or three points after midnight, we fetched well to windward,
and after making one short tack at the entrance of the reef,
before ten o`'clock were favoured safely to anchor off the island of Lifuka,
abreast of the settlement of Mua, in only three and a half fathoms water,
on Fourth day the 5th instant.
Any vessel less manageable than the Henry Freeling, might easily have got upon the reef,
the entrance is so narrow and intricate, in the worst part of which she had to tack.
It is probable that few vessels so large as ours ever anchored upon the same ground;
and none, however small, ought to venture without a competent pilot on board.
It is close to this spot that the Port au Prince was wrecked, perhaps thirty years ago:
some of her remains are visible at this day,
and are frequently dug out of the sand by the king`'s order,
for the sake of the copper bolts, etc.
Of recent date, the Snapper was cut off by the natives and lost upon an adjoining reef,
not far from Mua.
Soon after we had anchored, Charles Tucker,
the resident missionary at this place came off, bringing with him James Watkin,
who had arrived the preceding day from his station on the island of Tongataboo.
A double canoe was procured,
which took the whole of our passengers and luggage at once to the shore:
they were safely landed by eleven o`'clock, to their great relief.
The natives soon began to visit us,
well pleased to see a vessel at anchor off the island,
as it is but seldom that such a circumstance occurs.
