== Chapter XXXII.

[.chapter-synopsis]
* Island of Lifuka
* Native Meeting
* Distribution of Bibles, etc.
* Visit of the King
* Meeting with the Missionaries
* Sail For Tongataboo
* Anchor Off the Settlement at Nukualofa
* Letter from the Wesleyan Missionaries
* Distribution of Clothing and Medicines
* Visit to the Heathen Settlement at Mua
* Restraining Influence of the Missionaries
* Native Meeting at Nukualofa

Tenth Month 6th.--This morning early,
a turtle of prodigious size was sent on board as a present from Josiah Tubou,
the king of Tongataboo, who had arrived here from that island.
In the forenoon the weather became quite stormy,
and the wind coming in from the westward, made it uneasy riding in the bay.
Charles and myself sat down together as usual to wait upon the Lord,
though in much poverty and weakness.
At noon it threatened to blow strong;
but shortly afterwards the atmosphere became more tranquil.
There was not so much to be apprehended from the
anchor and cables not holding the vessel,
as from the danger of striking on the rocky bottom,
had the swell from the ocean been permitted to come in upon us.
The hurricanes which we are told occasionally occur here, are very awful,
levelling with the earth houses, trees, etc., before their tremendous blast;
and they generally, if not always, blow from the westward,
the only quarter from which we have any thing to fear at this anchorage,
as the land and the reefs are a shelter on every side, but this;
but the Lord`'s power is the same here as in every other place--
"`mighty to save and to deliver`" out of every trouble and distress.

7th.--This morning the natives thronged our decks with trifling shells for barter;
but the poor creatures have very little in their possession to offer.
The last violent hurricane with which they were visited,
destroyed their breadfruit trees, etc. to considerable extent,
and materially injured their yams, upon which they are usually supported;
and from this serious calamity they have not yet recovered.
Many of them are now subsisting upon the fern and tea-tree roots;
but it is expected that in a few weeks`' time,
the present complaints of famine will be banished by an abundant supply of yams,
sweet potatoes, etc.
In the afternoon we visited the mission-house by invitation.
While there it was with me to propose having an
opportunity afforded of seeing the people,
when collected at their morning meeting next First day.
On inquiring about some one to interpret what I might have to say to the people,
James Watkin the missionary then present from Tongataboo,
was proposed to undertake that part of the work, to which he kindly and readily assented.
May the Lord be graciously pleased to magnify his power,
and cause this stranger and myself to be faithful to Him, in performing each his office;
so that,
"`that life and immortality`" which "`are brought to light by the
glorious gospel,`" may be declared to the natives of Lifuka,
and others assembled with them, to our Maker`'s praise.

8th.--Engaged on board till late in the afternoon with the natives.
It is probable that the meeting tomorrow will be very large,
as the inhabitants from the different islands which compose the Haabai group,
are now assembled at this place, besides a vast number from the Haafuluhau group,
and Tongataboo.
Oh! that the Master of assemblies may be there.
To Him, who only knoweth my motive for coming amongst them, I commend them and myself;
humbly praying for help in the needful time,
lest the cause of truth and righteousness should suffer in such weak and feeble hands

9th. (First day.)--Proceeded towards the shore at an early hour.
We were met on landing by a swarm of young natives,
who appeared to be on the look out for us.
In half an hour the first bell rung to assemble the people:
this bell might have been spared, as the large meeting-house was filled,
and a multitude still outside,
when we passed by on our way from the boat to the mission-house:
another extensive building was also filled, not far from the largest.
The natives were indeed gathered together to an extent,
which we have not before witnessed in the Friendly Islands.

James Watkin kindly conducted me through the concourse of people,
into an enclosed place in front of the pulpit on a level with the floor: here I remained,
until the interval arrived for me to take a station by the side of my interpreter,
to be in readiness to minister to the people, as way should open.
I felt no hesitation in going up into the pulpit,
believing that even when the most advantageous position was chosen,
but a small portion of the people in comparison with the whole collected about the house,
would distinctly hear what was said; these buildings are open at the side,
a circumstance which the nature of the climate requires,
and which is a special advantage at these times,
as before has been witnessed by us at Vavau.
A general stillness now prevailed over this large assembly,
which I thought might be occasioned in the first place,
by the novelty of two persons appearing in the pulpit, both standing, and both silent.
It was not long however before I had to turn their attention to Him,
unto whom the cattle on a thousand hills belong; before whom,
the secret thoughts of every heart are laid open.
He seeth us as we really are, born in sin, and laden with iniquity, helpless,
and utterly unable of ourselves to do any thing for ourselves; for, as men and mortals,
we possess nothing, and are as nothing;
and yet such is the love of God even to a guilty world,
that of the fulness of His Son Christ Jesus the Lord, "`have we all received,
and grace for grace.`"
"`God so loved the world that he gave his only begotten Son,
that whosoever believeth in him should not perish, but have everlasting life.`"
Who among us can contemplate the wondrous mercy and unutterable love,
wherewith God so loved the world,
without feeling a desire to pour forth a grateful acknowledgment of "`thanks be
unto God for his unspeakable gift;`"--even the gift of His Son Jesus Christ,
by whom came that grace which hath appeared unto all men;
by which grace alone are we saved from sin and from the wrath to come, through faith,
and that not of ourselves; for we have nothing, and are only sinners.
It is through faith which cometh from the Son of God, who loved us,
and gave himself for us; who is also "`the author and finisher`" of that one true faith,
which worketh by love, and purifieth the hearts of those who believe in its saving,
cleansing power; which giveth the victory over the evil propensities of fallen nature,
and over every temptation of the devil.

The word of the Truth of the gospel flowed freely to these dear people;
for whom my desire was,
that they might not rest satisfied with making an empty profession of religion,
but "`believe in the Lord Jesus Christ, and be saved.`"
Although at the close of the meeting I felt as if my strength was renewed for the work,
I should, without such sustaining help,
have been dismayed at the burden which still rested upon my mind.
After the meeting broke up many of the people flocked about us; amongst others,
I shook hands with an aged female of rank,
considered by the people higher than their king:
king George himself was one of those who helped to carry her on their
shoulders--she being unable to walk any considerable distance.
Her placid countenance, and manner altogether,
bespoke that she had good will in her heart towards us;
and the remembrance of the interview, though short,
always brings with it a feeling of peaceful tranquillity to my mind.

11th.--Yesterday, engaged on board, bartering for the commodities brought by the natives,
not being willing to turn them back, although what they brought was often almost useless.
In the afternoon landed and conveyed to be deposited in the mission-house,
twenty-four English Testaments and six Bibles, six Spanish Testaments, six French ditto,
and six Portuguese ditto; one French Bible was given to Charles Simeon,
a native of France, now settled here.
Whaling vessels and others, not unfrequently at the present day,
fall in among the different groups of these islands; by some on board such vessels,
a copy of the Scriptures is often prized, as we have experienced;
and individuals are here and there to be found, of different nations,
whose lot has been cast among the natives from a variety of causes; some by shipwreck,
others by sickness, left by the ships to return if they can,
or remain the rest of their lives among the natives, wandering from island to island.
Some marry and bring up children among them.
If such understand a handicraft business, as that of blacksmith or carpenter,
ship or boat builder, etc., and there is no ardent spirit to be procured,
they generally fare well amongst the islanders.
Today the natives have furnished a supply of hogs;
but it is almost impossible to procure food, except the ninita,
(papaw) which remains but for a short time in a wholesome state.
At present the poor people are very destitute of the
vegetable food on which they are accustomed to subsist,
and frequently complain and make signs of being hungry;
but it is out of our power to supply their wants:
they never think of killing a hog for themselves,
they are mostly reared for sale and for the use of the chiefs.
In the afternoon went on shore with a present for king George,
consisting of a large chest of tools, a cask of flooring nails, and a ship`'s compass,
with sundry articles for his queen Charlotte.
Some articles had already been given to Josiah Tubou, the king of Tongataboo,
when on board the Henry Freeling.
Today we took with us some things considered suitable for his queen Mary,
so that no preference might appear on our side,
more particularly as Josiah Tubou is an older man, and much higher in rank.
King George is however very assiduous in giving him the preference in everything.

13th.--At two o`'clock p.m., Charles Tucker, the resident missionary at Lifuka,
and his wife, accompanied king George and his wife Charlotte on board to dinner.
On taking our seats at the table,
I told Charles Tucker that it was our practice to endeavour to
feel a grateful tribute arise in our hearts to Him,
from whom all our blessings come; they were of course left at liberty:
when Charles Tucker called upon the king to ask a blessing,
which he did in a serious manner.
The parties were greatly amused with a set of William Darton`'s Scripture views, etc.;
and I believe were pleased with their visit.
We landed towards evening, and walked to the other side of the island for exercise;
this part is wholly enclosed by a coral reef,
which enables the people to procure fish in almost any weather.

When looking towards visiting Lifuka,
I thought as the principal part of the Tongataboo people, with their ruler,
would be assembled here, that I might not have to proceed to the latter island;
but I do not find that this will be sanction enough for me to stay away from it,
as it has dwelt much upon my mind for several days past;
I therefore believe it safest for me to go thither,
however opposed to my own inclination: if the Lord`'s presence does but go with me,
it is enough; for in His presence only there is life,
and at His right hand durable riches and righteousness, yea pleasures for evermore.
The desire and prayer of my heart, and I believe it may be added,
my greatest delight also, is to be found labouring to exalt his great and adorable name,
and to promote the extension of the blessed Saviour`'s kingdom in the hearts of mankind.

On returning to the boat in the evening, several of the missionaries were upon the beach,
when I told James Watkin that I could not pass by Tongataboo,
offering him a passage with us to his family at Nukualofa.
Fearing to let the members of the mission separate
without requesting a select opportunity with them,
I told them that I should like us to have an hour or so together,
in the presence of the Most High, before they separated;
this proposal was accepted with openness,
and everything made to give way for bringing it about:
tomorrow evening at six or seven o`'clock was mentioned
as the probable time for our meeting together.
When we got on board I told Captain Keen, that as matters then stood with me,
I saw nothing in the way to prevent our going towards Tongataboo,
and that the water casks had better be filled up tomorrow,
as the beginning of the ensuing week might be looked to
as the probable time of our leaving this place.
It is expected that the Vavau missionaries will
return in two or three days from this time.

14th.--Engaged on board bartering with the natives during the fore-part of the day.
A large canoe came alongside before dinner with a present from king George, viz.,
six spears, two bundles of native cloth, a large floor mat, and two orange cowries,
which in days past were considered the most valuable
ornaments worn by the rulers of these islands,
and are very rarely met with at present.
The bearer of these articles is a Portuguese, but understands English;
he said that the king was desirous to obtain from me an English spelling-book.
This token of the king`'s good will was verbally acknowledged,
and the messenger himself presented with a Testament in the Portuguese language.
My mind in the midst of many interruptions attendant
upon bartering with the natives and other duties,
had to sustain a heavy load of exercise,
in the prospect of meeting the missionaries and their families in the evening,
which to my view was no small matter.

Landed in the afternoon, and drank tea at the mission-house.
About the time agreed upon, the whole of the families,
except the wife and young children of John Hobbs,
(whose numerous family could not be left alone,)
assembled in a large room in Charles Tucker`'s house,
and sat down together in silence.
I endeavoured to keep my mind stayed in humble dependence upon Him,
who commands the morning, and causeth the dayspring to know his place;
and after dwelling a considerable time in silence,
it was with me to bow the knee in supplication unto Him,
who inhabiteth the praises of eternity,
and "`covereth himself with light as with a garment;`"--
and to ask in the name of our Redeemer,
that His life-giving presence might be near on the occasion,
to subdue in us everything that stands opposed to His righteous principle of light,
life, and love;--that His power alone may rule, and preserve our hearts, etc.

After sitting down again, a quiet season was vouchsafed,
though a further time of silence was to be passed.
There seemed much to travail under before the way was fairly opened for me,
to declare the indispensable necessity for each
of us to know for ourselves the will of God,
seeing that Christ has said,--"`not every one that sayeth, Lord, Lord,
shall enter into the kingdom of heaven;
but he that doeth the will of my Father which is in heaven.`"
That before we are in a state to be entrusted with the knowledge of the Divine will,
the will of the creature must be laid low,
and subjected to the will of the great Creator; our bodies must become living sacrifices,
holy, acceptable to God; we must be altogether transformed,
and our minds renewed by the power of the Spirit of the Lord Jesus, believed in,
and operating in us, "`that we may prove what is that good and acceptable,
and perfect will of God,`"--as defined by the apostle Paul to the Romans.
Everything depends upon this,--to know the will of God in the first place,
and then to do it.
"`To obey is better than sacrifice, and to hearken than the fat of rams.`"
It is those only who do the will of the Father,
that shall know of the doctrine of His well beloved Son, in whom he is well pleased.
It was with me particularly to urge this upon all present, both male and female,
for both are one in Christ;--that all might, by implicit obedience,
know for themselves the will of God, and Christ to be unto them wisdom and righteousness,
sanctification and redemption.
The whole of our Lord`'s precepts must be regarded as binding upon His followers;
we cannot choose for ourselves, by selecting some parts and leaving others.
His example must be followed in everything, in every part,
to the denial of self in all things.
"`He that will be my disciple must deny himself,
take up his daily cross and follow me,`"--these are the terms which He prescribes;
we must take up a daily cross to our own corrupt wills and inclinations.
It seldom occurs, that the path chosen for us, or the thing required of us, is what we,
as creatures, should choose for ourselves, or can very readily yield obedience to;
it is against the nature of flesh and blood,--it does not suit our inclination;
if it were not so, and our will was consulted,
there would be no cross to take up,--it would be a sacrifice which costs us nothing.
We must be willing to part with and to suffer the loss of all things for Christ`'s sake;
and in following the great example which He hath left us,
we must in no part thereof deny Him before men,
nor be ashamed of Him and his words before men, lest He should also deny us,
and be ashamed of us,
before His Father and the holy angels,--according to His own
awful denunciation against such unworthy followers.

It was a solid and solemn season, the power of Truth was over all.
Before leaving the shore,
I mentioned the probability of my again attending a meeting of
the natives on the following First day morning,
to which no difficulty seemed likely to present.

15th.--In the afternoon we went on shore,
with a view to getting things so settled as to insure
no failure in my seeing the natives tomorrow.
James Watkin again kindly undertook the office of interpreter;
and I returned on board satisfied with the arrangements agreed upon,
and strengthened to look forward with some degree of confidence and resignation.

16th. (First day.)--This morning went to Charles Tucker`'s house,
to wait until the natives were collected together.
On the way was much gratified to learn,
that it was concluded to dispense with many of the
exercises usual at their meetings on First days.
This circumstance had come about without my knowledge,
although I had before-time mentioned,
that the meetings lasted longer than the people were able to bear;
being densely stowed upon the floor, almost without a circulation of air,
in a tropical climate.

After I had taken my station by the side of James Watkin,
a general silence prevailed over the multitude assembled;
and in due time my mouth was opened to revive in their hearing, that--"`Whoso is wise,
and will observe these things,
even they shall understand the loving-kindness of the Lord.`"
But the first thing to be done in order to partake of the Lord`'s loving-kindness,
which is better than life, is to believe in the Lord Jesus Christ; without this,
none can behold his wonderful works, nor praise Him,
for his great goodness to the children of men.
When the Saviour of the world was on earth, and dwelt among the sons of men,
he did not many mighty works in some places, because of the unbelief of the people;
and it is the same at this day.
There is no way unto God the Father, but by the Son; and we can never know the Son,
to be "`the way, the truth,
and the life,`" unless we believe in His power to save to the uttermost,
all those that are willing to come unto God by him.--"`For he that cometh to God,
must believe that He is, and that He is a rewarder of them that diligently seek him.`"
Without faith it is impossible to please him:
but how great is his goodness to the humble believer that feareth him,
--to them that wait for him,--to the soul that seeketh him.
Yea, eternal life is the reward of all those, who by patient continuance in well-doing,
thus seek the Lord with believing hearts.
While tribulation, anguish, indignation and wrath, will be the portion of unbelievers,
and of those who are contentious;
who disregard the shinings of the true light that
lighteth every man that cometh into the world,
who obey not the truth, or the manifestations of the Spirit of truth,
which convinceth of sin.
My heart was enlarged, and the way fairly opened before me,
to proclaim amongst the people the truth as it is in Jesus;
and to tell them that salvation was nigh unto them that day:--
it depended upon themselves,--it remained with themselves,--to
"`believe on the Lord Jesus Christ and be saved.`"
Not merely to believe that he came in the flesh,
and died for the sins of the whole world;
but to believe in the coming of his Holy Spirit into their hearts,
to purge away their sins, and save them from the wrath to come,
while the day of their visitation is mercifully lengthened out.
In the same love which brought me among them,
I bade them all an affectionate farewell in the Lord.

Many of them with whom we were personally acquainted, flocked round us to shake hands,
amongst others, the king and his principal chiefs.
And now believing myself clear of the island,
we paid a short and final visit to the mission-house, and then returned to the vessel,
having no other prospect before me,
but that of sailing in the morning towards Tongataboo.

[.offset]
The following are copies of letters received while at the island of Lifuka:--

[.signed-section-context-open]
Lifuka, October 10th, 1836.

[.salutation]
Dear Sir,

We, the Wesleyan missionaries, assembled at our annual district meeting,
beg leave sincerely to congratulate you upon the hitherto
successful prosecution of your missionary voyage;
and to express the unfeigned pleasure we feel in seeing
you in this part of the great missionary field;
and we trust that your efforts to promote the knowledge of the true God,
will have had the blessing of God;
and that you will have the pleasure of seeing at the right hand of the Most High,
many who, from among the Gentiles have been turned from darkness to light,
by your instrumentality.

We beg leave too to offer you our best thanks for the
kindness you have manifested in bringing five of our members,
with our families, to this place; and we pray that He,
who does not forget the smallest kindness done to the least of His disciples,
may reward you with every needful blessing, both for soul and body:
and finally grant unto you and yours, Eternal Life, through Jesus Christ our Lord.

[.signed-section-closing]
Signed on behalf of the meeting,

[.signed-section-signature]
John Thomas, Chairman

[.signed-section-signature]
James Watkin, Secretary

[.signed-section-context-open]
Lifuka, Ilaabai, October 17th, 1836.

[.salutation]
Dear Friend,

We, as Wesleyan Methodist missionaries, labouring in the Friendly Islands,
beg leave at this our annual meeting, to express our sentiments to you,
in reference to your visiting the various mission stations in these seas.

We admire the principle which induced you to
sacrifice the blessings of civilized society,
and to quit the land of your fathers,
in order to witness the glorious effects of the gospel among heathen nations,
and preach among the Gentiles the unsearchable riches of Christ.

We doubt not but you have been richly rewarded in your
own mind for all the sacrifices you have made,
and the privations you have been called to endure while
prosecuting the great work in which you are engaged.
We rejoice that the Lord has so signally blessed you hitherto in your undertaking;
and pray that his kind Providence may still preside over you, and make your way plain.

We have been very much gratified by your visit to this part of the great mission field.
We hail you as a fellow-labourer in the gospel, and wish you God`'s speed.

The very great kindness which you and your excellent
son have manifested to us in a variety of instances,
has produced a deep impression on our minds;
be assured you will long live in our affection; and we hope,
that your addresses and conversation will produce their desired effect.

And now, as you are about to take your departure from this place, we commend you to God,
and take an affectionate farewell, until we shall meet in our Father`'s house above.
We remain dear friend,

[.signed-section-closing]
Yours affectionately,

[.signed-section-signature]
John Thomas, William Allen Brooks, John Hofps, Stephen Rabone, James Watkin, John Spinney,
Charles Tucker

17th.--Unmoored at the earliest dawn of day.
Soon after we were ready, our passenger James Watkin came on board,
with the whole body of missionaries then at Lifuka.
Their stay was necessarily short indeed,
scarcely longer than while they delivered up their letters and parcels,
for not a few of their friends and connections in Sydney and England.
On their departure the anchor was weighed,
and we immediately proceeded towards the opening in the reef; making all sail,
if possible, to clear the principal dangers of the Haabai group, before nightfall.
We had a pilot with us, a native of Tongataboo,
well acquainted with the different channels;
but who could not understand many words of English.
The wind became more opposed at sunset;
and instead of our being in tolerably open water,
we were entangled with the long and dangerous reef off the island of Anamooka;
and were at last compelled to run down to its leeward-most point,
in order to get clear of its crags.
Whilst the sound of the breakers thundering upon the reef could be heard,
we were still within its reach; but as the noise became fainter,
we considered ourselves beyond its outermost point,
and ventured to haul up to the south south-east, for the night.

19th.--About ten o`'clock were favoured to get sight of Eouaigee,
owing to a strong current, which had, during the night, hurried us away to the eastward;
and the wind being strong, by noon the island of Tongataboo was distinctly to be seen,
though the weather was thick and hazy.
By two o`'clock we were abreast of the settlement of Nukulofa,
and were favoured to anchor safely in fourteen fathoms water, in a place well sheltered,
except when the winds blow from the northward and westward:
the north side of this island is one mass of reefs, rocks, and small islands.
Twenty-two of these islands are in sight from the vessel;
and in several directions the surf breaks incessantly upon sunken reefs,
which form the principal shelter between us and the main ocean.
A brig under English colours was entering the narrow channel
from the southward at the same time as ourselves;
but she took a different route from us, and anchored off a heathen settlement,
several miles distant from Nukulofa: she proved to be the Guide,
a Sydney whaling vessel in want of supplies.
Soon after having anchored, a canoe arrived,
and carried off our agreeable passenger and companion, James Watkin,
whose wife could be seen on the shore waiting for her husband.
Having had but little rest for the two past nights, we remained on board;
and the afternoon turning out wet, but few of the natives visited the vessel.
It is indeed renewed cause of humble thankfulness to be again and again preserved
amidst these dangerous and little frequented groups of the Friendly islands;
and particularly during our stay at Lifuka,
where there were but few feet of water to spare between the rocks which were visible,
and the bottom of our vessel.
Had one of those furious hurricanes been permitted,
which are occasionally witnessed by these islands,
her destruction would have been inevitable.
The very day after our arrival, (as before noticed,) the wind came in upon us,
and the atmosphere assumed for a time a threatening appearance:
but after having been shown our critical and helpless situation,
and renewedly made sensible that there was no refuge,
but in that power which winds and waves obey,--the storm was hushed,
the wind gradually shifted to its usual trade-quarter again;
and the rod was no more lifted up during our stay of about a fortnight.
Some of the missionaries, who well knew our dangerous situation,
were perhaps more alarmed for us than we ourselves were,
who were comparatively ignorant of many circumstances, peculiar to that neighbourhood;
indeed,
one of them afterwards acknowledged his not having been able to sleep on our account,
when the change of weather took place,
and the clouds gathered blackness in the stormy quarter.

We find that a large portion of the inhabitants of
Tongataboo still retain their heathenish practices,
and hitherto could never be prevailed upon to cast away their idols.
They keep those who have embraced Christianity in constant alarm,
and cause them to keep up a strict watch, and to live within strongly fortified places,
as in a state of actual warfare.

20th.--A few of the natives came off this
morning with some poor hogs and a few vegetables;
but for these and for their shells, they have learned to ask very extravagant prices,
which is owing we are told,
to their having calls not very unfrequently from our men-of-war,
who purchase largely their hogs, yams, shells, etc., without regard to price.
In the forenoon Charles and myself sat down together in the cabin.
It was a low season with me, as when the bridegroom is taken away;
towards the conclusion, a degree of strength was graciously afforded,
although my soul`'s enemies were still felt to be lively and strong.
At one o`'clock p.m., landed for the first time at the settlement of Nukulofa;
but the tide being low we were compelled to
submit to being carried over a part of the reef,
the water being too shallow to float our boat.
James Watkin, with two children, was on the beach, ready to conduct us to his house;
and we spent an agreeable afternoon with his family.
In the course of the time we were there, Abraham a brother of Josiah Tubou the king,
came in to see us:--he seems a serious steady man, from forty to fifty years of age,
and is considered a religious character.
The settlement of Nukulofa is surrounded by tall trees, so thickly planted,
that a man cannot pass between them, having several sally-ports or entrance gates,
which are secured at night in a substantial manner.
Outside this wall of trees, which have rails connected with them, is a very deep trench,
the coral taken out of which forms an additional barrier of defence outside the trees,
and renders the approach almost inaccessible.
It was pleasant to find that the missionaries have lived
latterly entirely outside of these fortifications,
without any defence beyond a fence of slender canework.
On returning to the vessel at sunset, we found a large shark hanging to her side,
which had been struck with a harpoon, by some whalers who had called on board.

21st.--Landed in the afternoon and made our way to the mission-house,
taking with us a variety of drugs, and numerous articles of clothing for children,
for the use of James Watkin`'s family,
with a quantity of dresses suitable for the native children.
It is a great privilege, through the kindness of my dear friends in England,
to be able to administer, in some degree,
to the wants and comforts of those to whom I am most certainly very greatly indebted;
and without whose kind and brotherly assistance, my mouth, in most instances,
must have been closed, as regards declaring the word of life in the different islands.

22nd.--In the morning some of the heathen part of the community came on board,
and appeared pleased at the treatment they met with;
some articles they brought were purchased,
by way of gaining their good-will rather than from necessity.
Abraham, the king`'s brother spent a part of the day with us;
after dinner he was presented with a broad axe.
Landed in the afternoon, and called upon Thomas Wellard,
a person connected with the missionaries here, who is about to return to Australia,
and has applied to me to give him and his wife a passage to Sydney; I can give no answer,
it being at present uncertain whether a direct course
to Sydney from hence will be a peaceful one;
time must decide our future destination.
All that man can do, is to endeavour to stand in the counsel of the Divine will,
and in humble resignation wait for its unfolding to the finite understanding;
and when once ascertained, then to do it with all his might.
Go thou and do likewise, with all thy might, whoever thou art,
who may perhaps read these fragments,
inscribed by one who has trodden the narrow path before thee; but who,
however unworthy of the least of all the Lord`'s tender mercies,
is at seasons comforted in believing, that he is on the way to the heavenly city,
none of whose inhabitants can say, "`I am sick.`"

Finding the necessary arrangements had been made to
open the way for my seeing the people tomorrow,
when collected in their place of worship, we returned on board,
and found some of the poor despised heathen
waiting with a quantity of cocoa-nuts for sale.
These nuts are such as are only fit for hogs,
being too old and rancid for the use of the people,
who are very short of food at this time.

23rd.--On going to the meeting we found the house quite filled,
with many standing and squatting outside, and others coming towards it.
My truly kind and faithful interpreter, James Watkin,
did everything in his power to open the way clearly for me,
by explaining the translation of the Morning Meeting`'s certificate, which he read.
The reading was succeeded by a time of silence, until I stood up,
and was strengthened to express the desire of my heart,
that they might all come to the knowledge of the truth as it is in Jesus, and be saved.
That a mere profession of the Christian religion would avail them nothing:
truth in the inward parts, the Lord desired.
They must come to know the Holy Spirit of the Lord Jesus,
(which is the Spirit of Truth,) in their own hearts;
which the blessed Saviour promised should come in his name,
even into the hearts of his followers, and abide with them for ever.
I had to speak of the greatness of the love of God,
in sending his Son into the world to save sinners.
I doubted not that many of them believed in His coming in a body of flesh;
but I wanted them to believe in His coming in the Spirit into their hearts.
I had to contrast their present state,--although it is to be feared,
in too many instances, making but an empty profession of the Christian religion,
and remaining as yet, in great measure,
strangers to the power of Christ,--with the dark
and heathenish condition they formerly were in,
without hope in the world; laden with sin, hateful, and hating one another.
Many of them had lived long enough to see and know the
difference between the past and the present;
and to be able to discern what are the works of the flesh,
and what is the fruit of the Spirit.
"`What fruit had ye then in those things whereof ye are now ashamed?
For the end of those things is death,`"--the sure wages of sin:
"`but the gift of God is eternal life by Jesus Christ our Lord.`"
They were earnestly entreated, in the love of the gospel,
to come to this precious gift of God, to turn inward to this light;
and they would find to their inexpressible comfort,
that it is none other than the Holy Spirit of Him, of whom Moses in the law,
and the prophets did write.
It was a precious meeting:
the people sat as if afraid to move,--such was the solemnity that prevailed over us.
Power belongeth unto God; and the praise and glory are his for ever.
Remained on board in the afternoon with our own people.

25th.--Fakafonua, a heathen chief, who can talk a little English,
paid us a visit this morning.
He had been invited to breakfast and was treated with kindness.
He behaved in a solid manner, whilst a chapter in the Testament was read,
and during silence.
An axe was presented to him before leaving the vessel.
In the afternoon it was with me to inquire,
whether it was practicable to obtain an interview with these poor heathen people,
who though apparently lost sight of, are still the sealed inheritance of the Lord Jesus.
James Watkin said it might be done,
and thought the best way would be to take them by surprise; for if notice was given,
as I had suggested, they would only get out of the way.
It is true, it may only tend to exposure, without any beneficial results;
but this must be left: to omit, however, making an attempt to visit them,
might make work for repentance at a future day,
when the present opportunity presented to me is for ever gone by.
May the Lord Most High prepare their hearts to receive,
and mine to declare to them salvation by Christ Jesus.

26th.--This morning the fleet from Lifuka made its appearance,
consisting of seventeen large double canoes.
The first which reached Nukulofa had on board Josiah Tubou and king George,
(alias Taufaahau), the kings of Haabaiand Tongataboo.
We afterwards, in company with James Watkin, attended the king`'s kava party,
assembled in the neighbourhood to welcome the
arrival of the different parties from Lifuka,
who had been to attend the general congress.

26th.--The kava ceremony was performed in the open air,
the heads of the islands only being under cover, and the strangers, when any are present.
The people were squatted in regular order, forming three sides of a square,
in front of their king and chiefs.
The fourth side was an open building, on the floor of which sat Josiah Tubou,
with three of his principal men on each side of him,
the admiral of the fleet directed the different proceedings of the meeting,
but Taufaahau mingled among those who were to prepare the kava.
As strangers, we were allowed to sit upon the floor of the building,
with the rulers of the people,
which afforded us full opportunity of seeing the whole process.
The kava root, after being well crushed with a heavy pole,
was separated into small parcels, and handed to different individuals,
whose names were proclaimed aloud, being chosen for having good clean teeth,
and sweet breath.
When they had chewed a mouthful of the root sufficiently,
it was placed in a cup made from the banana leaf; these cups were finally collected,
and their contents emptied into a large bowl, employed solely for the purpose.
Water was then poured into the bowl, and when the chewed root was sufficiently saturated,
a large bunch of very fine shavings, prepared from the purau bark was used as a strainer,
and the liquor repeatedly passed through it, until clear of all apparent sediment.
When pronounced ready, it is ordered to be served up,
and every cup that is filled is retained,
until the name of the person is declared to whom it should be handed.
We had to take a share of the nauseous liquid, but of course, a little served the turn.
Many heavy burdens of baked food, each brought upon a pole on the shoulders of two men,
were laid in front of the king and chiefs; who directed to whom a basket should be given.
Many of these were ordered to the men of the fleet, who were numerous on the occasion,
as the largest canoes carry at least an hundred men.
Thanks were repeatedly given to those who had the fatiguing part of the work,
especially to the kava makers, the food bakers, the chewers, the carriers,
and the cup bearers.
Returned on board as soon as the tide was high enough to carry us over the outer reef.

27th.--Before eight o`'clock a.m., James Watkin came on board,
bringing with him five natives,
to accompany us in an attempt to procure an interview with a body of the heathen,
residing at the settlement of Mua, in a fortified position.
We left the vessel forthwith, and proceeded towards the lagoon,
at the entrance of which a bay of islands in miniature is formed.
At eleven o`'clock, we were abreast of the settlement;
but the boat grounding upon a sand-bank, at a considerable distance from the shore,
one of the natives, Isaackee, waded to the landing-place,
where a number of the people were collected on seeing the boat approach their territory.
On being informed by Isaackee who we were, and what the object of our visit,
they denied that the chief was at home.
Our man returned to us and said the chief was not at home,
and that Charles and myself might land, but not the missionary.
Appearances on the shore were not very inviting,
as the war clubs were plainly seen in the hands of some of the natives.
James Watkin advised us not to land.
I was not satisfied, however, without making some further attempt to get among them,
and Isaackee was dispatched again, to say, that our coming on shore would be useless,
without the missionary to interpret.
He did not at all hesitate to go; but, apprehending some mischief might arise, said,
on leaving us, '`if they kill me,
it will be nothing.`' After a considerable parley had taken place, our man returned again,
and said,
that '`we might all come on shore;`' but now James Watkin refused to accompany us,
as the objection had appeared to be against him only.
I felt a little disappointed, but concluded to land, at all events,
without further debate.
Charles and myself were then conveyed to the shore by our native boat`'s crew;
and although a considerable number of these people immediately flocked about us,
I had not the least apprehension of danger, for the fear of man was cast out.

We ascertained afterwards that at least twenty muskets were pointed upon us,
from behind a strong wooden fence, in readiness, had any affray taken place.
We had in our hands only an umbrella each.
We proceeded towards the settlement, under an escort of the people,
until we had passed through the gates of the stronghold,
and at length reached the habitation of the chief.
We found him at home, and with a number of his people squatted ready upon the floor,
waiting our arrival.
The chief, perceiving me at a loss to distinguish him from the rest,
moved aside to the log of an old tree, upon which we both sat down together: this,
I thought, was correct on my part, from the signs that he made to me.
He could talk a few words of English; but could understand little that I said.
I made him understand that they had a shipwrecked sailor among them,
of whom I had heard previously, and made signs for him to be fetched;
but he did not make his appearance,
and was probably ashamed of being seen by his countrymen.
The chief was evidently desirous of asking questions;
but I signified that without the missionary we could do nothing.
Some people then had orders to go for James Watkin, who arrived in less than half an hour.
During this interval the number of people increased,
and a root of the kava plant was laid at my feet, as a token of good-will towards me.
An offer of some of the liquor was then tendered, which I accepted,
to show that I had nothing but good-will towards them.
Some persons were then appointed to chew the root, and prepare this odious drink, which,
in due time, was handed to me.
I drank some of it before them, and handed the remainder to one of the people,
which I had learned was a usual practice in such cases.
James Watkin now entered into conversation with the chief,
and believing that things were going on smoothly,
I proposed that the translation of my certificate from
the Morning Meeting should be read.
It was patiently and attentively heard to the end,
with ample explanation to elucidate the cause of my coming among them.
I had then to tell them, that the God whom I serve is a God of love and mercy,
and willeth not the death of a sinner, but rather that all men everywhere should repent,
return unto Him and live; and that such is the love of God to his creature man,
that he gave His only begotten Son to save them from their sins,
"`that whosoever believeth on Him should not perish, but have everlasting life.`"
That I was not satisfied to leave their island without telling them
of the good things which God hath prepared for those that love him:
I declared that salvation was come nigh unto them,--yea, placed within their reach,
and that by Jesus Christ;--He is Lord of all;
through the shedding of whose precious blood the gift
of the Holy Spirit was received for every mortal,
whether son or daughter,--for the whole human race,--even for the rebellious.
I told them,
that I did not come among them to persuade them
to turn to this way of life or that way of life;
but to turn them from the darkness they were in to the light of Christ,
"`from the power of Satan unto God.`"
To this Holy Spirit I desired that their hearts might be directed,
and to the patient waiting for Christ, that they might know Him to be in them,
"`who liveth and abideth for ever.`"
The above is the substance of what I had to express among them;
and though some individuals mocked and behaved rudely, saying aloud,
"`I wish he had done;`" so that James Watkin stopped, and reproved them for their behaviour;
yet the Divine Power was over others,
and I believe that its influence was felt by the chief, as I observed,
when I had finished and sat down, that his countenance was entirely changed,
and he said that, '`I had done well in coming.`'

Afterwards, by way of accounting for their not setting food before us,
as is their usual custom with strangers, (which I firmly believe would have been done,
had it been in his power,) he said, that they had very little to eat,
and that it would be about five months before they could have plenty again;
looking forward to the rainy season setting in.
This I knew to be the case, as the famine in all the Friendly Isles was grievous,
but more so at Tongataboo, than at Lifuka, as the bread fruit, banana, yam,
sweet potatoes, etc., were almost wholly destroyed by a hurricane;
and they were at this time eating the roots of the banana and tea tree.
It has been painful to observe how many have complained to us of hunger:
some would put their hands on their stomachs, and exclaim, '`dead, dead.`' It is, however,
a certain fact,
that in those places where the people are under the control of the missionaries,
although suffering much,
they are much better off for food than the heathen part of the community.
Some of these, called heathen, particularly the chief just alluded to,
and the other that came on board our vessel, declare,
that they perfectly understand the nature of Christianity,
and the blessing that it bestows, but they say, '`If we were to follow it,
we should have to give up all our present delights,--put away all our wives but one,
and all our bad habits.`' They seem sensible of the sinful condition in which they live;
for they say, in effect,
'`it is impossible that we should be saved,--it cannot be.`'
Their poor bodies very generally bear the marks of violence,
from the habit they are in of lacerating and burning themselves,
as an indication of mourning for the dead; this was strikingly apparent.
The little fingers on both hands had been in many cases cut off,
and offered as sacrifices to avert the evils they most dreaded.
This we found to be very general among those who are called Christians,
but more particularly remarked it to be the case with those that are grown up;
the rising generation of these now retain them.
This circumstance we discovered on shaking hands with them,
from their kings and chiefs down to the humblest individuals of their tribes,
both male and female.
We parted from this heathen chief in a friendly manner: his name is Fatu.
It gave me much pain, to hear from his own mouth, through James Watkin, that,
amidst all the wretchedness of a heathen life,
the miseries of his people were greatly increased by their intercourse with the shipping;
disease was fast sweeping them away.

It is a lamentable fact, that most of the vessels which touch at Tongataboo,
come to anchor on the heathen shores, because where the missionaries reside at Nukulofa,
there is not the same opportunity for the crew to indulge in their diabolical practices,
and promote the sale of rum, etc.
While we were at Tongataboo, two vessels under the English flag,
and one under the American, anchored near the heathen settlement; where, it is true,
there is much better shelter from the sea, than at Nukulofa; at the latter station,
however, the Henry Freeling rode sufficiently secure.
Such as do anchor at Nukulofa, are uniformly respectable,
and the crews under proper restraint:
it was quite the reverse with those which went to the other place,
during our stay at the island.
It was late in the afternoon before we got back from the heathen settlement of Mua.

28th.--Today, Josiah Tubou, and Mary, the king and queen of the island,
with their two sons dined on board, they brought with them James Watkin, as interpreter.
A prodigiously large fat turtle, and a quantity of fine yams,
were brought as a present by our guests.
These yams we understood to have come from Vavau; that island being hilly,
the crops in the valleys, were more sheltered from the late storm,
but as Lifuka and Tongataboo are flat, level islands,
no part escaped the fury of this sweeping blast.

No opening presented, during the stay of our royal visitors,
for any thing like edifying conversation,
but I believe the heat and the motion of the vessel, made some of them a little seasick,
as the wind was strong and a swell of the sea tumbled in upon us.
The king, however, expressed his satisfaction with the visit,
and they were all much pleased with the inside of the Henry Freeling.
The tide being low, our boat could only approach the edge of the reef;
but the queen being barefooted, had no difficulty in paddling over the coral bottom,
a few inches under water.
The king preferred taking a passage in a small canoe, with a single native to manage it.

29th.--The morning proved boisterous,
but we landed for an hour about the time of high water,
being desirous to speak with James Watkin,
not feeling easy to let an opportunity pass away without improvement,
of attending the native meeting tomorrow, if it should rest with me to do so.
The fleet from Haabai, having arrived since last First day,
has greatly increased the number of people from the other islands.
I found James Watkin ready as usual, to render me every assistance in his power,
and the morning was mentioned, if it were concluded to come,
and the weather did not prevent our landing.
It may be the last opportunity that I shall have to see
such a body of the Friendly islanders together;
and such an one as could scarcely have been calculated on;
and is of rare occurrence at any time, if indeed it ever took place before this season.
No other motive, I trust,
prompts in me a desire to avail myself of the
opportunity thus placed within my reach so unexpectedly,
than what is induced by that love which embraces the whole human family,
and would bind all the children of men in the Lord`'s "`bundle of life`" everlasting.
May the shout of a king be heard among these people,
and the glorious majesty of the spiritual kingdom of our Lord and Saviour Christ,
be unfolded to their understanding,
by the same Almighty power which opened the heart of Lydia,
in days that are over and gone, to His own praise and glory.

30th. (First day.)--The state of the weather combined
with other circumstances to weigh down my mind,
when looking towards attending the native meeting;
and the secret prayer of my heart last evening was,--'`Help, O Lord,
for thy great name`'s sake, and for the sake of Him who died, the just for the unjust,
that He might bring all mankind unto Thee.`'
The morning was rough and boisterous;
and there not being water enough for the boat to pass
over the reef into a sheltered landing-place,
seemed to throw difficulties in the way of our getting on shore.
This being the position of affairs,
I determined to take an arm-chair from the vessel to render the
fatigue of transporting us more tolerable to the willing natives,
and divide the weight more equally between several men;
two of these who had been watching our movements,
were seen wading towards the edge of the outer reef, as our boat approached.
We were, however, at last placed safely upon the beach,
without any material inconvenience to ourselves,
though the task was laborious for our burden-bearers.
I felt much discouraged soon after day-break,
and could almost have reasoned myself into a fancied liberty to remain quietly on board;
but it did not appear that I should stand acquitted,
unless a firm attempt to get through was first made on my part:
before leaving the vessel this gloom was measurably dispelled,
and I was strengthened to press forward,
and with humble resignation to bind the sacrifice as to the horns of the altar.

On account of the inadequate dimensions of the
building to accommodate the thousands assembled,
several hundreds were left outside;
but they endeavoured to keep as near as they could to
the place where the speaker is best heard.
James Watkin occupied a short space of time in speaking to the people,
and then left them in expectation of something from my mouth,
when a general silence prevailed.
It was not long before I stood up, in great weakness and fear,
and told them that I felt myself to be indeed a feeble
instrument in a cause so great and dignified;
but they might remember, that the Lord`'s servants formerly, as now,
had nothing of their own with which to satisfy the cravings of a hungry multitude.
But when the Great Master was pleased to command a blessing,
the few loaves and fishes were so multiplied, that there was much more left,
after the people were fed to the full, than there had been before they began to eat.
It is only, as He is pleased to qualify any one to speak in His name,
and to open the understandings of them that hear, that any can be availingly benefited.
"`Without me ye can do nothing,`" said Christ;
and though some may feel desirous to follow Him in the way of self-denial and the cross,
yet when an hour of trial comes, such is the weakness of the flesh,
that we are ready to shrink for fear of man, for fear of persecution;
and are ready to deny Him, who suffered for us,--who died that we might live for ever.
But although without Christ we can do nothing,
yet through His strength we can do all things;--through the strength of His Holy Spirit,
in our inner man, we can do all things to the praise and glory of God.
It is in the Holy Spirit of Christ Jesus, that we must believe;
and so wait to hear His voice, and obey Him in all things.
This is that heavenly Prophet, of whom Moses spake to the children of Israel,
whom the Lord their God should raise up unto them from amongst their
brethren:--"`A Prophet shall the Lord your God raise up unto you,
from amongst your brethren, like unto me, (said Moses;)--Him shall ye hear in all things;
and the soul that will not hear this Prophet shall be cut off from amongst the people.`"
In due time this was fulfilled;--this Prophet of the Lord was
raised up amongst the people,--born at Bethlehem in Judea;
in whom the fulness of the God-head dwelt bodily; and of whom the holy Father testified,
and said,--"`This is my beloved Son, in whom I am well pleased; hear ye him.`"
This is the Prophet whom we must hear in all things,
as the children of Israel in that day heard Moses in all things;
but with this difference,--Moses was only heard while in the flesh upon the earth,
and this Prophet speaketh from heaven, by His Holy Spirit in the soul of man.
How needful then for us to wait, and to watch, and to pray,
that we may hear and obey Him, who speaketh unto us from heaven in righteousness,
and is mighty to save the soul from sin.
It is by the power of the Spirit of the Lord Jesus,
that our hearts must be cleansed and purified from every defilement:
it is this that searcheth all things;
our secret thoughts and imaginations are all laid open before it;
and nothing that is unclean or impure, that worketh abomination, or that maketh a lie,
can stand before this heart-searching power of the Lord; which, as a fire,
consumeth all that cannot bear His righteous judgments.
But if this heavenly Teacher is heard, and obeyed in all things,
with meekness and resignation,--if we fear to offend or grieve this
Holy Spirit of the Lord,--it will purify us even as He is pure;
and it will prepare us for the reception into our
hearts of the spiritual kingdom of Christ Jesus.
This is the kingdom that men are commanded, above all things,
first to seek;--with the sure promise of our Lord,
that "`all things needful should be added`" unto them.
What then remains to prevent mankind from receiving the kingdom of Christ Jesus,
but hardness of heart and unbelief in his spiritual appearance in man.
We can scarcely suppose that any will earnestly seek for that,
which they do not believe can be found.
Hopeless and forlorn indeed is the situation of such as these: in vain do they say,
that they believe in Jesus Christ as the Saviour of the world,
and that there is no salvation but by Him;--whilst they remain
strangers to His heavenly power to cleanse their hearts from sin,
for want of believing that He is come in Spirit: therefore they know him not.
It is a consideration,
as affectingly awful as it is true,--that
although He is the Saviour of them that believe,
yet without we know and witness the power of His Holy Spirit to save us from our sins,
He is no Saviour of ours: our belief is vanity,
and will end in vexation of spirit;--we are not among
them that believe to the saving of the soul,
notwithstanding all our profession of religion before men.

This is the substance of the testimony I had to bear amongst these people,
though but a part of what I had to say.--Inviting and encouraging them, above all things,
to seek first and in earnest the kingdom of heaven,
and the righteousness thereof,--and with desires for their present and eternal welfare,
I sat down.
The place was exceedingly crowded, and the people were vory solid and attentive.
A number of English persons were present, probably in part from the shipping.

Spent the afternoon on board with our own people.

Eleventh Month 1st.--Believing that it would be best for me to leave here a
copy of the address presented to those in authority at the Sandwich Islands,
to be translated in the Tonguese language,
for the kings and rulers of the Friendly Islands;
the subject was this afternoon mentioned to James Watkin,
who concurred in the apprehension that it would be useful to them.
Under these considerations, a fair copy was drawn up by Charles,
and put into the hands of James Watkin, accompanied by the following letter,
which was addressed to the missionaries at the Friendly Islands.

[.salutation]
Dear Friends,

The annexed, as will be seen on perusal,
was addressed to those highest in authority upon the Sandwich Islands, and was presented,
when the king and Kinau,
(the female in whom the executive power is
invested,) with several of the principal chiefs,
were assembled together to receive it.
It was translated at the time by the senior American missionary, Hiram Bingham;
and they afterwards expressed a desire that it should be printed.
Although its contents may be peculiarly adapted to the present
state of those for whom it was originally intended,
yet as the same interest dwells in my heart
towards the inhabitants of the Friendly Islands,
I thought no harm could arise from presenting a copy of it to Josiah Tubou and Taufaahau,
the kings of Tongataboo and Haabai;
as it is possible that some hints may be found applicable, (if not at the present day,
in a day that is to come,) to themselves, or to those who may succeed them in authority:
at any rate it exhibits a Christian principle, a standard,
round which all nations may rally with safety at all times,
and at every period of their existence.

I am your affectionate friend, in the bonds of the gospel--the soul`'s truest liberty.

[.signed-section-signature]
Daniel Wheeler

[.signed-section-context-close]
Henry Freeling, off Nukulofa, Tongataboo, 1st of Eleventh Month, 1836.
