== Chapter XXXIV.

[.chapter-synopsis]
* New Zealand
* Visit to the Mission-Station at Waimate
* War Among the Natives
* Meeting with the Mission Families
* Distribution of Tracts
* Native Meetings at Korarareka
* Address to the Missionaries
* Sail from the Bay of Islands
* Remarks on the Character of the New Zealanders
* Anchor Off Sydney
* Religious Engagements There
* Return to England

Twelfth Month 2nd.--Spent the forenoon on board,
and the afternoon at James Busby`'s with Charles Baker,
and three others of the missionary establishment.
James Busby is an amiable man, upright in all his dealings with the people;
and decidedly desirous of promoting in others
that which he conceives to be the duty of man.
Men of his general character are greatly needed to improve the present state of things,
as regards the best interests of the natives;
while the bad example of licentious foreigners might be checked,
and their influence to a considerable extent diminished.

3rd.--At eight o`'clock a.m., reached the station at Paihia,
and found that the absent missionary, and senior of the establishment, Henry Williams,
had returned to his family.
He had been to the southward to endeavour to persuade the hostile tribes,
who are butchering and devouring one another in a dreadful manner,
to desist and listen to terms of peace.
He reports that they are determined to persevere in the contest;
and though he has heretofore been successful in restoring peace among them,
they now turn a deaf ear to every proposition which he made to them.
More than six hundred of these poor creatures have been slaughtered;
and some of the missionary stations in those
parts are entirely broken up for the present.
One of their houses had been destroyed, some of the families stripped of everything,
and others had taken refuge in flight.
Henry Williams brought with him a boy,
whose sister had been murdered in a recent struggle of the contending parties.

On leaving Henry Williams and his family, we proceeded towards Keri-Keri,
in a boat well manned by natives belonging to the mission,
having sent our own boat and crew back to the vessel from Paihia.
We reached the station of Keri-Keri about noon,
and were kindly received by James Kemp and his wife:
he is the principal resident missionary there.
This family came originally from Wymondham, in Norfolk.
Just after our arrival, a messenger appeared with a note to Henry Bobart, our conductor,
from Waimate, the object of which was to prevent our coming forward, until Second day,
on account of indisposition in one of the families, as the invalid would, no doubt,
then be recruited.
We consequently remained at Keri-Keri, and were invited to attend their place of worship,
next morning, the 4th instant; this I did not like to shrink from, however painful;
although there was nothing before the view of my mind, beyond the testimony, which we,
as a Society, have to bear, against form without life and power, in the will of man.
I think there were not ten adult natives male and female; nor as many children present,
and these belong to the household department of the missionaries: the Europeans,
who were on a raised platform, at the other end of the building,
were probably twice as numerous as the natives.

5th.--A note arrived from Waimate, stating, that if the weather cleared up,
a cart should meet us on the way; but the road was so slippery, the soil being clay,
and the horses wholly without shoes, that with the present rain,
the steep hills would be difficult and dangerous to travel over.
I preferred going on foot to horseback, under all the attending circumstances;
but Henry Bobart and Charles rode part of the way,
and then gave up the horses to native boys, and travelled on foot with me.
The rain commenced again before we had proceeded far,
and increased after noon-tide of the day; and having to pass through much fern,
and high coarse grass,
procured us a larger share of wet than the rain which actually descended.
We were five hours performing the journey, as from the state of the roads and lameness,
I could only proceed at a crawling pace.
Just as we began the last long hill, when my strength was nearly exhausted,
and breathing difficult, we met the principal missionary William Williams,
who (having been formerly a medical man,) anticipating
my situation from what he had heard of my age,
brought with him a sandwich, etc.
I told him that a friend in need was a friend indeed.
On the strength of this, and with frequent stops to rest and recover my breath,
I was enabled to reach the summit of the hill, and enter Waimate.
Every accommodation within the reach of William Williams and his wife,
was cheerfully afforded us;
but the greater part of our damp clothes we were forced to keep on.
In this place we found a well-conducted family, and a peaceful and quiet abode.
When invited to the family devotion in the evening, we entered a large room,
where thirty boys were assembled, the children of the missionaries;
but such was the quiet order of the establishment,
I did not know they were in the house till that time, nor that the house was a school,
although we had then been three hours under its roof.

6th.--Rested little during the night, but rose early to join the family before breakfast,
and remained in the house most of the day, on account of my lameness;
and the weather continuing so wet,
the garden walks served only as channels to carry off the
superfluous water from the surface of the neighbourhood.

7th.--The weather still showery, but fine at intervals.
Had an opportunity of seeing the manner in which the natives prepare the fern root,
at present the principal article of their food.
This root has an astringent property,
and is admirably calculated to counterbalance the effects of fish and bad potatoes.
Although well beaten after being roasted, it still retains a strong fibre,
which is separated from the more pulpy substance in the chewing,
and thrown away by the eater.
It requires good teeth to obtain sufficient support from it.

9th.--Yesterday, my lameness but little gone off,
and no opening presenting for religious service,
my situation altogether required continued exercise of faith and patience;
the weather was too unsettled to undertake the journey back to Keri-Keri.
This morning, the state of the weather was more promising.
Before breakfast, it crossed my mind,
that it was not improbable a proposal would be held out,
that if we stayed over next First day,
an opportunity would be afforded for seeing the people collected: after breakfast,
I mentioned to our host, that as the weather appeared more favourable,
we should be thinking about returning to the Bay of Islands.
The anticipated proposal, however, was immediately drawn forth,
for us to remain over First day, to see the natives collected.
I then stated, that we left the vessel unprepared for so lengthened a visit,
but as this offer was now made, I did not dare to run away from it,
acknowledging at the same time, that our clean linen was exhausted.
This difficulty was soon surmounted by our hostess,
who insisted upon getting everything we had immediately washed.
At nine o`'clock,
being informed that a considerable number of the
natives would be collected from a distance,
who would not be present on First day, it seemed safest for me to attend on the occasion.
We repaired to the building pointed out, and a goodly number soon collected in the place.
Finding that the manner of conducting the meeting was wholly left to my disposal,
we settled down into silence, until I was strengthened to declare amongst them,
in an encouraging manner, the truths of the everlasting gospel.
I had to turn them inward to the true minister of the sanctuary,
and of the true tabernacle, which the Lord hath pitched and not man;
who teacheth as never man taught, and speaketh as never man spake, by the Holy Spirit,
in the hearts of the children of men the world over.
There were some tender people present: the Lord`'s power was over us,
and my heart rejoiced.

10th.--The weather being much improved,
I was enabled to take what exercise I could bear
without retarding the cure of my lameness.
Late in the afternoon,
William Williams informed me that the usual meeting of the whole establishment of
missionaries and their families would be held in the evening,
querying whether I could not join them.
I said but little in return,
but in a while found that I must avail myself of this opportunity,
and at a suitable interval told William Williams that I should
like to have a little time afforded me at that meeting;
and knowing their mode of conducting these meetings, I mentioned as the best time,
the interval after the chapter in the Testament had been read.
He directly asked, if I wished that any chapter in particular should be selected;
I replied in the negative, saying, it would make no difference with me.
In due time the meeting commenced,
when individuals were fixed upon by them and named to lead the first and second prayer;
when these were gone through, a hymn was sung as usual,
and then the twentieth chapter of the Revelation was read by William Williams himself.
When this was concluded, we dropped into silence, no doubt, to the surprise of many,
as but few could have come to the knowledge of the request which I had made,
from the shortness of the intervening space of time.
After a solemn pause, I stood up with the words of the beloved disciple,
when on the Isle of Patmos, in the day of the Lord`'s power and presence in spirit,
for the word of God and the testimony of the Lord Jesus;--"`Unto Him that loved us,
and washed us from our sins in his own blood,
and hath made us kings and priests unto God and his Father;
to Him be glory and dominion forever and ever,
Amen;`"--declaring that this language was what I desired they might
be all enabled to adopt from their own blessed experience;
and proclaiming amongst them the glory of the gospel day,--
"`When the earth shall be filled with the knowledge of the Lord,
as the waters cover the sea.`"
I had to show the indispensable necessity of our possessing the true faith of the gospel,
once delivered to the saints,
and still delivered to all true believers in the
spiritual appearance of its only Author and Finisher,
in the heart of man at this day; which faith worketh by love, purifieth the heart,
and giveth the victory over sin, and the evil propensities of human nature.
This is the faith of the Son of God, who loved us and gave himself for us;
and is only bestowed on the simple, humble, child-like,
and obedient followers of the lowly Jesus, in the way of self-denial and the daily cross;
these henceforth live not unto themselves, but unto Him who died for them and rose again.
The dear children were directed to hearken to that voice which saith,
"`I love them that love me, and they that seek me early shall find me.`"
I had for some time to wade, as it were, against wind and tide;
but eventually it proved a solid opportunity: the goodliness of man was laid low,
as in dust and ashes, before the power of an endless life.

11th. (First-day.)--Since last Sixth day morning,
way has opened in the minds of those about us, in a remarkable manner,
as if the ever-blessed Master had directed our steps to a place,
where He himself intended to come, in his own appointed time,
in condescending mercy to a poor, way-worn, unprofitable servant.
It was now proposed by William Williams,
that I should attend their place of public worship,
and after the customary service was gone through in the New Zealand language,
according to their prescribed forms; he said, '`if you have a word for the people,
I will interpret for you.`' This was more than I had looked for, or dared to hope,
but a few days ago.
Although not exactly accordant with my own views, or if I might have chosen for myself,
what I should have proposed; yet I have of late, I think,
learned to be willing almost to become all things, and to submit to all things,
however humiliating to the creaturely part,
that would lead to an opening for me to proclaim to others the glad tidings of salvation,
through a Saviour`'s love.
At the proper time, we accompanied William Williams and family to the place of worship.
That I might not be at a loss, he said, when they had gone through their part,
he would come and conduct me to the proper place in front of the people,
which was raised higher than the platform to assist the speaker`'s voice.
We sat on one side of the congregation, on a low form, attracting the attention of many,
by retaining our seats, while all, but ourselves, stood, or knelt, as occasion required.

When all was gone through, William Williams threw aside his surplice,
and fetched me to the appointed spot, where we stood together in silence;
until I reminded the people, that we were in the presence of Him,
without whose knowledge a sparrow cannot fall to the ground: but,
though heaven is his throne, and the earth his footstool, yet to this man will he look,
even unto Him that is poor, and of a contrite spirit,
and who trembleth at the word of his power.
I had largely to testify of the love of God, as it is in Christ Jesus,
and to turn the attention of the people to the light of His unspeakable gift,
which shineth in every heart; who once in a body of flesh spoke to man upon the earth,
but now speaketh from heaven, by the Holy Spirit; and to all that believe in it,
and obey it, it is the power of God unto salvation.
The countenances of some of these dear people spoke louder than words,
that they had fallen upon the stone of Israel,--their brokenness could not be hid;
to such, the message of everlasting love flowed freely, and I humbly trust,
was as a shower upon the thirsty soil.
It was an open and relieving season:--it was the Lord`'s doing, and, I believe,
marvellous in the eyes of some present.
There were several European families, besides those of artizans,
attached one way or other to the mission; which,
with the boys`' school and the natives of the surrounding neighbourhood,
formed a considerable body of the people: but the praise was His alone,
who wrought the work;
and surely some of these were constrained to render unto Him of his due.
In the afternoon we attended the meeting again, but my lips were closed up:
it afterwards appeared that some were looking for words, and were disappointed.

12th.--Before getting up this morning,
I found there was something gathering upon my mind towards the children in the school;
and knowing that the whole family would be collected together at seven o`'clock,
I thought it best to speak with William Williams, without loss of time.
Meeting him soon after,
I told him that I wished to have a little time in the
course of their usual family devotion that morning,
mentioning the opportunity after the chapter had been read,
as most likely to answer my purpose, and not to interfere with them;--for this,
he readily made way.
As the whole company are accustomed to kneel down at the conclusion of the chapter,
I thought there might be a little unsettlement on this account,
particularly as the boys knew not of the alteration; however,
with a simple motion of the master`'s hand, all remained in stillness.
After sitting silent awhile,
I revived our Lord`'s expressions,--"`Herein is my Father glorified,
that ye bear much fruit;
so shall ye be my disciples,`"--which were spoken to his immediate followers,
when comparing himself and them to the vine and its branches,
so beautifully illustrative and instructive:--"`As a branch cannot bear fruit,
except it abide in the vine, no more can ye except ye abide in me.
He that abideth in me, and I in him, the same bringeth forth much fruit;
for without me ye can do nothing.`"
How then can we without Him glorify the God and Father of our Lord Jesus Christ,
or exhibit in the sight of others that heavenly badge,
which designates his true disciples.
I had, also, to remind the younger branches present, of their privileges and advantages,
far above the lot of many, in being placed under such care, in a situation so guarded;
where everything is conducted for the promotion of their best welfare,
and governed by the law of love and kindness:
having the Holy Scriptures read to them daily, which point to the Saviour,
from their earliest pages, by holy promises and prophecies,
which were fulfilled in the fulness of time, to every jot and tittle;
that through patience and comfort of them we might have
hope;--which are also able to make wise unto salvation,
through faith which is in Christ Jesus;
and yet they cannot be understood without the assistance of the same Holy Spirit,
which inspired the holy men that gave them forth.
We can know nothing of the things which belong unto God the Father,
but through the Holy Spirit of his Son.
And although all are not called to be apostles, or prophets, or teachers,
or workers of miracles, yet we are called to glory and to virtue,
with a high and holy calling; and to show forth the praises of Him,
who hath called us out of darkness into His marvellous light,
by bringing forth the fruits of love, joy, peace, long-suffering, gentleness, goodness,
faith, meekness, temperance, wrought by the power of the Spirit of the Lord Jesus,
in our hearts.
After bidding them an affectionate farewell in the Lord, I sat down.

After breakfast, preparation was made for our departure; but from one cause or other,
this was delayed until near noon.
During this interval, I called to see the wife of one of the missionaries,
who had long been an invalid, but is now considered in a state of convalescence.
It arose in my mind to tell her, that it is by these things we live, and by this,
is the life of the spirit, which inherits the kingdom;
and which retains in meekness and lowliness,
as it is concerned to pray always with all prayer and supplication, watching thereunto.
Henry Hobart and W. R. Wade, accompanied my son Charles on horseback,
but a cart being provided on account of my lameness,
I was conveyed in it a great part of the way.
We reached Keri-Keri by five o`'clock; and having nothing to detain us there,
proceeded towards the Bay of Islands, as soon as a boat could be got ready:
we were favoured to reach the vessel soon after ten o`'clock p.m.,
and to find all well on board, which was cause of thankfulness on my part,
as the neighbourhood of the Bay is a very dissipated and wicked place.
We had been absent ten days.

17th.--Since returning from Waimate, and getting well rested,
I have nearly got rid of my lameness.
In the daytime we have been engaged in selecting school materials,
for the use of the native children,
from the stock presented to us by the British and Foreign School Society in London;
also a variety of religious and temperance tracts, with clothing for the native children,
to a considerable extent; these we conveyed to the station at Paihia in the evening.
On Fifth day we sat down together in our usual way, and were favoured to get into quiet.
For some days I have been waiting to see what was likely to open for me,
in the line of duty,
and now find that the minds of some in this neighbourhood have been turned towards me,
who have it in their power to lend a hand of help,
to forward the work in which I am engaged.

This morning, Charles Baker came off to say,
that there would be an opening for my going to
Korarareka tomorrow to attend the native meeting;
and that afterwards,
there would be a meeting held for the English residents in this neighbourhood.
He also said, that Henry Williams and himself had concluded to prepare a notice,
stating that a member of the Society of Friends would be there,
perhaps mentioning my name, and would give them an address.
To avail myself of the opportunity of attending these meetings
was a duty from which I was not satisfied to shrink;
but I could not agree to the notice without its being worded in such a manner,
that none would be disappointed, if I should have nothing to say to them.
He said, the notice was so qualified, that that would be fully understood by all parties.

18th. (First day.)--Charles Baker came on board in the forenoon,
and we proceeded with him up the bay, and landed at Korarareka.
A considerable time was then occupied in going round to the different huts,
(of the natives,) to rouse them up and persuade them to attend the meeting.
I could perceive that Charles Baker availed himself of the
circumstance of my having been among the islands in the South Seas,
with the glad tidings of the gospel; when one of the chiefs immediately asked,
'`if the people of those islands had listened.`' I am not
aware of the reply of our interpreter to this question,
though we fully understood the sort of conversation going forward,
by the names of the different islands that were mentioned;
but the chief who was then lying on the ground, wrapped in a large Witney blanket,
seemed determined to attend the meeting, though not in the habit of so doing,
and quickly starting up retired into his hut,--but soon made his appearance again,
dressed in European clothing, and was about the first man to go into the meeting,
when the bell rang.
Charles Baker occupied a short time with them in the native language; but they came in,
in such a straggling, careless manner,
that they had scarcely all assembled before he had finished.
The number altogether was very small; but the love of the gospel flowed towards them,
as numbered among those for whom the Saviour died, and rose again, that they might live.
The truths of the gospel were sounded among them;
and they were invited to accept the terms of salvation
then proclaimed,--"`Believe on the Lord Jesus Christ,
and be saved.`"
They were directed to turn inward to the true light,
"`that lighteth every man that cometh into the world;`" for this light is Christ,
the light of the world, and the Saviour of the world, who by His Holy Spirit,
shineth in every heart.
In this light they must be willing to believe, which would not only show them their sins,
but if these were forsaken and repented of, would also save them from their sins.
With more words they were exhorted and entreated to repent, believe, and obey.
The people were very attentive and solid: may the Lord soften their hearts,
and incline them to ponder the things which they heard spoken.
The interval was short, after this meeting concluded,
before that for the English residents was to begin.
We dined upon such eatables as we brought with us in our pockets,
and distributed what we could spare, to the boat`'s crew of natives;
but we were not in a neighbourhood where a drink of water could be readily procured,
before the people began to gather;
who now appeared in numbers far greater than had been contemplated.
The families which had attended the missionary establishment at Paihia in the forenoon,
now crossed the bay in their boats to this meeting, amounting,
with some well-disposed persons from the shipping,
and others perhaps prompted by curiosity, to about seventy persons.

While Charles Baker went through what he considered himself bound to perform,
I sat more than half-an-hour,
but never under a feeling more destitute and more sensible of weakness and inability;
and yet the present appeared as an opportunity afforded,
to declare that the Son of God is come into the hearts of all true believers,
and in boundless love and mercy is still standing and
knocking at the door of the hearts of all:
that to those who are willing to hear His voice, open unto Him,
and receive His Holy Spirit, He will come in unto them;
and if His purifying and cleansing operations are patiently submitted to,
with full belief in His power to save,--their sins, though many, if repented of,
will be purged away through His blood, and remembered no more.
Of this, I had largely to testify, as no new doctrine, but an incontrovertible,
established truth; having holy writ for its author without us,
and an evidence which liveth and abideth forever, within us, even in our own hearts;
for "`he that hath the Son of God,
hath the witness in himself,`"--His law is written in the
heart;--the law of the spirit of life in Christ Jesus,
which makes free from the law of sin and death.
The necessity was urged of a serious examination being entered into individually to
ascertain whether we really know the law written in our hearts,--the law of the
spirit of life in Christ Jesus,--the faithful witness against sin and transgression;
these keep the soul of man in darkness and in death:
but he that hath the Son of God hath life,
and he that hath not the Son of God hath not life, but the wrath of God abideth on him.
We were favoured with a solemn season together,
though the opportunity was brought about in an unusual manner,
and agreed upon in the first place without my knowledge, or any suggestion of mine.

25th. (First day.)--On Fifth day last, we had a visit from Nathaniel Turner,
the senior Wesleyan missionary at Hokianga,
with whom I became acquainted at Hobart Town in 1834.
From all we have seen, New Zealand is at present a barren soil,
where religion does not thrive.
Without any previous knowledge of the real state of things at Hokianga,
I never saw my way to make an attempt to visit its neighbourhood, either by sea or land.
Nathaniel Turner said that the state of the road is so bad at this time,
that he believed I could not, at my age, accomplish a journey thither;
but that they should be glad to welcome us, if it could be done.
I am fully aware that the undertaking would be attended with difficulty and fatigue;
but if I felt the same inducement to go there, which has hitherto enabled me,
as it were "`to run through a troop`" of difficulties,
"`and leap over a wall`" of opposition,
all the statements we have had of the difficulties by land, and the danger by sea,
should not deter me from endeavouring to reach it.

Having been invited to attend a meeting to be held this evening,
by the whole of the members of the mission at Paihia, at the house of Henry Williams;
and believing it best for me to be there, we landed in time to take tea with the family.
When the meeting was gathering,
Henry Williams asked me if I would like to read a chapter in the Bible.
I declined the offer,
at the same time requesting that a little time
might be afforded me when the reading was over;
adding, that if I had any thing to say to them, they should have it.
The chapter had not been long finished before I stood up,
which produced a general silence.
And after referring to the affecting example of the dear Son of God,
as set forth in the language of inspiration,--"`Lo, I come to do thy will,
O God,`" I told them that I was among them in the bonds of the gospel,
and was desirous of being found in the counsel of this will, which is ever excellent;
and I stood resigned to minister in the ability which might be afforded,
and hoped to be faithful thereunto on the present occasion: declaring,
that it is only those that do the will of the Father,
that shall know of the doctrine of the Son.
His doctrine shall descend as the dew, and as the small rain upon the tender herb,
upon those that do the Father`'s will: they shall inherit substance,
eternal substance,--the living and substantial truth, pure and undefiled,
"`as it is in Jesus;`"--truth in the inward parts, which the Lord desireth.
Such are the Lord`'s children, and compose His church on earth;
they are all taught of Him: "`in righteousness shall they be established,
and great shall be their peace.`"
"`This is the heritage of the servants of the Lord, and their righteousness is of me,
saith the Lord.`"
There is no way of becoming of this blessed number,
but by a knowledge of the doctrine of the Son, our Lord and Saviour Jesus Christ.
"`This is my beloved Son, in whom I am well pleased; hear him.`"
This is the will of God the Father; and those who are faithful in doing this,
shall assuredly be taught of the Son: they shall know of His doctrine.
In this way I was engaged to turn the minds of all present,
to the teaching of the Holy Spirit of the Lord Jesus,
which would lead them safely along through time,
and sustain them in a boundless eternity.
This appeared to be well received: a solemn feeling spread over us,
under which we separated.

31st.--Most of the week has been employed in preparing documents for England,
a vessel being nearly ready to sail from hence.
On Fifth day our little meeting was held as usual.
On Sixth day, a proposition was made to pay another visit to Koua-Koua, next First day;
but not feeling any thing towards it, I declined going.
When on shore yesterday, I met with a missionary, Wilson,
just arrived from the seat of war,
having been driven with his family from the station occupied by him.
The account he gives of their vindictive barbarism and cannibalism is truly horrifying.
On his way, he had to pass by a piece of raised ground,
upon which the heads of the vanquished were placed, with their faces to the sun,
as they are seen to most advantage in this position.
A human heart was stuck upon a spear as a token of victory.
He saw one tribe returning from the battle-field,
loaded with human flesh for themselves and their friends to feast upon.
Miserable women and children followed in train
after the mangled remains of their husbands,
sons, brothers, and fathers; themselves captives,
and doomed to slavery the rest of their days.
He saw a child amusing himself with putting his fingers
into the eyes and nostrils of a human head,
which had been given him to play with.
Who can wonder at their hardness of heart,
when thus trained from infancy to habits of savage cruelty and barbarism!
At one place which they were destroying with fire, their conduct was really fiend-like.
In one instance, a missionary family had been plundered by their own congregation:
the reason assigned for this shameful conduct was,
that they expected the missionary was about to leave the neighbourhood,
probably taking for granted that the property would fall into the hands of their enemies.

First Month 1st, 1837.
(First day.)--Remained on board all the day, low and stripped,
like her who had lost her Lord, and knew not where to find him.
Assembled the crew both in the forenoon and afternoon as usual.
It seems as if something was gathering upon my
mind towards all the members of the mission,
in a collective capacity; and standing in resignation, I felt somewhat relieved.

6th.--Much of our time has been spent on board this week,
owing to different persons coming from the shore.
Today I learned that the missionaries from Waimate,
who had been generally over at Paihia during the time called Christmas,
with those from Keri-Keri, had all returned to their own stations,
which at once set aside my seeing them in a collective capacity,
which I had a little thought of, but had apparently been prevented from moving in;
and now the time was gone past, this brought me under a painful exercise of mind.
Today the wind is so strong as to prevent our getting on shore,
our vessel tumbling about, almost as if she was not in harbour.
In the forenoon we held our little meeting,
which had been set aside yesterday by the confused state of things on board.
My state was similar to that of the heath in the desert,
which knoweth not when good cometh; and as the barren mountain top,
where there is neither dew, nor rain, nor fields of offering:
the accuser of the brethren seemed to have prevailed against me.
I was smitten and wounded within; and a wounded spirit who can bear?

7th.--Early this morning the wind, which had been strong through the night lessened,
and the rain fell without intermission through the day,
which not a little contributed to darken the gloom already spread over my mind.
My Charles at the same time was unwell,
with a sore throat and other symptoms of a violent cold.

8th. (First day.)--Today the rain fell at intervals in light showers:
our sailors were assembled as usual;
and in the afternoon two strangers joined us from the shore.
I had to testify,
that the Almighty has not left himself without a witness in every heart,
which shineth as a light in a dark place;
and is no other than the light of the Holy Spirit of the Lord Jesus,
"`the true light that lighteth every man that cometh into the world,`" etc.
My mind has since felt more peaceful.
This afternoon the Chieftain, a British whaling vessel,
which was at Tongataboo at the same time as the Henry Freeling,
arrived in the Bay of Islands.

11th.--Yesterday, employed in disposing of articles of hardware, etc.
The way seemed now to open with clearness, before leaving New Zealand,
to draw up an address to the missionaries stationed at Paihia, Keri-Keri, Waimate,
Tepuna, etc,
and all the members belonging to the '`Church Missionary Society,`' (as
it is denominated by themselves,) employed in New Zealand;
and as I endeavoured to keep close to this prospect,
it more and more brightened before me.

12th.--We held our usual meeting, and although a low time, I felt comforted and peaceful.
In the afternoon took exercise on shore, after having been detained on board,
by one circumstance or other, nearly a fortnight.
As the way opened, I began to commit to paper, from time to time,
the matter which arose towards the members of the mission.

15th. (First day.)--Believed it my place to remain with our people on board,
feeling nothing towards the shore;
and being well aware that the whole neighbourhood of the bay,
except where missionary interest prevails, answers nearly, if not altogether,
the description of the place, where Satan`'s seat is.

16th.--Engaged in writing a fair copy of an address to the members of the mission.
In the evening went on shore for exercise;
and thinking that those at the station at Paihia,
might suppose I shunned calling upon them of late, I told Charles Baker,
that seeing their members could not be collected together,
as had been the case at the Sandwich and Friendly Islands,
I was preparing a written address to them; at the same time I informed him,
that the time of our departure from the Bay was drawing near.
This evening the Ganges, an American whaler, arrived from the neighbourhood of Madagascar.
Not far distant from New Zealand, her boats were engaged in pursuit of whales,
and affecting to relate, when night came on, one boat was missing altogether.
There was no trace whatever of the cause of this disastrous event:
whether the boat had been dashed in pieces by a whale,
or towed under water when fastened to one by a harpoon, or had lost sight of the ship,
and could not find her again before night overtook them, cannot be ascertained.
The captain, fourth mate, carpenter, and three others,
were in this boat when she left the Ganges.
Three other American whalers have also arrived; and one English merchant ship,
from Cloudy Bay, in the South of New Zealand.

17th.--Yesterday and today, employed in getting ready for sea.
Having parted with a considerable weight of iron goods out of the hold,
and our general stock of stores and provisions being greatly lessened,
I thought it needful to procure a quantity of stone,
lest the vessel should be endangered by being too light in the water,
and thus rendered unable to carry sail in a comfortable manner.
James Busby, the British resident, very kindly supplied our wants,
from the margin of his estate, which is washed by the sea.
In the morning called upon Charles Baker, and afterwards took leave of James Busby,
by whom we had been treated with much kindness and hospitality.

18th.--All being ready, at day-break this morning the Henry Freeling got under weigh,
and dropped down the Bay opposite the station at Paihia, where we anchored again.
We landed in the forenoon on the north side, settled our accounts,
and bade farewell to the parties as we went along.
My address being copied fairly,
and various articles put together to remunerate the natives for their services in boats,
etc., we landed in the evening for the last time at Paihia,
and delivered them with the address to the care of Charles Baker,
at whose house we drank tea.
As a reward of industry, and an encouragement to persevere,
we presented to a native farmer of promise, who goes by the name of industrious David,
a spade, ship axe, drawing knife, small saw, and a bunch of gimblets.
We also gave a Bible to a Sheffield woman, the wife of a blacksmith residing in the Bay,
and numerous articles of clothing to the native
children;--two Dutch hoes and a spade for Charles Baker,
with sundry drugs and glass bottles for James Stack were also landed.
We called upon all the resident families,
and saw those who had been forced from their stations to the southward by the war,
before we returned on board.
Before reaching the vessel a light land breeze had sprung up;
and the night being moonlight we weighed and steered towards
the entrance of the Bay with a fine breeze in our favour.

At half-past nine o`'clock, Gilbert Maer, the post-master,
with whom we had had some considerable traffic,
who had very kindly brought us off some milk,
and accompanied us until clear of all danger, left us in his own boat,
with a crew of natives, and I believe sincerely desired for us a prosperous voyage.
At midnight, we were clear of the islands which form the entrance to the Bay,
and from which it is probable the appellation of the Bay of Islands was originally taken.
I may long have to mourn,
on account of the lamentable state of the poor miserable natives of New Zealand,
bound down as with chains in the service of Satan, and the dupes of his agents,
who are mingled among them, of a lighter coloured skin, but in many instances,
it is greatly to be feared,
the very scum and offscouring of the nations which gave them birth,
and not a few of these mine own countrymen: however,
under all these unhappy circumstances, the New Zealanders are a noble race of men;
and though far behind-hand in that gentleness and docility which
characterize the swarthy multitudes of the more sultry climates,
in which the Georgian, Society, Hervey, and other isles of the Pacific ocean are placed;
and they certainly possess greater energy and firmness of character.
This unhappily in their present lost and undone and, I may add, betrayed condition,
is only devoted to the most barbarous purposes, for the destruction of their fellow-men.
But if the day should ever come,
when the benign principles of the everlasting gospel take root and spread among them,
soften their hearts, and prepare them for that wisdom from above, which is pure,
and peaceable,
and profitable in all things to direct into the love of God
and love to man,--they would then far outstrip those who have
long since made only a profession of the Christian religion;
both in exalting and promoting the spiritual
kingdom of our Lord and Saviour Jesus Christ,
in the heart of man, to the praise and glory of God,
and the welfare of their own species.
With this view of a deeply injured race of my fellow creatures,
constituting a part of the innumerable inheritance of the Lord Jesus,
I leave their shores with a peaceful and easy mind;--at the same time,
comforted under a belief,
that the address to the missionary establishment will now circulate to every member;
many of whom could not possibly have been present at a transitory interview,
however regularly appointed.
On looking at this subject,
I have thought that the conflict of mind I have lately had to pass through,
might be the means graciously vouchsafed,
to beget in me a willingness to prepare the address.
My desire is, that by it, and through it, the great name may be exalted,
and the kingdom of Christ Jesus in the heart better understood and believed in,
than heretofore has been the case, in the minds of many.
May the Lord on high prepare the ground, in which it may, as seed, be sown;
and may He bless it with fertility to bring forth fruit that
will lastingly remain;--that He may be glorified thereby.

[.offset]
The following are extracts from the address to the missionaries in New Zealand.

[.embedded-content-document.address]
--

Finding that I have no longer any place in these parts,
and being at the same time restrained from journeying forward,
as when the cloud rested on the tabernacle formerly.
I have endeavoured to wait in singleness of heart at the posts of wisdom`'s gate.
I find that, before being liberated from the Bay of Islands,
there is something due on my part to the members of the mission;
for whom I feel too much love to withhold any thing,
that may tend to strengthen or encourage them on their way to the everlasting kingdom.

In communicating what may be unfolded to my view,
should it be my lot to impart any spiritual benefit, let it be remembered,
that it is the Lord, from whom alone cometh every good and perfect gift,
and that the writer is but an unprofitable servant.

Among the different Isles that stud the capacious bosom of the Pacific,
to which my steps have been directed, opportunities have most unexpectedly presented,
for seeing the different members of the respective missions with their families,
concentrated at one place; but in New Zealand, circumstances not only local,
but of a deeply affecting nature, combine to render this impracticable,
if not impossible.
I have therefore no alternative,
but through this medium to salute you on the broad basis of the gospel; which,
expanding to earth`'s utmost bound, embraces all,
while it ever breathes in angelic unison, "`Glory to God in the highest, on earth peace,
good-will toward men.`"

We live in no common times, and the present is a day of distress and gloominess,
as the morning spread upon the mountains,
before illumined by the brightness of the rising sun;--a day when some,
struck with dismay as when a standard-bearer fainteth,
are ready to exclaim with Elijah the prophet of the Lord,--"`I only am left,
and they seek my life.`"
"`Oh! the depth of the riches,
both of the wisdom and knowledge of God! how unsearchable are his judgments,
and his ways past finding out!`"
Who among the sons of the mighty, at this cloudy season,
can develop the strength of the remnant of the called and chosen and faithful,
when the penetrating eye of the holy prophet, strong in the power of the Spirit,
was ignorant in his day of calamity and distress,
that the Lord had seven thousand men that had not bowed the
knee to the image of Baal? It is enough for mortal man to be
allowed to participate in the things that are revealed,
and no more is required from each of us in return,
than sufficient ability is given us to perform:
our own individual duty is all we have to attend to, or shall be accountable for.
It is not for us to say, "`and what shall this man do?`" lest the reproof should be ours,
"`what is that to thee? Follow thou me.`"
So that while surrounding circumstances exhibit ample cause for lamentation,
and mourning and woe; still we must not shrink,
nor suffer ourselves to be drawn aside from following our Lord and Master,
by searching after secret things which belong unto God,
or in brooding over results beyond our reach, and our power to control.
Our insidious adversary will not fail to prompt to any exercises calculated
to prevent our seeking after that knowledge which giveth life;
and the more plausible the engagement of mind,
the less we suspect that a snare lies beneath.
It is no matter to him, how near the Christian`'s path we may tread,
if not in it;--we are the more lulled into mistaken security:
even under the semblance of promoting the cause of religion,
our attention may be so unsuspectingly but completely engrossed,
that the great work of labouring in our own vineyards,
of seeking salvation in our own hearts, may be overlooked and neglected.
It is of little consequence by what bait the grand adversary succeeds;
his purpose is fully accomplished,
if we are but kept destitute of that knowledge which is life eternal.

To the heart that is upright and fixed, trusting in the Lord,
the trials and conflicts of time are highest, richest blessings,
operating like a weight of costly treasure on a pillar erect; the greater the burden,
the firmer and stronger it stands, and the closer it presses the foundation.
All the sufferings of the present time permitted to assail us,
are not worthy to be compared to the glory revealed in that man;
because he hath made the Lord his refuge, and the Most High his habitation,
in the day of trouble and adversity: he can say from heartfelt knowledge,
in humble resignation,--"`it is the Lord.`"

In the course of the last two years,
I have had an opportunity of witnessing the attempts that are making to benefit the
benighted inhabitants of various islands in the Southern and Northern Pacific Ocean,
and have been enabled to visit almost without exception,
the solitary and secluded allotments of those engaged in this important work.
Although this has been but partially the case in New Zealand,
yet opportunities have been afforded of seeing the faces of many of
the members of this extensive mission from remote places,
as well as of those who reside in this immediate neighbourhood,
who with others scattered among the different isles, where my lot has been cast,
are dwelling among strangers, in a strange land.
Having myself dwelt among a people whose language I could not understand,
gives me to know the heart of a stranger, and to feel for him;
and I also know his only place of safety and refuge to
be Christ Jesus the Lord:--if He be with us,
we have nothing to fear, for He is love itself, and "`perfect love casteth out fear.`"
It is that which revives and animates the fainting, wayworn traveller,
to persevere in the tribulated path.
It is the effect of this heaven-born principle, and the true dignity of its nature,
to sustain the Christian with fortitude and innocent boldness,
above the torments of fear, and far from the reach of terror.

Although my tarriance has been but short among you,
it has been long enough to allow me to witness
the upright devotedness of heart and intention,
of some whom our intercourse has given me an opportunity to know and love;
and to feel and sympathize with them.
I am also aware of the great difficulties to be encountered in
the prosecution of the cause of truth and righteousness,
and of the many obstacles thrown in the way by the agents of Satan:
but if the work be the Lord`'s, it will assuredly prosper,
though "`the heathen`" should "`rage,
and the people imagine a vain thing;`" however
"`the kings of the earth`" may "`set themselves,
and the rulers take counsel together.`"
"`He that sitteth in the heavens shall laugh, the Lord shall have them in derision.`"

I believe that you are all desirous of knowing the Lord for yourselves;
and I feel bound to encourage you to follow on to know Him,
desiring to be your companion in a pursuit of such eternal consequence;
for in the same proportion as we ourselves grow in the
saving knowledge of our Lord and Saviour Jesus Christ:
so shall we be in a capacity to benefit others.
My desire is, that none of us may be contented with saying,
we hope that we are led and guided by the Holy Spirit; for I can tell you,
"`in the word of the truth of the gospel,`" that no man led by the
Spirit of the Lord can have any doubt or hesitation on this account,
any more than he can doubt the shining of the sun, when he sees it at noon-day:
the way-faring men, though fools, shall not err therein, or be mistaken.
If we are not in possession of this inestimable gift,
the fault is our own,--we have the word of a King for it, even the King of saints,
and King of kings;--"`ask and it shall be given you, seek and ye shall find,
knock and it shall be opened unto you;`" again, "`if ye then, being evil,
know how to give good gifts unto your children,
how much more shall your heavenly Father give the Holy Spirit to them that ask him.`"
But then it must be sought in faith,
and as by those that have none in heaven but the Lord,
nor in all the earth in comparison of Him.
It must be sought as prescribed by the lip of Truth himself,
"`first`" and before every earthly consideration whatever:
"`seek ye first the kingdom of heaven and His righteousness,
and all these things shall be added unto you.`"
Without strict compliance with the terms "`seek ye first,`" we ask and receive not,
because we ask amiss.
Let none be discouraged; there is no cause for it.
"`Heaven and earth shall pass away,`" but the words of our King
"`shall not pass away;`" his promises are yea and amen forever.
"`Seek and ye shall find;`" but let us seek aright:
for "`the Lord is good unto them that wait for him--to the
soul that seeketh him;`" and for the encouragement of such as
thus seek and wait for the coming of the Lord`'s holy Spirit,
like those who watch for the morning,
after a dark and dismal night of peril,--for such as these,
the gracious promise through the inspired prophet is designed,
that they "`through patience and comfort of the
scriptures might have hope:`"--"`the Lord whom ye seek,
shall suddenly come to his temple, even the messenger of the covenant,
whom ye delight in; behold he shall come, saith the Lord of Hosts.`"
The heart of man must be purified and cleansed,
before it can become the temple of a pure and holy God.
"`But who may abide the day of His coming? and who shall stand,
when He appeareth?`" Truly nothing in man or of man;--self must be cast out,
and all that belongs to it: for "`He is like a refiners fire and like fuller`'s soap.
He shall sit as a refiner and purifier of silver; and He shall purify the sons of Levi,
(the priesthood He himself hath chosen,) that they may offer unto the Lord an
offering in righteousness;`"--even those whom He hath chosen and called to proclaim
the glad tidings of His gospel in His name and by His power and authority,
having their feet shod with His holy sanctifying preparation.
O! how great is the work to be done in the heart of every individual,
before it is fit for the reception of this heavenly guest,
who only dwelleth in the temple of an undefiled heart!
How many baptisms have we to pass through,
in order to purify and prepare us for the knowledge of the only true God,
and Jesus Christ whom He hath sent once in a body of flesh on the earth,--
but who now appears by the eternal Spirit in the heart of every man.
We have great instruction from the narrative in holy writ,
of the preparation which Elijah had to pass through on Mount Horeb,
before he was in a situation to discern the "`still small voice.`"
He had first to witness "`a great and strong wind to
break in pieces the rocks,`"--as a figure of that power,
which alone can subdue and soften the rocky and obdurate nature in
the human heart;--"`but the Lord was not in the wind.`"
"`And after the wind,
an earthquake,`"--another needful dispensation for the reduction of the creature,
and the shaking and separating of the earthly part,
and everything in man that cannot abide the day of the Lord`'s coming,
or stand when he appeareth.--"`But the Lord was not in the earthquake:
and after the earthquake a fire;`"--that searching, consuming,
baptising element--the fire of the Lord,
that consumes not only that which is light and chaffy,
but also the dross and tin and reprobate silver; that nothing may remain,
but what can endure and abide the trial,
as pure gold.--"`But the Lord was not in the fire: and after the fire,
a still small voice.`"
This ordeal we must all pass through, according to our measure:
it is the great work of regeneration;
and in order to hear this "`still small voice,`" we must ourselves be still,
as with our faces wrapped in a mantle.
The prince of this world must be cast out, and his strong holds pulled down;
all our imaginations and every high thing that exalteth
itself against the knowledge of God must be cast down,
and brought into captivity unto obedience, before we can know Christ to be in us,
"`the hope of glory.`"
The silence of all flesh must be attained:
the creature must cease from its own willings and runnings and strivings:
the holy command must be obeyed,--"`be still, and know that I am God:
I will be exalted among the heathen: I will be exalted in the earth.`"
Blessed and happy are they, who thus seek, and thus find; and having found,
to them the glorious day is come,
when whatsoever they shall ask the Father in the name of the Son, He will do it.
Before this day, how vain have been our petitions, because not in the name,
not in the power of the Spirit of the Lord Jesus, but in our own strength, time and will.
"`Verily, verily, I say unto you, whatsoever ye shall ask of the Father in my name,
he will give it you.
Hitherto have ye asked nothing in my name.
Ask and ye shall receive, that your joy may be full.
At that day ye shall ask in my name,
and I say not unto you that I will pray the Father for you;
for the Father himself loveth you, because ye have loved me,
and have believed that I came out from God.`"

I am reminded instructively of the confirming
expressions of our dear Lord on another occasion,
which prove to me how little can be done for the benefit of others,
until the great and necessary work is first wrought in ourselves.
Addressing Simon with the other disciples, he said, "`Simon, Simon,
behold Satan hath desired to have you, that he might sift you as wheat;
but I have prayed for thee that thy faith fail not; and when thou art converted,
strengthen thy brethren.`"
As a stream cannot rise higher than the fountain from which it issues,
so it is impossible for any to instruct others further than
they themselves have learned in the school of Christ.
Let us then seek, until we find the prize immortal.
Let us be determined to know nothing, save Jesus Christ, and him crucified.
Let nothing on earth prevent us from coming to the
life-giving knowledge of the Holy Spirit of this crucified,
risen, and glorified Lord, in our own hearts;
for unless we are crucified with Him to the world, and the world unto us,
we can never rise with Him into life.
And why should not we in this our day, be as complete as the Colossians,
to whom the great Apostle writing, said, "`and ye are complete in Him,
which is the head of all principality and power;
in whom also ye are circumcised with the circumcision made without hands,
in putting off the body of the sins of the flesh, by the circumcision of Christ;
buried with Him in baptism,
wherein also ye are risen with Him through the faith of the operation of God,
who hath raised Him from the dead.`"
The great apostle of the Gentiles and his contemporaries preached "`Christ crucified,
unto the Jews a stumbling block, and unto the Greeks foolishness;
but unto them which are called, both Jews and Greeks, Christ the power of God,
and the wisdom of God,`" unto salvation.
Alas! we may see and believe from the conduct and
conversation of thousands in this our gospel day,
and these too in the higher walks of life, as well as in every other,
without exclusion of sex, age,
or condition,--that however this may be overlooked and unheeded,
the same will judge these unhappy mortals at the last day.
They will then remember how they have been striven with on particular occasions,
when the Lord`'s visitations have been extended towards them in love indescribable;
staining the glory of this world in their sight; wooing, entreating, warning,
and as when reasoning "`of righteousness, temperance,
and judgment to come,`" making them afraid; stirring up the precious principle of life,
procured by the shedding of a Saviour`'s blood;--as when "`an eagle stirreth up her nest,
fluttereth over her young, spreadeth abroad her wings,`" to strengthen, cherish,
and save.
A day will certainly come upon them as a thief in the night,
unless averted by "`repentance toward God,
and faith toward our Lord Jesus Christ,`" when such will have, in spite of themselves,
to look upon Him whom they have so long pierced;
when they will find this "`still small voice`" to be the voice of the Lord in Spirit,
"`powerful and full of majesty,`" to the guilty soul.
The judge standeth at the door--He who when on earth in the body prepared for him,
told those who then disregarded His holy voice,
that his words should judge them at the last day;--"`I
judge no man,`" said he;--"`the word that I have spoken,
the same shall judge him in the last day.`"

Then let us press toward the mark for the prize immortal,
the prize of the high calling of God in Christ Jesus:
let us be found striving together for the faith of the gospel;
until we all come into the unity of the same,
and thereby grow in grace and stature from measure to measure,
unto the measure of the stature of the fulness of Christ Jesus our Lord.
Let us not stop short, until we have obtained the like precious faith,
once delivered to the saints;--the true faith of the gospel, which worketh by love,
purifieth the heart, and giveth victory over sin, death, hell, and the grave.
A historical or traditional faith, or one that admits of a continuance in sin,
is dead and unavailing; but the faith of the gospel is a living,
operative principle,--an impenetrable shield: it quencheth the fiery darts of the wicked,
disarmeth sin, justifieth its happy possessor, and giveth peace with God,
through our Lord Jesus Christ; from whom alone it must be obtained,
and for it we must all come to Him, in the humility and simplicity of little children;
of whom is the kingdom of heaven, though they be upon earth "`the poor in spirit.`"
It is Jesus alone who imparts this heavenly treasure,--faith:
He is the blessed author and finisher of it,
and from him we must receive the precious gift into our hearts.
"`The righteousness of God is revealed from faith to
faith,`" to those who walk in the obedience thereof;
it is indeed the life of the just,
a glorious reality to those who are crucified with Christ, and live thereby.
These can adopt the apostolic language, and say from blessed experience,
"`I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me:
and the life which I now live in the flesh, I live by the faith of the Son of God,
who loved me, and gave himself for me.`"
"`Happy is that people that is in such a case: yea, happy is that people,
whose God is the Lord.`"
In Him they live; in Him they die; and with Him they are everlastingly blessed.

The love in which this is dictated, still flows in my heart towards you,
and in the same I trust it will be received.
And now let me commend you in apostolic language, "`to God, and to the word of His grace,
which is able to build yon up,
and to give you an inheritance among all them
which are sanctified;`"--even that eternal word,
which liveth and abideth forever.

[.signed-section-closing]
I remain your affectionate friend, etc.

[.signed-section-signature]
Daniel Wheeler

[.signed-section-context-close]
Henry Freeling, of Paihia, Bay of Islands, First Month 18th, 1837.

--

[.offset]
A copy of a letter from the missionaries at Paihia

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Church Missionary Society`'s Station, Paihia, Bay of Islands, New Zealand, 18th January, 1837.

[.salutation]
Reverend and Dear Sir,

Before you bid adieu to New Zealand, we take this opportunity of expressing the pleasure,
and, we hope, the edification we have derived, by your unexpected coming to this country.

We had heard of your benevolent mission to other islands of these seas;
but we now have to record the higher gratification of
having seen you and your affectionate son amongst us.

We regret,
that circumstances of war and tumult have not made it desirable for
you to visit the more extensive field of our labour,
south of the Bay of Islands.
But we do hope, that the places favoured by your Christian example and addresses,
may have seen and heard to profit,
and that "`at the last day`" it may be found that your sojourn here has not been in vain.

One effect of your visit to New Zealand has been to remind us,
that though "`there are differences of administrations,
it is the same spirit`" which actuates the whole of Christ`'s mystical body,
"`the Church of the first-born, whose names are written in heaven.`"
With gratitude, also, we have to acknowledge your liberal bestowment of school-books,
tracts, clothing for natives, medicines, etc.,
which will remain behind you as a memorial of your Christian kindness.

The pleasure of our meeting together, is,
alas! now embittered by the painfulness of separation;--but
our high calling entitles us to the privilege of a friendship,
which is not interrupted by distance or time.
We cannot, however, at your advanced age,
and the immense distance which will ere long separate us,
but be solemnly reminded of the affecting words of the
venerable apostle to the elders of Ephesus,
"`And now I know that ye all among whom I have gone preaching the kingdom of God,
shall see my face no more!`"

It is our earnest prayer to God for you, that if consistent with His will,
you may be spared to return to our beloved native land, and to the bosom of your family,
to tell all your eyes have seen of "`what God hath wrought
among the Gentiles by the ministry of reconciliation.`"

Pray for us, that the word of the Lord may have free course,
and be glorified in New Zealand;
and that we may be delivered from unreasonable and wicked men.

Finally, Reverend and dear Sir, we bid you farewell,
and remain in the bonds of Christian friendship.

[.signed-section-closing]
Yours, very affectionately,

[.signed-section-signature]
Charles Baker, James Stack, William Colenss, William Thomas Fairburn

[.postscript]
====

P+++.+++ S.--A difference of location of several of our brethren,
and the absence of some from home, will not allow of their signing their names;
but we can confidently say,
they fully agree with us in this expression of our sentiments.

====

--

[.offset]
+++[+++No circumstance attending Daniel Wheeler`'s visit to the South Sea Islands,
appears to have more painfully affected his feelings,
than the observation forced upon him from place to place,
of the demoralizing and devastating effects of the intercourse
of the natives with the crews of vessels visiting their shores.
In some letters, not forming a part of his Journal, he thus alludes to the subject.]

We find that the voyages of the whaling-vessels are much longer than formerly,
their success being more precarious and uncertain,
owing to the increased number of ships engaged in that employ,
which constantly disturb a great breadth of ocean,
by looking over several hundred square miles of its surface every day;
so that the fish are becoming scarcer, and more shy than formerly.
We should rejoice to hear of any cause that would reduce the
number of shipping which visit these islands for supplies,
and to refit; as they only tend to diminish their population,
by bringing spirituous liquors amongst the people, and by keeping alive a disease,
the ravages of which are destroying whole families, both old and young,
to an extent little contemplated in England,
and truly painful and distressing to be an eye-witness to,
and which is greatly aggravated by the use of ardent spirits.
Surely, something will be done to stop this desolating scourge of the human race.
It is the suffering case of an afflicted, injured people, and calls for the attention,
and that speedily, of the legislature of every country,
but particularly of England and America,
which are the nations principally implicated in this dreadful traffic.
Scarcely a ship arrives, but what has for sale rum, muskets, and gunpowder,
for all of which the natives are extremely eager:
many of these are denominated '`Temperance ships,`' and yet are
engaged in producing madness amongst the natives,
by furnishing the means of intoxication,
at the same time supplying them with weapons of destruction to complete their misery.
We saw much of this whilst our lot was cast amongst them:
and although in certain of the islands the use of spirits is forbidden,
and the article itself destroyed when found, yet, even in those,
there are too many who carry on the trade in an underhand manner;
and of late its effects have been more and more apparent.
Those who have it in their power effectually to stop it,
are in their hearts desirous that it should be allowed; they not only like it themselves,
but are fully aware how profitable the sale is to those that deal in it.
Again,
if my friends at home could witness for themselves the
state of many of the islands in these seas,
which we have visited,--lamentation and mourning and woe,
must inevitably be their portion.
Rum, muskets, and gunpowder, are articles brought in great abundance,
particularly by the American ships,
many of which are styled '`Temperance ships.`' It is an incontrovertible fact,
that vessels of this description have landed larger quantities
of spirits on some islands than any other class of ships.
On almost every island the population decreases,
and the dreadful ravages made by disease is much aggravated by the use of spirits.

[.offset]
+++[+++After giving an affecting description of the consequences of disease,
and mentioning that he had, in as many cases as his stock of medicine would allow,
successfully checked and eradicated it, he adds:--]

The island of Bolabola is one that has suffered
most of any by the introduction of spirits,
as it has caused the people to distil their bread-fruit,
and every kind of food capable of producing spirit.
I can never forget the abject wretched state of these people,
with scarcely rags to cover them, in want of everything,
and possessing nothing to purchase any thing with,
their little property being consumed in order to obtain spirits:
the famished appearance also, of the more than halfnaked children, who abound,
will long retain a place in my memory,
in that love which must ever intercede on behalf of,
and plead the cause of suffering humanity.
The little things used to come on board to us; and when on shore,
we were surrounded in a few minutes by delighted groups of them.
My heart often revisits Bolabola,
and gladly would I bind up her wretched inhabitants in
the Lord`'s bundle of life forever.

20th.--Yesterday, the weather was fine and wind fair.
In the evening, the island of New Zealand was scarcely distinguishable from the deck.
We are now steering a course for New South Wales, I trust, in the right line of things,
to reach the port of Sydney, having nothing on my mind towards any other place.
Not having sat down yesterday, we held our little meeting this morning;
the forepart was more lively than sometimes, but the latter, as regards myself,
was unusually heavy.
At sundown, three whaling vessels were in company together.
As night approached, a heavy swell from the north-east,
and a still heavier from the southward, increased upon us,
after having fairly passed the isles of the three Kings of New Zealand.
The vessel lurched with such violence and suddenness,
owing to these cross and heavy swells of the sea,
that about ten o`'clock p.m. the topmast was carried away.
By midnight, the fragments of the mast,
and the shattered rigging and sail were rescued and properly secured.

24th.--On First day,
the weather being too rough for us to admit much light into the cabin,
and the heat being oppressive in the vessel below deck,
our crew were not assembled as at other times.
Fair wind and heavy sea through the day.
Our captain ascertained that seventy miles had been lost in forty-eight hours,
by an opposing current;
to which cause the cross swell and agitated state of the sea might fairly be attributed.
Today, our people were employed in substituting our flying jib-boom for a topmast,
which as a jury mast, will help to drive us along;
but in point of strength it is much inferior to the old topmast,
which came from England with us, and has stood ever since;
happily no one was hurt when the accident of losing it occurred,
which ought to be remembered with thankfulness of heart.

26th.--Today, the weather is favourable with less wind; we made but little headway.
We sat down in the forenoon in much poverty and strippedness,
and yet under a peaceful covering.
My Charles complains today of much pain in his side,
owing I believe to the great damp in the cabin,
produced by our having been closely shut up,
to prevent the sea from getting down in a wholesale manner;
but the water makes its way through so many places in the decks,
as to make every article of clothing and bedding too damp for use: we have, however,
no alternative, and hope, in a few days, again to see better times.
A sight of New Holland, will, I trust, revive and animate us.

27th.--Gentle breezes and fair all night.
At three o`'clock a.m., Lord Howe`'s Island was discovered upon the lee-bow,
and at day-break Ball`'s Pyramid on the weather-bow.
At ten o`'clock, passed between them with breeze from north northeast.
Upon Lord Howe`'s Island, there are three Englishmen residing,
who have women from New Zealand as wives.
It appears that they have raised hogs, potatoes and cabbages,
sufficient for the supply of fourteen whaling vessels in a year.
We are, this day at noon, four hundred miles from the shores of New Holland.
Charles seems better this morning.

28th--The heat of the atmosphere quite oppressive, and below deck almost insupportable.
After midnight the lightning was extremely vivid all round us,
with thunder at times awfully loud and near the vessel; the rain falling in torrents,
and the wind flying about, first on one side, and then on the other.
At five o`'clock a.m., the breeze became strong and steady from the south south-east,
which enabled us to pursue our course.

29th. (First day.)--A portion of the Scriptures was read to the crew,
only three of whom attended.
The air much cooler since the thunder-storm.
The state of feeling with me, both as to mind and body, for the last two days,
cannot be easily described; the former, as if it had never known good;
and yet the loss could not be felt, if the possession had never been witnessed.
It is, however,
to myself a relieving proof or evidence that a spark of life still remains,
for that which is dead cannot feel: but outward circumstances, which affect the body,
also bear upon the mind, though imperceptibly,
and at the moment unthought of as having any share in the mental conflict.
Below deck the water filters through upon us in many places:
the deck above us is drenched again and again by the breaking tops of the waves;
the motion of the vessel is so violent and incessant as to admit of no rest,
either sitting or lying, and walking is altogether impracticable.
Perhaps,
the motto of '`Brighter hours will come,`' is particularly appropriate in our case;
and we may yet be permitted to realize the fact itself,
and the language of David exultingly be ours,--"`God hath spoken in his holiness;
I will rejoice.`"

30th.--A fresh gale all night; but the moon rising about midnight,
enabled us to run towards the land without fear.
At daylight, several parts of the coast could be seen, from Port Stephen to the eastward.
At eight o`'clock a.m., the lighthouse upon the South Head appeared.
Strong breezes with considerable sea from the southward and eastward.
Soon after getting sight of the Heads, which form the entrance into Sydney,
a bark was seen standing into the offing, that had just come out of the harbour.
Not knowing but that she was one of the homeward bound for England,
and thinking this might possibly be an opportunity of letting
our dear friends know of our return to New South Wales,
from the isles of the Pacific, the Henry Freeling`'s flag was hoisted immediately, but,
on getting nearer to her, she was found to be a whaling vessel,
by the number of boats which she carried.
At ten o`'clock, took in a pilot and bore up for the harbour,
and before two o`'clock were safely anchored in the Cove.
In the evening, moored close under the government domain,
about thirty yards from the shore, by the side of the Jessie, of Liverpool.
Here we found several ships preparing to take in cargoes for London,
also the Rattlesnake and Victor men-of-war.
Our arrival was soon known in the neighbourhood.
Abraham Davy was shortly on board,
and our dear friends James Backhouse and George
Washington Walker were not long before they reached us:
our joy was mutual at seeing each other`'s faces again,
and I trust that our hearts were filled with gratitude and thankfulness to Him,
who had sustained us through all, and brought it about for His great name`'s sake.
It was afterwards ascertained,
that a number of letters from England and home were lying in store for us.
Accounts of the welfare of our beloved family at Shoosharry,
beyond my most sanguine expectations,
were received up to within seven months of the present date;
not having heard of them for nearly two years, they seemed now restored to us again,
as a treasure enhanced in value an hundred fold indeed,
but still far beyond the reach of full possession.
Humbled under a sense of the Lord`'s everlasting love and faithfulness,
my heart rejoiced before Him.

Second Month 2nd. (Fifth day.)--Attended the meeting in Sydney at eleven a.m.,
held in a comfortable building,
erected for the purpose during our absence from these shores.
Twelve persons were the whole number present: it was a silent meeting.
May faith and strength be more and more increased, if consistent with the Divine will,
and a door effectually opened for the word of
the gospel to be declared amongst these people;
that the name of the Lord may be glorified, and the way of life and salvation,
as it is in Jesus, set before them,
to the exaltation of the blessed Saviour`'s spiritual kingdom in the heart of man;
of the increase of whose government and peace, there shall be no end,
but the earth shall be filled with His praise.

[.offset]
+++[+++Daniel Wheeler and his son remained at Sydney until the 30th of Seventh Month,
when they sailed for Hobart Town.
Much public service did not devolve upon him whilst at Sydney; when health permitted,
he regularly attended the meetings for worship on First and Fifth days,
kept up by a few individuals professing with Friends in that town,
which were not unfrequently resorted to by others.
Soon after their arrival at Sydney, agreeably with arrangements made on leaving England,
the Henry Freeling was sold, the ship`'s company were discharged,
and the numerous surplus stores belonging to the ship disposed of;
these engagements undertaken in an exhausted state of health, occupied much time.
The following extracts from his journal and letters, refer to this period.]

[.embedded-content-document.letter]
--

[.letter-heading]
To John Kitching

[.signed-section-context-open]
Sydney, Third Month 3rd, 1837

I consider it no small favour that our crew have passed through the
voyage amongst the islands in so exemplary a manner.
Their good behaviour was remarked and commented on by the missionaries and others,
at various places.
They seemed to consider themselves bound to do nothing
that would be likely to bring reproach on the vessel,
on account of the object which she was engaged to promote.
Instead of being shunned and feared as dangerous people by the missionaries,
which is the case with the generality of sailors,
they were looked upon as quite a different class of men,
and treated with marked kindness on account of their orderly deportment.
Towards the latter part of the voyage, their patience began to get exhausted:
they longed for home;
and on reaching New Zealand they were like people "`weary in
well doing`" but I think this arose in great measure from our
unavoidably coming into close contact with other vessels,
where they could not fail to be assailed with continual jeers;
and the ridiculous stories as to the supposed
strict discipline they were under in our vessel,
(such as their having to pay a dollar for every oath they swore,)
seemed to make them think they really were rigidly treated,
and their just rights withheld from them.
Two or three of them at one time seemed desirous of settling in New Zealand;
this served to amuse, and keep their thoughts engaged,
and I promised them their discharge on reaching New Holland.
Sometimes in the night watches,
I used to lay before them the comfort they might enjoy when they got to England,
if they took proper care of their money;
and some of them seemed quite to enter into the idea of not having to go to sea again,
which with a little assistance might certainly have been realized.

It was my earnest desire on first setting out,
that our voyage together might truly be one towards the kingdom of heaven; but now,
if I except two or three individuals, every hope of this kind has vanished,
and has been exchanged for the painful certainty,
that after all the advantages they have enjoyed,
and the victory they seemed to have gained over the temptations which
in former days had so often prevailed over them,
they have again relapsed to their old degradation.
Perhaps they may not have gone to the full
extent that it is common in this horrible place;
yet there is little doubt that they have nearly
got through their money in a dissipated manner.

However much this is to be deplored on their account,
it is a consolation that nothing of the sort occurred
while they belonged to the Henry Freeling,
and that whatever infamy they may bring upon themselves,
it is altogether unconnected with that vessel,
and cannot bear in the least on the object of her late voyage.
Their conduct here is thought nothing of,
and passes unnoticed amidst the general mass of
wickedness with which this place overflows.
Let the conduct of those sailors be ever so notorious,
no one asks to what ship they belong; the thing is so common, and of hourly occurrence.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Same

[.signed-section-context-open]
Sydney, Third Month 18th, 1837.

Our dear friends James Backhouse and George W. Walker
took their departure from these shores last First day,
the 12th instant; so that we are sitting desolate,
and somewhat resembling those that are forsaken; but,
alas! not amongst an afflicted people.
Would that I could say so; but instead of this,
I think this is as wicked a place as any I have seen,
which have not been a few in my day.
Pride and haughtiness abound,
and lamentable ignorance of spiritual religion is manifest on every side:
indeed few seem to make even an outward profession of it.
Drunkenness appears to be the prevailing sin,
which leads to the most deadly amongst the working part of the community,
although it is not confined to their grade.
The major part of the lower order are bound in the fetters of popery;
and for the most part are prisoners who have obtained tickets of leave,
or they are what are called assigned servants,
many of whom have been accustomed to crime from their very youth.
The contrast is very and painfully striking with what
we have seen among the poor and benighted islanders,
with whom our lot has lately been cast;
the situation of many of these may be considered enviable,
when compared with the miserable wretchedness of many here,
who consider themselves Christians.
Cursing and bitterness resound continually through the streets;
and extortion and deceit prevail almost universally among the shop-keepers,
on whose promises hardly any dependence can be placed.
Many have amassed considerable wealth by extortion and the sale of spirits;
and having risen only as from a dung-hill, are living as if there was no God,
no judgment, and no world to come,--and length of days at their command.
Those who come out as settlers are generally of a better stamp,
though even among these there is little stability of character.

This is the state of the rising and fast flourishing
colony of Sydney and its neighbourhood;
but the most grievous thing we witness is the miserable
condition of the aborigines of the country,
who are frequently seen rolling about the streets in groups, altogether intoxicated;
whilst their emaciated frames declare,
that they are fast wasting from the surface of the earth.
They too, are following the dreadful example set before them,
of cursing and swearing in the English tongue,
which they have learnt from their exterminating visitors.

How long we may have to remain here, I know not;
but I desire to be resigned to wait the blessed Master`'s time.

--

[.asterism]
'''

Third Month 26th.--In the forenoon meeting yesterday I had a close,
searching testimony to bear,--standing up with the
words of our Lord,--"`If thine eye offend thee,
pluck it out: it is better for thee to enter into the kingdom of God with one eye,
than having two eyes, to be cast into hell fire; where their worm dieth not,
and the fire is not quenched.`"
Stating that I believed it safest for me to revive these expressions in their hearing,
lest there should be any present who were sensible that
something stood in the way between them and eternal life;
and though this might be dear to them as a right hand, a right foot, or a right eye,
it would be their soul`'s true interest to pluck it out, or cut it off,
and cast it from them, before it was too late to enter into life,
even halt or maimed or with one eye,
and before the day of the Lord`'s visitation was passed away forever.
Entreating all to lay aside every weight and every burden,
and that sin which most easily besets,
and "`run with patience the race that is set before us,
looking unto Jesus the author and finisher of our faith; who,
for the joy that was set before Him, endured the cross, despising the shame,
and is set down at the right hand of the throne of God.`"

Fourth Month 3rd.--Yesterday the forenoon meeting was
better attended than is frequently the case;
in the course of which it was with me to recite the
words of the Saviour to his disciples,--"`If ye love me,
keep my commandments;`"--stating my belief that it would be
difficult to find any who profess to believe in Christ,
who have not a hope that they love Him.
But let us prove what ground we have for this hope by the test of obedience,
and examine how far we really have obeyed the commands of Christ: His commandments,
as His promises, are "`yea and amen forever.`"
"`Seek ye first the kingdom of God and his righteousness.`"
Have we obeyed this important command? Has this been the employment of our life,
as the first and primary object of our search,
by which all things needful shall be added unto
us? Or have we only occasionally remembered it,
whilst following with eagerness after the follies, and vanities, and riches of the world;
instead of laying up for ourselves "`treasure in heaven?`" Have we
been securing to ourselves the enduring riches of eternity,
by seeking this kingdom as it should be sought,
"`first`" before all other things? It is time for some of us who are advanced in life,
diligently to examine how we stand in this important search,
and more especially so for those who make mention of His name before men.
It is evident,
that those whom our Lord enjoined to "`seek first the kingdom of God,`"
were fearful that whilst in pursuit of this heavenly treasure,
they should fall short of the food and raiment necessary for their poor perishing bodies.
"`Behold the fowls of the air:`" "`Consider the lilies of the field,`" etc.,
said our Saviour, as encouragement to these of "`little faith.`"

8th.--Attended the funeral of the wife of William Satterthwaite.
The privilege of interment in the ground recently bequeathed to the Society of Friends,
was granted at his request, his wife having formerly been a member.
This being the first interment at Sydney conducted after the manner of Friends,
it is probable that many would have attended out of curiosity,
had not the morning been extremely wet.
The whole was conducted in a consistent manner.
I had to remind those present, that to our own Master we must stand or fall:
the work is our own, and the reward is our own.
"`No man can save his brother.`"
And although nothing said or done by the living can possibly affect the dead;
yet the dead are often powerful preachers to the living,
warning them to flee from the wrath to come, by preparing for their latter end.
"`For we must all appear before the judgment seat of Christ,
that every one may receive the things done in the body, according to that he hath done,
whether it be good or bad.`"
"`Every man`'s work shall be made manifest, for the day shall declare it.`"
Blessed and happy are they that are building on the ancient and sure foundation,
which the righteous in all ages have built upon;--even Christ Jesus,
that tried corner-stone;--"`unto the Jews a stumbling block,
and unto the Greeks foolishness; but unto them which are called, both Jews and Greeks,
Christ the power of God, and the wisdom of God.`"
This is a stone of stumbling, and a rock of offence to all unbelievers now,
as in the day when this declaration was made; but to those who believe,
it is "`a chief corner-stone, elect,
precious,`"--and the blessed means appointed for the salvation of all mankind,
who are willing to submit to the power of the Holy Spirit of the Lord Jesus in the heart.
Although it was a scene never before witnessed here,
those present were very attentive and solid, and I had peace: it appeared afterwards,
that two Jews were present in the graveyard.

9th. (First day.)--In the forenoon meeting I had
to set forth the righteousness of Christ Jesus;
without which, none can enter the kingdom of heaven.
There are many highly professing Christians in this our day,
who like the Scribes and Pharisees of old, have a righteousness of their own making;
but a more excellent righteousness must be attained to,
than any that man is capable of clothing himself with,
before the heart is converted unto God.
"`Except your righteousness exceed the righteousness of the Scribes and Pharisees,
ye shall in no case enter into the kingdom of heaven,`" was declared by our Lord.
Now this righteousness which excelleth, is of the Lord;
and none but His children who have been taught of Him, are acquainted with it.
There are many who take upon themselves to teach others the way to the heavenly kingdom,
who "`being ignorant of God`'s righteousness,
and going about to establish their own righteousness,
have not submitted themselves to the righteousness of God.`"
Nothing but the righteousness of Christ Jesus believed in, and operating in our hearts,
by the power of the Holy Spirit, and submitted to on our part, will be availing.
It is this alone that can purify us as He is pure,
and procure for us an entrance into the everlasting kingdom of "`righteousness and peace,
and joy in the Holy Ghost.`"
Whatever may be our profession before men,
if we have not the righteousness of Christ Jesus,
we shall be like the poor man of whom we read; who, destitute of the wedding garment,
was speechless, when the question was put to him by the king,--"`Friend,
how camest thou in hither,
not having a wedding garment?`" After this manner I was largely opened amongst them.
Some strangers were present, but the whole number did not, I think,
exceed eighteen persons.
The evening meeting was smaller, but held under a comfortable quiet.

15th.--This week the passengers from the ship Lady Macnaughten have been landed;
after being some weeks under quarantine, which the vessel was subjected to on arrival.
We understand that there has been great suffering among them during the
latter part of the voyage for want of the actual necessaries of life:
many of them have been swept away by a contagious disorder, which prevailed on board.
It is much to be regretted that no efficient measures are in force,
to protect the emigrants from the cruel rapacity of some of the ship owners and agents.

23rd. (First day.)--This morning attended the funeral of William Satterthwaite.
During a solemn pause before the coffin was lowered into the grave,
I had to call the attention of the by-standers to the awful instance before us,
of the necessity of being prepared individually for the great change:
"`prepare to meet thy God,`" was sounded among them.
None of us know how soon the undeniable messenger may be sent to our
houses:--are we then acquainted with the appointed means of salvation?
Nothing will avail us in that hour of extremity,
but an interest in the Lord Jesus, unto whom all power in heaven and earth is given.
He died for the sins of all mankind, that all mankind might live.
Are we acquainted with the power of his Holy Spirit in our hearts?
Have we not felt this power in our hearts when we have committed sin,
convincing us of sin, and reproving for it?
Have we bowed to it in obedience, and acknowledged its might,
and thereby known its sufficiency to save from our sins? If so,
we have hearkened to the voice of the well-beloved Son, in spirit.
But if we have resisted this power when striving with us, set it at naught,
and rebelled against it, the day will yet come upon us,
when we shall have to bow before it,
but it will be in judgment for sin and transgression unrepented of,
in anguish of heart for having thus disregarded the Holy Spirit,
purchased by the blood of the Lamb of God.
There might be some present of various religious sentiments;
but however our opinions differ in some things, in one we shall all agree,
that we must all die, and all stand before the judgment seat of Christ: then,
how needful it is for us to be ready,
when called upon to return the spirit unto God who gave it, with joy and not with grief.

30th. (First day.)--In the forenoon meeting it was with me to revive
the language of the apostle when addressing the primitive believers,
who had witnessed the beauty and spirituality of the gospel dispensation,
when every man may sit under his own vine, and under his own fig tree,
and none shall make him afraid; which is realized at this day,
to all true believers in the second coming of the Lord Jesus,
by the Holy Spirit in the heart of man;--"`The anointing which
ye have received of Him (Christ) abideth in you,
and ye need not that any man teach you;
but as the same anointing teacheth you of all things, and is truth, and is no lie,
and even as it hath taught you, ye shall abide in Him.`"
What a great and precious privilege it is to be permitted to sit as at the feet of Jesus,
to hear the gracious words that proceed from Him;
it is the one thing needful for all to do,--the part which Mary chose,
and which our Lord declared should never be taken away from her.
It is this inward teaching of the Holy Spirit, that I want all to believe in,
and be acquainted with for and in themselves.
Those who have received from Him the anointing which abideth,
are qualified to give an account of the hope that is in them,
not only in meekness and fear,
but from heart-felt knowledge of the coming of the Son of God in spirit.
"`We believe and are sure that thou art that Christ,`" said Simon Peter,
when many had turned back and walked no more with Him,
on account of the narrowness of the path which leads to life.
"`Will ye also go away,`" said our Lord to the few remaining disciples:--
"`to whom shall we go?`" said Peter,--"`Thou hast the words of eternal life;
and we believe and are sure, that thou art that Christ, the Son of the living God.`"
Of this, and of the blessedness of those who come to this knowledge,
I had further to impart.

[.offset]
+++[+++It was whilst at Sydney that Daniel Wheeler received the
deeply affecting intelligence of the death of his eldest son,
William Wheeler, who had succeeded his father in his agricultural concerns in Russia.
He died on the 24th of Eleventh Month, 1836, at the Sand Rock Hotel, near Niton,
on the Isle of Wight, to which place he had resorted for a more genial climate:
his illness was a consumption, which rapidly terminated his life.
The first intelligence of this event came to hand in a public journal,
and proved a keen stroke; but was borne with much Christian resignation.
The life of William Wheeler had been marked by watchfulness and prayer;
and a conscientious regard to the pointing of Divine
wisdom in the discharge of his religious duties,
as well as by an active and diligent attention to his concerns
in business;--his end was eminently crowned with peace,
and an humble and confiding trust in redeeming mercy.]

Fifth Month 30th.--A letter has reached us by way of Hobarton, from our beloved Joshua,
conveying the long anticipated confirmation of
the painful report already in our possession,
that our dear William has finished his earthly course.^
footnote:[His son Joshua was removed by death about four years after;
decease took place at Clifton, on the 29th of Third Month, 1841.
He was mercifully permitted, towards the close of life, to enjoy a trembling,
but we trust a well-founded hope of acceptance.]
Although we have lost what never can be regained in this world;
yet the accompanying particulars of his last
days administered great consolation and relief,
and raised in my heart a tribute of humble thankfulness to the great Preserver of men,
who indeed "`loveth his own unto the end,`" at once removing all my doubts,
and causing me in the depths of distress,
to triumph with admiration at the lovingkindness of
the Lord to the poor and to "`him that hath no helper.`"
On reviewing with calmness the provision which
has been made for every exigency of the case,
I was constrained to acknowledge, that had it been practicable,
I could not have made any arrangement more satisfactory to myself;
so that while I am enabled to say Amen, so be it, to this dispensation of His holy will,
who wrought the work,--I can rejoice in the sustaining belief,
and give thanks at the remembrance of His holiness, that the loss sustained is only ours;
to the dear departed soul it is eternal gain,
through the tender mercy of God in Christ Jesus.
And now,
some things which at first sight only seemed to aggravate and add to our affliction,
appear to have formed a part of the great whole which has been vouchsafed,
by having in degree prepared our minds for the mournful event,
of which we were afterwards more fully to be informed.
Although the tidings received through a channel so unexpected and abrupt,
plunged us at once into deep affliction, as a stern harbinger of woe;
yet even this could afterwards be viewed as a blessing in disguise,
gradually to lighten the weight of an overwhelming reality,
and lessen the density of the gloom about to envelope us.
"`By watering, he wearieth the thick cloud,`" saith Job;
so doth the tear of affection when shed in meekness and submission,
soften the heart`'s keenest anguish,
until the dark cloud of grief dissolves into resignation to the Divine will,
and is sanctified to the praise and glory of God.
For some days my dear Charles could not divest himself of the idea,
that such a report might have got into the newspaper
accidentally and without any foundation in fact;
but this slender ray of hope was of short duration.

Sixth Month 11th. (First day.)--Since the 30th ultimo my pen
has been laid aside as to a record of passing events,
either outward or inward.
My harp has been hung, as it were, upon the willow, and my lips have been sealed;
but at seasons my heart has been softened by the love of God,
and my peace has been permitted to flow as the stream of a mighty river,
sheltered from every ruffling blast, and too strong to be impeded by trifles.
In the meeting this evening a word of encouragement was spoken to the poor and needy,
that are hungering and thirsting after heavenly food,
and looking to the Lord alone for their souls`' nourishment:
verily the Lord will hear them, and they shall be fed.

18th.--Since last First day, various have been my trials and provings;
but the Divine hand has sustained through all;
and by letters now received from England I am greatly comforted,
inasmuch as the belief so strong in my heart, of the mercy and compassion of my God,
is more than ever confirmed as regards the close of my precious William,--in
several particulars far more abundantly than I could have conceived;
and above all,
in the certain evidence that He hath crowned him with
everlasting life:--I had nothing more to ask.
"`The Lord hath heard the voice of my weeping;--the Lord hath heard my
supplication;--the Lord hath received my prayer;`" and the kingdom,
and the power, and the glory are His, forever.

26th.--The way seems now to open more and more for us to leave this place:
I humbly pray that we may be rightly directed, both as to the time,
and the next place of our destination.

At our morning meeting yesterday several persons attended,
who were evidently unaccustomed to sit in silence:
they stayed till near the conclusion of the meeting.
A Friend who has lately come to settle here, spoke a few words,
though perhaps from diffidence too long withheld, to the effect that,
the most eloquent language, if the heart be not right, however esteemed among men,
is an abomination in the sight of God, who seeth not as man seeth.
"`Man looketh at the outward appearance, but the Lord looketh on the heart.`"

Seventh Month 10th.--On First day the 2nd,
both the meetings were held in silence throughout: this cannot be wondered at,
when the expectation of many that attend on these days is evidently placed upon man,
instead of gathering inward to the great Teacher of his people.
Yesterday, the forenoon meeting was also held in silence:
in the evening the new covenant and its holy Mediator Christ Jesus,
were proclaimed amongst the people, to my own relief.
A solemn feeling was vouchsafed, under which we separated.

17th.--The fore-part of the morning meeting yesterday
was greatly disturbed by persons coming in,
and shortly going out again: towards the conclusion more settled quiet prevailed.
The evening meeting was altogether more comfortable.
The complaint of the Most High, through the holy prophet to His people formerly,
it is greatly to be feared is equally applicable to
many professing Christianity in this gospel day,
as when uttered by Divine inspiration,
in that period of degeneracy:--"`The ox knoweth his owner, and the ass his master`'s crib;
but Israel doth not know, my people do not consider.`"
I was largely opened to speak of the means mercifully afforded to all,
through the blood of Jesus;
by whom alone we can come to a saving knowledge of God the Father,
and of His beloved Son, on which knowledge eternal life depends.

During the past week a cargo of male convicts arrived from London;
and one of female convicts from Dublin.
A vessel also came in with male emigrants from Scotland;
and another with females from Ireland;
the former having lost twenty-three of her passengers in typhus fever during her voyage,
was placed under quarantine on arrival.

15th.--Attended the funeral of our landlord,
who died after a severe illness four days ago.
It was not a pleasing task,
to bear our public testimony against the forms and practices adopted on such occasions;
but I did not feel satisfied to absent myself.
The service was performed according to the usual forms of the Episcopalian establishment;
and although consisting of Scripture language was painfully inapplicable to the occasion.
Our standing the whole time with our hats on, might be a new thing in the colony,
but no notice was openly taken of it.

22nd.--Arrived the Marian Watson from Hobarton.
Went on board and secured our passage on her return.
Two days ago we very accidentally ascertained, from a public print,
that the house and furniture where we are lodging are
advertised for sale almost immediately.
This circumstance, for want of any previous notice,
has subjected us to much inconvenience, and no light expense,
as the Marian Watson will not be ready for sea for some time to come,
so that we must occupy fresh quarters in the mean time.
It may, however, serve renewedly to remind us,
that here we have no continuing city of habitation;
but if when the conflicts of time are ended,
we should be mercifully favoured to reach one that hath foundations and is everlasting,
every earthly change and suffering will be light as the dust of the balance,
and not worth a thought;
save only as they may have contributed to work for us a
far more exceeding and eternal weight of glory.

24th.--Having with much fatigue removed all our
baggage to an hotel near the head of the cove,
to be in readiness for embarkation,
we expected to have ample time to make our final arrangements in a comfortable manner;
but my Charles is so much indisposed,
that I scarcely know whether to venture the risk
of removing to Hobarton at this inclement season.
He does not, however, appear willing, notwithstanding present discouragements,
that the voyage should be delayed.
Our lodgings are so infested with rats,
that little undisturbed rest can be obtained at night;
though we have exerted all the skill we are masters of,
in blocking up their numerous holes, and have the assistance of an excellent cat.

30th. (First day.)--In the forenoon attended the meeting;
I had to bear testimony to the power of Truth in the heart,
if believed in and submitted to.
Just as we are concerned to dwell near to this power in our daily walks through life,
shall we be permitted to witness its influence upon our minds,
when met together for the purpose of worshipping that God who is a Spirit,
and must be worshipped in spirit and in truth.
It was declared by the Saviour of the world, when personally on earth,
that where two or three are gathered together in His name,
there is He in the midst of them.
But it would be well for us all to examine,
whether we are met in His name? whether His name, which is His power,
doth rule and reign in our hearts? whether our thoughts are brought
into obedience to the Spirit of Truth? None can meet in His name,
in the expectation of witnessing His presence in the midst of them,
but those who are subject to his power.
It is for want of submission to this power in our hearts, that so many sit in dry places,
where there is neither dew, nor rain, nor fields of offering.
Such go from meetings as they came, barren, unfruitful, and unrefreshed;
yet the Divine promise stands fast.
"`Where two or three are gathered together in my name, there am I in the midst of them.`"

31st.--Left the colony of New South Wales, with a gentle and favourable breeze.
There are on board ten prisoners in chains, with a guard of five soldiers,
making up with the captain, crew and passengers, thirty-nine persons.

[.offset]
+++[+++After a voyage of eleven days, they reached Hobart Town,
where they rejoined our friends James Backhouse and George W. Walker.
Here again the ministerial labours of Daniel Wheeler,
appear to have been pretty much confined to the meetings for Divine worship,
kept up in this town by persons professing with Friends,
and regularly held on First and Fifth

[.offset]
+++[+++Extract from a letter dated Hobart Town, Eighth Month 16th, 1837.]

It is encouraging to observe,
that the number of those who profess with us in this place is considerably increased,
since our visit three years ago; but the house where they meet is so small,
that the addition of Charles and myself amounts almost to an inconvenience,
and the members are not in a capacity of themselves to remedy the difficulty.
On First day last, in the morning, eight persons appeared in the ministry;
and I think the persevering manner in which several of these attend,
under very discouraging circumstances, and the solid deportment they manifest,
is a strong indication of their having found something,
which "`the topaz of Ethiopia cannot equal`" in value,
nor the wealth of the universe purchase.
About forty persons were present.
Of the above individuals alluded to as having spoken,
six are of those who have joined the Society by convincement.
I am told that occasionally a still greater number than this open their mouths;
and is it not a natural consequence, that as the heart believeth unto righteousness,
with the mouth confession is made unto salvation.
If these were to hold their peace,
would not the very stones cry out? In my apprehension it does not necessarily follow,
that such as these must become hereafter, or be extensively employed as gospel ministers;
although they are thus constrained, like the tenth leper that was cleansed,
to return and give glory to God,
from a sensible conviction of the working of the power of the Spirit of Him,
who speaketh in righteousness, is mighty to save from sin,
and that to the very uttermost.
I need not say more of these interesting people, as I find from dear James Backhouse,
that their case is already known to Friends in England in every particular.

[.asterism]
'''

22nd.--We attended a meeting of the temperance society, held in Hobart Town:
my mind is more and more impressed with the great importance of this institution,
from a conviction that next to the gospel of life and salvation,
and the circulation of the Holy Scriptures,
it is of the highest importance to the well being of the human race.
Nothing stands more opposed to the benign influence of the gospel than intemperance.
I believed it my duty to speak on this important subject.

27th.--In the forenoon the little meetinghouse was filled.
James Backhouse had good service both in testimony and supplication.
The afternoon meeting was somewhat smaller:
James Backhouse had again to exercise his gift.
Although much of what was expressed during the day passed before the view of my mind,
yet not feeling what I deem sufficient qualification to warrant my standing up,
I had no part in the vocal service;
and although under much poverty of spirit was not conscious of
having withheld what should have been uttered.

Tenth Month 1st. (First day.)--In the forenoon an
individual who has attended meetings for some time,
expressed a few words under much exercise of mind: he said,
it has been strongly impressed upon his mind to say,
"`the meek shall inherit the earth,`"--adding,
and the humble Christian doth inherit all things.
After some other communications,
I had to remind the meeting that the two mites cast into the treasury by the poor widow,
were of more value than all that had been given by the rich;
these gave of their abundance, but she had given all that she had.
It is not the magnitude of the offering that insureth its acceptance with the Lord:
He seeth not as man seeth.
"`Lebanon is not sufficient to burn,
nor the beasts thereof for a burnt offering.`"--"`To obey is better than sacrifice,
and to hearken to the voice of the Lord than the fat of rams.`"--"`If
ye know these things,`" said our Lord to his immediate followers,
"`happy are ye, if ye do them.`"
Knowledge will profit us little, unless obedience keeps pace therewith.
It is not the hearers of the law, but the doers,
that are justified in the sight of Almighty God.
"`It is not every one that saith unto me, Lord, Lord,`" said Christ,
"`that shall enter into the kingdom,
but he that doeth the will of my Father which is in heaven.`"
Therefore whilst we labour after humility and resignation of mind in sincerity to say,
"`not my will but thine be done,`"--let us at the same time be
earnestly desirous to ascertain what is the Lord`'s will concerning us.
But this can never be done in the noise and mixture of the world;
it must be sought for in retirement, in the silence of all flesh,
and that more frequently than the returning morning, and in the night watches also.
We cannot reasonably expect to be entrusted with a knowledge of the Divine will,
if we conform to the world and its practices.
"`Be not conformed to this world, but be ye transformed by the renewing of your mind;
that ye may prove what is that good and acceptable and perfect will of God.`"
The judgments of the Lord must pass over the transgressing
nature in our hearts to redeem us therefrom;
and it is only by and through the righteousness
of Christ believed in and operating in us,
that our minds can be transformed and renewed unto God.
The meeting was in the forepart very unsettled and discouraging,
but it ended well under a very solemn feeling.

31st.--Not feeling bound to remain any longer on this side of the globe,
we this day engaged places in the Lloyds,
which arrived yesterday with part of her cargo of oil, to load out here for London.

Eleventh Month 3rd.--Accompanied J. Backhouse and G. W. Walker on board the Eudora,
who were about to proceed to some of the South Australian settlements.
We did not think well to add to their unsettled situation by remaining long on board;
but soon took leave, parting from them in much love,
and under a feeling of Divine regard.
Whether we shall ever meet again in this world is very doubtful;
and as regards myself at least, I consider it a final parting;
yet we know the Lord can lengthen out our days at his pleasure.
To Him I desire to commend both them and ourselves.
The Eudora was crowded with passengers,
and in my apprehension a very undesirable vessel to sail in;
but our dear friends seemed to have no alternative left.

27th.--This day completed my sixty-sixth year.
May the Lord be graciously pleased to make me more and more,
a living monument of his everlasting mercy;
and to humble me before Him under a sense thereof, until He shall say "`it is enough.`"

30th.--Visited a young man in the hospital, who has just arrived here as a convict.
His family were formerly in comfortable circumstances in England.
He appears to have long strayed from the paths of virtue;
but the laws of his country have now arrested his wild career,
and he is sensible of his deplorable situation.
I was led to commiserate his case, thinking it very possible,
that though the hand of human justice has overtaken him,
and he is doomed to several years of painful and degrading exile;
yet that in reality he may not have been more evil-disposed than some others,
who have escaped the laws of man,
who and have in a still greater degree transgressed the laws of a righteous God,
and been still more offensive in His sight.
Amongst these I feel willing to number myself, remembering as I write,
the words of the compassionate Saviour,--"`Or those
eighteen on whom the tower of Siloam fell and slew them,
think ye that they were sinners above all men that dwell in Jerusalem? I tell you nay;
but except ye repent, ye shall all likewise perish.`"

Twelfth Month 7th.--Received a letter from our cousin John Kitching,
communicating the mournful intelligence that my precious Jane had finished her course,
and entered into rest.
These tidings had truly flown apace,
as it still wanted eight days to complete the fourth
month since they were dispatched from Petersburg.
Although this was sudden at last, and truly overwhelming for a time,
yet the mercy and goodness of our heavenly Father soon changed the strain of sorrow,
into that of adoration and thanksgiving,--binding up all the wounds
of affliction in the healing virtue of His everlasting love:
for her end had been truly peaceful; death was deprived of its sting,
and the grave of its victory.
Thus, the eldest and the youngest of my flock, have been gathered, since we left them,
into the arms of everlasting mercy;
whilst we are left a little longer in this vale of tears.
May the Lord Most High be graciously pleased to prepare us also in like manner,
for the heavenly kingdom.

After calling upon all our friends and acquaintance for the last time,
and desiring their welfare in the utmost signification of the word '`farewell,`'
we embarked on board the Lloyds late in the evening of the 9th;
and early next morning, being First day, the 10th of Twelfth Month 1837,
we began to glide gently down the Derwent towards Storm Bay.
We should have been rejoiced if the First day could have been spent in harbour;
but I believe the captain was desirous to get to sea,
in order to keep his crew from getting intoxicated on shore,
which often happens on such occasions, and causes serious delay to the shipping.

In the course of our stay at Hobarton we paid several satisfactory
visits to the Lieutenant-governor Sir John Frankland and his family.
Although the sphere in which they are accustomed to move,
is not one that comports with those who profess to be followers of the lowly Jesus;
yet we were not satisfied to shrink from such exposure altogether,
however the non-compliance on our parts with the usual practices at such times,
might entitle us to the appellation of fools by some of
the more gay and thoughtless part of the company;
if however the watch was properly maintained, our conduct may prove beneficial to others,
by leading them to inquire into the cause of our differing so
widely in life and conversation from our fellow-men.

+++[+++The voyage to London, by way of Cape Horn, was completed on the 1st of Fifth Month,
1838.]

+++[+++The following are the closing extracts from the South Sea Journal:]--

After a voyage of four months and twenty days from Van Diemen`'s Land,
and the changes from heat to cold twice experienced during that time,
my own health seemed scarcely to have been impaired;
but from the weakly state of my dear Charles,
whose constitution had been much shaken by a lengthened
illness previous to our leaving Europe,
he was less able to bear the total want of vegetables for many weeks,
to which we were exposed, and the small quantity of fresh water,
and that of a quality scarcely wholesome,
to which we were subjected the latter part of the passage.
With these disadvantages,
which there is reason to believe contributed to reduce his already diminished strength,
he landed in a very feeble and languid condition; but I humbly trust,
he is under the immediate and protecting care of the great Physician,
who alone hath power to heal, and to bless every endeavour to restore.

I should not be satisfied to conclude this unconnected and imperfect narrative,
without saying,
how greatly I have been aided in the course of this religious engagement by
the missionaries from different societies in Europe and North America;
who very kindly acted as interpreters on my behalf to the
native congregations on the islands where my lot was cast,
and opened their meetinghouses for our accommodation in the most brotherly manner;
to whom, for this assistance and Christian kindness many ways exhibited,
we feel gratefully and highly indebted.

I may also be allowed to add at the same time,
that having been encouraged by my dear friends at home
to accept the company of my son Charles Wheeler,
I have found him very useful and strengthening to me,
during our long sojourn in foreign parts, in a variety of instances,
and on many important occasions.^
footnote:[Notes respecting the South Sea Isles, etc., by Charles Wheeler,
being extracts from letters to his family, will be found in the Appendix.]

For the best welfare of the dear and interesting people,
who inhabit those isles afar off, which in the love of the gospel,
I have thus been drawn forth, and enabled to visit,--a petition however feeble,
must ever dwell in my heart;
and on whose behalf I would earnestly and affectionately crave
the fervent aspirations of all my dear brethren and sisters,
when it is well with them: and may they unite with me in commemorating the mercy,
lovingkindness and faithfulness of Him, who for His great name`'s sake,
and for His beloved Son`'s sake,
wrought the work,--hath so marvellously sustained us
through every season of trial and conflict,
and delivered us out of every distress:
that the thanksgiving of many may resound to His praise, to whom the kingdom,
and the power, and the glory, belong forever.
