== Concluding Remarks.

It is far from being the intention of the Editor to attempt any elaborate
delineation of the character of the subject of these Memoirs:--this he thinks will
be best gathered from the correspondence and memoranda which have preceded.
There is however one feature, on which he hopes the reader will bear with him,
whilst he offers a few remarks,
which appear to be called for by the peculiar opportunities for observation
which he enjoyed,--viz. the mingled fidelity and tenderness with which his
beloved father sustained the responsible character of a parent.
In reverting to this particular,
those who enjoyed the privilege of a filial relationship,
feel that they have abundant cause to rise up and call him blessed.
From their early years,
the benign influence of his devout and pious spirit was forcibly felt;
and it is now a mournful satisfaction to the survivors to recollect,
that their earliest impressions of good were associated
with the affectionate counsels of their departed father.
His was not the language of precept only,--that of his
strikingly consistent example was still more powerful.
It was impossible to observe from day to day the thankful, cheerful,
humble frame of mind which he so uniformly manifested,--his watchfulness to
check every rising of improper feeling,--and above all,
the deep reverence and filial love which pervaded his heart
towards the great Author of every mercy,--without being made
sensible of that blessed and all-pervading principle,
which regulated the daily tenor of his life.
His children at once loved and honoured him;
for while he possessed their entire confidence, and the fullest hold on their affections,
they knew that he was unflinching in the refusal of whatever he felt
to be inconsistent with his principles or their highest good.
Notwithstanding the kindness of his nature,
and the strength and warmth of his parental feelings,
his known firmness precluded all hope of inducing him to yield to their inclinations,
when these stood opposed to their eternal interests.
Many perhaps may have been more systematic in their instructions;
but few could keep more steadily or practically in view
the superior importance of heavenly things.

From their early years, he patiently laboured to imbue the minds of his children,
with the love and fear of the Almighty.
He instructed them diligently in the holy Scriptures;
and endeavoured to explain in a manner suited to their capacities,
the truths they contain.
He was also persevering in his efforts to exhibit to
them the example of the righteous of other generations:
and especially that exemplification of the fruits of his own principles,
which the lives of the early members of our Society so strikingly display.
For this purpose he set apart a portion of time daily,
in which he read to his family works of this description;
a practice that was continued up to the period
when his religious labours called him from them.
Perhaps some might be ready to think that such a
course would be found irksome by the young;
but certainly in the present instance the result was widely different,
and his children can now recall the feelings of solemn
interest and enjoyment that often attended these readings,
and the short period of quiet by which they were invariably followed.
It was also his custom each evening, when his children had retired to rest,
to visit their chambers,
and endeavour to direct their hearts to their great Creator and Preserver.
On these occasions, he would repeat, or teach them to repeat passages of Scripture,
or poetry of a devotional character, to which his own admonitions were frequently added;
and he generally closed these sweet and well remembered seasons with a solemn pause:
during which, doubtless,
his pious spirit was often engaged in committing them to the Lord.

As his children advanced towards maturity, instead of relaxing his watchful care,
he felt that there was need rather of redoubled
vigilance to shield them from surrounding danger.
Ever anxious for their best welfare, yet deeply sensible that through Divine grace alone,
their youthful minds must be awakened, quickened,
and enabled to lay hold of a Saviour`'s love;
he was earnest in imploring for them this heavenly gift,
and diligent in watching for opportunities to impress
upon them the importance of spiritual things.
One instance of the condescension of the Lord in hearing and
answering his prayers may be here introduced.
As his eldest son attained the age of manhood, earnest were the cravings of his father,
that the Lord would direct his heart "`into the love of God,
and into the patient waiting for Christ.`"
He knew well that to the natural man, the things of God must ever be a mystery;
and he longed that through submission to the operations of the
Spirit of truth they might be opened to his understanding.
Often with parental tenderness he silently watched the
opening convictions of his inquiring mind,
and as opportunities presented,
he laboured to explain to him the views he had himself received.

At one time the sentiments of his son on these all
important subjects were exceedingly unsettled,
and he passed through deep mental conflict before he
yielded to the light of Divine truth in his soul,
which dispelled the doubts and reasonings by which he was assailed.
It was at this period, that one evening his father and he being alone together,
they had much conversation on the points which
then pressed heavily on the mind of the latter.
Before retiring to rest, his father handed him the Bible,
and requested him to read a chapter:
he took the book and read the third chapter of Malachi.
Deep seriousness overspread his countenance,
and after a considerable time of silence he repeated,
'`The Lord whom ye seek shall suddenly come to his temple,
even the messenger of the covenant whom ye delight in;`"
--and he shall be "`like a refiner`'s fire,
and like fuller`'s soap,`" adding, '`yes, he will come into his own temple,
the temple of the heart, and there do his own work.
I never understood this chapter before, nor saw, as I now see it,
the spiritual nature of the gospel dispensation.`'
The impression thus made was not soon effaced;
and it was evident to his thankful and rejoicing parent,
that the prophetic declaration was indeed fulfilled in
his experience,--that the Lord had come into his temple,
and was there working to the purifying of his soul.
The change which gradually succeeded was most striking; clearly evincing to those around,
that the day had indeed dawned and the day star arisen,
in a heart long oppressed with darkness, and a prey to many doubts.
In reference to this period his father once remarked with much emotion,--"`this
kind can come forth by nothing but by prayer and fasting,`" intimating the long
continued exercise of soul through which he had been led on behalf of his son.

Two avenues to evil,
he guarded with especial jealousy in his domestic sphere,--the
introduction of books of an injurious tendency,
and the association which he allowed to his children.
With respect to reading,
he was liberal in supplying whatever he thought calculated to improve or expand the mind,
and furnish profitable exercise to the understanding;
but very few productions of a frivolous or hurtful
nature escaped the vigilance of his watchful eye.
On these occasions, he regarded not the inclinations of those he so tenderly loved;
and he has been known, when works that he disapproved had been lent to his young people,
to return them himself to the parties from whom they came,
accompanied by a frank avowal of his sentiments respecting them.
With regard to society for his family, his situation in a foreign country,
far separated from those of his own religious views,
would doubtless have appeared to many to present unusual difficulties.
These he endeavoured to obviate, by rendering home as pleasant and cheerful as possible,
and thus leaving his children little to desire beyond its precincts.
Perhaps few domestic circles ever presented a happier scene than his own,
while its links were permitted to remain unbroken.
Doubtless the result of such a system has been to make the changes and separations,
inevitable in a world of fluctuation and mutability,
fall heavily on the hearts of survivors;
but the shelter thus afforded to their inexperience,
and to the unfixed principles of early years, was an invaluable safeguard;
and they can now look back with grateful hearts
to the wisdom and care of their departed parent.
If his labours have not always been attended with adequate results,
his children can freely, though with shame acknowledge,
that the fault rested not with him but with themselves;
and as respects those who have been called from this state of probation,
the survivors are permitted to believe the counsels and
prayers of their pious father were blessed on their behalf,
and that they were made partakers of that redemption which is in Christ Jesus,
and favoured to know their robes washed and made white in His precious blood.
And how full of consolation is the belief, that their spirits are now united with his,
who so fondly and faithfully watched over their early years,--shielded them
from temptations to surrounding evil,--and turned their feet into the path
that leads to blessedness:--"`Therefore are they before the throne of God,
and serve him day and night in His temple:
and He that sitteth on the throne shall dwell among them.
They shall hunger no more, neither thirst anymore; neither shall the sun light on them,
nor any heat.
For the Lamb which is in the midst of the throne shall feed them,
and shall lead them unto living fountains of waters:
and God shall wipe away all tears from their eyes.`"



